### ISSUE TITLE
How to install search providers?

### ISSUE THREAD

**Issue by Fabian42** [linuxmint/cinnamon#8453] opened 2019-03-11 13:00 UTC
```
 * Cinnamon version 3.2.7
 * Distribution - debian 9.8
 * 64 bit
 ```

**Issue**

The cinnamenu settings say "No search provider extensions found", but I don't see how I would install the search providers. They're not in Synaptic, dragging from here to the settings window doesn't work (would be awesome), they're not in the extensions list, I see no readme anywhere here, …

I assume I have to put the files somewhere, but where?

(I'm talking about [these](https://github.com/linuxmint/cinnamon/tree/master/docs/search-providers-examples),)

**Comment by Odyseus** [comment] 2019-03-11 13:48
Hello, @Fabian42.

You can install search providers into `~/.local/share/cinnamon/search_providers`. The folder structure should look something like this:

```
[~]
└──.local
    └──share
        └──cinnamon
            └──search_providers
                └──apt@cinnamon.org
                └──calc@cinnamon.org
                └──chromium-history@cinnamon.org
                └──trackerprovider@cinnamon.org
                └──wikipedia@cinnamon.org
                └──yahoo@cinnamon.org
```

After installing search providers, Cinnamon needs to be restarted or the Cinnamenu applet reloaded for the search providers to appear in Cinnamenu's settings window.


The default Cinnamon menu applet also supports search providers, but they need to be enabled globally for them to be used by the default menu.

You can use the command line to enable search providers globally:

```shell
gsettings set org.cinnamon enabled-search-providers [\"calc@cinnamon.org\"]
```

Or dconf Editor (GUI):

![Screenshot-area-2019-03-11-104422](https://user-images.githubusercontent.com/3822556/54128430-d0713880-43ea-11e9-851b-d43d5ac93930.png)

**Comment by Fabian42** [comment] 2019-03-11 15:07
Great, works! This should be in some kind of readme or, even better, in a help text in the Cinnamenu settings.

My findings so far:
* The Wikipedia search results have no icon.
* The apt-get search results have a "forbidden" icon
* The calculator changes the results screen to only show the calculation and result, but there are still tooltips of other results and they can be navigated and selected with the keyboard.
* The Chromium history search provider does not work with Chrome (as expected, but it could have).
* I don't know what the "Tracker search" provider does. I haven't managed to find a search result from it.
* I didn't try Yahoo.

Should these be reported? The folder is called "example search providers", that sounds like they aren't meant as full products. But it can't hurt to fix bugs, right?

**Comment by Odyseus** [comment] 2019-03-11 16:21
> The Wikipedia search results have no icon.

That's because [its icon is hard-coded](https://github.com/linuxmint/cinnamon/blob/master/docs/search-providers-examples/wikipedia%40cinnamon.org/search_provider.js#L15) to an icon that exists in the Mint-X icon theme, shipped with Linux Mint distributions. You could simply change that path to an icon that exists in your system.

> The apt-get search results have a "forbidden" icon

The icons for this search provider results are extracted from [the `mintinstall` application](https://github.com/linuxmint/cinnamon/blob/master/docs/search-providers-examples/apt%40cinnamon.org/search_provider.js#L6). You could simply change it to Synaptic (`synaptic.desktop`) or any other application that you have installed in your system.

> The calculator changes the results screen to only show the calculation and result, but there are still tooltips of other results and they can be navigated and selected with the keyboard.

If that happens with Cinnamenu, report it in the [third-party applets repository](https://github.com/linuxmint/cinnamon-spices-applets/issues) (search existent issues first). I can't reproduce the behavior you describe using the standard Cinnamon menu.

> The Chromium history search provider does not work with Chrome (as expected, but it could have).

I imagine that changing all instances of **chromium** to **chrome** [in the search_provider.py file](https://github.com/linuxmint/cinnamon/blob/master/docs/search-providers-examples/chromium-history%40cinnamon.org/search_provider.py) ([here](https://github.com/linuxmint/cinnamon/blob/master/docs/search-providers-examples/chromium-history%40cinnamon.org/search_provider.py#L19) and [here](https://github.com/linuxmint/cinnamon/blob/master/docs/search-providers-examples/chromium-history%40cinnamon.org/search_provider.py#L58); also [here](https://github.com/linuxmint/cinnamon/blob/master/docs/search-providers-examples/chromium-history%40cinnamon.org/search_provider.js#L11)) might fix this. I can't be sure since I don't use neither of those web browsers.

> I don't know what the "Tracker search" provider does. I haven't managed to find a search result from it.

I have no idea. It may have something to do with music. The URLs found in its **search_provider.py** file (www.tracker-project.org) are all down.

> I didn't try Yahoo.

This one also works, but it has the same problem as the Wikipedia one (hard-coded path to an icon on the Mint-X icon theme).

---

Technically, none of these search providers are broken and serve perfectly well as examples. Although, I agree, the search providers system requires *some love* (better documentation, distribution agnostic icons, etc.). Cinnamon developers are aware of this, and they are constantly working on improving it.

**Comment by Fabian42** [comment] 2019-03-11 16:55
>I have no idea. It may have something to do with music. The URLs found in its search_provider.py file (www.tracker-project.org) are all down.
I just searched for the title of a music file and it found it, then I searched for the name of an image and it didn't find it. So that could be it.

**Comment by Fabian42** [comment] 2019-03-11 18:46
Thanks for your helpful replies!
1. I used this logo for Wikipedia, works well: https://upload.wikimedia.org/wikipedia/en/8/80/Wikipedia-logo-v2.svg
2. `synaptic.desktop` works well for apt.
3. Replacing all instances of "chromium" with "chrome" did not work, even though I thought it did, because first I matched bookmarks, then a window title :D "google-chrome-stable" also doesn't work.
4. I just found an image file by entering its name. So maybe the "tracker" thing is not just music. Maybe it's just regular file search, but I couldn't get it to reliably show me any file.
5. I now created [this report](https://github.com/linuxmint/cinnamon-spices-applets/issues/2361) for the calculator bug.
6. I've made [this pull request](https://github.com/linuxmint/cinnamon/compare/master...Fabian42:patch-1#diff-e3222d3807bcf1de774482b2ab0e27c7) to document how to install the search providers.
7. I made [this feature suggestion](https://github.com/linuxmint/cinnamon/issues/8455) for the missing icons.
8. I don't know how support "issues" are usually handled. Should it be closed now that I have an answer?
9. Do you know any other place where I can get search providers from? Is there a category in Synaptic or a "market" somewhere or a folder in the Cinnamon repository or…?

**Comment by Odyseus** [comment] 2019-03-11 21:05
> Replacing all instances of "chromium" with "chrome" did not work...

I tested it and it should be *google-chrome*, not just *chrome*. I edited my previous answer to not generate confusion. And here you have a functional example: [chrome-history@cinnamon.org.zip](https://github.com/linuxmint/cinnamon/files/2954104/chrome-history%40cinnamon.org.zip)

> I don't know how support "issues" are usually handled.

Yes, you can close the issue. I would also like to mention that these repositories aren't the place to look for support per se. When it comes to Cinnamon, you can ask questions in the [Linux Mint forums](https://forums.linuxmint.com/viewforum.php?f=208) and the IRC channel (irc://irc.spotchat.org/linuxmint-help) no matter the Linux distribution you are on (this is true for the IRC channel, I'm not entirely sure if the forums allow this---well, the worst that can happen is that you get banned LOL).

> Do you know any other place where I can get search providers from?

Not that I know of. Search providers are a kind of an *obscure* Cinnamon feature. And since they can only be used programmatically from other types of xlets (AFAIK), there aren't many places that you could find them, other than creating them yourself.

**Closed** 2019-03-11 21:42 UTC
