### ISSUE TITLE
Firefox 96 (customized to have no titlebar) resizes to a slightly smaller window after fullscreen

### ISSUE THREAD

**Issue by name-changer** [linuxmint/cinnamon#10655] opened 2022-02-05 10:23 UTC
Cinnamon 5.2.7
Mint 20.3, 64 bit
Nvidia GTX 960 with driver 470.86
Firefox 96.0.3

**Issue**
When Firefox 96 is customized to show no titlebar, it resizes to a slightly smaller window than it was before after going fullscreen and back. This happens with Firefox 96.0.x on Mint 20.3, and only when Firefox is customized to show no titlebar (left bottom checkbox in the FF-CustomizeScreen). 

**Steps to reproduce**
To replicate the bug, disable the titlebar in FF (click the menu button in FF, click 'More Tools' and choose 'Customize Toolbar', then disable the option bottom left), use a non-maximized Firefox-window and maximize it only vertically, so that you can see the desktop left and right of the window, but top and bottom are fully maxed out. Then go to fullscreen (either in a video or by maximising the window) and back to the previous state. Now the window is not vertically maximized anymore, there are a few pixels margin at the top and the bottom. 
When you continue to maximise and minimize the window there's a chance Cinnamon crashes and closes all windows. But I can't replicate that, and it's probably related to the resize-bug anyway.

**Expected behaviour**
The window should be restored to the size it had before going to fullscreen.

**Other information**
This doesn't happen when Firefox is customized to show a titlebar. It started with Mint 20.3 and FF 96.0. Before with Mint 20.2 and FF <= 95.x this worked fine.

The bug doesn't seem to be related to the theme. It occurs with the default Mint-Y themes, but also with a custom theme from github (Matcha-Dark-Azul). 
There are no errors logged in syslog or xsession-errors.

**Comment by mtwebster** [comment] 2022-02-05 14:49
Duplicate of https://github.com/linuxmint/muffin/issues/611 I think.

Firefox 95->96 saw some significant changes to how the window decorations work when the titlebar is disabled, revealing this bug.

**Closed by mtwebster** 2022-02-05 14:49 UTC

**Comment by name-changer** [comment] 2022-02-05 23:05
Agreed. Thanks!
