### ISSUE TITLE
'Window borders' theme not applied to certain preinstalled apps

### ISSUE THREAD

**Issue by graue70** [linuxmint/Cinnamon#8382] opened 2019-02-10 15:28 UTC
```
 * Cinnamon 4.0.9
 * Mint 19.1
 * 64 bit
 ```

**Issue**
Certain apps have a very different look and the theme is not applied. These are the apps I found so far:

- GNOME Disks
- Disk Usage Analyzer (baobab)
- Calculator

![screenshot from 2019-02-10 16-10-41](https://user-images.githubusercontent.com/23035329/52535591-a75c7a00-2d50-11e9-8264-5984eeb2e936.png)

**Steps to reproduce**
Go to 'Themes' and change the one for 'Windows borders' to 'Mint-Y-Dark' (or any other). Then open one of the apps mentioned above side-by-side with for example 'Nemo' to see the difference.

**Expected behaviour**
When I change a theme, I expect it to be applied to all programs and all windows.

**Other info**
This problem also occured in older Mint versions like 18 and 19.
This seems to have been reported in #5367, but I don't quite understand why nothing has been done about it since then.

**Comment by clefebvre** [comment] 2019-02-10 17:23
The apps you mention are CSD (Client Side Decorated) windows. This means they handle their titlebar themselves and it follows the GTK theme (as opposed to the titlebar ... i.e. metacity theme).

As such they're working as intended and as designed by their developers.

I'll close this because it's not a bug.

That said, note that we're hoping to discontinue support for titlebar themes, and use the GTK themes for all windows moving forward, so once this is done this inconsistency will eventually vanish.

**Closed by clefebvre** 2019-02-10 17:23 UTC
