### ISSUE TITLE
Background colour black behind window in external screen.

### ISSUE THREAD

**Issue by ZorencenR** [linuxmint/Cinnamon#7801] opened 2018-08-10 15:11 UTC
```
 * Cinnamon version: 3.8.8
 * Distribution: Mint 19
 * Graphics hardware: Intel Corporation HD Graphics 520
 * Linux Kernel: 4.15.0-30-generic
 * 64 bit
 ```

**Issue**

In the external screen when you try to move a windows this create behind this a background colour black until top. 

![img_20180810_094243](https://user-images.githubusercontent.com/9750729/43965486-fcb345cc-9c84-11e8-8328-aab9787dc183.jpg)
(I tried to take a picture with PrintPant but didn't works, for it I taked a picture with my mobile phone)

**Steps to reproduce**

- Start you laptop without connect an external screen.
- login.
- Connect an external screen. 
- Open an application and move this to external screen.

**Expected behaviour**
When you move the Window in the external screen this create a background colour black behind the window.

**Other information**
Don't open more windows, only use a one window.

**Comment by ZorencenR** [comment] 2018-08-25 21:08
I recorded this video https://www.youtube.com/watch?v=9TXrLrI4MWQ

The "solution" is restart Linux Mint whit external screen connected.

**Comment by germanfr** [comment] 2018-08-25 21:12
This is a duplicate of #7665

**Comment by JosephMcc** [comment] 2018-08-25 21:14
Thanks @germanfr

**Closed by JosephMcc** 2018-08-25 21:14 UTC
