### ISSUE TITLE
Closing application sometimes leaves empty space in tray icon bar

### ISSUE THREAD

**Issue by orschiro** [linuxmint/Cinnamon#7226] opened 2018-01-24 12:01 UTC
```
orschiro@x230 ~ $ inxi -Sz
System:    Host: x230 Kernel: 4.13.0-31-generic x86_64 (64 bit)
           Desktop: Cinnamon 3.6.7  Distro: Linux Mint 18.3 Sylvia
 ```

Doesn't happen always. Cannot tell when and why it works and when/why not.

Tested with closing Skype and Hexchat. 

![image](https://user-images.githubusercontent.com/170947/35331172-a265099e-0106-11e8-97db-b503a0db7897.png)

**Comment by icarter09** [comment] 2018-07-10 03:14
Cinnamon 3.8.7
Linux Mint 19 64bit
AMD Radeon 6520G

@orschiro a couple questions....
 1. Have you upgraded to the latest version of Cinnamon? If so, does this issue still persist?
 2. Is the problem only occurring with Skype or Hexchat? I attempted this with several applets in the tray icon bar (along with Hexchat), but was unable to reproduce the issue.

**Comment by orschiro** [comment] 2018-07-10 05:19
@icarter09 I am sorry. No longer with Linux Mint. Hope someone else can
jump in and help reproduce!

**Comment by JosephMcc** [comment] 2018-07-10 09:38
Since there was only a single reporter who an no longer verify this, I'm going to go ahead and close it.

**Closed by JosephMcc** 2018-07-10 09:38 UTC
