### ISSUE TITLE
Cinnamon Volume Control using a lot of Pulse Audio connections

### ISSUE THREAD

**Issue by ukoda** [linuxmint/cinnamon#12180] opened 2024-05-03 03:50 UTC
### Distribution

Linux Mint 21.3 - from EDGE ISO

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

i7-1355U with Intel Iris Xe Graphics

### Frequency

Always

### Bug description

After running for a long time Pulse Audio stopped accepting connections.  Rebooting resolved the problem but using "pactl list clients" showed multiple "Cinnamon Volume Control" connections with the number increasing over time.  After an uptime of 28 hours I am seeing 11 of these connections.  I am assuming given enough time they will consume all Pulse Audio connections.  Unsure what the "Cinnamon Volume Control" actually is and searching has not helped.  I have the default sound applet on the default panel and an external USB volume control knob.

I realise this may be a Pulse Audio or Gnome issue but I'm starting here given the application name reported.

### Steps to reproduce

Boot and run system as normal.  Periodically use "pactl list clients | grep application.name" to check on how many applications are using Pulse Audio.

### Expected behavior

I would expect Pulse Audio client connections to be stable over time depending on what apps I was running.  I would expect to only see one or two instances of the "Cinnamon Volume Control" in the client connections.

### Additional information

An snippet of the "pcatl list client" output for one connection:
```
Client #35999
	Driver: protocol-native.c
	Owner Module: 12
	Properties:
		application.name = "Cinnamon Volume Control"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.id = "org.gnome.VolumeControl"
		application.icon_name = "multimedia-volume-control"
		application.version = "6.0.0"
		application.process.id = "1858"
		application.process.user = "david"
		application.process.host = "shigoto"
		application.process.binary = "cinnamon"
		application.language = "en_NZ.UTF-8"
		window.x11.display = ":0"
		application.process.machine_id = "946eaeb097784e6bbdfdac10384010a0"
		application.process.session_id = "c2"
```

**Comment by ukoda** [comment] 2024-05-08 02:32
I got five days out of it before the problem reoccurred.  Tried restarting Pulse Audio with no luck as the "Cinnamon Volume Control" connections remained at about 54.  Maybe I'm not restarting Pulse Audio correctly.  Regardless I had to reboot agaib.  I'm running Linux, not Windows, so would prefer a solution that did involve a reboot.  Next time I will try to force a Cinnamon restart without killing all my apps etc.

**Comment by claudiux** [comment] 2024-05-08 02:49
Using pipewire instead of pulseaudio, I get that:
```
$ pactl list clients | grep "application.name"
		application.name = "pipewire"
		application.name = "WirePlumber"
		application.name = "WirePlumber [export]"
		application.name = "Cinnamon Volume Control Media Keys"
		application.name = "xdg-desktop-portal"
		application.name = "speech-dispatcher-dummy"
		application.name = "Cinnamon Volume Control"
		application.name = "Radio Volume Control"
		application.name = "Cinnamon Volume Control"
		application.name = "Firefox"
		application.name = "pactl"
```
That seems normal.

**Comment by ukoda** [comment] 2024-05-08 03:52
@claudiux Would 54 volume controls be consider normal?  Basically it grows by about 10 a day until it breaks my system.  I'm still wondering what "Cinnamon Volume Control" actually is?  I am assuming it is not the one on the default panel as there is only one of those.

**Comment by claudiux** [comment] 2024-05-08 09:02
It seems to me that one "Cinnamon Volume Control" is used to control the output device, and another one for the input device.

**Comment by frantzmff** [comment] 2024-05-09 01:52
>  Would 54 volume controls be consider normal? Basically it grows by about 10 a day until it breaks my system. I'm still wondering what "Cinnamon Volume Control" actually is? I am assuming it is not the one on the default panel as there is only one of those.

I am also dealing with the exact same bug. It appears the "Cinnamon Volume Control" is the Sound applet which can be removed from the panel. Note after removing the Sound applet, I had to restart Cinnamon to kill all of these orphaned volume connections by running "cinnamon --replace" from the command line.  I think you can use the PulseAudio Volume Control instead if needed.

Note I started a long thread about this issue here: https://forums.linuxmint.com/viewtopic.php?p=2465446#p2465446

**Comment by ukoda** [comment] 2024-05-09 05:35
@frantzmff Thanks for that.  Since I have a physical USB volume know I have simply removed the sound applet from the panel.  It looks good so far.  If it stays ok I could close this issue with your post as the solution.  However it is really only a work around, so I'm sure if closing it is the right thing to do.  While the problem is solved for me it is still going to bite other people until the root cause is found and fixed.

**Comment by DirkHaar** [comment] 2024-05-09 10:32
can you change the title, Pulase to Pulse?

**Comment by frantzmff** [comment] 2024-05-09 13:51
> If it stays ok I could close this issue with your post as the solution. However it is really only a work around, so I'm not sure if closing it is the right thing to do. While the problem is solved for me it is still going to bite other people until the root cause is found and fixed.

@ukoda Please don't close it. This has been driving my crazy for months. It is a bug that needs to be fixed.

**Comment by ukoda** [comment] 2024-05-09 21:29
@frantzmff It is 16 hours now and no bogus pulse audio connection, just what you would normally expect.  So it looks like no more downtime dealing with it.  Yes, I decided to leave the issue open as not everyone has the luxury of a hardware volume control and it should be fixed.

**Comment by frantzmff** [comment] 2024-05-09 22:44
@ukoda Yes, I am currently over 20 hours with no issues. 48 hours is about the longest I lasted without audio breaking when the Cinnamon Volume Control was running.

There is a software alternative, the PulseAudio Volume Control, but it is an over-engineered, multi-tabbed monstrosity. The Cinnamon Volume Control should be fixed.

**Comment by claudiux** [comment] 2024-05-09 23:14
PulseAudio will be replaced with Pipewire in LM22. There is a way to do that in LM21.3: https://linux.claudeclerc.fr/linuxaddict:astuces:pipewire (French language but you can translate it).

**Comment by frantzmff** [comment] 2024-05-10 00:23
@claudiux Thanks. Now that I seem to have this working, I'd rather not mess around with Pipewire.

**Comment by Qwinn1** [comment] 2024-05-14 00:00
> PulseAudio will be replaced with Pipewire in LM22. There is a way to do that in LM21.3: https://linux.claudeclerc.fr/linuxaddict:astuces:pipewire (French language but you can translate it).

This problem has been plaguing me too.  And in my desperate attempt to stop it, I went ahead with those directions and replaced pulseaudio with pipewire.

Cinnamon still spawns multiple connections.  Doesn't fix the issue at all.

The good news is, I did find an easy way to deal with it.  Just restart cinnamon.  And the only thing you need to do for that is to hit Control-Alt-Escape.  That's it.  All the extra connections immediately disappear per `pactl list clients`

Still hope this gets fixed though.  It remains an annoying bug regardless.

**Comment by Qwinn1** [comment] 2024-05-14 00:14
I just figured out what causes this issue.

Most of my boxes are on a KVM switch.  And every single time I switch my KVM to a box, it causes that box to spawn another Cinnamon Volume Control connection.  Easy to reproduce, once you know what's causing it.

**Comment by frantzmff** [comment] 2024-05-14 02:34
@Qwinn1 I use a KVM on my computer but switching is **not** spawning new Cinnamon Volume Control connections for me. I just tested switching 5 times. 

A separate issue is that I am noticing Spotify pulse audio connections slowly creeping up over time.

**Comment by ukoda** [comment] 2024-05-14 09:42
For the sake of completeness I should mention I also use a KVM, but have not changed the system selection with it in a while.  The extra Cinnamon Volume Controls connections were appearing even while the KVM was not changing.

**Comment by studog-github** [comment] 2024-06-08 15:09
I am experiencing this issue of audio instability.  
  
Relatively fresh Linux Mint 21.3 install (about a month old).  
No KVM.  
I do have two desktops that share monitors connected via DP and HDMI though, and switch between them.  
I have a bluetooth dongle.   
I have the "too many connections" log messages from pulseaudio.  
  
Restarting Cinnamon restores sound.  
  
I'm a programmer. Happy to try things to help debug.

**Comment by frantzmff** [comment] 2024-06-08 16:20
@studog-github While waiting for a proper solution, I suggest removing the Sound applet from the desktop panel.  This Sound applet, a.k.a. the "Cinnamon Volume Control," is the main culprit for me. I also have Bluetooth disabled but I'm unsure how much of an issue it is. 

The Spotify desktop app also causes the issue. I just restart Spotify periodically to free up its connections.

**Comment by claudiux** [comment] 2024-06-08 18:34
@frantzmff I suggest you to try the `sound150@claudiux` applet: https://cinnamon-spices.linuxmint.com/applets/view/306 

Using it with Pipewire, I often obtain:
```
$ pactl list clients | grep "application.name"
		application.name = "WirePlumber"
		application.name = "WirePlumber [export]"
		application.name = "pipewire"
		application.name = "Cinnamon Volume Control Media Keys"
		application.name = "Sound150 Volume Control"
		application.name = "Radio Volume Control"
		application.name = "xdg-desktop-portal"
		application.name = "speech-dispatcher-dummy"
		application.name = "mpv"
		application.name = "pactl"
```

**Comment by frantzmff** [comment] 2024-06-08 20:22
@claudiux  I just installed Sound150 and I already see 2 connections. We'll see how it goes:

	application.name = "Sound150 Volume Control"
	application.name = "Sound150 Volume Control"

**Comment by ukoda** [comment] 2024-06-08 20:26
I would agree with @frantzmff that removing the default "Cinnamon Volume Control" fixes the problem.  My system has been stable since. @claudiux thanks for the suggestion of your Sound150.  I have installed it.  It looks good and it is nice to have a volume control on the desktop again.  It has created three entries when listed with pactl but that is fine if it stays at that.  Will let it run and see if it stays at that over time.  If it does I will recommend it as the solution.

**Comment by frantzmff** [comment] 2024-06-08 22:30
Sound150 now has 7 connections. It has the same issue as the "Cinnamon Volume Control" when it comes to PulseAudio. I am uninstalling it.

**Comment by claudiux** [comment] 2024-06-08 22:51
https://github.com/orgs/linuxmint/discussions/462

**Comment by Qwinn1** [comment] 2024-06-08 23:06
> https://github.com/orgs/linuxmint/discussions/462

I previously replaced pulseaudio with pipewire on one of my boxes hoping it would fix the issue for the original Cinnamon Volume Control applet, but it doesn't.  Same issue, just slightly different (and redder) messages in the system journals.

Do you have reason to believe that your applet + pipewire will not have this issue, when every other combination does?

**Comment by claudiux** [comment] 2024-06-09 00:03
Multiple `application.name = “Sound150 Volume Control”` occur only when the `sound150@claudiux` applet is reloaded. I think I've found the bug. I'll make a PR soon.

**Comment by ukoda** [comment] 2024-06-09 00:12
@claudiux sounds promising as I was seeing the same as @frantzmff with extra instances appearing while working on the development of a program that uses pulse audio.  Please post an update when we should try sound150@claudiux again.

**Comment by claudiux** [comment] 2024-06-09 00:24
v6.17.1 of `sound150@claudiux` is available. Please try it. After the update, reload Cinnamon.

If it works as you expect, I will also fix the `sound@cinnamon` applet.

If not, then the bug comes from pulseaudio/pipewire.

**Comment by claudiux** [comment] 2024-06-09 00:53
I'm waiting for your feedback before publishing the fix for the `sound@cinnamon.org` applet.

**Comment by frantzmff** [comment] 2024-06-09 03:20
@claudiux I have the latest version (6.17.1) of Sound150 installed. We'll see how it goes. Thanks.

For anyone trying this, the quickest way to restart Cinnamon seems to be CTL+ALT+ESC.

**Comment by ukoda** [comment] 2024-06-09 10:23
@claudiux I have been running your update version (6.17.1) of Sound150 for a few hours now and so far it is looking good.  Has remained stable with only a single copy running.  Thank you for following this up.

I will give a bit more testing time and wait for feedback from @frantzmff  before doing a comment to close this issue with.

**Comment by Qwinn1** [comment] 2024-06-09 10:36
I can confirm, as on my system the issue is easily reproducible with my KVM.  Switching back and forth, there are no additional instances of Sound150 Volume Control being created.  Fantastic!  This is the only significant bug I'm experiencing in Linux Mint so if today is that gets fixed, then today is a great day.  Thanks claudiux!

**Closed** 2024-06-09 11:51 UTC
Labels: BUG

**Comment by claudiux** [comment] 2024-06-09 11:57
If you like the `sound150@claudiux` applet, please increase its score on https://cinnamon-spices.linuxmint.com/applets/view/306

**Comment by ukoda** [comment] 2024-06-09 12:00
> If you like the `sound150@claudiux` applet, please increase its score on https://cinnamon-spices.linuxmint.com/applets/view/306

Done

**Comment by frantzmff** [comment] 2024-06-09 14:33
After 11+ hours of testing, Sound150 still has only one pulseaudio connection. Looking very good so far.

**Comment by studog-github** [comment] 2024-06-09 14:58
Thanks @claudiux . I checked the commits (for `sound@cinnamon.org` and your `sound150@claudiux`); it's a clear fix.  
  
I don't recall ever seeing a spice/applet "new version available" notification, and, I discovered your [Spices Update](https://cinnamon-spices.linuxmint.com/applets/view/309), so I've installed that to watch for when the fix makes it to my pc.  
  
Repeated a few times already, but I'll repeat again for signal-boost: **Restarting Cinnamon clears the orphaned connections. `ctrl-alt-escape` is the shortcut for that.**  
  
In my case, bluetooth is contributing to the issue by causing (exact mechanism undetermined) the bug in `sound@cinnamon.org` to occur. I see the list of Pulse Audio clients growing: `pactl list clients | grep "\.name"`. Since yesterday my client list has grown from 7 (including two _usual_ `sound@cinnamon.org` clients) to 28. All of the _extra_ clients are `application.name = "Cinnamon Volume Control"`.
  
These two facts allow a workaround by checking for the growing problem and restarting Cinnamon to avoid hitting the crash. I'm assuming the `(64)` in the log messages is the max number of clients allowed. The math `(64 - 7) / 21 per day` works out to a crash for me every 2.7 days. The growth rate should vary depending on bluetooth usage, but, yesterday was typical for me; my bluetooth usage is my wireless headphones.

**Comment by claudiux** [comment] 2024-06-09 21:38
The applet `sound@cinnamon.org` will be updated with the next Cinnamon update (6.2 in LM22?).

If you use `sound150@claudiux`, you must remove `sound@cinnamon.org` from the panel.

Version 6.17.1 of `sound150@claudiux` is available (right-click on this applet and select About... to find out which version is installed). With Spices Update you can force the installation of the latest version of an applet by checking its two boxes in the Applets tab of Spices Update and then clicking Refresh).

I don't have any bluetooth headphones to test with, sorry.
