### ISSUE TITLE
Fonts disappearing from panel and menu on resume from sleep

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/Cinnamon#5686] opened 2016-09-14 07:44 UTC
I'm running Linux Mint 18 with cinnamon 3.0.7+sarah

And every _now and then_ when my laptop resumes from sleep, all the fonts are gone from the panel.

You only see a shadow of the fonts, and when the mouse cursor moves over the active programs, the shadow of the fonts disappears too.

![image](https://cloud.githubusercontent.com/assets/1702193/18503620/3c4ac264-7a5e-11e6-9800-02978f273fec.png)

_In this image you see that only a shadow is left. I moved the mouse over "Chrome" and the shadow also disappeared._

The font disappears from the menu too.

![image](https://cloud.githubusercontent.com/assets/1702193/18503744/eaf74fbc-7a5e-11e6-988e-a00b55b753e7.png)

_Opened menu after resume from sleep._

Interestingly, only certain letters appear in the input box.

![image](https://cloud.githubusercontent.com/assets/1702193/18503806/2d6cb882-7a5f-11e6-98a6-43249c5a85a7.png)

_Typed in: "abcdefghijklmnopqrstuvwxyz"._

_Sometimes_ the run dialog (alt+f2) shows the same behavior as the input box from the menu. However, not now.

---

I've seen this behavior every now and then when resuming from sleep for a while now. But since it's not consistent, not guaranteed reproducible, I thought it wouldn't make sense to report this vague issue, and assumed it would probably be fixed in some update. However, it still isn't, so... I'm hoping this report is of some use.

Luckily, the font __does not__ disappear from software like nemo.

**Comment by Redsandro** [comment] 2016-09-17 22:10
Hmm, let's pick the 5G network. I just have to find it in this list.

![image](https://cloud.githubusercontent.com/assets/1702193/18611241/c4def8ca-7d33-11e6-858a-c47bc0635669.png)

---

I'm surprised not more people have stepped forward with the same problem.
What have I done that is unique, apart from placing my panel at the top? Probably something. I have no idea in which direction to think for stuff that might be related.

**Comment by ageorgop** [comment] 2016-09-30 02:54
I am seeing the same issue here if it makes you feel any better :)
![screenshot from 2016-09-29 19-53-26](https://cloud.githubusercontent.com/assets/871561/18979301/748754cc-867e-11e6-9725-4cae62849566.png)

**Comment by Redsandro** [comment] 2016-09-30 08:59
@ageorgop Ah, thank you! Now I know I didn't mess something up in a unique way!

**Comment by rik-shaw** [comment] 2016-10-26 04:50
This seems like a duplicate of #5607

**Comment by feren** [comment] 2016-10-26 08:32
@Redsandro I already reported it.
https://github.com/linuxmint/Cinnamon/issues/5607

**Closed** 2016-10-26 08:53 UTC
Labels: BUG
