### ISSUE TITLE
Keyboard shortcuts with Ctrl-Shift-<Symbol> no longer work, but respond to Ctrl-<Number>

### ISSUE THREAD

**Issue by kmorton** [linuxmint/cinnamon#5419] opened 2016-07-03 02:31 UTC
**Goal:**
Assign "Ctrl-Shift-1" as a keyboard shortcut for a program.

**Problem:**
The keyboard shortcut is assigned as "Ctrl-!" but does not respond to "Ctrl-Shift-1", however, it does respond to "Ctrl-1".
The same is true of other numbers and symbols:
- "Ctrl-Shift-`" (backtick) does not work, but the shortcut works when "Ctrl-`" is pressed.
- "Ctrl-Shift-2" does not work, but the shortcut works when "Ctrl-2" is pressed.

**Steps to reproduce:**
1. System Settings > Keyboard > Shortcuts > Custom Shortcuts
2. Add custom shortcut
3. Fill out name and command, e.g. Terminal, gnome-terminal
4. Double click first slot under Keyboard bindings section
5. Press "Ctrl-Shift-1"
6. Observe that the shortcut is set to "Ctrl-!"
7. Press "Ctrl-Shift-1"...nothing happens
8. Now press "Ctrl-1"...gnome-terminal launches!

**Other notes:**
- Issue in Mint 18 with Cinnamon 3.0.6. This previously worked in Mint 17.3
- "Ctrl-1" and "Ctrl-Shift-1" can be assigned to different shortcuts. Pressing "Ctrl-1" appears to activate the "Ctrl-Shift-1" shortcut

**Comment by kmorton** [comment] 2016-07-03 14:15
**Workaround:**

- Open dconf Editor 
- Navigate to "org > cinnamon > desktop > keybindings > custom-keybindings > custom<#>"
- Change the binding value
  - From: "\['\<Primary\>exclam'\]"
  - To: "\['\<Primary\>\<Shift\>1'\]" (or to "\['\<Primary\>\<Shift\>exclam'\]")
- Restart cinnamon (press Alt-F2, press "r", press Enter)
- Open "System Settings > Keyboard > Shortcuts > Custom Shortcuts" and notice that the keyboard binding for the shortcut is set to "Shift-Ctrl-1".

**Comment by mbolivar** [comment] 2017-02-13 03:56
This may be due to different behavior when using right or left shift. I'm running 3.2.8-1 on Arch, and I noticed the following today, which reproduces every time on my machine.

1. Open System Settings -> Keyboard -> Layouts, click "keyboard" symbol to bring up the "Keyboard Layout" window which shows which key events are generated

2. Press Control - left shift - S. Note that only control and left shift show up as pressed (expected behavior would be for all three keys to show up pressed)

3. Press Control - right shift - S. Note that this time, all three keys are shown pressed.

This prevents "save as" from working properly in some applications. Pressing left shift before control doesn't help. A fix would be nice.

**Comment by solson** [comment] 2017-07-14 20:28
This is still a problem for me in Cinnamon 3.2.7.

**Comment by mtwebster** [comment] 2017-07-14 20:47
Thanks for bumping, I missed closing this - should be fixed by https://github.com/linuxmint/Cinnamon/commit/34f4699dae205e2f6b79ed44d3c1602a02464a59

**Comment by solson** [comment] 2017-07-14 20:51
Cool, thanks for fixing!

**Closed** 2019-12-04 03:27 UTC
Labels: BUG
