### ISSUE TITLE
ThinkPad L15 Debian & Ubuntu HDMI Port not working with Intel Iris XE

### ISSUE THREAD

**Issue by marius1904** [linuxmint/cinnamon#11816] opened 2023-08-08 04:53 UTC
### Distribution

Debian 12 Bookworm

### Package version

Cinnamon 5.6.8

### Graphics hardware in use

Intel Iris XE

### Frequency

Always

### Bug description

Hello,

I have a ThinkPad L15 Gen4.
i7-1355U with Intel Iris Xe Graphics
64 GB RAM

Debian 12 & Ubuntu 22.04 for Testing

Kernel 5.15.0-67-generic

HDMI output for other Display with HDMI works if using Windows (I have the same issue with an exactly same Laptop)

but it wont work with:
Ubuntu 22.04
Debian 12 Bookworm

I tested the older BIOS and the new one but nothing did change. 
I used different Displays but it didnt change anything.
I also tried different cables -> same Problem
With Gnome -> same Problem

I think the issue is because of the Linux Intel Iris GPU driver.

Debian and Ubuntu tell me that it is connected, but it wont turn on at any resolution etc.

Here some Information

$ grep . /sys/class/drm/*/status
/sys/class/drm/card0-DP-1/status:disconnected
/sys/class/drm/card0-DP-2/status:disconnected
/sys/class/drm/card0-DP-3/status:disconnected
/sys/class/drm/card0-DP-4/status:disconnected
/sys/class/drm/card0-eDP-1/status:connected
/sys/class/drm/card0-HDMI-A-1/status:connected

$ inxi -bG
System:
  Host: debian-thinkpad Kernel: 6.1.0-10-amd64 arch: x86_64 bits: 64
    Desktop: Cinnamon v: 5.6.8 Distro: Debian GNU/Linux 12 (bookworm)
Machine:
  Type: Laptop System: LENOVO product: 21H3S03700 v: ThinkPad L15 Gen 4
    serial: <superuser required>
  Mobo: LENOVO model: 21H3S03700 v: SDK0T76530 WIN
    serial: <superuser required> UEFI: LENOVO v: R24ET29W (1.12 )
    date: 06/16/2023
Battery:
  ID-1: BAT0 charge: 58.7 Wh (100.0%) condition: 58.7/57.0 Wh (103.0%)
CPU:
  Info: 10-core (2-mt/8-st) 13th Gen Intel Core i7-1355U [MST AMCP]
    speed (MHz): avg: 2252 min/max: 400/5000:3700
Graphics:
  Device-1: Intel Raptor Lake-P [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: Luxvisions Innotech Integrated RGB Camera type: USB
    driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915 resolution:
    1: N/A 2: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 22.3.6 renderer: Mesa Intel Graphics (RPL-P)
Network:
  Device-1: Intel driver: iwlwifi
  Device-2: Intel Ethernet I219-V driver: e1000e
Drives:
  Local Storage: total: 953.87 GiB used: 325.26 GiB (34.1%)
Info:
  Processes: 347 Uptime: 12h 25m Memory: 62.48 GiB used: 6.96 GiB (11.1%)
  Shell: Bash inxi: 3.3.26

I really hope anyone can help :)

### Steps to reproduce

Just connecting any HDMI Output over the inbuilt HDMI Port when using Debian or Ubuntu and the connected Display wont turn on (Inbuilt Monitor turns off for a second like if it tries to connect, disabling it doesnt do anything)

### Expected behavior

connected Display should turn on normal like in windows

**Comment by marius1904** [comment] 2023-08-08 05:58
i just realized that the Problem only appears if i connect it to our HP 4k Z-Series Monitors, so looks like a Problem with Linux and HP.

**Comment by rcalixte** [comment] 2023-08-08 12:10
The ThinkPad L15 Gen 4 was announced in February 2023 and released in May 2023. It is very likely that you will need a newer kernel. If you are running Debian 12 still, you can try with the 6.4.x kernel available in the testing or unstable branches if you are comfortable doing so or compiling a newer kernel manually yourself. You can also wait for the next LTS kernel to be available in Debian stable backports in about 6 months or so if this missing functionality isn't urgent for you right now.

As you correctly pointed out, this is not a bug with Cinnamon or that Cinnamon can resolve. A newer kernel will hopefully eventually work with all of your hardware needs.

**Closed by rcalixte** 2023-08-08 12:10 UTC
