### ISSUE TITLE
Graphics issues after restart with laptop and external display

### ISSUE THREAD

**Issue by vpal** [linuxmint/cinnamon#9402] opened 2020-06-28 18:12 UTC
```
 * Cinnamon version (cinnamon --version)
   Cinnamon 4.6.6

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
   Linux Mint 20

 * Graphics hardware *and* driver used
   VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)

 * 32 or 64 bit
   64 bit

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
   [logs.zip](https://github.com/linuxmint/cinnamon/files/4842784/logs.zip)
```

**Issue**

On a Dell Latitude E5550 with a Dell external monitor attached via DVI.
Both displays have the same 1920x1080 resolution.
External display is configured so that the laptop display is disabled and only the external display is enabled as primary.

After Laptop restart login works.
After login the desktop background is black and there is constant flickering in some randomn areas of the display especially when moving the mouse around.
It is possible to open apps like terminal, but NOT able to open Cinnamon related apps like Display Manager.
Selecting the Display app it from the menu just does not start the app.

Cinnamon restart with "Alt + F2: r " does not solve the issue.

To fix the issue I plugged out the DVI cable and restarted the machine.
It starts on the Laptop display.
Then I plugged in the DVI cable, the external display was recognized and used as primary and the laptop display was powered off according to the confuguration before the restart.
After plugging back the cable everything is working as expected.

It seems like suspend also does not trigger this issue.

**Steps to reproduce**

Setup: laptop with external display.
Configure: laptop display is disabled, external display is enabled and is primary
Restart the laptop and log in.

**Expected behaviour**
Cinnamon works with mentioned setup after restart.

**Other information**
None.

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by vpal** [comment] 2020-06-28 18:24
[logs.zip](https://github.com/linuxmint/cinnamon/files/4842784/logs.zip)

**Comment by kkittykait** [comment] 2020-06-28 19:34
possibly related?

https://github.com/linuxmint/cinnamon/issues/9401 (this one is a critical segfault in muffin)

I also had display artifacts with a VGA external plugged in during the live image boot, it was flickering and tearing like crazy and had to disconnect that during install

**Comment by vpal** [comment] 2020-06-28 21:39
@kkittykait Is there a way I colld verify if this is the same issue?

**Comment by kkittykait** [comment] 2020-06-29 11:26
well, they're both related in the sense of they involve an external display and one set to inactive

**Comment by Betalord** [comment] 2020-06-29 14:30
I can confirm I had similar (the same) problem with my Mint 20 on Lenovo ThinkPad P51. When I first booted it up (from USB key), the screen would flicker like crazy, after a minute or so it would start showing some random pixels and areas from my previous boot of Windows 10 (like parts of windows and random stuff), so I didn't see any more of the Mint desktop. I opened my lid, and then it started working again. Note that I never open my lid though, since I have a monitor attached to my laptop so I don't need it.

**Comment by yigitdnz** [comment] 2020-06-30 09:39
I am having same problem on my laptop with Arch Linux and Cinnamon 4.6.6. When I start the computer with laptop screen off and external monitor on, the same thing people explained above happens. When I unplug and replug the HDMI cable, it works without problem until I reboot again.

**Comment by vladimir-didenko** [comment] 2020-06-30 13:20
It is probably duplicate of https://github.com/linuxmint/cinnamon-desktop/issues/151. You could verify it downgrading cinnamon-desktop package to 4.6.1 (if possible).

**Comment by yigitdnz** [comment] 2020-06-30 14:19
Downgrading cinnamon-desktop to 4.6.0 fixed the issue. (didn't have 4.6.1 as an option)

**Comment by gusbrs** [comment] 2020-07-01 12:07
I'd like to report I have what's likely the same issue, for a very similar setup.

As to setup:
I also use a Laptop (Dell Inspiron N4050), with a Dell external monitor (P2717H) connected through an HDMI cable. Same versions of Mint (20) and Cinnamon (4.6.6). I also set up things so as to disable the laptop monitor and use the external one instead.

As to the issue:
For me as well, as long as the display settings are made within the session, all works fine. But as they are reapplied *during login* they don't. The background is stretched wide, an there is a lot of flickering all around, to the point of the desktop being unusable.

I think a couple of pictures might illustrate what I meant by "the background is stretched wide" (sorry, made with external device). The fist one is the desktop immediately after login:

![P1000208](https://user-images.githubusercontent.com/19410606/86241047-a06a1d80-bb78-11ea-9b5d-123e64a2a2c7.JPG)

The second, with workspaces exposed:

![P1000209](https://user-images.githubusercontent.com/19410606/86241141-ca234480-bb78-11ea-8bb2-50cf7f590587.JPG)

On the second one I had also tried to open "Display", it did, but was not accessible from the desktop (it was "to the right"). But it can be accessed with the workspaces exposed (the OP can confirm if this is the same for them).

Curiously, the panel and menu are not stretched, only the desktop background. And only the width dimension.

Current workaround:
Simply unplug the external monitor cable and replug it. And things get back to where they should.

But, of course, I also would like not to need this workaround.

If any other info is required, please let me know.

**Comment by mtwebster** [comment] 2020-07-01 12:32
Hi, can I get some more info from all of you please:

- output of  `xrandr --verbose` both while everything is 'working' and then also when 'broken'.
- contents of cinnamon-monitors.xml file in ~/.config if it exists, and contents of monitors.xml if it exists
- output of `inxi -G`

Is anyone *not* on a laptop?  Specify if this is an 'optimus' laptops (having both a discrete nvidia as well as built-in intel), do you run in hybrid mode via bios settings, or discrete only.  If in hybrid, do you run in performance or intel mode (or on-demand)?

Thanks

**Comment by yigitdnz** [comment] 2020-07-01 13:17
I'm on a 13'' Samsung Ultrabook with HD4000 graphics card. 


[xrandr output - working.txt](https://github.com/linuxmint/cinnamon/files/4858073/xrandr.output.-.working.txt)
[xrandr output - broken.txt](https://github.com/linuxmint/cinnamon/files/4858074/xrandr.output.-.broken.txt)
[cinnamon-monitors.xml.txt](https://github.com/linuxmint/cinnamon/files/4858075/cinnamon-monitors.xml.txt)
[output of inxi -G.txt](https://github.com/linuxmint/cinnamon/files/4858076/output.of.inxi.-G.txt)

**Comment by gusbrs** [comment] 2020-07-01 13:18
Hi @mtwebster , thank you for looking into this.

Regarding your questions:

> output of xrandr --verbose both while everything is 'working' and then also when 'broken'

[xrandr-broken.txt](https://github.com/linuxmint/cinnamon/files/4858030/xrandr-broken.txt)
[xrandr-working.txt](https://github.com/linuxmint/cinnamon/files/4858031/xrandr-working.txt)

> contents of cinnamon-monitors.xml file in ~/.config if it exists, and contents of monitors.xml if it exists

[cinnamon-monitors.txt](https://github.com/linuxmint/cinnamon/files/4858055/cinnamon-monitors.txt) (renamed, to be attachable)

`find ~ -name "monitors.xml"` returns no results.

> output of inxi -G

[inxi.txt](https://github.com/linuxmint/cinnamon/files/4858064/inxi.txt)

> Specify if this is an 'optimus' laptops (having both a discrete nvidia as well as built-in intel), do you run in hybrid mode via bios settings, or discrete only. If in hybrid, do you run in performance or intel mode (or on-demand)?

Sorry, I don't really know how to answer. As far as I know, mine is an oldish laptop with just the built-in graphics card, and no nvidia. But I can check things if you give me the directions.

**Comment by kkittykait** [comment] 2020-07-01 13:58
> Hi, can I get some more info from all of you please:
> 
> * output of  `xrandr --verbose` both while everything is 'working' and then also when 'broken'.
> * contents of cinnamon-monitors.xml file in ~/.config if it exists, and contents of monitors.xml if it exists
> * output of `inxi -G`
> 
> Is anyone _not_ on a laptop? Specify if this is an 'optimus' laptops (having both a discrete nvidia as well as built-in intel), do you run in hybrid mode via bios settings, or discrete only. If in hybrid, do you run in performance or intel mode (or on-demand)?
> 
> Thanks
> 
> edit: Please put this stuff into a text file and attach the file to your response - I don't want to overwhelm this thread :)


You're going to have to start testing more on external display set ups and yes >50% of the market is laptops

**Comment by mtwebster** [comment] 2020-07-01 16:54
I can reproduce now, thanks

**Comment by vpal** [comment] 2020-07-01 17:07
No optimus here, single integrated GPU.
No monitors.xml.

[cinnamon-monitors.xml.txt](https://github.com/linuxmint/cinnamon/files/4859293/cinnamon-monitors.xml.txt)
[inxi-G.txt](https://github.com/linuxmint/cinnamon/files/4859294/inxi-G.txt)
[xrandr--verbose.broken.txt](https://github.com/linuxmint/cinnamon/files/4859295/xrandr--verbose.broken.txt)
[xrandr--verbose.working.txt](https://github.com/linuxmint/cinnamon/files/4859296/xrandr--verbose.working.txt)

**Comment by Marshal-Kilgore** [comment] 2020-07-01 17:59
I can confirm the issue and would like to add:
As shown in the posted xrandr-outputs, the size of the (virtual) Desktop is set wrong (for the width of both monitors), albeit the laptop screen is OFF (because the lid is closed).
The regression happened in the update of cinnamon-desktop 4.6.0 => 4.6.2, cinnamon 4.6.6 itself works fine on my system.
A workaround is to change the monitor-setup with xrandr, either
`$ xrandr --output <external-monitor> --auto` or
`$ xrandr --output <laptop-screen> --off`,
but you have to repeat that after every login.

**Comment by kkittykait** [comment] 2020-07-01 18:24
make sure to set your screens on again before log out or you lose the desktop to a muffin segfault

**Comment by mtwebster** [comment] 2020-07-01 19:22
I've a few packages to try if anyone is interested:
https://www.dropbox.com/sh/qk2emkdcyq8ixdj/AADPEd8iiMZzKAE2Frjlo05oa?dl=0

Download them all, open a terminal, then `dpkg -i *.deb`

Anyone not on mint/ubuntu, build from git master of cinnamon-desktop (https://github.com/linuxmint/cinnamon-desktop)

Thanks

**Comment by vladimir-didenko** [comment] 2020-07-02 18:27
@mtwebster Your latest commit in cinnamon-desktop fixes the problem for me. Thank you!

**Comment by vpal** [comment] 2020-07-03 12:22
@mtwebster do you know when this patch will be available through the update channels?

**Comment by mtwebster** [comment] 2020-07-10 15:21
cinnamon-desktop 4.6.3 is released and has this fix.  Please confirm the fix when the update comes out (mintupdate will want to install it over any test packages you've installed, so you shouldn't need to worry about those).

https://github.com/linuxmint/cinnamon-desktop/commit/c1701bbc7cadeebb7720b913ee79c8af32428498

Thanks

**Comment by gusbrs** [comment] 2020-07-10 17:50
I've just applied the latest `cinnamon-desktop` upgrade and can happily report the issue is gone for me.

@mtwebster Thank you very much!

**Comment by vpal** [comment] 2020-07-10 19:54
After applying update all fine after restart. Thanks for the quick solution.

**Closed** 2020-07-10 20:07 UTC

**Comment by Betalord** [comment] 2020-07-13 18:37
This solves the problem of blinking for me, but doesn't entirely solve the problem - what remains is the login screen problem. When I boot up the system, I can't see the login form (or mouse) on my screen. If I open my laptop's lid, I can see the login prompt. What I see on my monitor is only my wallpaper and that is it. It seems as it is treating my monitor as a secondary display or extended desktop or something like that. Not sure how to fix that, but it is related to this problem.

**Comment by vladimir-didenko** [comment] 2020-07-13 19:42
@Betalord As a workaround you could move mouse cursor to your external display moving it in the right direction. But I agree that it is annoying issue especially when you have Bluetooth mouse that doesn't work until you login. Could you create separate story for this issue?

**Comment by mtwebster** [comment] 2020-07-13 21:20
In the greeter settings do you have it set to 'auto'?  I'll take a look at this.

**Comment by vladimir-didenko** [comment] 2020-07-14 09:38
@mtwebster Yes this issue happens with montor setting set to 'auto'.

**Comment by Betalord** [comment] 2020-07-14 14:44
OK so I tested it out: if I move my mouse to the right side, the eventually the login prompt appears on my monitor and I can log in. However, it is overscaled (including the mouse cursor), and if I open the lid, computer it goes to standby. So I have to close the lid and open it up again. Which is strange, since once I'm logged in, that doesn't happen - I can open and close lid as many times as I want and nothing happens.
What greeter setting do I need to change (where do I find it)?
Also, do I need to open a new issue?
