### ISSUE TITLE
Cannot use keyboard to navigate Cinnamon Settings

### ISSUE THREAD

**Issue by polsVoice** [linuxmint/Cinnamon#4861] opened 2015-11-23 02:17 UTC
Recently, I was checking out the settings for **Mouse and Touchpad** on my laptop. In the **Touchpad** section, near the top, is a setting for "Enable Touchpad". I foolishly clicked it, setting it to OFF, so my touchpad quit working! I was unable to set it back. The keyboard apparently did nothing. The tab key did not select any of the buttons. Also, I was somewhere where I didn't have access to a USB mouse. I tried several command-line options that I found through Google via my phone, but none of them worked. I could not get ```synclient```, ```xinput```, or ```gsettings``` to turn the touchpad back on. One web page suggested creating ```/etc/modprobe.d/touchpad.conf``` containing the command ```options psmouse proto=imps``` and then rebooting. Nada. Nothing...worked. I finally was able to change it back when I got home and plugged in the USB mouse from my desktop.

In my opinion, the user should always have the option of controlling the UI from the keyboard. I tried opening the control panel several times and tabbing around, but A) the Tab key did not highlight any of the options, and B) just tabbing and hitting Return blindly did nothing. This leads me to believe that control panels can't be controlled from the keyboard.

**Comment by JosephMcc** [comment] 2015-11-23 10:50
This is a duplicate of https://github.com/linuxmint/Cinnamon/issues/4447

**Closed by JosephMcc** 2015-11-23 10:50 UTC

**Comment by polsVoice** [comment] 2015-11-30 07:07
Two things:

1) Shouldn't the command line utilities still work, though? Why would I not be able to turn the touchpad back on using the commands I mentioned?

2) KDE's touchpad settings say "These settings won't take effect in the testing area". This makes much more sense to me. If you disable the touchpad, you should be able to undo this easily, without even having to resort to the keyboard. (Just like when you change monitor resolutions they will revert back if you do nothing, in case you found a setting that makes it difficult or impossible for you to undo it manually.)

**Comment by JosephMcc** [comment] 2015-11-30 07:30
Please don't post in closed issues. There is already a linked issue for this so use that.
