### ISSUE TITLE
Issue with mumble notifications

### ISSUE THREAD

**Issue by raku-cat** [linuxmint/Cinnamon#4707] opened 2015-10-14 02:42 UTC
I have an issue with mumble notifications, where they all come up with the html tags in them https://i.imgur.com/GAstyeI.png I asked about it in the mumble channel and was told to talk to the cinnamon folks about it. I'm on linux mint 17.2, running mumble 1.3.0.

**Comment by anandrkris** [comment] 2016-09-07 16:37
Duplicate of https://github.com/linuxmint/Cinnamon/issues/2416
See [here](https://github.com/linuxmint/Cinnamon/issues/2416#issuecomment-40145181)

**Closed** 2016-09-07 17:41 UTC
