### ISSUE TITLE
Cryptocat crashes Cinnamon only if Cryptocat.desktop is in place (Linux Mint 18 Cinnamon)

### ISSUE THREAD

**Issue by battaglia01** [linuxmint/Cinnamon#6134] opened 2016-12-26 21:57 UTC
Cryptocat is an [encrypted chat app](https://crypto.cat/) that doesn't yet have a package set up. You can download a self-contained tar.gz and put it wherever - in /opt, in /usr/local, in ~/whatever.

When you load Cryptocat for the first time, it auto-generates the file ~/.local/share/applications/Cryptocat.desktop. Here's what's in that file:

    [Desktop Entry]
    Name=Cryptocat
    Exec=/opt/cryptocat/Cryptocat
    Icon=/opt/cryptocat/logo.png
    Terminal=false
    Type=Application
    Categories=GNOME;GTK;Network;InstantMessaging;
    Comment=Easy, secure chat for your computer.

Looks fine, but for some reason, this causes Cinnamon to crash. The first time you open the program, it works fine (although there is no icon in the taskbar), but as soon as that Cryptocat.desktop file gets acknowledged, it causes Cinnamon to crash on every subsequent load. It enters fallback mode and asks if you want to restart.

I'm on a Lenovo ideapad 110. I so far have not had this problem on Mint XFCE 18. Have not tried on 18.1 yet.

**Comment by clefebvre** [comment] 2018-02-01 10:13
Testing on 18.3... it might have been fixed on our side, or on cryptocat's side.. I don't know. I'm unable to reproduce the issue.

**Closed by clefebvre** 2018-02-01 10:13 UTC
Labels: BUG
