### ISSUE TITLE
Mint 18.3 - Cinnamon 3.6.6 - Cinnamon Crashes on Resume From Sleep

### ISSUE THREAD

**Issue by roygilby** [linuxmint/Cinnamon#7101] opened 2017-11-30 07:19 UTC
```
 * Cinnamon version - 3.6.6
 * Distribution - Linux Mint 18.3 Cinnamon   64 bit
 * Graphics hardware *and* driver used - Intel Mesa DRI Intel(R) Haswell Mobile  driver=i915

 ```

**Issue**
Cinnamon crashes when Laptop is resumed from Sleep state.  When Laptop lid is opened, system resumes - desktop appears but is unresponsive - after a few seconds a Dialog Box appears stating that "Cinnamon has Crashed" and would I like to restart Cinnamon.  Cinnamon then restarts without error.

**Steps to reproduce**
Put system into sleep state, either by closing laptop lid, or by selecting "Sleep" from the "Quit" menu.  Then, initiate Resume from Sleep, either by opening laptop lid, or by pressing Power Button on Laptop.

**Expected behaviour**
Cinnamon should not crash when system is resumed from Sleep State.

**Other information**
Stack Trace ------- https://gist.github.com/anonymous/7e5314a60b88c7e8253f079b13df6808
[crash.tar.gz](https://github.com/linuxmint/Cinnamon/files/1516861/crash.tar.gz)

**Comment by tomc797** [comment] 2017-12-17 22:05
I'm experiencing similar problems on resume too. Segfault using gobject. 
Much of the information is similar to the above poster:
linuxmint                   18.3
cinnamon                   3.6.6+sylvia
libglib2.0-0:amd64     2.48.2-0ubuntu1
xserver-xorg-core     2:1.18.4-0ubuntu0.7

Xorg is using modesetting driver
Kernel 4.10.0-42-generic, i915 bound to "Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)"

**Comment by tomc797** [comment] 2017-12-19 07:56
cinnamon 3.6.7 exhibits behavior. Backtrace attached.

cinnamon[2464]: segfault at 1 ip 00007f76fbe9c8f0 sp 00007ffc0f8d3b90 error 4 in libgobject-2.0.so.0.4800.2[7f76fbe68000+52000]

[gdb.txt](https://github.com/linuxmint/Cinnamon/files/1570783/gdb.txt)

**Comment by leigh123linux** [comment] 2017-12-19 08:19
@tomc797 The backtrace isn't any use without  the debugging symbols.

**Comment by tomc797** [comment] 2017-12-20 04:16
Again, with symbols and bt full.

A ffi call is dereferencing null.
[gdb.txt](https://github.com/linuxmint/Cinnamon/files/1574144/gdb.txt)

**Comment by tomc797** [comment] 2018-01-27 04:06
Is there any more information I can provide that would speed the hunting?

**Comment by clefebvre** [comment] 2018-02-01 10:21
Duplicate of https://github.com/linuxmint/Cinnamon/issues/7064

**Closed by clefebvre** 2018-02-01 10:22 UTC
