### ISSUE TITLE
Menu applet items are selectable/openable when they arent supposed to be

### ISSUE THREAD

**Issue by AlemarTheKobold** [linuxmint/cinnamon#12220] opened 2024-06-03 05:23 UTC
### Distribution

Mint 21.3 Cinnamon

### Package version

6.0,4

### Graphics hardware in use

AMD Radeon Vega Mobile Picasso/Raven2 (Ryzen 7 3700u processor integrated graphics)

### Frequency

Always

### Bug description

If your taskbar/panel is in the top position of your monitor (so that the menu opens downward) and you hover over the items within the 'all applications' submenu, you can click and open programs that are not visible, as well as scroll the menu, from below the actual visible window

This seems to also work with any of the submenus that have enough items to scroll with

![oop2](https://github.com/linuxmint/cinnamon/assets/171536828/7ef2a4ca-a13a-4764-b9a9-2fbec9551530)

### Steps to reproduce

move taskbar/panel to top of screen
open 'menu' applet

### Expected behavior

Items that are not visible on the list of applications should not be selectable or openable when not visible; potentially opening unwanted programs or files

**Comment by fredcw** [comment] 2024-06-03 05:44
Duplicate of #11123

**Closed** 2024-06-03 12:15 UTC
Labels: BUG
