### ISSUE TITLE
Cinnamon 2.8.2 – sometimes „windows thumbnails“ and tray tooltips do not disappear

### ISSUE THREAD

**Issue by kmkom** [linuxmint/Cinnamon#4804] opened 2015-11-08 19:58 UTC
Hello,
sometimes (maybe once or twice per day) the new “windows thumbnails” do not disappear when the mouse pointer is not hovering over the windows list. For example, a “windows thumbnail” from Nemo is visible, but I could use Firefox at the same time and use it for browsing while the popup-windows from Nemo stays visible. 
To remove the “Nemo windows thumbnail” I must move the mouse on the windows list again, this closes the thumbnail popup window.
This sometimes also happens with tooltips from a system tray icon.

Linux Mint Cinnamon 17.2, Intel I5 (integrated graphic).

**Comment by JosephMcc** [comment] 2015-11-08 20:31
Duplicate of https://github.com/linuxmint/Cinnamon/issues/4750

**Closed by JosephMcc** 2015-11-08 20:31 UTC
