### ISSUE TITLE
Visual bug when window snapping with keyboard shortcut

### ISSUE THREAD

**Issue by stefanmeili** [linuxmint/cinnamon#10232] opened 2021-07-22 16:27 UTC
```
 * Cinnamon version 5.0.5
 * Distribution - Mint Cinnamon 20.2
 * Graphics hardware *and* driver used : Nvidia RTX 2080 Ti + Nvidia 460.91.03 drivers
 * 64 bit
 ```

**Issue**

Visual / cosmetic issue when snapping windows using super + left / right. Creates a small double image along centre side and gap to background along outside edge of snapped window top to bottom.

**Centre side:**
![image](https://user-images.githubusercontent.com/16913760/126671243-1b3a39d3-1ea5-43b6-8197-a5c80302ab32.png)
**Outside edge:**
![image](https://user-images.githubusercontent.com/16913760/126673229-630dcc98-e001-40e0-9b5a-52f269068e7f.png)

**Steps to reproduce**
Use mouse to snap window to left side of monitor. Use super/windows + right twice to snap window to right side of monitor.
or
Use mouse to snap window to right side of monitor. Use super/windows + left twice to snap window to left side of monitor. 

Doesn't affect windows that are snapped to a corner.

The need to hit super/windows + left/right twice may also be a bug. I think in past versions a single press was needed.

**Expected behaviour**
Move snapped window from one side of monitor to another with a single press

**Other information**
Confirmed on laptop with nvidia GTX 1050 and 460.80 drivers too.

**Comment by mtwebster** [comment] 2021-07-22 16:30
Duplicate of https://github.com/linuxmint/muffin/issues/591 (fixed, will be in next update)

**Closed by mtwebster** 2021-07-22 16:30 UTC
