### ISSUE TITLE
External monitor not detected the second time

### ISSUE THREAD

**Issue by talonx** [linuxmint/Cinnamon#5378] opened 2016-06-15 08:48 UTC
Steps to reproduce
- Connect an external monitor (VGA) to the laptop running Cinnamon (2.8.6-1ubuntu1) on Ubuntu 16.04
- Monitor is detected and things work as expected
- Disconnect the monitor and connect it again
- This time the monitor is not detected
- Suspend/reboot makes it being detected again

**Comment by el-Salmon** [comment] 2016-11-13 10:55
I have detected a similar issue with HDMI monitor in my laptop with intel driver. Cinnamon 3.2 on Manjaro Linux. Steps:
- Start Cinnamon with HDMI and laptop screens (both) activated.
- Disconnect HDMI cable
- Laptop screen doesn't appear as primary screen: empty desktop

**Comment by alexsim2004** [comment] 2017-01-03 10:26
I also have the same issue with Cinnamon 3.2.7 on Arch Linux and Intel HD graphics (built-in modesetting driver).
These same steps that el-Salmon posted can reproduce the issue straight away for me:

-Start Cinnamon with HDMI and laptop screens (both) activated.
-Disconnect HDMI cable
-Laptop screen doesn't appear as primary screen: empty desktop

Have to restart cinnamon before it recognises the Laptop screen as Primary again.

**Comment by mxchange** [comment] 2017-09-27 08:22
I'm having a similar issue, which occured after I tried adding `--scale 2.00:2.00` to xrandr. After that, I cannot get my laptop screen back as working with cinnamon as primary. Whatever I do, rebooting, adding the key `workspaces_only_on_primary` to false (which didn't exists before) does nothing. 
Really strange, don't know where to look.
It seems that `xrandr` is doing its job fine, but cinnamon is not playing nice.

I had this problem before with a 3rd monitor and eventually just accepted it, because I thought cinnamon just didn't support a 3rd screen, but it seems to be a different issue now that my primary laptop screen is not being seen, and I'm unable to add panels to it, or use the window manager like splitting a window etc..

**Comment by talonx** [comment] 2017-09-27 08:33
I stopped using Cinnamon long ago due to this issue and others.

**Comment by leigh123linux** [comment] 2017-09-27 09:08
@talonx I guess you wont mind me closing this misfiled report, it should have been filed against cinnamon-settings-daemon.

**Closed by leigh123linux** 2017-09-27 09:08 UTC
Labels: BUG
