### ISSUE TITLE
Using an On-screen keyboard to write in menu's search box

### ISSUE THREAD

**Issue by aggman** [linuxmint/Cinnamon#3462] opened 2014-09-03 14:53 UTC
I am using the onscreen keyboad ("onboard"), on cinnamon 17 32bit, installed on tablet (Viewsonic Viewpad 10, Intel Atom x86_64 CPU) with touch screen. The problem is I cannot type in menu's search box, because the menu looses focus and hides, as soon as I click on "onboard" keyboard.

**Comment by Vahan86** [comment] 2016-08-31 19:27
@JosephMcc , duplicate of Issue https://github.com/linuxmint/Cinnamon/issues/2192

**Closed** 2016-08-31 19:29 UTC
