### ISSUE TITLE
[Regression] Spotify no longer appears in system tray

### ISSUE THREAD

**Issue by DurandA** [linuxmint/cinnamon#4783] opened 2015-11-03 20:42 UTC
In Cinnamon 2.8, Spotify no longer appears in system tray in Cinnamon even with "Hide system tray icons for compatible players" (Right click the sound applet -> Configure -> "Hide system tray icons for compatible players") disabled. This behaviour appears when upgrading Cinnamon 2.6 to 2.8.

This is not the same as issue [#1180](https://github.com/linuxmint/Cinnamon/issues/1180).

**Comment by JosephMcc** [comment] 2015-11-03 20:55
It works here. If I have indicator support enabled in Cinnamon Settings->General, I get the indicator. If I disable that setting I get the systray icon. I did need to close and open the player for it to take effect. A Cinnamon restart is needed if you enable/disable indicators.

**Comment by DurandA** [comment] 2015-11-03 22:21
Still no tray with indicator support disabled (after reboot). I attached a screenshot with Cinnamon settings. If you think this is related to my specific configuration I'll close the issue and ask on the forums.
![screenshot](https://cloud.githubusercontent.com/assets/3709037/10923377/db5d3818-8280-11e5-86e5-6515e7986f1f.png)

**Comment by clefebvre** [comment] 2015-11-04 11:34
It works for me too.

Try to "highlight" the sound applet... there was a bug in early 2.8 with settings not finding their applet instance id. It was fixed in Cinnamon 2.8.2.

**Comment by grenzor** [comment] 2015-11-05 06:46
Also came across this issue. Not for Spotify but other programs no longer appear in system tray

**Comment by rpbaptist** [comment] 2015-11-05 12:23
I have the exact same issues. Playing with Banshee works. Spotify does not. I am using the latest official Cinnamon. If I can configure this I would be happy to do so.

**Comment by JosephMcc** [comment] 2015-11-05 21:13
Did any of you having issues with Spotify try clems suggestion? Go to Cinnamon-Settings->Applets, select the sound applet and choose configure. Hit the "Highlight" button at the top right. Does this make the sound applet flash on the panel?

**Comment by DurandA** [comment] 2015-11-06 00:31
Highlight button makes the sound applet flash (as expected), but it doesn't help to display the hidden tray icons.

**Comment by DurandA** [comment] 2015-11-08 15:13
I should add that Spotify only appears in the window list if I move it to another workspace.
In the meantime, I added a launcher with `wmctrl -xa spotify.Spotify || spotify` which makes it less painful.

**Comment by rpbaptist** [comment] 2015-11-09 08:35
My problem is actually slightly different. It does appear in the system tray, but it looks the same in the sound applet. No application name, no album art, unkown artist and unkown title always.

**Comment by rwpreece** [comment] 2015-12-18 22:37
Hi Clem,
That screenshot shows enough of the Spotify client that I noticed it's the **1.0.x beta/pre-release** that many are moving to due to the **0.9.x version causing Cinnamon crashes/hangs** (which I'll bet is related to proxy issues and error handling in the chromium plugin that Spotify uses).

The **1.0.x version of Spotify** (http://repository.spotify.com/pool/non-free/s/spotify-client) installs to **/usr/share instead of /opt/share** like the 0.9.x versions.  Also, it looks like the executable is **"Spotify" instead of "spotify"** now.

The /usr/share/cinnamon/applets/sound@cinnamon.org/applet.js probably needs a little tweaking to accommodate the changes.  

At first glance it looks like it's just missing references for:
1) player name and status, and the open and close buttons.
2) Album art, artist and track.

I wonder if **Spotify 1.0.x** is now using **mpris to pass dbus information** now.  It sounds like it was significantly re-written.

I'll paste this info into #4858 as well in case it helps.

**Comment by tp0** [comment] 2015-12-22 05:27
I can get it to show up in the "application" list on the indicator: volume control works, and play control (next/prev/play etc.) works, but no album art or artist/song names.

Highlight trick makes no difference. Tried with another user account too. Spotify = `1.0.19.106.gb8a7150f`.

![untitled](https://cloud.githubusercontent.com/assets/5863551/11948426/91646fca-a87c-11e5-8f30-5400a33d2044.png)

I can't remember a time without any tray icon/indicator/album art related issue, but this is definitely so far the worst experience due to the separate? window list bug.

**Comment by rwpreece** [comment] 2015-12-22 19:27
All,
Please remember that *the sound applet is setup to work with Spotify 0.9.x.  Not Spotify 1.0.x.*

The install location, among other things, has changed in Spotify 1.0.x.  It installs to /usr/share now.  The previous version installs to /opt/share (see my previous post).

The issues in this and #4858 are not bugs in Cinnamon or Spotify.  Simply a symptom of using beta release versions of software.  

If you want to make the sound applet work with the beta 1.0.x versions of Spotify then you can modify the applet javascript () to properly handle it.

If you just want it to work, then I would suggest an clean install of Spotify 0.9.x from Software Manager or Synaptic.  

By clean install I mean:
1) Uninstall Spotify 1.0.x
2) Delete spotify folders in .config, .local, and .cache.
3) Delete old spotify folders from /opt/share and /usr/share 
4) Delete the spotify symlink in /usr/bin
5) Now install spotify-client from the Software Manager.

By the way, you can delete your "additional repository" and signing/auth key for Spotify if you originally installed it from the Spotify repo.

Now all your sound applet features should work.  You'll have to run Spotify once and start playing a song for it to be picked up by the sound applet.

Oh, and if you like seeing the Spotify icon in your system tray, you can turn off the "Enable support for indicators" option in General under System Settings.

Also, if you have trouble with Spotify hanging or crashing Cinnamon and that's why you installed the Spotify 1.0.x beta release, you might just go back to the 0.9.x version and play with your proxy settings in Spotify settings.  Make sure you click save and completely exit/close Spotify and go back in to ensure your settings were saved and implemented.  The hang/crash caused by Spotify 0.9.x actually appears to be related to the chromium tool used in Spotify for the browser functionality like getting album art, updating your status and music that your are listening to, etc. between your computer and the Spotify servers.

Hope this helps someone.

By the way, I'm not affiliated with Cinnamon or Linux Mint but I am a huge fan.

**Comment by mtwebster** [comment] 2015-12-25 02:51
Are you sure this isn't a bug in spotify?

I just installed `spotify-client 1:1.0.19.106.gb8a7150f`

The executable is simply 'spotify.'

The sound applet isn't working because the client appears not to be speaking with it correctly over dbus:

```
(cinnamon:18827): GLib-GIO-WARNING **: Value for PropertiesChanged signal with type '(sa{sv}an)' does not match '(sa{sv}as)'

(cinnamon:18827): GLib-GIO-WARNING **: Dropping signal PropertiesChanged of type (sa{sv}an) since the type from the expected interface is (sa{sv}as)

(cinnamon-settings-daemon:18771): GLib-GIO-WARNING **: Value for PropertiesChanged signal with type '(sa{sv}an)' does not match '(sa{sv}as)'

(cinnamon-settings-daemon:18771): GLib-GIO-WARNING **: Value for PropertiesChanged signal with type '(sa{sv}an)' does not match '(sa{sv}as)'

(cinnamon:18827): GLib-GIO-WARNING **: Value for PropertiesChanged signal with type '(sa{sv}an)' does not match '(sa{sv}as)'

(cinnamon:18827): GLib-GIO-WARNING **: Dropping signal PropertiesChanged of type (sa{sv}an) since the type from the expected interface is (sa{sv}as)
```

**Comment by rwpreece** [comment] 2015-12-25 09:27
@mtwebster - **It's definitely a bug in Spotify 1.0.x, but it's a beta version and bugs are to be expected.**  I've seen other similar posts, including one from Arch Linux (https://aur.archlinux.org/packages/spotify-beta/) which refers to the **1.0.x version of Spotify as a beta version.**  The Spotify community forums also indicate that it's a **beta version** as well.

Technically there is no **"regression in Cinnamon"** because it's sound applet would have been developed with the **released version** of the Spotify client, which is **version 0.9.17.x**.  This is also the version that is **included in the repositories for Linux Mint 17.3 Cinnamon Edition**, which implies that it's the supported version of Spotify.  If you install this one from the Software Manager **both the Cinnamon Sound Applet and the Spotify client work fine.**  

Users shouldn't **reasonably expect** Linux Mint and/or Cinnamon to work with/support beta versions of any software.

However, I suspect the **developers at Spotify** would really **appreciate some feedback**, that includes some **really good technical information** like you've posted above, from the **Linux Mint and Cinnamon developers.**  

This could be a good opportunity to bring up Clem's information about **Spotify reporting that it supports seeking when it really doesn't appear to.**

I hope this clarifies what I was trying to say, which is, **"Use Spotify 0.9.17.8x with Cinnamon 2.8.x and the sound applet will be fully functional."**  I tend to ramble which leads to unclear messages.  I blame the ADHD that definitely doesn't get better with age. :)  

By the way, I'm also a big fan of Spotify.  I subscribe to their premium service.  It's great stuff and so is Linux Mint and Cinnamon. :D

Oh, also, it appears that people are moving to the 1.0.x beta version of Spotify because it no longer causes Cinnamon to hang/crash when communicating with the Spotify servers.

**Comment by rpbaptist** [comment] 2015-12-25 14:07
Thanks @rwpreece! I was using 0.9.17 from the Spotify repo for a long time and at one point the tray information was gone. I never used the beta.

But deleting everything locally and installing from the Mint repo solved the issue for me.

**Comment by rpbaptist** [comment] 2015-12-29 16:21
Okay, scratch that. Spotify pushes notifications to the tray on each track which is completely stupid. It can be disabled by settings this in prefs: `ui.track_notifications_enabled=false`

However, this also disables sound applet integration. I guess we can't have both. :disappointed:

**Comment by tp0** [comment] 2016-03-05 21:38
> Spotify’s rep also says the company do ‘want to fix’ some minor issues, like incorrect MPRIS data being passed to sound applets in GNOME, Unity, Cinnamon, etc, but when this may happen is as-yet unknown.

> Bigger issues, like the missing system tray icon, ‘probably won’t’ be tackled.

http://www.omgubuntu.co.uk/2016/03/spotify-linux-no-development

**Comment by mastorak** [comment] 2016-03-07 13:36
After some digging in the code it becomes obvious that the problem is that the Metadata are not read from dbus because Spotify does not write it correctly. Check `xml_with_owner['org.mpris.MediaPlayer2.Player']` in [ js/misc/interfaces.js](https://github.com/linuxmint/Cinnamon/blob/master/js/misc/interfaces.js) you will see that the Metadata is null when read from `getDBusProxyWithOwnerAsync`
However  Spotify will report to those Metadata so a workaround can be produced. For example running
`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`  

Playerctlc project has [a workaround](https://github.com/acrisci/playerctl/commit/fda38a67af9979ea801ca7fa7a6d7562941a3248) to tackle [the same issue](https://github.com/acrisci/playerctl/issues/20)

**Comment by hmcezar** [comment] 2016-04-09 12:47
For those who wanted the MPRIS2 support in the 1.x version, it's now working in the current testing version (1.27).

It means that the sound applet is now working with the new version (album cover and controls).

**Comment by rwpreece** [comment] 2016-04-09 20:56
Would Spotify consider "open sourcing" parts of the Linux client code that
is not proprietary or would expose any of their security or DRM code?

There is a lot of competition in their industry and I'm sure resources are
very limited.  I'm sure they are allocated to where their is the highest
demand or return on investment.

Whom ever has been getting responses from Spotify's rep should ask them if
they would be open to the  "partial open source" idea.  I know there is
enough demand in the Linux community that contributors would jump at the
opportunity.  Also, we should keep in mind that the Spotify Linux client
was started as a developer's personal project for their "open coding time"
at work but has now taken on a life of it's own because we all really enjoy
it.

It's good to see it getting some attention though but I'll be it would get
a lot more from the community.

Just an idea.

Roger

**Comment by utack** [comment] 2016-04-17 01:39
Slightly related:
You can start the Windows client in Wine, which spawns a tray entry and icon, and the Linux client in parallel (not showing up and hence not in the way of your workflow) will mirror the media information and forward playback control for you cia the synchronisation Spotify uses.

**Comment by clefebvre** [comment] 2016-04-18 15:23
Hi,

Version 0.27 was added to Mint 18 and I'm looking at the upcoming Cinnamon 3.0 to support Spotify the best I can.

I noticed a few things which could be fixed: https://github.com/linuxmint/Cinnamon/commit/6ce9bc28afd63305a5fca24ce3992b1adb865bbd

If you happen to know a Spotify dev though, send him our way. We can drastically support for Spotify over MPRIS in a matter of seconds and highlight to them exactly what's wrong and what to change it to.

**Comment by hmcezar** [comment] 2016-04-18 16:07
Hi Clem,

I personally don't know anyone from the Spotify dev team, and unfortunately they don't even have a dedicated Linux client developer.
The devs work in the Linux client during their "free time".

However, the one responsible for the changes of 1.0.27 is "jooon" from the Soptify forums.
"jooon" and "dreadlord" are the ones I always see posting in the Spotify forums about Linux.
You could try to contact them via private messages, below I provide the links to their profiles in the Spotify forums:
https://community.spotify.com/t5/user/viewprofilepage/user-id/53
https://community.spotify.com/t5/user/viewprofilepage/user-id/1799509

**Comment by clefebvre** [comment] 2016-04-18 18:04
Thanks, I sent a PM to jooon.

**Comment by Vahan86** [comment] 2017-01-21 22:18
@DurandA, is this still an issue for you with Cinnamon 3.2?

**Comment by kelebek333** [comment] 2017-02-27 06:21
This problem still on Cinnamon 3.2 with locale turkish language. There no problem if I login with English locale or reset Cinnamon with following command.

LC_ALL=C cinnamon --replace

"Sound with apps volume" applet can shows album cover with Turkish locale or English.

https://cinnamon-spices.linuxmint.com/applets/view/150

**Comment by mabod** [comment] 2017-05-25 11:36
Since my bug report was just closed and linked to here I want to add some more details.

On debian / Mint LMDE the cover art for spotify is working with the sound applet. 
Versions installed are:
spotify-client                               1:1.0.49.125.g72ee7853-111
cinnamon                                    3.2.7+betsy  

I downgrade my spotify on Manjaro by editing the PKGBUILD file and it is still NOT working:
spotify 1.0.49.125-1
cinnamon 3.4.0-1.1

So from my point of view this is most likely not an issue with the spotify client.

Matthias

**Comment by mabod** [comment] 2017-06-15 18:24
It works with cinnamon 3.4.1-1.1

**Comment by Vahan86** [comment] 2018-02-11 18:37
@DuarndA, is this still an issue for you with Cinnamon 3.6?

**Comment by Vahan86** [comment] 2019-11-24 19:58
@JosephMcc, can we close this issue?

**Closed** 2019-11-24 20:18 UTC
Labels: BUG

**Comment by mabod** [comment] 2019-11-25 12:36
yes you can.
