### ISSUE TITLE
Slow MDM to Cinnamon 2.4.1 transition

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/Cinnamon#3675] opened 2014-11-16 21:14 UTC
After entering password in MDM Cinnamon takes 35+ seconds to show up (compare to 6 seconds of Unity). During this interval there is a lot of disc I/O activity. The computer is a Core I7 with discrete nvidia card.

**Comment by dalcde** [comment] 2015-04-16 09:30
Duplicate of #3681

**Closed by dalcde** 2015-04-16 09:30 UTC
