### ISSUE TITLE
clock/calendar applet size shrinks resulting in misleading clock

### ISSUE THREAD

**Issue by dashesy** [linuxmint/Cinnamon#4418] opened 2015-07-08 22:35 UTC
Here is the screen-shot note that the time is 3:29pm (i.e. 15:29 in 24hour mode):
![screenshot from 2015-07-08 15 29 44](https://cloud.githubusercontent.com/assets/873905/8583920/5d840af4-2586-11e5-9712-8ae03c0053af.png)

Whereas in the screen-shot the leading `1` is kind-of seen on top of the Bluetooth icon, it is actually less visible on monitor.

I think this started to happen after I updated (unless I did not notice it before)

```text

Installed Packages
Name        : cinnamon
Arch        : x86_64
Version     : 2.6.7
Release     : 3.fc21
```

**Comment by pixunil** [comment] 2015-07-09 08:22
Just a little question: Do you have wide applets, like the window applet in the center region of your panel? In some versions of `2.6`, the center region does grow to large and the right section is put out of screen. When it is so, try to upgrade (here on `2.6.11`, it's okay).

**Comment by dashesy** [comment] 2015-07-09 15:24
What is a window applet? I do not have any applet in the middle though, here is the full line (added few more terminals to show the problem better now that time is in the morning):
![screenshot from 2015-07-09 08 21 57](https://cloud.githubusercontent.com/assets/873905/8599174/cc40ad98-2613-11e5-9f88-a3da28fe1cb8.png)

**Comment by pixunil** [comment] 2015-07-10 12:59
Sorry, my mistake, window _list_ applet (where all your windows are visible).
Is it better when you don't have that much windows open? (E.g. on a second virtual workspace)
I'm not sure that this helps, but also consider to upgrade.

**Comment by dashesy** [comment] 2015-07-10 14:48
thanks, I wait some time for my distro (it is a minor version so they will eventually pick it up) before upgrading myself, it is only recently that applets like Bluetooth, ... work flawlessly, one little clock down the corner is not a big deal.

**Comment by Vahan86** [comment] 2016-09-07 16:48
@JosephMcc, can we close this issue?

**Comment by JosephMcc** [comment] 2016-09-07 17:51
Yeah, it has had no follow up in over a year. There are occasions where this sort of thing can be caused by the window list and that is known and I'm pretty sure there are other open issues for it.

**Closed by JosephMcc** 2016-09-07 17:51 UTC
