### ISSUE TITLE
Thorough and coherent documentation

### ISSUE THREAD

**Issue by cobrafast** [linuxmint/Cinnamon#4078] opened 2015-04-24 22:53 UTC
I think the project and community could hugely benefit from a thorough and coherent source of information, especially references for applet and extension programming.

Right now there is very sparse information in the form of a brief tutorial page on the mint website and a few short wiki pages here on github (one of them links to the tutorial page as its sole content :confused:). There is no way to get a start into development without digging through the cinnamon codebase and exisiting extensions - which makes it very hard to find specific features and get a more general overview about what's possible and how.

Having great documentation would probably lead to better quality in extensions and more people developing and getting involved with extensions as less developers would be scared off. It would give new people an easier start and give seasoned devs a more simple source for more specific information.

**Comment by dalcde** [comment] 2015-04-27 06:55
This is an experimental attempt at code documentation: http://dec41.user.srcf.net/cinnadoc/

**Comment by dalcde** [comment] 2015-04-29 08:47
Duplicate of #3186

**Closed by dalcde** 2015-04-29 08:47 UTC
Labels: [FEATURE REQUEST]
