### ISSUE TITLE
LibreOffice icons are invisible with new Cinnamon theme

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#11762] opened 2023-07-18 17:04 UTC
### Distribution

Linux Mint 21.2

### Package version

5.8.4

### Frequency

Always

### Bug description

LibreOffice icons are invisible with new Cinnamon theme:

![Capture d’écran du 2023-07-18 19-00-38](https://github.com/linuxmint/cinnamon/assets/3955499/b2ff8400-47a1-4110-bdcc-c786e01f954c)

### Steps to reproduce

Choose this theme:

![Capture d’écran du 2023-07-18 19-03-21](https://github.com/linuxmint/cinnamon/assets/3955499/1232181d-5d83-48ca-88d4-0df0332ccf22)

Start LibreOffice.

### Expected behavior

Icons should be visible.

**Comment by JosephMcc** [comment] 2023-07-18 17:22
Cinnamon doesn't really have anything to do with this.

**Comment by InfoLibre** [comment] 2023-07-18 19:58
My LibreOffice configuration:

![Capture d’écran du 2023-07-18 21-57-47](https://github.com/linuxmint/cinnamon/assets/3955499/09882c19-f9f0-4744-84ba-33d187c57114)

**Comment by mtwebster** [comment] 2023-07-19 01:09
Is that a new or upgraded system?

It's clear why your icons are that way (You have a light system icon theme but office is using Breeze dark), but I'm not sure why it's doing so under Automatic selection - this should cause the theme to switch between Breeze and breeze(dark) on its own, depending on the system theme or color-scheme preference.

Try temporarily renaming your `~/.config/libreoffice` folder

**Comment by dominiquearpin** [comment] 2023-08-06 15:19
I got the same issue with a new installation Linux Mint 21.2 Cinnamon.  I need to use the dark theme to see all the icons in LibreOffice.

**Comment by claudiux** [comment] 2023-08-06 18:28
If you're using the 'darkMode@linuxedo.com' applet, please try to remove it.

**Comment by dominiquearpin** [comment] 2023-08-09 01:05
I don't use any applet, its a fresh install.  Laptop HP G4.

**Comment by vaitkus** [comment] 2023-08-09 03:56
I had the same issue after upgrading from 20.1 to 20.2.

Renaming the `~/.config/libreoffice` folder does not fix the issue as the `(Breeze (SVG + dark))` icon theme is once again automatically selected. Manually changing the theme to `Breeze` or `Colibre` as described [here](https://forums.linuxmint.com/viewtopic.php?t=400479) does make the icons visible, though.

**Comment by clefebvre** [comment] 2023-08-09 11:11
Alright, this seems to be a regression from the addition of libreoffice-style-breeze.

https://github.com/linuxmint/mint21.2-beta/issues/30.

I'm not sure how LO decides which theme to apply automatically, but we definitely want to guarantee everything works OOTB with the default theme prior to accomodating for dark theme support.

We'll remove libreoffice-style-breeze in 21.3, and I'm removing it now from mint-upgrade-info.

Issue https://github.com/linuxmint/mint21.2-beta/issues/30 becomes upstream-wont-fix and needs to be addressed by LO directly.

**Closed by clefebvre** 2023-08-09 11:11 UTC
