### ISSUE TITLE
nemo doesn't fit to screen at first launch

### ISSUE THREAD

**Issue by A-Shahbazi** [linuxmint/Cinnamon#4725] opened 2015-10-19 17:00 UTC
When I launch nemo the window is not fitted to screen until I do some action like opening a folder or opening properties dialog.
screenshot:
![screenshot from 2015-10-19 20 26 33](https://cloud.githubusercontent.com/assets/7456141/10584560/bf201c20-769f-11e5-86bd-f7de877419d6.png)
BTW, I'm using cinnamon on elementary os freya distribution. It's based on ubuntu trusty but uses gtk 3.14 instead of ubuntu trusty's delivered gtk 3.10

**Comment by JosephMcc** [comment] 2015-11-06 12:50
Is this restricted to Nemo? If so please close this and open the issue on the Nemo github repo instead.

**Comment by A-Shahbazi** [comment] 2015-11-06 16:37
I think it's just nemo. linuxmint/nemo/issues/999

**Comment by A-Shahbazi** [comment] 2015-11-10 07:46
Although I have experienced this issue just with nemo I found out that nemo behaves normally when I login to other desktop environments. Unity and Pantheon were tested.

**Comment by JosephMcc** [comment] 2015-11-10 08:02
Normally nemo re-opens at whatever size it was when you last closed it. How are you reproducing this? Do you close nemo maximized?

**Comment by A-Shahbazi** [comment] 2015-11-10 08:25
Yes, I close it maximized. It's ok when it's closed unmaximized.

**Comment by JosephMcc** [comment] 2015-11-16 00:17
Are you using any of Cinnamon panel auto-hide features? I just trying to find a way to reproduce this.

**Comment by A-Shahbazi** [comment] 2015-11-16 05:36
No I don't.
BTW, I encountered another app(Pantheon Photos) that has this problem under cinnamon.

**Comment by JosephMcc** [comment] 2015-11-16 07:39
Does it work the same way as nemo? It remembers the size from the last time you closed it? So closing it maximized and then re-opening it causes the issue?

**Comment by A-Shahbazi** [comment] 2015-11-16 08:15
Unfortunately, I can't reproduce the issue using Pantheon Photos. It doesn't remember the size from the last time I closed it.
I found out that the issue is not just about maximization. Nemo window doesn't fit to screen when I use tile feature for other edges of the screen with one difference. The difference is that nemo doesn't remember the exact size/position in those conditions.
I noticed something I think might be worth of mentioning. The elementary OS Freya distribution uses gala as window manager and I noticed that using nemo I experience a bug known to be related to gala. Is it possible that nemo is using gala or a library from gala instead of muffin? How do I find out?

**Comment by A-Shahbazi** [comment] 2015-11-18 06:10
update:
The other application which had the same issue as nemo wasn't "Pantheon Photos". It was Gnome Image Viewer(Eye of Gnome - eog).

**Comment by keitalbame** [comment] 2016-01-26 08:25
I have the same behavior for Gnome Image Viewer.
When I open it, it is not maximed. After maximize, it doesn fit on screen. If I minimize and maximize again, it will display correctly.
After close and reopen, it doesn't remember the last size.

I'm on Arch.

Did not tested Gnome Image Viewer on other laptop with Linux Mint, to check if it also happens there.

Maybe is not an Cinnamon issue but a Gnome one?

**Comment by JosephMcc** [comment] 2016-01-26 08:30
I can't reproduce the issue with Image Viewer on Mint. It's possible it's related to the use of a header bar in your case. I'll test on Ubuntu later.

It's up to individual apps to remember their size after they were closed and reopened.

**Comment by keitalbame** [comment] 2016-02-06 10:03
Tested on below distros and open and maximize works without issues.
Will test on ubuntu-gnome 15.10.

Maybe it is related with client side decorations because none of the below, have it.

mint 17.2
version - 3.10.2 - no client side decorations.

mint 17.3
version - 3.10.2 - No client side decorations

ubuntu 14.04
version 3.10.2 - No client side decorations

ubuntu 15.10
version 3.16.3 - No client side decorations

**Comment by keitalbame** [comment] 2016-02-06 10:31
Image viewer 3.16.3 works ok in ubuntu-gnome 15.10 and have client side decorations.

In my case, I previously had Gnome installed. Maybe is some config from that time.

**Comment by ManIVIctorious** [comment] 2016-09-06 12:39
Is this still relevant in cinnamon 3.0?

**Closed** 2016-09-06 18:40 UTC
Labels: BUG
