### ISSUE TITLE
Linux Mint 17.3 Cinnamon crash on dragging any html tags in chrome's inspect element 

### ISSUE THREAD

**Issue by secanaly** [linuxmint/Cinnamon#5109] opened 2016-02-27 16:36 UTC
On dragging flash file html tags from inspect element, Cinnamon crashes everytime. Here are the steps to reproduce it:

1. Open this https://www.gstatic.com/charts/motionchart/1/en/tlz-gviz.swf?js=sync&chartId=explorer-motionChart-swf&state=%7B%22stateVersion%22%3A3%2C%22showTrails%22%3Afalse%2C%22xAxisOption%22%3A%22wmt_url_impression.impressions%22%2C%22yAxisOption%22%3A%22wmt_url_impression.clicks%22%2C%22colorOption%22%3A%22_UNIQUE_COLOR%22%2C%22sizeOption%22%3A%22_UNISIZE%22%2C%22dimensions%22%3A%7B%22iconDimensions%22%3A%5B%22wmt_url_impression.countryId%22%5D%7D%7D&opt_.featureConfig_advancedPanel=false

2. Open inspect element and now drag any html tags from it. Cinnamon will be crashed

Cinnamon will only crash if above steps is done in chrome.

**Comment by mtwebster** [comment] 2016-02-27 16:54
Duplicate of https://github.com/linuxmint/Cinnamon/issues/4789

**Closed by mtwebster** 2016-02-27 16:54 UTC
