### ISSUE TITLE
Turning off bluetooth turns off wireless as well

### ISSUE THREAD

**Issue by djk-2** [linuxmint/Cinnamon#7209] opened 2018-01-16 15:40 UTC
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit

Cinnamon 3.4.6
Mint 18.2 x64

Graphics:  Card: Advanced Micro Devices [AMD/ATI] Wrestler [Radeon HD 6320]
           bus-ID: 00:01.0 chip-ID: 1002:9806
           Display Server: X.Org 1.18.4 drivers: ati,radeon (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.00hz
           GLX Renderer: Gallium 0.4 on AMD PALM (DRM 2.46.0 / 4.8.0-53-generic, LLVM 3.8.0)
           GLX Version: 3.0 Mesa 12.0.6 Direct Rendering: Yes

Network:   Card-1: Broadcom BCM4313 802.11bgn Wireless Network Adapter
           driver: wl bus-ID: 03:00.0 chip-ID: 14e4:4727
           IF: wlo1 state: up mac: <filter>
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: 2000 bus-ID: 07:00.0 chip-ID: 10ec:8168
           IF: eno1 state: down mac: <filter>

Network Driver: bcmwl-kernel-source
                             Version 6.30.223.271+bdcom-Oubuntu1~1.2
                             Broadcom 802.11 Linux STA  wireless driver source

 ```

**Issue**

When I disable bluetooth, it also turns off the wireless signal. My system dual boots with Windows 10, and this is not an issue in Windows. 

**Steps to reproduce**

Click on Bluetooth icon in panel. Switch to "Off" position. The bluetooth icon goes grey and bluetooth is disabled. Additionally, the wireless icon changes, and hovering over it indicates "no connection." The wireless is also disabled. This is unwanted. The two processes should be independent of each other.

**Expected behaviour**

Be able to turn off bluetooth without simultaneously turning off the wireless signal. 

**Other information**

I can disable wireless without it disabling bluetooth, i.e. clicking on the wireless icon and turning it off does not turn off the bluetooth.

This is not an issue in Windows running the same system.

**Comment by leigh123linux** [comment] 2018-01-16 15:53
Duplicate of #7208

**Closed by leigh123linux** 2018-01-16 15:53 UTC
