### ISSUE TITLE
Theme Settings Not Persisting Between Reboots

### ISSUE THREAD

**Issue by bradonomics** [linuxmint/cinnamon#10576] opened 2022-01-06 21:46 UTC
```
 * Cinnamon version 5.2.7
   - I am not using the daily builds PPA
 * Distribution - Mint 20.3
 * Graphics hardware: Intel Iris Plus Graphics 655
 * 64 bit
```

The icons and windows borders settings in the Themes are not persisting between reboots. I'm trying to use the [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) which I installed it using [their PPA](https://launchpad.net/~papirus/+archive/ubuntu/papirus). After selecting the new icon set in Settings > Themes > Icons, I reboot and the icons are returned to the default (Mint-Y-Dark). I installed it the same way on 20.2 (Cinnamon 5.0.7) and had no problems. This is a fresh install of 20.3.

The same thing is true of the mint-y-legacy settings for Window borders.

**Comment by viveksreedharan88** [comment] 2022-01-08 18:17
- Yeah! 20.3 has this issue. Hope they find a fix soon.

**Comment by viveksreedharan88** [comment] 2022-01-09 06:27
> ```
>  * Cinnamon version 5.2.7
>    - I am not using the daily builds PPA
>  * Distribution - Mint 20.3
>  * Graphics hardware: Intel Iris Plus Graphics 655
>  * 64 bit
> ```
> 
> The icons and windows borders settings in the Themes are not persisting between reboots. I'm trying to use the [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) which I installed it using [their PPA](https://launchpad.net/~papirus/+archive/ubuntu/papirus). After selecting the new icon set in Settings > Themes > Icons, I reboot and the icons are returned to the default (Mint-Y-Dark). I installed it the same way on 20.2 (Cinnamon 5.0.7) and had no problems. This is a fresh install of 20.3.
> 
> The same thing is true of the mint-y-legacy settings for Window borders.

Root cause here is the mint welcome screen! Try disabling it at the start up.

**Comment by viveksreedharan88** [comment] 2022-01-09 06:27
> > ```
> >  * Cinnamon version 5.2.7
> >    - I am not using the daily builds PPA
> >  * Distribution - Mint 20.3
> >  * Graphics hardware: Intel Iris Plus Graphics 655
> >  * 64 bit
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The icons and windows borders settings in the Themes are not persisting between reboots. I'm trying to use the [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) which I installed it using [their PPA](https://launchpad.net/~papirus/+archive/ubuntu/papirus). After selecting the new icon set in Settings > Themes > Icons, I reboot and the icons are returned to the default (Mint-Y-Dark). I installed it the same way on 20.2 (Cinnamon 5.0.7) and had no problems. This is a fresh install of 20.3.
> > The same thing is true of the mint-y-legacy settings for Window borders.
> 
> Root cause here is the mint welcome screen! Try disabling it at the start up.

https://github.com/linuxmint/mint-themes/issues/345

**Comment by clefebvre** [comment] 2022-01-09 14:27
Closing as duplicated of https://github.com/linuxmint/mint-themes/issues/345

**Closed by clefebvre** 2022-01-09 14:27 UTC
