### ISSUE TITLE
Settings -> Display monitor pictures don't match up with mouse

### ISSUE THREAD

**Issue by fang0654** [linuxmint/Cinnamon#3848] opened 2015-01-24 01:04 UTC
I have 4 monitors running on 1 NVidia GTX 650.  The Display utility shows all 4 monitors, but the displayed graphic doesn't match up with the mouse.  In order to 'grab' a monitor, I actually need to mouse the mouse under the picture and move that.

For example, in the attached screenshot, if I mouseover the "Samsung 22" monitor, I can't click anything.  The clickable area exists about a half inch below where the image is.  Will be glad to provide any other debugging info requested.  Running cinnamon-control-center 2.4.2-1 on Arch Linux.

**Comment by JosephMcc** [comment] 2015-01-24 19:55
I just played around with this on my dual monitor setup. After moving the screen widgets around a bit I was able to reproduce this. It looks like the grab area is out of alignment with the widgets. This is on Mint 17.1.

**Comment by arfett** [comment] 2015-02-06 18:47
For me I have to click right near the bottom edge of the monitor display box to drag it.

**Comment by Vahan86** [comment] 2016-09-25 15:32
@fang0654, is this still an issue in Cinnamon 3.0.x?

**Comment by JosephMcc** [comment] 2016-09-25 16:37
Yes, it's still an issue.

**Comment by JosephMcc** [comment] 2016-09-25 16:42
Actually, I might have to take that back. I don't remember anyone fixing it but I'm now unable to reproduce it.

**Comment by Vahan86** [comment] 2016-10-18 17:08
@JosephMcc, can we close this issue?

**Comment by mtwebster** [comment] 2016-10-18 17:14
For completeness: https://github.com/linuxmint/cinnamon-control-center/commit/86e303624f14ed2180cc88584dfb8d4bcb377db7

**Closed** 2016-10-18 17:14 UTC
Labels: BUG
