### ISSUE TITLE
Allow multiple actions for Panel Launcher Applet icons

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/Cinnamon#3666] opened 2014-11-10 20:00 UTC
Currently, you can only use the Panel Launcher Applet items for one action: To launch a specified program.  
Here, I like Unity's approach more (one of the few things I actually like in Unity): The Panel Launcher items are links to .desktop launcher files, like in /usr/share/applications. Some of these launchers, e.g. Firefox, support multiple actions.  
In the case of Firefox, if you normally click the launcher, it starts as it would in Cinnamon. However, if you right click the launcher icon, the context menu offers some more options, like opening a window in private mode or a new window.

To show what I mean, I found this image on Google:
![image](https://cloud.githubusercontent.com/assets/5564491/4982605/1291fee0-6914-11e4-886c-f375d6fa27ec.png)
The entries "Wallch" and "Unlock from Launcher" are default, everything above is defined in the .desktop file.

This is a really nice feature which, at least for me, would improve workflow, and which I'd like to see in Cinnamon.

**Comment by anandrkris** [comment] 2015-04-26 04:48
Duplicate of https://github.com/linuxmint/Cinnamon/issues/2826 ?

**Comment by JosephMcc** [comment] 2016-04-24 23:47
This is now implemented in git master for Cinnamon 3.0

**Closed by JosephMcc** 2016-04-24 23:47 UTC
Labels: FEATURE REQUEST

**Comment by geoffm** [comment] 2017-01-02 22:46
Actually there are officiel additionnal application actions in the freedesktop.org specifications, they just haven't been implemented yet by most DE's.
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s10.html
