### ISSUE TITLE
Opened apps icons do not appear on panel when using dual monitor 

### ISSUE THREAD

**Issue by tethragon** [linuxmint/cinnamon#11352] opened 2022-12-26 06:45 UTC
```
 * Cinnamon 5.6.5
 * Distribution - Linux Mint 21.1 (problem existed in 20.3 also)
   Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] vendor: Sapphire
    driver: amdgpu v: kernel pcie: speed: 16 GT/s lanes: 16 ports: active: DP-1,DP-2
    empty: DP-3,HDMI-A-1 bus-ID: 09:00.0 chip-ID: 1002:731f
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x1200 s-dpi: 96
  Monitor-1: DisplayPort-0 mapped: DP-1 pos: primary,right model: ASUS VP249 res: 1920x1080
    dpi: 93 diag: 604mm (23.8")
  Monitor-2: DisplayPort-1 mapped: DP-2 pos: primary,left model: Dell U2412M res: 1920x1200
    dpi: 94 diag: 611mm (24.1")
  OpenGL: renderer: AMD Radeon RX 5600 XT (navi10 LLVM 15.0.5 DRM 3.42 5.15.0-56-generic)
    v: 4.6 Mesa 23.0.0-devel (git-64d584b 2022-12-05 jammy-oibaf-ppa) direct render: Yes
 * 64 bit

 ```

### Issue

When enabling 2nd monitor (join monitors, NOT mirror) and start opening apps, the app icons on panel do not appear. I need eventually, as a workaround, hit ctrl+alt+esc to restart cinnamon in order for the app icons to appear on panel

### Steps to reproduce

1. use display manager to enable second monitor
2. start opening apps (like VM, browser etc.), move them in 2nd monitor etc.
3. see that apps icons do not appear on panel. If you minimize an app, the only way to access it again is through alt+tab

### Expected behaviour

When opening an app, icon should appear on panel.

### Other information

My system specs
https://pastebin.com/2gWRmD2U

**Comment by mtwebster** [comment] 2022-12-26 14:26
Duplicate of https://github.com/linuxmint/cinnamon/issues/11319

**Closed by mtwebster** 2022-12-26 14:26 UTC
Labels: New
