### ISSUE TITLE
Random Cinnamon crash, error:0 in libglib-2.0

### ISSUE THREAD

**Issue by timstoop** [linuxmint/cinnamon#10308] opened 2021-09-08 08:18 UTC
```
 * Cinnamon version (cinnamon --version): Cinnamon 5.0.5 (not using PPA)
 * Distribution: Linux Mint 20.2
 * Graphics hardware *and* driver used: VGA compatible controller: NVIDIA Corporation TU106M [GeForce RTX 2060 Mobile] (rev a1) using driver nvdia-dkms-470 (470.63.01-0ubuntu0.20.04.1)
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog:
    .xsession-errors: https://gist.github.com/timstoop/73ab67018a9bb73514fd397e392d1340
    Cinnamon crash report: https://termbin.com/4ttc
    Syslog contained way too much personal information, but I do notice the following line:
      Sep  8 09:56:10 idefisk kernel: [ 3796.113025] traps: cinnamon[4897] trap int3 ip:7fa8de2b6295 sp:7fffb274b8b0 error:0 in libglib-2.0.so.0.6400.6[7fa8de27a000+84000]
 ```

**Issue**
Cinnamon crashes this way about once a day, sometimes several times per day. I have been unable to determine if there's any thing I do that triggers the crash. X asks me if I would like to restart Cinnamon after this, which usually works fine.

**Steps to reproduce**
It seems to happen randomly.

**Expected behaviour**
No crashes.

**Other information**
Not sure what other information would be useful, but please let me know if there's anything I can contribute.

**Comment by mtwebster** [comment] 2021-09-08 13:06
Hi, this looks like a duplicate of #9916.

There are test packages available if you're interested in testing a potential fix. See this comment: https://github.com/linuxmint/cinnamon/issues/9916#issuecomment-914518352

**Closed by mtwebster** 2021-09-08 13:06 UTC
