### ISSUE TITLE
Grouped Window List: thumbnails disappearing on gap

### ISSUE THREAD

**Issue by Nitrooo** [linuxmint/cinnamon#8741] opened 2019-07-28 15:14 UTC
```
 * Cinnamon 4.0.10
   - No daily build
 * Mint 19.1
 * Radeon HD 4850, "radeon" driver
 * 64 bit
 ```

**Issue**
When you move the cursor between the panel and the thumbnail, the thumbnail disappears.
Sometimes you need to show the window by moving the cursor from the panel to the thumbnail, but this works only when you move the cursor very fast. It's frustrating.
![thumbnail](https://user-images.githubusercontent.com/3680777/62009010-20faef80-b15a-11e9-9b50-8a0d7e7cc3f6.jpg)

**Steps to reproduce**
Enable thumbnails, open a program, move the cursor on the panel icon to show the thumbnail, move the cursor on the gap between the panel and the thumbnail.

**Expected behaviour**
The thumbnail does not disappear when the cursor is on the gap.

**Comment by JosephMcc** [comment] 2019-07-29 05:33
You need to provide some more info such as the theme you are using, window list settings, etc. I can't reproduce this here. I don't even have a gap between the panel and thumbnail using Mint-Y.

**Comment by smurphos** [comment] 2019-07-29 06:23
I can reproduce this with a few themes that have a gap, but I really gave to concentrate _not to_ move the mouse fast enough to leave in the gap for long enough to the thumbnails disappear. 

The timeout is hardcoded at 50ms in line 1006 of the applet's menu.js as far as I can tell.

```
    onMenuLeave(actor) {
        if (this.state.menuOpen || this.state.panelEditMode) {
            return false;
        }

        this.shouldClose = true;

        if (actor != null) {
            this.groupState.set({thumbnailMenuEntered: false});
        }

        setTimeout(() => this.close(), 50);
    }
```

**Comment by Nitrooo** [comment] 2019-07-29 11:38
@JosephMcc 
Theme: https://www.pling.com/p/1161427/
Configuration: [config.zip](https://github.com/linuxmint/cinnamon/files/3441806/config.zip)

@smurphos 
I use a gaming mouse that has very high resolution and frequency, maybe this contribute to the issue. I don't have to be that slow, at all.

**Comment by claudiux** [comment] 2019-08-22 22:11
New option proposed in #8814.

**Comment by JosephMcc** [comment] 2019-11-27 14:14
Closing this since there is active discussion about it in https://github.com/linuxmint/cinnamon/issues/8796 and a solution is being looked at.

**Closed by JosephMcc** 2019-11-27 14:14 UTC

**Comment by brownsr** [comment] 2019-12-20 14:46
Perhaps this is a hardware related issue as like @smurphos I have to really move the cursor unnaturally slowly to trigger the thumbnails disappearing between the icon and the thumbnail.
