### ISSUE TITLE
Moving or adding panels in a multi-monitor setup confuses which monitor is set as primary

### ISSUE THREAD

**Issue by thelabcat** [linuxmint/cinnamon#12106] opened 2024-03-04 22:30 UTC
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

NVIDIA GeForce RTX 2060 SUPER

### Frequency

Always

### Bug description

I have two monitors, and the one that Cinnamon initially had set as my secondary is actually my primary, so I changed this setting. When I add a new panel and select the new location, or move an existing panel, it reliably moves to the wrong one of my two monitors.

This problem completely disappears if I use Cinnamon's original assumption of which monitor is the primary.

### Steps to reproduce

- Have two monitors.
- Change which monitor is the primary from the default.
- Add a new panel to either display. It will move to the wrong one, and the old default panel will swap monitors.
- Delete the new panel. The old default panel will move back to the primary display.

### Expected behavior

Panels stay where they are unless I move them, and they move to where I click on the display I clicked.

### Additional information

You cannot click where a panel is to put a new panel there, but you can get the new panel to go there by clicking that location on the other monitor.
I feel like there is a logical way to force a contradiction with this bug, but I forgot what it was, and I don't want to crash my desktop.

**Comment by zelimir86** [comment] 2024-04-12 20:35
Confirming this issue...

**Comment by rcalixte** [comment] 2024-04-13 02:36
Duplicate of #12064

**Closed by rcalixte** 2024-04-13 02:36 UTC
Labels: BUG
