### ISSUE TITLE
Active Application Locked When "Show Desktop" Is Clicked

### ISSUE THREAD

**Issue by madprops** [linuxmint/Cinnamon#3939] opened 2015-02-27 03:55 UTC
When I click on the "Show Desktop" button all the windows get minimized. But when I try to open the application that is active on the panel (the application that was active before I clicked the show desktop button) it doesn't open. If I click on any other application on the panel they open. I find this behavior very awkward.

**Comment by Swistaku** [comment] 2015-03-07 16:11
This must be a regression, as on Mint live (downloaded today) the problem doens't occur. However, I can confirm that after installing & updating I can notice the same problem - not only with Show Desktop applet, but also when using Super-D - last active window, when clicked on panel doesn't show up

**Comment by dalcde** [comment] 2015-05-24 17:32
Seems to be fixed in git master. Can someone confirm?

**Comment by JosephMcc** [comment] 2015-05-24 19:50
It does seemed to be fixed. When I have two windows open and activate the applet, all windows are hidden and I am able to activate the one that was active before doing it.

**Closed** 2015-08-22 05:34 UTC
Labels: BUG, BUG REPRODUCED, CLOSE IF NO INFO
