### ISSUE TITLE
Menu search should respect casing like a new word

### ISSUE THREAD

**Issue by dgp1130** [linuxmint/cinnamon#9398] opened 2020-06-25 01:38 UTC
```
 * Cinnamon version (cinnamon --version)
    * 4.2.4
 * Distribution
    * Debian Rodete
 * 32 or 64 bit
    * 64 Bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
    * [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4828638/xsession-errors.txt)
 ```

**Issue**

Searching an application name in the menu must start with the first letter of a word in that application's metadata, but many applications use special casing ie. "PulseAudio Volume Control". In this scenario, searching "Audio" does not list PulseAudio, but searching "Volume" does.

**Steps to reproduce**

* Make an application with a pascal cased name, for example add the following `.desktop` file to `~/.local/share/applications/`:

```
[Desktop Entry]
Version=1.0
Name=Foo BarBaz
Terminal=false
Type=Application
Exec=/usr/bin/ls
```

* Search "Foo", observe "Foo BarBaz" result.
* Search "Bar", observe "Foo BarBaz" result.
* Search "Baz", observe "Foo BarBaz" is **missing** from results list.

**Expected behaviour**

Searching "Baz" should yield "Foo BarBaz"

**Other information**

Many applications case their names in this fashion. I've encountered this twice recently:
* [Pulse Audio](https://wiki.ubuntu.com/PulseAudio), which has "PulseAudio Volume Control" as its full name. I kept forgetting the proper name for this, so I would search "Audio" and then be confused when it would not show up.
* [Slides Code Highlighter](https://romannurik.github.io/SlidesCodeHighlighter/), a PWA which installs with the name "SlidesCodeHighlighter". I would search "Code" or "Highlight" and this would not show up.

The only workaround I'm aware of is to find the `*.desktop` file in `/usr/share/applications/` or `~/.local/share/applications/` and edit the `Name` field to introduce spaces.

**Comment by ItzSwirlz** [comment] 2020-07-23 01:37
Essentially a dupe of #9444

**Closed** 2020-07-23 05:33 UTC
