### ISSUE TITLE
Screen brightnes needs to be corrected to be perceived for human eye as a linear change

### ISSUE THREAD

**Issue by TMarkivULCRobotics** [linuxmint/cinnamon#10911] opened 2022-07-07 19:12 UTC
```
 * Cinnamon version (cinnamon --version)  5.2.7
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - Linux Mint 20.3;
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Screen brightness change appears to be exponential 

**Steps to reproduce**
Change screen brightness

**Expected behaviour**
Linear brightness change

**Other information**
https://jared.geek.nz/2013/feb/linear-led-pwm
There is a good source of information

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by JosephMcc** [comment] 2022-07-07 20:54
Thanks for the request. I'm closing this one since I don't think it's something you're going to see much movement on. In addition your link is throwing up a warning from Firefox.

**Closed by JosephMcc** 2022-07-07 20:54 UTC

**Comment by TMarkivULCRobotics** [comment] 2022-07-08 17:19
This is really simple thing to do and it is so pleasant when it is done right. I will even provide a piece of code for this.

Am I the only one with this problem? I would think that laptop's brightness control driver would deal with it, that would make so much sense.

Here is the code for input value of PWM duty cycle in range from 0 to 1, output value is the corrected value for brightness:

Also I could edit this code for you to use input value range from 0 to 100.
```
float light_correction(float input)
{
#if 0 // Pick which one you like more
    float L = input;

    if (L <= 0.08)
    {
        L = (L / 9.033);
    } 
    else
    {
        L = pow((L + 0.16) / 1.190, 3);
    }

    return L;
#else
    return (input <= 0.08) ? input / 9.033 : pow((input + 0.16) / 1.190, 3);
#endif
}
```
I also attached a screenshot of spreadsheet with input vs output data and a little graph that shows logarithmic curve that will be used to compensate for exponential human eye light perception
![Screenshot from 2022-07-08 20-09-22](https://user-images.githubusercontent.com/39525092/178039347-9a144196-66cd-4471-a59a-2b26e429ee1c.png)
.

Do you think this is something that could be added to Linux Mint?

**Comment by JosephMcc** [comment] 2022-07-09 19:16
You emailed me about this and  just so you know, even though the issue is closed, devs still get a notification whenever someone responds to it.

> Do you think this is something that could be added to Linux Mint?

To be honest, I doubt it will be unless someone wants to pick up the idea and implement it and submit a PR that we would accept.

**Comment by TMarkivULCRobotics** [comment] 2022-07-09 20:18
Thank you for your response. 

I guess then all I can do is just hope someone buys that idea..
