### ISSUE TITLE
[improvement/feature request] centralized applets on panel

### ISSUE THREAD

**Issue by gilbertohasnofb** [linuxmint/Cinnamon#3849] opened 2015-01-24 02:00 UTC
The panel in my Linux 17.1 64-bit Cinnamon has three areas for adding applets (in edit mode, they are color coded: a red section on the left, a green section in the centre and a blue section on the right). Dragging applets to each one of them will move their icons to the left, centre and right of the panel, respectively.

The problem is the central section panel is not adding the applets to the centre of the panel itself (that is, exaclty in the middle of the screen), but rather to the centre of the green section. So if for instance an user has a lot of applets in the blue section and only the menu applet in the red section, it will make the green section be quite shifted to the left, and thus the centralized applets will look bad and not centralized to the screen (one of the typical uses of centralized applets nowadays is, for instance, to put the clock in that position). Also, when using applets such as "show/hide applets", it will move anything located in the green section since it dynamically changes the size of the blue section. 

Here are some images of what I am describing:

![a-0](https://cloud.githubusercontent.com/assets/5700795/5885695/6c79f166-a374-11e4-95b1-6653d3a620b3.png)
![a-2](https://cloud.githubusercontent.com/assets/5700795/5885696/6c915284-a374-11e4-8057-5396b12fa3aa.png)

Please let me know if I can be of any help with this.

**Comment by JosephMcc** [comment] 2015-01-24 04:21
Thanks for the great explanation of what you're after. Not sure you can really do this though. Think about it this way. If I have a panel on the bottom with a window list applet in the left area of the panel and a large number of windows open, the applet takes up more than half the panel. Now I can't have another applet centered in the area already used by the window list.
![screenshot-1](https://cloud.githubusercontent.com/assets/2231759/5886093/69ed60a4-a33d-11e4-92f9-eb49ae3e1b42.png)

**Comment by daviday** [comment] 2015-01-24 07:11
I don't think you're defining the issues/attributes re the applets properly. You should be able to simply reassign to fit your needs. Justification is ledger dependent, obviously, but if you're unable to add/remove applets from the tool bar you may be in for more work than you bargained for. 
This is a non issue for me on 15.01 btw. 

Sorry if this is not helpful.

**Comment by JosephMcc** [comment] 2015-01-24 09:05
@daviday Sorry but what are you talking about? No one said anything about not being able to add or remove applets from the panel. The original poster brought up a legitimate issue, just not sure it can be changed. And what is 15.01?

**Comment by gilbertohasnofb** [comment] 2015-01-24 12:48
@daviday thanks for the reply, but I also do not understand your message - I am sorry :(

@JosephMcc thanks for your reply, Joseph. I can see how problematic this situation can be if the "Window list applet" is active, but nevertheless we are still offering this "centralized" option regardless of the active applets, and it looks really terrible in my opinion when used with the default settings:

![a](https://cloud.githubusercontent.com/assets/5700795/5887406/76815d66-a3ce-11e4-9651-725e2e7a6319.png)

Maybe a solution could be to have a tickable option (off by default) which would force the red and blue sections to have the same size always. This way, anything in the centralized green would still be forced to the centre. But of course, with this options on there could be some large amount of empty space between the window list and the menu if the user has tons of applets in the blue section on the right, for instance.

Also, I have seen a lot of pictures of other desktop environment in several distros handling this quite well, but none of them had the window list in the panel active, so it's very difficult to judge how they are handling this.

**Comment by lestcape** [comment] 2015-01-24 21:14
Hey guys, on my opinion we are creating a problem where only could be the user preferences... Is clear the situation and what we want to have, but on a general situation this is not possible at all. Just thinking that we added several applets to one site (left or right), it's the same place, but we add several and now the sum of all applets exceeds the middle of screen, then you can not put center panel in the center of the screen on any way. So, provide a "solution" that could only apply on some cases can not be on my opinion an issues on this case and will create more problems than solutions and will be complex to be understand by user if we try to center the applets when is possible. So, i consider is the current implementation the best of possible.

**Comment by dalcde** [comment] 2015-01-24 21:18
To be honest, I don't see any need for the center panel area given that the window list always changes sizes. However, I think the default implementation should be that it tries to be as centered as possible. So if the panel is cleared, if is centered. If the window lists is long and reaches past the center, the center applets would be left justified to get near the center. Not that it's a trivial thing to do :)

**Comment by lestcape** [comment] 2015-01-24 21:38
Yes @dalcde, is not trivial, one possible solution could be set two hidden boxes on left and the right of the center panel and estimate the size of this boxes, taking the screen width and the sum of the width of the applets inside the center panel and the size of left and right panel to check if it's possible do that. On my opinion a creepy code.

**Comment by collinss** [comment] 2015-01-26 05:08
You could just use the spacer applet to balance it out...

**Comment by lestcape** [comment] 2015-01-26 05:41
@collinss, this will work only for some cases, we can not balance anything when we have applets that could modify the width dynamically (like windows list).

**Comment by gilbertohasnofb** [comment] 2015-01-26 10:47
@collinss there are also more cases in which this workaround does not work: when mounting a device, normally an applet will show that. Also, if one opens an application that has a tray icon it will affect the spacing. And on top of it all, even if the user would not use any of these applets/applications metioned, it is still a hassle to manually set something to the very centre of the screen.

**Comment by mohammad-sn** [comment] 2015-04-12 17:19
Hi! I wrote an extension that adds this option to cinnamon! :) Check it out here: http://cinnamon-spices.linuxmint.com/extensions/view/33

**Comment by gilbertohasnofb** [comment] 2015-04-12 17:24
@mohammad-sn Fantastic! Works like a charm, thanks a lot :smile:

**Comment by lestcape** [comment] 2015-04-12 17:31
@mohammad-sn thanks, could you also control the insternal panels aligment on the extension settings? https://github.com/linuxmint/Cinnamon/issues/3597
Regards.

**Comment by mohammad-sn** [comment] 2015-04-13 15:27
you're welcome :)
@lestcape i'll look into it

**Comment by lestcape** [comment] 2015-04-13 16:30
@mohammad-sn thanks, like is what your extension do, if can be generalized the behavior, to all possible position (normal, real center, left, right), will be the best... The center panel is on my opinion the most interesting at all and is the point of feature request always. So, i considere your extension really usefull.
Thanks anyway.

**Comment by gilbertohasnofb** [comment] 2015-04-14 16:42
@mohammad-sn after using your extension for a while, I am having some troubles with it. It makes any tray icon unclickable for some reason (such as Skype, or FireTray for Firefox and Thunderbird, among others).

**Comment by mohammad-sn** [comment] 2015-04-14 16:59
@gilbertohasnofb could you please provide more detail? like when does this happen? does it happen immediately after you enable the extension or in some special situation like when left (or right) panel is larger then the other? does it affect other tray icons or just some specific icons? i think your trays are at right corner of panel, right?

**Comment by gilbertohasnofb** [comment] 2015-04-14 17:14
@mohammad-sn sure, here is what I found so far: my tray icons are on the right panel, and all of them (including the System Updates, for instance) are affected. It happens some 5 minutes after I activate your extension (I can check more precisely the time if that's necessary), every time. If I kill an application and restart it, then that tray icon will work again for some short time, before becoming dead to my clicks again.

**Comment by mohammad-sn** [comment] 2015-04-14 17:29
@gilbertohasnofb does disabling extension make tray icons click-able or you have to restart applications even after disabling? I'm not able to reproduce the issue, it works just fine for me :D
are you using cinnamon's original system tray applet? which theme are you using?

**Comment by gilbertohasnofb** [comment] 2015-04-14 17:47
@mohammad-sn I have to restart all applications individually. I indeed use the original system tray applet, and my theme is Zukitwo-Cinnamon.

**Comment by mohammad-sn** [comment] 2015-04-14 17:56
@gilbertohasnofb thanks, i'll try to find out why this happens and how can i fix it, just one thing, which version of cinnamon do you use?

**Comment by gilbertohasnofb** [comment] 2015-04-14 18:26
@mohammad-sn my version is 2.4.7+recebecca. I just realized that there is a new version available (2.4.8+recebecca) which I will try soon. Thanks for having a look on it and let me know if I can be of any help!

**Comment by mohammad-sn** [comment] 2015-04-14 18:40
@gilbertohasnofb i updated the extension, i hope this helps, go to extension settings, in available extensions tab, refresh the list (at the bottom of window), then update extension.

**Comment by gilbertohasnofb** [comment] 2015-04-14 19:50
@mohammad-sn that seems to have fixed it, thanks a lot! If I find any other problem, I will report it to you. I really appreciate all your help.

**Comment by mohammad-sn** [comment] 2015-04-14 20:18
@gilbertohasnofb  thanks, i am happy to have helped you :)

**Comment by dalcde** [comment] 2015-05-04 22:00
https://github.com/linuxmint/Cinnamon/commit/3a664285eb031b26c3f432a58b33ce0ac89a3758

**Closed by dalcde** 2015-05-04 22:00 UTC
