### ISSUE TITLE
Window size, position, maximized status of a new opened window especially with dual monitor setup

### ISSUE THREAD

**Issue by mibuthu** [linuxmint/Cinnamon#1199] opened 2012-09-26 17:47 UTC
I have a dual monitor setup with the primary monitor on the right and the secondary monitor on the left. I'm using cinnamon 1.6.
The size, position, screen and maximized status of at least some application is wrong after loading.

Examples:

Thunderbird:
Don't save the size, position, screen, maximized status at all.

Firefox:
If I close Firefox not in maximized status everything works as expected - Firefox opens on the same screen with same size and position than it was closed the last time.
If I close Firefox in maximized status Firefox also opens maximized again, but always on the left screen.

Nemo:
If I close Nemo not in maximized status it will start with the same size but the position is not saved and always the same and always on the primary screen.
If I close Nemo in maximized status it opens maximized again, also on the correct screen, but if I change the folder (double click on a folder) the window always jumps to the left screen.

gedit:
If I close gedit not in maximized status it will start with the same size but the position is always the same and always on the primary screen.
If I close gedit in maximized status it also opens maximized again, but always on the left screen.

Terminal:
Don't save the size, position, screen, maximized status at all.

I also tried this in Gnome Shell to compare the behavior. Some of these issues are the same there, but some are also different.
I don't know if all of this issues can be fixed in cinnamon or if some of them are problems of the applications itself.

**Comment by JosephMcc** [comment] 2016-09-05 08:13
Are any of you still having the problem in Cinnamon3?

**Comment by nmjbhoffmann** [comment] 2016-09-13 14:54
Me me me, I do, I do!

If I have a window (say 800x600px) open, and maximize it then close it, When I open it again, it opens maximized as expected, but when you restore the window, it restores it to a sort of maximized window and not the original 800x600 size.

I also have the issue where it opens on my left most monitor, but only in certain applications (Like Firefox), but not all, Atom opens on the correct screen, but still has the maximized window issue.

This is in Cinnamon 3.0.6 in LMDE.

**Comment by JosephMcc** [comment] 2016-09-13 16:48
> If I have a window (say 800x600px) open, and maximize it then close it, When I open it again, it opens maximized as expected, but when you restore the window, it restores it to a sort of maximized window and not the original 800x600 size.

This depends on the application. Some applications remember and save their size when closed and others do not. I can't reproduce this with Cinnamon settings for example. The fact that is doesn't restore to the original 800x600 size isn't really a bug either. When you maximize a window the WM saves that unmaximized size in memory so it can return to it. Once you close the window it's gone as far as the WM is concerned and that old size goes with it.

**Comment by nmjbhoffmann** [comment] 2016-10-01 11:37
The ones that open from originally maximized windows always open with the same window dimensions, is it not possible to add a check for when you open a program and the window is close enough to the maximized resolution to just set it maximized?

**Comment by JosephMcc** [comment] 2018-02-17 23:04
The original report here is about how different applications handle things. That isn't under our control and some apps override compositor behaviour.

**Closed by JosephMcc** 2018-02-17 23:04 UTC
Labels: BUG
