### ISSUE TITLE
Cinnamon crashes while moving taskbar icon

### ISSUE THREAD

**Issue by Symbiont123** [linuxmint/cinnamon#10707] opened 2022-03-15 17:56 UTC
* Cinnamon 5.2.7
 * Linux Mint 20.3 Una 64 bit
 * Kernel 5.4.0-104-generic
 * AMD Trinity [Radeon HD 7500G]

Cinnamon crashes while moving taskbar icon of application that was NOT pinned to taskbar before. While dragging the icon press key <Escape> to release the icon. Cinnamon crashes (reproduced every time). Expected behavior: The icon should move back to its position. - Thanks for fixing this issue in advance!

**Comment by fredcw** [comment] 2022-03-24 09:23
Confirmed: Seems to be problem with GWL applet.

To reproduce: Start dragging a pinned app to another location on the applet, as if to rearrange your pinned apps. Instead of letting go of mouse, press space instead. Cinnamon doesn't crash but becomes unresponsive with the following message in .xsession-errors:

```
(cinnamon:835): Cjs-CRITICAL **: 09:10:03.660: JS ERROR: TypeError: this.target is null
_onEvent@/usr/share/cinnamon/js/ui/dnd.js:193:21
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
_getEventHandlerActor/<@/usr/share/cinnamon/js/ui/dnd.js:57:63
```

The above message is repeated for each subsequent mouse click but cinnamon is unresponsive and a reboot is required.

**Comment by JB-FE** [comment] 2022-03-24 13:27
System Hang - Cinnamon 5.2.7 - Linux-Mint 20.3

Start dragging and press the ESC key on the keyboard to cancel the move.
Regards.

**Comment by fredcw** [comment] 2022-03-24 20:17
Now that I test it again, space doesn't do anything but ESC causes a freeze instead.

**Comment by jonath92** [comment] 2022-04-20 12:27
> Now that I test it again, space doesn't do anything but ESC causes a freeze instead.

This is a duplicate of https://github.com/linuxmint/cinnamon/issues/10618

**Comment by yungthai** [comment] 2024-03-18 00:36
I have noted this occasionally happens when accidentally moving / dragging the multiple Brave browser icons in the taskbar.

Afterwards, mouse pointer can move, but does not respond to mouse clicks. Enter/Return key also unresponsive e.g. when trying to shutdown via the graphical UI.

Ctrl+Alt+F2 worked, and able to shutdown / reboot from there.

System info
```
$ cat /etc/linuxmint/info
RELEASE=21.1
CODENAME=vera
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 21.1 Vera"
DESKTOP=Gnome
TOOLKIT=GTK
...
GRUB_TITLE=Linux Mint 21.1 Cinnamon
```

**Closed** 2024-04-19 08:16 UTC
