### ISSUE TITLE
Background Slide Show Feature keeps disabling 

### ISSUE THREAD

**Issue by mort8088** [linuxmint/Cinnamon#7236] opened 2018-01-29 18:23 UTC
```
 * Cinnamon version 3.6.7+sylvia
 * Distribution Mint 18.3 64 bit
 * Nvidia GTX-1050 - driver version 384.111-0ubuntu0.16.04.1
 ```
Randomly the "Play backgrounds as a slideshow" gets disabled all the other settings remain.
I know that's super vague but it's what happens, not the same background that it gets stuck on.
It doesn't seem to happen when I run any particular application. just after a while it'll disable the option.
**Steps to reproduce**
It's seems random.
**Expected behaviour**
system settings shouldn't just change on their own.
**Other information**
Not sure if this is the best place for this but... sorry if it's not. :-)

**Comment by JosephMcc** [comment] 2018-02-12 05:19
Ok. I'm testing this here to see if I can reproduce. Without more info to go on there isn't much we can do. When this happens possibly check the output of your ~/.xsession-errors and see if anything looks relevant. Closing it for now but can reopen if we get some more info.

**Closed by JosephMcc** 2018-02-12 05:19 UTC

**Comment by tzvishmuel** [comment] 2018-11-12 08:05
The same thing happens to me, and I also can't supply more info because I don't notice it right away...after a day or two I notice that I keep seeing the same background image.  Same Cinnamon/Mint versions.

The only possibly relevant additional detail is that I noticed it this morning, and yesterday Cinnamon crashed; I got the message saying it was running on a backup copy and it offered me a restart option.
