### ISSUE TITLE
scrolling on the battery icon should never decrease brightness to zero 

### ISSUE THREAD

**Issue by real-or-random** [linuxmint/Cinnamon#5063] opened 2016-02-03 18:59 UTC
The brightness slider in the battery applet has a minimum value to ensure that the user does not accidentally set the brightness to 0.

However, when decreasing the brightness by scrolling on the battery icon, setting the brightness to 0 is possible. If you move the mouse then, good luck! ;)

**Comment by Vahan86** [comment] 2016-12-01 07:20
Checked in Cinnamon 3.0.7.  The issue is still there.

**Comment by joaoclemencio** [comment] 2017-01-16 20:10
Cinnamon 3.2.7, not the same issue but similar.

Battery applet working OK, both scrolling and dragging.

However, using keyboard shortcuts the screen turns off if brightness is turned down to the end.

**Comment by JosephMcc** [comment] 2017-11-26 01:20
https://github.com/linuxmint/Cinnamon/issues/7080

**Closed by JosephMcc** 2017-11-26 01:20 UTC
Labels: BUG REPRODUCED
