### ISSUE TITLE
Menu applet - search: name field prioritization not working or too limited

### ISSUE THREAD

**Issue by s44i7h-sam** [linuxmint/cinnamon#8166] opened 2018-12-20 14:09 UTC
```
 * Cinnamon version 4.0.8
 * Distribution - Mint 19.1
 ```

**Issue**
Menu applet does not prioritize applications whose name contains in some way the searched pattern or word. Instead it threats the `Name=` field the same as any other searched field like `Keywords=`.

**Steps to reproduce**
Open the menu applet and watch the results as you type *`s` `t` `a` `r` `t`*. "LibreOffice" is shown at the top of the list instead of the more obvious "Startup Applications" whose name actually matches the regex pattern `\bstart`.
Another example: type *`s` `c` `r` `e` `e` `n` `s`* and watch the results as you type - "Screensaver" and "Screenshot" remain at the bottom of the list.
The issue is the same even if the whole word is typed out. I have a custom .desktop file which includes the whole word "def" in its `Name=` field. When typing *`d` `e` `f`* "Preferred Applications" is shown first because its `Keywords=` field contains "default". To reproduce this add the word "def" to some .desktop file's `Name=` field.

**Expected behaviour**
Those applications which contain the searched pattern in the name itself should be shown first. The applet should perform (on the `Name=` field) a regex search (not regex match!) for `\b${pattern}` (start of *any* word in the name).

**Other information**
This issue has to do with the `_listApplications` function in the `/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js` file.
The LM 18.3 version of this applet seemed to work better in this regard, so a look at recent changes of the `_listApplications` function could be helpful.

**Comment by s44i7h-sam** [comment] 2018-12-20 17:01
After playing a bit with the code in the `_listApplications` function I realised that this function itself already works somewhat according to the expected behavior (see above). The name results are added to the `res` array first, then other fields are searched for, going through each application again, with the effect that `res` can contain duplicates (in case both name and some other field of the same application contain the pattern).

---

Here's the updated report (steps to reproduce are the same as above):

**Issue**
The problem is rather in the `_displayButtons` function where the order of the `res` array (now named `apps`) is not maintained because the function merely goes through the whole application list in the default (alphabetical) order and calls show() and hide() for each application button based on whether that application is in the `apps` array.

**Expected behaviour**
The order of the search results should be maintained when displaying application buttons: matches by name first, then matches by other fields after that. Perhaps by replacing `this._applicationsButtons` array with a new one on each `_doSearch` call, if that does not introduce new issues elsewhere, or by having a completely separate array (e.g. `this._resultButtons`) shown in the result pane/list from the start.

---

As for the duplicates in the `res` array of the `_listApplications` function mentioned above: one possible solution is to go through the application list only once instead of twice, adding an application to either `resByName` or `resByOther` array, depending on which field matches. Then after the loop call `res = resByName.concat(resByOther)`. It's a simple modification of the existing code:

    if (pattern){
        let resByName = [];
        let resByOther = [];
        let regexpPattern = new RegExp("\\b"+pattern);
        for (let i in this._applicationsButtons) {
            let app = this._applicationsButtons[i].app;
            let latinisedLowerName = Util.latinise(app.get_name().toLowerCase());
            if (latinisedLowerName.match(regexpPattern) !== null) {
                resByName.push(app.get_id());
                if (!exactMatch && latinisedLowerName === pattern)
                    exactMatch = app.get_id();
            }
            else if (Util.latinise(app.get_name().toLowerCase()).indexOf(pattern)!==-1 ||
                     (app.get_keywords() && Util.latinise(app.get_keywords().toLowerCase()).indexOf(pattern)!==-1) ||
                     (app.get_description() && Util.latinise(app.get_description().toLowerCase()).indexOf(pattern)!==-1) ||
                     (app.get_id() && Util.latinise(app.get_id().slice(0, -8).toLowerCase()).indexOf(pattern)!==-1))
                resByOther.push(app.get_id());
        }
        res = resByName.concat(resByOther);
    } else res = applist;

**Comment by icarter09** [comment] 2018-12-23 15:14
@s44i7h-sam good job on troubleshooting the issue. Does your modification work? I'm going to test out your solution as well.

**Comment by icarter09** [comment] 2018-12-23 16:01
@s44i7h-sam I think the whole problem is this section of code...
`
else if (Util.latinise(app.get_name().toLowerCase()).indexOf(pattern)!==-1 ||
                 (app.get_keywords() && Util.latinise(app.get_keywords().toLowerCase()).indexOf(pattern)!==-1) ||
                 (app.get_description() && Util.latinise(app.get_description().toLowerCase()).indexOf(pattern)!==-1) ||
                 (app.get_id() && Util.latinise(app.get_id().slice(0, -8).toLowerCase()).indexOf(pattern)!==-1))
`

**Comment by s44i7h-sam** [comment] 2018-12-24 11:19
I think the `_listApplications` functions *should* check some other .desktop fields that are not apparent to the user, such as the description and the keyboard field. *However*, name matches should be shown at the top of the list.
My modification above will make `_listApplications` return such prioritized list because it keeps name matches and "other" matches in two separate lists, then concatenates them afterwards (see `res = resByName.concat(resByOther);` above).
Your fix has visual effect only because it is actually limiting the search results, however it does not solve the ordering problem. And it still goes through the application list twice and duplicates items. You might as well just remove the second loop, and it will do the same thing visually.

But **the core of the problem** is rather in the `_displayButtons` functions because that function *ignores the order*. It merely goes through the existing alphabetically ordered list of all applications (`this._applicationsButtons`) and shows those that are in the filtered list (generated by `_listApplications`), thus keeping the alphabetical order and ignoring the order of the filtered list. To summarize: *currently the only effect of the filtering is what is shown but not the order it is shown in*.

So it's a bit tougher problem because you would have change the logic of how the buttons are displayed. The current show/hide logic would have to be replaced by something else.
Here's one way to do it:

 - On search go through a static and alphabetical application button list, filtering the buttons into a new list, in a similar way as my modification of `_listApplications` above. *However*, this time push buttons themselves to the result list instead of just app ids (e.g. `res.push(app)` instead of `res.push(app.get_id())`)!
 - Then in the `_displayButtons` function show this generated list itself, instead of modifying the show/hide flags of the alphabetical list.
 - When the search input is empty show the alphabetical list instead.

This is only a start, because the search could be optimized a lot by further filtering the already filtered list when the user merely adds more letters to the current pattern. That is, if the user already typed in "scree" and now added "n", the search function does not need to go through the whole application list yet again.
Such optimization would require storing the previous pattern in order to compare to the current one: *if* current pattern starts with previous pattern *then* filter through already displayed buttons instead of the whole application list yet again.
But let's leave such optimizations for later.

**Comment by icarter09** [comment] 2018-12-24 12:39
@s44i7h-sam I'm confused on your comment on why you think typing "Screen" should return "Power Management"? Is that because the word "screen" is contained within the "Power Management" applet? If that is the case, then there is the chance that every word searched for will probably be contained within an applet or two. I get that pushing the name to the top of the search results would be one way to address the returned results, but that is not intuitive to a user. If the search is going to search on more then the displayed name, then a user needs to be alerted to that fact.

**Comment by icarter09** [comment] 2018-12-24 12:48
@s44i7h-sam Feel free to fix the current PR to make the search better however you see fit. Whether it be to include the other search fields or remove the second loop. 
Personally, I don't want the search to go beyond the Application Names, since that is what I've always expected the search to work against. Now if it has always been searching on more behind the scenes and makes it look like it has only been searching against the Application Names, then my PR should be negated. 
If you look at #8070, you'll see that is another group of users that are all expecting the search results to return only the Application Names that match the search.

**Comment by icarter09** [comment] 2018-12-24 14:15
@s44i7h-sam I removed my PR since that logic still needs to be in place.

**Comment by Curly060** [comment] 2019-01-03 01:31
@s44i7h-sam The trouble is that the whole menu is 'pre-built' and all interactions with it actually only call a 'hide' or 'show' operation on the buttons. So you can't just generate a list of buttons and display those.

The whole thing is really old and has been discussed in great detail here: #4053 

I had made PR #6929 which made the search far more usable, but raised other problems and over time accidentally got reverted which resulted in regression #8070 

I have now made another attempt in finally fixing this in a manner that's acceptable for most. It's still a workaround, but hopefully this time one people can live with.
Have a look at my PR #8251 

Cheers, Curly060 =;->

**Comment by NikoKrause** [comment] 2020-09-22 05:52
Fixed by https://github.com/linuxmint/cinnamon/commit/a6738bd306180b4e2e668c90c1d7d5d6c0578906

**Closed by NikoKrause** 2020-09-22 05:52 UTC
