### ISSUE TITLE
cinnamon-settings sound problem

### ISSUE THREAD

**Issue by marcelitocs** [linuxmint/cinnamon#7627] opened 2018-06-08 06:49 UTC
```
 * Cinnamon version 3.4.6
 * Distribution - Linux Mint 18.2 Sonya
 * 64 bit
 ```

**Issue**

cinnamon-settings sound controls does not work and does not show sound devices. But if I sign in with another user on my computer, it work and shows the devices.

The controls to change the volume on the keyboard also do not work. When I change the volume by the alsamizer on the terminal, it works normally

**Comment by claudiux** [comment] 2018-06-08 14:16
Can you please post some screenshots with cinnamon-settings output tab and alsamixer view, for each user?

**Comment by marcelitocs** [comment] 2018-06-08 21:03
my user
![screenshot from 2018-06-08 17-57-11](https://user-images.githubusercontent.com/17323064/41180826-fbe7ee38-6b45-11e8-9055-7d4c98ccdef1.png)

another user
![captura de tela de 2018-06-08 17-59-24](https://user-images.githubusercontent.com/17323064/41180825-fbb5ef1e-6b45-11e8-819e-f690a26a625d.png)

**Comment by claudiux** [comment] 2018-06-08 23:38
Do users have the same rights? Are they part of the same groups?

**Comment by marcelitocs** [comment] 2018-06-10 20:06
```
marcelito:~ $ groups visitante
visitante : visitante nopasswdlogin
marcelito:~ $ groups marcelito
marcelito : marcelito adm cdrom sudo dip plugdev lpadmin sambashare docker
```

**Comment by marcelitocs** [comment] 2018-06-12 00:19
> What is the first user connected? marcelito or visitante? Did you disconnect the first user before connecting the second?

I already tested by first entering one after a reboot, then another, and the order was indifferent.

**Comment by claudiux** [comment] 2018-06-12 21:06
I am looking for a possible bug (I can't reproduce it). I will compare the codes of versions 3.4, 3.6 and 3.8 of Cinnamon. It will take a little while.

**Comment by wujastyk** [comment] 2018-08-16 22:04
I am not sure if this is the same problem, but I hope so.

The following report applies to two Thinkpad T500s and a T560, all running Linux 4.15.0-32-generic amd64 and the new Cinnamon 19, updated today (16 August).

I have a Blue Snowball USB microphone.  It's meant to be plug-n-play, and on the WWW several users report no problems with using it on Linux/Mint in the past.  When I plug it in (or reboot with it attached), the microphone is seen (red light on mic) but the USB connection is not recognized properly and the microphone does not show up in Sound settings or in Pulseaudio pavucontrol.

Below, I append an extract from /var/log/syslog after plugging in the mic.

Dominik

Syslog extract:

Aug 16 15:45:01 Panini kernel: [ 6025.694703] usb 1-4: new full-speed USB device number 9 using xhci_hcd
Aug 16 15:45:04 Panini dbus-daemon[1984]: [session uid=1000 pid=1982] Activating service name='org.gnome.Terminal' requested by ':1.97' (uid=1000 pid=19272 comm="/usr/bin/gnome-terminal.real " label="unconfined")
Aug 16 15:45:04 Panini dbus-daemon[1984]: [session uid=1000 pid=1982] Successfully activated service 'org.gnome.Terminal'
Aug 16 15:45:12 Panini kernel: [ 6036.153432] usb 1-4: New USB device found, idVendor=0d8c, idProduct=0005
Aug 16 15:45:12 Panini kernel: [ 6036.153439] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Aug 16 15:45:12 Panini kernel: [ 6036.153444] usb 1-4: Product: Blue Snowball 
Aug 16 15:45:12 Panini kernel: [ 6036.156802] usb 1-4: can't set config #1, error -32
Aug 16 15:45:12 Panini mtp-probe: checking bus 1, device 9: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-4"
Aug 16 15:45:12 Panini mtp-probe: bus: 1, device: 9 was not an MTP device
Aug 16 15:45:12 Panini upowerd[1432]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-4
Aug 16 15:45:12 Panini kernel: [ 6036.227477] [UFW BLOCK] IN=wlp4s0 OUT= MAC= SRC=fe80:0000:0000:0000:89ad:71de:367a:9971 DST=ff02:0000:0000:0000:0000:0000:0000:0001 LEN=64 TC=0 HOPLIMIT=1 FLOWLBL=931081 PROTO=UDP SPT=8612 DPT=8612 LEN=24 
Aug 16 15:45:12 Panini kernel: [ 6036.227494] [UFW BLOCK] IN=wlp4s0 OUT= MAC= SRC=fe80:0000:0000:0000:89ad:71de:367a:9971 DST=ff02:0000:0000:0000:0000:0000:0000:0001 LEN=64 TC=0 HOPLIMIT=1 FLOWLBL=947506 PROTO=UDP SPT=8612 DPT=8610 LEN=24 
Aug 16 15:45:12 Panini kernel: [ 6036.237971] [UFW BLOCK] IN=wlp4s0 OUT= MAC= SRC=fe80:0000:0000:0000:89ad:71de:367a:9971 DST=ff02:0000:0000:0000:0000:0000:0000:0001 LEN=64 TC=0 HOPLIMIT=1 FLOWLBL=931081 PROTO=UDP SPT=8612 DPT=8612 LEN=24 
Aug 16 15:45:12 Panini kernel: [ 6036.238153] [UFW BLOCK] IN=wlp4s0 OUT= MAC= SRC=fe80:0000:0000:0000:89ad:71de:367a:9971 DST=ff02:0000:0000:0000:0000:0000:0000:0001 LEN=64 TC=0 HOPLIMIT=1 FLOWLBL=947506 PROTO=UDP SPT=8612 DPT=8610 LEN=24 
(END)

**Comment by Vahan86** [comment] 2019-11-30 06:04
@marcelitocs, is this still an issue for you in Cinnamon 4.2?

**Comment by wujastyk** [comment] 2019-11-30 11:07
Thanks for checking.  I'm travelling at present (in India).  When I get back home in a couple of weeks I'll test the current Linux Mint release with the Snowball mic.

**Comment by marcelitocs** [comment] 2019-11-30 20:22
> @marcelitocs, is this still an issue for you in Cinnamon 4.2?

To work around the issue, I switched to a new user and removed the old one.

**Comment by wujastyk** [comment] 2019-12-15 02:33
This is still an issue.  The Blue Snowball USB microphone isn't recognized.
Linux Mint 19.2 Cinnamon.

I'll try creating a new user account.

**Comment by wujastyk** [comment] 2020-04-24 17:30
This is indeed still an issue, on four different Thinkpads running Linux Mint Cinnamon.   This includes a Thinkpad X Carbon that recently ran Windows 10 and recognized the microphone just fine.  Wiped the machine, installed Mint, and no more microphone.  Same as all my Mint machines.  However, I have an old Zoom H2 that can function in USB mode, and that is recognized.  Also, a Blue Yeti [url]https://www.bluedesigns.com/products/yeti/[/url] (taller, vertical format)

So, after this A/B testing, it's not the cable, it's not the laptop hardware, it's not other Blue microphones or USB microphones in general. It's specifically Linux Mint not seeing the Blue Snowball.

**Comment by collinss** [comment] 2020-04-26 16:39
@wujastyk Is it working correctly for you in Pulse Audio Volume Control? (You may need to install it - `apt install pavucontrol`)

**Comment by wujastyk** [comment] 2020-04-26 17:39
It does not appear as a device in any sound software including pavucontrol

**Comment by collinss** [comment] 2020-04-26 18:21
Ok, in that case it is most likely an issue with pulse audio or your kernel. Either way, it is not an issue with Cinnamon, or with Mint in general, and is therefore outside of our control. You might try a newer kernel version though, and see if that resolves your issue. Sorry we can't do more!

It sounds like the op's problem was resolved as well, so I'm going to go ahead and close this. If any experience the original issue in the future, feel free to comment here. We'll still see it even though it's closed, and we can reopen it if need be.

**Closed by collinss** 2020-04-26 18:21 UTC

**Comment by wujastyk** [comment] 2020-04-26 18:42
I use the latest 5.3 kernel (currently 5.3.0-46).  It's not a problem with pulse audio, which recognizes other USB microphones just fine (e.g., an old Zoom H2 and a Blue Yeti). This is a very specific problem recognizing the Blue Snowball microphone.  I have four different laptops all Linux Mint Cinnamon 19.3, two of them recently wiped and re-installed, so very clean and up-to-date. they all throw the same
`kernel: [ 6036.156802] usb 1-4: can't set config #1, error -32`
error when the Snowball is plugged in, and then the mic is not recognized by any software.

Personally, looking around the web, I think it might be a problem with udev.  But I don't have the chops to diagnose or fix it myself.
