### ISSUE TITLE
default menu behaviour polish

### ISSUE THREAD

**Issue by beastr45** [linuxmint/cinnamon#11547] opened 2023-03-09 00:23 UTC
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 21, Arch, Fedora 37, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
cinnamon version 5.6.7
### Issue
with the default cinnamon menu included in linux mint it is possible to make the taskbar and the menu to overlap. 

### Steps to reproduce
In order to reproduce this bug set the taskbar to hide. Then press the windows icon key and the taskbar will overlap with the menu

### Expected behaviour

the expected behaviour would be for the menu to place itself above the taskbar or to have some sort of logic to position the menu under certain conditions.

### Other information
I have checked if this is fault of my desktop theme, it is not.

### Configuration info, if applicable
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

This is related to the default menu applet in Linux mint. I am not sure if this behaviour replicates with other menu's or if the same menu desk-let is in use in normal cinnamon. nevertheless someone could very easily fix this in around 5 minutes.

**Comment by fredcw** [comment] 2023-04-29 04:44
Duplicate of #10970

**Comment by fredcw** [comment] 2023-08-08 20:25
This issue was fixed by 11788 above and can be closed.

**Closed** 2023-08-11 14:53 UTC
Labels: New
