### ISSUE TITLE
Window moving and tiling behavior with multiple monitors

### ISSUE THREAD

**Issue by raqua** [linuxmint/cinnamon#4526] opened 2015-08-18 16:37 UTC
I am on Mint 17.2. I am using additional monitor with my laptop in dual monitor extended setup. 
I believe that window positioning and tiling does not work as expected. 
First - positioning: Both screen are regarded as one giant screen. So when I want to position window that is on main screen (on 2 screen setup the one on the right) to the top left corner of this screen it is moved to other screen's corner instead. Please see attached pictures:

Top right
![screenshot_workspace 2_002](https://cloud.githubusercontent.com/assets/1541886/9336067/cb10da9a-45d7-11e5-8f18-be6fc7b9600c.jpg)

Bottom right
![screenshot_workspace 2_003](https://cloud.githubusercontent.com/assets/1541886/9336077/df4ee704-45d7-11e5-9925-f40946c943b7.jpg)

Top left
![screenshot_workspace 2_004](https://cloud.githubusercontent.com/assets/1541886/9336084/ed3ebdd0-45d7-11e5-89fb-c34d18488f3d.jpg)

Bottom left
![screenshot_workspace 2_005](https://cloud.githubusercontent.com/assets/1541886/9336091/f480f40a-45d7-11e5-8907-a001d07d73d4.jpg)

I believe that this functionality should not move windows between screens, because there are other shortcuts for that and that it is expected behavior that window moves only on the same screen. 

Also please note that the screens do not have the same resolution and when window is moved to bottom left, it is also getting partially hidden outside of the screen.

Tilling works fine on main screen, but when I attempt it on secondary (laptop) screen, window is moved to the main screen and tiled there. 

The last issue is that when starting certain apps (i.e. Intellij Idea), it starts with centered small screen, where one can select project. This screen is centered on both screens - resulting in being in the middle. See image:
![screenshot_workspace 1_001](https://cloud.githubusercontent.com/assets/1541886/9336245/db59094e-45d8-11e5-8143-101f4ee0121f.jpg)

**Comment by tp0** [comment] 2015-09-01 19:17
This is because the desktop is treated as a single rectangle encompasing all monitors.

Because of this issue I use the "Push tile left/right/up/down" shortcuts instead, pretty much achieves the same thing except that they resize the window to 1/4 size at the same time..

The last thing has been fixed: https://github.com/linuxmint/muffin/pull/201

**Comment by raqua** [comment] 2015-09-01 19:51
Yes, I got that part, but it is imho not correct. Desktop should not be treated (at least in this regard) as a single rectangle. I am not sure, whether this is Cinnamon or Xrandr issue. 
Tiling instead does not work for me, because most of the time, I want to keep the window size, just position it in the corner. That is the most often use case I do have. And it works correctly also only on main monitor as I mentioned above.

**Comment by JosephMcc** [comment] 2015-09-01 20:17
@raqua How are you tiling the window? I use multiple monitors and have no issues with tiling on either screen. How are you producing the effect shown in the screenshots? By moving the windows with hotkeys?

**Comment by raqua** [comment] 2015-09-02 14:14
It does not matter what method I use, both keyboard shortcut and also dragging window to corner has the same result:

A) main monitor 
 - tiling to up, bottom, right, top right, bottom right works as expected
 - tiling to left, top left, bottom left does not as it is the inside between two monitors
B) secondary screen
 - tiling to right, top right, bottom right does not work
 - tiling to top, top left moves the window and tils it on the main monitor
 - tiling to bottom, left bottom 
      - with mice: does not work as the screen resolution is smaller than on the main monitor and I can not reach it with mice
     - with keyboard : screen is moved and tiled to main screen

**Comment by f3l1x** [comment] 2016-03-19 13:46
Same issues by me.

=/

**Comment by ManIVIctorious** [comment] 2016-09-06 10:20
I just tried to reproduce this, could you please provide more info on how exactly you are tiling the windows? It seems to work fine here (cinnamon 3.0.7 Arch Linux)

**Comment by raqua** [comment] 2016-09-06 13:47
Just tested in on Cinnamon 17.3. 

I am not tilling the windows, I am repositioning them using keyboard shortcuts. 
See attached picture for the idea
![screenshot from 2016-09-06 15 45 43](https://cloud.githubusercontent.com/assets/1541886/18275869/17350a2c-7449-11e6-9c22-c23eacf6c6dd.png)
. 
I am not sure, which part is not clear to you, so if this does not answer that, please be more specific.

**Comment by ManIVIctorious** [comment] 2016-09-06 14:53
I just tried these commands (well, had to assign them manually) and it seems they are working in my setup.
Move window to upper-left/right lower-left/right do as expected without moving the windows to the other screen.

My monitors don't have the same resolution either, maybe its somehow related to the way you setup your monitors? I used the standard display settings provided by cinnamon-settings

**Comment by raqua** [comment] 2016-09-06 15:09
Ok, I have retested again, with some changed results (note - I am using now higher Cinnamon version because of OS update since the report). 

The first issue is partially solved. That means, that moving the windows on **main** monitor works as expected. But using the keyboard shortcut on a window that is placed on secondary monitor results in moving this window (and placing it to desired position) on main monitor. 

Starting Intellij Idea (and few other) apps with centered splash screen still results in splash screen placed half on main monitor and half on secondary monitor. 

When I try window tilling as described in my last example, it works as expected on main monitor. On secondary monitor I can not snap it to left or bottom egde due to my main screen having higher resolution and therefore I could not drag it to the edge. I can drag it to top edge of secondary monitor, which results in the window moved to main monitor and tiled to top part of it, as expected, but on wrong monitor. 
See attachment for my monitor setup. I do not think there is anything fancy there. 
![screenshot from 2016-09-06 17 07 50](https://cloud.githubusercontent.com/assets/1541886/18279104/998d5028-7454-11e6-9224-7f03f67a7e63.png)

**Comment by Vahan86** [comment] 2020-01-26 11:10
@raqua, is this still an issue in Cinnamon 4.4?

**Comment by raqua** [comment] 2020-01-26 11:27
@Vahan86 I don't have machine with 4.4, but it now works fine even in a previous version.

**Comment by Vahan86** [comment] 2020-01-26 12:20
@raqua, thanks for the update.
@icarter09, can we close the issue?

**Closed** 2020-01-26 12:39 UTC
Labels: BUG
