### ISSUE TITLE
Key binding [Super] + [Space] does result in "Next Group" and not working

### ISSUE THREAD

**Issue by georf** [linuxmint/cinnamon#10236] opened 2021-07-25 21:26 UTC
```
 * Cinnamon version: 5.0.5
 * Distribution: Linux Mint 20.2
 * 64 bit
 ```

**Issue**

When I create my own key combination, I get an error. I want to use the combination of Super and Space. After entering, "Next Group" appears. If I use the combination nothing happens. When I press the spacebar alone, the combination is triggered.

Before the update to Mint 20.2 this combination worked without problems.

**Steps to reproduce**

Create an own key binding with combination of Super and Space.

**Expected behaviour**

The bindings triggers the command.

**Comment by icarter09** [comment] 2021-07-31 18:12
Cinnamon 5.0.5
Mint 20.2 64bit

What is the action your assigning for your key combination? When I reassign a current key combination to use `Super + Space`, it works as expected.

**Comment by georf** [comment] 2021-08-01 19:01
![Auswahl_042](https://user-images.githubusercontent.com/361453/127782355-611aa0a9-f3d4-4309-823f-68160496b06c.png)

My action is `guake -t`.

Did your test result in `Next Group` too?

**Comment by icarter09** [comment] 2021-08-01 19:27
Thanks. I installed guake and created a custom shortcut for `guake -t` that works with the key combo of `Super + Space`. My test did not result in `Next Group`.

**Comment by icarter09** [comment] 2021-08-01 19:32
@georf I am able to reproduce this issue on another box that is not using the daily builds.

**Comment by georf** [comment] 2021-08-01 19:33
xev gives this output on pressing *Super*:

```
KeyPress event, serial 38, synthetic NO, window 0x7200001,
    root 0x7a6, subw 0x0, time 104715505, (619,613), root:(1480,1067),
    state 0x10, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by georf** [comment] 2021-08-01 19:34
> @georf I am able to reproduce this issue on another box that is not using the daily builds.

So I need to wait for an update? Or what is the procedure now?

**Comment by icarter09** [comment] 2021-08-01 19:44
You can wait for an update if you want. I'm currently looking over commits to find the exact one so you could apply it and pick up the fix. Also trying to verify that being on the daily builds is why it's working on one machine and not the other.

**Comment by mtwebster** [comment] 2021-08-03 14:59
Hi, it looks like you have have the 'next group' keyboard layout shortcut enabled:
![image](https://user-images.githubusercontent.com/262776/128037331-5cb14b75-a9a6-4ec4-9559-51f5478e9ace.png)
Go to keyboard settings, Layouts, then the options button in the lower right corner. Expand "Switching to another layout" and uncheck 'Win-Space` (It's the last checkbox in the list).

Then if you re-teach your shortcut, it should recognize it as Super+Space.

Unfortunately this sort of collision happens occasionally (the mechanism for the layout switching shortcuts is different from the other cinnamon keybindings), though I think most people that need to make use of keyboard layout switching know not to try to assign that elsewhere.

**Closed by mtwebster** 2021-08-03 14:59 UTC

**Comment by georf** [comment] 2021-08-03 19:21
Thank you! That was the key.

Now that you mention it, I remember that this key combination also changes the layout in Windows. But I didn't know about these options until now.
