### ISSUE TITLE
Lock screen doesn't ask password - Cinnamon 3.2.6

### ISSUE THREAD

**Issue by chirag7jain** [linuxmint/Cinnamon#6152] opened 2017-01-02 08:11 UTC
command to lock - ctrl + alt + l

Linux mint - 18.1
Cinnamon - 3.2.6

**Comment by leigh123linux** [comment] 2017-01-02 09:42
Duplicate of https://github.com/linuxmint/cinnamon-screensaver/issues/194

**Closed by leigh123linux** 2017-01-02 09:42 UTC
