### ISSUE TITLE
VLC full-screen doesn't work; VLC developer says Cinnamon is the cause.

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6566] opened 2017-05-26 00:53 UTC
When using the 'VLC Media Player', the only way I can make videos enter full screen is by right-clicking to see the context menu and then selecting 'full screen'. Pressing 'F' or the (or what I take to be) full-screen icon generates a quasi-full screen, whereby most but not all of the controls are hidden. 

There may also be a problem with closing VLC's 'about' box, though I did find the pressing <escape> closed that box.

[Here is bug report filed against VLC, together with a response by a VLC developer that says that the full-screen problem (and the problem with the 'about' box, if indeed that box is meant to have a close button) lie with Cinnamon.](https://trac.videolan.org/vlc/ticket/18362#comment:1)

Mint 18.1 Cinnamon 3.2.7.

**Comment by JosephMcc** [comment] 2017-05-26 07:48
The problem with the about box missing the close button isn't Cinnamon's problem. It's the problem of the metacity theme you are using. You will see it works fine in Mint-X or Y.

**Comment by ACinnamonUserInUK** [comment] 2017-05-26 13:26
> The problem with the about box missing the close button isn't Cinnamon's problem. It's the problem of the metacity theme you are using. You will see it works fine in Mint-X or Y.

OK, good. But do you mean the 'controls' theme or the 'windows border' theme?

And what, please, about the other, more significant problem - the one with full-screen?

**Comment by JosephMcc** [comment] 2017-05-26 18:32
The window border theme. I can't reproduce the other issue. Can you post a screenshot of what it looks like when it's broken?

**Comment by ACinnamonUserInUK** [comment] 2017-05-26 22:01
I can confirm that it is the window border theme. I know this isn't a support forum, but I'd appreciate a hint as to what code or icon (though I think it is code) that's the problem there, so that I can fix it in my (no longer supported, but beloved) theme.

**Screenshot of the VLC full-screen problem (using Mint-Y for borders and controls)**

VLC with maximised but not full-screen window

![image](https://cloud.githubusercontent.com/assets/9998846/26514049/c8107ea6-425e-11e7-81c2-9e8d078f3a1a.png)

VLC after entering what is meant to be full-screen mode, by either pressing F11 or using the menus (view -> full screen)
![image](https://cloud.githubusercontent.com/assets/9998846/26514054/ce7b0edc-425e-11e7-8214-1f09eac595a5.png)

**Comment by ACinnamonUserInUK** [comment] 2017-05-26 22:03
Also, somehow, generating a screenshot by using the printscreen key, together - though this may not have contributed to the problem - with accidentally pressing caps-lock (I saw an OSD indicating it), crashed Mint really hard; even ctrl-alt-backspace did nothing. However, I have not yet been able to reproduce this.

**Comment by JosephMcc** [comment] 2017-05-27 05:54
Ok, I see that same thing with VLC and fullscreen. However, when you start playing a video the controls disappear. I'm not a big vlc user but are you sure that isn't how it's supposed to work? I'll check in some other DE's.

**Comment by JosephMcc** [comment] 2017-05-27 06:19
Ok, so I've now tested this under Cinnamon and gnome shell. Using F11 gives you the psuedo fullscreen thing. Using the button in the toolbar or setting fullscreen from the right click context menu makes it truly fullscreen. I'm starting to doubt there is an issue here and it's working exactly how it's supposed to.

**Comment by itzexor** [comment] 2017-05-27 06:20
Was just about to post the same thing. Also, you can't enter true fullscreen unless a video is playing.

**Comment by JosephMcc** [comment] 2017-05-27 06:43
I'm closing this. I also tested under Metacity and works the same there as well.

**Closed by JosephMcc** 2017-05-27 06:43 UTC
