### ISSUE TITLE
Power off and logout dialogs are not fully translated.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/Cinnamon#6436] opened 2017-04-12 19:52 UTC
Power off and logout dialogs are not fully translated.
I have in mind title of window.
![cyhiutv](https://cloud.githubusercontent.com/assets/23406555/25018397/8476507e-2087-11e7-8774-86ed42f06685.png)

**Comment by theel0ja** [comment] 2017-04-14 08:24
Same here, with Finnish version.

**Comment by NikoKrause** [comment] 2017-06-24 12:20
This issue is in this repo https://github.com/linuxmint/cinnamon-session

But I didn't found that repo on launchpad.

**Comment by NikoKrause** [comment] 2017-07-18 20:32
This issue belongs to cinnamon-session repo. Currently it's not available for translation on launchpad, but it's planned to be added for LM 18.3.

That's a duplicate of https://github.com/linuxmint/cinnamon-translations/issues/23

@JosephMcc Can you close one duplicate?

**Comment by JosephMcc** [comment] 2017-07-19 04:58
Yep I'll close this one since it' open on the other.

**Closed by JosephMcc** 2017-07-19 04:58 UTC
