### ISSUE TITLE
Floating dead window titles in Window List applet

### ISSUE THREAD

**Issue by emengd** [linuxmint/cinnamon#9040] opened 2019-12-20 20:16 UTC
```
 * Cinnamon 4.4.5 (from regular 19.3 repositories)
 * Mint 19.3
 * inxi -G
    Device-1: Intel UHD Graphics 620 driver: i915 v: kernel 
    Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
    resolution: 1920x1080~60Hz 
    OpenGL: renderer: Mesa DRI Intel UHD Graphics 620 (Kabylake GT2) 
    v: 4.5 Mesa 19.1.2 - padoka PPA
 * 64 bit
 ```

**Issue**

Occasionally, windows that I have closed will linger on in the form of floating titles above the panel, as shown in the attached screenshot (I guess these are ghost thumbnails?). These floating titles cannot be interacted with and are permanently in foreground. Restarting cinnamon using the troubleshooting menu gets rid of them.

I have noticed this happening regularly for the past few days. It appears to correspond to the upgrade from 19.2 to 19.3.

I am using the Window List applet (as opposed to Grouped Window List). I see there is a bunch of similar issues involving Grouped Window List but none with Window List, sorry if  this is known and I couldn't find the report.

**Steps to reproduce**

I am unable to systematically reproduce it. I think it only happens when closing windows through the panel right-click menu, but just doing that is not enough to reproduce it, and I am not sure about that generalization to begin with. I usually don't notice immediately when it happens.

**Expected behaviour**

These things should not be there. Dead windows should die.

**Other information**

I attach a screenshot and .xsession-errors. You can see in the log that I restart cinnamon at 14:39; the dead titles in the screenshot were there before that. Then it actually happened again while I was writing this and I was able to identify that the lines that appears at 15:08 in the log correspond to when I closed a window and a floating title appeared.

[cinnamon_bug_cropped.png](https://user-images.githubusercontent.com/5831832/71288924-dd3b9900-2339-11ea-9cbe-3ed87266bb71.png)

[xsession-errors.log](https://github.com/linuxmint/cinnamon/files/3990079/xsession-errors.log)

**Comment by icarter09** [comment] 2019-12-21 03:21
@emengd please update this ticket whenever you have the steps to reproduce the issue.

**Comment by buzo-ffm** [comment] 2019-12-24 15:54
I think #9051 has the steps to reproduce this.

**Comment by JosephMcc** [comment] 2019-12-26 02:25
Yep this is a duplicate of https://github.com/linuxmint/cinnamon/issues/9051

**Closed by JosephMcc** 2019-12-26 02:25 UTC
Labels: Gathering Info

**Comment by emengd** [comment] 2019-12-26 09:24
I confirm that the steps in #9040 let me reproduce the issue.
