### ISSUE TITLE
Window thumbnail remains open after right clicking on item from window list.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#4860] opened 2015-11-22 19:29 UTC
When you hover over item from window list, window thumbnail appears. But after that, when you open right click menu, for instance to close the application, the window thumbnail remains open (please see attached screenshot).

It would be better if after right clicking on item from window list, window thumbnail will disappear.

![screenshot from 2015-11-22 22 52 32](https://cloud.githubusercontent.com/assets/12819058/11325797/25e9741e-9168-11e5-9bdc-0f073b5337e2.png)

**Comment by JosephMcc** [comment] 2015-11-23 10:24
You don't say what version you are on. I remember having this issue but it seems to be fixed in 2.8.5

**Comment by Vahan86** [comment] 2015-11-24 15:59
SorryCinnamon 2.8.4
Can you  ffk;jew' fjerojg eriojg ioerjgojg;rejgjjhfkjasbasBDhjHI

**Comment by Vahan86** [comment] 2015-11-28 19:12
@JosephMcc , I have installed Linux Mint Beta and updated Cinnamon to 2.8.6 version, but the issue is still there.

![untitled](https://cloud.githubusercontent.com/assets/12819058/11453487/0ccc5ed8-961d-11e5-94b9-53f3158d89d7.png)

**Comment by JosephMcc** [comment] 2015-11-28 21:27
I can't reproduce this. It seems to work correctly here on the latest nightly builds.

**Comment by RavetcoFX** [comment] 2015-11-29 00:30
I can't reproduce on master either

**Comment by JosephMcc** [comment] 2015-11-29 10:58
You can reproduce this by opening the context menu and then moving the cursor out and back in the window list item.

**Closed** 2016-01-15 03:54 UTC
