### ISSUE TITLE
Wacom Settings - Cannot Assign Modifier Keys to Tablet Buttons

### ISSUE THREAD

**Issue by zorbama** [linuxmint/Cinnamon#3800] opened 2015-01-04 20:21 UTC
Hello!

After upgrading to Linux Mint 17.1 (32-bit), I was delighted to discover that the graphics tablet GUI configuration finally works with my Wacom Intuos5 tablet, with some extra functionality like switching monitors and on-screen help. Great job!

One thing that I'm missing in the graphic configuration is the ability to assign to the tablet's button modifier keys, such as Shift, Ctrl and Alt. It is possible to assign key combination with those keys, but you can't assign them separately (for example, map a button to only the Shift key).
The current workaround I made is to assign Ctrl, Alt and Shift with a script that runs at startup. It works well and doesn't interfere with the other settings, however, the on-screen help shows that these buttons are assigned to "None".
Furthermore, I believe it's worth modifying the GUI to allow mapping of modifier keys, as they allow much better control in graphics programs in general.

Thanks again!

**Comment by Deevad** [comment] 2015-01-11 12:23
Duplicate of https://github.com/linuxmint/cinnamon-control-center/issues/76

**Closed** 2017-03-24 16:00 UTC
Labels: FEATURE REQUEST
