### ISSUE TITLE
Can't unlock desktop - Cinnamon 3.2

### ISSUE THREAD

**Issue by maddeer** [linuxmint/Cinnamon#6125] opened 2016-12-23 09:57 UTC
Tried Mint 8.1 Cinamon on Virtualbox 
When desktop locks I can type the password but there no reaction on Enter or pressing "lock" picture. 
I can only press to switch user button and then use the same user.

**Comment by leigh123linux** [comment] 2016-12-23 10:02
Duplicate of https://github.com/linuxmint/cinnamon-screensaver/issues/183

**Closed by leigh123linux** 2016-12-23 10:02 UTC
