### ISSUE TITLE
No icons in menu after upgrade to 4.8.5

### ISSUE THREAD

**Issue by herbstschweigen** [linuxmint/cinnamon#9853] opened 2021-01-13 21:19 UTC
```
 * Cinnamon version 4.8.5, no daily builds
 * Distribution Arch
 * Graphics hardware *and* driver used: NVIDIA Corporation GM107M [GeForce GTX 850M], nouveau
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

After running pacman -Syu today, cinnamon started with no icons in the panel and in the menu. The menu still worked and had all the categories and text links. Applications can be started from the menu. Keyboard locale was not set however.
![20210113 menu](https://user-images.githubusercontent.com/61930179/104512702-ea838f80-55ee-11eb-8c5d-2f10c02c9b5e.png)

Grep'ing syslog for "cinnamon" shows many "Too many levels of symbolic links" warnings.

[20210113.syslogs.txt](https://github.com/linuxmint/cinnamon/files/5811124/20210113.syslogs.txt)
[20210113.xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/5811108/20210113.xsession-errors.txt)

**Steps to reproduce**

**Expected behaviour**

**Other information**
Downgrading cinnamon-settings-daemon from 4.8.4 to 4.8.3 solves the issue.

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by eli-schwartz** [comment] 2021-01-14 04:59
Duplicate of https://github.com/linuxmint/cinnamon-settings-daemon/pull/321

Tracked in Arch via https://bugs.archlinux.org/task/69309

**Comment by herbstschweigen** [comment] 2021-01-14 10:53
ok, thanks.

**Closed** 2021-01-14 10:52 UTC
