### ISSUE TITLE
VLC Fullscreen Moves Window When Player Position Is Bottom-Left

### ISSUE THREAD

**Issue by mumblyjoe** [linuxmint/Cinnamon#2730] opened 2013-12-13 18:03 UTC
When a VLC Media Player window is positioned to be flush with the bottom and left sides of the desktop, entering fullscreen mode and exiting it causes the original window to jump to the top of the desktop. Disabling Effects or Snapping features doesn't seem to make a difference.

Steps to recreate:
Play a video in an unmaximised VLC window positioned bottom-left, enter and exit fullscreen mode.

Result:
Player jumps to the top-left.

Expected result:
Player should remain in its original position.

System: Ubuntu 13.10, Cinnamon 2.0, VLC 2.0.8

**Comment by JosephMcc** [comment] 2016-04-24 10:55
Closing this since it's old and I can't reproduce it on Cinnamon 2.8

**Closed by JosephMcc** 2016-04-24 10:55 UTC
