### ISSUE TITLE
bug report & fix(cinnamon-settings can't open default )

### ISSUE THREAD

**Issue by Superkeyv** [linuxmint/cinnamon#8860] opened 2019-09-16 14:25 UTC
```
 * Cinnamon version (4.2.4)
   - from archlinux community/cinamon
 * Distribution - (Arch)
 * Graphics hardware *and* driver used
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
"cinnamon-settings" can't open "default".  I trace error code when some unsuitable code appear

file-path: /usr/share/cinnamon/cinnamon-settings/modules/cs_default.py
at 445 line:
---------------------------------------------------------
    def getDescription(self, content_type):
        for d in other_defs:
            if content_type == d[DEF_CONTENT_TYPE]:
                s = d[DEF_LABEL]
                if s == _(s):
                    description = Gio.content_type_get_description(content_type)
                else:
                    description = s
                break

        if description == None:
            print("Content type '%s' is missing from the info panel" % content_type)
            return Gio.content_type_get_description(content_type)

        return description
--------------------------------------------------------

the fix method I think is：
--------------------------------------------------------
    def getDescription(self, content_type):
        description = None
        for d in other_defs:
            if content_type == d[DEF_CONTENT_TYPE]:
                s = d[DEF_LABEL]
                if s == _(s):
                    description = Gio.content_type_get_description(content_type)
                else:
                    description = s
                break

        if description == None:
            print("Content type '%s' is missing from the info panel" % content_type)
            return Gio.content_type_get_description(content_type)

        return description
--------------------------------------------------------

**Comment by BrosephJ** [comment] 2019-09-19 15:29
My defaults wouldn't open and adding that line to the file worked for me! :>

**Comment by leigh123linux** [comment] 2019-09-19 16:24
Duplicate of #8855 

https://github.com/linuxmint/cinnamon/commit/453d7fe01e03e15fd329d25016385a0865f82780

**Closed by leigh123linux** 2019-09-19 16:24 UTC

**Comment by Superkeyv** [comment] 2019-10-02 10:29
> 
> 
> My defaults wouldn't open and adding that line to the file worked for me! :>

you need edit this file with root. 
before that, backup the old file

**Comment by Superkeyv** [comment] 2019-10-02 10:34
> 
> 
> My defaults wouldn't open and adding that line to the file worked for me! :>

I'm using Archlinux, maybe the path is different to you. 
you can try run 'cinnamon-settings‘ in terminal. when error appear. pay attention to the path of python  file
