### ISSUE TITLE
Changing Workspaces breaks windowshade windows

### ISSUE THREAD

**Issue by cscrimge** [linuxmint/Cinnamon#1564] opened 2013-01-04 23:26 UTC
LinuxMint Nadia Cinnamon 1.6.7 64bit
In Cinnamon settings - Windows, set the 'Action on title bar double-click' to 'Toggle Shade'
Now open a window (gvim/firefox/gedit/...) in a workspace, double-click the title bar to shade it and then use the ctrl+alt+arrow keys to switch workspaces.
When you switch back to the workspace with the shaded window, the window title bar can be seen on the screen, but you cannot interact with it (to restore it, for example)

**Comment by gerow** [comment] 2015-11-11 23:42
Might want to close this as a duplicate of https://github.com/linuxmint/Cinnamon/issues/4638 since that has a little more up to date info.

**Comment by JosephMcc** [comment] 2015-11-12 03:05
@gerow thanks for pointing out the duplicate.

**Closed by JosephMcc** 2015-11-12 03:05 UTC
