### ISSUE TITLE
gwl: Some task bar entries do not show a window title

### ISSUE THREAD

**Issue by Piiit** [linuxmint/cinnamon#8162] opened 2018-12-20 08:11 UTC
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) LM 19.1
 * Graphics hardware *and* driver used:

$ lspci -vnn | grep VGA -A 12
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 620 [8086:5916] (rev 02) (prog-if 00 [VGA controller])
	Subsystem: Lenovo HD Graphics 620 [17aa:224b]
	Flags: bus master, fast devsel, latency 0, IRQ 128
	Memory at db000000 (64-bit, non-prefetchable) [size=16M]
	Memory at 80000000 (64-bit, prefetchable) [size=512M]
	I/O ports at e000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915

 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog

 ```

[xsession-errors.tar.gz](https://github.com/linuxmint/Cinnamon/files/2697880/xsession-errors.tar.gz)
[gwl-config.json.tar.gz](https://github.com/linuxmint/Cinnamon/files/2697897/gwl-config.json.tar.gz)

**Issue**
After a while some applications do no longer show their window title inside GWL applet.

**Steps to reproduce**
Actually, I did not manage to reproduce the issue always. It happens after some time, and a Cinnamon restart fixes it again.

**Expected behaviour**
Always show a window title, and if no window title is provided fallback to the application title.

**Other information**
Upgraded from LM19.0 recently and migrated pinned apps from [ITM 6.3.14](https://github.com/linuxmint/cinnamon-spices-applets/commit/094305a9a3b270394d0912123ddc7f7357d033df#diff-6e63c06628b0f8c26fd965bacda635f0)

I have 3 monitors, 3 panels and 3 GWL applets...

**Comment by icarter09** [comment] 2019-12-02 04:29
@Piiit were you able to ever come up with steps on how to reproduce this issue?

**Comment by Piiit** [comment] 2020-02-11 06:55
@icarter09 Unfortunately not, because I do no longer use the GWL option "Button label: Show window title", so I can't say...

**Comment by claudiux** [comment] 2020-02-11 10:56
@icarter09 I encountered this bug a few days ago. No window title and no miniature in GWL. But I don't know the cause of this bug. Restarting Cinnamon fixes it.

**Comment by icarter09** [comment] 2020-09-27 03:12
@claudiux if you are still experiencing this issue can you send me your GWL settings? Thanks.

**Comment by claudiux** [comment] 2020-09-29 11:05
@icarter09 It's been a long time since I noticed this bug. But I didn't pay too much attention to it, so that doesn't mean it was resolved.

**Comment by icarter09** [comment] 2020-09-30 02:00
@claudiux thanks. I'm going to leave the setting for `Button Label: Window title` enabled for the next couple of weeks to see if the issue will happen. So far I haven't noticed it the past couple of days since enabling it.

**Comment by icarter09** [comment] 2020-10-12 01:44
I've enabled the setting since my last comment and haven't noticed the issue yet.

**Comment by claudiux** [comment] 2020-10-12 10:58
Me neither. It seems to me that you can close this issue.

**Closed** 2020-10-12 21:15 UTC
Labels: Gathering Info
