### ISSUE TITLE
Applet window-list missing windows

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/Cinnamon#4986] opened 2016-01-05 21:57 UTC
Hi.
after upgrading to 17.3 i noticed that some windows are missing in the bar. OpenTTD and factorio (a game too) for example. I'm sure those windows were shown in previous versions.

**Comment by eladhen** [comment] 2016-01-07 22:38
I have the same problem. The problem seems to be with the new Window list applet thumbnail feature. If you turn it off the problem disappears. You can do it by: Settings > Applets > Window list > Configure > disable "Show window thumbnail on hover".

It's still a bug...

**Comment by eladhen** [comment] 2016-01-08 23:05
More on this bug here: http://forums.linuxmint.com/viewtopic.php?f=208&t=213098&start=0

**Comment by eladhen** [comment] 2016-01-14 20:04
I just confirmed this bug on another computer running Mint Cinnamon 17.3. Try installing chocolate-doom and then running the Chocolate Doom Setup (from command line or menu) and it doesn't show in the Window List applet. If I turn off the "Show window thumbnail on hover" it appears.

**Comment by kajzersoze** [comment] 2016-01-18 21:27
No need to turn that feature off, there's a patch for this problem here : https://github.com/linuxmint/Cinnamon/issues/4950

**Comment by eladhen** [comment] 2016-01-18 21:32
Thanks! Though I'll admit to not having a clue how to use a patch... I just hope the fix will enter the mint updates soon...

**Comment by kajzersoze** [comment] 2016-01-18 21:39
Download that diff2_edf483e324ee1225065a6c2c219224c386d70bb2.txt patch and put it in the /usr/share/cinnamon/applets/window-list\@cinnamon.org/ 

then in terminal go to that dir and run :
patch -p1 applet.js diff2_edf483e324ee1225065a6c2c219224c386d70bb2.txt

**Comment by JosephMcc** [comment] 2016-01-19 07:12
This is hopefully fixed in git master by: https://github.com/linuxmint/Cinnamon/commit/ded116d53631a2e8cd249cad7583328424ef8609

**Comment by JosephMcc** [comment] 2016-01-19 20:12
See https://github.com/linuxmint/Cinnamon/issues/4950
This should be fixed

**Closed by JosephMcc** 2016-01-19 20:12 UTC

**Comment by eladhen** [comment] 2016-01-20 09:54
Does anybody know when, if at all, this fix will reach simple mint users such as myself? :(
