### ISSUE TITLE
Icons drawn outside area of vertical panel

### ISSUE THREAD

**Issue by mbazley** [linuxmint/Cinnamon#6138] opened 2016-12-28 14:48 UTC
Related to #6137.  Refer once again to [this image](http://i.imgur.com/XiuSIyH.png).

The broken calendar applet has caused all the other applets to be drawn outside the area of the panel.  This seems to be the result of naive centring on the width of the widest applet, without checking for sanity.  On the opposite edge of the screen, it's even worse - the applets are drawn off the screen entirely.

**Comment by leigh123linux** [comment] 2016-12-28 15:49
duplicate of https://github.com/linuxmint/Cinnamon/issues/6109

**Closed by leigh123linux** 2016-12-28 15:49 UTC

**Comment by mbazley** [comment] 2016-12-28 18:08
You can close this bug as many times as you like, it's still a bug.  Shall I report it again?
