### ISSUE TITLE
Launcher applets do not always show assigned icons until Cinnamon is restarted

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7360] opened 2018-03-16 15:30 UTC
```
 * Cinnamon version (cinnamon --version) Cinnamon 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel integrated (I'll provide details if relevant)
 * 32 or 64 bit: 64
 ```

**Issue**

Launcher applets do not always show assigned icons, but instead appear blank, until Cinnamon is restarted. 

**Steps to reproduce**

On a fresh install of Mint Cinnamon, add to the panel (I have a top panel only, set to autohide), a new launcher. (I have two other launchers too.) For its icon, choose something - perhaps it needs to be something from a third-party theme. (I am using the third-party theme called 'Paper'.) Observe how, sometimes, a blank icon appears. Restart Cinnamon. Observe how the icon now appears.

**Expected behaviour**

The selected icon should appear immediately, I presume.

**Other information**

**Comment by CottonEaster** [comment] 2018-07-12 02:36
This problem persists in Mint 19. To reproduce, try the following.
Create a launcher (I have some on a panel already)
Fill out the necessary fields - name, command - and choose an icon from Mint-Y (and perhaps Mint-Y needs to be not set as one's icon theme).
Observe the blank launcher.

**Comment by icarter09** [comment] 2019-12-06 03:49
Closing this issue since the original submitter of this ticket is no longer present on Github.

**Closed by icarter09** 2019-12-06 03:49 UTC
