### ISSUE TITLE
Alt-F2 box malfunction

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#6290] opened 2017-02-15 02:31 UTC
**Scenario / step to reproduce**

1. Press Alt-F2 to get the command box up.
2. Right-click and select paste (presuming one has text to paste)
3. Paste.
4. Press ENTER to execute the command.

**Result**

[Edited because the editor was misparsing my text.] If one pastes, e.g., `gnome-schedule`, then, `gnome-schedulegnome-schedule` appears in the box (sic) and the computer tries to run that command.

**Affected system**

Mint 18.1 Cinnamon. I imagine this could be a theme bug. I am using the desktop theme called 'Cinnamon' (*sic*).

**Comment by collinss** [comment] 2017-02-15 03:23
I can't reproduce. It works fine for me using the exact steps you outlined, and the same theme and Mint version.

**Comment by ACinnamonUserInUK** [comment] 2017-02-15 16:54
I'll investigate some programs on my computer that just possibly might be responsible for the problem. I will report back. Thanks for your work.

**Comment by JosephMcc** [comment] 2017-02-15 21:30
Here is a way I can reproduce it. Open a terminal and type `notify-send "hello"` then highlight and copy the text with the right click menu. Not try pasting that in the run dialog. It will reproduce the issue.

In fact there seems to be more problems here. I seem to have to hit "Paste" twice for it to work. Then when I hit enter nothing happens, probably because a faulty command. I cannot dismiss the run dialog at this point either. I have to click in the text box to refocus it before `esc` will dismiss it.

**Comment by ACinnamonUserInUK** [comment] 2017-02-15 22:17
> In fact there seems to be more problems here.

Yes, I have encountered those further problems too. Thank you for investigating.

This is a fairly serious problem, it seems to me. I'd love a fix.

**Comment by ACinnamonUserInUK** [comment] 2017-03-18 03:45
I feel the need to 'bump' this, if I may, since it seems to me that fundamental functionality is at issue here and, consequently, the bug is obstructing me and, I imagine others (and I cannot see a sign here that a fix is in the offing - although, admittedly, it has not been that long).

**Comment by JosephMcc** [comment] 2017-04-06 18:39
Ok, so I just retested this on git master and now it seems to work fine. I can no longer reproduce the issue at all.

**Comment by CottonEaster** [comment] 2017-09-02 23:49
I too have just re-tested, on Cinnamon 3.4.6, and the command box still doesn't work properly, I am afraid. To reproduce:

1. copy `/etc/udev/rules.d/90-keyboardwakeup.rules` to the clipboard.
2. Alt-F2
3. Enter `gksudo xed ` (complete with trailing space) into the box.
4. Paste the  `/etc/udev/rules.d/90-keyboardwakeup.rules`, from the clipboard, into the box.
5. Press return.
6. Watch funny things happen and the command not run.

**Comment by pdcurtis** [comment] 2017-09-05 21:22
I have just tried this on my system and it runs as I would expect opening xed with elevated privileges and empty file  /etc/udev/rules.d/90-keyboardwakeup.rules

System:    Host: defiant Kernel: 4.4.0-21-generic x86_64 (64 bit) Desktop: Cinnamon 3.4.6
           Distro: Linux Mint 18.2 Sonya
Machine:   System: Notebook (portable) product: W230ST
           Mobo: Notebook model: W230ST Bios: American Megatrends v: 4.6.5 date: 11/18/2013
CPU:       Quad core Intel Core i7-4700MQ (-HT-MCP-) cache: 6144 KB 
           clock speeds: max: 3400 MHz 1: 2401 MHz 2: 2403 MHz 3: 2405 MHz 4: 2409 MHz 5: 2534 MHz 6: 2521 MHz
           7: 2478 MHz 8: 2478 MHz
Graphics:  Card-1: Intel 4th Gen Core Processor Integrated Graphics Controller
           Card-2: NVIDIA GK106M [GeForce GTX 765M]
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa) Resolution: 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile GLX Version: 3.0 Mesa 11.2.0
Audio:     Card-1 Intel 8 Series/C220 Series High Definition Audio Controller driver: snd_hda_intel
           Card-2 Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.4.0-21-generic
Network:   Card-1: Intel Centrino Advanced-N 6235 driver: iwlwifi
           IF: wlp3s0 state: up mac: c4:d9:87:0a:df:a2
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169
           IF: enp4s0f1 state: down mac: 00:90:f5:f7:1d:5b
Drives:    HDD Total Size: 1000.2GB (59.5% used) ID-1: /dev/sda model: ST1000LM014 size: 1000.2GB
Partition: ID-1: / size: 39G used: 9.2G (25%) fs: ext4 dev: /dev/sda6
           ID-2: /home size: 193G used: 46G (25%) fs: ext3 dev: /dev/sda7
           ID-3: swap-1 size: 16.78GB used: 0.06GB (0%) fs: swap dev: /dev/sda3
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 64.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 289 Uptime: 6 days Memory: 4526.5/7903.7MB Client: Shell (bash) inxi: 2.2.35

**Comment by CottonEaster** [comment] 2017-09-05 21:36
Strange. I've tried it again - on the originally affected computer (Cinnamon) and on another (XFCE). The XCFE computer works fine in that regard. On Cinnamon, I found that: pasting, via mouse or keyboard, did not work the first few times I tried it, but then (still within the same command box - I hadn't closed it) did work, but I ended up with the box containing *double* the text on the clipboard. Then, after closing the command box and re-opening it, everything worked.

Tentative inferences: perhaps the problem occurs only the *first* time in a session one uses the box or (?) uses the box with paste; and/or perhaps one's 'desktop' (a.k.a. Cinnamon theme) makes a difference. _Actually - ah - the problem seems to occur with the theme called 'Cinnamon' and not with the theme called 'Mint-Y Dark'. (I have not tested other themes yet.)_

@Peter Curtis: your thoughts?

**Comment by pdcurtis** [comment] 2017-09-06 16:17
@CottonEaster No thoughts - I was intrigued by your comment above of"Watch funny things happen and the command not run" and having not seen anything funny it seemed worth reporting. 

I can also report I have tried with theme 'Cinnamon' and again OK.

Have you tried creating a new user or better still made a LiveUSB and tried with a 'virgin' system?

**Comment by CottonEaster** [comment] 2017-09-06 16:23
I'll test on a LiveUSB when I get around to it - that's a good idea.

PS: I am unsure whether or not to be pleased that you have not seen anything funny, though I am afraid that the variety of funniness at issue is 'funny-peculiar' rather than 'funny-haha' (though I suppose it depends on one's sense of humour).

**Comment by CottonEaster** [comment] 2018-03-19 20:29
I've just encountered the problem on a new install of Mint 18.3 on a new (new to me, and new hardware) laptop.

**Comment by CottonEaster** [comment] 2018-07-05 20:32
I still have this problem - whereby, in the alt-F2 box, <paste>+enter duplicates the pasted text - on Mint 19. It's pretty frustrating, especially when one is using alt-F2 to troubleshoot _other_ problems. I've Mint set to use Mint-Y-Dark themes for most things (if that makes a difference - I haven't tested).

**Comment by icarter09** [comment] 2019-12-07 03:43
Closing this issue since the original submitter of this ticket is no longer present on Github.

**Closed by icarter09** 2019-12-07 03:43 UTC
Labels: BUG REPRODUCED
