### ISSUE TITLE
wallpaper ?

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#4949] opened 2015-12-20 00:51 UTC
i set the wallpaper but sometimes it goes back to the Gnome wallpaper is irritating i dont know what to find those to fix or what i did

.xsession-errors : http://paste.pound-python.org/show/U2KIQ3dEIQxbGEX19mHc/

what did i wrong i got also a dualscreen setup but technically i find it buggy
because right screen stays when i switch workspaces but is a happy feature on my side because i keep irc in on a eye.. got also manjaro linux dont know if its really a bug afterall ..

**Comment by ringo32** [comment] 2015-12-20 21:06
hmm happends again, when gedit (gtk3) opened a config filen but its a symlink

**Comment by ManIVIctorious** [comment] 2016-09-05 17:03
Duplicate of #3953

**Closed** 2016-09-05 18:14 UTC
