### ISSUE TITLE
Telegram tray icon is tiny and wrong

### ISSUE THREAD

**Issue by NaughtySquid** [linuxmint/Cinnamon#4960] opened 2015-12-23 07:41 UTC
Didn't have this issue on Unity, I'm guessing it's due to Cinnamon's new indicator support?

![telegram](http://i.imgur.com/6prvmJO.png)

It should from what I remember be the actual telegram logo, blue circle with a white arrow pointing to the top right. Not to mention, it shouldn't be tiny like that.

**Comment by tchncs** [comment] 2015-12-23 09:27
As i remember this is an custom Indicator.
Sadly i switched finally to awesomewm and doesnt remember its name.
But i remember that i had'nt this problem (smallest panel size).
I guess i remember that i compiled it because of *missing* trayicon from telegram in cinnamon.

**Comment by leigh123linux** [comment] 2015-12-23 09:31
No the black box issue is a dropbox problem, their bundled libGL lib doesn't work with nvidia driver.
The solution is to delete it

rm ~/.dropbox-dist/dropbox-lnx.*/libGL*

As for the icon size they provide 16x16 icons in ~/.dropbox-dist/dropbox-lnx.*/images/hicolor/16x16/status , use nemo image converter to resize them to 32x32 size.

**Comment by NaughtySquid** [comment] 2015-12-23 09:33
This is not about Dropbox, this is about Telegram, but nice to know.

**Comment by leigh123linux** [comment] 2015-12-23 09:36
@NaughtySquid try this for the telegram issue (run command as standard user)

gsettings set org.cinnamon enable-indicators false

**Comment by NaughtySquid** [comment] 2015-12-23 09:36
Yes, I have now turned them off, but this is still a bug with the way it's handled in Cinnamon.

**Comment by leigh123linux** [comment] 2015-12-23 09:38
@NaughtySquid I agree, the new system tray appindicator support is broken.

**Comment by lestcape** [comment] 2015-12-24 01:35
This is a duplicate of this issue: https://github.com/linuxmint/Cinnamon/issues/4883

**Closed** 2015-12-24 12:20 UTC
