### ISSUE TITLE
GNOME application do not respect Windows button settings

### ISSUE THREAD

**Issue by jtlpa** [linuxmint/Cinnamon#5136] opened 2016-03-16 20:15 UTC
If you open Windows and set window-buttons to just one button on left side, many GNOME default packages do not respect the setting (all three buttons remain on the right side).

![screenshot from 2016-03-16 15 13 08](https://cloud.githubusercontent.com/assets/11615699/13827326/ddd1383e-eb89-11e5-923d-ec6dd417bfc3.png)

**Comment by Mowalle** [comment] 2016-03-17 08:27
I had this problem too a few days ago. You can work around this by changing the respective key in `gsettings`:
`gsettings set org.cinnamon.desktop.interface 'close,minimize,maximize,menu:'` 
(everything before the `:` will be on the left side). Or use `dconf-editor` to set the same key via GUI.

I think setting the window buttons in Cinnamon Settings should maybe change this key as well as a solution?

**Comment by jtlpa** [comment] 2016-03-17 16:21
Mowalle
Thanks for quick reply. I tried your recommendation, but gsettings give error that no **key-name** was supplied. Could you double check your fix for key and key-name.

Thank you
JTL

**Comment by jtlpa** [comment] 2016-03-17 16:22
Whoops, hit the wrong button, didn't mean to close
JTL

**Comment by Mowalle** [comment] 2016-03-18 06:46
Right I'm stupid, sorry...

The command should be `gsettings set org.cinnamon.desktop.interface gtk-decoration-layout 'close, minimize, maximize, menu:'`. You can of course sort them differently if you want.

**Comment by leigh123linux** [comment] 2016-03-18 07:51
Gnome apps are broken by design so please close this report and bug the gnome devs instead.

**Comment by jtlpa** [comment] 2016-03-18 12:36
Mowalle
Thanks, but didn't work. Here is terminal output.
gsettings set org.cinnamon.desktop.interface gtk-decoration-layout 'close,minimize,maximize,menu:'
No such key 'gtk-decoration-layout'

**Comment by Mowalle** [comment] 2016-03-18 13:13
@leigh123linux I don't think this issue should be closed, as it has to do with a Cinnamon-specific key not being set. 

@jtlpa That is weird, I just double checked it and it works fine for me. Which distro and Cinnamon version are you running?

**Comment by jtlpa** [comment] 2016-03-18 13:27
Hi Mowalle
I will leave the issue open and agree with you on that. As to the version:
Debian Jessie 8.3 64bit, Cinnamon 2.2.16

Hope that helps

**Comment by collinss** [comment] 2016-03-18 13:42
@jtlpa Your Cinnamon version is almost 2 years old. I'm pretty sure a lot has changed regarding gnome apps since then. It's quite possible this is no longer an issue. I would recommend trying a new version of Cinnamon. The current version is 2.8 and 3.0 will likely be released in a month or two.

**Comment by jtlpa** [comment] 2016-03-18 14:07
Collinss
Yep I am aware of that, however our machines require stability. That's why we only use software from Debian Stable repositories.

**Comment by cranes-bill** [comment] 2016-03-18 17:54
Why you using Gnome applications!? Just use their _normal interface_ alternatives...

**Comment by jtlpa** [comment] 2016-03-18 20:53
crains-bill
To answer your question, the apps Archive Manager, Caculator, Font Viewer, Gedit, Gdebi, Document Viewer **are all included in the default Debian Jessie Cinnamon desktop** and we use all of them.

**Comment by jtlpa** [comment] 2016-03-20 17:39
SOLVED - move window buttons to left side of windows
APPLIES to **Debian** Jessie **Stable** 8.3 64bit, Cinnamon desktop 2.2.16, Gnome apps
open or create   /home/Your-User-Name/.config/gtk-3.0/settings.ini
add this new line of text "gtk-decoration-layout=close:" with out quotes

You could also use "gtk-decoration-layout=close,minimize,maximize:" with out quotes fro all three buttons

**Comment by wunderlich** [comment] 2016-09-04 18:50
Using `gsettings` works for me as well (Linux Mint 18, Cinnamon 3.0.7). But shouldn't the order of the buttons be `close`, `maximize`, `minimize`? I did the following:

`gsettings set org.cinnamon.desktop.interface gtk-decoration-layout 'close,maximize,minimize,menu:'`

Is somebody implementing this to cinnamon? I think the configuration of cinnamon should also affect the GNOME apps as they are shipped with Linux Mint.

**Comment by JosephMcc** [comment] 2016-09-04 19:09
There is already a feature request open to allow the titlebar layout settings in Cinnamon settings->Windows to also effect this key. We are aware of it but there are only so many hours in a day :)

**Closed by JosephMcc** 2016-09-04 19:09 UTC
Labels: NEEDS IMPROVEMENT

**Comment by clefebvre** [comment] 2018-01-24 14:34
Fixed today. See https://github.com/linuxmint/Cinnamon/issues/5617 for details.
