### ISSUE TITLE
Windows Minimizing Wrong Direction

### ISSUE THREAD

**Issue by ttjimera** [linuxmint/Cinnamon#6115] opened 2016-12-20 12:58 UTC
I have my panel at the top of the screen (the only panel on the only monitor – using a notebook here with no external monitor). Whenever I open an application for first time, say Nemo or terminal, and if I minimize the window, the window effect shows the window shrinking to the bottom instead of to the top panel. Subsequent minimization of the same window will show the correct window effect: shrinking to the top panel.

**Comment by JosephMcc** [comment] 2017-04-20 08:49
I can't reproduce this problem on git master and since you don't provide even basic info like distro and Cinnamon version, I'm closing this.

**Closed by JosephMcc** 2017-04-20 08:49 UTC
Labels: BUG

**Comment by ttjimera** [comment] 2017-04-21 05:50
My apologies, I forgot to supply you with the version and distro. This weird windows behaviour is still there in the  Cinnamon 3.2.7 with Mint 18.1. I have been using Cinnamon together with Mint through all its 17.x releases and now the 18.x. And I always keep Cinnamon up to date via the Update Manager. Somewhere along the 17.x Mint releases (I cannot now remember the exact point) I started observing this behaviour. Perhaps it was when I started using Cairo Dock.

Anyway I have since found more info. I observed that it is tied to Cairo Dock (which I place at the bottom). If I quit Cairo Dock, the windows behave as expected. But if I run Cairo again, it display the weird behaviour as described again.

It's ok if you close this issue. It's just a minor one which does not get in the way of my work.

**Comment by JosephMcc** [comment] 2017-04-21 06:09
Thanks for following up. The use of a Dock explains the problem. The dock is probably trying to take over the role of the window list.

**Comment by ttjimera** [comment] 2017-04-21 07:35
Yes, something like that, although I do not know the technical details behind it. It was able to take over the first time the window is minimized, and then on subsequent minimization, Cinnamon somehow managed to wrestle control back from it (Or maybe the Dock relinquished the control, or something else). BTW Cairo-dock version is 3.4.1, the one available via Mint 18.1 Software Manager. And yes, Cairo does perform the role similar to the window list. It has all the icons of the software that are opened. And, I just checked again, when the window minimized down to the Dock, it does "shrink" towards its icon on the Dock, similar to window list.

So it seems there is a clash of function between Cinnamon and Cairo-dock
