### ISSUE TITLE
Problem with cinnamon window list after update (5.0.4)

### ISSUE THREAD

**Issue by nathan-b** [linuxmint/cinnamon#10209] opened 2021-07-12 17:07 UTC
```
 * Cinnamon version (cinnamon --version): 5.0.4
 * Distribution: Arch Linux
 * Graphics hardware *and* driver used: AMD Vega onboard graphics, default Linux driver
 * 32 or 64 bit: 64-bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Cinnamon window list does not display all windows, and some windows are displayed from other workspaces.

This is an odd one. I'll try to describe it as best I can:
* System starts up. I launch Firefox in Workspace 1
* Then I launch a second program, Terminal
* When I switch to Workspace 2, Firefox still shows in the window list, but I can't see it in the workspace. When I click on it, it takes me to Workspace 1
* If I close Firefox, Terminal takes on this same behavior

There's a second issue with the window list that might be related. Sometimes windows spawned by a process do not show up in the window list. For example, when I start a meeting with Zoom, the meeting window does not show up on the window list -- I have to use Alt + Tab to switch to it.

**Configuration info, if applicable**

```
{
    "section1": {
        "type": "section",
        "description": "Behavior"
    },
    "show-all-workspaces": {
        "type": "switch",
        "default": false,
        "description": "Show windows from all workspaces",
        "value": false
    },
    "enable-alerts": {
        "type": "switch",
        "default": true,
        "description": "Show an alert in the window list when a window from another workspace requires attention",
        "value": true
    },
    "enable-scrolling": {
        "type": "switch",
        "default": false,
        "description": "Enable mouse-wheel scrolling in the window list",
        "value": false
    },
    "reverse-scrolling": {
        "type": "switch",
        "default": false,
        "description": "Reverse the direction of mouse-wheel scrolling in the window list",
        "dependency": "enable-scrolling",
        "value": false
    },
    "left-click-minimize": {
        "type": "switch",
        "default": true,
        "description": "Left click to minimize window",
        "value": true
    },
    "middle-click-close": {
        "type": "switch",
        "default": true,
        "description": "Middle click to close window",
        "value": true
    },
    "section2": {
        "type": "section",
        "description": "Display"
    },
    "buttons-use-entire-space": {
        "type": "switch",
        "default": false,
        "description": "Window buttons can have different sizes and use the entire space available",
        "value": false
    },
    "window-preview": {
        "type": "switch",
        "default": true,
        "description": "Show window thumbnails on hover",
        "value": true
    },
    "window-preview-show-label": {
        "type": "switch",
        "default": true,
        "description": "Show title above thumbnail",
        "dependency": "window-preview",
        "value": true
    },
    "window-preview-scale": {
        "type": "radiogroup",
        "default": 1,
        "description": "Thumbnail size",
        "options": {
            "Small": 0.75,
            "Medium": 1,
            "Large": 1.25,
            "Largest": 1.5
        },
        "dependency": "window-preview",
        "value": 1
    },
    "last-window-order": {
        "type": "generic",
        "default": "",
        "value": "121634834::81788972::100663297::81788931::83886081::83886083::83886104::125829127::125832722::125835851::125837216::130023431::125873052::12583111::148897801::138412363::142606343::142610063"
    },
    "__md5__": "5ef6c9311df5af19c26eced1327c8c40"
}

```

**Comment by mtwebster** [comment] 2021-07-12 18:06
I can't reproduce the first issue, but the second may be fixed by https://github.com/linuxmint/cinnamon/commit/1c7cc5de912a962f361ed77e47ea082eb95236b1, and I wonder if maybe it has something to do with the first issue as well.

If you'd like to test it, copy the code here:
https://raw.githubusercontent.com/linuxmint/cinnamon/1c7cc5de912a962f361ed77e47ea082eb95236b1/files/usr/share/cinnamon/applets/window-list%40cinnamon.org/applet.js

Make a copy of the existing `/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js` and replace the original's contents with that new code.

**Comment by nathan-b** [comment] 2021-07-12 18:10
@mtwebster brilliant, that fixed both problems! Thanks so much!

**Closed** 2021-07-12 18:29 UTC

**Comment by mtwebster** [comment] 2021-07-12 19:00
Ah great :) I love these sorts of bug reports.

**Comment by Harry-W-Haines-III** [comment] 2021-07-13 12:11
Well that fixes the disappearing act.  Was able to go back in and remove the entry for demands-attention-passthru-wm-classes "['gnome-screenshot', 'lxterminal', 'xfce4-terminal', 'firefox']" and leave the default for 'gnome-screenshot'

Also wondering why some applications like Firefox that didn't demand attention (flashing orange bar) in the past are now doing so.  I startup apps in auto start in the following order-time delay:
Application              Delay in seconds
Redshift                 0
System Monitor           1
Audacious                2
KSystemLog               3
LibreOffice              4
Firefox Web Browser      5
HexChat                  6

At least now Firefox is not disappearing from the window list when it is clicked on.

**Comment by mtwebster** [comment] 2021-07-13 12:31
You should put those entries back in the passthru setting - that will be the new default in the next cinnamon update. Those programs don't behave properly when being launched in certain situations (like with shortcuts or autostarting). In previous releases, ALL programs were allowed to launch and take focus, which was wrong also. This (hopefully) small group of programs are assisted in this by being added to that setting.

**Comment by Harry-W-Haines-III** [comment] 2021-07-13 12:47
Thank you for the information on the issue.

**Comment by ChooChooAl** [comment] 2021-07-13 16:34
Would this be related to my Thunderbird launching via 'startup programs' and displaying on the desktop and shows in panel as needs attention.   Then clicking the panel to minimize TB just makes it disappear.  If I quit TB and restart it, all is well.

**Comment by Harry-W-Haines-III** [comment] 2021-07-13 17:37
Entries were put back in.  Now Firefox does not flash attention on the window list.  Something is still not 100% though.  I am using the traditional window list layout.  Firefox is allowed plenty of time to start but has still traded places with Hexchat on the ordering of the windows.  In the past the last application started would be the one furthermost to the right.

**Comment by Harry-W-Haines-III** [comment] 2021-07-13 18:34
@mtwebster 

Could you there be other applications that need to be in this list?  I don't use steam or game much but have heard in IRC of some who are frustrated with panels disappearing.

**Comment by mtwebster** [comment] 2021-07-13 18:41
The items disappearing from the panel issue is strictly an issue with the window list applet and is fixed as mentioned here: https://github.com/linuxmint/cinnamon/issues/10209#issuecomment-878484613

The exception list is only to make sure the given programs that don't behave properly when opening windows get focus as expected.
