### ISSUE TITLE
Wrong icon aspect ratio for Nvidia Prime applet (nvidia-prime-applet package)

### ISSUE THREAD

**Issue by elephant-overlord** [linuxmint/Cinnamon#7086] opened 2017-11-27 18:46 UTC
```
 * Cinnamon 3.6.6
 * Mint 18.3
 * Intel i7-3517U / Nvidia GeForce GT 630M - Intel + Nvidia Driver
 * 64 bit
 ```

**Issue**
It's only a very small cosmetic issue: When using the Intel/Nvidia Prime applet (package nvidia-prime-applet), the aspect ratio of the icons used to show which gpu is being used (Intel or Nvidia) is wrong. The icon appears to be slightly "squeezed". This does not happen if I use any of the other Prime applets (e.g. through the download option in the applet settings), but I prefer the applet from the package mentioned above, as it uses grayscale instead of colored icons. The icon aspect ratio was ok in Mint 18.2.

**Steps to reproduce**
Install the applet (sudo apt-get install nvidia-prime-applet) and activate it through the applet settings.

**Expected behaviour**
Icon aspect ratio should be used (worked in Mint 18.2) or icon should be resized to fit inside the "square" applet space.

**Other information**
See the attached screenshots:

![screenshot from 2017-11-27 19-24-23](https://user-images.githubusercontent.com/34039206/33283087-0c3d722c-d3ab-11e7-9954-6009f7e30863.png)
![screenshot from 2017-11-27 19-25-15](https://user-images.githubusercontent.com/34039206/33283088-0c580768-d3ab-11e7-90fd-bf5c96df1a51.png)

**Comment by NikoKrause** [comment] 2017-11-27 19:55
Do you use a custom panel height?

**Comment by elephant-overlord** [comment] 2017-11-27 19:58
No, I use the panel height defined by the theme. I've tried switching to other themes, including the ones provided by Mint by default, but it doesn't make a difference. If I turn on custom panel height, the issue persists no matter the height of the panel, too.

**Comment by NikoKrause** [comment] 2017-11-27 20:08
Can you take a screenshot of the applets about dialog?

**Comment by elephant-overlord** [comment] 2017-11-27 20:24
![screenshot from 2017-11-27 21-22-00](https://user-images.githubusercontent.com/34039206/33287551-53a6d7c6-d3b9-11e7-8db4-135b80228e8a.png)

**Comment by NikoKrause** [comment] 2017-11-27 20:34
Looking at the applets code it hasn't been changed in the last year:
https://github.com/linuxmint/nvidia-prime-applet/tree/master/usr/share/cinnamon/applets/nvidia-prime%40cinnamon.org

Did you upgraded from LM18.2 to LM18.3 or did you a fresh install of LM18.3?

**Comment by elephant-overlord** [comment] 2017-11-27 20:49
It's a fresh install of 18.3, although I used the beta ISO (downloaded yesterday afternoon) and installed all available updates through the update manager (which, according to today's final release upgrade info, should make this a vanilla 18.3 install). I can't say if the beta ISO is the culprit, and tbh it doesn't bother me enough to do a fresh install of 18.3 final to see if it changes anything.

**Comment by NikoKrause** [comment] 2017-11-27 20:56
No Beta install should be fine. No need to do a fresh install, because as you said, it's as good as a fresh install. As you said, the ratio looks fine here on LM18.2. I'll try it on LM18.3 later.

**Comment by NikoKrause** [comment] 2017-11-28 00:02
Ok. I can reproduce it on LM18.3. I'm not sure what exactly changed, but I can fix it.
Also I noticed the applet doesn't use symbolic icons, i.e. you can barely see it with the Mint-X theme.
I create a PR tomorrow. But I don't know if this will be merged to LM18.3.

**Comment by elephant-overlord** [comment] 2017-11-28 09:14
Thank you! :thumbsup:

**Comment by NikoKrause** [comment] 2018-02-02 23:42
We are aware of the issue. There's a PR waiting to be merged. So I'll close this now.

**Closed by NikoKrause** 2018-02-02 23:42 UTC
