### ISSUE TITLE
Broken display of all Desklets after standby mode

### ISSUE THREAD

**Issue by OCTOGONE-DEV** [linuxmint/cinnamon#12050] opened 2024-01-24 22:32 UTC
### Distribution

21.3

### Package version

6.0.4

### Graphics hardware in use

gtx 1060 

### Frequency

Always

### Bug description

Broken display of all Desklets after standby mode on desktop
![image](https://github.com/linuxmint/cinnamon/assets/40270594/b23a178e-52fc-44e6-9d4d-87230e54e25b)
also applet user picture is out of bound

### Steps to reproduce

put computer in stanby mode on desktop, turn it back on, now Broken display of all Desklets 

### Expected behavior

display should be teh same

### Additional information

I'm using arc dark theme

**Comment by schorschii** [comment] 2024-02-08 15:35
duplicate of #11458

**Comment by rcalixte** [comment] 2024-02-09 03:58
Duplicate of #11458

**Closed by rcalixte** 2024-02-09 03:58 UTC
Labels: BUG
