### ISSUE TITLE
Lock Screen not working under Wayland

### ISSUE THREAD

**Issue by mgeck64** [linuxmint/cinnamon#12500] opened 2024-11-15 04:12 UTC
Note: I had set up a dual monitor environment with screen mirroring enabled when I discovered the problem, but I unplugged one of the monitors to reproduce this with a simple single monitor setup and the bug persisted.

Here's a System Settings dump, for whatever that might be worth:

### Distribution

Mint 22

### Package version

6.2.9

### Graphics hardware in use

Intel Corporation CometLake-S GT2 [UHD Graphics 630]

### Frequency

Always

### Bug description

The lock screen won't function when Wayland is enabled. Furthermore, the screensaver also fails to activate.

### Steps to reproduce

Enable Wayland.
Log in to my user account.

Either of the following:

1. Lock the screen from the Start Menu.
2. Enable the screensaver.

### Expected behavior

I can lock the screen; the screensaver functions.

### Additional information

System:
  Kernel: 6.8.0-48-generic arch: x86_64 bits: 64 compiler: gcc v: 13.2.0 clocksource: tsc
  Desktop: Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Muffin v: 6.2.0 vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
Machine:
  Type: Mini-pc System: HP product: HP EliteDesk 800 G6 Desktop Mini PC v: SBKPF
    serial: <superuser required> Chassis: type: 35 serial: <superuser required>
  Mobo: HP model: 8711 v: KBC Version 09.08.23 serial: <superuser required> part-nu: 31S34UC#ABA
    uuid: <superuser required> UEFI: HP v: S21 Ver. 02.18.00 date: 12/14/2023
CPU:
  Info: 6-core model: Intel Core i5-10500T bits: 64 type: MT MCP smt: enabled arch: Comet Lake
    rev: 3 cache: L1: 384 KiB L2: 1.5 MiB L3: 12 MiB
  Speed (MHz): avg: 800 min/max: 800/3800 cores: 1: 800 2: 800 3: 800 4: 800 5: 800 6: 800 7: 800
    8: 800 9: 800 10: 800 11: 800 12: 800 bogomips: 55199
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel CometLake-S GT2 [UHD Graphics 630] vendor: Hewlett-Packard driver: i915 v: kernel
    arch: Gen-9.5 ports: active: DP-6 empty: DP-1, DP-2, DP-3, DP-4, DP-5, HDMI-A-1, HDMI-A-2,
    HDMI-A-3 bus-ID: 00:02.0 chip-ID: 8086:9bc8 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: intel
    dri: iris gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1200 s-dpi: 96 s-size: 508x317mm (20.00x12.48") s-diag: 599mm (23.57")
  Monitor-1: DP-6 mapped: DP3-3 model: PA248QV serial: <filter> res: 1920x1200 hz: 60 dpi: 94
    size: 520x320mm (20.47x12.6") diag: 611mm (24.1") modes: max: 1920x1200 min: 720x400
  API: EGL v: 1.5 hw: drv: intel iris platforms: device: 0 drv: iris device: 1 drv: swrast
    surfaceless: drv: iris x11: drv: iris inactive: gbm,wayland
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.0.9-0ubuntu0.2 glx-v: 1.4
    direct-render: yes renderer: Mesa Intel UHD Graphics 630 (CML GT2) device-ID: 8086:9bc8
Audio:
  Device-1: Intel Comet Lake PCH cAVS vendor: Hewlett-Packard driver: snd_hda_intel v: kernel
    bus-ID: 00:1f.3 chip-ID: 8086:06c8 class-ID: 0403
  Device-2: Lenovo ThinkPad USB-C Dock Gen2 USB Audio driver: hid-generic,snd-usb-audio,usbhid
    type: USB rev: 2.0 speed: 12 Mb/s lanes: 1 bus-ID: 1-6.3.3.2:10 chip-ID: 17ef:30d1 class-ID: 0300
    serial: <filter>
  Device-3: Creative Pebble Pro driver: hid-generic,snd-usb-audio,usbhid type: USB rev: 1.1
    speed: 12 Mb/s lanes: 1 bus-ID: 1-6.3.4:8 chip-ID: 041e:3287 class-ID: 0102 serial: <filter>
  API: ALSA v: k6.8.0-48-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin
Network:
  Device-1: Intel Comet Lake PCH CNVi WiFi driver: iwlwifi v: kernel bus-ID: 00:14.3
    chip-ID: 8086:06f0 class-ID: 0280
  IF: wlp0s20f3 state: up mac: <filter>
  Device-2: Intel Ethernet I219-LM vendor: Hewlett-Packard driver: e1000e v: kernel port: N/A
    bus-ID: 00:1f.6 chip-ID: 8086:0d4c class-ID: 0200
  IF: eno1 state: down mac: <filter>
  Device-3: Lenovo USB-C Dock Ethernet driver: r8152 type: USB rev: 3.0 speed: 5 Gb/s lanes: 1
    bus-ID: 2-3.1:6 chip-ID: 17ef:a387 class-ID: 0000 serial: <filter>
  IF: enx5cff35d4b63d state: down mac: <filter>
Bluetooth:
  Device-1: Intel AX201 Bluetooth driver: btusb v: 0.8 type: USB rev: 2.0 speed: 12 Mb/s lanes: 1
    bus-ID: 1-14:5 chip-ID: 8087:0026 class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 5.2 lmp-v: 11
    sub-v: 20f9 hci-v: 11 rev: 20f9 class-ID: 7c0104
Drives:
  Local Storage: total: 2.29 TiB used: 117.61 GiB (5.0%)
  ID-1: /dev/nvme0n1 vendor: Toshiba model: KBG40ZNS256G NVMe KIOXIA 256GB size: 238.47 GiB
    speed: 31.6 Gb/s lanes: 4 tech: SSD serial: <filter> fw-rev: 10410106 temp: 27.9 C scheme: GPT
  ID-2: /dev/nvme1n1 vendor: SK Hynix model: PC601 HFS256GD9TNG-L2A0A size: 238.47 GiB
    speed: 31.6 Gb/s lanes: 4 tech: SSD serial: <filter> fw-rev: HPS1 temp: 38.9 C scheme: GPT
  ID-3: /dev/sda vendor: SanDisk model: Portable SSD size: 1.82 TiB type: USB rev: 2.1
    spd: 480 Mb/s lanes: 1 tech: SSD serial: <filter> fw-rev: 6004 scheme: GPT
Partition:
  ID-1: / size: 229.63 GiB used: 9.22 GiB (4.0%) fs: ext4 dev: /dev/dm-1 mapped: vgmint-root
  ID-2: /boot size: 1.61 GiB used: 194 MiB (11.8%) fs: ext4 dev: /dev/nvme1n1p2
  ID-3: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/nvme1n1p1
Swap:
  ID-1: swap-1 type: partition size: 1.91 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/dm-2
    mapped: vgmint-swap_1
USB:
  Hub-1: 1-0:1 info: hi-speed hub with single TT ports: 16 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-2: 1-1:2 info: Genesys Logic Hub ports: 4 rev: 2.1 speed: 480 Mb/s lanes: 1 power: 100mA
    chip-ID: 05e3:0610 class-ID: 0900
  Hub-3: 1-1.3:4 info: Genesys Logic Hub ports: 4 rev: 2.1 speed: 480 Mb/s lanes: 1 power: 100mA
    chip-ID: 05e3:0610 class-ID: 0900
  Hub-4: 1-6:3 info: Lenovo USB2.0 Hub ports: 4 rev: 2.1 speed: 480 Mb/s lanes: 1
    chip-ID: 17ef:a392 class-ID: 0900
  Hub-5: 1-6.3:6 info: Lenovo USB2.0 Hub ports: 4 rev: 2.1 speed: 480 Mb/s lanes: 1
    chip-ID: 17ef:a394 class-ID: 0900
  Hub-6: 1-6.3.3:7 info: Lenovo USB2.0 Hub ports: 4 rev: 2.0 speed: 480 Mb/s lanes: 1
    power: 100mA chip-ID: 17ef:a395 class-ID: 0900
  Device-1: 1-6.3.3.1:9 info: Cypress USB-I2C Bridge type: <vendor specific> driver: N/A
    interfaces: 2 rev: 2.0 speed: 12 Mb/s lanes: 1 power: 100mA chip-ID: 04b4:521a class-ID: 0000
  Device-2: 1-6.3.3.2:10 info: Lenovo ThinkPad USB-C Dock Gen2 USB Audio type: audio,HID
    driver: hid-generic,snd-usb-audio,usbhid interfaces: 4 rev: 2.0 speed: 12 Mb/s lanes: 1
    power: 30mA chip-ID: 17ef:30d1 class-ID: 0300 serial: <filter>
  Hub-7: 1-6.3.3.3:11 info: Genesys Logic Hub ports: 4 rev: 2.1 speed: 480 Mb/s lanes: 1
    chip-ID: 05e3:0610 class-ID: 0900
  Device-1: 1-6.3.3.3.1:14 info: Logitech LogiG TKL MKeyboard type: keyboard,HID
    driver: hid-generic,usbhid interfaces: 3 rev: 2.0 speed: 12 Mb/s lanes: 1 power: 500mA
    chip-ID: 046d:c34a class-ID: 0300
  Device-2: 1-6.3.3.3.2:13 info: Sunplus Innovation Optical Mouse type: mouse
    driver: hid-generic,usbhid interfaces: 1 rev: 2.0 speed: 1.5 Mb/s lanes: 1 power: 98mA
    chip-ID: 1bcf:0005 class-ID: 0301
  Device-3: 1-6.3.3.4:12 info: SanDisk Portable SSD type: mass storage driver: uas interfaces: 1
    rev: 2.1 speed: 480 Mb/s lanes: 1 power: 500mA chip-ID: 0781:55bb class-ID: 0806 serial: <filter>
  Device-4: 1-6.3.4:8 info: Creative Pebble Pro type: HID,audio
    driver: hid-generic,snd-usb-audio,usbhid interfaces: 4 rev: 1.1 speed: 12 Mb/s lanes: 1
    power: 100mA chip-ID: 041e:3287 class-ID: 0102 serial: <filter>
  Device-5: 1-14:5 info: Intel AX201 Bluetooth type: bluetooth driver: btusb interfaces: 2
    rev: 2.0 speed: 12 Mb/s lanes: 1 power: 100mA chip-ID: 8087:0026 class-ID: e001
  Hub-8: 2-0:1 info: super-speed hub ports: 10 rev: 3.1 speed: 10 Gb/s lanes: 1
    chip-ID: 1d6b:0003 class-ID: 0900
  Hub-9: 2-1:2 info: Genesys Logic Hub ports: 4 rev: 3.2 speed: 5 Gb/s lanes: 1
    chip-ID: 05e3:0626 class-ID: 0900
  Hub-10: 2-1.3:4 info: Genesys Logic Hub ports: 4 rev: 3.2 speed: 5 Gb/s lanes: 1
    chip-ID: 05e3:0626 class-ID: 0900
  Hub-11: 2-3:3 info: Lenovo USB3.1 Hub ports: 4 rev: 3.1 speed: 10 Gb/s lanes: 1
    chip-ID: 17ef:a391 class-ID: 0900
  Device-1: 2-3.1:6 info: Lenovo USB-C Dock Ethernet type: Network driver: r8152 interfaces: 1
    rev: 3.0 speed: 5 Gb/s lanes: 1 power: 288mA chip-ID: 17ef:a387 class-ID: 0000 serial: <filter>
  Hub-12: 2-3.3:5 info: Lenovo USB3.1 Hub ports: 4 rev: 3.1 speed: 10 Gb/s lanes: 1
    chip-ID: 17ef:a393 class-ID: 0900
Sensors:
  System Temperatures: cpu: 36.0 C pch: 42.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Repos:
  Packages: pm: dpkg pkgs: 1944
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //mirror.fcix.net/linuxmint-packages wilma main upstream import backport
    2: deb http: //mirrors.sonic.net/ubuntu noble main restricted universe multiverse
    3: deb http: //mirrors.sonic.net/ubuntu noble-updates main restricted universe multiverse
    4: deb http: //mirrors.sonic.net/ubuntu noble-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
Info:
  Memory: total: 32 GiB note: est. available: 31.12 GiB used: 2.4 GiB (7.7%)
  Processes: 345 Power: uptime: 12m states: freeze,mem,disk suspend: deep wakeups: 0
    hibernate: platform Init: systemd v: 255 target: graphical (5) default: graphical
  Compilers: gcc: 13.2.0 Client: Unknown python client inxi: 3.3.34

**Comment by rcalixte** [comment] 2024-11-15 04:36
Duplicate of linuxmint/wayland#98

**Closed by rcalixte** 2024-11-15 04:36 UTC
Labels: BUG
