### ISSUE TITLE
Chrome Application Window icons

### ISSUE THREAD

**Issue by igitur** [linuxmint/Cinnamon#527] opened 2012-03-15 09:53 UTC
When running a web app, e.g. Gmail, in a Chrome application window, the Gmail icon is supposed to be displayed in the taskbar entry. Instead, the generic Chrome icon is displayed.

**Comment by mgiuca** [comment] 2015-11-09 01:58
#4730 Seems to be the same bug (that one is getting attention so I would mark this as a duplicate of that).

**Comment by JosephMcc** [comment] 2015-11-09 04:14
Closing as duplicate. Thanks to those who pointed them out.

**Closed by JosephMcc** 2015-11-09 04:14 UTC
Labels: FEATURE REQUEST
