### ISSUE TITLE
Where is the focus when I press Cltr+Alt+Del?

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9850] opened 2021-01-12 13:41 UTC
Just updated to 20.1. When I press Ctrl+Alt+Del, the focus goes somewhere else. Note the lack of a shadow, which shows the dialog doesn't have focus:

![image](https://user-images.githubusercontent.com/33569/104321676-0ae50a00-5488-11eb-9de0-563f29b3d12c.png)

 If I press Esc, nothing happens, and I expect the dialog to close.

**Comment by Everest10** [comment] 2021-01-12 17:56
Try to press TAB to show the focus. By default the focus could be on the logout button.

**Comment by dandv** [comment] 2021-01-13 11:22
@Everest10: it's not there. I'm on this GitHub page right now, I press Ctrl+Alt+Del, the focus stays in the browser.

Are you experiencing different behavior?

**Comment by Everest10** [comment] 2021-01-15 00:00
> @Everest10: The Log Out button is red, but not focused. I'm on this GitHub page right now, I press Ctrl+Alt+Del, the focus stays in the browser.
> 
> Are you experiencing different behavior?

Yes. When I press Ctrl+Alt+Del the focus go to Session Window. If you press Ctrl+Alt+Del and Alt+Space I'll see the window pop-up menu in the Session Window without focus on the buttons but if you press TAB the 'Switch User' button is focused and you can navigate through the buttons.  The logout button as default focused is a good request.

**Comment by dandv** [comment] 2021-01-15 03:47
> When I press Ctrl+Alt+Del the focus go to Session Window. If you press Ctrl+Alt+Del and Alt+Space I'll see the window pop-up menu in the Session Window without focus

Yeah, not here. I'm in Firefox right now, I press Ctrl+Alt+Del, and the focus stays in the browser. Alt+Space bring up the browser window's context menu.

![image](https://user-images.githubusercontent.com/33569/104678925-99c47300-5690-11eb-9b3f-cb7daeed312b.png)

**Comment by Everest10** [comment] 2021-01-15 16:52
> > When I press Ctrl+Alt+Del the focus go to Session Window. If you press Ctrl+Alt+Del and Alt+Space I'll see the window pop-up menu in the Session Window without focus
> 
> Yeah, not here. I'm in Firefox right now, I press Ctrl+Alt+Del, and the focus stays in the browser. Alt+Space bring up the browser window's context menu.
> 
> ![image](https://user-images.githubusercontent.com/33569/104678925-99c47300-5690-11eb-9b3f-cb7daeed312b.png)

It's ok here. The focus go to FF just if press alt + tab otherwise the focus still in the session window.
Fedora 33 + Cinnamon 4.8.5

**Comment by aragubas** [comment] 2021-01-20 14:20
![image](https://user-images.githubusercontent.com/47148297/105187373-7a569b80-5b11-11eb-8edd-b081508cec2d.png)
_t does happens here as well *note that the titlebar text is grayed out a little bit_

**Comment by mtwebster** [comment] 2021-01-20 15:45
I can't reproduce this.

Check:
cinnamon-settings->windows->behavior->"prevent windows which require attention from stealing focus"

With this enabled, I can reproduce it.

This is unfortunate but due to https://github.com/linuxmint/cinnamon-session/commit/bbc4fdbdd07452517d0f8e77825593940c301f77 the dialog can't override that behavior.

**Comment by aragubas** [comment] 2021-01-20 20:09
it worked
________________________________
De: Michael Webster <notifications@github.com>
Enviado: quarta-feira, 20 de janeiro de 2021 15:45
Para: linuxmint/cinnamon <cinnamon@noreply.github.com>
Cc: Aragubas <dpaulootavio5@outlook.com>; Comment <comment@noreply.github.com>
Assunto: Re: [linuxmint/cinnamon] Where is the focus when I press Cltr+Alt+Del? (#9850)


I can't reproduce this.

Check:
cinnamon-settings->windows->behavior->"prevent windows which require attention from stealing focus"

With this enabled, I can reproduce it.

This is unfortunate but due to linuxmint/cinnamon-session@bbc4fdb<https://github.com/linuxmint/cinnamon-session/commit/bbc4fdbdd07452517d0f8e77825593940c301f77> the dialog can't override that behavior.

**Comment by JosephMcc** [comment] 2021-03-13 05:33
Closing this since we don't have any intention of changing the behavior currently.

**Closed by JosephMcc** 2021-03-13 05:33 UTC
Labels: Gathering Info
