### ISSUE TITLE
App-find font issue

### ISSUE THREAD

**Issue by mellobob** [linuxmint/Cinnamon#4405] opened 2015-07-06 19:04 UTC
When I use the finder (alt-F2) I get a small font plus the letters are pushed down off screen so I only see the top half.

This is on Mint 7.2 Cinnamon 2.6.11. It worked find before the upgrade from Mint 7.1.

I have the text scaling factor set to 1.4 which I think is causing the text to move down in the search bar. But, I need to do this because the font settings do not appear to effect the mint menu or the finder.

**Comment by JosephMcc** [comment] 2015-11-08 10:01
I can't reproduce this in Cinnamon 2.8? Is it working for you now?

**Comment by mellobob** [comment] 2015-11-09 02:20
Sorry, no help.

I'm still on cinnamon 2.6.13 and have replaced the stock alt-f2 command
with something else that default ... of course, I have no idea how I did
that or what I replaced it with.

On Sun, Nov 8, 2015 at 3:01 AM, JosephMcc <notifications@github.com> wrote:

> I can't reproduce this in Cinnamon 2.8? Is it working for you now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linuxmint/Cinnamon/issues/4405#issuecomment-154796864>
> .
>



-- 
**** Listen to my FREE CD at http://www.mellowood.ca/music/cedars ****
Bob van der Poel ** Wynndel, British Columbia, CANADA **
EMAIL: bob@mellowood.ca
WWW:   http://www.mellowood.ca

**Comment by JosephMcc** [comment] 2015-11-09 04:19
Ok. It seems to be OK in 2.8. I'm going to close this but if the issue comes back up I will re-open it.

**Closed by JosephMcc** 2015-11-09 04:19 UTC
Labels: CLOSE IF NO INFO
