### ISSUE TITLE
Mint 18 Sound Settings won't switch audio inputs to different device [video included]

### ISSUE THREAD

**Issue by jessedubord** [linuxmint/Cinnamon#5472] opened 2016-07-20 21:49 UTC
See video for example and details: [CLICK HERE TO WATCH](https://youtu.be/il1lQaqNGVA)

When I try to switch audio input devices of the Sound Settings in System Settings, it won't switch; it stays on the default build-in device. This is the same whether I use a wireless bluetooth microphone, webcam, USB microphone, etc.

Bug reported using Mint 18 (Ubuntu base) x64, Cinnamon 3.0.7 desktop environment.

Cheers

**Comment by SDodding** [comment] 2016-07-22 18:28
Experiencing this also with a fresh install of Mint 18 x64 / Cinnamon 3.0.7 - No matter which input is selected the actual input is always from the default internal laptop mic

**Comment by artscoop** [comment] 2016-07-24 14:51
I was just about to open a ticket for this. Indeed, when you switch the audio input in the cinnamon applet, it does nothing, volume values and actual pulseaudio input remain unchanged.
Using the pulseaudio applet (pasystray) to change the audio source works however, so this is a problem with the cinnamon applet only.

**Comment by haljhon** [comment] 2016-08-01 12:57
I can confirm that I see this issue on Fedora 24 (x64) running Cinnamon 3.0.6.

**Comment by rhollencamp** [comment] 2016-08-02 15:28
right-clicking on the audio panel applet allows you to change the default input device the same way you can change the output device; this only shows up if something is using an input device however.

**Comment by IHaveThatPower** [comment] 2016-08-09 17:13
I ran into this same problem and identified the cause. 

In `/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py`, under the `Module` class's `buildLayout` method, in the `## Input page` section, there is this line (ca. line 609):

`self.inputSelector = self.buildDeviceSelect("output", self.inputDeviceList)`

Change `"output"` to `"input"`, save the file (you'll need sudo permission to do so), and then it will start working. This is almost certainly the result of a copy/paste without updating the reference to which section of the device selector was being used.

**Comment by KonanBZH** [comment] 2016-08-18 19:24
Thank's a lot @IHaveThatPower ;o)), that was that. And now, it's working after a reboot ! Sound inputs can be choosen.

**Comment by jessedubord** [comment] 2016-08-18 19:26
That's great, @IHaveThatPower , thanks for that solution. Now that a fix has been identified, can we request a commit for this issue?

**Comment by IHaveThatPower** [comment] 2016-08-18 19:36
Fix has already been committed. :) https://github.com/linuxmint/Cinnamon/pull/5533#event-750591417

**Comment by jessedubord** [comment] 2016-08-18 19:37
You guys rock.

**Comment by JosephMcc** [comment] 2016-08-19 18:02
If your original issue has been fixed could please close this?

**Comment by Enelar** [comment] 2016-11-27 19:00
Guys, i experiencing same issue, and willing to participate.
Its Fedora spin btw

**Comment by leigh123linux** [comment] 2016-11-27 22:13
@Enelar Another fedora user 🆒

**Comment by Enelar** [comment] 2016-11-28 00:28
In my case, topic-starter bug reproducing. And i am also attaching new story.

When i am connecting to the Bluetooth audio device, it **often** (A) starts play sounds with it. But sometimes it not (B). And i should go to the sound settings, and select output device manually. (Btw no matters if i connects as A2DP, it will by default enable HSP). 

And in both situations (A) / (B) i have to select input device explicitly, when connecting through HSP profile. And if i select blue-tooth input device - nothing changes. 


**Offtopic**
@leigh123linux yea, i actually tried it before. But it has so many tiny annoying issues, so i returned to gnome. And after a while, i decided to give it a shot, like i did to btrfs and many other hopeful technologies.
Between lines - it a pain to decide report here, main Fedora line, or in Fedora-Cinnamon department ;)

Because i am not sure, is this bug will reproduce under Ubuntu, or it just porting issue :)

**Comment by Enelar** [comment] 2016-11-28 04:17
Bug confirmed under Cinnamon 3.2.1

It having bluetooth reconnecting issues, which already reported to the RedHat.
But once it connected, it still not changing profiles. It just playing through new device, and not changing setting. Which leads to this:

- applet volume change don't affects volume (because it changing volume of speakers, whos not playing anything right now)
- advanced applications (such as games / or players) sending sound to current active device, which is speakers. odd.
- system notifications still playing through speakers

And original bug still reproduces.

Hoping it will help <3

**Comment by n8nagel** [comment] 2017-01-29 20:14
Am experiencing the same issue on a fresh install of Mint, laptop is seeing my DAC but I can't switch over to it.  Will check code mentioned above and let you know if that works.

**Comment by jessedubord** [comment] 2017-01-31 18:23
I did some more testing, and in this case the issue was fixed; the bug was not present.
**Hardware:** Lenovo 80SA laptop, Logitech G930 Wireless headphones w/ built-in mic.
**Software:** Linux Mint 18.1 x64, Cinnamon 3.2.7, Kernel 4.4.0-59-generic .

I am able to switch from the laptop's internal webcam mic to the G930 wireless headphone mic without issue.

**Comment by t-hofmann** [comment] 2017-02-09 21:41
I can second the identification of the problem's source as stated by "IHaveThatPower":
by changing line 600 of /usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
from
self.inputSelector = self.buildDeviceSelect("output", self.inputDeviceList)
to 
self.inputSelector = self.buildDeviceSelect("input", self.inputDeviceList)
the problem/bug was fixed.

I use Linux Mint 18.1 cinnamon updated from 18.

**Comment by collinss** [comment] 2017-02-09 22:50
@t-hofmann That line was indeed fixed in 18.1.

**Comment by bjvt** [comment] 2017-03-08 16:16
I have the same issue.  The sound control panel didn't do anything. But, I'm using Google phone, and changed the output on that control panel.  That worked.

**Comment by drauber** [comment] 2017-04-04 13:09
Hello! I changed the line as guidance, it is now possible to change the input device, but now it is mute. Anyone have any suggestions?

**Comment by ropeladder** [comment] 2017-07-27 08:08
I am having the same problem as @Enelar (https://github.com/linuxmint/Cinnamon/issues/5472#issuecomment-263180270), where Mint automatically connects to a bluetooth device (which is good) but the sound settings do not update, either in the applet or in the Sound settings window.

It's reproducible for me simply by turning bluetooth off manually (which automatically switches the sound output to built-in speakers and _does_ update sound settings), and then turning it back on, which automatically switches the actual sound output to my bluetooth device after it connects _without_ updating the Sound settings page or the sound applet to show the new device.

The problem has been around since at least 17.1 (when I started using Mint).

**Comment by mrdowden** [comment] 2017-12-13 02:20
I'm having the same issue on Linux Mint 17.3 Rosa 64-bit (Ubuntu 14.04, Trusty Tahr) running Cinnamon 2.8.8. Plugging in my USB Sennheiser Headset (SC60-USB-CTRL) shows both input and output options, but I'm unable to select them.

This is a very new issue for me - I just updated to Mint 17.3 / Cinnamon 2.8.8 and the issue showed up immediately.

I'm unable to use the proposed fix above because I don't have a `cs_sound.py` file:

```
$ cat /usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py
cat: /usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py: No such file or directory
```

**Comment by mrdowden** [comment] 2017-12-13 03:16
I was able to fix the output settings by grabbing the `cs_sound.py` off of [Cinnamon's GitHub](https://raw.githubusercontent.com/linuxmint/Cinnamon/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py), but now I don't have any input settings available and my entire System Settings Control Center won't load.

Can anyone please share a working `cs_sound.py` file?

**Comment by t-hofmann** [comment] 2017-12-13 07:19
What about grabbing from this very same repository.
For your convenience the direct link to the file in question:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py

**Comment by collinss** [comment] 2017-12-13 08:08
@mrdowden that wont work. The cs_sound.py has dependencies that don't exist in 17.3. If you want to fix your issue, your only real option is to upgrade to a newer version (current mint version is 18.3).

**Comment by leigh123linux** [comment] 2017-12-13 08:09
@mrdowden your cinnamon is to old to use cs_sound.py as your cinnamon-desktop package doesn't have CVC

https://github.com/linuxmint/cinnamon-desktop/commit/65e05c22eddeba8ad14a32847f28a7548d8e91c6#diff-aedc2821722b38165f437fa5ed2060fd

https://github.com/linuxmint/Cinnamon/blob/2.8-maintenance/files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py#L71

the setting for 2.8 points to 

```
cinnamon-control-center sound
```

**Comment by leigh123linux** [comment] 2017-12-13 08:11
Can anyone reproduce the issue on a supported cinnamon version (3.6.x)?

**Comment by mrdowden** [comment] 2017-12-13 14:52
@leigh123linux Thanks. Hadn't noticed how far behind Mint 17.3 was on Cinnamon versions. I'm a bit surprised since Mint 17.3 is an LTS that is officially supported until April 2019.

**Comment by belonog** [comment] 2017-12-31 16:01
@leigh123linux Yes, I have the same problem on:

System:    Host: *** Kernel: 4.10.0-42-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.6.7 (Gtk 2.24.30)
           Distro: Linux Mint 18.3 Sylvia
Machine:   System: LENOVO (portable) product: 80SV v: Lenovo ideapad 510-15IKB
           Mobo: LENOVO model: Torronto 5C1 v: NO DPK
           Bios: LENOVO v: 3JCN24WW date: 12/29/2016

**Closed** 2018-01-30 16:31 UTC
Labels: BUG

**Comment by mlopezgva** [comment] 2018-02-15 03:52
Sorry to bother, but I have the same problem in both Cinnamon (17.1) and XFCE (Mint 18.3). I have another machine with Mint 18.3 Cinnamon, but I am guessing it will have the same issue:

1. Cinnamon changes the streaming to the new device, XFCE is not
2. When using external devices (in this case an USB headphone) the volume control is controlling the built-in device, and not the one used to output the sound.

> Feel free to move it no another repo if this is not the right one.
