### ISSUE TITLE
Window list icons don't correspond to launcher icons for Google Chrome application shortcuts

### ISSUE THREAD

**Issue by adamltaylor** [linuxmint/Cinnamon#2247] opened 2013-07-10 14:16 UTC
I use Google Chrome to create application shortcuts for GMail and Google Calendar.  The launcher items created in this way have appropriate icons (an envelope-looking thing for GMail, a calendar for Google Calendar).  But when I launch these launcher items, the icons in the window list do not necessarily match the launcher icons.  In particular, all the Chrome-based windows have identical icons.  Sometimes they all have the GMail icon, sometimes the Google Calendar icon, and sometimes the Google Chrome icon.  In particular, the common icon _seems_ to be the icon for whatever was launched most recently.  (With them all getting set to the Google Chrome icon if I launch a plain-old Google Chrome browser window.)

All of this is on 64-bit Linux Mint 13 with backports enabled.  In particular, I'm currently using Cinnamon 1.8.8.

**Comment by Yanpas** [comment] 2015-04-17 14:51
+

**Comment by jreimers** [comment] 2015-05-06 23:16
+1

**Comment by davidbarredo** [comment] 2015-10-01 08:24
+1

Another one with Linux Mint and the same problem. In Ubuntu the apps show the correct icons.

**Comment by mgiuca** [comment] 2015-11-09 01:58
#4730 Seems to be the same bug (that one is getting attention so I would mark this as a duplicate of that).

**Comment by JosephMcc** [comment] 2015-11-09 04:13
Ok, I'm closing this as a duplicate.

**Closed** 2015-11-16 00:26 UTC
Labels: APPLETS, BUG, window list
