### ISSUE TITLE
Broken behavior of desktop entry with Type=Link

### ISSUE THREAD

**Issue by yumashka** [linuxmint/cinnamon#11808] opened 2023-08-05 20:32 UTC
### Distribution

Mint 21.2

### Package version

Cinnamon 5.8.4

### Frequency

Always

### Bug description

When working with desktop entry of type Link (Type=Link) all operations are done with target. Not only double-click (i.e. "Open") and "Open with" but **all**. Including drag-drop, copy-paste, cut-paste, move to Trash.

### Steps to reproduce

Install fresh Mint 21.2 Cinnamon. Update (optionaly).

Turn off auto-arrange on the desktop.

On the desktop create new empty file named **testlink.desktop** (any name ended with "**.desktop**")

Open this file with any text editor. The editor will open this file itself because it is empty.

Type this desktop entry contents ("Name" is optional, any "URL" with only sitename with or without slash):

```
[Desktop Entry]
Name=Test Link
Type=Link
URL=https://wikipedia.org
```

Save the file. Right after that icon will appear as Link, i.e. with small arrow at the right bottom and name "**Test Link**"

To check that icon is a desktop entry of type "Link": right click, select "Open With", then select "Text Editor". The text editor will open the target, i.e. download and show the web-page. 

_TEST 1_
Drag-drop "Test Link" icon to another place on the desktop (just from one corner to another).
Expected to happen (and was in 21.1): The icon appeared on the new place.
Actually happen in 21.2: Desktop icons diappeared and appeared again; seems linke Nemo is crashed. If you try to repeat then all icons on desktop are disappeared, Cinnamon restart does not help. 

_TEST 2_
Copy-paste "Test Link" icon to another folder
Expected to happen (and was in 21.1): The "Test Link" successfully appeared in the another folder.
Actually happen in 21.2: Folder window is closed; seems like Nemo is crashed.

_TEST 3_
Move "Test Link" icon to Trash
Expected to happen (and was in 21.1): the "Test Link" successfully moved to trash.
Actially happen in 21.2: Error "Cannot move to trash, do you want to delete immediately?" with message about error to delete "/" then "Error when deleting"

If target URL looks like **https://some.site/some/path** then the observed behaviour changes:
_TEST 1_: The "Test Link" icon stays on the same place, but new file appeared on the desktop. Contents of the new file is the contents of the link target (web-page in this example). The name of the new file is the last part of the URL path (after the last /)
_TEST 2_: The link entry stays on the same place, new file appeared on the new place where "Test Link" was pasted. Contents of the new file is the contents of the link target (web-page in this example). The name of the new file is the last part of the URL path (after the last /)

If target URL looks like **file:///path/to/file** then all operations are done with target file: target file copy appeared on desktop in _TEST1_, target file appear in folder in _TEST2_, target file is moved to Trash in _TEST3_

### Expected behavior

When working with desktop entry of type Link (Type=Link) only "Open" and "Open with" operations are done with target. 
All other operations (drag-drop, copy-paste, cut-paste, move to Trash) are done with link itself.
(Like it was in Mint 21.1)

### Additional information

Firefox and Crome has a feature: user can select the whole address in the address bar and drag it to the desktop. Or just drag the lock sign. Desktop entry with "Type=Link" appeared on the desktop. It is supposed that user can copy this desktop entry somewhere.

**Comment by mtwebster** [comment] 2023-08-05 21:07
Duplicate of https://github.com/linuxmint/nemo/issues/3285

**Closed by mtwebster** 2023-08-05 21:07 UTC
