### ISSUE TITLE
Arch readline version problem

### ISSUE THREAD

**Issue by Teejer** [linuxmint/Cinnamon#5959] opened 2016-11-14 17:10 UTC
Today I updated my Arch install - which included readline 7. Which broke my cinnamon DE. If I manually launched a cinnamon application like cinnamon-settings I would get this error.

cinnamon: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 43, in <module>
    modules = map(__import__, mod_files)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_applets.py", line 5, in <module>
    from ExtensionCore import ExtensionSidePage
  File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 32, in <module>
    curr_ver = subprocess.check_output(["cinnamon", "--version"]).splitlines()[0].split(" ")[1]
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['cinnamon', '--version']' returned non-zero exit status 127

Temporarily I've symlinked /usr/lib/libreadline.so.6 -> libreadline.so.7

This gets me back into cinnamon. I'm wondering if it should be linked against libreadline.so instead? That way the version of libreadline doesn't matter as much?

**Comment by leigh123linux** [comment] 2016-11-14 18:56
Please close and re-file it at arch bug tracker as it's there screw up!

**Comment by lots0logs** [comment] 2016-11-14 21:02
@leigh123linux cjs links against it. 

This is actually not caused by Arch package. Its the Antergos package. An update will be pushed out later today. Sorry for the trouble. Cheers!

**Comment by JosephMcc** [comment] 2016-11-14 21:16
@lots0logs Can we go ahead and close this then?

**Comment by lots0logs** [comment] 2016-11-14 21:21
@JosephMcc :+1:

**Comment by JosephMcc** [comment] 2016-11-14 21:21
Thanks

**Closed by JosephMcc** 2016-11-14 21:21 UTC
