### ISSUE TITLE
Icons on vertical panel rearrange themselves whenever a window/app/prompt, which is represented by an icon, gets closed

### ISSUE THREAD

**Issue by firepainting** [linuxmint/cinnamon#9845] opened 2021-01-11 11:30 UTC
* Cinnamon version - 4.8.5
 * Distribution - Mint 20.1 Ulyssa
 * Graphics hardware *and* driver used

```
Graphics:
  Device-1: Intel HD Graphics 620 vendor: Lenovo driver: i915 v: kernel 
  bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.2.6 
  direct render: Yes 

```

 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
[XSession Errors.txt](https://github.com/linuxmint/cinnamon/files/5795328/XSession.Errors.txt)
[Sys Log.txt](https://github.com/linuxmint/cinnamon/files/5795329/Sys.Log.txt)
 
--

**Edit: This also happens on my other PC.** Same Cinnamon version and distribution as above. Also 64 bit.

```
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
  vendor: Micro-Star MSI driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) 
  v: 4.5 Mesa 20.2.6 direct render: Yes 
```

--

**Issue**

Hello,

I just upgraded to 20.1 Ulyssa (from 20 Ulyana).

The icons on my vertical panel rearrange themselves whenever a window/app/prompt--which is represented by an icon--gets closed. The new arrangement seems set, it doesn't change thereafter.

I restored all settings to default: right-click on panel > Troubleshoot > Restore all settings to default... and it still behaves the same.

For example, this is how I regularly position my icons, more or less: 
![panel 1](https://user-images.githubusercontent.com/50393421/104173059-30e6bc00-5440-11eb-9c8b-8555293aa1c3.png)

After closing the file manager: 
![panel 2](https://user-images.githubusercontent.com/50393421/104173057-2fb58f00-5440-11eb-8d7a-1ea632f8d6e7.png)

I've been using Mint (Edit: Cinnamon) since 19.1 (April 2019) and this is the first time this happened.

**Steps to reproduce**

Arrange icons to desired positions, by dragging. Close any open window/app/prompt represented by an icon on the panel.

**Expected behaviour**
Icons' positions remain in previously set order.

**Other information**
N/A

**Configuration info, if applicable**
N/A

Thank you.

**Comment by mmuehlfeldRH** [comment] 2021-01-11 13:04
This problem also came up on Fedora 33 with a recent update (cinnamon-4.8.3-1.fc33.x86_64).
I use a horizontal panel here and the entries are reordered whenever I close a window by clicking the X or pressing [Alt]+[F4].
Please let me know if you need further information to get this fixed.

**Comment by firepainting** [comment] 2021-01-11 17:57
@mmuehlfeldRH Haven't found anything yet. I'd appreciate any help. Thank you.

**Comment by mmuehlfeldRH** [comment] 2021-01-12 07:59
@firepainting Sorry for the confusion and not being clearer in my post. "Please let me know if you need further information to get this fixed." was addressed to the developers. :-) I'm just a user (not a developer) who is affected by this bug.

**Comment by ronyala** [comment] 2021-01-14 17:42
Hi @firepainting , I added a PR that will hopefully fix this issue (well, it at least fixed _an_ issue) If you want to try it :)

**Comment by firepainting** [comment] 2021-01-15 06:25
Hi @ronyala.

Thank you very much :) 

I'm at a loss here, though. I'm just a regular user that can't read code I even only have a slight idea on what a pull request is. I'm here pretty much just to report any issues I'm seeing.

Could you give me a rundown on how to fix this myself? Or a link for that?

Otherwise it's all good. Just wanted to thank you for the PR, very much appreciated.

**Comment by ronyala** [comment] 2021-01-15 09:28
@firepainting 
Hi, yea it's fine, We can wait a week or two for the next update of Cinnamon, and if you want to do it yourself I added a how-to below :)

You need to copy-paste the content of `applet.js` and `appGroup.js` from PR #9858 into `/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org`.
The PR files are in `https://github.com/linuxmint/cinnamon/pull/9858/files`. For every file, there's a `View File` option in the `...` menu on the top-right of it, and then you will find a `Raw` button, that will open a tab with only the file's content.

You will need `sudo` privileges to edit the files but that shouldn't be a problem (there's an open-as-root option in `nemo`).
From there it's just replacing the code.
After you've done it, right-click in a panel, and choose 'Troubleshoot' -> 'Restart Cinnamon' for the changes to take effect.

**Comment by firepainting** [comment] 2021-01-15 10:24
@ronyala Again thank you very much!

For me waiting for the next update may be the best move :D However, I am following your how-to, and it just made its way into the notes. Until the issue is more annoying I'll just wait.

Learned something new! Getting a better grasp on how to use Github more seriously hehe.

**Comment by mmuehlfeldRH** [comment] 2021-01-16 09:01
I replaced the updated files on my Fedora 33 (cinnamon-4.8.5-1), but the changes do not fix the problem.

I don't know how the windows are ordered. For example, if you open (in this order):
1) Kolourpaint
2) Firefox (2 windows)
3) Audacious
4) Thunderbird
5) gnome-terminal-server
and then close one of the Firefox windows, then the order is:
1) Thunderbird
2) Audacious
3) Kolourpaint
4) Firefox
5) gnome-terminal-server
However, if I close all windows again, open them in the same order as mentioned at the beginning, and then close one Firefox window again, the order is again completely different.

This is really an annoying bug, because you loose a lot of time during the day by searching the right window in the task bar if you have many windows opened.

This bug is reproduceable on all my 3 computers that are running on F33.

@ronyala , please let me know if I can somehow help you debugging the problem.

**Comment by ronyala** [comment] 2021-01-17 17:47
Hi @mmuehlfeldRH , I tried to replicate this by opening the same programs you listed above, but it still works fine on my computer.

Could you post the configuration of the applet?
There's an Export to File option in its settings that you can use and paste/upload the file here.

**Comment by ronyala** [comment] 2021-01-17 17:50
Possibly related to https://github.com/linuxmint/cinnamon/issues/9802

**Comment by mmuehlfeldRH** [comment] 2021-01-18 07:33
@ronyala , It seems that "Group windows by application = false" causes this issue. I reset the applet to its defaults, and no icons were re-arranged. Then I changed only "Group windows by application" to "false", and the bug appeared.

**Comment by lazarin** [comment] 2021-01-21 07:49
For me "Group windows by application = false / true" does not make any difference. Tried many different combinations with all the settings but the bug sits there.

**Comment by mmuehlfeldRH** [comment] 2021-01-21 08:11
I did some more checks around this yesterday:

For me, it's definitely the "Group windows by application = false" that causes this problem: . I created a new user and logged in as this new user. Then I ran the procedure I describe above, and the order did not change when I closed a window. Then I changed only "Group windows by application" to "false" (no other settings were changed for this new user), and ran the same test again. Now the order changed right after I closed a window.

What helped me to workaround the issue was to downgrade to the previous version (4.6.7) that was available in Fedora 33. So the issue was introduced between cinnamon 4.6.7 (released on Aug 11, 2020) and 4.8.3 (released on Dec 13, 2020). Fedora didn't publish any updates beween these two releases, so I can't give a shorter time frame.

**Comment by lazarin** [comment] 2021-01-21 08:49
So in Mint20.1 it's even worse :)
I've created a short screen capture with that: https://gofile.io/d/H9JeRa

**Comment by ronyala** [comment] 2021-01-27 12:54
Hi, I added a PR #9899 that fixes it for me.
This stops it most of the time.
Note that it will still happen when closing a pinned window in ungrouped-windows mode, as to prevent other issues (4c1aa69b4662c7091e5a2d29e72aa404ad801424).

**Comment by mmuehlfeldRH** [comment] 2021-01-27 13:25
@ronyala I replaced appList.js with the one from your PR on my Fedora 33 (cinnamon-4.8.6) and it solves my issue. Thanks for your work.

**Closed** 2021-03-01 16:48 UTC
Labels: BUG

**Comment by tragiccommons** [comment] 2021-05-04 23:03
@ronyala I applied the files from your two changelists, and this seems to have fixed or improved the issues greatly. Thank you.

I was struggling with this issue for several months. I'm kind of confused about why there hasn't been a cinnamon update with these changes. This issue was really quite terrible. Is there a reason for this delay?
