### ISSUE TITLE
"allow pointer to pass through the edge of panels" has no effect

### ISSUE THREAD

**Issue by sdbillin** [linuxmint/cinnamon#9952] opened 2021-02-24 01:39 UTC
```
 * Cinnamon version (cinnamon --4.8.6)
 * Distribution - (Mint 20.1)
 * Nvidia 760
 * 64 bit
**Issue**
"allow pointer to pass through the edge of panels" has no effect


**Steps to reproduce**
toggle "allow pointer to pass through the edge of panels" in panel settings. See pointer passing through edge of panel on multiple screen setup

**Expected behaviour**
Pointer should not pass through edge of panel


**Other information**


**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by ablacksheep** [comment] 2021-02-27 22:04
Duplicate of #9855 :)

**Closed** 2021-03-09 04:32 UTC
