### ISSUE TITLE
Mixed Python versions

### ISSUE THREAD

**Issue by bernd-wechner** [linuxmint/Cinnamon#6599] opened 2017-06-10 04:35 UTC
On an initial sally into the code I observe that:

`/files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py`

is headed:` #!/usr/bin/python2`

and:

`/files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py`

is headed: `#!/usr/bin/python3`

No crisis per se, but I wonder, before I invest any energy into it, are Python3 upgrades to a file like `cinnamon-settings.py `welcome as pull requests and likely to be accepted?

**Comment by mtwebster** [comment] 2017-06-10 05:27
We were discussing this earlier internally, and here: https://github.com/linuxmint/Cinnamon/pull/6596

It's not something we want to worry about right at this time (being in the middle of a release and not wanting to create fresh, new and exciting regressions) but it's definitely something we plan for 3.6, at least within the main 'cinnamon' repository, to have everything running and intended  to run with python 3.

**Comment by bernd-wechner** [comment] 2017-06-10 07:37
I'm on Cinnamon 3.2.6 what release are you in the middle of? (I take it you mean stabilising for a push to releasing it or in process of finalising it?) 

I'm guessing though from that, that generally Python 3 upgrades are welcome as pull requests (as long as they pass regression, so would need to check how regressions tests are performed), but it may take a little while before accepted because a release is underway? 

Just curious, because upgrading cinnamon-settings.py to Python 3 doesn't look onerous on the surface, I only noticed because well I'm using PyDev and the project ask for a Python version to do its syntax checks against and it basically underlines and highlights syntax issues well, and so editing a Python 2 file immediately throws up red spots all over the print statements ;-). 

But if any change were made yes, would be great to run regressions locally first before ever considering a pull request, so should probably take a look at how that's done before I touch a line of code I guess. Any pointers welcome there.

**Comment by collinss** [comment] 2018-03-26 04:19
Closing as all python files in the Cinnamon package have now been moved to python3.

**Closed by collinss** 2018-03-26 04:19 UTC
Labels: NEEDS IMPROVEMENT
