### ISSUE TITLE
GWL - Broken Super+<number> shortcut to switch/open windows

### ISSUE THREAD

**Issue by 1998marcom** [linuxmint/cinnamon#9028] opened 2019-12-19 15:31 UTC
```
 * Cinnamon 4.4.5
   - Not using daily builds, just what is till now offered by software manager
 * Mint 19.3 64bit
 * Using AMD Ryzen 2500u, amdgpu default driver
 * [xsession-errors](https://github.com/linuxmint/cinnamon/files/3984245/xsession-errors.txt)
 
```

**Issue**
Just yesterday updated to Linux Mint 19.3 from 19.2. Noticed that one shortcut I regularly used in Mint 19.2 (Super+number) isn't working (nothing happens).

**Steps to reproduce**
Login, then Super+1 to open the first defined application (I think the default is Firefox).

**Expected behaviour**
Let n be a (natural) number between 1 and 9. Super+n should open the n-th window in "grouped windows list".

**Other information**
Didn't find a way to configure it in System Settings -> Keyboard -> Shortcuts
Didn't find a way to configure it in RMB on "Grouped Windows List" applet -> Preferences -> Configure

**Comment by parabolic** [comment] 2019-12-19 22:03
Hi @1998marcom I am also facing the same issue and after some digging I found that the code for this was removed without any explanation whatsoever.
Here's the commit for that.
https://github.com/linuxmint/cinnamon/commit/94719c2cf1525f17b38bc7356d46d5b6bb5eab59
I would very much like to see this feature re-introduced because for me it gives a productivity boost that I have since ubuntu + unity which where the first ( maybe even across all OSes) that have introduced this.
I am using **cinnamon-desktop 4.4.0.1**

**Comment by agalitsyn** [comment] 2019-12-20 07:26
And I can confirm this bug, stop working in 19.3. Also commented in #5561

**Comment by Kerooker** [comment] 2019-12-22 01:37
Pawit Pornkitprasan created [an article on how to fix](https://medium.com/@pawitp/restoring-super-num-window-switching-in-linux-mint-19-3-6652633bf7e2) this until it's fixed by Mint.

(Bringing the instructions from the article in case something happens to it)

[This](https://gist.github.com/pawitp/fb74c6da0a8e9e5f6738669c8e502195) is the gist that reverts that commit.

To apply it:
```
cd /usr/share/cinnamon/applets
# Backup
cp -pR grouped-window-list@cinnamon.org ~/Desktop/grouped-window-list@cinnamon.org.bak
# Apply the patch
curl https://gist.githubusercontent.com/pawitp/fb74c6da0a8e9e5f6738669c8e502195/raw/0c145dc936253fd339574bb18b81c720a42e8855/super_num.patch | sudo patch -p0
```

**Comment by michalzubkowicz** [comment] 2019-12-25 17:59
@clefebvre , you are the author of this change, could you please explain what's the point of removing such important feature? Can we revert it back?

**Comment by rodrigograca31** [comment] 2019-12-26 12:59
I'm here do show my support for this feature.
I can't understand why it would ever be removed.... :disappointed: 
Its what makes cinnamon awesome and all OSs have this feature nowadays.

Please bring back `SUPER + n`  && `SUPER + SHIFT + n`

**Comment by 1998marcom** [comment] 2019-12-26 13:53
Another workaround that now (Dic 2019) works is just to copy-paste an old version of the "Grouped windows list" applet (e.g. from the 4.2-maintainance branch) in the applet folder `/usr/share/cinnamon/applets`, maybe after a backup.
A bovine way of doing so would be:
```
# Backup
cd /usr/share/cinnamon/applets
cp -pR grouped-window-list@cinnamon.org ~/Desktop/grouped-window-list@cinnamon.org.bak
# Getting a copy of old cinnamon source
cd /tmp
git clone https://github.com/linuxmint/cinnamon
cd cinnamon
git checkout 4.2-maintenance
# Copying the "Grouped windows list" applet
STARTFOLDER=/tmp/cinnamon/files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org
DESTFOLDER=/usr/share/cinnamon/applets/
cp -R $STARTFOLDER $DESTFOLDER
```
Maybe a Cinnamon restart is necessary after this.

**Comment by mathiasbaldissera** [comment] 2019-12-28 00:14
Maybe the Cinnamon team can bring back this function and create an option to enable/disable this in the applet preferences

**Comment by rodrigograca31** [comment] 2019-12-28 16:02
Just received an update for cinnamon 4.4.6+tricia that said this on the changelog:
```
   [ Clement Lefebvre ]
   * Revert "GWL: Remove hotkeys"
```

After restarting cinnamon it seems to work again! :tada:

**Closed** 2019-12-28 23:23 UTC
