### ISSUE TITLE
Battery status not updating

### ISSUE THREAD

**Issue by moorkai** [linuxmint/Cinnamon#4176] opened 2015-05-22 11:43 UTC
*~~This is a copy of my comment on issue #3068~~ (comment deleted, unnecessary double posting)*

I have built the 2.6.1 Cinnamon GitHub release as well as other dependencies needed for Cinnamon to build successfully (as per Mint's [Segfault] (http://segfault.linuxmint.com/2013/10/how-to-build-and-install-the-latest-cinnamon-from-git/) post) on my Vivid laptop and am encountering this issue. Prior to that, I was using [Tsvetko's build] (https://launchpad.net/~tsvetko.tsvetkov/+archive/ubuntu/cinnamon) of Cinnamon 2.4.8 as well as the dependencies found there on Utopic and everything was kinda fine, sans the *installing Trusty packages on Utopic* part. Updated to Vivid, built new Cinnamon, and ... here I am. "upower -d" properly shows battery percentage, unlike the **Power Manager applet** and the **Power Management part of Cinnamon Settings** which do not update at all, only on reboots (and perhaps when I log in-log out). 

**EDIT:** Just noticed Cinnamon 2.6.2 is out, is it maybe addressed there? Building updated packages, will report back.

**EDIT 2:** Changelogs don't speak a lot about batteries, will build nevertheless.

**EDIT 3:** Built all the new stuff, no difference.

**EDIT 4:** Specs and stuff.
I'm running AMD64 Ubuntu 15.04 Vivid, converted from Lubuntu to Ubuntu with Cinnamon, MATE behind and perhaps some remnants of LXDE (other DE's fighting with Cinnamon readings?). The computer I'm running it on is a Fujitsu LifeBook AH531 laptop, Sandy Pentium B950 chip, GeForce-less variant of AH531, so only on-chip Intel HD graphics (using Intel proprietary drivers BTW, if it affects something).

**Comment by moorkai** [comment] 2015-05-22 11:49
This issue **is** a duplicate of #3068 and #3121, but as they're closed, I thought no-one will receive notifications about updates there. Sorry for double posting. If there is some kind of a GitHub rules page, etiquette, I'd gladly read it to act accordingly.

**Comment by dalcde** [comment] 2015-05-22 11:59
No we actually *do* receive notifications for closed issues.

No you should not post your issue twice. If you think no one will read the closed thread, don't post it there. We are now getting notifications for the same issue twice.

No this is not a duplicate of #3068. That was an issue with 2.2 and was fixed. This is a separate issue that happens to have the same symptoms.

No there is no GitHub rules page. Only common sense is required.

**Comment by moorkai** [comment] 2015-05-22 12:03
Sorry, first time doing *anything* semi-relevant on GitHub sans that one or two comments and a test repository, so now that I know, I will make sure it doesn't happen again. Message on #3068 deleted (wrong?). I didn't know about the rest though. Thanks for informing me.

**Comment by moorkai** [comment] 2015-05-23 19:29
This awful, dirty hack seems helpful:
````
while [ 1 == 1 ]; do killall cinnamon-settings-daemon; killall cinnamon-settings-daemon; sleep 1; cinnamon-settings-daemon & sleep 120; done
````
Seems like it's *cinnamon-settings-daemon* to be blamed. Should this issue be moved (if possible) to *cinnamon-settings-daemon* repo then?

**Comment by moithil** [comment] 2015-05-23 20:16
when is cinnamon 2.6 going to be available from the stable repos? I want to check the battery applet and tuts say i have to install cinnamon 2.6 from unstable repository.

**Comment by moorkai** [comment] 2015-05-23 20:21
Yeah, I didn't like it either, so I built it myself and uploaded it on [my PPA] (https://launchpad.net/~moorkai/+archive/ubuntu/cinnamon). Utopic and Vivid builds only.

**Comment by dalcde** [comment] 2015-05-24 06:33
What is the output of the command 
```
gsettings get org.cinnamon.desktop.session use-systemd
```

**Comment by moorkai** [comment] 2015-05-24 13:01
The output is ``false``

**Comment by dalcde** [comment] 2015-05-24 13:04
Try
```
gsettings set org.cinnamon.desktop.session use-systemd true
```
Probably Cinnamon thought you weren't using systemd while you actually are.

**Comment by moorkai** [comment] 2015-05-24 14:31
Entered, but sadly, it doesn't remedy the problem.

**Comment by dalcde** [comment] 2015-05-24 14:36
Even after restart? What are you currently running?

**Comment by dalcde** [comment] 2015-05-24 14:38
If you are running a sufficently new version of Cinnamon, you will need to do run the same command with `use-systemd` replaced with `screensaver-uses-logind`, `session-manager-uses-logind` and `settings-daemon-uses-logind`.

**Comment by moorkai** [comment] 2015-05-24 16:37
I first replied, then rebooted :smiley:, but still it didn't work when I set *use-systemd* to true.
Typed ``gsettings set org.cinnamon.desktop.session use-systemd true; gsettings set org.cinnamon.desktop.session screensaver-uses-logind true; gsettings set org.cinnamon.desktop.session session-manager-uses-logind true; gsettings set org.cinnamon.desktop.session settings-daemon-uses-logind true`` in terminal.
Got this:
```
No such key 'screensaver-uses-logind'
No such key 'session-manager-uses-logind'
No such key 'settings-daemon-uses-logind'
```
Is something outdated in my system?

**Comment by dalcde** [comment] 2015-05-24 16:43
Your system is outdated by a few days :) Try updating (recompiling *everything* from git) and see if there is any difference (I doubt it, though). Am I right that ubuntu is fully on systemd?

**Comment by moorkai** [comment] 2015-05-24 16:44
I see that later commits which (I think) didn't make its way to the latest releases split these gsettings keys.

**Comment by moorkai** [comment] 2015-05-25 17:27
Built May 25 releases. Typed ``gsettings set org.cinnamon.desktop.session screensaver-uses-logind true; gsettings set org.cinnamon.desktop.session session-manager-uses-logind true; gsettings set org.cinnamon.desktop.session settings-daemon-uses-logind true``. Window-specific keyboard layouts, keep maximum brightness and battery status issues seem fixed now. Yay!

Will report if the battery applet problem happens again, but for now it seems solved. Other mentioned issues bugged me too, but not as much as this one, so I skipped on reporting them.

**Comment by moorkai** [comment] 2015-05-25 17:35
Kinda OT (so if it is too much of a digression from this issue, please let me know where it belongs more), but it seems relevant to Cinnamon ... I get this error when I'm building signed Cinnamon packages:
````
gpg: WARNING: The GNOME keyring manager hijacked the GnuPG agent.
gpg: WARNING: GnuPG will not work properly - please configure that tool to not interfere with the GnuPG system!
````
I don't recall seeing this before.

**Comment by dalcde** [comment] 2015-05-25 17:38
It seems to be an issue with the GNOME keyring manager or gpg. I'm pretty sure it is not a Cinnamon issue. Closing since the original problem is solved

**Closed by dalcde** 2015-05-25 17:38 UTC
Labels: BUG
