### ISSUE TITLE
Copy and paste only works when nemo file manager is open

### ISSUE THREAD

**Issue by antoxa78** [linuxmint/cinnamon#10393] opened 2021-10-16 07:07 UTC
```
 * Cinnamon version 5.0.6
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). No
 * Distribution - Mint 20.2
 * Graphics hardware *and* driver used: Nvidia RTX 2060 + Nvidia  470.74 display driver
 * 64 bit

 ```

Hi! i have the the issue with latest cinnamon version in Linux Mint 20.2
Copy and paste only works when i leave nemo file manager (my version is 5.0.4) is open 

**Steps to reproduce**
1. open file in nemo file manager and select any file
2. right click and select copy
3. close the nemo file manager
4. right click and paste option will  not be available

**Expected behaviour**

**Other information**
this bug is not affected for files located on desktop

**Configuration info, if applicable**
System:    Kernel: 5.11.0-37-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.0.6 
           wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Dell product: G5 5500 v: N/A serial: <filter> Chassis: type: 10 
           serial: <filter> 
           Mobo: Dell model: 039Y47 v: A02 serial: <filter> UEFI: Dell v: 1.10.1 date: 08/13/2021 
Battery:   ID-1: BAT0 charge: 64.4 Wh condition: 64.4/68.0 Wh (95%) volts: 16.2/15.2 
           model: BYD DELL W5W190C serial: <filter> status: Full 
           Device-1: hidpp_battery_0 model: Logitech M705 serial: <filter> charge: 95% 
           status: Discharging 
CPU:       Topology: 6-Core model: Intel Core i7-10750H bits: 64 type: MT MCP arch: N/A 
           L2 cache: 12.0 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 62399 
           Speed: 800 MHz min/max: 800/5000 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 801 
           5: 800 6: 800 7: 800 8: 800 9: 800 10: 800 11: 800 12: 800 
Graphics:  Device-1: Intel UHD Graphics vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:9bc4 
           Device-2: NVIDIA TU106 [GeForce RTX 2060] vendor: Dell driver: nvidia v: 470.74 
           bus ID: 01:00.0 chip ID: 10de:1f15 
           Display: x11 server: X.Org 1.20.11 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa resolution: 1920x1080~300Hz 
           OpenGL: renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2 v: 4.6.0 NVIDIA 470.74 
           direct render: Yes 
Audio:     Device-1: Intel Comet Lake PCH cAVS vendor: Dell driver: sof-audio-pci bus ID: 00:1f.3 
           chip ID: 8086:06c8 
           Device-2: NVIDIA TU106 High Definition Audio vendor: Dell driver: snd_hda_intel 
           v: kernel bus ID: 01:00.1 chip ID: 10de:10f9 
           Sound Server: ALSA v: k5.11.0-37-generic 
Network:   Device-1: Intel Wi-Fi 6 AX201 vendor: Bigfoot Networks driver: iwlwifi v: kernel 
           port: 6000 bus ID: 00:14.3 chip ID: 8086:06f0 
           IF: wlp0s20f3 state: up mac: <filter> 
           Device-2: Realtek vendor: Dell driver: r8169 v: kernel port: 3000 bus ID: 08:00.0 
           chip ID: 10ec:2502 
           IF: enp8s0 state: down mac: <filter> 
Drives:    Local Storage: total: 1.40 TiB used: 269.65 GiB (18.8%) 
           ID-1: /dev/nvme0n1 model: KXG60ZNV1T02 NVMe KIOXIA 1024GB size: 953.87 GiB 
           speed: 31.6 Gb/s lanes: 4 serial: <filter> 
           ID-2: /dev/sda type: USB vendor: Transcend model: TS512GSSD230S size: 476.94 GiB 
           serial: <filter> 
Partition: ID-1: / size: 31.83 GiB used: 16.91 GiB (53.1%) fs: ext4 dev: /dev/sda2 
           ID-2: /home size: 434.36 GiB used: 252.70 GiB (58.2%) fs: ext4 dev: /dev/sda4 
           ID-3: swap-1 size: 1.91 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 59.0 C mobo: N/A gpu: nvidia temp: 57 C 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb https: //dl.winehq.org/wine-builds/ubuntu/ focal main
           Active apt repos in: /etc/apt/sources.list.d/graphics-drivers-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/inkscape_dev-stable-focal.list 
           1: deb http: //ppa.launchpad.net/inkscape.dev/stable/ubuntu focal main
           No active apt repos in: /etc/apt/sources.list.d/linrunner-tlp-focal.list 
           Active apt repos in: /etc/apt/sources.list.d/linuxuprising-apps-focal.list 
           1: deb http: //ppa.launchpad.net/linuxuprising/apps/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/linuxuprising-java-focal.list 
           1: deb http: //ppa.launchpad.net/linuxuprising/java/ubuntu focal main
           No active apt repos in: /etc/apt/sources.list.d/lutris-team-lutris-focal.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com uma main upstream import backport
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           No active apt repos in: /etc/apt/sources.list.d/openshot_developers-ppa-focal.list 
           Active apt repos in: /etc/apt/sources.list.d/teamviewer.list 
           1: deb https: //linux.teamviewer.com/deb stable main
           Active apt repos in: /etc/apt/sources.list.d/ubuntuhandbook1-apps-focal.list 
           1: deb http: //ppa.launchpad.net/ubuntuhandbook1/apps/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/vivaldi.list 
           1: deb http: //repo.vivaldi.com/stable/deb/ stable main
Info:      Processes: 330 Uptime: 32m Memory: 15.40 GiB used: 1.68 GiB (10.9%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 8/9 Client: Unknown python3.8 client 
           inxi: 3.0.38 

Please paste here

```

**Comment by antoxa78** [comment] 2021-10-16 14:09
Yes it is the same issue

**Comment by leigh123linux** [comment] 2021-10-17 07:35
Duplicate of https://github.com/linuxmint/cinnamon/issues/10204

**Closed by leigh123linux** 2021-10-17 07:35 UTC
