### ISSUE TITLE
Weird behavior with snapped windows.

### ISSUE THREAD

**Issue by radorn** [linuxmint/cinnamon#12139] opened 2024-03-30 04:59 UTC
### Distribution

Linux Mint 21.3 Cinnamon

### Package version

6.0.4

### Graphics hardware in use

Intel i7-1255U integrated graphics

### Frequency

Always

### Bug description

Under specific circumstances, dragging the joint edge between two windows snapped to the sides of the screen causes the window to the left to randomly change its height for no apparent reason.

### Steps to reproduce

With two windows snapped to the sides of the screen, with the rightmost window having focus, if I try to grab and drag the middle intersection, soon, the rightmost window starts to fluctuate in size vertically while remaining snapped to the top and right of the screen and the other window, but not the bottom.
Works with any two apps.

https://github.com/linuxmint/cinnamon/assets/10700998/2ba93940-4b98-482a-83b3-b8ccd650adf4

### Expected behavior

I'd say the window on the right side should not change in height when dragging the middle joint side to side.

**Comment by elduglas** [comment] 2024-03-30 21:34
same issue https://github.com/linuxmint/cinnamon/issues/11219

**Comment by rcalixte** [comment] 2024-03-31 01:04
Duplicate of #11219

**Closed by rcalixte** 2024-03-31 01:03 UTC
Labels: BUG
