### ISSUE TITLE
Screen locking leaves Virtualbox machines in full-screen exposed

### ISSUE THREAD

**Issue by ralienpp** [linuxmint/cinnamon#3619] opened 2014-10-28 12:18 UTC
If a Virtualbox system is running in full-screen mode and the computer is left unattended for a period of time:
- the screen is dimmed
- when the mouse is moved, the screen is turned on and I have unhindered access to the VM
- when the VM is shutdown - I see Cinnamon's lock-screen and authentication prompt

In other words, the lock only affects my desktop, but leaves the virtual machines exposed.

The expected behaviour is to have everything locked and prevent any form of UI interaction.

**Comment by MiguelMCarrillo** [comment] 2015-04-21 17:44
It also happens when running the virtual machine in normal mode (no full-screen) and mouse integration is disabled. If mouse integration is enabled it works as expected.

Using Cinnamon 2.2.16

**Comment by kroghnet** [comment] 2015-08-23 14:22
I have the same problem using minecraft (1.8.8) in full-screen; when leaving my computer with the game open, the game is still showing after the screen is locked. The game acts funny, though - probably due to the input being captured by the lock screen).

**Comment by lcafaro** [comment] 2016-05-08 13:53
Confirmed in Cinnamon 2.8.8 on Linux Mint 17.3 + VirtualBox 5.0.4 running a Windows 7 guest.

If a virtual machine is left running in full screen, the Cinnamon lock screen isn't able to lock anymore, leaving access to the VM exposed.

**Comment by Vahan86** [comment] 2017-02-05 16:49
@ralienpp, is this still an issue for you with Cinnamon 3.2?

**Comment by ralienpp** [comment] 2017-02-07 11:12
I have no way to test it at the moment, but I will get back to you within several days and let you know how things went.

**Comment by Vahan86** [comment] 2017-05-13 04:23
@JosephMcc, can we close this issue?

**Comment by metabubble** [comment] 2017-06-14 18:35
Why did you close that? The Problem still exists with Cinnamon 3.2

**Comment by metabubble** [comment] 2017-06-14 18:39
Cinnamon is set up to lock the screen after 10 Minutes of inactivity. Works fine when Virtualbox is not running with focused window.
 
Steps to reproduce:
- install virtualbox
- start a virtual machine, don't know if it matters what the guest is, but in my case it is Windows 7 with VirtuallBox Guest addons installed
- focus the Virtualbox window
- leave computer alone until screen turns off

move the mouse: you will not be required to enter your password
Expected behavior: Desktop is locked

**Comment by icarter09** [comment] 2019-11-13 03:27
Has this issue been tested against other operating systems?

**Closed** 2020-04-11 02:56 UTC
Labels: Gathering Info

**Comment by oyxnaut** [comment] 2020-11-26 13:58
This still happens with virtualbox-6.1.16-140961-ubuntu-bionic using gnome as desktop environment.
