### ISSUE TITLE
Two Instances of nm-applet Running

### ISSUE THREAD

**Issue by gareththered** [linuxmint/Cinnamon#2702] opened 2013-12-06 15:34 UTC
Not certain who this bug should sit with...

v 0.9.9.0-7 (revision 2940) (http://bazaar.launchpad.net/~vcs-imports/network-manager-applet/git-master/revision/2940 ) and later of network-manager-applet start nm-applet; apparently, in order to support some non-Gnome-Shell desktops.  Cinnamon also starts nm-applet.  The end result is two instances running and two notifications for network (dis)connects.

Who should change?  Cinnamon or network-manager-appet?  I'd suggest Cinnamon as a change to network-manager-applet would have repercussions across a wider community.

I've noticed this on Fedora 20, by the way - not sure how widespread the issue is.

**Comment by MartinThoma** [comment] 2015-02-19 10:12
Just in case somebody else still has this problem:

```python
#!/usr/bin/env python

"""Kill nm-applet if there are exactly two."""

# Add this to your .profile:
#  python /your/absolute/path/killnmappletdupe.py

import os
import signal

pids = [pid for pid in os.listdir('/proc') if pid.isdigit()]
nm_applets = []
for pid in pids:
    try:
        command = open(os.path.join('/proc', pid, 'cmdline'), 'rb').read()
        command = command.rstrip('\0')
        if "nm-applet" == command:
            nm_applets.append(int(pid))
            # print(pid)
            # print(command)
    except IOError:  # proc has already terminated
        continue

if len(nm_applets) == 2:
    os.kill(nm_applets[1], signal.SIGQUIT)
```

**Comment by Vahan86** [comment] 2016-09-05 20:18
@JosephMcc, it seems the issue is fixed. Can we close it?

**Closed** 2016-09-06 03:39 UTC
