### ISSUE TITLE
Cannot add applets to panels

### ISSUE THREAD

**Issue by shred** [linuxmint/Cinnamon#7051] opened 2017-11-19 13:03 UTC
```
 * Cinnamon 3.6.3
 * Fedora 27
 * Intel Graphics and Kernel driver
 * 64 bit
 ```

**Issue**
It is not possible to add applets to panels any more. There is no button to do so.

**Steps to reproduce**
* RMB click into a panel.
* Select "add applet to panel".
* The Applet dialog opens. All installed applets are listed and can be selected.
* There is no button to actually add the selected applet to the panel. Also the attempt to double-click the applet, or drag-and-drop it to the panel, does not work.

**Expected behaviour**
There should be way to add the selected applet to a panel.

**Screenshot**

This is how my Applet dialog looks like when I am trying to add the calendar applet.

![bildschirmfoto vom 2017-11-19 14-00-17](https://user-images.githubusercontent.com/505118/32990911-13f65062-cd32-11e7-8fd2-70aeccf2e125.png)

**Comment by leigh123linux** [comment] 2017-11-19 14:01
Resizing the window will make the missing buttons appear.

**Comment by leigh123linux** [comment] 2017-11-19 14:04
Duplicate of #7018

**Closed by leigh123linux** 2017-11-19 14:04 UTC

**Comment by shred** [comment] 2017-11-19 15:00
Thank you. Sorry for the duplicate... Actually I have tried resizing it, but I didn't expand the window wide enough.
