### ISSUE TITLE
Feature Request: Workspace switcher window icons.

### ISSUE THREAD

**Issue by nervecenter** [linuxmint/cinnamon#9425] opened 2020-07-03 03:15 UTC
Commonly seen in workspace switchers under various desktops, including XFCE, KDE, etc. Makes the switcher wonderfully readable at a glance. Not sure how much more detail I can provide given how commonplace of a feature it is. I'd simply ask that the icons are either configurable, or that the chosen defaults make them decently large, even when the window is sized strangely, such as a thin, tall portrait orientation.

**Comment by xenopeek** [comment] 2020-07-03 05:50
Duplicate of #7320

**Closed by xenopeek** 2020-07-03 05:50 UTC
