### ISSUE TITLE
Bluetooth is reactivated after reboot 

### ISSUE THREAD

**Issue by damnfella** [linuxmint/cinnamon#9072] opened 2019-12-29 19:58 UTC
```
 * Cinnamon 4.4.6
   - the standard one used in Linux Mint 19.3
 * Linux Mint 19.3
 * Graphics hardware *and* driver used
 * 64-bit
 * [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4008499/xsession-errors.txt)
```

**Issue**
I found the same exact issue (#1244) in the current version of Linux Mint.
Bluetooth is reactivated on reboot even after turning it off in the last session.

**Steps to reproduce**
Start Linux Mint. Turn off Bluetooth. Reboot. 
> Bluetooth stays ON

**Expected behaviour**
Start Linux Mint. Turn off Bluetooth. Reboot.
> Bluetooth stays OFF

***
**Additional info: I had recently updated from Linux Mint Tina (19.2) to Tricia (19.3), using the command line:** `sudo apt full-upgrade`

**Comment by icarter09** [comment] 2019-12-29 21:01
Linux Mint 19.3 64bit
Cinnamon 4.4.6

I'm not able to reproduce this issue.

**Comment by damnfella** [comment] 2020-01-02 16:08
Additional info: I had recently updated from Linux Mint Tina (19.2) to Tricia (19.3), using the command line: `sudo apt full-upgrade`. Many updates/features seemed to be missing out of the box, including the new grub menu. Which I got in a later update.

Seems like this is a linux mint issue, so I'll move this issue to Linuxmint/linuxmint. Feel free to close if it really is.

**Comment by claudiux** [comment] 2020-01-02 22:57
@damnfella The right way to upgrade from 19.2 to 19.3 is here: https://blog.linuxmint.com/?p=3838

**Comment by xenopeek** [comment] 2020-01-11 10:29
Closing this here to avoid discussing same issue in two places.

**Closed by xenopeek** 2020-01-11 10:29 UTC
