### ISSUE TITLE
Segmentation fault for Backgrounds module when org.cinnamon.desktop.background primary-color set to non hex

### ISSUE THREAD

**Issue by euxneks** [linuxmint/Cinnamon#5517] opened 2016-08-03 18:01 UTC
Don't ask me how I managed to get org.cinnamon.desktop.background primary-color set to just 'FFFFFF', but it happened :\ In any case, I managed to fix this but I think this is a bug with either the Backgrounds module or gnome - you can reproduce this bug easily and fix it just as easily:

For some reason my org.cinnamon.desktop.background primary-color was set to FFFFFF (note no #). When attempting to change my background afterwards, cinnamon settings would segfault on the Backgrounds module. I managed to trace the issue to GSettingsColorChooser in cs_backgrounds.py.  

Perhaps this should try to gracefully recover from the problem data instead of "shitting the bed" :P

I am using Linux Mint 17.2 'Rosa' cinammon 64-bit

set org.cinnamon.desktop.background primary-color to 'FFFFFF':
`gsettings set org.cinnamon.desktop.background primary-color 'FFFFFF'`
`cinnamon-settings backgrounds` will now Segmentation Fault.
To FIX:

`gsettings set org.cinnamon.desktop.background primary-color '#FFFFFF'`
`cinnamon-settings backgrounds` works fine now.

**Comment by xenopeek** [comment] 2016-08-24 08:28
I can reproduce this on Linux Mint 18 with Cinnamon 3.0.7.

Running the commands:
`gsettings set org.cinnamon.desktop.background primary-color 'FFFFFF'`
`cinnamon-settings backgrounds`

Results in:
> Loading Backgrounds module
> Segmentation fault

**Comment by JosephMcc** [comment] 2016-08-24 09:29
To be fair you can break a great deal of things by entering improper values for gsettings. I would be more concerned if the wrong value was being set from cinnamon settings and causing the problem.

**Comment by xenopeek** [comment] 2016-08-24 17:17
I retested this on Linux Mint 17 and 17.3 and I can't reproduce it any way other than "cheating" a bit with gsettings command.

Picking a color for the background ignores anything I type in the box except hash (#) followed by exactly 6 hexadecimal digits (0-9 A-F a-f). Entering anything else just leaves the color selected in the colors slab underneath it.

primary-color and secondary-color are currently stored as gvariant type string ("s") with no option to limit what gsettings can enter. Only thing I can think of would be to store them as gvariant type uint32 ("u") and add `<range min="0" max="16777215"/>` to the schema file.

**Comment by JosephMcc** [comment] 2016-08-24 17:33
In the xlet settings revamp that just landed in Cinnamon the color chooser widget now actually wants to use an rgba value. So something like rgba(0,0,0,0). We have a workaround in place specifically for the background color settings because the background code in cinnamon-desktop is still using the older Gdk.Color. Once we update this the bg settings will also use an rgba value.

**Comment by euxneks** [comment] 2016-08-24 20:47
In between the time I submitted this bug and now I've managed to find the offending code that made my background primary colour bad - a piece of software that made my background a "live" picture of earth from a satellite managed to set the background color to "FFFFFF" without the hash.

I still think this shouldn't produce a segmentation fault from the system but should be caught and dealt with in a sane manner - even just deleting the offending value is better in my mind than preventing me from using the GUI :)

**Comment by JosephMcc** [comment] 2017-04-22 22:55
Missed this one. This is fixed.

**Closed by JosephMcc** 2017-04-22 22:55 UTC
Labels: BUG REPRODUCED
