### ISSUE TITLE
'cinnamon-settings startup': one huge icon

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7697] opened 2018-07-05 18:18 UTC
```
 * Cinnamon version (cinnamon --version): 3.8.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used: NA?
 * 32 or 64 bit: 64
 ```

**Issue**

This does not look right . .

![image](https://user-images.githubusercontent.com/9998846/42340501-179b2314-8088-11e8-8552-cef60d4f701a.png)

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by CottonEaster** [comment] 2018-07-07 18:12
Install `indicator-stickynotes` (from, I think, the repositories). Add it to startup using Startup-Manager -> Choose Application.

**Comment by JosephMcc** [comment] 2018-07-07 18:21
I was going to look into this but indicator-stickynotes doesn't exist in the repos.

**Comment by icarter09** [comment] 2018-07-07 18:40
@CottonEaster I installed the stickynotes application using the ppa you posted. Checked for it through the Startup Application and not experiencing the problem that your screen capture shows. Maybe reinstalling it fresh on Mint 19 will fix the issue.

**Comment by JosephMcc** [comment] 2018-07-07 18:41
It likely only shows up under HiDPI.

**Comment by CottonEaster** [comment] 2018-07-07 18:42
@icarter09 
I reinstalled it - no change. Then I found that the PPA had a new version, so I installed that.
But, as I said above, I think, I do have HiDPI (Lenovo X1 Carbon, model code: 20KHCTO1WW).

**Comment by icarter09** [comment] 2018-07-07 18:56
@CottonEaster thanks for trying that out. @JosephMcc is probably correct that the issue shows up under HiDPI.

**Comment by JosephMcc** [comment] 2018-07-07 20:30
Maybe a stupid question but have you installed all updates and restarted your machine since reporting this. It started working fine here.

**Comment by CottonEaster** [comment] 2018-07-07 22:34
I have, yes.

If you could point to a good system information tool, or bash one-liner, I can provide more information on my system.

**Comment by germanfr** [comment] 2018-07-08 07:38
I can reproduce with the Arc theme and the `image-missing` icon, which doesn't have a smaller version in this theme. The command is a Manjaro preinstalled command to launch the update checker.
![screenshot from 2018-07-08 09-35-19](https://user-images.githubusercontent.com/10391266/42417763-4e156cea-8292-11e8-933d-c809452b8f77.png)

**Comment by CottonEaster** [comment] 2018-10-25 17:38
I have just installed the application `flameshot` (from a .deb provided by its github site) and . . 

![image](https://user-images.githubusercontent.com/9998846/47519286-25ba0c80-d885-11e8-949b-ce6f2580683f.png)


I note that flameshot is a qt application.

**Comment by CottonEaster** [comment] 2018-12-20 16:08
The problem persists on Mint 19.1:

![image](https://user-images.githubusercontent.com/9998846/50296028-68592900-0471-11e9-8152-9dbc5d702e62.png)

**Comment by umangv** [comment] 2019-02-11 20:50
I'm the developer of indicator-stickynotes and I don't know why this is happening. Under `/usr/share/icons/hicolor` the package provides 48x48, 256x256, and scalable icons. The icon displayed here does not look to be either 48x48 or 256x256. Could a cinnamon developer suggest what I might be able to do to address this?

**Comment by Vahan86** [comment] 2019-11-30 05:37
@germanfr, is this still an issue in Cinnamon 4.2?

**Comment by germanfr** [comment] 2019-12-03 20:39
Yes, @Vahan86. This is still an issue.

**Comment by mtwebster** [comment] 2019-12-03 21:15
Hi, I just pushed a fix for this - it's rather vulgar but it's the most effect way to avoid this problem.

It's only two lines if someone wants to copy/paste test it :smile: .  I'll close this once I have some confirmation.

Thanks

**Comment by germanfr** [comment] 2019-12-03 21:29
Yes, that works for me at least @mtwebster.

**Closed** 2019-12-03 22:46 UTC
Labels: BUG
