### ISSUE TITLE
Open window list misbehaves if too many windows are open.

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#6778] opened 2017-08-06 08:30 UTC
```
 * Cinnamon version: 3.4.4
 * Distribution - Arch
 * Graphics: Intel i5-5200U integrated, modesetting driver
 * 64 bit
 ```

**Issue**
If you open really many windows in a Cinnamon session, they start to overlap with the status area, and some of them just go out of the screen (see the `1` in the screenshot?) It's the time/date applet.
![screenshot from 2017-08-06 10-27-12](https://user-images.githubusercontent.com/2914938/29001711-3dce6e6c-7a92-11e7-9124-f1057eb57854.png)

**Steps to reproduce**
Just open a load of windows.

**Comment by leigh123linux** [comment] 2017-08-06 08:57
Duplicate of #4646

**Closed by leigh123linux** 2017-08-06 08:57 UTC
