### ISSUE TITLE
system-config-printer-applet doesn't appear in Cinnamon tray

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/cinnamon#2476] opened 2013-10-15 18:59 UTC
Hello,

I'm using the new Cinnamon 2.0 release on Arch. I frequently use the system-config-printer-applet, which appears in the system tray whenever documents are stuck in the print queue due to some kind of printer issue. This icon will not appear in the Cinnamon system tray. I have confirmed that the "applet.py" process for the printer applet is running. The applet works perfectly on Mate and Openbox desktops.

Thanks in advance for looking into this.

**Comment by brub2** [comment] 2015-06-23 17:20
Still an issue here (Mint 17.1 Cinnamon 2.6). 

Can someone tell us if it is considered as the normal behavior of Cinnamon (have notifications but no tray icon) or a bug? Said otherwise, should we ask for a fix or a "new feature"?

**Comment by BandonRandon** [comment] 2015-07-01 07:26
I feel this is the intended behaviour, one option would be to create an optional printer applet.

**Comment by sb56637** [comment] 2015-07-01 12:25
It makes more sense for an applet to appear like it does in Mate. This prevents clutter on the panel, but it gives the user the opportunity to easily cancel printing when there is a mistaken print job.

**Comment by brub2** [comment] 2015-07-01 13:16
I also think that it should appear like it does in others environments. I don't know if notification messages are more complete in cinnamon (maybe the justification to not have the icon?).

**Comment by sb56637** [comment] 2015-07-01 17:58
The notification is nice too, but the problem is that you can't interact with it. If I accidentally send a 100 page document to the printer, or if it jams, I need quick access to the queue, I don't want to be digging around for it.

**Comment by brub2** [comment] 2015-07-01 22:33
I totally agree...

**Comment by asoltesz** [comment] 2015-08-04 09:47
I also have this problem with Mint 17 x64.

The tray applet has worked properly on my previous Linux desktops (only appears when there is something in the print queue, otherwise hidden).

Cinnamon should behave exactly the same as the MATE edition from this respect. The current behaviour is not user friendly at all since users have no easy way to access the queue when something unexpected happens during printing. (e.g. the user sends the doc to the printer but the printer was not yet switched on. Then the user switches the printer on but the docs are not sent out from the queue to the printer at all, or one has to wait a LOT of time for them to be sent out)

This is a rough edge on Cinnamon and should be polished away as soon as possible. Users need direct feedback and interactivity about the printing process and the tray icon is the well-known way to do that.

**Comment by Piiit** [comment] 2016-06-28 18:12
https://github.com/linux-man/cinnamon-printers looks promising...

**Comment by geckolinux** [comment] 2016-06-28 18:34
On 06/28/2016 01:12 PM, Piiit wrote:
> https://github.com/linux-man/cinnamon-printers looks promising...

Hmm! Nice find, thank you!

**Comment by lestcape** [comment] 2016-10-17 07:50
@Piiit I disagree, this not looks promising, but probably will work on this way. What I think it's needed, is an introspection binding for cups... I don't know why this is not development or i can not find where it is...

**Comment by Piiit** [comment] 2016-10-17 12:54
@lestcape Hi, I guess you are right, but I have no clue how these things should work. However, it is important that the applet does not slow down or interfere with Cinnamon. Asynchronuous spawning of subprocesses is the right way, I think. 
Nevertheless, it is important to have such an applet, and with the lack of an alternative I think this one is a nice-to-have. I use it now already over some months without problems.

**Comment by lestcape** [comment] 2016-10-18 02:36
@Piiit but see the roadmap, apparently @clefebvre has the idea of create a printer applet, so not only will be a thing of work or not work, you need to find a way to not load cinnamon with a lot of loops for try to find the printer and the jobs state. The solution of the applet it's not in this way, he make a loop constantly...

There are i think a way to listen notification when they occurs without need to iterate and ask the state of all things from the command line, This is if we use the cups.Notifier DBus service:
http://fossies.org/linux/cups-filters/utils/org.cups.cupsd.Notifier.xml

As an interesting things, there are an implementation of cupsd.Notifier in the cinnamon-settings-daemon:
 https://github.com/linuxmint/cinnamon-settings-daemon/blob/22510cc0c2f30d7093006de0b03002bc61dcc6b9/plugins/print-notifications/csd-print-notifications-manager.c#L47

But there are not a way to read the current state of all printer and all jobs when for example you restart cinnamon (at less i don't know how). Thats normally can be read from the cups library, but the cups library have not an introspection, so can not be access directly from gi repository and then probably we can not read it in cjs. At less, i don't know how read it, without create the support for accessing to cups using a cinnamon class as an intermediary.

**Comment by geckolinux** [comment] 2016-10-18 02:40
I know absolutely nothing about programming for Cinnamon, but would it be possible to take a look at how Mate does it? Mate has always supported this functionality and it's not slow or CPU intensive.

**Comment by lestcape** [comment] 2016-10-18 02:48
@geckolinux The mate applet can be implemented in c++, where you have access to the cups library, or also can be implemented in python where there are a python bindings to access to the cups library. If you want to implement an applet in javascript you need like on mate an intermediary class to access the cups library. I can not find any implementation of this intermediary library and thats the problem.

**Comment by Piiit** [comment] 2017-01-04 10:37
I think that https://cinnamon-spices.linuxmint.com/applets/view/251 is a good candidate for a tray icon of this configuration tool. Could we close this issue therefore?

**Comment by lestcape** [comment] 2017-01-04 22:12
@linux-man of course this is not your fault and also create a binding without packaging it to most commons distros, will also not resole anything for an standard user, but like you say  "Like most programmers, I see this method as a 'hack'" and if it's for be a part of a desktop, i think with much more reason. There are also a Gtk binding to the printer system, that also it's not a module with introspection.

**Comment by linux-man** [comment] 2017-01-04 23:48
@lestcape Don't get me wrong: I don't fell bad at all! When I fell bad I blame Gnome devs for choosing JS as a Desktop language. It's really their fault! :wink:
I know that when there is no other way, a "hack" is the way to go, and I'm not alone: 1/3 of the official Cinnamon applets use spawn. Sound applet uses spawn_async! Just don't depends heavily on it...
Having defended my "baby", I still think there will be a better way. Just not right now.

**Comment by lestcape** [comment] 2017-01-05 00:34
@linux-man i have a binding to the printer events here: https://github.com/lestcape/Printers/blob/master/printers%40lestcape/printerManager.js (thats it's directly from cups events) just i have not a way to list printers and printers jobs... Probably I will need just one spaw to initialized the applet, and then i could update it just capturing the signals and without any other call to spaw... Thats in my opinion it's better, than always spaw the command line... But, also i don't like it.

**Comment by linux-man** [comment] 2017-02-03 23:39
Last days I noticed the appearance of a non-symbolic printer icon (gray) when printing. Is the print-applet back to work? Can someone confirm?

**Comment by NikoKrause** [comment] 2019-04-27 01:26
The printer applet from linux-man is included in Cinnamon 4.2 now.

**Closed by NikoKrause** 2019-04-27 01:26 UTC
