### ISSUE TITLE
A fake suspend: using chrome

### ISSUE THREAD

**Issue by iraguhaelvis** [linuxmint/Cinnamon#7950] opened 2018-10-21 18:49 UTC
### When I suspend my computer while cursor is in chrome history(on the right top corner), if the computer awake it does not ask for password as usual.

 * Cinnamon version: 3.8.8
 * Distribution - (Ubuntu 18.04)
 * 64 bit
 *Linux version 4.15.0-36-generic 

**Steps to reproduce**
Open chrome
Click three vertical dots on right top corner
Click on 'History'
Move the cursor over those history (refer to the image below)
Suspend your pc (press suspend button or close the lid)
Awake your pc (open the lid)
![issue](https://user-images.githubusercontent.com/36812634/47271582-f5b7f400-d57a-11e8-9721-0530d549933c.png)

**Expected behaviour**
At the awake, it is expected to ask for a password

**Other information**
I' ve seen this bug while I was using Parrot os, at first I thought the problem was with the OS, but when I switched to Ubuntu the same problem happened. And it only happen on Cinnamon. I think this happens on other software not only chrome.

**Comment by icarter09** [comment] 2018-10-23 01:09
Cinnamon 3.8.9
Linux Mint 19 64bit

Verified that this issue is occurring on both Chromium and Brasero. The issue seems to be related to any internal window within an app being open. On Brasero, I test it against the "Tools" window being open and did not hover the mouse over the options. Also tested this against the 'History' and 'Bookmarks' in Chromium. Issue will occur if the mouse/touchpad icon is hovered over the given active window or not. Issue seems to be related to either Cinnamon or the cinnamon-screensaver seeing the internal window of the given app as the session being active instead of inactive.

**Comment by smurphos** [comment] 2018-10-23 06:31
This is a duplicate of a longstanding non fixable bug - https://github.com/linuxmint/cinnamon-screensaver/issues/93

**Closed** 2018-10-23 06:49 UTC
