### ISSUE TITLE
GWL: toggling window visibility by clicking icon ceases to work after a time

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9046] opened 2019-12-21 23:08 UTC
```
 * Cinnamon version (cinnamon --version) 4.4.5
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). No.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used: Intel onboard; mesa
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

By design, clicking an icon in the GWL toggles the appearance of that applications window (or, if the application has more than one window, toggles the appearance of some one of those windows). However, sometimes this ceases to work. That is: one clicks one of the icons - say, the Firefox icon (and I have that icon pinned) and up comes Firefox; one clicks again, and Firefox is hidden; one clicks a third time and . . nothing happens. And the same for the fourth time. I have had the problem with Nemo too (and I have Nemo pinned as well). In my limited testing I find that restarting Cinnamon solves the problem.

**Steps to reproduce**

Please see above. I could supply a video or gifff, if that would be helpful. The more specific circumstantial causes I am unsure about.

**Expected behaviour**

I expect the toggling to go on indefinitely.

**Other information**

I could try to reproduce the issue with a non-pinned item, if that would be helpful. (Having restarted Cinnamon recently, the problem is not occuring, for any icons, right now.)

The PC at issue:

OS: Linux Mint 19.3 Tricia x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.3.18-050318-generic 
Uptime: 1 day, 6 hours, 57 mins 
Packages: 3186 (dpkg), 14 (flatpak), 4 (snap) 
Shell: bash 4.4.20 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 4.4.5 
WM: Mutter (Muffin) 
WM Theme: N_Cinn (N_Cinn) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-8550U (8) @ 1.800GHz 
GPU: Intel UHD Graphics 620 
Memory: 2808MiB / 15907MiB 
Disk (/dev/nvme0n1p4): 20G / 40G (52%) 
Disk (/dev/nvme0n1p2): 151G / 405G (40%) 
Disk (udev): 0 / 7.8G (0%)

**Comment by icarter09** [comment] 2020-09-26 15:35
Cinnamon 4.6.7
Mint 20 64bit

I'm not able to reproduce this issue. @LinuxOnTheDesktop are you still experiencing this problem? If so, could you provide a video and/or your gwl settings file (`~/.cinnamon/configs/grouped-window-list@cinnamon.org/*.json`).  Thanks.

**Comment by LinuxOnTheDesktop** [comment] 2020-09-26 16:30
Thanks, but I gave up on GWL a long time ago, in favour of [Plank](https://launchpad.net/plank). I am afraid that, at this stage, I am unwilling to spend more time on GWL.

**Comment by icarter09** [comment] 2020-09-26 17:42
No worries and thanks for the update. I'm going to close this ticket.

**Closed by icarter09** 2020-09-26 17:42 UTC
