### ISSUE TITLE
Thunderbird not maximized

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/Cinnamon#657] opened 2012-04-28 16:43 UTC
I need to maximize Thunderbird always.
It seems the window state of Thunderbird will not be saved correctly...

**Comment by dalcde** [comment] 2015-05-02 07:54
Can you explain your issue more clearly? Do you want it to be maximized by default every time it opens? Or is it incapable of being maximized?

**Comment by dtrunk90** [comment] 2015-05-03 12:20
Steps to reproduce: Open Thunderbird (not maximized), Maximize it, Close and Open again (not maximized). The issue is: When closing a window maximized, it should save that state and reopen with the same characteristics (position, size, whether maximized or not, ...) again.

**Comment by dralley** [comment] 2016-07-06 02:03
I can no longer reproduce this on Mint 18 w/ Cinnamon 3.0

@dtrunk90 can you confirm?

**Comment by Vahan86** [comment] 2016-08-31 21:39
@JosephMcc, I have also tried to reproduce this,  but it seems the issue is fixed in current Cinnamon version.

**Comment by JosephMcc** [comment] 2016-09-01 18:03
Seems to work here as well.

**Closed by JosephMcc** 2016-09-01 18:03 UTC

**Comment by CottonEaster** [comment] 2018-10-17 00:56
This has just started happening to me, since the update to Thunderbird 60. The problem is as follows.

By design, or at least on previous and welcome behaviour,

(1) if Thunderbird was maximised when it was closed
then,
(2) when it was re-opened (in any fashion, except perhaps in safe mode) it would be maximised;

and now that no longer happens, i.e. 1 no longer causes 2.

**Comment by leigh123linux** [comment] 2018-10-17 03:10
Start a new issue instead of a worthless me too.
