### ISSUE TITLE
Lingering thumbnail previews in the taskbar

### ISSUE THREAD

**Issue by ParaDice13** [linuxmint/cinnamon#9087] opened 2020-01-03 09:57 UTC
```
  * Cinnamon version: Cinnamon 4.4.6 (no daily builds)
  * Distribution - Mint 19.3 Cinnamon x64
  * Graphics: Intel HD Graphics 620 w/ Mesa DRI Intel HD Graphics 620 (Kaby Lake GT2) 
  * .xsession-errors: Is attached (see "Other information" at the bottom of this posting)
 ```

**Issue**
Cinnamon shows persistent thumbnail previews of applications in the taskbar, even for applications that have already been closed. They linger above the taskbar and do not allow for any interaction. Restarting Cinnamon (e.g. via Alt + F2 + "r" command) will remove them.

![Bildschirmfoto vom 2019-12-30 11-22-25](https://user-images.githubusercontent.com/52176040/71717375-2e5a8b00-2e18-11ea-8b45-a9fb018f168b.png)

**Steps to reproduce**
None, I'm afraid. The problem seems to occur randomly over time. From what I remember, I didn't even hover the pointer over these applications, so they shouldn't show any thumbnail.
The issue seems not to be linked to any specific application (I've had it with Nemo, Tor Browser, LibreOffice, ...).
It occurs on two different machines: One was upgraded from Mint 19.2 (no issues previously), the other one got a fresh install of Mint 19.3. Since the error occurs on both, it's safe to assume that the in-place upgrade is not the cause of the issue. It must be a bug introduced with the new version of Cinnamon that comes with Mint 19.3.

**Expected behaviour**
There shouldn't be any such tumbnail previews, only on mouseover.

**Other information**

inxi -Fxz output
```
System:    Host: MH-NOTE Kernel: 5.0.0-37-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 Desktop: Cinnamon 4.4.6 
           Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:   Type: Laptop System: LENOVO product: 20H2S00500 v: ThinkPad E470 serial: <filter> 
           Mobo: LENOVO model: 20H2S00500 serial: <filter> UEFI [Legacy]: LENOVO v: R0DET87W (1.87 ) date: 09/18/2017 
Battery:   ID-1: BAT0 charge: 37.2 Wh condition: 43.7/45.3 Wh (97%) model: SMP 01AV413 status: Discharging 
CPU:       Topology: Dual Core model: Intel Core i3-7100U bits: 64 type: MT MCP arch: Kaby Lake rev: 9 L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19200 
           Speed: 1200 MHz min/max: 400/1200 MHz Core speeds (MHz): 1: 1200 2: 1200 3: 1200 4: 1200 
Graphics:  Device-1: Intel HD Graphics 620 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa tty: N/A 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 620 (Kaby Lake GT2) v: 4.5 Mesa 19.0.8 direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Lenovo driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           Sound Server: ALSA v: k5.0.0-37-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Lenovo driver: r8169 v: kernel port: d000 
           bus ID: 04:00.0 
           IF: enp4s0 state: down mac: <filter> 
           Device-2: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter vendor: Lenovo driver: ath10k_pci v: kernel 
           port: d000 bus ID: 05:00.0 
           IF: wlp5s0 state: up mac: <filter> 
           Device-3: Atheros type: USB driver: btusb bus ID: 1-6:3 
Drives:    Local Storage: total: 465.76 GiB used: 325.98 GiB (70.0%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 850 EVO 500GB size: 465.76 GiB 
Partition: ID-1: / size: 136.50 GiB used: 18.30 GiB (13.4%) fs: ext4 dev: /dev/sda5 
           ID-2: /home size: 320.59 GiB used: 302.61 GiB (94.4%) fs: ext4 dev: /dev/dm-0 
Sensors:   System Temperatures: cpu: 39.0 C mobo: N/A 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 245 Uptime: 3h 26m Memory: 7.26 GiB used: 1.98 GiB (27.3%) Init: systemd runlevel: 5 Compilers: 
           gcc: 7.4.0 Shell: bash v: 4.4.20 inxi: 3.0.32 
```

.xsession-errors
I've shortened the log file to the exact time when one such thumbnail error occurred. The error contained in the log below is likely related to the issue.

```
(caribou:1695): GLib-GObject-CRITICAL **: 20:59:39.001: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Cjs-Message: 20:59:39.041: JS LOG: metaWindow has no actor!

(cinnamon:1681): Cjs-WARNING **: 20:59:39.057: JS ERROR: TypeError: this.windowActor is null
_destroy@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:234:13
TooltipBase.prototype.destroy@/usr/share/cinnamon/js/ui/tooltips.js:162:9
destroy@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:523:9
onUnmanaged@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:367:9

(caribou:1695): GLib-GObject-CRITICAL **: 20:59:39.503: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(caribou:1695): GLib-GObject-CRITICAL **: 20:59:39.504: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(caribou:1695): GLib-GObject-CRITICAL **: 20:59:39.504: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by mtwebster** [comment] 2020-01-03 19:39
This is a duplicate of #9051

**Closed by mtwebster** 2020-01-03 19:39 UTC
