### ISSUE TITLE
Problem with super+W as the short cut for "show the window selection screen"

### ISSUE THREAD

**Issue by xyh-cosmo** [linuxmint/cinnamon#8918] opened 2019-10-25 14:10 UTC
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
In the previous version, pressing "Super+W" will successfully make the window selection screen show up and stay there, until pressing "Super+W" will selection screen disappear. However, in version 4.0.10, the screen would not stay unless you keep "super+w" being pressed, releasing your figures from "super+W" would immediately cause disappearence of the selection screen.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment] 2019-11-03 02:57
@xyh-cosmo could you provide the steps to reproduce this issue? Thanks.

**Comment by xyh-cosmo** [comment] 2019-11-03 06:29
@icarter09 
Ubuntu version: 19.10
cinnamon version: 4.0.10

Steps:
1) open the system settings
2) open the keyboard settings and switch to "shortcuts"
3) add new shortcut, i.e., "Super+w", under "General/Show the window selection screen"

After pressing "Super+w", the selection screen shows up successfully, but it disappears immediately after releasing the pressing

**Comment by icarter09** [comment] 2019-11-03 16:05
Linux Mint 19.2
Cinnamon 4.2.4

I think this issue is related to your Ubuntu version. I set `Super + w` to the shortcut, verified it was still there after several open/closing of the window, and the new shortcut also works as intended. I haven't tested it after a reboot, but it looks like the issue is occurring well before then for you.

**Closed** 2019-11-24 20:29 UTC
Labels: BUG
