### ISSUE TITLE
cinnamon-settings doesnt open

### ISSUE THREAD

**Issue by AdriBloober** [linuxmint/cinnamon#8715] opened 2019-07-12 19:26 UTC
```
 * Cinnamon version: 4.0.10
 * Distribution - (Mint latest)
 * Graphics AMD iGPU Radeon Vega 11
 * 64 bin
 ```

**Issue**

When i open cinnamon-settings, it caused this error:
```
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 619, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 247, in __init__
    for module in modules:
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py", line 5, in <module>
    import imtools
  File "/usr/share/cinnamon/cinnamon-settings/bin/imtools.py", line 623, in <module>
    if Image.VERSION == '1.1.7':
AttributeError: module 'PIL.Image' has no attribute 'VERSION'
```

- AdriBloober

**Comment by leigh123linux** [comment] 2019-07-13 05:15
Duplicate of #8495

**Closed by leigh123linux** 2019-07-13 05:15 UTC
