### ISSUE TITLE
Cannot switch from Chinese to English input when entering login password after screen wakeup

### ISSUE THREAD

**Issue by Benjen** [linuxmint/Cinnamon#3803] opened 2015-01-06 12:06 UTC
1) Linux Mint 17.1 Cinnamon 64bit edition
2) Had switched to Chinese Pinyin input method using ibus.  Left the computer.  When I came back the computer screen had switched off.  When I moved the mouse the screen turns on and I am presented with a login screen asking me to enter my password. 
3) [bug] I am not able to switch to the English input method and thus am unable to enter my password, since my password is in english.  The switch input hot-key [ctrl + space] doesn't work so I am not able to switch input methods.
4) I would expect to be able to at least use the switch input hot-key combination [ctrl + space] to switch between input methods when enter password.
5) This is the first time I have encountered the issue as I do not frequently use Chinese input method.

**Comment by anandrkris** [comment] 2015-01-16 07:21
https://github.com/linuxmint/Cinnamon/issues/3483 > Same issue, i suppose.

**Comment by anandrkris** [comment] 2015-01-16 07:24
@mtwebster  To be file under https://github.com/linuxmint/cinnamon-screensaver/issues ?

**Comment by mxa** [comment] 2015-04-21 06:48
Actually this is not an issue confined to cinnamon, the same problem exists with MATE. If I have the IBUS iput set to Korean, leave my desk and come back I am essentially locked out since my login password consists of alphanumericals and i can only type Korean, being unable to switch (Ctl.+Space in my case) to another input method. The workaround is to select "Change User" then you can select the same user again and switch the input method. It's impossible to do this in the Cinnamon or MATE lock screens. I think that is a nasty bug for anyone who uses Mint with a different input method. It took me a while to discover the workaround, before that I used to do a hardware reset.

**Comment by mtwebster** [comment] 2015-04-21 14:12
There should be an indicator just to the right of the password field to change input language - is this not what you're after?  It's not obviously a button - it shows an abbreviation of the current language.

**Comment by mxa** [comment] 2015-04-21 18:57
Oh, I see this in MATE now, but in Cinnamon there is no such thing. Strange.

**Comment by dalcde** [comment] 2015-05-06 21:21
Duplicate of #3048

**Closed by dalcde** 2015-05-06 21:21 UTC
