### ISSUE TITLE
GParted icons are unhappy with the new Cinnamon themes, dark or light

### ISSUE THREAD

**Issue by ineuw** [linuxmint/cinnamon#11461] opened 2023-01-31 15:29 UTC
```
 * Cinnamon version 5.6.7
 * Distribution - Mint 21.1
[gparted_display.tar.gz](https://github.com/linuxmint/cinnamon/files/10548022/gparted_display.tar.gz)

 * Graphics hardware Intel, on board
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

### Issue
Light theme icons on light background
Dark theme icons on dark icons are not visible

**Comment by fredcw** [comment] 2023-02-03 18:22
Some of the icons in the gparted toolbar are intentionally "grayed out" when they're insensitive (can't be clicked on). Is this what you mean? If not, can you provide a screenshot.

**Comment by ineuw** [comment] 2023-02-03 18:40
Attached are the images of Settings and their results in gParted, 
[gparted_display.tar.gz](https://github.com/linuxmint/cinnamon/files/10581781/gparted_display.tar.gz)

**Comment by JosephMcc** [comment] 2023-02-03 18:42
@ineuw it's a lot easier to see your images if you don't compress them. You can just display them in your issue.

**Comment by ineuw** [comment] 2023-02-03 18:58
My apologies, 

![230130_legacy_light_theme](https://user-images.githubusercontent.com/10367016/216684491-968936d9-8b18-490c-94c9-7e67dfba60eb.jpg)
![gparted_legacy_light_theme](https://user-images.githubusercontent.com/10367016/216684499-b29c347c-9184-4034-abe8-56e682c91648.jpg)

**Comment by JosephMcc** [comment] 2023-02-03 19:21
Ok, a couple things here I notice in your screenshots. First, the screenshot of gparted is most definitely not using the Mint-Y-Legacy applications theme. It's using the new Mint-Y-Blue.  That being said, as someone noted above, the icons will be lighter depending on what is selected in the lower half of the window because they are inactive. I just tested and they aren't as light on mine as they seem to be on yours with any Mint themes.

Outside of that, this definitely isn't an issue with Cinnamon but with your theme and I can't reproduce it.

**Comment by ineuw** [comment] 2023-02-03 19:30
You are right, my apologies for wasting your time. I need more time to study this sudden introduction of varieties and their interrelationships.

**Comment by JosephMcc** [comment] 2023-02-03 19:33
Ok, I'm going to go ahead and close this since down to either the app or the theme and not Cinnamon.

**Closed by JosephMcc** 2023-02-03 19:33 UTC
Labels: New
