### ISSUE TITLE
Applications search is not so good as it used to be in mint 18

### ISSUE THREAD

**Issue by fermmm** [linuxmint/Cinnamon#8371] opened 2019-02-07 02:04 UTC
**Issue**
Something changed in mint 19 and the searching of applications is not so good anymore.
In the following screenshot spotify should appear first as is the only thing that make sense with "spo" and it's the only thing I open when I write that letters. I need to write "spot" to make spotify appear first.
In mint 18 this was better.

![captura de pantalla de 2019-02-06 21-54-26](https://user-images.githubusercontent.com/3660373/52386144-7a177f80-2a63-11e9-9da8-ab7b093bc5e6.png)

**Comment by LingMan** [comment] 2019-03-01 02:19
This is a duplicate of https://github.com/linuxmint/Cinnamon/issues/8070. See https://github.com/linuxmint/Cinnamon/pull/8251 for an attempted fix.

**Closed** 2019-03-05 05:53 UTC
