### ISSUE TITLE
Categories in menu flickering when hovering over applications

### ISSUE THREAD

**Issue by gwillgues** [linuxmint/cinnamon#10666] opened 2022-02-11 14:02 UTC
Cinnamon 5.2.7
OS: Debian Unstable

**Issue**
Graphical glitches in menu when hovering over applications, the category names will flicker if the name is over a certain length.

 I have added a video displaying the behavior.

 I have also observed this behavior on Linux Mint 20.2 (with whatever version cinnamon has from the repos that is most up to date) after changing the size of menu items.

**Steps to reproduce**
Open menu, hover mouse over applications. Increasing the size of the categories in the menu increases the frequency. 

**Expected behaviour**
Menu should not have any graphical anomalies

https://user-images.githubusercontent.com/96144967/153605083-5ed2c0e5-cb09-431e-8d30-52407e0e77b4.mp4

**Comment by smurphos** [comment] 2022-02-12 12:59
Duplicate of #10212

**Comment by IvoAndonov** [comment] 2022-02-28 09:00
+1, I have it too, altough in my case it's barely seen bc I'm using a semi-transparent theme which makes the flickering hard to see, if you're not looking for it.

**Closed** 2022-08-26 14:56 UTC
