### ISSUE TITLE
Entries under the settings applet

### ISSUE THREAD

**Issue by abn-volk** [linuxmint/Cinnamon#2615] opened 2013-11-09 17:43 UTC
1. Because Cinnamon Menu settings are now in "Applets", its entry under the Cinnamon settings applet should be removed, or changed so that it points to the new location.
2. Also, when you right-click the panel, there are duplicate entries of Panel and Applets. They should be removed, too; and the right-click menu should be the same as the settings applet.

**Comment by Vahan86** [comment] 2016-09-17 11:16
Cinnamon Settings applet is disabled by default in Cinnamon 3.0, so the issue is no longer relevant.

@JosephMcc, can we close the issue?

**Closed** 2016-09-17 13:26 UTC
