### ISSUE TITLE
Menu screen-cutoff bug (Cinnamon Unstable)

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5578] opened 2016-08-20 16:35 UTC
<s>The Box Pointer Cinnamon theme feature looks inconsistent on vertical panels to what it looks like on normal ones, e.g: Popup-menu on bottom:
![screenshot from 2016-08-20 16-31-57](https://cloud.githubusercontent.com/assets/11057934/17832491/c5a3cdcc-66f3-11e6-940c-38bd09dd2fdc.png)
...and then on the right-panel: 
![screenshot from 2016-08-20 16-32-16](https://cloud.githubusercontent.com/assets/11057934/17832498/e503505c-66f3-11e6-8a35-9bf3a8c9032f.png)</s>

And then, if you put the popup-menu far down enough on both left and right panels, and then open a sub-menu, this happens:
![screenshot from 2016-08-20 16-35-08](https://cloud.githubusercontent.com/assets/11057934/17832506/19db511c-66f4-11e6-9100-bc07ebabee91.png)

**Comment by feren** [comment] 2016-08-20 16:37
Just to add, here's my Cinnamon version, oh, and I'm using the Cinnamon Unstable PPA here:
![screenshot from 2016-08-20 16-37-01](https://cloud.githubusercontent.com/assets/11057934/17832522/54cc382c-66f4-11e6-9a49-d0907140a731.png)

**Comment by JosephMcc** [comment] 2016-08-20 16:52
The boxpointer used by Cinnamon menus is something we plan to take a look at. In fact we kind of want to ditch them and redesign this a bit.

**Comment by brownsr** [comment] 2016-08-21 16:35
I can't reproduce this problem using the development mint-y theme.  That's not to say I haven't seen it before, I got this to happen many times during development, and thought I had made changes to eliminate it.  Could you please clarify which theme you are using ?  The vertical panels code introduces new css, so if you don't have the development version of the themes then you may see odd things happen.  At the moment you will want one of the mint supplied themes - mint-x, cinnamon, linux mint, or mint-y, and the versions straight out of git at that - as only these are going to have been adapted for the new code at the moment.

**Comment by JosephMcc** [comment] 2016-08-21 17:19
This happens for me regardless of theme. The panel context menu is placed when you right click on the panel and then expanding the submenus can push it partly off screen.

**Comment by feren** [comment] 2016-08-21 17:31
@brownsr I am using the Inspire GTK Theme's Cinnamon portion of the theme, you can find it by searching 'feren GTK' on either GNOME Look or DeviantArt, your choice, but still...

**Comment by JosephMcc** [comment] 2016-08-21 17:36
When testing something like the vertical panels in Cinnamon which are brand new you should check for the same issue using the default built in theme. You can't expect 3rd party themes to have adjusted to these features  already, if they ever choose to at all.

**Comment by feren** [comment] 2016-08-21 17:38
Hmm, the cinnamon theme seems to have it fixed, will copy a bit of cinnamon's code into feren GTK and will close this, though, thanks for the help anyway, much appreciated...

**Comment by JosephMcc** [comment] 2016-08-21 17:53
As I already said the theme used makes no difference in the problem of the menu expanding off screen.

**Comment by feren** [comment] 2016-08-21 18:20
Oh yeah, just remembered about that bug, will probably rename the title to put the emphasis on the cut-off bug...

**Comment by JosephMcc** [comment] 2016-11-08 04:07
This problem should now be fixed with the revamped menus.

**Closed by JosephMcc** 2016-11-08 04:07 UTC
Labels: BUG REPRODUCED
