### ISSUE TITLE
Cinnamon menu search should prioritise exact name matches over description matches instead of being straight alphabetical

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/Cinnamon#2360] opened 2013-09-01 10:29 UTC
When searching in the cinnamon menu I'm always getting frustrated at the way I type in the name of something I'm looking for only for it to appear way down the bottom of the list.  I think the search system needs to be modified so any program name that has a match of the search criteria anywhere in the title should be presented above any other program with the search criteria in just the description.
Further more any programs that are an exact match of the search description ( so any program name beginning with the search criteria ) should always be displayed first.

At the moment the search function just displays all programs containing the search criteria  in either the name or description and just lists them alphabetically. I think a good idea would be to have a setting in the menu section of cinnamon settings to enable or disable "Alphabetical search results" or "Smart searching" or some such description

Here are a few classic examples when looking for "System Settings" that regularly annoy me.
![screenshot from 2013-09-01 11 23 35](https://f.cloud.github.com/assets/1920963/1063824/531d6636-12f1-11e3-880f-b04742054b2a.png)
![screenshot from 2013-09-01 11 19 43](https://f.cloud.github.com/assets/1920963/1063826/5b2d0dc2-12f1-11e3-9133-26e7fb502c82.png)

**Comment by dalcde** [comment] 2015-05-23 19:07
Closing as duplicate of #1220

**Closed by dalcde** 2015-05-23 19:07 UTC

**Comment by moinmoti** [comment] 2019-05-21 12:16
This issue is still there and opened at #4053
