### ISSUE TITLE
calendar@cinnamon.org calendar week numbers suffer from one-off

### ISSUE THREAD

**Issue by stefan123t** [linuxmint/Cinnamon#4031] opened 2015-04-09 16:18 UTC
As suggested also by other users in #3947 the problem with weeks 13/43 in 2015 still exists.
As the issue just is not fixed yet and I do not know how to reopen a closed issue I am opening a new one here.

I replaced the following line in calendar.js which resolves the problem for me.

/usr/share/cinnamon/applets/calendar@cinnamon.org/calendar.js
<pre>
@@ -393,1 +393,1
@@ Calendar.prototype = {
-            if (this.show_week_numbers && iter.getDay() == 4) {
+           if (this.show_week_numbers && ((7 + iter.getDay() - this._weekStart) % 7) == 0) {
</pre>

Kind regards,
Stefan

**Comment by cptmintalicious** [comment] 2015-04-09 16:30
Hi Stefan,

I can confirm that this just works for me, too. Thanks.
Hopefully, that will be applied into the master branch.

Regards,
Erik

**Comment by mtwebster** [comment] 2015-04-09 22:14
Hi, I'm not seeing this with the new release, can you pastebin the contents of `calendar.js`?

In Mint 17.1, simply do:

`cat /usr/share/cinnamon/applets/calendar@cinnamon.org/calendar.js  | pastebin`

and post the resulting link here.

Thanks

**Comment by cptmintalicious** [comment] 2015-04-10 05:41
Hi mtwebster,

Stefan has posted this workaround/fix just 13h ago. I've updated my calendar.js on my own and so you should do, too. Simply change line 393 in the file as mentioned above, reboot or restart cinnamon (mdm) and it will work.

Regards,
Erik

**Comment by mtwebster** [comment] 2015-04-10 11:27
I'm one of the developers - I meant I can't reproduce the original issue.  It should be fixed in the latest release, and I want to be certain you're running that before moving further.

**Comment by cptmintalicious** [comment] 2015-04-10 18:41
Sorry, my fault. You can find the contents of my (already changed) calendar.js here: http://paste.linuxmint.com/view/kr6j

**Comment by mtwebster** [comment] 2015-04-10 19:30
That file is identical to the one in the latest Cinnamon update (2.4.7/2.4.8) - it does *not* have the line change detailed above - perhaps you hadn't updated yet at the time..  If you're no longer experiencing the issue I am going to close this.

**Comment by cptmintalicious** [comment] 2015-04-10 19:46
You're right. There was a cinnamon update today which seems to have fixed the issue. The calendar.js must have been overwritten by the update. Last change date of it is now 9 April 17:12 and that's definitively later then when I was editing it.
I'm not seeing the double 13/missing 43 now anymore.

**Comment by mtwebster** [comment] 2015-04-10 19:53
Ah good news then :)

Thanks

**Closed by mtwebster** 2015-04-10 19:53 UTC

**Comment by stefan123t** [comment] 2015-04-12 08:09
Hi Michael,
find below the pastebin you requested. Please note that I already changed line 393 because it did not work for me before.
http://paste.linuxmint.com/view/nwkl
Kind regards,
Stefan

**Comment by stefan123t** [comment] 2015-04-12 08:16
But for your reference I have reverted back to the old line and the new line suggested by myself. Restarting Cinnamon did not show the erratic behaviour neither with old nor new line.
Kind regards,
Stefan
