### ISSUE TITLE
Resizing maximized windows using Alt+right-click crashes Cinnamon 3.0.1

### ISSUE THREAD

**Issue by jraimundo** [linuxmint/Cinnamon#5245] opened 2016-04-26 21:47 UTC
If I try to resize a maximized window using Alt+right-click Cinnamon crashes.
It works if the windows is not maximized.

I'm using Arch Linux.

**Comment by Cobinja** [comment] 2016-04-27 13:28
Duplicate of #5182, linuxmint/muffin#226

**Closed** 2016-04-27 19:15 UTC
