### ISSUE TITLE
Cinnamon 3.2.8 applets not working since last update

### ISSUE THREAD

**Issue by luke8800gts** [linuxmint/Cinnamon#6513] opened 2017-05-06 08:50 UTC
Hello,

since the last update and following restart, Cinnamon tells me it has problems to load third party applets in the system tray (in the sense that standard cinnamon applets are still working). Looking glass tells me for all failing applets a similar error:
```
 redeclaration of let bookmarks
 [Applet "placesCenter@scollins"]: Error importing applet.js from placesCenter@scollins
 Could not load applet placesCenter@scollins
```
```
 redeclaration of let array_lines
 [Applet "text-to-speech-applet@cardsurf"]: Error importing applet.js from text-to-speech-applet@cardsurf
 Could not load applet text-to-speech-applet@cardsurf

```
So first of all I tried to update the applets, but it tells me: [Errno 2] No such file or directory
This it tells me for all applets with update.
Furthermore I get the same error when I wanna install a new applet.

Do you have any suggestions?

**Comment by leigh123linux** [comment] 2017-05-06 09:31
capture@rjanja is a dead applet, please remove it then repost any new errors

**Comment by luke8800gts** [comment] 2017-05-06 10:02
I hope placesCenter@scollins and text-to-speech-applet@cardsurf are not dead too.

**Comment by collinss** [comment] 2017-05-06 14:35
The reason you are seeing this is that Cinnamon 3.4 switched to a new js engine that is more particular about the code it allows. Most of the problematic applets have been fixed now or will be soon, but you will need to update them in applet settings. Places center has for sure, though I'm not sure about the others.

**Comment by luke8800gts** [comment] 2017-05-06 14:42
I tried to update over the settings, but then I get that 2nd error I mentioned:
[Errno 2] No such file or directory

**Comment by collinss** [comment] 2017-05-06 14:42
I just merged a fix for the text to speech applet. It may take a few minutes for the changes to take effect on the site.

**Comment by collinss** [comment] 2017-05-06 14:43
Did you click "refresh list"? Sometimes it causes issues if you haven't updated the cache.

**Comment by luke8800gts** [comment] 2017-05-06 14:49
Yes, I tried that several times. It is says 7 applets need an update. Then I click the button to update and I get the mentioned error.
I tried also to install a new applet that for sure was 3.4 ready. Same problem.

**Comment by collinss** [comment] 2017-05-06 14:57
Does it give you any errors when you run it from terminal? (```cinnamon-settings applets```)

**Comment by luke8800gts** [comment] 2017-05-06 15:32
It says:
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`
But thats all.
By the way it gives the error for applets it wants to update. So 7 dialogs with Errno 2 and 7 times Gtk-Messages in the terminal.

**Comment by luke8800gts** [comment] 2017-05-08 10:54
Some one has a suggestion?

**Comment by collinss** [comment] 2017-05-08 11:44
The warning has nothing to do with your problem. It just happens to show up when you get that dialog, but it is harmless. I have no clue what the issue is at this point, either. It could very well be completely unrelated, such as an internet connection/proxy/cache issue. If that is the case it's likely outside of my area of expertise.

**Comment by collinss** [comment] 2017-05-08 11:49
It's also possible to install applets and desklets manually. You just go to the spices site and download the ones you want. Then unpack the zip files into ~/.local/share/cinnamon/applets (if it's an applet - desklets and extensions each have a similar subfolder, just change applet to desklet or extension in the path)

**Comment by luke8800gts** [comment] 2017-05-10 07:49
Thank you, this will fix it for me for a while. Hope somebody finds a solution, so that it is again possible to update over settings.

**Closed** 2018-02-02 22:53 UTC
