### ISSUE TITLE
Super-long Lag on Cinnamon Startup after upgrading to 6.4.0

### ISSUE THREAD

**Issue by username227** [linuxmint/cinnamon#12530] opened 2024-11-29 01:31 UTC
### Distribution

Arch

### Package version

6.4.0

### Graphics hardware in use

GeForce GTX 1650 & integrated AMD Radeon

### Frequency

Always

### Bug description

This is a proper bug report for the issue that I mentioned towards the end of #12522 . After the upgrade to 6.4.0, (and after all of the Cinnamon components were upgraded), the system takes about a minute or so to load after signing in. The mouse is able to move, but there is no window pop-ups at all. There are no error messages or applet error messages. 

Additionally, when I close the lid, and reopen it again, the there is an additional lag. The mouse is able to move, but all windows are frozen for about a minute, after which it unfreezes. The .xsession-errors file prints error output for this second error (see below in additional info). The first error probably has an error message somewhere there as well but it's much harder to determine that one.

I believe it likely that these two issues are probably the same or closely related.

### Steps to reproduce

Updated Cinnamon to 6.4.0
Restart, or log out and back in again, or restart cinnamon.

### Expected behavior

There shouldn't be a long lag when signing in, similar to what there was before the upgrade.

### Additional information

Error info from .xsession-errors for the lid close problem:

(csd-power:1277): CinnamonDesktop-WARNING **: 20:17:09.186: Error setting property 'PowerSaveMode' on interface org.cinnamon.Muffin.DisplayConfig: Timeout was reached (g-io-error-quark, 24)

Note also: there's a bug report opened last week, #12517 which sounds vaguely similar to this problem. However, it seems that this happens to him only when suspending, and this is happening to me on every startup. Additionally, this issue references 6.4.0, while that report references 6.2.9. Therefore, I believe it's probably a different issue.

**Comment by RandCircle** [comment] 2024-11-30 11:04
Same

**Comment by leigh123linux** [comment] 2024-11-30 11:08
It works fine here on fedora, maybe you should file the issue at the archlinux bug tracker instead.

**Comment by archiebug** [comment] 2024-12-01 02:39
Same here- seems to be a 5-10 second delay after login.  Wasn't present in 6.2.

**Comment by username227** [comment] 2024-12-01 03:25
> It works fine here on fedora, maybe you should file the issue at the archlinux bug tracker instead.

Believe me, considering how messed up the Arch roll-out of 6.4 was last week, this was my first thought. I actually sat on this error for a day or so before I filed the report, until I was about 90% convinced that it wasn't an "arch" problem. And, we're getting a specific error message, that I mentioned above, at least for the issue of when I close and reopen the lid.

**Comment by archiebug** [comment] 2024-12-01 03:48
I've combed through my logs and do not see anything that stands out.

**Comment by archiebug** [comment] 2024-12-01 03:59
ok- did some other poking around...since it is start-up related, I checked out

`systemd-analyze blame`

The top offender was the reflector.service - over 35 seconds...a good amount of hosts are timing out.

I disabled the service and restarted.  I was able to instantly log in.  I enabled the service again and restarted, and I got the delayed log in.  Did another disable / reboot and I'm able to instantly log in again.

Maybe check to see if there is a service hanging up the startup of Cinnamon?

**Comment by username227** [comment] 2024-12-01 04:31
I just downgraded to 6.2.9 in order to compare the xsession-errors files to see what's different. The biggest different seems to be that the following error appears towards the beginning of the startup process only on 6.4. I can't say for sure this is what the issue is, but it seems a likely bet considering the nature of the message:
```

(csd-keyboard:1293): Gdk-WARNING **: 04:03:50.769: The program 'csd-keyboard' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 477 error_code 3 request_code 18 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by username227** [comment] 2024-12-01 04:34
> ok- did some other poking around...since it is start-up related, I checked out
> 
> `systemd-analyze blame`
> 
> The top offender was the reflector.service - over 35 seconds...a good amount of hosts are timing out. _(side note: I realized that I should have the service disabled where I rely on the timer)._
> 
> I disabled the service and restarted. I was able to instantly log in. I enabled the service again and restarted, and I got the delayed log in. Did another disable / reboot and I'm able to instantly log in again.
> 
> Maybe check to see if there is a service hanging up the startup of Cinnamon?

Thanks for the suggestion. reflector is taking less than 2 seconds. Although the system hangs after login for up to 60 seconds, nothing is standing out there. The biggest offender is NetworkManager, which is still less than 6 seconds.

**Comment by JosephMcc** [comment] 2024-12-01 14:25
Just to add a bit more info, I don't experience this issue on Mint either. I've haven't seen any of the other MInt devs mention it being an issue.

**Comment by username227** [comment] 2024-12-01 16:01
Or it could be these critical errors, not sure:

```
(cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: cannot register existing type 'MetaDBusDisplayConfig'

(cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(cinnamon:1420): GLib-CRITICAL **: 05:02:40.403: g_once_init_leave_pointer: assertion 'result != 0' failed

(cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed

(cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: g_object_class_override_property: Can't find property to override for 'MetaDBusDisplayConfigProxy::power-save-mode'
```

**Comment by sobrus** [comment] 2024-12-02 08:38
Same problem here, system is Manjaro unstable branch with cachyos v3 repos added. Broken cinnamon 6.4 packages came from cachyos repo (probably just recompiled version of arch packages).

**Comment by leigh123linux** [comment] 2024-12-02 09:01
This issue is more likely to be an archlinux packaging issue, maybe they have forgotten a dependency or some other packaging issue, it would be the first time they have done something like this.

**Comment by fredcw** [comment] 2024-12-06 02:52
> Or it could be these critical errors, not sure:
> 
> ```
> (cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: cannot register existing type 'MetaDBusDisplayConfig'
> 
> (cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
> 
> (cinnamon:1420): GLib-CRITICAL **: 05:02:40.403: g_once_init_leave_pointer: assertion 'result != 0' failed
> 
> (cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed
> 
> (cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: g_object_class_override_property: Can't find property to override for 'MetaDBusDisplayConfigProxy::power-save-mode'
> ```

I'm using Manjaro unstable and also getting these errors when there's a ~20 second delay starting/restarting cinnamon. *But* it only happens when Cassia Window List or CobiWindowList applets are on the panel.

What other applets are people running?

**Comment by username227** [comment] 2024-12-06 12:39
> > Or it could be these critical errors, not sure:
> > ```
> > (cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: cannot register existing type 'MetaDBusDisplayConfig'
> > 
> > (cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
> > 
> > (cinnamon:1420): GLib-CRITICAL **: 05:02:40.403: g_once_init_leave_pointer: assertion 'result != 0' failed
> > 
> > (cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed
> > 
> > (cinnamon:1420): GLib-GObject-CRITICAL **: 05:02:40.403: g_object_class_override_property: Can't find property to override for 'MetaDBusDisplayConfigProxy::power-save-mode'
> > ```
> 
> I'm using Manjaro unstable and also getting these errors when there's a ~20 second delay starting/restarting cinnamon. _But_ these errors and delay only happen when Cassia Window List or CobiWindowList applets are on the panel. None of these other applets cause the delay: GWL, all menu applets, gpaste-reloaded, sysmonitor@orcus, weather@mockturtl, network manager, calendar, inhibit applet.
> 
> What other applets are people running?

Finally, a breakthrough! OK, so I am using the CobiWindowList applet on my main panel. I have set it to show only open apps. I have a side panel with a different applet where I pin most-used apps. When I disabled the CobiWindowList applet, the desktop started normally. Therefore, the problem is that this is being caused by this applet.
I suppose that means we need to open up a  different bug report on the other repo? @fredcw do you want to do this since you found the bug?

Does anybody have a non-broken similarly-functioning applet that I could use in the meantime to show running programs on the panel?

**Comment by username227** [comment] 2024-12-06 13:03
To answer my own question and expand a little, if your problem is cased by CobiWindowList, remove this applet and use grouped-window-list@cinnamon.org instead.

On my end, removing the offending applet solves BOTH the startup lag AND the lag when closing and opening the lid.

**Comment by leigh123linux** [comment] 2024-12-06 13:52
@Cobinja

**Comment by leigh123linux** [comment] 2024-12-06 13:54
@klangman

**Comment by sobrus** [comment] 2024-12-06 14:30
I'm not using this applet (but I'm using many others). I don't know which one (if any) was responsible for my problems.
Right now, I can see that Arch Linux has newer "cinnamon" package in staging, and some other cinnamon packages marked as outdated already, so I guess I'll wait till the updates come and try again then.
I will report back whether this has been fixed and/or which applet misbehaves for me.

**Comment by klangman** [comment] 2024-12-06 16:06
Do you guys have Cobinja's fix for 6.4 https://github.com/linuxmint/cinnamon-spices-applets/pull/6637? I have implemented his fix in CassiaWindowList locally as well and it fixes the issues I was seeing in a Manjaro Virtualbox VM where I am testing Cinnamon 6.4.0. I was seeing Cinnamon freeze up (or at least the screen would not update) after enabling CassiaWindowList. I'll be pushing Cobinja's fix (applied to CassiaWindowList) to cinnamon-spices tonight or tomorrow, but if you guys are using CobiWindowList and have updated it to the latest version, then I would hope the issue is resolved?

**Comment by username227** [comment] 2024-12-06 16:15
> Do you guys have Cobinja's fix for 6.4 [linuxmint/cinnamon-spices-applets#6637](https://github.com/linuxmint/cinnamon-spices-applets/pull/6637)? I have implemented his fix in CassiaWindowList locally as well and it fixes the issues I was seeing in a Manjaro Virtualbox VM where I am testing Cinnamon 6.4.0. I was seeing Cinnamon freeze up (or at least the screen would not update) after enabling CassiaWindowList. I'll be pushing Cobinja's fix (applied to CassiaWindowList) to cinnamon-spices tonight or tomorrow, but if you guys are using CobiWindowList and have updated it to the latest version, then I would hope the issue is resolved?

No, apparently I didn't, and when I manually updated it, it now works again. Thanks for the heads up. Does anybody know how to get these types of cinnamon spices to automatically update on Arch?

**Comment by klangman** [comment] 2024-12-06 16:28
I use https://cinnamon-spices.linuxmint.com/applets/view/309 to make sure I know when spice updates are available. It does not automatically update the spices but at least it informs you when there are updates you can apply.

**Comment by username227** [comment] 2024-12-06 16:51
> I use https://cinnamon-spices.linuxmint.com/applets/view/309 to make sure I know when spice updates are available. It does not automatically update the spices but at least it informs you when there are updates you can apply.

Thanks. that is super helpful!

**Comment by sobrus** [comment] 2024-12-06 17:05
you can update all spices automatically by running "cinnamon-spice-updater --update-all"
I have it in cinnamon startup sequence so it updates every system start (updated spices are loaded on next restart though)

**Comment by fredcw** [comment] 2024-12-06 17:40
@klangman 
>if you guys are using CobiWindowList and have updated it to the latest version, then I would hope the issue is resolved?

Yes, updating to latest version fix it.

**Comment by username227** [comment] 2024-12-06 18:37
> I'm not using this applet (but I'm using many others). I don't know which one (if any) was responsible for my problems. Right now, I can see that Arch Linux has newer "cinnamon" package in staging, and some other cinnamon packages marked as outdated already, so I guess I'll wait till the updates come and try again then. I will report back whether this has been fixed and/or which applet misbehaves for me.
> 
> At the moment I have cinnamon, cinnamon-desktop, cinnamon-session and cinnamon-settings-daemon downgraded. The rest is 6.4 and it works OK. Also, when the desktop was broken (full 6.4 update), the notifications for volume change etc were not visible.

You're right. the cinnamon repo is at 6.4.2 already, and the Arch repositories are still at 6.4.0. According to the archlinux git repo, the Cinnamon package on Arch is on "life support" (their words) since the maintainer bowed out; someone else took it over but he's quite busy, I guess, and has other priorities as well. I have done my fair share of packagaing for the AUR, and would consider taking it over, except that I am not a true developer, and for something as complicaated as a DE, I would likely not have the skills to maintain it properly.

Regarding your other point about the newer version in the staging repository - that is most likely a cinnamon package built on the new python version 3.13, which will be released together with all of the other python packages once all of the maintainers who use python have properly updated the dependent packages. this prevents things from breaking.

**Comment by klangman** [comment] 2024-12-07 01:53
FYI.. The CobiWindowList fix for running under Cinnamon 6.4 has now been applied to CassiaWindowList as well with version 2.4.0 (just merged a few minutes ago).

**Comment by username227** [comment] 2024-12-08 02:15
Thank you all for helping with the issue. And I learned something about cinnamon too. In case anybody's interested, I preserved the default cinnamon theme from 6.2 on the AUR here: https://aur.archlinux.org/packages/cinnamon-6.2-theme.

**Closed** 2024-12-08 08:58 UTC

**Comment by fredcw** [comment] 2024-12-08 13:20
@Klangman @Cobinja Any idea why this bug causes a long delay rather than just returning an error? Because that in itself could be considered a bug.

**Comment by sobrus** [comment] 2024-12-08 13:41
In my case, the offending extension was "back-to-monitor". It saves windows placement when you turn on/off secondary display.
From what I see, the screen/display/xrandr calls have changed in 6.4 (and this extension uses alot of it to monitor display activity). 

When I try to enable this extension, it causes immediate about 50s long system freeze (apart from the mouse pointer).

**Comment by klangman** [comment] 2024-12-09 19:56
> Any idea why this bug causes a long delay rather than just returning an error? Because that in itself could be considered a bug.

I didn't really look in to it deeply. I knew that the CibiWindowList fix existed before I even had a Cinnamon 6.4 environment to test with, so I was expecting the issue to exist in CassiaWindowList as well. When I saw the issue I applied the fix and it worked, so I left it at that.

@sobrus Maybe an issue should be opened against "back-to-monitor" so that the author has a chance to fix it before Mint22.1 is available and lot of people will start using Cinnamon 6.4.

**Comment by sobrus** [comment] 2024-12-09 20:30
@klangman I will open an issue if this extension fails to load with updated cinnamon packages (probably tomorrow)

@archiebug I need to wait till the updates are available in cachyos v3 repo (some packages are there already, but not all of them).
After disabling back-to-monitor, everything seems to be OK. As it turned out, the problem with notifications and modals was caused by used desktop theme (adapta-nokto-maia) which probably needs to be.. adapted for 6.4 ;). But I switched to official theme, which is very nice now, just tweaked it a bit (colors and fonts).

**Comment by username227** [comment] 2024-12-10 12:48
> It looks like that 9 cinnamon DE packages have been updated on the arch repos. Have ya given them a spin yet?
> 
> https://archlinux.org/packages/?sort=&q=cinnamon&maintainer=&flagged=
I had been playing with the packages locally, and had successfully upgraded to 6.4.2 several days prior. I believe now the packages have caught up with me. They should be working fine, as upgrading the pkgbuilds is a simple matter (but all the related parts need to be upgraded at the same time or it causes issues).
