### ISSUE TITLE
Thumbnails in windows list applet doesn't update title

### ISSUE THREAD

**Issue by donlencho** [linuxmint/Cinnamon#4944] opened 2015-12-17 11:02 UTC
If you open an application it shows correctly in the windows list but if within the application the name of the window changes (for instance if you open your home folder in Nemo then browse to another folder, says Downloads) then name in the thumbnail stays the same (the title shown in preview will be your home, but Nemo is showing Downloads)

**Comment by JosephMcc** [comment] 2015-12-17 12:10
This is a duplicate of https://github.com/linuxmint/Cinnamon/issues/4879 and there is already a fix waiting https://github.com/linuxmint/Cinnamon/pull/4890

**Closed by JosephMcc** 2015-12-17 12:10 UTC
