### ISSUE TITLE
alt+F2 then alt+tab

### ISSUE THREAD

**Issue by lejar** [linuxmint/Cinnamon#1841] opened 2013-04-04 11:10 UTC
If alt+tab is pressed when the run command dialogue is open (alt+F2), the run dialogue window will lose focus and focus cannot be regained. When this happens, the mouse cannot be used to interact with windows and the screen is greyed out.

Using cinnamon 1.6.7 on Ubuntu 12.10.

**Comment by dalcde** [comment] 2015-05-06 21:03
It seems to be fixed in Cinnamon master. Can someone else confirm?

**Comment by JosephMcc** [comment] 2015-05-07 10:14
I'm unable to reproduce this on Cinnamon master.

**Closed** 2015-06-08 09:59 UTC
Labels: BUG, CLOSE IF NO INFO, GRAPHICS WEIRDNESS
