### ISSUE TITLE
Closing application with mouse over the taskbar leaves a "window" that can not be closed

### ISSUE THREAD

**Issue by ilopmar** [linuxmint/cinnamon#9077] opened 2019-12-31 11:09 UTC
```
 * Cinnamon version: 4.4.6 (not daily builds)
 * Distribution: Mint 19.3
 * Graphics hardware *and* driver used: Intel HD 530 with built-in drivers
 * 64 bit
 ```

**Issue**

When closing any application, if the mouse is over the application in the taskbar, then a small window with title with the application is shown and can not be removed.
Please see this:

![Peek 2019-12-31 11-56](https://user-images.githubusercontent.com/559192/71619699-ec3a0b00-2bc5-11ea-9dd5-b77ab9d25120.gif)

I keep the mouse over the taskbar and then close the terminal with `exit` and then I close the calculator using `ALT+F4`. You can see the small windows displayed.

**Steps to reproduce**

Open any application, move the move over the taskbar and while displaying the preview, close the application with the keyboard doing `ALT+F4`

**Expected behaviour**

The "small" window with the application name should not be displayed.

**Comment by claudiux** [comment] 2019-12-31 11:43
@ilopmar What applet are you using? I can't reproduce this issue with the Grouped Window List (GWL) applet.

**Comment by ilopmar** [comment] 2019-12-31 11:46
Sorry, I forgot to mention that. I'm using `Window list`. In the "Welcome" window I selected the "Traditional Desktop" layout:

![image](https://user-images.githubusercontent.com/559192/71620688-894b7280-2bcb-11ea-87fa-097c00332438.png)

**Comment by mtwebster** [comment] 2019-12-31 12:32
This is a duplicate of https://github.com/linuxmint/cinnamon/issues/9051, already fixed (pending an update)

**Closed by mtwebster** 2019-12-31 12:32 UTC
