### ISSUE TITLE
cinnamon-settings ignores translated wallpaper names

### ISSUE THREAD

**Issue by jbicha** [linuxmint/Cinnamon#6289] opened 2017-02-14 23:41 UTC
Test Case
-------------
Install the `gnome-backgrounds` package.
Run this command in a terminal:
`LANGUAGE=fr cinnamon-settings`
Click `Fonds d'écran`
The waterfall image should be labeled `Chutes d'eau`

What happens
-------------------
The waterfall image is labeled 'Waterfalls'.

Other info
-------------
The translations are clearly visible in the same place you get the wallpaper name from:
`/usr/share/gnome-background-properties/gnome-backgrounds.xml`

The testcase works with Unity.
Make sure `unity-control-center` is installed then run
`XDG_CURRENT_DESKTOP=Unity LANGUAGE=fr unity-control-center appearance`
Click the waterfall image.

The testcase doesn't work in MATE for a [different reason](https://github.com/mate-desktop/mate-control-center/issues/268).

System Info
---------------
Ubuntu 17.04 Alpha
cinnamon 3.2.7-2

**Comment by clefebvre** [comment] 2017-02-16 11:50
Here's an extract of the XML for testing purposes:

```
<wallpapers>
	<wallpaper deleted="false">	
		<name>Waterfalls</name>
		<name xml:lang="fr">Chutes d'eau</name>
		<filename>/usr/share/backgrounds/gnome/Waterfalls.jpg</filename>
		<options>zoom</options>
    <pcolor>#ffffff</pcolor>
    <scolor>#000000</scolor>
	</wallpaper>
</wallpapers>
```

Afaik this should be in cinnamon-background-properties to be loaded though.

**Comment by JosephMcc** [comment] 2017-02-16 11:53
Yep. Just like Mate uses mate-background-properties, we use cinnamon-background-properties. Unity on the other hand using the gnome path.

**Comment by clefebvre** [comment] 2017-02-16 11:54
I can't reproduce that issue.

Tested on Mint 18.1, I modifed /usr/share/cinnamon-background-properties/linuxmint-maya.xml (from mint-backgrounds-maya), to add a French name to the first wallpaper:

```
<wallpaper deleted="false">
    <name>Ancient</name>
    <name xml:lang="fr">Vieux</name>
    <filename>/usr/share/backgrounds/linuxmint-maya/ancient.jpg</filename>
    <options>zoom</options>
    <shade_type>solid</shade_type>
    <pcolor>#000000</pcolor>
    <scolor>#000000</scolor>
    <artist>Al Butler</artist>
</wallpaper>
```

The result is as expected:

![capture du 2017-02-16 11-53-28](https://cloud.githubusercontent.com/assets/1138515/23020358/9b2b7d1e-f43e-11e6-82a1-fbc1226e6918.png)

**Comment by clefebvre** [comment] 2017-02-16 11:56
But @JosephMcc afaik gnome-backgrounds doesn't provide metadata for Cinnamon, so the backgrounds shouldn't visible at all.

**Comment by clefebvre** [comment] 2017-02-16 11:57
Localized names are functional anyhow so I'll close this issue.

**Comment by jbicha** [comment] 2017-02-16 11:58
As far as cinnamon metadata goes, see also
https://github.com/mate-desktop/mate-control-center/issues/268

**Comment by JosephMcc** [comment] 2017-02-16 11:59
@clem but I believe the actual images still live in /usr/share/backgrounds. Maybe thats why? I'd have to look in cs_backgrounds again to remember. I know we only look for metadata in the cinnamon path though.

**Comment by jbicha** [comment] 2017-02-16 12:02
Then this bug should be reopened since the test case Clem tried is not the same as the test case I reported.

**Comment by clefebvre** [comment] 2017-02-16 12:04
Ah sorry, I misinterpreted the report.

**Comment by clefebvre** [comment] 2017-02-16 12:06
Let's point to the MATE issue then and talk about it there, otherwise we'll just duplicate the very same conversation.

**Comment by clefebvre** [comment] 2017-02-16 12:06
https://github.com/mate-desktop/mate-control-center/issues/268

**Closed by clefebvre** 2017-02-16 12:06 UTC
