### ISSUE TITLE
Screen flickering after upgrading to Mint 19.1

### ISSUE THREAD

**Issue by bws678** [linuxmint/cinnamon#8613] opened 2019-06-07 04:18 UTC
```
 * Cinnamon version 4.0.10
 * Distribution - Mint 19.1
 * GTX 1060 with Nvidia 390.116 proprietary driver
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

[syslog.txt](https://github.com/linuxmint/cinnamon/files/3264349/syslog.txt)

**Issue**
The screen flickers horribly and artifacts are present all over the OS. 

**Steps to reproduce**
At startup, dragging the welcome screen back and forth will cause a trail of artifacts that persist after dropping the screen in place. Hovering the mouse over the close causes the entire trail to flash. It is worse if the window is dragged from right to left. Moving another window over the artifacts, moving the same window back over them, or closing the window altogether will cause them to disappear. 

Opening the mint menu (programs list) causes some flashing when moving the mouse over the different program icons. 

**Expected behaviour**
The new update (Mint 19.1) was supposed to help with the screen tearing, but it doesn't seem to have done so. This is the case for at least the 1060. 

**Other information**
I have tried changing drivers to the open source driver, but all this served to do was lock me from changing back to the proprietary driver and make the flashing much worse. The only thing that was present in LM 19 was the screen tearing.

**Comment by leigh123linux** [comment] 2019-06-07 08:54
Try a newer driver, 390.xx is a legacy driver.

**Comment by MartinX3** [comment] 2019-06-07 13:01
My 2 ThinkPads having the same issue. One with v418 driver (GTX 940MX) and one with the iGPU of the i7-6700HQ.
I boot it up without connected monitors, I put it in standby, I connect 2 monitors, I wake it up, hello flickering black areas around application windows.

**Comment by bws678** [comment] 2019-06-07 14:10
Tried one of the 400+ drivers. It seemed to help a little with screen tearing, but the artifacts remained. What's worse, I now do not have the ability to change dribers through the driver manager since all options are greyed put except for "continue using a manually installed driver." 

In order to update to the later nvidia driver, I had to use the ppa for graphics drivers. When I tried to install in driver manager, it told me that I was missing dependencies and when I tried to install the dependencies, it told me I was holding broken packages. I was able to install the driver after deselecting the ppa in software sources, but I only had the 390 and 410 drivers as options. I'm thinking LM 19.1 has broken something with the ppa or driver manager.

**Comment by clefebvre** [comment] 2019-06-10 16:14
I'll prepare a build for you to test, I've an idea of what the cause could be.

**Comment by clefebvre** [comment] 2019-06-10 17:06
https://github.com/linuxmint/muffin/pull/521

@bws678 @MartinX3, can you test this build:

[4.0-maintenance-no-norelayout-flag.zip](https://github.com/linuxmint/cinnamon/files/3273029/4.0-maintenance-no-norelayout-flag.zip)

Let me know if it helps.

**Comment by jaszhix** [comment] 2019-06-10 17:11
https://github.com/linuxmint/cinnamon/issues/7665

**Comment by bws678** [comment] 2019-06-10 18:28
How should I go about applying the package? Through terminal?

**Comment by JosephMcc** [comment] 2019-06-10 18:31
@bws678 unzip the folder, dive into it and open it in the terminal. Then run sudo dpkg -i *.deb

Make sure to restart your machine after you install them

**Comment by MartinX3** [comment] 2019-06-11 21:22
@clefebvre sadly your packages made the problem of #7665 even worse
Now i have bigger black flickering areas.
But thank you for trying. :)

**Comment by clefebvre** [comment] 2019-06-11 22:15
That's ok... that was with the flags like they were on 3.8. Let's try the way they were on 4.0. Can you try this one?

[flags-like-in-4.0.zip](https://github.com/linuxmint/cinnamon/files/3278783/flags-like-in-4.0.zip)

**Comment by clefebvre** [comment] 2019-06-12 09:37
I can reproduce #7665.

**Comment by clefebvre** [comment] 2019-06-12 10:11
@MartinX3 I get the feeling you're having a different problem than @bws678. What you're describing sounds like #7665, which I can reproduce and which is an issue which has been in Cinnamon for a long time now (affects 3.8, 4.0.6, 4.0.7, current master/PPA).

@bws678 your issue is different. I'm not sure I can reproduce it. You're seeing artefacts with only the welcome screen open, at startup, with only one monitor? Can you check your version of muffin? (muffin --version). Is it 4.0.6 or 4.0.7?

**Comment by MartinX3** [comment] 2019-06-12 10:16
@clefebvre 
Woops, sorry, sadly english is not my mother tongue. Seems you are right.

And sometimes if I put my laptop into the password screen the left upper corner has a colourful artefacts area. But maybe there is already a issue ticket somewhere.

**Comment by clefebvre** [comment] 2019-06-12 11:06
That sounds like #7665 as well.

**Comment by bws678** [comment] 2019-06-12 15:53
I reinstalled a new copy of linux mint 19.1 over the existing one and installed all new drivers and updates. After this, the screen flickering and artifacts disappeared. The issue with the ppa seems to be resolved as well. Looks like something that occurs during the upgrade process breaks driver manager? I still have screen tearing. The worst of it is on only one monitor, but the other two have it to a lesser degree. I am now on the 410 nvidia driver release from the ppa and I have tried fiddling with the mint settings and the nvidia settings. Nothing seems to help. I only started having screen tearing problems in lm 18, so why is it so difficult to fix now?

**Comment by clefebvre** [comment] 2019-06-12 15:59
If you use the version from the alpha testing PPA you can choose your vsync method. I'll close this issue for now as the mintwelcome artefacts are gone, and @MartinX3's issue is in #7665.

**Closed by clefebvre** 2019-06-12 15:59 UTC

**Comment by clefebvre** [comment] 2019-06-13 10:20
I see cinnamon2d refs in the log actually... we know we get artefacts there on window moves: https://github.com/linuxmint/cinnamon/issues/8582

**Comment by howdev** [comment] 2020-09-05 03:51
There is still flickering in Cinnamon 4.4. I seen more and more flickering issue after version 4.0. Version 3 I did not see this. And now Simplescreenrecorder affected by this, records flickering using either software or hardware encoder. The author of Simplescreenrecorder pointed this issue https://www.maartenbaert.be/simplescreenrecorder/troubleshooting/#the-recording-occasionally-flickers-showing-parts-of-the-desktop-background-instead-of-windows
