### ISSUE TITLE
Steam slows down shutdown

### ISSUE THREAD

**Issue by plata** [linuxmint/cinnamon#3752] opened 2014-12-12 18:03 UTC
If the steam window is open at shutdown, shutting down takes very long. (By shutdown I mean the time until cinnamon closes; once it logged off, everything is pretty fast).
Maybe cinnamon tries to store some information to startup steam again after the next boot (which btw does not work - for other programs it works though).

**Comment by SHOTbyGUN** [comment] 2015-05-26 19:54
+1 I'v noticed this as well. I have to manually shutdown steam before pressing  shutdown button. Otherwise it takes about 30 seconds to log off.

**Comment by martinrotter** [comment] 2015-07-28 07:06
+1 Experiencing too.

**Comment by Rugnak** [comment] 2015-08-19 02:42
Same ~20 s logout/reboot on i7-3770k with 16gb ram and ssd raid, on mint 17.2

**Comment by SHOTbyGUN** [comment] 2015-08-19 04:21
Installed MATE on LMDE2 Cinnamon Edition... and **this slow shutdown also happens on MATE session ** when steam is running. So this might be Linux Mint issue instead of Cinnamons.

**Comment by dalcde** [comment] 2015-08-19 05:26
On Tue, Aug 18, 2015 at 09:21:59PM -0700, Teemu Kauhanen wrote:
>Installed MATE on LMDE2 Cinnamon Edition... and **this slow shutdown also happens on MATE session ** when steam is running. So this might be Linux Mint issue instead of Cinnamons.

I guess it is more likely to be a Steam issue?

**Comment by leigh123linux** [comment] 2015-08-19 06:18
@dalcde 

It's a user issue IMO, programs should be shutdown manually before trying to shutdown as some programs set an inhibitor

**Comment by SHOTbyGUN** [comment] 2015-08-19 07:05
Could it be that Cinnamon sends wrong signal to the Steam, or Steam does not currently handle the signals what Cinnamon sends on logout.

**What signal does the Cinnamon send to Applications on logout ?**
If we knew that, we could report this issue on https://github.com/ValveSoftware/steam-for-linux/

Since there is no issues when using sudo reboot or sudo shutdown -h the issue is isolated between cinnamon / mate logout function and steam signal handling.

@leigh123linux  @dalcde it is NOT a user issue imho.

**Comment by martinrotter** [comment] 2015-08-19 07:08
@leigh123linux I could NOT disagree more. User issue, seriously? This is actually not concerning only Steam. Totally same thing happens for me for example for Double Commander (Qt version) too.

Simple systemctl reboot works, for example.

**Comment by dalcde** [comment] 2015-08-19 07:26
I am under the impression that when you ask Cinnamon to shut down, cinnamon sends a signal to ask everything to gracefully close, and wait for things to close. If steam/whatever application doesn't respond, Cinnamon won't shutdown until it gets impatient (after 30 seconds?).

To prove that it is a cinnamon issue, you must show that you don't get this problem if you use another desktop environment (and possibly a different display manager). Comparing with `sudo reboot` is a completely invalid since afaik `sudo reboot/shutdown` just brutally kills everything without waiting for them to close.

**Comment by martinrotter** [comment] 2015-08-19 07:28
Is there a way to edit that 30 s timeout?

**Comment by plata** [comment] 2015-08-19 19:43
@dalcde I've run some tests with different Linux Mint installations. All tests with fresh installs of 64bit Linux Mint 17.2 with all available updates installed in VirtualBox. This is what happens when I shutdown with Steam opened:
Cinnamon: slow; theme does not change (compare Mate), icons on desktop disappear long before shutdown
KDE: fast
Mate: slow; whole theme turns to the default theme (icons + panel) some time before shutdown
XFCE: fast

I think this proves that the issue is somehow related to Cinnamon/Mate.

@leigh123linux In this case it would not make sense to automatically open programs which were open before the last shutdow.

**Comment by dalcde** [comment] 2015-08-19 23:16
On Wed, Aug 19, 2015 at 12:43:28PM -0700, plata wrote:
>@dalcde I've run some tests with different Linux Mint installations. All tests with fresh installs of 64bit Linux Mint 17.2 with all available updates installed in VirtualBox. This is what happens when I shutdown with Steam opened:
>Cinnamon: slow; theme does not change (compare Mate), icons on desktop disappear long before shutdown
>KDE: fast
>Mate: slow; whole theme turns to the default theme (icons + panel) some time before shutdown
>XFCE: fast

Thanks a lot. That is, finally, some really useful information.

**Comment by martinrotter** [comment] 2015-08-20 04:28
It just seems that Cinnamon really has longer (it really sometimes seems to be 30s) "patience" interval. For example, Double Command opened without any ongoing action really delays the shutdown. When I kill it when shutdowning, then PC halts immediately.

**Comment by martinrotter** [comment] 2015-09-04 08:58
Steam has shipped new update to fight this bug on their side. They now correctly implement SIGINT and SIGTERM handlers.

**Comment by SHOTbyGUN** [comment] 2015-09-04 09:24
> Steam has shipped new update to fight this bug on their side. They now correctly implement SIGINT and SIGTERM handlers.
> http://www.hltv.org/news/15854-map-adjustments-in-new-update

Looks like those are for Linux CS:GO Server binary, not steam client.
I cannot find anything about this on Steam changelogs:
http://store.steampowered.com/news/?feed=steam_client
http://steamcommunity.com/groups/SteamClientBeta#announcements?p=1

But lets hope they will implement it to the steam client as well.

**Comment by martinrotter** [comment] 2015-09-04 09:27
OH, you are probably right. I completely forgot to diferentiate between Steam and CSGO binaries.

**Comment by Zerophase** [comment] 2015-10-11 15:35
Is there a work around for this?

**Comment by Rfvgyhn** [comment] 2015-10-16 16:18
It looks like this issue isn't just with Mint. It's been logged on the steam-for-linux repo and reported to happen in arch, ubuntu and elementary with both cinnamon and mate.

https://github.com/ValveSoftware/steam-for-linux/issues/3301

**Comment by calexil** [comment] 2015-12-19 19:27
issue continuing, fglrx, mint mate 17.3, steam on... long hang on shutdown theme defaults.. timeout

**Comment by intdel** [comment] 2016-01-18 23:21
It's not a Mint issue, but a Cinnamon issue because I have the same behavior on Fedora 23. I wonder if it is an incompatibility with gnome 3?

**Comment by calexil** [comment] 2016-01-18 23:25
its not a cinnamon issue intdel, its not DE dependent

**Comment by Zerophase** [comment] 2016-08-16 17:33
Steam just released a beta update for stopping a crash during shutdown on Linux. I'm stuck in windows pulling from a server for the next couple hours. Anyone want to check if the issue has been fixed?

**Comment by Tumetsu** [comment] 2016-08-29 21:02
Still having the issue with Linux Mint Sarah and Steam beta (package versions: 1471977975)

**Comment by Vahan86** [comment] 2018-02-11 14:24
@plata, does this issue still relevant to Cinnamon 3.6?

**Comment by plata** [comment] 2018-02-12 09:47
I cannot tell (I'm on KDE right now). If no one else is still experiencing this, feel free to close the issue.

**Comment by mainmachine** [comment] 2018-02-12 18:11
This was fixed in a recent Steam Client Beta release:

>  Fixed an issue where the Steam client could prevent some desktop sessions from shutting down

http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1655505073049286411

This is distro and DE agnostic, so we should close this.

**Comment by calexil** [comment] 2018-02-12 18:20
its not mainlined yet, but when it is @clefebvre close this

**Comment by JosephMcc** [comment] 2018-02-12 18:29
This can be closed here if the fix was on their side.

**Comment by Zerophase** [comment] 2018-02-12 18:34
@mainmachine Still slows shutdown on Cinnamon. What happens now is Cinnamon notices an 'unknown' process is slowing the shutdown, and 30 seconds later the system shuts down.  Only seems to be happening with Cinnamon. 

https://github.com/ValveSoftware/steam-for-linux/issues/5379

**Comment by mainmachine** [comment] 2018-02-12 18:37
@Zerophase - Honestly, I think I've gotten in the habit of closing Steam before I shutdown/reboot so I can't confirm it works properly now. I'll re-test myself tonight and report back. I heard anecdotally that it was solved with this Beta update, but I assumed it was DE independent...

**Comment by JosephMcc** [comment] 2018-02-12 18:49
Err, alright. When you guys can confirm if this is working please follow up.

**Comment by mainmachine** [comment] 2018-02-14 21:59
@Zerophase was correct, this is still a problem on Cinnamon. :/

**Comment by moel85** [comment] 2018-03-07 18:21
dont know why my issue was closed.

my system just doesn't shutdown at all.
Neither after 30 seconds, nor after 5 minutes.
Or do you guys think that this is still a failure on Steam-Side?

**Comment by moel85** [comment] 2018-03-07 19:20
> 
* Applet version/Build date: IcingTaskManager@json: 6.3.0 (#1637) 
 * Cinnamon version 3.4.6
 * Distribution -Linux Mint LMDE 2  cinnamon 64 bit
 * Graphics hardware Card: Intel 2nd Generation Core Processor Family Integrated Graphics
                                            Controller
 * Snippet or attachment of ~/.cinnamon/glass.log -- nothing shows up
 * Snippet or attachment of ~/.xsession-errors -- (https://github.com/linuxmint/Cinnamon/files/1790077/Unbenanntes.Dokument.txt)



**Issue**
When Steam is running (no matter if i just opened it or after 30 minutes of gaming), clicking the "shutdown"-Button in the Cinnamon menu or any extension which can shut-down the system, ONLY shuts down steam.
Even after waiting more than 3 minutes the System doesn't shut down.
If i again click Shut-Down the system shuts down as usual.
This issue doesn't only happen by trying to shut down, but also by trying to log-out  or restart or suspending the system.
Even after a restart it is reproducible


**Steps to reproduce**
as mentioned above


**Expected behaviour**
that the system shuts-down when i click the shutdown-button. Not only Steam :D


**Other information**
--


don't know why my issue was closed.

my system just doesn't shutdown at all.
Neither after 30 seconds, nor after 5 minutes.
Or do you guys think that this is still a failure on Steam-Side?

**Comment by mainmachine** [comment] 2018-03-07 19:46
@moel85 - it was closed as it's a duplicate of this issue. It's almost definitely the same root problem.

**Comment by LinuxOnTheDesktop** [comment] 2019-04-03 19:02
I have this problem too. That is: some application isn't responding to the shutdown signal. I am having trouble telling whether the problem is Conky or KeePassXC (the latter has an acknowledged problem on this front, but I am using a version of it that supposedly does not have the problem) or something else.

It would be useful were Cinnamon to provide some information - or information that is more visible? - about what is causing the delay.

**Comment by breadland** [comment] 2019-05-31 21:12
I have the same problem. No matter if I use Linux mint with the Cinnamon DE, or Arch, or Ubuntu.

If Steam is open when I reboot, shutdown, or log out, Steam will instantly close, then a second or two later, I'll get a small window pop up that says "A Program is not responding".

Inside it, there's just one program called "Unknown" that's not responding. After a second, that little popup window will disappear. I can use my computer normally, until exactly 30 seconds pass, and it shuts down, restarts, logs out.

If I close Steam beforehand, then the action is pretty much instant, like the other DE's I've used.

If that delay could be removed I'd be really happy with the Cinnamon DE. I've also noticed the the MATE DE has the same exact problem.

**Comment by StaticRocket** [comment] 2019-06-13 07:26
I don't think Steam is properly indicating that it has successfully exited. Looking at the logs and running processes during the 30 second timeout, it is clear that all Steam processes exit almost immediately after initiating logout/shutdown. Regardless, the timeout persists.

**Comment by JSkier21** [comment] 2020-01-25 22:00
As @plata mentioned, not all DEs suffer from the slowdown. I also use XFCE4, and it will shutdown just fine. I prefer to keep Steam running upon startup. Running ArchLinux.

**Comment by Rakly3** [comment] 2020-02-28 16:18
There still is no fix for this? It's driving me insane cuz I mainly am using Steam remotely.

**Comment by Commander-Zal** [comment] 2020-03-15 02:27
I experience this issue as well with Mint 19.3 Cinnamon, it shuts down instantly if Steam isn't open, but takes significantly longer if Steam is running. 

Quite annoying on a dual-boot system, as it slows down a reboot tremendously.

**Closed** 2020-03-16 18:59 UTC
Labels: BUG

**Comment by Rakly3** [comment] 2020-03-17 05:41
Why closed?
