### ISSUE TITLE
Icon tray is using legacy theme

### ISSUE THREAD

**Issue by Lukypie** [linuxmint/Cinnamon#5179] opened 2016-04-01 17:57 UTC
After updating cinnamon in Ubuntu 16.04 to the nightly repository, the tray icons are using the legacy GNOME theme.

Before update (ubuntu 16.04 default repo)
![schermata del 2016-04-01 19-48-49](https://cloud.githubusercontent.com/assets/7904559/14215521/c73154a8-f843-11e5-9769-19b41b071ca8.png)

After (ubuntu 16.04 nightly repo)
![schermata del 2016-04-01 19-44-30](https://cloud.githubusercontent.com/assets/7904559/14215520/c72eab68-f843-11e5-81f6-7bbe86edf403.png)

Since I don't know if the repository is updated, and if the bug is already fixed, please if it is just ignore this.

**Comment by ManuelSchneid3r** [comment] 2016-07-29 21:50
cinnamon 3.0.7: I can not reproduce this. (btw 19.48 before 19.44? :wink: )

**Comment by JosephMcc** [comment] 2016-09-05 04:47
Closing since the OP never responded.

**Closed by JosephMcc** 2016-09-05 04:47 UTC
