### ISSUE TITLE
Screensaver remains on foever running in the background after activation

### ISSUE THREAD

**Issue by Fuxy22** [linuxmint/Cinnamon#6135] opened 2016-12-28 01:47 UTC
I'm runnig Cinnamon 3.2.1 on Arch Linux and it seems the xscreeensaver will remain running in the bacground forever once it kicks in and worse yet it uses 100% of the core it is running on.

In my case I have 2 monitors so 2 instances get started that will use 100% of 2 of my cores.

Worse yet if you leave the computer idle again another 2 instances get started which in turn will use another 2 cores.

Why isn't the screensaver shut off after it dissappears? Am I missing something or is this a bug?

![htop of screensaver still running in the background](https://cloud.githubusercontent.com/assets/2676026/21511934/fddeeaf8-cc9e-11e6-973a-402db9ecbc13.png)

**Comment by zquestz** [comment] 2017-01-10 21:04
I am also seeing this happen. For instance:

```
quest     6204  0.2  0.0 178940 24212 tty2     S+   09:28   0:35 /usr/lib/xscreensaver/glmatrix -window-id 62914563
quest     6206  0.2  0.0 178616 24960 tty2     S+   09:28   0:33 /usr/lib/xscreensaver/glmatrix -window-id 65011715
quest    21506  1.1  0.0 178940 23188 tty2     S+   12:07   0:37 /usr/lib/xscreensaver/glmatrix -window-id 75497475
quest    21509  1.0  0.0 178744 22940 tty2     S+   12:07   0:36 /usr/lib/xscreensaver/glmatrix -window-id 77594627
```

I have to manually kill the xscreensaver sessions after unlock.

**Comment by mtwebster** [comment] 2017-01-11 02:38
I can't reproduce this on latest Arch, up-to-date (screensaver version 3.2.13)  Can you try on the latest updates?

**Comment by zquestz** [comment] 2017-01-11 19:49
@mtwebster I am on the latest packages, seems to happen a lot more often when using 2 displays.

**Comment by michael-schaller** [comment] 2017-05-03 14:37
I was able to reproduce this issue with these instructions:
1) cinnamon-settings screensaver
2) Select CubeStorm
3) Select default Screen Locker
4) There should be a leftover /usr/lib/xscreensaver/cubestorm process

This doesn't happen with all the xscreensavers in the list. So try several if you aren't able to reproduce it with CubeStorm like I was able to. You can watch for leaked xscreensaver processes with this one liner:
$ while true; do ps ax | grep -i xscreensaver | grep -v grep; sleep 0.1; done

**Comment by mtwebster** [comment] 2017-05-03 15:26
Should be fixed for 3.4 I think by:

https://github.com/linuxmint/cinnamon-screensaver/commit/cfa1f1aa45908f4e92aa2572a0cf6d563a1938ad

https://github.com/linuxmint/Cinnamon/commit/50f665f3bee4718b1b09ce02011f48c3b59f52ba

**Comment by bitstrings** [comment] 2017-05-11 20:48
Nope still got it with 3.4.

I have 2 monitors.

**Comment by mtwebster** [comment] 2017-05-11 21:08
Did you log out/in or at least kill and restart the screensaver after upgrading? (Sorry for the possibly dumb question but I have to ask)

**Comment by bitstrings** [comment] 2017-05-11 21:11
Of course, this on a computer I use for gaming in Windows. I Rebooted many times since. Fresh start.

**Comment by mtwebster** [comment] 2017-05-11 21:19
Hmm can't reproduce - I was definitely able to reproduce precisely this a while back, that's why I was pretty certain I'd fixed it - some screensavers wouldn't exit cleanly, many would.  I'll try to take another look at this asap.   Are fully upgraded with cinnamon as well?  The settings page is part of that package, not cinnamon-screensaver.  Again, apologies for potentially insulting suggestions ;)

**Comment by bitstrings** [comment] 2017-05-11 21:40
Nothing insulting, I appreciate you're looking into this.

Yes fully upgraded. For reference I am trying to use "lockward".

But hey, I will give another look tonight, see if I missed something. I looked at the code and I agree, it should be fixed.

**Comment by bitstrings** [comment] 2017-05-14 20:07
After using "lockward" screensaver it happened again
![selection_001](https://cloud.githubusercontent.com/assets/911165/26037372/5e855932-38bf-11e7-8347-e83973eb8ded.png)

**Comment by bitstrings** [comment] 2017-05-15 02:35
Small precision, it doesn't happen every time.

**Comment by mtwebster** [comment] 2017-05-15 02:41
Does this happen *only* when you're in cinnamon-settings configuring the screensaver, or does it also happen via the normal operation of cinnamon-screensaver itself? (Screensaver starts after timeout or locking, and after unlocking, the process is still running)

Also, what distro is this on, and what versions of GLib and Gtk3?

**Comment by bitstrings** [comment] 2017-05-15 02:47
Tumbleweed - Cinnamon 3.4.0

It happens during normal screensaver operation.

![selection_002](https://cloud.githubusercontent.com/assets/911165/26040916/2855dd04-38f7-11e7-8d84-194e1057a807.png)

**Comment by mtwebster** [comment] 2017-05-15 02:58
Any idea how well it runs under virtualbox?  I'd like to try it and see why this behaves differently.

I'm a bit concerned because the devs for Gtk aren't too concerned about support for GtkPlugs and GtkSockets (which allows this all to work,) since they don't work under Wayland, which generally means they'll stop caring about fixing anything that goes wrong with them.

Thanks

**Comment by mtwebster** [comment] 2017-05-27 04:13
https://github.com/linuxmint/cinnamon-screensaver/commit/f08c726496a33ee266a15e748c9ccbed58894975

This hopefully will do it - i did my previous fix with 'lock the computer when the screensaver starts' active - the plugin gets killed properly when happens.  There was no kill being sent when directly de-activating the screensaver without the lockscreen first.

**Comment by bitstrings** [comment] 2017-05-28 17:59
alright I will test this, thanks.

**Closed** 2017-12-18 11:00 UTC
Labels: BUG

**Comment by leigh123linux** [comment] 2017-12-18 11:01
I believe the misfiled cinnamon-screensaver is fixed.
