### ISSUE TITLE
The architecture of indicator.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#4261] opened 2015-06-04 19:07 UTC
Hi. As i know is planned include the indicator on cinnamon and i want to help on this. I need to know some basic things. I have currently two different ways to implement this. Inside there are a lot of decision that need to be taken on account... As include more things on the api of cinnamon popup menu or only as part of the indicator. 

The implementations that i have are:
1- The copy of the indicator with several change to work in cinnamon (https://github.com/lestcape/Appindicator).
2- A rewrite of the 1 to allow reuse the menu factory to construct any menu and also allow override the current functionality (https://github.com/lestcape/Global-AppMenu).

In 1, the menu factory api is "final" and is part of the dbusmenu api by design. In the second, the factory can be reuse to build any abstract type of menu and is part of the popup menu api by design.

I create the second, because i use in the Global Menu API two types of DBus Menu, one for GTK and other for KDE, so Is useful have a dynamic API. In the indicator, only is useful the KDE, but a dynamic api could be useful to other things. For example: if you use the api on cinnamon menu applet, then you not need to rebuild the full cinnamon menu applet structure, when you install one application.

**Comment by leigh123linux** [comment] 2015-06-05 06:03
Just another thing for me to rm when building cinnamon for fedora.

**Comment by lestcape** [comment] 2015-06-05 06:48
@leigh123linux, the indicator used an standar API, also this API is proposed to be part of freedesktop.org. As opposite, the global menu not use this standar API. The systray is an applet, so you don't need to include this new applet on Fedora if finally is implemented. You can continued using the current implementation and if in some time required a patch, i'm happy to help. Also this can be speak with @clefebvre and cinnamon can used also both types of systray applets as a user decision. I also have my own doubts about the feasibility of sacrifice the performance for the sake of a better aesthetics (this include solve current problems with pinding icons and others), but to my knowledge by test, nobody will lose anything.

You work in Fedora is incredible, your help on Cinnamon is invaluable. You have a general knowledge about hardware environment, which I think is unique and would be certainly a shame for the reasons were, if you left to help, but of course is your personal decision. I think you have the power of take the decision that you want on Fedora and will be the right decision on Fedora, also if this is not taking on account in Mint. Certainly you have the arrogance to believe that everything you say is correct, because it is the arrogance of all genius like you and if unfortunately another genius takes a different decision to yours decision, not mean you're wrong.

**Comment by leigh123linux** [comment] 2015-06-05 07:06
This isn't a personal choice, fedora never really adopted appindicator and it's rarely used (probably non-functional like the fedora apt package).

```
$ dnf list *appindicator*
Last metadata expiration check performed 2 days, 0:21:19 ago on Wed Jun  3 07:35:46 2015.
Available Packages
libappindicator.i686                                                        12.10.0-8.fc22                                           fedora
libappindicator.x86_64                                                      12.10.0-8.fc22                                           fedora
libappindicator-devel.i686                                                  12.10.0-8.fc22                                           fedora
libappindicator-devel.x86_64                                                12.10.0-8.fc22                                           fedora
libappindicator-docs.noarch                                                 12.10.0-8.fc22                                           fedora
libappindicator-gtk3.i686                                                   12.10.0-8.fc22                                           fedora
libappindicator-gtk3.x86_64                                                 12.10.0-8.fc22                                           fedora
libappindicator-gtk3-devel.i686                                             12.10.0-8.fc22                                           fedora
libappindicator-gtk3-devel.x86_64                                           12.10.0-8.fc22                                           fedora
libappindicator-sharp.x86_64                                                12.10.0-8.fc22                                           fedora
libappindicator-sharp-devel.i686                                            12.10.0-8.fc22                                           fedora
libappindicator-sharp-devel.x86_64                                          12.10.0-8.fc22                                           fedora
perl-Gtk2-AppIndicator.x86_64                                               0.15-5.fc22                                              fedora
python-appindicator.x86_64                                                  12.10.0-8.fc22                                           fedora
```

We also have apt but it has functioned properly for 5 years+

```
$ dnf list apt
Last metadata expiration check performed 2 days, 0:24:54 ago on Wed Jun  3 07:35:46 2015.
Available Packages
apt.i686                                                 0.5.15lorg3.95-17.git522.fc22                                               fedora
apt.x86_64                                               0.5.15lorg3.95-17.git522.fc22                                               fedora
```

**Comment by lestcape** [comment] 2015-06-05 07:23
Check the existence of a service and then swap to the current implementation is also possible. I finally will not take any decision... If i can help on any thing please tell me.

**Comment by vladimir-didenko** [comment] 2015-06-07 09:41
I think indicators are useful since KDE5 has dropped legacy tray and supports only SNI now. Gnome is also going to drop legacy tray (unfortunately without replacement). Not sure about global menu usefulness in another distros since it requires patches for core packages.

**Comment by dalcde** [comment] 2015-06-07 19:58
I'll add my vote for supporting indicators. Despite not being able to understand how exactly it works after reading many sites, it seems to be a cleaner architecture and much more pleasant to support than systrays.

So a few comments:
 - I'm not sure I understand how the second option is supposed to work. What is the menu factory? What do you mean by "can be reuse to build any abstract type of menu and is part of the popup menu api by design"?

 - We might want to look into the original patches submitted to GNOME shell  (https://bugzilla.gnome.org/show_bug.cgi?id=652122) since that probably provides better integration with existing source instead of a huge hack on top of the current system. Not sure how well-developed those are compared to the current applet implementation, though.

 - We probably want to fix the issue of classicMenu freezing problem before integrating into Cinnamon. Other than that, I don't see any showstoppers that prevent the implementation, given that there is a current working applet. Support for more complicated features such as tooltips or indicators-with-weird-sizes can be added later. I think it is more important to have the core features landed on git master as soon as possible to ensure stability and fix any bugs.

 - Afaik, if there is no working appindicator libraries, the appindicator applet will simply be non-functional and the systray will take over. So distros not supporting appindicators need not worry as the old behaviour will remain.

 - It seems that many programs are using appindicators as cross-DE applets, and I'm not sure if we want to encourage that. However, given that this is the case, it might be a good idea to allow users to separate appindicators, similar to separating panel launchers.

  I think this can be implemented by allowing applet instances to be either an individual application or a "master" one - if there is an individual applet for the particular program, then the appindicator will appear at the individual applet. Otherwise, it ends up at the master applet. The individual ones can simply hide themselves when the corresponding applications don't exist.

**Comment by lestcape** [comment] 2015-06-07 23:00
@dalcde any Dbusmenu, is an abstract representation of a menu (i.e. not a real clutter actors). In the Dbus Menu this abstract implementation is provided in an array of menu items, and need to be converter to a real one (clutter actors) using some mechanisms (the menu factory). So, the menu factory could directly receive the array of items and construct the clutter menu, or instead could receive a more general  class (an abstract class) that absorve any complexity of the menu source (the Dbusmenu items). In the last case, and how the factory receives an abstract class, you can inherit of the abstract class and create a child using the source that you want, for example: an xml with the menu description, the definition of the CMenu, the KDE menu items, the GTK menu items. Then how right now only is useful create the kde Dbusmenu, we not need to include the version with the abstract class on the popup menu API, but could be useful provide this general implementation, to be reused to other things, and this is my question. Will be useful or not the general implementation?

Is not classicMenu in the cinnamon black list?

"the systray will take over": i don't think so, not as how this is implemented currently, is possible the some part of the gnome work will help to provide this.

For the rest we need to walk first, then we can run.

**Comment by dalcde** [comment] 2015-06-08 04:54
On Sun, Jun 07, 2015 at 04:00:50PM -0700, Lester Carballo P�rez wrote:
>@dalcde any Dbusmenu, is an abstract representation of a menu (i.e. not a real clutter actors). In the Dbus Menu this abstract implementation is provided in an array of menu items, and need to be converter to a real one (clutter actors) using some mechanisms (the menu factory). So, the menu factory could directly receive the array of items and construct the clutter menu, or instead could receive a more general  class (an abstract class) that absorve any complexity of the menu source (the Dbusmenu items). In the last case, and how the factory receives an abstract class, you can inherit of the abstract class and create a child using the source that you want, for example: an xml with the menu description, the definition of the CMenu, the KDE menu items, the GTK menu items. Then how right now only is useful create the kde Dbusmenu, we not need to include the version with the abstract class on the popup menu API, but could be useful provide this general implementation, to be reused to other things, and this is my question. Will be useful or not the general implementation?

Sounds like a cool idea.

>Is not classicMenu in the cinnamon black list?

I don't know, but if classicMenu breaks, then probably something else
also will. "Cinnamon freezing" is a pretty serious  ssue.

>"the systray will take over": i don't think so, not as how this is implemented currently, is possible the some part of the gnome work will help to provide this.

I have the appindicator applet installed and dropbox is still showing up
in the systray. I presume that is what happened.

>For the rest we need to walk first, then we can run.

Sure. Just throwing out ideas.

**Comment by lestcape** [comment] 2015-06-08 05:42
Well i will try to merge all things and implement the initial code in a functional way, i will separate in different file what i think need to be part of some current cinnamon file. I have my own menu api, but i will use the cinnamon api instead. In the cinnamon api is not allowed have several popup menus opened at the same time, so what I will do is a submenu inside a submenu, like is in gnome shell. There are an implementation to open two submenus in the cinnamon code, i enhanced this implementation to show more than two. This can be considered, and then can merge when the rest can work ok, is will be required.

**Comment by dalcde** [comment] 2015-06-08 07:15
You can patch Cinnamon code as you wish. After all, you are adding code to Cinnamon itself, not developing an external applet.

**Comment by lestcape** [comment] 2015-06-08 09:04
@dalcde i have not internet connection to make a complete update of cinnamon, and if I make a lot of commit, you clear will say me that merge all this in one, so not thanks... Better do the job outside and when this will be "ready", then i will merge with cinnamon. The systray is an applet, so not need to be merged to be tested.

**Comment by dalcde** [comment] 2015-06-08 09:58
> i have not internet connection to make a complete update of cinnamon

Updating to the nightlies once should not take a lot of bandwidth. If you wish to develop on latest Cinnamon git, you can do a shallow clone:
```
git clone --depth 1 https://github.com/linuxmint/Cinnamon
```
to avoid cloning all the history and just download the latest version. Developing on an old Cinnamon version might cause merge conflicts which can be painful at times.

> and if I make a lot of commit, you clear will say me that merge all this in one, so not thanks... 

What is wrong with merging commits?

> Better do the job outside and when this will be "ready", then i will merge with cinnamon. The systray is an applet, so not need to be merged to be tested.

Nope. Attempting to write everything outside of the Cinnamon is likely to cause maintenance hell and probably quite a lot of code duplication. The (current) systray is not an individual applet. In fact, the applet code is surprisingly simple, because most of the work is done within Cinnamon itself, and not in the applet.

**Comment by lestcape** [comment] 2015-06-08 10:28
What i say, is the same to no update the code before this will be "ready", to be integrated with cinnamon. As i see all people try to do that, they not provide a broken thing at the begin. You never suffer 4 hour to upload an image, right?

**Comment by dalcde** [comment] 2015-06-08 10:31
Sorry I don't understand what you are saying

**Comment by lestcape** [comment] 2015-06-08 23:41
Forget it... I will try to upload this in a day or two, now only are missing some little things that i want to do first.

**Comment by lestcape** [comment] 2015-06-09 02:05
![captura de pantalla de 2015-06-08 18 42 31](https://cloud.githubusercontent.com/assets/1389572/8047699/32849c0e-0e0e-11e5-8c40-8f765eedcdc7.png)

**Comment by lestcape** [comment] 2015-06-15 07:15
@leigh123linux if you have time please test this in fedora: https://github.com/linuxmint/Cinnamon/pull/4298
I try to avoid problems, and provide both behaviors, but this could need more things that i don't see.

**Comment by JosephMcc** [comment] 2015-11-08 07:36
I think this is safe to close since @lestcape's work on indicators is now part of Cinnamon.

**Closed by JosephMcc** 2015-11-08 07:36 UTC
Labels: FEATURE REQUEST
