### ISSUE TITLE
mint 17.1 after last update, now Mint disconnects huawei dongle in 15 seconds

### ISSUE THREAD

**Issue by ven-u** [linuxmint/Cinnamon#3780] opened 2014-12-23 09:06 UTC
See http://forums.linuxmint.com/viewtopic.php?f=53&t=185618   

Text of the post:

Topic: mint 17.1 huawei G3 dongle disconnects after15 seconds

Postby sadhu on Tue Dec 23, 2014 2:21 pm
On Wednesday Dec 17, 2014 I installed Mint 17.1 Cinnamon and was running for a couple of days with no problems. Was able to download and install the installation updates. Then, in the middle of a software update on Saturday, Dec 20, at approx 1030 hrs GMT, I was disconnected. I am unable to reconnect (that is, it disconnects after 15 seconds) no matter which dongle I use (I have two), nor which machine (laptop or desktop) I'm using. Both are running 17.1 64bit.

I had previously updated my laptop when I was in town, using a Wifi connection (not my dongle). So when I got back home, the dongle no longer worked on the laptop.

I rebooted to my fallback mint 17, and the E156 dongle works fine on both machines. Obviously a software problem that originated with the latest Mint 17.1 update.

My dongles are
E156 (I think --  the lettering has worn off the dongle)
E173

**Comment by leigh123linux** [comment] 2015-05-10 23:36
@dalcde 

I doubt that Linuxmint can fix this as the issue is likely to be in an Ubuntu provided package.

**Comment by dalcde** [comment] 2015-05-11 06:22
Closing unless someone can show it is directly related to Cinnamon

**Closed by dalcde** 2015-05-11 06:22 UTC
Labels: BUG
