### ISSUE TITLE
[BUG] Can't rotate screen (greyed)

### ISSUE THREAD

**Issue by lucasgabmoreno** [linuxmint/cinnamon#11112] opened 2022-08-24 23:12 UTC
```
 * Cinnamon version 5.4.11
 * Distribution: LMDE 5
 * Graphics: intel celeron
 * 64 bit
 ```

### Issue
Can't rotate with display app

<br>

### Steps to reproduce
![Captura de pantalla de 2022-08-24 20-01-51](https://user-images.githubusercontent.com/83520011/186538993-59eda4f9-7c97-4c19-988b-2910d2ddb4b6.png)

<br>

### Expected behaviour
Rotate screen, but looks greyed.

<br>

### Other information
Solved with `xrandr -o right` at startup, no permanently.

![Captura de pantalla de 2022-08-24 20-02-18](https://user-images.githubusercontent.com/83520011/186539033-f45f988c-8d78-4d37-a68e-64b0b9363d4d.png)

<br>

Same problem with `etc/X11/xorg.conf.d/30-monitor.conf`:
```
Section "Monitor"
Identifier "DSI-1"
Option "Rotate" "right"
EndSection
```
:point_up: This file works until last Cinnamon update

**Comment by leigh123linux** [comment] 2022-08-25 02:16
Duplicate of #11111

**Closed by leigh123linux** 2022-08-25 02:16 UTC
