### ISSUE TITLE
Code mistake in official tutorial about applets developing

### ISSUE THREAD

**Issue by DMantis** [linuxmint/Cinnamon#6329] opened 2017-02-28 19:02 UTC
http://developer.linuxmint.com/reference/3.0/cinnamon-tutorials/write-applet.html contains non-working applet code if copy-paste and load.

Current version of applet example shows notification "Cannot convert string to array of 'utf8'" when you click on it. That's because Util.spawn function needs array as input, not string.

So fix can be Util.spawn('xkill') -> Util.spawn(['xkill'])

For me it doesn't still work with xkill but works with launching other apps, e.g. works with Util.spawn(['steam']).

I use Linux Mint 18.1 64-bit with Cinnamon 3.2.7

**Comment by collinss** [comment] 2017-02-28 22:06
This has already been fixed. The online docs just haven't been updated in a while. If you look at it in devhelp, it is correct (requires the Cinnamon doc package which is not installed by default).

**Comment by RyanNerd** [comment] 2017-03-07 19:42
@DMantis I had the same issue with the tutorial and getting the example to work by issuing `xkill` _appears_ to be a permissions issue (which I've still not solved). Just my two cents.
@collinss The online documentation for creating applets that @DMantis referenced is outdated and makes multiple assumptions (it's just bad documentation if I'm brutally honest). Applets for Cinnamon from the community are very old as well (probably because creating them is not very easy or clear).

I'm a seasoned developer with over 20 years experience in multiple languages and platforms. I'd love to contribute by creating applets or desklets for Cinnamon but it's not worth my time because of sparse or terrible documentation.

**Comment by collinss** [comment] 2017-03-08 02:06
@RyanNerd I'm sorry you feel that way. I agree that the documentation certainly needs some work, though to be fair, there is much more of it than there was when I first started developing applets for Cinnamon. The truth is that we have day jobs, and we do this because we love it, not for a paycheck, so we do what we can, when we can. What little time we have to contribute is usually spent fixing some annoying bug, or working on some cool new feature. That's what keeps us going. Working on the documentation just doesn't rank high on the priority list.

In addition, there really is a lot of documentation out there, but it can be a little bit hard to find some of it because we rely on upstream libraries for a lot of what we do, and those libraries have their own documentation elsewhere.

> Applets for Cinnamon from the community are very old as well (probably because creating them is not very easy or clear).

The current state of the documentation may contribute in some way, but it is certainly not the biggest reason for the issue you have observed. In fact, the documentation is actually leagues ahead of where it was when most of the old abandoned applets were written, so logic would suggest that we should actually see more contributors, not less (and indeed I can think of at least 10 off the top of my head, who are actively developing right now, and some of them with 5 applets or more).

The reason it seems like most of the applets are old and outdated is two-fold. First, applets on the old site were primarily displayed by rating, which lead to new applets not being used and rated as often as older ones. Second, many of the older applets were abandoned by their original developers, and at some point many of them stopped working (due to newer package bases, changes in api, etc.). The problem has been compounded even further by other people coming along and forking some of these old, broken applets, and then abandoning them a while later, leaving behind yet another broken applet. Some of the more popular original applets have as many as 7 or 8 different forks or rewrites.

That being said, there have been some significant changes to how we manage the 3rd party extensions hosted on the spices website that make it much easier to keep the spices website clean. There are several of us who have been working hard to fix or remove all the old applets that no longer work. In addition, there is some work currently underway to revamp the rating system to make it easier to use and to avoid the problem of new applets being harder to discover.

I know that explanation was a bit long-winded, but I hope you see that the issue is much more complicated than a simple documentation issue, but it is one that is currently being addressed.

**Comment by RyanNerd** [comment] 2017-03-08 09:12
@collinss Thank you for your reply. Looks like I am the one that made assumptions and I apologize. I appreciate you taking the time to respond in such detail. I just wanted a working tutorial so I could try my hand at writing my own applets.
Looking at the code for some of the built in applets it appears many are just python apps launched from the applet icon click event which is okay. I wanted to write my own applets to perhaps get my feet wet enough where I could create PRs to contribute to Cinnamon (I don't have enough experience with Gnome or Cinnamon's internals that I feel comfortable doing this yet). 
Once again thanks for your time. I use Linux Mint with Cinnamon and **love it** perhaps you could direct me to the location of newer tutorials or any learning materials that I can use as a primer so that I can contribute code one day? Also, what editor would you recommend to code for Cinnamon?

**Comment by JosephMcc** [comment] 2017-03-08 11:08
The best resource is existing applets and Cinnamon's own code. Looking at existing code in combination with docs in devhelp is a good way to get the hang of how things are working. Many of the applets on the spices site are more up-to-date at this point. Some built in ones are fairly basic like the background slideshow applet. 

Don't be afraid to join the #linuxmint-dev IRC channel. Just be patient if you ask question there. It can be hit or miss if someone happens to be paying attention.

**Comment by DMantis** [comment] 2017-03-08 16:48
@collinss I fully understand that it's not paid job for most of contributors and this more "marketing" problem occurs almost anywhere in open-source/ But Mint is a an end-user operating system. Stuff like branding website, smart rating system, good docs are really important to operating system. If we talk about platform to write apps upon it (which applets are), it should have well-documented API, examples and so on - that will lead to engage new developers (including not hardcore professionals) in writing code to this platform. 

Moreover, I think as far not so much people write most using applets it would be smarter to union and divide these core applets from general rating at all to build base ecosystem applications to Cinnamon with similar design and user-experience. It will be more user-friendly and convenient to non-IT end-user.

**Comment by JosephMcc** [comment] 2017-03-13 20:39
Closing this since the original issue is actually fixed in Cinnamon itself.

**Closed by JosephMcc** 2017-03-13 20:39 UTC
