### ISSUE TITLE
Wireless networks aren't sorted

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5536] opened 2016-08-10 17:59 UTC
I've just installed Mint 18, and when trying to connect to my Wi-Fi hotspot, I noticed that the list of wireless networks isn't sorted by any criterion - neither name, [nor signal strength](https://github.com/linuxmint/Cinnamon/issues/5272).

![image](https://cloud.githubusercontent.com/assets/33569/17578321/506717bc-5f3c-11e6-941d-02ef9c94d558.png)

**Comment by anandrkris** [comment] 2016-08-11 15:34
Duplicate of https://github.com/linuxmint/Cinnamon/issues/2881

**Comment by JosephMcc** [comment] 2016-08-11 16:24
Search is your friend.

**Closed by JosephMcc** 2016-08-11 16:24 UTC

**Comment by dandv** [comment] 2016-08-11 19:33
> Search is your friend

@JosephMcc: do you honestly think that given my history of reporting bugs (which I've [made you aware of](https://github.com/linuxmint/Cinnamon/issues/5544#issuecomment-239209110)), I haven't searched? Is it possible that search ain't always the silver bullet, [as you yourself have experienced](https://github.com/linuxmint/Cinnamon/issues/5540#issuecomment-239203505)?

**Comment by anandrkris** [comment] 2016-08-12 03:58
I just want to say that network manager needs some :heart: :smiley:

**Comment by dandv** [comment] 2016-08-12 04:20
Is it possible somehow to set wireless network priority? [GNOME fixed the bug this capability depends on in 2014](https://bugzilla.gnome.org/show_bug.cgi?id=580018).
