### ISSUE TITLE
Grouped window list: "zombie" icons

### ISSUE THREAD

**Issue by yesint** [linuxmint/Cinnamon#8224] opened 2018-12-28 20:00 UTC
```
 * Cinnamon version: 4.0.8
 * Distribution: Mint 19.1
 * 64 bit
 * [errors.zip](https://github.com/linuxmint/Cinnamon/files/2715585/errors.zip)
 ```

Grouped window list applet sometimes "forgets" to remove the icon from the panel when the application is closed and it is *not* pinned. This happens when "show windows from all workspaces" is on. On the workspace where the program was running and then closed the icon is removed from panel correctly, but on the other workspace it remains as "zombie". Here is an example. Libreoffice was run on workspace1 and then closed. On workspace1 there is no icon, but on workspace2 there is one. The tooltip still shows the name of the file, which was open (can't put it to screenshot).
![screenshot from 2018-12-28 20-58-15](https://user-images.githubusercontent.com/14368585/50526592-53b90880-0ae3-11e9-9bcc-305d0921a735.png)
![screenshot from 2018-12-28 20-57-48](https://user-images.githubusercontent.com/14368585/50526593-54519f00-0ae3-11e9-9f27-5033e974559f.png)

The problem appears randomly with no obvious pattern, approximately few time per day and with different applications. Rather annoying and should be fixed. 

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by jaszhix** [comment] 2018-12-28 21:48
Duplicate of #8190 and fixed by #8192.

**Closed by jaszhix** 2018-12-28 21:48 UTC
