### ISSUE TITLE
Screen keeps locking when closing lid despite screensaver settings

### ISSUE THREAD

**Issue by HenryJk** [linuxmint/Cinnamon#7752] opened 2018-07-19 12:46 UTC
```
 * Cinnamon version 3.8.8
 * Distribution - Mint 19
 * Nvidia 940MX - nvidia-driver 390.48
 * 64 bit
 ```

Cinnamon lock screen keep appearing despite disabling lock screen from screensaver

**Steps to Reproduce**
1. Disable everything in system-settings>preferences>screensaver>settings>lock-settings
2. Close laptop lid
3. Open it again, lock screen still appear and password still prompted

**Expected Behavior**
No lock screen at all, display back to before lid closed.

**Other information**

**Comment by stellarpower** [comment] 2018-07-24 17:48
I have the opposite, my laptop refuses to sleep on lid switch closing. I believe this is brought forward from Ubuntu, dmesg says: 

`ACPI: button: The lid device is not compliant to SW_LID.`

and the workaround is to uncomment a line in /etc/systemd/logind.conf

[Apparently](https://discourse.ubuntu.com/t/testing-of-laptop-lid-close-suspend-behavior-in-unity-18-04/1470) Ubuntu changed behaviour in gnome-settings and this may be trickling through to cinnamon's settings daemon.

**Comment by smurphos** [comment] 2018-08-08 05:38
A workaround to the OP's issue.

`sudoedit /etc/UPower/UPower.conf`

Change `IgnoreLid=false` to `IgnoreLid=true`, Ctrl-X and then Y and enter to save. Reboot. 

This has a side effect of removing Lid Actions entirely from the Power Manager GUI, but also kills the bug of the screensaver kicking in despite settings on lid close being set to Do Nothing. Screensaver remains operational otherwise.

**Comment by Gigadoc2** [comment] 2018-09-27 22:43
I think the problematic line is in https://github.com/linuxmint/cinnamon-settings-daemon/blob/6dc353ba1c0d1e7dfd398fa88155dee72853bddd/plugins/power/csd-power-manager.c#L2308 (And the line above, but I have upower 0.99 so I can't check that right now)

This looks like it will just lock the screen whatever, disregarding any settings made. However, that line has been there for five years, so now I am wondering why the setting ever worked...

**Comment by mtwebster** [comment] 2018-09-27 23:17
That line is only called if the action is *not* hibernate or suspend.  Otherwise should_lock_on_suspend is checked, which looks at the setting.

I cannot reproduce this issue.

It's possible that some other mechanism is causing the lock to occur, even though it's disabled in cinnamon's settings.

Can you guys tell me if you're at least on cinnamon-settings-daemon 3.8.5? (`dpkg --list | grep cinnamon-settings-daemon`)

Please try the following:
```
killall csd-power
killall csd-power (yes, twice - it restarts itself)

csd-power --verbose
```

and reproduce the problem, then paste the logs here (or link to a paste site)

Thanks

**Comment by Gigadoc2** [comment] 2018-09-27 23:58
Maybe I misunderstood @HenryJk, but I think for him (and definitively for me) the action is not hibernate or suspend, so it fits?

In my case (and most likely @HenryJk's) the setting is not to suspend, hibernate or lock the screen on lid close (don't take any action, really).

This is the output of cinnamon-settings-daemon 3.8.6 (without the line commented):
```
(csd-power:9502): power-plugin-DEBUG: 01:48:35.701: lid is closed; suspending or hibernating
(csd-power:9502): power-plugin-DEBUG: 01:48:35.702: Locking screen before sleep/hibernate
(csd-power:9502): GLib-DEBUG: 01:48:35.702: posix_spawn avoided (fd close requested)
(csd-power:9502): power-plugin-DEBUG: 01:48:36.462: keyboard toggle on
(csd-power:9502): power-plugin-DEBUG: 01:48:36.465: Received gnome session status change
(csd-power:9502): power-plugin-DEBUG: 01:48:36.469: setting up blank callback for 600s
(csd-power:9502): power-plugin-DEBUG: 01:48:36.470: idle dim set with timeout 90
(csd-power:9502): power-plugin-DEBUG: 01:48:36.472: Setting dim idle timeout: 90s
(csd-power:9502): power-plugin-DEBUG: 01:48:36.472: keyboard changed signal

(csd-power:9502): GLib-CRITICAL **: 01:48:36.472: g_variant_unref: assertion 'value->ref_count > 0' failed
(csd-power:9502): power-plugin-DEBUG: 01:48:36.472: keyboard changed signal

(csd-power:9502): GLib-CRITICAL **: 01:48:36.472: the GVariant format string '(i)' has a type of '(i)' but the given value has a type of '(is)'

(csd-power:9502): GLib-CRITICAL **: 01:48:36.472: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

(csd-power:9502): GLib-CRITICAL **: 01:48:36.472: g_variant_unref: assertion 'value->ref_count > 0' failed
(csd-power:9502): power-plugin-DEBUG: 01:48:37.427: keyboard toggle off
(csd-power:9502): power-plugin-DEBUG: 01:48:37.430: keyboard changed signal

(csd-power:9502): GLib-CRITICAL **: 01:48:37.431: g_variant_unref: assertion 'value->ref_count > 0' failed
(csd-power:9502): power-plugin-DEBUG: 01:48:37.431: keyboard changed signal

(csd-power:9502): GLib-CRITICAL **: 01:48:37.431: the GVariant format string '(i)' has a type of '(i)' but the given value has a type of '(is)'

(csd-power:9502): GLib-CRITICAL **: 01:48:37.431: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

(csd-power:9502): GLib-CRITICAL **: 01:48:37.431: g_variant_unref: assertion 'value->ref_count > 0' failed
(csd-power:9502): power-plugin-DEBUG: 01:48:40.294: Received gnome session status change
(csd-power:9502): power-plugin-DEBUG: 01:48:40.294: setting up blank callback for 600s
(csd-power:9502): power-plugin-DEBUG: 01:48:40.295: idle dim set with timeout 90
(csd-power:9502): power-plugin-DEBUG: 01:48:40.295: Setting dim idle timeout: 90s
```
`/org/cinnamon/settings-daemon/plugins/power/lock-on-suspend` and `/org/cinnamon/desktop/screensaver/lock-enabled` are off. In the past, having these options off would also prevent the lock from activating when closing the lid. I'm afraid I don't remember the version of cinnamon or how long ago this was, I known I should have opened an issue right then.

While I am writing this I realize, it would actually be nice if one could have the screen lock on idle and on suspend but not on lid close. But I realize that this might be a niche feature and I might need to go the full length and just remove the lid detection as a whole (as that is what i want in the end).

But having the lock engaging when all the lock settings are turned off should probably still be fixed. If it is that easy to replace the running version of csd-power, I can also test this with the master branch.

**Comment by mtwebster** [comment] 2018-09-28 00:32
So what action do you have set for "When the lid is closed?"  I guess I missed the fact you none of you are talking about suspend or hibernate?

So yes, I can reproduce the screen locking when 'do nothing' is selected, even though locking is disabled all around.

**Closed** 2018-09-28 02:13 UTC

**Comment by Gigadoc2** [comment] 2018-09-28 16:02
Yes, I had both the "When the lid is closed" actions set to "Do nothing" (I often close the screen for just a few seconds, to carry the notebook to a different desk or such).

With https://github.com/linuxmint/cinnamon-settings-daemon/commit/677bbf6d27b394d7429e18f3fe9a3def000f49df this issue is now fixed, and I can even have the screensaver activate on suspend but not on lid close (when lid close is not causing a suspend, of course), which was not possible before (I think).

Thank you for the quick fix :smiley:
