### ISSUE TITLE
cinnamon crash at boot and reboot

### ISSUE THREAD

**Issue by melmelissa** [linuxmint/Cinnamon#7169] opened 2017-12-26 11:20 UTC
Hello

Cinnamon 3.6.7-1
ArchLinux 64-bit
Intel HD4000 and Nvidia GF108m with proprio driver
Kernel 4.9.71-1 lts

Cinnamon crashes when booting the pc, after Lightdm loading (version 1.24.0-3)
despite my research, no trace of the crash in question (neither in the logs, nor in dmesg ...)
I changed the theme, icons, wallpaper, but the problem persists, even with the default theme ...

easily reproducible.
Starting and restarting the PC is enough to crash Cinnamon.

a workaround exists this time ???

I came back to version 3.4, while waiting for a patch to be provided.
each update since the version 3.6 brings its batch of bugs on ArchLinux, it is normal such a regression ???
is a fix planned for us (Arch users) ??

I have the impression that ArchLinux users are not being listened to, or that our bugs are of no interest to anyone, yet we would also like to have a stable Cinnamon, without being stuck in version 3.4 (and version 3.2 of cjs), which one day we will have real problems over the updates of our other packages ..

thank you for taking into account our bug reports ...
versions of Cinnamon pass, but problems persist and grow ...

**Comment by leigh123linux** [comment] 2017-12-26 12:16
> Hello
> 
> Cinnamon 3.6.7-1
> ArchLinux 64-bit
> Intel HD4000 and Nvidia GF108m with proprio driver
> Kernel 4.9.71-1 lts
> 
> Cinnamon crashes when booting the pc, after Lightdm loading (version 1.24.0-3)
> despite my research, no trace of the crash in question (neither in the logs, nor in dmesg ...)
> I changed the theme, icons, wallpaper, but the problem persists, even with the default theme ...
> 
> easily reproducible.
> Starting and restarting the PC is enough to crash Cinnamon.
> 

I works fine here

```
rpm -qa lightdm cinnamon
lightdm-1.25.0-1.fc28.x86_64
cinnamon-3.6.7-1.fc28.x86_64
```

```
inxi -GCS
System:    Host: localhost Kernel: 4.15.0-0.rc4.git0.1.fc28.x86_64 x86_64 bits: 64 Desktop: Cinnamon 3.6.7
           Distro: Fedora release 28 (Rawhide)
CPU:       8 core AMD FX-8350 Eight-Core (-MCP-) cache: 16384 KB
           clock speeds: max: 4500 MHz 1: 1440 MHz 2: 2317 MHz 3: 1404 MHz 4: 1404 MHz 5: 2436 MHz 6: 1736 MHz
           7: 1404 MHz 8: 1391 MHz
Graphics:  Card: NVIDIA GP107 [GeForce GTX 1050 Ti]
           Display Server: x11 (X.org 119.6 ) drivers: nvidia (unloaded: modesetting,fbdev,vesa,nouveau)
           Resolution: 3840x2160@60.00hz
           OpenGL: renderer: GeForce GTX 1050 Ti/PCIe/SSE2 version: 4.6.0 NVIDIA 387.34
```


> a workaround exists this time ???
> 

Try filing an issue at flyspray as it isn't going to get fixed unless you provide some error logging.

> I came back to version 3.4, while waiting for a patch to be provided.
> each update since the version 3.6 brings its batch of bugs on ArchLinux, it is normal such a regression ???
> is a fix planned for us (Arch users) ??
> 
Have you considered it's due to poor packaging?

> I have the impression that ArchLinux users are not being listened to, or that our bugs are of no interest to anyone, yet we would also like to have a stable Cinnamon, without being stuck in version 3.4 (and version 3.2 of cjs), which one day we will have real problems over the updates of our other packages ..
> 
A lot of the arch issues are due to poor packaging IMO.


> thank you for taking into account our bug reports ...
> versions of Cinnamon pass, but problems persist and grow ...

**Comment by brownsr** [comment] 2017-12-26 12:48
nothing at all in .xsession-errors ?

**Comment by eli-schwartz** [comment] 2017-12-26 15:14
FWIW Cinnamon works for me, as it generally does. Filing an issue on flyspray without any reproducing details doesn't help any more than it does here. :frowning_face:

@leigh123linux I am now taking over maintenance of Cinnamon in the Arch repos, so if you think we have poor packaging feel free to offer suggestions.

**Comment by leigh123linux** [comment] 2017-12-26 15:28
@eli-schwartz  For starters, how about packaging the gi overrides for xapps

https://www.archlinux.org/packages/community/x86_64/xapps/

```
rpm -qal  python*-xapps-overrides
/usr/lib64/python2.7/site-packages/gi/overrides/XApp.py
/usr/lib64/python2.7/site-packages/gi/overrides/XApp.pyc
/usr/lib64/python2.7/site-packages/gi/overrides/XApp.pyo
/usr/lib64/python3.6/site-packages/gi/overrides/XApp.py
/usr/lib64/python3.6/site-packages/gi/overrides/__pycache__/XApp.cpython-36.opt-1.pyc
/usr/lib64/python3.6/site-packages/gi/overrides/__pycache__/XApp.cpython-36.pyc
```

**Comment by eli-schwartz** [comment] 2017-12-26 16:26
I can do that, sure. The former maintainer isn't active and the person who was building Cinnamon doesn't actually use it, so things were a bit iffy.

But it would really help if I could find a changelog for xapps, or in some way know that adding a makedepends on python-gobject would automagically install this file. (It would also be nice if a file that declares itself as necessary for both python2 and python3 would install both versions in one installation command, rather than requiring you to configure two separate copies of the xapps source tree, just in order to `install -Dm644 ...` a single file.)

**Comment by melmelissa** [comment] 2017-12-26 16:40
absolutely nothing in the xsession-errors, this is the first place I searched.
as if the bug did not exist, no trace anywhere, I do not understand absolutely.

I do not question our maintainer of the package, a bad packaging can happen, the error is human, but it is since version 3.6 that there is this regression.
compatibility problem with another element?
there was for example the problem with cjs 3.4 for cinnamon 3.4 which had been solved for Linux Mint but under Arch, I had and I still have problems with this package, hence the downgrade to cjs 3.2 for cinnamon 3.4 .

I am ready to compile myself cinnamon to do tests on my pc, but I am convinced that the problem does not come from the maintainer of Arch, but of any incompatibility with another package, or so I am really cursed!!!!!

**Comment by leigh123linux** [comment] 2017-12-26 17:00
@eli-schwartz I used this for the fedora packaging

http://pkgs.fedoraproject.org/cgit/rpms/xapps.git/commit/?id=e57eb07d1a22375c10e1bb7a408486753c2afb89

And what requires them (hopefully correct).

```
	python2-xapps-overrides(x86-64) is needed by (installed) cinnamon-3.6.7-1.fc28.x86_64
	python3-xapps-overrides(x86-64) is needed by (installed) cinnamon-screensaver-3.6.1-2.fc28.x86_64
	python3-xapps-overrides(x86-64) is needed by (installed) xviewer-plugins-1.2.0-5.fc28.x86_64
	python3-xapps-overrides(x86-64) = 1.0.4-13.fc28 is needed by (installed) xapps-1.0.4-13.fc28.x86_64
	python3-xapps-overrides(x86-64) is needed by (installed) cinnamon-3.6.7-1.fc28.x86_64
```

**Comment by leigh123linux** [comment] 2017-12-26 17:05
@melmelissa No xsession-errors logging IMO indicates a lightdm or X issue, can you post the logs for /var/log/lightdm/lightdm.log and /var/log/lightdm/seat0-greeter.log and  /var/log/lightdm/x-0.log
Also post /var/log/Xorg.0.log

**Comment by eli-schwartz** [comment] 2017-12-26 17:24
Confirmed on the Arch bugtracker that @melmelissa can start Cinnamon via startx.

re: xapps, that's basically what I did, it just seems rather frustrating to do. (Granted that you use autohell, is there no way to make this streamlined?) Though FWIW no need to copy files around, just `cd build-py2; ../xapps-$pkgver/configure; cd ../build-py2; ../xapps-$pkgver/configure`.

We could fix this more systematically if you could ensure that Cinnamon and its components always have good documentation on building, rather than having no documentation or changelogs except buried in the buildscripts for various distros...

**Comment by melmelissa** [comment] 2017-12-26 17:35
here are the 4 logs requested
 https://pastebin.com/raw/KtehnKEPdemandés
https://pastebin.com/raw/1Zs7f5a1
https://pastebin.com/raw/wwmjM1Cy
https://pastebin.com/raw/APQL4L0Y

and I also have this bug (see screenshot)
http://pix.toile-libre.org/upload/original/1514309481.png

the drop-down menu does not go to the bottom of the menu, yet this same theme works well under Cinnamon 3.4
I downloaded it via the cinnamon menu and updated it via the themes menu.
I am the only one to have this problem :(

**Comment by melmelissa** [comment] 2017-12-26 21:15
for the menu I found a solution in the meantime.
remove the original menu and replace it with the Cinnamenu applet (under test to see if the problem reappears)
https://www.pixenli.com/image/Qkf5gfC7

pending a response from you for the logs provided previously

**Comment by melmelissa** [comment] 2017-12-27 07:47
new crash by starting the pc this morning
with or without lightdm, the problem is the same.

you have log reports, if it interests someone, all the better, if not too bad.

in the meantime I downgrade again in version 3.4.

I think this version 3.6 will never be usable on my pc.
I give as much info as I can, but without help from anyone I can not guess what's going on, it's not me who is creating cinnamon ..........

it annoys me because Cinnamon is my favorite environment.
but I obviously have no luck on github, never got help in the long run, in short it is a detail .....

Thanks to @ eli-schwartz, thank you for your involvement in the ArchLinux project, and your answer on Arch's bugreport, good luck.

**Comment by leigh123linux** [comment] 2017-12-27 07:55
@melmelissa The logging didn't show the error/issue

**Comment by melmelissa** [comment] 2017-12-27 08:07
yes I know, this is what I tell you since yesterday, even if it sounds crazy, in the eyes of the system, there are no crashes, yet I have ......

what do we concretely do ?????

I'm the only one on Earth to have this bug ???
it's impossible

I can say goodbye to Cinnamon on Archlinux ???

I do not intend to remain stuck on version 3.4 all my life, it will be necessary to think one day to take into account ALL BUGS.
some are satisfied (good for them) but others would like to find a functional Cinnamon and have this recurring regression ...

it would be cool to investigate anyway .....
it's you developers, it's not me

it's not my first bug report, (probably not my last, I do not believe in miracles) so if someone could take a serious interest in it, I'm very interested but really ....

**Comment by melmelissa** [comment] 2017-12-27 08:25
nobody answers questions ......
in fact you just tell me what I already know .....
the logs do not provide any info ......
but there are these bugs (well present and well anchored) in this version 3.6

the bug fixes are just that, yet I'm talking about walls it looks like ....
if you want ALL your users to be satisfied, ALL of them listen and help them.
because at this rate, the next update, I could not start my pc at all, maybe (I know, it's not your pc, at worst it does not matter)

because by ignoring those who have had trouble for weeks (even months) it's no wonder that at one time we harass people to have REAL HELP and not tell us what we've already known for days ..

I see new versions (owl !!!!!!!!), thinking that they will correct the problems (false hope !!!!!!!!!!)
ha bah yes it fixes bugs, but it creates others (and which are unique in the world in +)
"" too loud "", I have no other words that come to my mind ....

unusual things make me smile in life, but there .............

**Comment by leigh123linux** [comment] 2017-12-27 09:20
@melmelissa my only issue with archlinux is the lack of debug symbols.

> Cinnamon crashes when booting the pc, after Lightdm loading (version 1.24.0-3)
> despite my research, no trace of the crash in question (neither in the logs, nor in dmesg ...)
> I changed the theme, icons, wallpaper, but the problem persists, even with the default theme ...
> 
> easily reproducible.
> Starting and restarting the PC is enough to crash Cinnamon.

If it works using startx then your issue is in lightdm or elsewhere.

> but there are these bugs (well present and well anchored) in this version 3.6

I haven't seen any thing at bugzilla or here to back up your claim.

> if you want ALL your users to be satisfied, ALL of them listen and help them

Maybe archlinx should provide a couple of Dev's to hang here and answer/fix issues.

> or you have a problem with ArchLinux users, or with women ... which would explain this (this silence and this lack of recurrent help) ... !!!!!!!!

Ignore me as I hate almost everyone and everything.

My most disliked/hate list (in reverse order) 

1. People. (least disliked)
2. Archlinux users.
3. Windows users.
4. BSD users.
5. Police.
6. Taxi Drivers.
7. Pedophiles.
8. Politicians. (most disliked)



@eli-schwartz  

> Confirmed on the Arch bugtracker that @melmelissa can start Cinnamon via startx.

**Comment by melmelissa** [comment] 2017-12-27 10:01
yesterday it worked with startx (with @eli-schwartz  we thought to have found the cause of the problem), but that was yesterday, since today with or without lightdm, the crash takes place from the start .. (I made 20 reboots and boots, the bug is easily reproducible)

the menu applet exploded, you have the proof via my screenshot posted above.
I do not invent these bugs anyway ???

and it does not come from my installation of ArchLinux otherwise I would have other bugs, which is not the case

and it does not come from my pc, otherwise I would have Debian problems, which is not the case.

it only crash with Cinnamon 3.6 .....
and I'm not questioning Arch's maintainer's job, if he was the culprit, we'd be hundreds to complain about the same bug, which is not the case.

so the problem comes from version 3.6, sorry, I'm not a medium but it's just logical.
and as long as the problem is not solved, I will still have bugs despite the updates ...

as I said, you are the developers of Cinnamon, you are in the best position to know where it comes from, or there is a serious problem ...
I am a simple user who goes back the bugs but who would go well, and who would like to have a Cinnamon 3.6 as stable as 3.4.

**Comment by leigh123linux** [comment] 2017-12-27 10:36
post

```
journalctl -b0 >> boot.txt
```

**Comment by melmelissa** [comment] 2017-12-27 12:43
here is the log
https://pastebin.com/raw/HiPX8mh2
nothing very relevant

**Comment by jaszhix** [comment] 2017-12-27 13:47
Can you try to run `cinnamon --replace`, then try to reproduce the issue? That should give you the output from what would be in ~/.xsession_errors. Afterwards open a new terminal and run `cinnamon --replace &` to move cinnamon back to the background, and copy the output from the other terminal to a new file for attaching here.

**Comment by eli-schwartz** [comment] 2017-12-27 13:58
> @melmelissa my only issue with archlinux is the lack of debug symbols.

I have that issue too! :grinning:
(Our repository management scripts cannot currently handle splitting out debug packages into a separate debug repo. This is something a few people are annoyed by, but no one has gotten around to fixing it. :frowning_face:)

> Maybe archlinx should provide a couple of Dev's to hangout here and answer/fix issues.

Unlikely. But I can offer on my own to provide one, at least. Please feel free to @ mention me on any issues that impact Arch users for any cinnamon related packages, so I am at least aware of the issue. Or generally communicate with me for any issue/fact you think I as a cinnamon distro packager should be aware of. If you need to, you can find a couple methods of contacting me outside of GitHub, [here](https://www.archlinux.org/people/trusted-users/#eschwartz).

**Comment by melmelissa** [comment] 2017-12-27 14:53
@jaszhix
that's what I get
https://pastebin.com/raw/4tUz2hqf
again, it does not sound good :/ :/

@eli-schwartz
I hope that someday there will be change on this point.
the problems under Archlinux are not frequent, but when they arrive, we find ourselves a little blocked, except when it is a bug known by several people, it changes everything.
my current bug seems to be unique, and i'm really an isolated case, i think :( :(

and personally I do not understand why ..
I do not understand what is happening with this version 3.6 on my pc, until now everything was fine, and I'm running out of ideas :( :(

thank you for your involvement.
I would like so much to find this calm :| :| 
and do not annoy everyone with this weird problem

**Comment by melmelissa** [comment] 2017-12-27 18:15
the rest of the operations, what is it ???
what do we do??

**Comment by melmelissa** [comment] 2017-12-27 19:41
@jaszhix 
the rest of the operations, what is it ???
What do we do now ??
......

**Comment by melmelissa** [comment] 2017-12-27 20:02
we are far from finding the source of the problem ....

anyway I do not have any illusions, I know very well that this bug report will not correct my problem and that I am condemned all the time to downgrade to Cinnamon 3.4.
no problem it's not your pc, we do not care.

it's crazy to ignore the bug reports you get.
in addition to not trying to seriously explore the problem, we make a bug report that ultimately is useless, since everything you asked me, I already know, since I tell you that there is no trace of bugs in question, but apparently no one believes me, I'm blonde but not stupid.
I can still read a log correctly.

rather than useless theory, so do something serious, I would at least feel like wasting time for nothing ....
because not wanting to recognize that the problem comes from you, it gives this current situation, a deaf dialogue, a waste of time and of course no problem solving ...
when we see all open bug reports without answer, that says a lot .........
short is not with you that I have a real answer, I think I'll rather see the side of the international forum of ArchLinux, they at least offer tracks other than reading an empty log of interest.

tired of wasting time for months to tell you that some people have fucking bugs, and that they are waiting for a REAL CORRECTION.

the "" solidarity "" American version is very different from us French ...
CQFD

**Comment by jaszhix** [comment] 2017-12-27 20:22
This bug report has only been open for one day, and you have already received more responses than average I think. At this point to me it looks like either a graphics driver issue, or something else related to the C bindings which will require debug symbols.

> tired of wasting time for months to tell you that some people have fucking bugs, and that they are waiting for a REAL CORRECTION.

Nobody's going to fix a bug within 24 hours of you reporting it. I don't think that's an appropriate tone..

**Comment by melmelissa** [comment] 2017-12-27 21:24
except that version 3.6 is buggy since its release.
there was the bug in the menu applet when we clicked on it that made Cinnamon crash, it was corrected, miracle.

version 3.4 of cjs which is still not corrected for Archlinux today, for proof, I still have to use version 3.2 with Cinnamon 3.4, it's normal ???
however, I've put this bug back to you already.

the current crash bug at boot - reboot.
the bug of the menu completely exploded.
and tomorrow what will it be?
a bug with Nemo, like there has never been before, it will not be long, just to vary the pleasures ....
no, but seriously .... it's delirium ...

the bugs are piling up but nobody is doing anything, yet I'm putting them back to you huh, I'm breaking my head writing in English while I'm French, hoping to get an answer filled with common sense, but nada.

you think???? indeed, you only think .... and it is all there the problem ... to think without acting, it is useless ....

receive as many answers to ask me things that I already told you, that there were no traces of bugs in the logs, I do not see the interest at all.
it is to make me wait by making me believe that you are really interested in my bug ??

you have a serious problem with Archlinux users it's not possible ...
three times that I go back bugs, three times that indirectly makes me understand to annoy me.

the tone I use is not appropriate ???
 maybe, or not ???
Honestly, I do not care.

because I know that you will NEVER fix this bug, and that I will have another 100 that will annoy me.

when I have a problem, I would ask the maintainer of Arch who deals with Cinnamon if the bug is known, at least it offers me solutions.
but surely not that I would come back here.
for me to go round in circles asking me what I already said in the first message, it is useless, and it shows incompetence on your part.

you develop Cinnamon and you are unable to know the cause of the crash, it is serious, you test at least before proposing it ??
I wonder now ...
you send the source code and each one his crap.

I hope Debian Sid will stay a long time on version 3.4 of Cinnamon.

allez hop basta ciao

**Comment by leigh123linux** [comment] 2017-12-27 21:34
@melmelissa It looks like there is a commit that will fix the critical warnings but it wont fix your issue.

https://github.com/linuxmint/Cinnamon/pull/6931

> it's crazy to ignore the bug reports you get.
> in addition to not trying to seriously explore the problem, we make a bug report that ultimately is useless, since everything you asked me, I already know, since I tell you that there is no trace of bugs in question, 

Without error logging there isn't anything to fix here or even assign blame.
Even @eli-schwartz can't reproduce the issue with 3.6 on archlinux so it looks like something isn't right on your install

**Comment by melmelissa** [comment] 2017-12-27 21:50
ha bugs will be repaired ??
well, it's going to add a little layer.
cool, new bugs in perspective for me, thank you for Christmas gift.

and I am at fault that there is no logging of errors ???
no, then ???

my pc is fine, thank you for worrying for him, with cinnamon 3.4 everything rolls, but not with 3.6 ...
Why???
I ask you constantly ..
and you answer me what ???
NOTHING AT ALL...
ha that things I already know ...
I feel like I hear a looping speech.

when there is something interesting, maybe I can keep my cool ..
3 months to support bugs, to report them, but to have no correction, it is much, much too much.
my tolerance level has just dropped extremely low ..

for now I just feel like talking to walls, and that's the case in reality, it's a drama .....

eli-schwatz does not have the same pc as me.
and we all know that from one pc to another, the problems are varied.
but a Cinnamon crash at startup is pure delirium ..

as crazy as microsoft windows

**Comment by leigh123linux** [comment] 2017-12-27 21:53
Closed

**Closed by leigh123linux** 2017-12-27 21:53 UTC
