### ISSUE TITLE
Lockups with Cinnamon 3.2.1 (betsy)

### ISSUE THREAD

**Issue by gwvr** [linuxmint/Cinnamon#5965] opened 2016-11-15 12:16 UTC
I've experienced several "lockups" since updating to Cinnamon 3.2.1+betsy. My system had previously run Cinnamon reliably for many months.
Symptoms are Cinnamon and applications becoming unresponsive, with the exception of the mouse pointer still moving with the mouse. I have been able to Ctrl+Alt+F1 to a terminal and reboot. Unfortunately I don't have a copy of the relevant ~/.cinnamon/glass.log - it was overwritten on reboot. I'll attempt to restart Cinnamon with Alt+F2 & r next time, and will try to save the log prior to reboot too.

**Comment by mtwebster** [comment] 2016-11-15 12:36
This is likely caused by cinnamon screensaver - the fix for it was committed last night, you should see a point release for it today or tomorrow.  In the meantime, if possible, disable the screensaver to prevent this.

**Comment by gwvr** [comment] 2016-11-15 12:42
Thanks @mtwebster , that makes sense
I think I've disabled the screensaver (the language in the dialog is a bit ambiguous now). I'll re-enable it when the updates come through, and report back if the issue re-occurs.

![screensaver](https://cloud.githubusercontent.com/assets/2746263/20306060/7f41e34c-ab30-11e6-9535-d2fc9d12ac63.png)

**Comment by gwvr** [comment] 2016-11-17 17:38
I've updated to
> cinnamon:amd64/betsy 3.2.1+betsy
> cinnamon-screensaver:all/betsy 3.2.3+betsy

and re-enabled the screensaver, but just experienced another lockup.

Apologies, but I didn't have time to check the log - I was in a conference call and had to reboot fast.

**Comment by mtwebster** [comment] 2016-11-17 17:48
Make sure you've restarted the screensaver (it runs in the background, even with locking disabled) - log out and back in.

**Comment by gwvr** [comment] 2016-11-17 20:20
I've updated to
> cinnamon:amd64/betsy 3.2.1+betsy
> cinnamon-screensaver:all/betsy 3.2.3+betsy

and re-enabled the screensaver, but just experienced another lockup.

Apologies, but I didn't have time to check the log - I was in a conference call and had to reboot fast.

**Comment by JosephMcc** [comment] 2016-11-21 18:57
@gwvr Did you test this again after being sure you restarted the screensaver as @mtwebster suggested?

**Comment by gwvr** [comment] 2016-11-21 19:47
I have, and I haven't been able to reproduce this bug.

**Comment by JosephMcc** [comment] 2016-11-21 19:50
Thanks, I'm going to close it then.

**Closed** 2016-11-21 20:48 UTC
