### ISSUE TITLE
[BUG] St.ScrollView invisibly extends outside of menu applet.

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon#11123] opened 2022-08-30 01:40 UTC
```
 * Cinnamon version 5.4.11 daily builds PPA Mint 21
 
 * No errors in .xsession-errors
 ```

### Issue
Since 5.4.11 (possibly also 5.4.10 but I don't think so, not in Manjaro at least) the otherwise hidden part of St.ScrollView is invisibly extending outside of the menu applet (also in Cinnamenu applet) such that if you move the mouse pointer above (or below if menu is on top panel) the menu applet, names & descriptions of invisible apps still show in the menu (and tooltips show in Cinnamenu) and the apps are clickable and can be opened.

**Comment by fredcw** [comment] 2022-09-11 08:35
Problem seems to have disappeared in cinnamon 5.4.12

**Comment by fredcw** [comment] 2022-09-11 15:31
Sorry, just tested again, the problem is still there. Mint 21 & Mint 21 daily PPA.

**Comment by mfreeman72** [comment] 2022-12-21 07:08
This bug is still present in Cinnamon 5.6.5 in Linux Mint 21.1. It causes a lot of problems, as I tend to habitually click the area just below the menu (I use a panel at the top of the screen). I'm constantly accidentally opening a program, because the application links extend beyond the boundaries of the menu.

**Comment by njdf18** [comment] 2023-01-13 16:50
I found this bug, too.

I record a gif and posted it on Reddit.
https://www.reddit.com/r/linuxmint/comments/109rk1e/a_bug_when_the_panel_with_cinnamenu_and_menu_is/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by mfreeman72** [comment] 2023-01-13 20:19
Yep. Still present in Cinnamon 5.6.6.

**Comment by mfreeman72** [comment] 2023-01-17 06:28
Also still in Cinnamon 5.6.7.

**Comment by mfreeman72** [comment] 2023-03-16 17:14
Still in Cinnamon 5.6.8. I hope this gets some attention sometime soon. It's an extremely frustrating bug!

**Comment by mtwebster** [comment] 2023-03-16 17:39
It's gotten lots of attention. Unfortunately it's an elusive bug.

**Comment by mfreeman72** [comment] 2023-03-16 17:44
Awesome! Thank you for the info. I just hadn't seen any response to this yet.

**Comment by rcalixte** [comment] 2023-11-10 23:57
I was digging into troubleshooting this and it appears to be more than just the Menu applet. I tested with the Notifications applet and I was able to reproduce clicking beyond the boundary but having the click captured by the list of objects being drawn.

**Comment by mfreeman72** [comment] 2024-06-17 18:37
Any chance this will be fixed in the upcoming Cinnamon 6.2 release for Mint 22? For now, my workaround is to make the menu the full height of the screen, which isn't ideal, but it prevents the mouse from getting to the applications outside the menu area.

**Comment by rcalixte** [comment] 2024-06-17 18:40
> Any chance this will be fixed in the upcoming Cinnamon 6.2 release for Mint 22? For now, my workaround is to make the menu the full height of the screen, which isn't ideal, but it prevents the mouse from getting to the applications outside the menu area.

It is still something that will take a bit of dedicated time to figure out. From what I can gather, it was likely something that was introduced in Cinnamon 5.4 and is likely a bug in the St or Clutter libraries. Assuming this hunch is correct, a lot of commits and C code would need to be traced to try to determine the source of the bug. Someone needs to spend this time though.

**Comment by DokterKaj** [comment] 2024-07-20 03:02
[Issue #2522 from the GNOME Shell repo](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2522) provides a workaround: setting the `clip_to_allocation` flag to true, which is set to false by default according to [Clutter docs](https://gnome.pages.gitlab.gnome.org/mutter/clutter/property.Actor.clip-to-allocation.html). Can somebody try this?

**Comment by DokterKaj** [comment] 2024-07-20 04:04
Just tested the fix on Cinnamenu@json and it now works as intended. However, would it be possible to somehow set the flag to true by default within the Cinnamon shell? That way the fix should apply to all applets by default, instead of applets having to apply the fix individually.

**Comment by rcalixte** [comment] 2024-07-20 05:31
Phenomenal find! I've confirmed that this property does resolve the issue. I'm not sure if it should be defaulted at the toolkit level or if we just need to patch `St.ScrollView` objects that have the capacity to extend beyond the screen. After a cursory look through the code for both, I think patching at the toolkit level might be trickier (there are some conditional blocks based on this exact property and possible unintended side effects elsewhere since I don't fully understand the scope of those).

The even trickier part is finding all of the areas that need to be patched and patching them. This doesn't need to be applied to every single instance of `St.ScrollView`, just the ones that are potentially unbounded (like the notification tray or menu applets). Now that we have a working remedy, at the very least, we can resolve it if we ever see it again. Thank you!

**Closed** 2024-07-20 09:22 UTC

**Comment by fredcw** [comment] 2024-07-20 12:05
I've added a PR #12298 that reverts a drag & drop workaround I added due to this bug and which can now be reverted.
