### ISSUE TITLE
Connect/Disconnect button in Network Settings

### ISSUE THREAD

**Issue by Ocelot92** [linuxmint/cinnamon#4670] opened 2015-10-02 16:51 UTC
OS: Linux Mint 17.2 Cinnamon 64 bit 3.19.0-28 
Hi everyone, whenever i'm connected to a wifi network if i open the network settings (the one in System Settings) the button to connect doesn't change into disconnect (the black square). It just remains with the Play icon and if i click on it the Mint disconnect and reconnect to the wifi.
![screen](https://cloud.githubusercontent.com/assets/9950484/10252239/8377ed04-6936-11e5-8c33-7ef2d9561e0b.jpg)

**Comment by Vahan86** [comment] 2016-11-27 18:08
It works fine for me. Cinnamon version 3.0.7.
@Ocelot92, is this still an issue for you with Cinnamon 3?

![55](https://cloud.githubusercontent.com/assets/12819058/20650690/0c3fb71c-b4ee-11e6-9faf-0992ae06497d.png)

**Comment by Ocelot92** [comment] 2016-11-27 20:35
@Vahan86 Sorry  but i'm unable to verify it because I haven't Cinnamon installed at the moment.

**Comment by germanfr** [comment] 2016-11-28 19:04
This have just happened to me on Cinnamon 3.2.1. It happens sometimes.
![screenshot from 2016-11-28 19-49-30](https://cloud.githubusercontent.com/assets/10391266/20681825/98cc9ae4-b5a5-11e6-90a6-6cfcbc2d88a2.png)

I turned on wifi and connected to it through the applet while network settings was opening.

**Comment by JosephMcc** [comment] 2016-11-28 19:58
Ok. I tried to reproduce it like that and still can't. From your description I thought maybe it wasn't catching some changes that were happening but it seems to be working ok here.

**Comment by icarter09** [comment] 2021-05-17 16:53
The UI design and functionality of the Network settings has changed since this ticket was originally created. Closing this issue since it no longer applies.

**Closed by icarter09** 2021-05-17 16:53 UTC
Labels: BUG
