### ISSUE TITLE
Computer does not suspend when power is unplugged while lid is closed

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/cinnamon#4689] opened 2015-10-08 16:14 UTC
I have power management set up to suspend the PC automatically when the lid is closed with no A/C. (For lid closed with A/C, I selected "Do nothing" because I frequently use my machine with an external screen.) When I now unplug the power while the lid is closed (e.g., because I'm leaving some place where I have an external screen), I expect the computer to suspend: It is now without A/C with the lid closed.
However, instead, nothing happens. That's bad, I have to be extra careful not to put the machine in the bag without it being in suspend.

**Comment by InAnimaTe** [comment] 2016-05-04 20:16
YUPPPP.....

So I basically just cooked my laptop for about 1.5 hrs during a trip I took yesterday. I had my laptop closed, which meant standby (which it properly seemed to be in). I then unplugged and put it in my bag.

Got to my destination and my machine was basically ready for cooking an egg. Here are my power management settings:

![screenshot from 2016-05-04 16-15-00](https://cloud.githubusercontent.com/assets/1192726/15027769/5e01bdee-1213-11e6-8c78-3390877100ae.png)

I'm going to do some more testing at some point to make sure that is actually what happened (and not some other glitch). i'll respond back. Either way, this is pretty much a critical bug which needs to be fixed ASAP.

**Comment by keitalbame** [comment] 2016-05-08 15:02
Do you have issues suspending while the closing the lid, on AC or battery?
Like on #4919

**Comment by InAnimaTe** [comment] 2016-05-08 18:27
So here are my findings:

When plugged in and closing the lid (without anything connected i.e. hdd, monitor, etc..):

* The computer does go to standby
* The computer then wakes back up after so many seconds

So at this point the computer is plugged in and awake.
If I pull the power cord, it does seem to stay in standby meaning my previous reasoning may be false. 

Basically, standby seems wonky whilst the machine is plugged in, but seems to work as intended without power connected.

**Comment by Vahan86** [comment] 2018-02-19 19:40
@RalfJung, is this still an issue under Cinnamon 3.6?

**Comment by RalfJung** [comment] 2018-02-19 21:51
I'm not using Cinnamon any more, sorry.

**Comment by Vahan86** [comment] 2019-12-03 17:33
@icarter09, can we close this issue?

**Closed** 2019-12-03 17:35 UTC
Labels: BUG
