### ISSUE TITLE
Cinnamon Panel Remains During Full Screen Video When Dock Is Used

### ISSUE THREAD

**Issue by annoyingduck** [linuxmint/Cinnamon#7573] opened 2018-05-11 16:06 UTC
```
 * Cinnamon version 3.8.2
 * Distribution - Arch Linux
 * Intel i5 and Intel Graphics & Driver
 * 64 bit
 ```

**Issue**
After recent Cinnamon/system update if any dock program is used (Cairo, Plank), enabling a video in fullscreen mode still shows the panel (panel is not hidden, it's overlaid on top of the fullscreen video).  Happens with all media players and web based videos. Shutting down the dock fixes the issue and fullscreen videos work as they should.

**Steps to reproduce**
Have a dock running.  Play a video and enable fullscreen.  The panel still shows.  Close (shutdown) the dock, play a video, enable fullscreen, and the panel disappears as it should.

**Expected behaviour**

**Other information**
This just started happening this past week with Arch's updates. Not sure if it's Arch or Cinnamon related, but it's only happening w/Cinnamon on 2 of my computers.  It's not happening with Arch & XFCE.  Cairo dock is my dock of choice, but I tested with Plank and the issue is present with Plank running as well.

**Comment by itzexor** [comment] 2018-05-11 16:42
This should be fixed in the next muffin point release.

Duplicate of https://github.com/linuxmint/muffin/issues/320

**Closed by itzexor** 2018-05-11 16:42 UTC
