### ISSUE TITLE
Missing animations on some menus

### ISSUE THREAD

**Issue by MorbidShell** [linuxmint/cinnamon#12259] opened 2024-06-28 15:27 UTC
### Distribution

Fedora 40 

### Package version

6.2.2

### Graphics hardware in use

Radeon RX 7900 XTX

### Frequency

Always

### Bug description

This is the same bug I reported here #10983  

### Steps to reproduce
Open up Nemo (or other Cinnamon/Xapp) and hit the Files or Edit, and observe the (lack of) animation.

### Expected behavior
That said menus are animated.

**Comment by JosephMcc** [comment] 2024-06-30 22:36
This is not a bug. It's the intended behavior. Animations get messy with these since hovering over items in the menubar will constantly open and close theme. Closing this as a won't fix/not planned.

**Closed by JosephMcc** 2024-06-30 22:36 UTC
Labels: BUG

**Comment by mfreeman72** [comment] 2024-07-01 19:37
@JosephMcc Are you talking about the smooth open/close menu animations that used to be present in Cinnamon application windows? I really miss them. Those being missing in newer versions of Cinnamon is intended?! They were so beautiful, and never cause a problem that I ever saw, until they were just inexplicably gone after an update several years ago. I was hoping they would make their return someday. It seems like Cinnamon has been removing a lot of its beauty-focused extras that used to exist over the last 5+ years. I get why if there were underlying bugs, though. I just miss these quality of life/eye candy features a lot.

**Comment by JosephMcc** [comment] 2024-07-01 19:51
I'm totally fan of animations when used correctly. I actually implemented the ones you are talking about. However, these did not look good in some cases and in fact looked worse then not having them. So while I actually implemented them, I was also a proponent of removing them when they were removed.

> It seems like Cinnamon has been removing a lot of its beauty-focused extras that used to exist over the last 5+ years

Such as? Outside of this obviously. Seems some things have changed but maybe not removed.

**Comment by mfreeman72** [comment] 2024-07-01 20:25
> I'm totally fan of animations when used correctly. I actually implemented the ones you are talking about. However, these did not look good in some cases and in fact looked worse then not having them. So while I actually implemented them, I was also a proponent of removing them when they were removed.

I never saw anything wrong with them at all, and loved how they looked much more than the way things work currently.
 
> > It seems like Cinnamon has been removing a lot of its beauty-focused extras that used to exist over the last 5+ years
> 
> Such as? Outside of this obviously. Seems some things have changed but maybe not removed.

For example: Cinnamon used to have an optional feature that would replace the system tray icon menus with a menu that was themed like the rest of the panel applets. That was removed because it caused problems for some users, which is totally understandable, although I never had any problems with it. But still, it's annoying to now be force into the situation where applet menus dropping from the panel are themed nicely to the panel theme, and system tray icons sitting next to them on the same panel are not. It just looks bad.

Another example: Window theming was changed, which removed the ability to independently theme window widgets (aka window controls, such as the - + x icons that minimize, maximize, or close the windows). Window widgets now follow the icon theme, and cannot be changed separately to match the window theme again. So if I like the application/file icons of one theme, and the window theme of another, then the window widgets have to look badly out of place, with no way to fix it.

Another example: I used to be able to configure how panel menu clicking behaved. Now, the only option available is to click-to-open, click-to-close, and you have to click-to-close on applet before clicking-to-open another one, which imposes way too many clicks on users. We used to have at least one or two other options, but this was removed. For example, I used to be able to set it so that I can click-to-open one applet, move the mouse to another applet, and when I click on it, the previous applet would close AND the new applet would open, which would save the extra click. I'd also love to see the option of having it work like window menus do, so that you click-to-open one panel applet, and sliding the mouse over to another without clicking closes the first applet and opens the next. After this functionality was removed, I then found an extension that replaced this functionality for quite a while, but that extension stopped being developed, and Cinnamon 6.x became incompatible with it. So now I'm stuck with terrible applet menu handling. I would love to have those options back. It's an accessibility issue for some of us, such as people with arthritis or those prone to carpel tunnel problems.

Anyway, this is getting way off-topic, so I'll leave it at that. But those are just a hand full of things that have been removed from Cinnamon over the years. That said, there have also been some great things done with Cinnamon, too, which keeps me using this desktop! I just wish I could get some of those older functions back, too, to make Cinnamon even better.
