### ISSUE TITLE
Maximus doesn`t work with Cinnamon.

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/Cinnamon#5764] opened 2016-10-05 21:16 UTC
Cinnamon 3.0.7

Maximus application doesn`t work correctly. 
When window is maximized - it dissapears. Right click on icon button in window buttons applet - "unmaximize" - make it visible again.

It affects not all applications, but many (webbrowsers, Gimp, Inscape...). Some, Like Nemo, work well (headbar removed when maximized)

I noticed this bug in Mint 17.3
I use pannel on top with global menu applet and window buttons (close, maximize, minimize) applet. So with help of Maximus (undecorated maximized window) I used to make my Cinnamon act like Unity desktop... I just like to use my desktop space in rational way. 

Sadly, but there is no option in Cinnamon Settings "undecorate maximized windows" like MATE and XFCE have.. So only one solution - use Maximus app.

P.S. Cinnamon-maximus applet from cinnamon applets list doen`t work too (can`t be installed).

**Comment by Odyseus** [comment] 2016-10-05 22:22
Hello, @alxgvr.

This is not a Cinnamon issue. Maximus extensions doesn't even work right on Gnome Shell either.

> When window is maximized - it dissapears. Right click on icon button in window buttons applet - "unmaximize" - make it visible again.

This is a known issue of all Maximus extensions, among several others. When it happens, just restart Cinnamon and the *invisible* window will re-appear.

If you want to undecorate **all** maximized windows without exceptions, you don't need Maximus at all. You can just edit your metacity theme to remove decorations of all maximized windows ([here are detailed instructions](http://www.webupd8.org/2011/05/how-to-remove-maximized-windows.html)). Is infinitely less buggy than using an extension to programmatically remove decorations.

**Comment by alxgvr** [comment] 2016-10-06 21:46
Thanks, but here described for Gnome. Can I do same for Cinnamon? I need to
edit theme I currently using? I tried with Adapta, but it didn't work.

6 окт. 2016 г. 1:22 пользователь "Odyseus" <notifications@github.com>
написал:

**Comment by Odyseus** [comment] 2016-10-07 02:12
Hello, @alxgvr.

> Thanks, but here described for Gnome. Can I do same for Cinnamon?

For all intent and purposes, when talking about window borders themes, Gnome Shell and Cinnamon are exactly the same (mostly).

> I need to edit theme I currently using?

You can edit any theme that has a metacity theme.

> I tried with Adapta, but it didn't work.

You are editing the window borders theme. Did you changed the theme in **Cinnamon Settings** > **Themes** > **Window borders**? If you are editing a theme that you are currently using, first you need to switch to another window border theme, and then switch back to the one that you edited. I just tried with the Adapta theme and it worked as expected.

Also, you should take into account that some themes may name that element differently.

- name="max"
- name="maximized"
- name="normal_max"
- name="normal_maximized"

**Comment by JosephMcc** [comment] 2016-10-07 02:48
> For all intent and purposes, when talking about window borders themes, Gnome Shell and Cinnamon are exactly the same (mostly).

I didn't look at the tutorial you pointed to and I assume it's for an older version of gnome shell. Shell hasn't used used metacity themes at all for quite some time now. All theming is pulled directly from the gtk theme.

**Comment by Odyseus** [comment] 2016-10-07 03:57
Hello, @JosephMcc.

Yes, it is a tutorial that I found inside the Maximus extension comments and was last updated on December 2011. Since then, Gnome Shell was stabbed a thousands times with *new features*. That's why at the end of the sentence I added the word **mostly**. I didn't want to enter in details. Mostly because I myself can barely understand it.

**Comment by leigh123linux** [comment] 2016-10-07 07:16
I see this as a maximus issue, the code hasn't been kept up to date with modern DE's.

https://launchpad.net/maximus

https://bugs.launchpad.net/maximus/+bug/1628321

**Comment by alxgvr** [comment] 2016-10-07 21:02
@leigh123linux  yeh, that`s me created that issue on launchpad :)

**Comment by alxgvr** [comment] 2016-10-07 21:16
@leigh123linux  yeh, that`s me created that issue on launchpad :)

@Odyseus top bar still there... it is tilny, but it still there 
![screenshot from 2016-10-08 00-13-59](https://cloud.githubusercontent.com/assets/19569543/19205645/65ef9a40-8cec-11e6-900e-4c0d514ea70a.png)

**Comment by Odyseus** [comment] 2016-10-07 21:25
> top bar still there... it is tilny, but it still there 

That's most likely the result of not setting the attribute **has_title** to **false**.

**Comment by JosephMcc** [comment] 2016-10-07 22:00
That application hasn't been updated in years. I'm closing this as a Cinnamon issue. It doesn't stop you from adding new posts to it if @Odyseus is continuing to help you figure out a workaround.

**Closed by JosephMcc** 2016-10-07 22:00 UTC
Labels: BUG

**Comment by alxgvr** [comment] 2016-10-08 20:29
Sorry, but it doesn't work with Mint-Y theme. Edited both metacity-2 and
metacity-3 files, but have no effect. With Ambiance worked well.

8 окт. 2016 г. 1:00 пользователь "JosephMcc" <notifications@github.com>
написал:

**Comment by Odyseus** [comment] 2016-10-08 22:03
Hello, @alxgvr.

Yes, the **Mint-Y** theme is an entire different beast. Just edit the **metacity-theme-3.xml** file like follows.
```xml
<frame_geometry name="max" has_title="false" title_scale="medium" parent="normal" rounded_top_left="false" rounded_top_right="false">
	<distance name="right_width" value="0" />
	<distance name="left_titlebar_edge" value="0"/>
	<distance name="right_titlebar_edge" value="0"/>
	<distance name="title_vertical_pad" value="0"/>
	<border name="title_border" left="0" right="0" top="0" bottom="0"/>
	<border name="button_border" left="0" right="0" top="0" bottom="0"/>
	<distance name="bottom_height" value="0" />
	<distance name="button_width" value="0"/>
	<distance name="button_height" value="0"/>
</frame_geometry>
```

I just added the following two lines to make it work with the **Mint-Y** theme:
```xml
<distance name="button_width" value="0"/>
<distance name="button_height" value="0"/>
```

I didn't need to edit the **metacity-theme-2.xml** file but, every system is different. So you may have to.

**Comment by JosephMcc** [comment] 2016-10-08 22:34
Fyi, Cinnamon uses the metacity themes in order of version. If there is a metacity-3, it will use that. Next it will look for metacity-2 and then metacity-1.

**Comment by Odyseus** [comment] 2016-10-08 23:09
Like always, something new can be learn from your comments. Thanks, @JosephMcc.

**Comment by lestcape** [comment] 2016-10-09 03:35
The way of how the Maximum works, is the cause of all issues... a call for x11 from command line that's need to be a crap always. If we add that Muffin, Cinnamon and GdkWindows system won't play good together... Or will be a directo option on cinnamon to update the gdkwindows representation, or simple, won't try to use crap.

**Comment by alxgvr** [comment] 2016-10-12 15:16
This works. Thank you @Odyseus

2016-10-09 6:35 GMT+03:00 Lester Carballo Pérez <notifications@github.com>:
