### ISSUE TITLE
Right-click Menus stuck in place until logoff

### ISSUE THREAD

**Issue by piers109uk** [linuxmint/cinnamon#6550] opened 2017-05-20 10:57 UTC
Apparent bug: Entering panel edit mode and right clicking on a window causes the right-click menu to become fixed in place until log off. This persists after exiting panel edit mode.

I can replicate this issue and have attached screenshots. The only fix I have found is logging off and on again.

These menus are fixed at the front of the screen regardless of the window I pull up (seen in second screenshot). Oddly, one of the fixed menus disappeared and I have no idea why. 

I have also attached the output of inxi -fxr in a text file as was suggested in Linux-help chat.
EDIT: Closing the associated window gets rid of the pop-up menu, which makes this a very non-urgent bug, but a bug nonetheless.

![screenshot from 2017-05-20 11-22-19](https://cloud.githubusercontent.com/assets/28823694/26275178/c8c44078-3d52-11e7-9f1d-e81ca7fd156b.png)

![screenshot from 2017-05-20 11-55-04](https://cloud.githubusercontent.com/assets/28823694/26275193/35e18472-3d53-11e7-98f1-e68f2103805e.png)

[inxi-Fxr.txt](https://github.com/linuxmint/Cinnamon/files/1016088/inxi-Fxr.txt)

**Comment by JosephMcc** [comment] 2017-05-20 15:59
I can't reproduce this in Cinnamon 3.4. What is that thing running in the upper right hand corner?

**Comment by collinss** [comment] 2017-05-20 16:17
I can't reproduce this either. I don't even get that menu in panel edit mode - right click just brings up the standard applet context menu as it's supposed to in panel edit mode.

@JosephMcc are you referring to the devtools desklet, or the system monitor?

**Comment by germanfr** [comment] 2017-05-20 16:18
I can reproduce it since long time ago. But I can close them right-clicking again on each window button.

**Comment by JosephMcc** [comment] 2017-05-20 16:20
@collinss I'm talking about the devtools desklet. Didn't realize that's what it was since it isn't themed like the other cinnamon chrome.

**Comment by piers109uk** [comment] 2017-05-20 17:03
@germanfr Thanks. I'm surprised I hadn't tried right clicking after exiting edit mode before.

I'm on 3.2.7.

Should I close the issue now that there's an easy fix, or left open until the bug itself is fixed?

**Comment by JosephMcc** [comment] 2017-05-20 17:19
You can leave it open. If you plan to upgrade to Mint18.2 with Cinnamon3.4 maybe retest at that point and report back.

**Comment by brownsr** [comment] 2017-06-06 19:02
readily reproducible in Cinnamon 3.4,  just right click to launch the context menu of an applet when edit mode is on.

**Comment by JosephMcc** [comment] 2017-06-06 19:32
> readily reproducible in Cinnamon 3.4, just right click to launch the context menu of an applet when edit mode is on.

Not here it isn't. I can't seem to reproduce the issue in any way. I tried turning on edit mode and then opening the context menus of several different applets and it all worked fine.

**Comment by brownsr** [comment] 2017-06-07 19:33
Ah, retested in less haste - only triggers from window list applet or panel launchers applet.  For panel launchers it triggers both the context menu for the overall applet and the context menu for the specific launcher.  The context menu for the specific launcher gets stuck on. The same happens for the window list applet.

**Comment by brownsr** [comment] 2017-06-09 19:00
@piers109uk This is proving curious.  Some of us can reproduce this, some can't, it may take a while to work out what is behind it.

**Comment by mdchaves** [comment] 2017-06-09 19:18
I can reproduce the issue too (right click to launch the context menu of an applet when edit mode is on).

**Comment by brownsr** [comment] 2017-06-11 07:57
This problem seems to require that 'effects on menus' is turned on - settings/effects/enable effects/effects on menus

**Comment by JosephMcc** [comment] 2017-06-11 08:21
I still can't reproduce this.

>  Also 'overlay scroll bars' also appears to have to be enabled to get this problem, so another workaround is to turn this off.

This actually has no effect on cinnamon elements.

**Comment by itzexor** [comment] 2017-07-21 05:23
I've been investigating this for a bit now, and I believe I have tracked down the issues that combine to cause this to happen.

This bug can be triggered during edit mode for the window list and panel launchers, for the sound applet by pressing mouse left and right at the same time, and any mouse-activated menu if you activate it while pressing the super key to open the main menu.

Misbehaviors that cause this to happen:
- Our event handlers don't always consume events when we act on them, so the event propagates down and can trigger additional actions.
- We sometimes act on both button press and button release events, preventing single action per button press
- PopupMenu.open() tweens are added on idle after the menu is opened. The menu can be immediately closed again because either the event handler is still propagating opening menus, or we have multiple simultaneous menu open events. The tween needs to be cancelled when the menu is closed.

**Comment by itzexor** [comment] 2017-07-21 05:31
I have a fix for the window-list case[0], but I'm unsure what the best course of action here is. I don't know how our event handlers should consume events, and there is no easy fix for multiple actions because of different event handlers (press vs release).

I also have a fix for the tween race[1], but I don't fully understand the side-effects it may have so I am not ready to propose that.

I would appreciate any advice on solving these issues if anyone has dug deep enough to offer additional insights. Thanks.

[0] https://github.com/itzexor/Cinnamon/commit/1dcc24c92f9f600756be2c52b05a3db17ec29b58
[1] https://github.com/itzexor/Cinnamon/tree/popup-tween-race-1

**Comment by icarter09** [comment] 2019-11-21 03:14
@itzexor did the merged PR fix this issue?

**Comment by itzexor** [comment] 2019-11-21 04:32
The merged PR just made the referenced applets behave "properly" in edit mode. That prevents you from reaching the stuck menu state in the first place. I don't know if there are other cases where stuck menus can happen but this specific one shouldn't happen anymore. If someone does run into a new bug they can open a new issue about it.

**Closed by itzexor** 2019-11-21 04:32 UTC
Labels: Gathering Info
