### ISSUE TITLE
Middle-click paste breaks software. Option to disable it should be available in mouse settings

### ISSUE THREAD

**Issue by mikkovedru** [linuxmint/cinnamon#10726] opened 2022-03-30 08:55 UTC
```
 * Cinnamon 5.2.7
 * Distribution - Mint 20.3
 * 64 bit
 ```

**Issue**
- Many programs use the middle-click for various functions like opening links in new tabs/windows, rotating the view (in 3D applications), etc.
- But this is conflicting with the default Linux OS behavior in which the middle-click pastes the clipboard and thus makes it difficult/impossible to use important functions in certain software.
- Unfortunately, there is no sure way to turn this pasting feature off on the OS level, not consistently, not easily, and without any guarantee that it will work. It's "a pity" that one of the most popular Linux distros available (Linux Mint Cinnamon) does not allow to fix this issue (not graphically nor using the terminal commands). It’s a really big mess.
- I believe it was possible to turn this feature off, but all the old suggestions don't work anymore.

I tried every suggestion I found, including dozens [from here](https://askubuntu.com/questions/4507/how-do-i-disable-middle-mouse-button-click-paste). Nothing solved the problem.

**Expected behavior**
The ability to disable middle-button-click pasting feature in Cinnamon's mouse settings.

**Other information**
This feature was requested here #8450, received a lot of votes, but so far there is no indication that it will ever be implemented. Hence I created this new issue in order to raise the important issue again.

**Comment by leigh123linux** [comment] 2022-03-30 09:44
Duplicate of #8450

**Closed by leigh123linux** 2022-03-30 09:44 UTC
