### ISSUE TITLE
Cinnamon Generic Container Changes in 2.8 

### ISSUE THREAD

**Issue by bluedxca93** [linuxmint/Cinnamon#4728] opened 2015-10-20 07:51 UTC
Hi,
![bildschirmfoto vom 2015-10-20 09 52 24](https://cloud.githubusercontent.com/assets/4351663/10601255/68a767ec-7710-11e5-8d9c-4fa2a114a88e.png)

see this screenshot for an example of this using Stark menu. In Configurable Menu the text for applications/favorites Changer is invisible to and tycho places also not showing text.
It seems that something has changed in cinnamon 2.8, so that only true menuitems/popover.menuitems  can be clicked on and not showing text transparent. Why?
Configurable menu also displays repos source actor not found.

Is there a way the applets affected by  this bug will be updated once 17.3 is out? Tried myself already some hours but it seems i don`t have the  skills (yet).

regards bluedxca93

**Comment by leigh123linux** [comment] 2015-10-23 05:56
This is a third-party applet issue, please close the bug and re-file it against the offending applet instead!

**Comment by bluedxca93** [comment] 2015-10-23 06:07
NO leigh123linux.!!!
I did look at code and configurable menu is affected too. Other applets highly probaply too. If it was only stark menu related i didn't post here. Every 2.4 applet that uses a custom menu button might be/is affected.That are quite some more! So dont close. on 2.6.10 it was still working. also it affects applets with button text and icon in panel.

**Comment by bluedxca93** [comment] 2015-10-23 06:13
of course once cinnamon fixed the changes in propably popupmenu.js to mantain backward compatibility yes it  can be closed. The cinnamon devs do know what they changed and why and i believe they have good reasons but without leaving a note and applets are broken now thats not nice.

**Comment by lestcape** [comment] 2015-10-25 17:29
I don't  know how will be the correct way for handle the incompatibilities that was created when the cinnamon code was improved. I think sometime cinnamon devs can do some things to keep the compatibility, in some cases not or at less will not be convenient. In most cases i think the most convenient will be update the external applets, to not be affected the cinnamon behaviour with charge with the old and new way.

@bluedxca93, the third-party devs can always see the cinnamon changes to fix or rewrite his code. It's more difficult predict the applets or desklet that would be affected by a change.

**Comment by lestcape** [comment] 2015-10-25 18:04
To be more clear:

What occurs with Configurable Menu will be fixed, but just not now. Will have more priority to me add some code to the new cinnamon feature of appindicator. I want to add a way to can be disable and enable dynamically. Also an internally blacklist to some indicators when an "equivalent" applet will be enabled/disabled, and a support for the DbusMenu shortcuts, as right now is not working, but is working in the global menu implementation.

To be more complex, i lost one of my disk. The ddrescue program is working for a week now and will be working another week more making an image of my disk. So, i can not take the risk of make a restart cinnamon right now and this is necessary to development or make the correction of any problem.

In the case of configurable menu, is not working because of my fault, not of any other people or organization and I'm aware of that.

**Comment by JosephMcc** [comment] 2015-11-06 12:47
>  also it affects applets with button text and icon in panel.
How? Could you be more specific?

**Comment by lestcape** [comment] 2015-11-12 16:47
@JosephMcc configurable menu extends the cinnamon boxpointer api and your changes in the boxpointer class cause the break of the extension. Is not the same use the api or extended the api. In the extension I used "private" functions also and possible this is my fault and the cause of the rupture. So any change inside the class (not only the interface) will break the compatibility with the Configurable Menu API and could cause an issue. Thats why i say is my matter, because the "public" functions was not modify. Unfortunately is not enough for all features of the configurable menu  what the cinnamon api provide and make a complete copy of the cinnamon API will also be an overhead.

**Comment by JosephMcc** [comment] 2015-11-16 00:00
We try to maintain backward compatibility as much as we can. In some cases though things are going to get broken for third party xlets. If we took the approach of "we never break it no matter what" we would be left in a situation where it would be difficult to improve anything.

**Comment by lestcape** [comment] 2015-11-16 00:31
@JosephMcc yes i know and thanks for improve cinnamon. I appreciate this and is one more reason of why i use cinnamon (because always have new features). The inconvenience of this (because have) will never be significant, because will always have a solution... The update of the third party cinnamon extension.

**Comment by JosephMcc** [comment] 2016-04-24 21:19
Closing this since it is an issue with a 3rd party applet. We really do try not to break things for xlet devs but on occasion it is going to happen.

**Closed by JosephMcc** 2016-04-24 21:19 UTC
