### ISSUE TITLE
Networking: Add support for captive portals

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#6223] opened 2017-01-23 17:04 UTC
https://en.m.wikipedia.org/wiki/Captive_portal

After choosing a public wlan hotspot it would be nice if a window dialog pops up with login screen like in android for example.

**Comment by leigh123linux** [comment] 2017-01-28 13:20
Duplicate of https://github.com/linuxmint/Cinnamon/issues/5756

**Closed by leigh123linux** 2017-01-28 13:20 UTC
