### ISSUE TITLE
Seeing two unlock screen dialogs on a single unlock screen sometimes

### ISSUE THREAD

**Issue by gerow** [linuxmint/Cinnamon#4816] opened 2015-11-10 22:49 UTC
Note that this is _not_ two unlock screens requiring the password to be entered twice, this actually looks like a visual quirk. From the user:

"""
*Sometimes* when I need to unlock the screen, I get 2 different size unlock dialogs.  I do NOT have to unlock twice if I get my password right, but if I get it wrong one of them does go away.  Sometimes I only see one box.  I can't fully reproduce on demand, but it may be more about when it is resuming from sleep vs. the screen lock timing out.
"""

A screenshot (well a picture from a phone because it's a lockscreen :smile:) is attached.

Probably relevant: the user is using a 4k display.
Cinnamon version: 2.6.13

![lockscreen_visual_glitch](https://cloud.githubusercontent.com/assets/403962/11078337/15f92a0c-87ba-11e5-9af1-0bea9901cb60.jpg)

**Comment by RavetcoFX** [comment] 2015-11-16 19:31
This is confirmed on my end, I'll look into fixing this.

**Comment by leigh123linux** [comment] 2015-11-17 09:08
Duplicate of

https://github.com/linuxmint/cinnamon-screensaver/issues/55

**Comment by JosephMcc** [comment] 2015-11-17 11:05
@leigh123linux thanks.

**Closed by JosephMcc** 2015-11-17 11:05 UTC
Labels: BUG REPRODUCED
