### ISSUE TITLE
Cannot configure keyboard shortcuts using the Up or Down arrow keys

### ISSUE THREAD

**Issue by Morgul** [linuxmint/Cinnamon#5039] opened 2016-01-26 05:38 UTC
I am currently trying to configure Ctrl+Up/Down to move through workspaces on Cinnamon 2.8.6. The moment I try to assign the Up or Down key at all, to any shortcut, with any combination of modifiers held down, it cancels the input.

What's even weirder is the Super+Up will always tile the window to the top of the screen, even if I'm attempting to set a keyboard shortcut.

**Comment by JosephMcc** [comment] 2016-01-26 07:30
This seems to be fixed in git master. At least I can't reproduce it.

**Comment by Morgul** [comment] 2016-01-26 23:54
I installed Linux Mint 17.3 Cinnamon edition in a VM today (different machine), and it exhibits the same problem. Let's hope it is fixed in master...

**Closed** 2016-04-24 20:06 UTC
