### ISSUE TITLE
Windows don't move when dragged quickly

### ISSUE THREAD

**Issue by swarmer** [linuxmint/Cinnamon#7186] opened 2018-01-08 10:25 UTC
```
 * Cinnamon version - 3.6.7
 * Distribution - Mint 18.3
 * Graphics: Nvidia GTX 1060, NVIDIA binary driver 384.90
 * 64 bit
 ```

**Issue**
If I try to drag a window too quickly, it doesn't move.

**Steps to reproduce**
Click on the window title bar, move mouse quickly.

**Expected behaviour**
Window should be dragged at any speed.

**Other information**
I can start dragging window slowly and when it starts moving, proceed at any speed after that, this works fine. But if you start dragging quickly, window just stays in place while mouse cursor moves away.

**Comment by leigh123linux** [comment] 2018-01-08 10:58
Your issue doesn't reproduce.

```
* Cinnamon 3.6.7
* Graphics: Nvidia GTX 1050Ti, NVIDIA binary driver 387.34
* 64 bit
```

Maybe your mouse is faulty or needs a new battery?

**Comment by leigh123linux** [comment] 2018-01-08 10:59
Without logging showing it's cinnamon at fault I will have to close it.

**Comment by jaszhix** [comment] 2018-01-08 11:15
This is a problem I've noticed for a long time with Cinnamon - I've recently been able to test a Polaris card and so far can only reproduce with the Nvidia driver. I think this should be filed with Muffin.

More environmental info would help see if others experiencing the issue have a similar set up and help figure out what triggers it most often. On my optimus laptop I can't reproduce it on either Intel or Nvidia, so it seems more likely caused by multi-monitor displays. 

Its also more noticeable if you are using Chrome/Chromium, or have a lot of windows stacked un-minimized.

**Comment by swarmer** [comment] 2018-01-08 11:19
> multi-monitor displays
> Chrome/Chromium
> have a lot of windows stacked un-minimized

All of this is true for me.

> Without logging showing it's cinnamon at fault I will have to close it.

I have no idea how to get relevant logging. Is there something you can point me to?

**Comment by jaszhix** [comment] 2018-01-08 11:24
Check `/var/log/Xorg.0.log` and `inxi -F`.

**Comment by leigh123linux** [comment] 2018-01-08 11:27
@jaszhix  How long has it been present?, was in present in nvidia 375.xx?

**Comment by leigh123linux** [comment] 2018-01-08 11:33
Issue moved to [linuxmint/muffin #307](https://github.com/linuxmint/muffin/issues/307) via [**ZenHub**](https://www.zenhub.com/)

**Closed by leigh123linux** 2018-01-08 11:33 UTC

**Comment by jaszhix** [comment] 2018-01-08 11:55
Since I've started using Cinnamon I think. I can test 375.xx again sometime, its been a while since I've used that driver. I think 384.xx is the new LTS though.

**Comment by leigh123linux** [comment] 2018-01-08 14:04
@jaszhix I've moved this to muffin.
It doesn't reproduce here on my single monitor setup.

```
$ inxi -GSC
System:    Host: leigh-main-pc Kernel: 4.10.0-42-generic x86_64 (64 bit)
           Desktop: Cinnamon 3.6.7  Distro: Linux Mint 18.3 Sylvia
CPU:       Octa core AMD FX-8350 Eight-Core (-MCP-) cache: 16384 KB 
           clock speeds: max: 4500 MHz 1: 2100 MHz 2: 1400 MHz 3: 1400 MHz
           4: 1400 MHz 5: 1400 MHz 6: 3400 MHz 7: 1400 MHz 8: 2100 MHz
Graphics:  Card: NVIDIA Device 1c82
           Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 3840x2160@60.00hz
           GLX Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
           GLX Version: 4.5.0 NVIDIA 384.90
```
