### ISSUE TITLE
Workspace Captions not Shown If Effects Are Disabled

### ISSUE THREAD

**Issue by H8to** [linuxmint/Cinnamon#6971] opened 2017-11-02 10:00 UTC
```
 * Cinnamon 3.4.6
 * Arch Linux
 ```

**Issue**
When the window effects (desktop-effects) are disabled workspace captions are not shown to the user any more.

**Steps to reproduce**
Switch workspaces while effects are on -> Captions will be displayed in the middle of the screen.

Switch workspaces while effects are of -> No captions displayed.

**Expected behaviour**
Captions to be displayed according to the workspace indication setting in the menu "workspaces".

**Comment by leigh123linux** [comment] 2017-11-02 13:11
Duplicate of #6942

**Closed by leigh123linux** 2017-11-02 13:11 UTC
