### ISSUE TITLE
Multiscreen setup, different resolutions, desktop icons hidden

### ISSUE THREAD

**Issue by johschmitz** [linuxmint/Cinnamon#3276] opened 2014-06-17 13:07 UTC
I am using my Laptop screen together with an external Monitor connected to the dockingstation.
The Laptop has a 1366x768 resolution and is the primary display on the left side.
The external screen has a 1280x1024 resolution.
Now when I do "Organize Desktop by Name" cinnamon assumes that both screens have the higher resolution of 1024 lines and some of the icons are placed outside the top of my laptop screen. 
The only way to get them back is CTRL+A and then pull everything down with the mouse.

**Comment by darkwolffe** [comment] 2015-04-03 08:12
I can confirm this is still the case. I have a fourth monitor physically above the other three, all of which are different resolutions. My icons begin appearing at 0,0 which is void space, as my upper-most monitor doesn't begin until 1,905px on the X-axis.

Normal configuration (monitors virtually placed relative to physical location):
![Screenshot](https://cloud.githubusercontent.com/assets/868416/6979799/dd2ae924-d99d-11e4-8c10-1d7c1ccae63b.png)

Cinnamon desired configuration (displays in a tiled configuration starting at 0,0):
![screenshot](https://cloud.githubusercontent.com/assets/868416/6979849/5d884fda-d99e-11e4-9600-8f2eb14f81b0.jpg)

**Comment by buesche87** [comment] 2015-05-11 08:53
Still the case with cinnamon 2.4.8 using nemo 2.4.5
![screenshot from 2015-05-11 10 48 14](https://cloud.githubusercontent.com/assets/11134705/7561373/becc3680-f7cb-11e4-969c-4e7241baf791.png)

**Comment by hubbyist** [comment] 2015-05-19 16:39
In Cinnamon 2.4.8+rebecca, If there is a top panel in desktop, icons are staying in the visible screen area. But desklets still gone missing to void zone. A possible workaround may be to put a 0 pixel height dummy panel in all panel layouts.

**Comment by sproger1** [comment] 2015-10-09 14:29
This issue still exists in 2.6.13+rafaela. It seems KDE is the only one to have correclty solved this with a 'Folder View' menu option that even let's you choose which monitor you want the desktop icons to appear on. Please implement something similar.

See: http://askubuntu.com/a/416903

**Comment by ACinnamonUserInUK** [comment] 2015-11-21 01:25
I have this problem too, using my laptop screen and an external screen.

Linux Mint 17.2. Cinnamon 2.8.

**Comment by kehugter** [comment] 2015-11-26 21:16
Same on Debian, Cinnamon 2.6.13, nemo 2.6.7

**Comment by ian-bertolacci** [comment] 2016-03-20 23:41
Centos 7, Cinnamon 2.8.5
Not sure if the Nemo fix a) made it in or b) just didn't work
The moving the display monitor "up" relative to where it was next to the external monitor allowed me to find and move them.

**Comment by mtwebster** [comment] 2016-03-21 00:01
The fix won't be in a release until nemo 3.0, or if you build it from the current git master branch.

**Comment by edpaay** [comment] 2016-05-07 16:36
I am on Mint 17.3 and the issues are still there it appears as of May 2016 since the desktop icons appear on the wrong monitor not the primary one.  I am new to Linux if I install the KDE version would that work better?

**Comment by pazlex** [comment] 2017-01-03 21:37
Still having this issue on Unity 7.4 on Ubuntu 16.04. The workaround suggested by Hubro 2 years ago works. I made the monitor with the highest resolution (the external monitor) appear on the left side of the configuration and the icons appeared again. However, this also means that my external monitor is also as the primary one, as in this version of Unity the left monitor is by default the primary one, which is another annoying bug (not really hindering my work, but you know how it is....).

**Comment by kehugter** [comment] 2017-01-04 22:41
Seems to be fixed for me in Cinnamon 3.2.6 from Debian testing repos.

@pazlex 
> Unity 7.4

But this is Cinnamon...

**Comment by Vahan86** [comment] 2017-02-04 11:48
@johschmitz, is this still an issue for you in Cinnamon 3.2?

**Comment by AdrianDC** [comment] 2017-02-11 18:34
Issue still present on Cinnamon 3.2.7, Mint 18.1.

I got used to kill the nemo process and restart it manually, which fixes the issue for the session.

Here is the workaround I did :
- Open the "Startup Applications" settings
- Add a new rule. Name "Nemo Kill", Command "killall nemo", Startup delay "0"
- Add a new rule. Name "Nemo Restart", Command "nemo", Startup delay "2"
- Reboot, should be fine

**Comment by kehugter** [comment] 2017-02-11 20:03
^ That could be fixing it for me too. My sessions last weeks/months and I kill nemo often because of https://github.com/linuxmint/nemo/issues/1101

**Comment by Vahan86** [comment] 2017-02-18 20:29
@JosephMcc, can we mark this issue as a bug?

**Comment by JosephMcc** [comment] 2017-02-18 20:51
I'm closing this. The original issue should be fixed. The problem in the last couple of posts is different and you can turn up issues for that by searching for disappearing icons here or on the Nemo git page.

**Closed by JosephMcc** 2017-02-18 20:51 UTC
