### ISSUE TITLE
Grouped windows list: pinned apps disapearing by themselfs

### ISSUE THREAD

**Issue by nleo** [linuxmint/cinnamon#9219] opened 2020-03-25 08:03 UTC
1. Open FireFox. Pin it
2. Open another firefox profile (firefox --no-remote -P)
3. Close first profile
4. Close Second profile
5. No pinned firefox present
![cina-bug](https://user-images.githubusercontent.com/800970/77514614-3579be00-6e88-11ea-9a6f-0ca70d4f35da.gif)

**Comment by smurphos** [comment] 2020-03-29 04:43
Duplicate of https://github.com/linuxmint/cinnamon/issues/8377, https://github.com/linuxmint/cinnamon/issues/8951, https://github.com/linuxmint/cinnamon/issues/8517

Pending fix - https://github.com/linuxmint/cinnamon/pull/9029

**Closed** 2020-10-30 15:22 UTC
Labels: BUG
