### ISSUE TITLE
segmentation fault when opening cinnamon-settings

### ISSUE THREAD

**Issue by bgottschall** [linuxmint/cinnamon#10267] opened 2021-08-13 11:59 UTC
```
 * Cinnamon 5.0.5
 * Linux Mint 20.2 Uma
 * Intel Integrated Graphics Graphics
 * 64 bit
 ```

**Issue**

Opening cinnamon-settings results in a segmentation fault.

**Steps to reproduce**

Open any cinnamon-settings dialog or execute it in the terminal

```bash
/usr/bin/cinnamon-settings
[1]    10406 segmentation fault (core dumped)  cinnamon-settings
```

**Expected behaviour**

No segfaults.

**Other information**

I recently upgraded to Linux Mint 20.2 Uma. Syslog tells me that the segfault happens in a library of the python3-pil package.

```
cinnamon-settin[3376]: segfault at 7f9abb9d1ab7 ip 00007f9a993928ea sp 00007ffcc24f46b0 error 7 in _imagingft.cpython-38-x86_64-linux-gnu.so[7f9a9938a000+b000]
```
[syslog.txt.gz](https://github.com/linuxmint/cinnamon/files/6982257/syslog.txt.gz)

**Comment by mtwebster** [comment] 2021-08-13 12:08
duplicate of https://github.com/linuxmint/cinnamon/issues/10195

You likely have a pip version of pil installed that's incompatible (too new) - it needs to be using the distro version python3-pil. See discussion in the other bug report.

**Closed by mtwebster** 2021-08-13 12:08 UTC
