### ISSUE TITLE
Grouped windows list - pinned app disappears

### ISSUE THREAD

**Issue by pikakolendo02** [linuxmint/cinnamon#9650] opened 2020-10-18 06:51 UTC
```
 * Cinnamon version (Cinnamon 4.6.7)
 * Distribution - (LMDE 4)
 * Graphics hardware *and* driver used
 * 64 bit
 ```
[syslog](https://github.com/linuxmint/cinnamon/files/5397136/syslog.txt)

**Issue**
The pinned app disappears with a specific operation.

**Steps to reproduce**
1. Uncheck "Group windows by application".
![Screenshot 1](https://user-images.githubusercontent.com/15796641/96360348-06da7200-114f-11eb-80c5-b59f8ac2a5f1.png)
2. Open two windows of a pinned app (the two windows are separated! I prefer they are together just like windows 7)
![Screenshot 2](https://user-images.githubusercontent.com/15796641/96360379-60db3780-114f-11eb-964d-d7aa9134aa84.png)
3. Close the first one,
![Screenshot from 3](https://user-images.githubusercontent.com/15796641/96360400-ab5cb400-114f-11eb-9b35-a80ac8dd4483.png)
    then close another.
![Screenshot 4](https://user-images.githubusercontent.com/15796641/96360410-ba436680-114f-11eb-933f-5686ef665bae.png)
    Uh oh, the pinned terminal has gone :(

If I close the second window then the first one, nothing is wrong.

**Expected behaviour**
Two or more windows of one application bind together with "Group windows by application" unchecked (just like win7 or later).
![win7 uncombined style](https://user-images.githubusercontent.com/15796641/96360488-48b7e800-1150-11eb-975b-0521a58609a2.png)

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

Configurations of Grouped windows list
![Screenshot 5](https://user-images.githubusercontent.com/15796641/96360598-2d99a800-1151-11eb-8550-bdf7438560d2.png)
![Screenshot 6](https://user-images.githubusercontent.com/15796641/96360599-2f636b80-1151-11eb-8ea5-b30406d54097.png)
![Screenshot 7](https://user-images.githubusercontent.com/15796641/96360600-2ffc0200-1151-11eb-9968-33e7fedb4d9f.png)
![Screenshot 8](https://user-images.githubusercontent.com/15796641/96360601-30949880-1151-11eb-8b5a-cef39ae0b3ae.png)

I love cinnamon. Thank you!

**Comment by mtdvuk** [comment] 2020-10-27 20:25
Seems like a duplicate of #8951, #9219  and #8377 
This has been annoying me so it's good to see it's a known problem

**Comment by claudiux** [comment] 2020-10-28 09:43
Rechecking "Group windows by application" causes the icon to reappear.

**Comment by claudiux** [comment] 2020-10-28 16:10
@mtdvuk The solution is so simple! https://github.com/linuxmint/cinnamon/pull/9678/files

**Closed** 2020-10-30 15:22 UTC
