### ISSUE TITLE
Focus Stealing Settings Per-App 

### ISSUE THREAD

**Issue by de-angelov** [linuxmint/cinnamon#11368] opened 2022-12-29 12:56 UTC
### Is your feature request related to a problem? Please describe.
I am using vscodium on 21.1 Cinnamon
When atempting to open/save file. New dialog is opened but its not focussed and stays in the background of the main vscodium window as an additional step you need to Alt + Tab to set focus on this window.

### Describe the solution you'd like
Add Windows/Behavior setting to allow new windows created by specified list of programs (vscodium in my case ) to be on top and focused by default. This will allow programs to have the expected behavior.

**Comment by mtwebster** [comment] 2022-12-29 14:03
I think this may be an issue with electron (what vscodium is built with) - it also happens with vscode, and I can reproduce the issue in Mate/Metacity as well.

The problem is that the 'timestamp' being used by vscodium's dialog is *older* than the most recent user interaction timestamp reported by main the vscodium window. It's assumed then that this dialog hasn't been spawned directly thru a user's action, but programmatically, and refuses to focus the window (and interrupt the user).

If I open a dialog on another editor, like xed, that dialog's timestamp *does* match the most recent event timestamp reported by xed, and is allowed to take focus. I tested another flatpak editor - 'geany' and it also works fine.

**Comment by mtwebster** [comment] 2022-12-29 14:10
Try this:
install dconf-editor:
```
apt install dconf-editor
```

Start it from the menu, and navigate to /org/cinnamon/demands-attention-passthru-wm-classes. That is a list of apps that can misbehave also. Click on that item to edit it, and add `xdg-desktop-portal-gtk` to the list (you need to turn off 'Use default value' first).

**Comment by de-angelov** [comment] 2022-12-29 14:33
Thanks for the response.
I added xdg-desktop-portal-gtk to the list aftrer disabeling 'Use default value'. Rebooted and the behaviors remains the same from open/save window

**Comment by mtwebster** [comment] 2022-12-29 15:00
Weird, doing this has an immediate (no reboot needed) and permanent effect on the file dialogs, whether opened from the File menu, or using ctrl-o. Do you have any other windows open from other apps, that you've marked as 'Always on top' from the window menu? This can also have an effect on window focus.

![image](https://user-images.githubusercontent.com/262776/209970987-7000e90a-86a3-4011-ad75-e813fc7fd6b3.png)

The 'works the first time' thing was that way even without this change - I was at first inclined to say I couldn't reproduce the issue because of it.

**Comment by de-angelov** [comment] 2022-12-29 15:29
I tried with only with vscodium running , also with all vscode extensions disabled just in case and it remains the same for me.

**Comment by de-angelov** [comment] 2022-12-29 17:59
I found why the solution was not working for me .
I actually forgot that I installed VSCodium from https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo
Adding 'codium' to the above list fixes the issue.

Thanks for the help and sorry for the confussion

**Closed** 2022-12-29 18:00 UTC
Labels: FEATURE REQUEST
