### ISSUE TITLE
Lock screen UI is messed up with interface scaling turned on

### ISSUE THREAD

**Issue by sonelliot** [linuxmint/Cinnamon#4732] opened 2015-10-22 13:26 UTC
**Distro:** Linux Mint 17.2 (64-bit)
**Cinnamon Version:** 2.8.0
**How to reproduce:**

*Note:* You may need a high-definition screen. I am using a laptop with a 2560x1440 resolution screen.

1. Activate interface scaling in `System Settings -> General` by selecting `Double (Hi-DPI)` in the dropdown.
2. Log out and log back in again.
3. Lock the screen. You should see that the login buttons are overlapping and the UI is squished into the top-left corner.
4. Switch back to `Normal` interface scaling and lock the screen again to see what it should look like.

I'd like to take a screenshot as well so I can show you what it looks like, but the standard screenshot command does not seem to work while locked. Is there an alternative method I can use?

**Comment by leigh123linux** [comment] 2015-10-23 05:37
duplicate of 

https://github.com/linuxmint/cinnamon-screensaver/issues/55

**Closed** 2015-10-23 05:52 UTC
