### ISSUE TITLE
Can't add Google mail account to Calendar with nvidia driver

### ISSUE THREAD

**Issue by jave808** [linuxmint/cinnamon#12042] opened 2024-01-23 04:48 UTC
### Distribution

Linux Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

nvidia RTX3070

### Frequency

Always

### Bug description

Can't add Google Mail account to the default Calendar app in Linux Mint 21.3

I just get a blank window when the "Google" option is selected in "Online accounts"
![Screenshot from 2024-01-23 15-46-30](https://github.com/linuxmint/cinnamon/assets/65537119/f57a894f-9471-4b5f-b611-7340e57e371d)

### Steps to reproduce

Open Calendar app. Select "Online accounts" from menu in top right corner. Click on "Google" when window opens.

Window then opens but is blank.

### Expected behavior

Google should open where a user can input their email address and password.

**Comment by leigh123linux** [comment] 2024-01-23 08:22
Duplicate of #11881

**Closed by leigh123linux** 2024-01-23 08:22 UTC
Labels: BUG
