### ISSUE TITLE
Preferences-Display-Rotation

### ISSUE THREAD

**Issue by gh4snow** [linuxmint/Cinnamon#4981] opened 2016-01-03 16:45 UTC
Using 2 AMD HD6450 Display adapters /w 2 Dell 1600x1200 displays.
Prefer Primary Display in Landscape Mode & Secondary Display rotated
to Portrait Mode.

Linux Mint 17.3 Cinnamon Ver 2.8.6 doesn't allow the second display to be rotated.

So I am stuck having to use MSFT Win 7.
Please improve the Preference/Display/Rotation Menus.

**Comment by luyikei** [comment] 2016-01-05 14:26
Can you elaborate more on the bug you reported? I can't reproduce the problem.

![display_001](https://cloud.githubusercontent.com/assets/1858413/12117283/275e18f0-b403-11e5-8513-f5449049dd27.png)
![display_004](https://cloud.githubusercontent.com/assets/1858413/12117284/2763219c-b403-11e5-8d38-fbb8c49ba595.png)

As attached images show, if you click a display that you want to rotate, you can rotate the display by selecting from the "Rotation" drop-down list. I'm sorry if my understanding is wrong.

**Comment by gh4snow** [comment] 2016-01-09 17:19
I want to use 2 displays, the primary in Landscape mode, the second display in Portrait mode.
Both displays to be in the same desktop, so that both can be used by any application.

**Comment by luyikei** [comment] 2016-01-10 02:54
All right. You mean you want to use displays in mirroring mode, right?

**Comment by gh4snow** [comment] 2016-01-15 13:13
Not mirroring mode. I believe it is called Independent mode, both displays are part of the same desktop, and can be used by either a single or multiple applications, as the user wishes.

**Comment by JosephMcc** [comment] 2016-01-19 07:55
It seems to work here http://imgur.com/QSwCcmt
I can freely move windows between the two monitors. I do have to say it's a bit strange though since my monitors can't be physically rotated ;)

**Comment by gh4snow** [comment] 2016-01-19 14:45
Menu choices for second monitor rotation don't display on my PC's /w Mint, but work fine /w MSFT Win 7.

**Comment by gh4snow** [comment] 2016-01-25 18:48
Tried installing AMD Catalyst Driver for the video adapter & found it could only detect the first display.
De-installed the driver & returned to the default Linux Mint driver which does not allow for rotation of the second display.

**Comment by JosephMcc** [comment] 2016-06-09 11:38
Closing since this seems to be a limitation of the driver.

**Closed by JosephMcc** 2016-06-09 11:38 UTC
