### ISSUE TITLE
text in OS related applets disappears

### ISSUE THREAD

**Issue by elmarr** [linuxmint/Cinnamon#6096] opened 2016-12-16 03:49 UTC
At first I thought it was because of extended sleep mode, but this morning it happened whilst the computer was on all night.
Dell E6530 8GB
LMC18 v3.0.7 with no outstanding updates
kernel 4.4.0-21
Intel 3rdgen core processor graphics controller

All text on the taskbar disappears. The icons are visible. ditto in the Menu
![2011-11-01_16-36-11](https://cloud.githubusercontent.com/assets/14230564/21251010/9487108a-c352-11e6-94b7-c7bf0412d260.png)

Text is normal in other apps apps (e.g firefox,, office apps, etc.) 

Reboot resolves the problem. Has been happening since upgrade - I did a normal upgrade from LMC17.1, then recently switched to LMKDE then reinstalled LMC18 (because KDE did not work for me.)

**Comment by elmarr** [comment] 2016-12-16 03:53
apologies, shows wrong screenshot
![screenshot from 2016-12-16 05-50-48](https://cloud.githubusercontent.com/assets/14230564/21251129/bf84222c-c353-11e6-9370-830ad2096137.png)

**Comment by leigh123linux** [comment] 2016-12-16 07:25
Duplicate of
#3442

**Closed by leigh123linux** 2016-12-16 07:25 UTC

**Comment by elmarr** [comment] 2016-12-16 08:37
Dear Leigh, 

yes, looking at the screenshots in #3442 it seems to be exactly that. 

Note that this never occurred when I was still using LMC17.0 

I cannot recall if it happened whilst I briefly used KDE.
