### ISSUE TITLE
Cinnamon Theme Module doesn't work

### ISSUE THREAD

**Issue by chromer030** [linuxmint/cinnamon#9044] opened 2019-12-21 16:07 UTC
```
 * Cinnamon version (cinnamon --version) : Cinnamon 4.4.4
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). : No
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) : Arch Linux
 * Graphics hardware *and* driver used : Intel CPU & GPU -  Mesa 19.3.1
 * 32 or 64 bit : 64Bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Cinnamon Theme Module doesn't work

**Steps to reproduce**

running cinnamon-settings themes

**Expected behaviour**

`Arch@Chromer:~$ cinnamon-settings themes

/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py:334: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if show_seconds is 'default':
/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py:338: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if show_seconds is 'true':
/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py:340: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif show_seconds is 'false':
True
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:422: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if category.int_name is not "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:431: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if category.int_name is "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:446: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if category.int_name is "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:456: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if entry is not "_invalid_":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:539: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cat[2].int_name is "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:577: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cat[2].int_name is "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:603: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cat[2].int_name is "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:694: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if entry is not "":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:734: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if entry is not "":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:780: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  ok_enabled = self.name_entry.get_text().strip() is not "" and self.command_entry.get_text().strip() is not ""
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:780: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  ok_enabled = self.name_entry.get_text().strip() is not "" and self.command_entry.get_text().strip() is not ""
Using pam module (python3-pampy)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:426: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Themes module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 726, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 431, in __init__
    self.go_to_sidepage(cat, path, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 188, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 213, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 154, in on_module_selected
    self.refresh()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 186, in refresh
    self.refresh_chooser(payload)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 239, in refresh_chooser
    if os.path.exists(theme_path):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Arch@Chromer:~$ `

**Comment by leigh123linux** [comment] 2019-12-21 16:12
Duplicate of #9043

**Comment by eli-schwartz** [comment] 2019-12-26 14:50
This line here crashes, apparently:

https://github.com/linuxmint/cinnamon/blob/bd2104e59dc2eb86b52ee9c6c14a7df847cd73fe/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py#L239

theme_path is supposed to be defined to something other than None, because of this:

https://github.com/linuxmint/cinnamon/blob/bd2104e59dc2eb86b52ee9c6c14a7df847cd73fe/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py#L224-L229

Or previously because of:

https://github.com/linuxmint/cinnamon/blob/bd2104e59dc2eb86b52ee9c6c14a7df847cd73fe/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py#L218-L222

@leigh123linux 

Why do you think this is a duplicate? Both issues refer to the same module failing, but the underlying tracebacks point to completely different components.

**Comment by eli-schwartz** [comment] 2019-12-26 14:54
@chromer030 

As far as I can tell, this should only fail if you're using an icon theme that does not have a "places/folder.png" icon.

**Comment by eli-schwartz** [comment] 2019-12-26 15:00
From the linked issue:

> Thanks to neko from Porteus Linux , this issue was fixed.
> The cause of this crash is that setting the path to variable theme_path was missing and added in line 239 of cs_theme.py

And the supposed fix was to always set theme_path to "usr/share/themes" which is *completely* insane and utterly wrong.

**Comment by eli-schwartz** [comment] 2019-12-26 17:48
@leigh123linux I think the confusion between the two issues is due to the very noisy noise I've tried to fix in #9060

**Comment by mtwebster** [comment] 2019-12-26 17:51
I've spent quite a bit of time attempting to reproduce this, and even with a missing folder.* file, it always finds a fallback to use.  Even if I remove gnome-icon-theme's folder.*  No matter what I do I cannot break it.  I suppose I can just catch the exception there and skip it.. but it'd be nice to reproduce it.

**Comment by mtwebster** [comment] 2019-12-29 21:58
Can anyone maybe try inserting these two lines?  I'm 99% sure they would at least prevent the crash, but I'd rather be certain before I commit it, and I can't reproduce this.

Thanks

```
diff --git a/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py b/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
index badc27a5a..cb12b20be 100755
--- a/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
+++ b/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py
@@ -242,6 +242,9 @@ class Module:
 
                     dump = True
 
+                if theme_path == None:
+                    continue;
+
                 if os.path.exists(theme_path):
                     chooser.add_picture(theme_path, callback, title=theme, id=theme)
                 GLib.timeout_add(5, self.increment_progress, (chooser, inc))
```

**Comment by AdrianTwo** [comment] 2019-12-30 00:33
@mtwebster Very nice. I inserted those two lines and my themes module works again! I don't get any errors and I can change all themes. I think you solved the problem!

![grafik](https://user-images.githubusercontent.com/53347802/71564636-565a8f00-2aa4-11ea-90c0-9bb49b83f805.png)

**Closed** 2019-12-30 00:45 UTC
