### ISSUE TITLE
Deleting desktop folder beeps, even when all sound effects are disabled

### ISSUE THREAD

**Issue by TopView** [linuxmint/Cinnamon#7652] opened 2018-06-15 17:00 UTC
```
 * Cinnamon version (cinnamon --version): 3.2.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Debian 9.4 (Stretch)
 * Graphics hardware *and* driver used: AMD RV710/M92 (Mobility Radeon HD 4530/4570/545v)
 * 32 or 64 bit: 64 bit
 ```

Hi, I noticed that even when all sound effects are disabled deleting a desktop folder still beeps.

**Steps to reproduce**

1) First ensure that system beeping is otherwise enabled:

1a) Open GNOME ALSA mixer, 
1b) Select your sound card if necessary,
1c) Enable the Beep column (i.e. Menu> Edit> Sound Card Properties and check Beep),
1d) Un-Mute (un check) Beep for your current sound card.  (The sound slider doesn't seem to matter).

2) Now verify that beep actually works:

2a) Open a GNOME terminal window,
2b) Edit Profile Preferences,
2c) Ensure that Terminal bell is checked (enabled),
2d) Then enter `echo -e '\a'` into the terminal and a beep should be heard.  (If you don't get a beep here, then first fix your system so you do get a beep here.)

3) Verify that all Sound Effects are disabled:

3a) Open system Settings in Cinnamon,
3b) Select Sound,
3c) Select the Sound Effects tab,
3d) Switch off all Effects, e.g. Starting Cinnamon, Leaving Cinnamon, Switching workspace, ...

4) Create a dummy folder on the desktop.

5) Delete the dummy folder on the desktop.  

**Expected behavior** 

The folder should be quietly deleted with no sound emitted.

**Comment by leigh123linux** [comment] 2018-06-15 19:15
Duplicate of https://github.com/linuxmint/Cinnamon/issues/5253

**Closed by leigh123linux** 2018-06-15 19:15 UTC

**Comment by lmarszalek** [comment] 2020-02-17 15:10
Worked for me:
Go to Settings/Sound/Sound effects tab
"Notifications" is the only one unassigned by default.
Set it to /usr/share/cinnamon-control-center/sounds/notification.oga as it should be.
Done. Fedora 31 Cinnamon 4.4.8
