### ISSUE TITLE
Cinnamon 1.6 (and more?) : Applets inhibit sleep mode

### ISSUE THREAD

**Issue by RyDroid** [linuxmint/Cinnamon#1975] opened 2013-05-06 20:15 UTC
OS : GNU/Linux Ubuntu 12.10
Cinnamon : 1.6 with PPA

I had my music applet open : the "pop-up" with a music played with Rhytmbox that was on pause. I let my mouse on the "pop-up" more than 1 hour (this is enough for going in "sleep mode") without using the PC. Then (nldr: after more than 1h), I move the mouse outsite from the "pop-up" and it suddendly passes to "sleep mode"/"password screen".

**Comment by ManIVIctorious** [comment] 2016-09-10 19:20
Duplicate of #1430

**Closed** 2016-09-10 19:34 UTC
