### ISSUE TITLE
Improvements to the background settings

### ISSUE THREAD

**Issue by liamdawe** [linuxmint/Cinnamon#3047] opened 2014-04-14 14:22 UTC
So, I have 2 monitors and it seems in Cinnamon there is no way to have a different background on my monitors, it seems to set the background on all monitors.

Do you think for Cinnamon 2.4 or 2.6 that could be a focus?

**Comment by RavetcoFX** [comment] 2015-06-07 07:18
Duplicate of #2301

**Closed** 2015-06-07 07:19 UTC
