### ISSUE TITLE
Places Menu in Cinnamon 1.6 prefers Nautilus over Nemo if Both Installed

### ISSUE THREAD

**Issue by crossroadstech** [linuxmint/Cinnamon#1182] opened 2012-09-23 00:51 UTC
If both Nautilus and Nemo are installed, the Places menu in Cinnamon 1.6 will always open the bookmarks with Nautilus, even if Nemo is handling the desktop.  When I removed Nautilus, then the Places menu bookmarks would open with Nemo.

**Comment by Vahan86** [comment] 2016-08-28 18:23
The issue is fixed in current version of Cinnamon. 

@JosephMcc ,  I think the issue can be closed.

**Comment by JosephMcc** [comment] 2016-08-28 18:38
@ManIVIctorious is this issue solved for you under the latest Cinnamon?

**Comment by ManIVIctorious** [comment] 2016-08-29 13:23
Have to admit, didn't use dropbox for a long time, I'll try in the evening

**Comment by ManIVIctorious** [comment] 2016-08-29 15:47
Ok, just started dropbox and rightclicked to open "Dropbox-Folder" -> started nautilus :(

I checked `xdg-mime query default inode/direcory` which states `nemo.desktop` is the default

`pacman -Qs cinnamon | grep "^\S"`
  local/cinnamon 3.0.7-1
local/cinnamon-control-center 3.0.1-1
local/cinnamon-desktop 3.0.2-1
local/cinnamon-menus 3.0.2-1
local/cinnamon-screensaver 3.0.1-1
local/cinnamon-session 3.0.1-1
local/cinnamon-settings-daemon 3.0.1-1
local/cinnamon-translations 3.0.3-1
local/cjs 3.0.1-1
local/muffin 3.0.5-1
local/nemo 3.0.6-1

**Comment by JosephMcc** [comment] 2018-02-17 22:59
I'm closing this since the original issue is fixed. Not sure about the dropbox issue. Having both nemo and nautilus installed seems to lead to several issues like this.

**Closed by JosephMcc** 2018-02-17 22:59 UTC
Labels: BUG
