### ISSUE TITLE
Calendar applet: Date highlighted is different than actual date

### ISSUE THREAD

**Issue by john-light** [linuxmint/cinnamon#9582] opened 2020-09-15 21:23 UTC
```
 * Cinnamon version (cinnamon --version)
- Cinnamon 4.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
- Mint 20
 ```

**Issue**

The date highlighted on the calendar does not match the date actually shown.

When I switched the day that the week should start (from "locale default" to "Sunday" and then to "Monday") the calendar got even more screwed up, starting the week with Saturday in the former case and Sunday in the latter case.

See screenshots:

![date-error](https://user-images.githubusercontent.com/9424721/93266140-2c174180-f799-11ea-83a1-2087ff2be4a0.png)

![date-error2](https://user-images.githubusercontent.com/9424721/93266161-32a5b900-f799-11ea-9e1a-0c01b025df43.png)

![date-error-3](https://user-images.githubusercontent.com/9424721/93266175-38030380-f799-11ea-989a-9edc0c2b6845.png)

**Steps to reproduce**

I'm not sure how to reproduce because I'm not sure what caused the problem in the first place. This is a fresh install of Mint 20 and I haven't done anything unusual with it.

**Expected behaviour**

I expect that the date highlighted on the calendar would be the same as the date actually shown, and when I switch the day that the week starts on the calendar will update accordingly and start on the day specified.

**Configuration info, if applicable**

Calendar applet:

```

{
    "section1": {
        "type": "section",
        "description": "Display"
    },
    "show-week-numbers": {
        "type": "switch",
        "default": false,
        "description": "Show week numbers in calendar",
        "tooltip": "Check this to show week numbers in the calendar.",
        "value": false
    },
    "use-custom-format": {
        "type": "switch",
        "default": false,
        "description": "Use a custom date format",
        "tooltip": "Check this to define a custom format for the date in the calendar applet.",
        "value": false
    },
    "custom-format": {
        "type": "entry",
        "default": "%A, %B %e, %H:%M",
        "description": "Date format",
        "indent": true,
        "dependency": "use-custom-format",
        "tooltip": "Set your custom format here.",
        "value": "%A, %B %e, %H:%M"
    },
    "format-button": {
        "type": "button",
        "description": "Show information on date format syntax",
        "indent": true,
        "dependency": "use-custom-format",
        "callback": "on_custom_format_button_pressed",
        "tooltip": "Click this button to know more about the syntax for date formats."
    },
    "section2": {
        "type": "section",
        "description": "Keyboard shortcuts"
    },
    "keyOpen": {
        "type": "keybinding",
        "description": "Show calendar",
        "default": "<Super>c",
        "tooltip": "Set keybinding(s) to show the calendar.",
        "value": "<Super>c"
    },
    "__md5__": "630b424730fcba4718d867a7442c6b3b"
}

```

**Comment by icarter09** [comment] 2020-10-02 02:54
@john-light are you still experiencing this issue? I've been trying to break the calendar applet by changing the settings you referenced, but haven't been able to reproduce the issue.

**Comment by john-light** [comment] 2020-10-02 16:31
I ended up having so many issues with 20 that I downgraded to Mint 19.3, the issues have mostly gone away now.

**Comment by icarter09** [comment] 2020-10-13 00:08
I'm going to close this issue since you aren't experiencing the issue any longer. If you do experience it again, just open up a new ticket. Thanks.

**Closed by icarter09** 2020-10-13 00:08 UTC
Labels: BUG, Gathering Info
