### ISSUE TITLE
[Cinnamon 4.0.9 - GWL] Some apps are shown as unpinned when grouping is disabled

### ISSUE THREAD

**Issue by FrogMcRibbit** [linuxmint/cinnamon#8377] opened 2019-02-08 01:06 UTC
```
 * Cinnamon version
4.0.9

 * Distribution
Manjaro Cinnamon + Linux Mint 19.1 Cinnamon

 * Graphics hardware *and* driver used
On Manjaro Cinnamon: Nvidia Geforce GTX 970 (non-free drivers)
On Linux Mint 19.1 Cinnamon: Virtual Box 6.0.2 (Hosted on my Manjaro Cinnamon machine)

 * 32 or 64 bit
64 bits

 * Browsers tested
Firefox, Chromium, Opera
 ```

**Issue**
Major browsers nowadays feature a mode called "Private" or "Incognito". When used, it opens a window of that browser in that mode.

If I use the new Grouped window list applet, I have a browser pinned in panel and I close a window of that browser that is in "Private"/"Incognito" mode, if I have no regular window of that browser left, the browser gets unpinned from the panel. I need to pin the browser back.

This bug only happens if the GWL actually don't group windows ("Group windows by application" disabled); the browser doesn't get unpinned if windows are grouped by applications (option enabled, which is the case by default).

I get the same behavior on Firefox, Chrome, and Opera. I could reproduce the issue both on real hardware on Manjaro Cinnamon and in a virtual machine (Virtual Box) on Linux Mint 19.1. I use Cinnamon 4.0.9 on both operating systems. The way I launch the browser (from panel, from menu, from a launcher on desktop...) doesn't give a different behavior.

**Steps to reproduce**
0. Have a pinned browser (for example: Firefox).
1. Launch the browser in regular mode.
2. In the browser, open a new window in "Private"/"Incognito" mode.
3. Close the regular window first.
4. Then, close the window in "Private"/"Incognito" mode.

When I follow these steps, the browser get unpinned unintentionally.

**Expected behaviour**

Normally, a browser that has been pinned to panel should just stay pinned after I close the last window no matter what.

**Other information**
If you want to see a visual demonstration of the issue, I recorded a video. Fell free to skip parts of it as I reproduce the issue quite a lot of time and pretty slowly.
https://www.youtube.com/watch?v=LCo9gPNWQRI

I see that Cinnamon got modified quite a lot since the release of Cinnamon 4.0.9, so perhaps it has already been fixed?

I do not have any log files to offer, and I do not know what could be helpful for this issue.

Thanks in advance for reading my report and handling the issue.

**Comment by smurphos** [comment] 2019-02-08 05:52
I can reproduce this with a bit of additional info - a cinnamon restart (Ctrl-Alt-Del) restores the original pinned browser icon without having to repin it.

**Comment by DrCPlusPlus** [comment] 2019-02-14 18:28
I can, too, confirm this is an issue. Although I will add that it is any program that can have multiple windows not just web browsers, nor is the private window required (can be two non private windows) etc. Once a new window is opened and if you right click on it in the panel it will have the 'Pin to Panel' option as opposed to 'Unpin from panel', if this new window is the last closed, the app will no longer be pinned.

**Comment by Saucistophe** [comment] 2019-02-15 10:04
Nice, I now understand what was going on with my development computer.
Confirmed on chromium, and also on Sublime merge (File Menu > Open Recent > Whatever, close the original window, close the newly open window) and VS Code (File Menu > New Window, close the original window, close the newly open window)

**Comment by FrogMcRibbit** [comment] 2019-02-15 22:34
> with a bit of additional info - a cinnamon restart (Ctrl-Alt-Del) restores the original pinned browser icon without having to repin it.
Indeed, I also get back the pinned application as normal when I log out->log in, or if I ask a Cinnamon restart with Right click on the panel > Troubleshoot > Restart Cinnamon.

> Although I will add that it is any program that can have multiple windows not just web browsers, nor is the private window required (can be two non private windows) etc
Indeed, I can confirm that it can also happen with two regular window. It seems that as long as you close the original window, then close the newer window, the application will get unpinned. I first though it was only an issue with Private windows since it is how I first discovered the issue and could reproduce it with 100% success.

I could also reproduce the same behavior with Gnome Terminal for example.

So it seems to actually affect any application that allows you to open multiple windows of it at the same time, not just browsers when using Private windows.

I changed the title of this issue to make it more accurate to what it has been discovered so far.

**Comment by FrogMcRibbit** [comment] 2019-07-08 23:32
Follow-up:

I can still reproduce the issue on Cinnamon 4.2.0 on Manjaro following the same steps.

**Comment by DrCPlusPlus** [comment] 2019-08-04 14:10
I can also still reproduce the issue on Cinnamon 4.2.3 on Linux Mint 19.2 following the same steps.

**Comment by jerry-sky** [comment] 2019-11-12 10:20
I also experienced something similar to this bug.

In my case switching between workspaces can trigger this issue. After switching to another workspace and quitting the application (e.g. Vivaldi Browser) the app disappears from the panel.

**Curiously, the app doesn't show as unpinned on other workspaces** - *only on the workspace where the app was shut down*.

**Comment by SteMak** [comment] 2020-04-18 01:13
I'm enjoying the same bug with my Discord. You know, it firstly opens the window for checking updates. And if it closes before opening the main Discord window, the app will become unpinned.

**Comment by pomponfrais** [comment] 2020-04-22 17:39
Hello !
Same issue here, it's really annoying because i'm used to work with different workspaces and several windows for each program. I'm constantly opening and closing windows... It's very boring to pin them again each time. Is there a fix or a workaround ? thank you :)

**Comment by smurphos** [comment] 2020-04-24 08:07
There's a pending pull request that fixes this - https://github.com/linuxmint/cinnamon/pull/9029

**Closed** 2020-10-30 15:22 UTC
Labels: BUG, BUG REPRODUCED
