### ISSUE TITLE
WindowGroupList applet uses drag without mouse click event

### ISSUE THREAD

**Issue by stefan123t** [linuxmint/Cinnamon#4044] opened 2015-04-13 16:00 UTC
Dear Cinnamon-team,

I have logged an issue with the original author of this non-official Cinnamon applet.
https://github.com/jake-phy/WindowIconList/issues/91

Having read through a couple of cinnamon issues (#2597, #2779, #3116) and tried out xev to debug the situation I understand that it can be tricky to capture/timeout the button release event, in case the pointer is leaving the panel/applet area.

The problem with this applet is that it will start to drag favorites/window icons around its applet space and across the desktop even though I have not pressed (or alread, quickly released) a button. This happens very frequently though I can not reproduce it at will.

Would you mind taking a look at the applet in order to tell if there is something that needs to be changed in order to make it work properly with Mint 17.1 / Cinnamon 2.4.8, which I am running ?

Kind regards,
Stefan

**Comment by Cobinja** [comment] 2015-05-04 11:16
The applet uses a timer to show the preview window (which is also used to display the app name when no app instance is running). The issue is that during the menu opening process, the mouse button release is not handled properly, so the applet thinks that the button is still down, and starts the dragging.
It's a regression introduced by https://github.com/linuxmint/Cinnamon/commit/0b7cbf894e27c22f12ad952dde885c550e405a00#diff-3b6207d7724bf19d69e904032034e026

**Comment by stefan123t** [comment] 2015-05-11 13:48
@Cobinja thanks for your analysis, this sounds like what I expected when staring at the timer being used in https://github.com/jake-phy/WindowIconList/issues/91. The conclusion you draw is reasonable.

**Comment by lestcape** [comment] 2015-05-11 20:59
Thanks @stefan123t, i will response here, as is a meta-bug that also affect cinnamon behavior. 

I'm agree with @Cobinja, he is right on what he say, but i can not find a better way to do what @mtwebster  do. The real problem on my opinion is not this commit, the problem is, handled the mouse relase instead the mouse press, and then, the commit just try to mitigate as possible whats occurs...

What is needed, is find a general way on cinnamon to fixed all possible wrong behaviors, because try to find a fix for an specific extension just will help this extension as i do on configurable menu, because i can not find a good general way to handle this. Possible what is needed is a more general and at the same time specific behavior. As a filter of global events take into account if the target of the event is an actor inside the popupmenu actor that trigger the global event, and not filter any other even outside the popupmenu actor, but ofcourse this will need to be tested for a while and see if could help.

I think that the most important opinion here, will be the @mtwebster opinion, as he is who really try to find a general solution and he is who find the currently better solution.

Regards.

**Comment by lestcape** [comment] 2015-05-12 03:00
I test for a while, what i say an aparently this fix the problem.

Change this line (Main.popup_rendering = true;):
https://github.com/linuxmint/Cinnamon/commit/0b7cbf894e27c22f12ad952dde885c550e405a00#diff-09304ba2858e4c3eefca50fd13f45308R1240
by this one:  Main.popup_rendering = this.actor;

Then change this(Main.popup_rendering = false;) https://github.com/linuxmint/Cinnamon/commit/0b7cbf894e27c22f12ad952dde885c550e405a00#diff-09304ba2858e4c3eefca50fd13f45308R1276
by this one:  Main.popup_rendering = null;

Then change this line(let popup_rendering = false;) https://github.com/linuxmint/Cinnamon/commit/0b7cbf894e27c22f12ad952dde885c550e405a00#diff-3b6207d7724bf19d69e904032034e026R140
by this one:  let popup_rendering = null;

Then change this code: https://github.com/linuxmint/Cinnamon/commit/0b7cbf894e27c22f12ad952dde885c550e405a00#diff-3b6207d7724bf19d69e904032034e026R1067
```
if (event.type() != Clutter.EventType.KEY_PRESS) {
       return popup_rendering && event.type() == Clutter.EventType.BUTTON_RELEASE;
}
```
by this one: 

```
if (event.type() != Clutter.EventType.KEY_PRESS) {
        if(!popup_rendering || event.type() != Clutter.EventType.BUTTON_RELEASE)
            return false;
        let src = event.get_source();
        if(src && popup_rendering.contain(src))
            return true;
        return false;
    }
```

Save and restart cinnamon. The cinnamon windows list, will work ok, but the windows icon list will need an update to propertly work with this change, but this update will be a regretion for a wrong thing...

Regards.

**Comment by lestcape** [comment] 2015-05-12 03:30
Will be better use an another name, different of popup_rendering, because is imposible check the javascript type, and with a different name could be apply a diferent patch to the extension that currently use/modify this value, as configurable menu.

**Comment by JosephMcc** [comment] 2015-11-08 10:44
@letscape Did your PR fix the original posters issue?

**Comment by lestcape** [comment] 2015-11-10 03:30
@JosephMcc, yes in most of cases, but probably not for all cases. When the mouse release will be eat, because was inside the popup menu and the applet is waiting for the release this probably can cause the same issue. This fact occurs now when you try to open a popup menu that have several items (and is slow), as for example the cinnamon menu, but only if the applet with the slowed popup menu is waiting for the release. So, i think there are not an actually applicable case right now (but yes, this is not perfectly), and i think would not be perfect without come back to the old implementation of mouse release instead of mouse press.

As resume, the patch just decreased the number of occurrence of this problem. From always happens to will happen only in certain contexts, when there is no choice but to swallow the release of the mouse to avoid the activation of an unwanted item.

**Comment by JosephMcc** [comment] 2015-11-10 03:44
Okay, I'm going to close this. If the problems still shows I can always reopen it.

**Closed by JosephMcc** 2015-11-10 03:44 UTC
Labels: BUG
