### ISSUE TITLE
New mouse pointer bug

### ISSUE THREAD

**Issue by stablecloud** [linuxmint/cinnamon#11533] opened 2023-02-28 11:46 UTC
OS: Linux Mint 21.1 Cinnamon
Cinnamon: 5.6.7
Uname: 5.15.0-60-generic

With the release of 21.1 the new Bibata-Modern Classic mouse pointer theme is set as default, and I've now reverted this to DMZ-White as my preferred mouse pointer theme. However, in some instances, such as opening Chrome extensions, and in some instances Virtualbox the pointer reverts back to Bibata when hovering over this particular window. Once the pointer is moved away that particular window it reverts back to DMZ-white.

Please see attached screenshots demonstrating this bug. 

![Screenshot from 2023-02-28 11-45-35](https://user-images.githubusercontent.com/123074026/221845201-a2221655-d0e9-4460-9b55-3787745d5b67.png)

![Screenshot from 2023-02-28 11-44-55](https://user-images.githubusercontent.com/123074026/221845193-413e2745-79c5-42ed-8533-57839fb595c5.png)

**Comment by anaximeno** [comment] 2023-03-04 21:22
This is a duplicate of https://github.com/linuxmint/cinnamon/issues/11341. 

The most fast solution is using the following command to choose the preferred cursor:

```bash
sudo update-alternatives --config x-cursor-theme
```

An then restart those applications for changes to be applied.

**Comment by JosephMcc** [comment] 2023-03-05 14:34
As noted this is a duplicate.

**Closed by JosephMcc** 2023-03-05 14:34 UTC
