### ISSUE TITLE
Display applet in Settings causes system freeze

### ISSUE THREAD

**Issue by Dad4Linux** [linuxmint/cinnamon#6224] opened 2017-01-25 23:32 UTC
Linux Mint 18.1 crashes and completely unresponsive when connected to projector on a Dell Latitude D630 laptop or to an external monitor via DisplayPort on a Lenovo T430 laptop.  As soon as the resolution or if the "mirror displays" option changes, the desktop background, any open windows, as well as the menu bar splits and the system freezes. System unresponsive to any keystrokes; Cinnamon menu button does not work. Disconnecting the external monitor or projector does not unfreeze the computers. Cannot recover except by powering off the laptops.  Please see attached photos and screen shots for system info for both laptops running Cinnamon 3.2.  However, Linux Mint 17.3 Display Settings app works with no issues on both laptops.

Screen after unchecking "mirror displays" option on Dell laptop connected to Acer PD113 DLP projector:
![img_5347](https://cloud.githubusercontent.com/assets/25355969/22313467/f468fa16-e35c-11e6-8eb7-46fad42cc3b0.JPG)

Photo of frozen screen from the projector (note: the Cinnamon menu bar not completely at bottom of screen as in the laptop screen):
![img_5348](https://cloud.githubusercontent.com/assets/25355969/22313466/f4315106-e35c-11e6-95f2-a7875a194b65.JPG)

System info for Lenovo T430 laptop:
![t430-specs](https://cloud.githubusercontent.com/assets/25355969/22313502/26fd75ba-e35d-11e6-9847-cf55113ef5c0.png)

System info for Dell Latitude D630 laptop:
![dell-d630-cinnamon-freeze](https://cloud.githubusercontent.com/assets/25355969/22730971/6169d450-ede9-11e6-84bf-6e291be4676a.png)

**Comment by Marko-M** [comment] 2017-02-07 07:56
Same here with Dell 7559 and any external display (HDMI)

**Comment by zmertens** [comment] 2017-02-07 20:53
I have this issue sporadically when I plug in an HDMI cable to my laptop. Sometimes, if I leave the laptop in a suspended state, plug in the HDMI, and then wake up the laptop the resolution will adjust but most of the time it freezes the system.

 - Linux Mint 18 "Sarah"
 - Cinnamon 3.0.7
 - HP ProBook 440 G3

**Comment by nralbers** [comment] 2017-03-17 10:48
I have this same issue when attempting to change my multi-monitor display geometry (move the second display position).
- Linux Mint 18 "Sarah"
- Cinnamon 64-bit
- Asus SonicMaster S301L

Steps to reproduce:
1. Open the Display applet
2. Move the display to it's actual position
3. Hit Apply.

At this point the display will "Scramble" and the confirmation dialog will not display. After the confirmation dialog timeout, the display will reset to another invalid combination. At all points after hitting Apply, the mouse is visible, but nothing is clickable. You can recover by dropping to a system terminal (Ctrl-Alt-F1) and killing the xorg process.

Workaround:
- Use arandr tool to modify display. Downside: changes made here will reset after system sleep or restart.

**Comment by kameranis** [comment] 2017-05-04 22:20
Same here on Mint 18.1 and Toshiba Satelite P755 with Nvidia GeForce 540m. Disconnecting my second screen, closing the lid, altering display settings through display app. When are we expecting a solution to this? (By the way, my installation is new, ran fine on Mint 17.2)

**Comment by Dad4Linux** [comment] 2017-06-07 15:30
Problem persists in the beta release of Mint 18.2 Sonya Cinnamon version.

**Comment by clefebvre** [comment] 2017-06-08 16:24
This is actually an issue in muffin. I'll leave it open here because other people are likely to be looking for it here.

We're chasing it, we've no solution for it yet.

**Comment by akrus** [comment] 2017-06-30 06:38
Well, I have to stick with Intel driver as DisplayLink USB docking station doesn't work with modesetting. Do you know why it's working fine with GNOME 3 and doesn't in Cinnamon?

**Comment by mtwebster** [comment] 2017-07-04 04:49
Gnome-shell and Cinnamon have diverged so much it'd be hard to say.  Some of the main libraries we use, they've copied entirely into their window manager code, so they basically maintain their own copies now.  The only thing that springs to mind that might help your particular issue is xrandr was re-done there.  That's something we've considered porting eventually.

You said the docking station doesn't work with modesetting - have you tried recently?  I only ask because everyone I've talked with over this has had poor prior experience with modesetting, then they try it, and it seems to have been greatly improved (relatively recently?)

**Comment by akrus** [comment] 2017-07-07 06:36
I've just tried modesetting driver - it simply hangs the system when I connect the docking station. It doesn't even work with Pageflip off as mentioned here:
http://support.displaylink.com/knowledgebase/articles/1181623-displaylink-ubuntu-driver-after-recent-x-upgrades

**Comment by leigh123linux** [comment] 2017-07-07 11:05
@akrus Your issue belong at ubuntu bug tracker or  DisplayLink, wringing here is never going to result in a fix as mint doesn't provide intel. modesetting or  DisplayLink drivers!

**Comment by akrus** [comment] 2017-07-07 13:45
@leigh123linux, if you look above, you'll find out that it was response to @mtwebster. DisplayLink support is non-existent and Ubuntu bug tracker has nothing to do with it.

**Comment by netw0rkf10w** [comment] 2017-10-03 19:27
Same problem here with Linux Mint 18.2 on a Dell Precision M4800 workstation and a Samsung S27E390HS monitor. When setting Mirror Display it freezes and I have to force shutdown.

The problem only occurs for HDMI only (VGA works fine).

**Comment by niessen** [comment] 2017-10-06 12:51
I came here, because I had the same issue (with Mint 18.2 on HP 250 G5), and removing xserver-xorg-video-intel fixed it. Thanks!
Perhaps this driver should no longer be installed by default?

**Comment by pascal95** [comment] 2017-12-27 21:17
Thanks for the "fix" . 
just wondering why this is used and not "modesetting" if this has "better performance"...

**Comment by nixgeekgirl** [comment] 2018-01-12 19:38
I had the same issue after install a few items to watch a video.  I ran the apt remove xserver-xorg-video-intel command, and I rebooted.  Works great again.  Thank you!!

**Comment by Dad4Linux** [comment] 2018-01-19 12:14
Thank you Clem and Linux Mint team!  Your solution worked for me.  Should this be marked as solved/closed?

**Comment by clefebvre** [comment] 2018-02-01 10:06
Not yet.. the fact that it works in GNOME indicates there's a possible solution on our side (unless Intel hardcoded something specific for Mutter?).

**Comment by clefebvre** [comment] 2018-02-01 10:06
We're also moving to a new base, it's possible the driver might behave a little better there... let's see how things go, whether this issue gets old or whether it continues to affect people with Mint 19 and LMDE 3.

**Comment by cxubrix** [comment] 2018-03-15 14:05
Same here with HP EliteBook and Mint 18.3

**Comment by frostblooded** [comment] 2018-07-27 07:43
I had this same issue with both the nvidia-384 version 384.130-0ubuntu0.16.04.1 and the xserver-xorg-video-nouveau version 1:1.0.13+git20170208.1516d35b-0ubuntu0ricotz~xenial, but I fixed the problem when I started using nvidia-340 version 340.104-0ubuntu0.16.04.1

**Comment by camilotejeiro** [comment] 2018-08-25 16:28
Had exactly the same issue, after removing xserver-xorg-video-intel, it has been working without the display split freeze that used to happen upon changing display settings, 

Thank you!

**Closed** 2021-02-21 04:57 UTC
Labels: BUG
