### ISSUE TITLE
Animated and interactive desktop background

### ISSUE THREAD

**Issue by balooloo** [linuxmint/Cinnamon#2075] opened 2013-05-24 06:31 UTC
A nice feature that can enhance user experience is to implement an animated and interactive desktop background like Android one. 
This goal does not aim to replace desklets but to complement them with, for examples, procedural rendered background, picture cycles, image alterations, animations (fireworks, water ...) with eventually user interactions (mainly mouse clicking).

I don't know if the Android approach and API is the best. Using an HTML back-end like MDM can probably make that easier.

**Comment by valgusk** [comment] 2016-08-23 10:43
For those who can't wait/don't hope:
Take a look at _NET_WM_WINDOW_TYPE_DESKTOP. You can set it to any application and keep the nemo icons too if you want. I bet this is not advised, but currently it works for multiple applications to handle desktop. A bit hacky, but I currently do have a video wallpaper in cinnamon with icons, low cpu usage etc.

**Comment by echuber2** [comment] 2017-01-09 22:45
@valgusk Could you elaborate on how you did it? I search for some references and people seemed to be having trouble getting clicks on the desktop to work even if the window displayed as intended.

**Comment by JosephMcc** [comment] 2017-08-07 23:49
Closing this since it's outside of what we want to implement.

**Closed by JosephMcc** 2017-08-07 23:49 UTC
Labels: FEATURE REQUEST

**Comment by irfan798** [comment] 2017-11-23 15:15
So are there any progressions about this? Cinnamon already uses html/js for lots of stuff.
Can we implement webkit in desktop background like lightdm-webkit2-greeter?

If not, to achieve webgl and gif as wallpaper with icons and desklets intact, where should i start looking, cinnamon source code or nemo source code or just look for _NET_WM_WINDOW_TYPE_DESKTOP as @valgusk suggested?

Btw @valgusk could you elaborate on how you did it?

**Comment by valgusk** [comment] 2017-11-23 21:13
@irfan798 , you can see example here https://github.com/valgusk/windesktop

**Comment by LinuxOnTheDesktop** [comment] 2019-12-30 03:03
I'd like to second (or, given #3560, 'third') this request, if I may.
