### ISSUE TITLE
Sporadic CPU spikes with indicators enabled

### ISSUE THREAD

**Issue by Nihlus** [linuxmint/Cinnamon#5458] opened 2016-07-15 18:36 UTC
If Indicators are enabled in General settings, Cinnamon experiences sporadic CPU spikes on my system.

The CPU usage of one core will spike to 100% or more, hold there for up to three seconds, and then drop back down to 2-5%. This locks up the desktop and drops all input for the duration of the spike.

This install is a fresh install of Linux Mint 18, using an existing /home partition from Linux Mint 17.3.

System information:
![image](https://cloud.githubusercontent.com/assets/2340428/16884801/aada7868-4acb-11e6-9599-bed833a62a2f.png)

**Comment by lestcape** [comment] 2017-01-11 05:22
@Nihlus do you use an indicators witch animations? Skype, indicator-multiload? When you lost the connection, skype create an animation that can freezes cinnamon. Could be also possible other indicators... It's known that owncould could cause a higher CPU usage.

**Comment by hackoon** [comment] 2017-01-11 20:13
@Nihlus First try to update to 18.1  Serena. Cinnamon 3.2. run much better that 3.0. I got rid of almost all problems by the upgrade. If it persists look at the mentioned indicator related freeze.

**Comment by Nihlus** [comment] 2017-01-11 21:02
This bug was quite a while ago and I'd mostly forgotten about it. I'm no longer experiencing this issue on a new laptop with Mint 18.1.

**Comment by lestcape** [comment] 2017-01-11 23:59
@JosephMcc Can you close this?

**Closed** 2017-01-12 06:15 UTC
Labels: BUG

**Comment by Nihlus** [comment] 2017-01-15 00:08
Back again, unfortunately. It seems I was a little too quick to dismiss this issue, and it remains a problem. The issue did not present itself until I had rebooted and Cinnamon had been given a chance to restart (despite the fact that indicators activated and worked fine before the reboot), but once that had happened, it reared its ugly head again.

Repo steps:

- Open the "General" menu
- Enable indicator support
- Reboot the system
- Use the desktop normally. At this point, CPU spikes on multiple cores should begin occurring.

The system under which this happens now is the following:
Linux Mint 18.1 Serena, x64 Cinnamon Edition
Dell XPS 13 Developer Edition (Intel i5-6200U, Skylake)
Cinnamon 3.2.7

Of the installed applets, these two gain indicators when enabled:
blueman 2.0.4-1ubuntu2
redshift-gtk 1.10-5ubuntu1

**Comment by lestcape** [comment] 2017-01-15 02:49
@Nihlus Right now you can enabled or disable the indicator support and you will not need a cinnamon restart (or a reboot), like you can see. When you say CPU spikes on multiple cores. You say 100% of CPU? What program you use to see that? Are you sure you need a system reboot or this also occurs if you restart cinnamon? Will not occurs if you only enable the indicator support without a cinnamon restart or a System Reboot?

There are some indicators that need to be loaded with a delay, because they are not connected properly to the cinnamon indicator Dbus system and they required that the Dbus will be runner to export the data. In this case you need a delay on this indicator start and also if you restart cinnamon you will lost the connection and the indicator will disappear. I has redshift installed in my system, but without the autostart and i can not reproduced this in any way if i started redshift manually.  I will test blueman.

**Comment by lestcape** [comment] 2017-01-15 03:24
I also test Blueman and also it's the same i don't see any CPU spikes and if i see the cinnamon process, never it's more than 10%... I have also the indicator-cpufreq in my system... Well i have more indicators, but only this indicators are actively... I also check the auto-start for redshift and reboot my system...

Be sure that if you use indicators you will need cpu for that and be sure the indicator processing will occurs inside the cinnamon process... Anyway i don't see any difference about cpu usage in my system if indicators are enabled or not.

**Comment by lestcape** [comment] 2017-01-15 03:34
@Nihlus i also use the applet https://github.com/mtwebster/Cinnamonitor to monitor the cpu usage of cinnamon, i don't see anything up to 10% of CPU usage...

**Comment by Nihlus** [comment] 2017-01-17 21:37
@lestcape The issue only presented itself after I had rebooted my machine. I'm using the system monitor to view the CPU spikes. The spikes do not occur if I just restart Cinnamon, but they do begin occurring if I log out and back in again.

Here's a screengrab of some of the spikes. The system was playing a video in the background at this point.
![image](https://cloud.githubusercontent.com/assets/2340428/22040944/2f5f885a-dd05-11e6-82b4-4c1cac267466.png)

This is a screenshot of identical activity, but with indicators disabled and after a relog.
![image](https://cloud.githubusercontent.com/assets/2340428/22041038/8f153830-dd05-11e6-80c6-60bc9f53a466.png)

**Comment by lestcape** [comment] 2017-01-17 21:54
@Nihlus this is interesting, but do you see that all spikes occurs in one CPU and when they occurs, the others CPU decrease the usage? I can not give you any warranty, but I'm pretty sure with this little data of some things: 

This is an apparently fail to have of a good balance of the CPU usage in some certainly conditions. This probably can only be reproduced with some specific hardware (Intel processors? I have an AMD). This not mean an average increase of the microprocessing usage, and this not say me anything about a failure on the code that cause spikes in your system as a whole...

**Comment by Nihlus** [comment] 2017-01-17 22:02
@lestcape I'll try to provide any other information you might need. I only have access to Intel hardware at the moment, so I can't test it on other configurations.

**Comment by lestcape** [comment] 2017-01-19 00:39
@Nihlus What i try to say it's that you don't have CPU spikes with indicators enabled, you have a non optimal load balance of core usages with indicators enabled: https://software.intel.com/en-us/articles/load-balance-and-parallel-performance

I think it's important find:
1- If the thread that have 100% of usage it's where cinnamon is running. You need to explore a graph of the individual cinnamon process and find if also you can notices spikes there.
2- If the spike it's directly relate with a call in the cinnamon indicator code. This only need to be done if in the first point the spikes occurs in the cinnamon process. The way could be print a log on all indicator activity. In the begin of the code of all indicators.

If point 1 fail, this mean the spikes are not directly relate with cinnamon... Probably related with other thing that dislike what cinnamon it's doing... the fix probably need to be in this process, no in cinnamon...

If point 2 fail, but not 1, the indicators code in java script are not the directly cause of the spikes, the problem could be related with something in cinnamon, thats dislike something in the indicator code.

I can not released  this test as i can not notices anything of this. You can?

**Comment by lestcape** [comment] 2017-01-19 01:02
@Nihlus Just for record, cinnamon have only one thread, the compositor thread, so there are nothing that we can do to split our processing to optimized the load balance of the cores. In an idle state, cinnamon not use cpu but when indicators are actively the indicator manager run inside the cinnamon process and of course use cpu.

Probably, your video player have enable the multi-thread for decoding videos and they have a low priority, more lower than the cinnamon process priority as the cinnamon process have a  high priority because it's your desktop process. Then as cinnamon run in one thread and this thread probably use only one core as the task can not be splinted the other cores decrease the load to help the thread with more priority (the cinnamon thread) and thats it's only what happen. 

All that not explain why this occurs in some conditions and not in others, but i'm not an expert of multi threading programing and less an expert in the microprocessing architecture.

**Comment by Nihlus** [comment] 2017-01-19 13:36
I'm afraid I'm not able to run a debugging session or a source build of
cinnamon at this time. What program would you recommend for diagnosing the
process graph of cinnamon?

On 19 January 2017 at 02:02, Lester Carballo Pérez <notifications@github.com

**Comment by lestcape** [comment] 2017-01-21 02:45
@Nihlus sorry, but i can not help on this... Good luck.
