### ISSUE TITLE
Window title outside the screen

### ISSUE THREAD

**Issue by Manazius** [linuxmint/cinnamon#4611] opened 2015-09-11 20:31 UTC
Hello! 
I have a problem with the window title. They go outside the screen when I open the application in maximized window. Why?
Screen Resolution: 1366x768
GPU: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
Distro: Monjaro Linux

**Comment by ManIVIctorious** [comment] 2015-09-14 08:13
Can you please add a screenshot to explain better what your issue is?
Does this happen with all applications or only with specific ones (gtk applications tend to this behaviour, since they have a minimum width/height, which could be more than your screen resolution)?

**Comment by JosephMcc** [comment] 2016-05-13 06:39
Linking https://github.com/linuxmint/Cinnamon/issues/4621 since it's likely related.

**Comment by JosephMcc** [comment] 2016-05-13 06:46
I finally managed to reproduce this using Eye of Gnome on Cinnamon3. It doesn't happen every time though. Weirdly when you grab the titlebar to pull it loose from the maximized state it first snaps into the proper maximized position and then pull loose.

**Comment by Vahan86** [comment] 2019-08-05 20:42
@Manazius is this still an issue in Cinnamon 4?

**Comment by JosephMcc** [comment] 2019-08-09 14:33
This is ancient and haven't seen it happen in forever. Closing until someone comes across it again.

**Closed by JosephMcc** 2019-08-09 14:33 UTC
Labels: BUG REPRODUCED
