### ISSUE TITLE
Vertical panels: No menu icon and hovering over an applet at a corner

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5748] opened 2016-10-02 19:00 UTC
I know that the vertical panels are still in progress and maybe this is already fixed or known, but I wanted to mention it in case it isn't.

(1) In the menu applet you can choose to have a custom icon. You can also choose to have no icon at all. That's a problem with vertical panels, because then the applet is gone. I know, who does that, huh? I don't even know what behavior I would expect at that situation. Maybe using the first letter of the word "Menu" (in the respective language) or something like that?

I'm not sure if the second one is a themeing issue (I'm using Mint-Y):
(2) Imagine you have a vertical panel, here for example left panel, without any horizontal panels. In the top left or bottom left corner you have an applet, for example the menu applet.
I you hover with your mouse to the very edge of the corner the menu applet isn't selected/hovered/green.
With horizontal panels that's not a problem at all.

**Comment by JosephMcc** [comment] 2016-10-03 00:46
#2 Might be addressed by this: https://github.com/linuxmint/Cinnamon/commit/ccf753c185d162ff32dda738f1f1f2b36daa73f2
Themes besides for the stock theme may still need some tweaking though since this just went in today. It makes the layout of applets in a vertical panel fill the full horizontal width like they do vertically in a horizontal panel.

**Comment by brownsr** [comment] 2016-10-22 10:10
It would appear most likely to be a theme issue.  There is a thin inactive strip at top and bottom of vertical panels. Sides are fine.  I can't reproduce this issue in mint-x themes, or the linux mint theme,  but I can make it happen in mint-y, and the base cinnamon theme.

**Comment by NikoKrause** [comment] 2016-10-22 13:37
Yeah, I wasn't sure about (2).
But (1) isn't a theme issue.

**Comment by brownsr** [comment] 2016-10-22 18:46
I cannot reproduce any problem in your case 1).  I always get a default icon, the one that looks like a cog, even if I do my best to try to clear it out.  If you can reproduce this using the latest git version please say how !

**Comment by NikoKrause** [comment] 2016-10-22 19:20
@brownsr 
Sorry, if it was unclear what I meant. When you open the settings of the menu-applet, you have to turn on the switch in "Use a custom icon". Then you are getting the cog as icon, because the Icon path below says `/usr/share/cinnamon/theme/menu-symbolic.svg`. You have to delete this path. Then you have no icon at all.
The applet isn't gone, but it's invisible. If you go to the corner it's still there as a small stripe.

Now that I'm writing this, I'm not sure if it's an issue, that should be solved.
Because you can get this issue also with horizontal panels.
When you delete the icon path and also the "Menu" text, you have the same result with the menu-applet in horizontal panels.

**Comment by JosephMcc** [comment] 2016-10-24 03:14
I don't really see this as an issue. If you set the icon to nothing and the text to nothing, it behaves just as expected.

**Closed by JosephMcc** 2016-10-24 03:14 UTC
Labels: BUG
