### ISSUE TITLE
[Feature Request] Option to allow hotcorners during fullscreen

### ISSUE THREAD

**Issue by FlowXP** [linuxmint/cinnamon#8682] opened 2019-07-01 20:20 UTC
```
 * Cinnamon version (**4.0.10**)

 * Distribution - (Mint 19.1)
 * Graphics hardware - xserver-xorg-video-nouveau
 * 64 bit

 **Issue**
Hot Corners are not working at all when youtube/smplayer/vlc/virtualbox is in full screen.
**In LM 17.1 this was working perfectly**


**Steps to reproduce**
Open youtube or smplayer in fullscreen and if you move the mouse to the configured corner, nothing happens. In any other situation the hot corners are working fine.


**Other information**
Fresh install Linux Mint 19.1
Hotkeys are working fine in fullscreen

**Comment by LinuxOnTheDesktop** [comment] 2019-07-29 15:58
A perhaps related problem is as follows. When running Mint 19.1 in a VirtualBox VM on Windows, the VirtualBox toolbar - the one that is meant to be at the bottom of the screen (or, if one flicks a switch, at the top) shows only when booting the VM and not afterwards. This causes inconvenience and does not occur when I run Windows in a VirtualBox on Mint.

Possibly the faut is with VirtualBox itself, but I can imagine the VB people blaming Mint . .

**Comment by FlowXP** [comment] 2019-07-29 18:56
I am aware of that, but this is not on a virtual machine.
This is on my daily driver - my laptop - connected at a tv screen

**Comment by germanfr** [comment] 2019-07-30 17:01
I guess this is not a bug but a feature.

**Comment by FlowXP** [comment] 2019-07-30 17:11
true but if this was working 2 years ago, I thought it's a bug involved

**Comment by mtwebster** [comment] 2019-07-31 23:52
I checked in cinnamon 3.6 and 4.0 (mint 18.3 and 19.1, respectively), and in neither did hotcorners work.  If anything I think the fact they were working in fullscreen would have been considered the bug, not the other way around.

I can envision a couple uses for hotcorners during fullscreen, so for now I'll leave this open and call it a feature request, until we can evaluate it more.

**Comment by FlowXP** [comment] 2019-08-01 20:33
Thank you !!

**Comment by icarter09** [comment] 2019-11-28 03:03
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Closed by icarter09** 2019-11-28 03:03 UTC
Labels: FEATURE REQUEST, Reviewed
