### ISSUE TITLE
Mint 17.1 - Cinnamon Becomes Unresponsive

### ISSUE THREAD

**Issue by NeoGeo64** [linuxmint/Cinnamon#3798] opened 2015-01-01 22:41 UTC
Hey guys! Sometimes when I am using 17.1 Cinnamon I encounter a situation where the GUI becomes unresponsive except for being able to right-click on any open window on the taskbar and click on close. Then, and only then, will the rest of the GUI become responsive again (minimize and other window buttons, desktop icons are able to be clicked on again, Menu works again, etc). I didn't encounter this in 17.0. My system is "up to date" as of right now.

My hardware specs are as follows:

Dell XPS 8700
i7 4770k 3.4GHz
8GB RAM
1TB HDD
AMD Radeon HD 7570 w/ 1GB RAM
Free X.org drivers

I've also posted this issue over @ the Linux Mint forums.  Click on the following link to view it. <a href="http://forums.linuxmint.com/viewtopic.php?f=47&t=185072">*Linux Mint Forums - Cinnamon Unresponsive*</a>.

This has been going on for a while now and no one on the forums have been able to find out what's going on.  I'm apparently not the only one experiencing this issue.

Anyone know what's going on?  Cinnamon may need to be fixed and released as a new version...

**Comment by daviday** [comment] 2015-01-02 01:07
Tony I too am having similar issues in re to installing a flawless version of linux that suites my needs. Can I ask what were the steps that you took to install?

**Comment by NeoGeo64** [comment] 2015-01-02 02:50
I'm not too clear on what you're asking but if you're asking me how I 
installed Linux MInt 17.1, I installed it with a burned DVD.

It's a weird problem that happens from time to time.  It won't crash the 
system but it's definitely something that needs to be addressed.

Who's with me?

**Comment by daviday** [comment] 2015-01-02 03:09
I'm with you. There is or will be a fix to this - especially if it's not isolated to your machine.

**Comment by lestcape** [comment] 2015-01-02 19:11
I'm not note a thing like that, but what occurs me is a delay on open a video file... While more videos i open, more time is needed to open a new video. I have an ATI video card to. Tested with SMPlayer and VLC.

**Comment by NeoGeo64** [comment] 2015-01-03 16:42
This may be a blanket issue or maybe just an issue for Linux Mint 17.1 users (not sure if this is isolated to Cinnamon).  But it seems LInux Mint Cinnamon 17.1 with an AMD/ATI video card are experiencing this issue.

Where are the developers?  Do they read the posted issues?

**Comment by daviday** [comment] 2015-01-03 17:06
I'm reading. Having difficulty keeping track as things have changed drastically and I'd rather not look like a fool. 
The issues seem to be with the translation differences from 14.03 to 14.10 in re to the desktop GUI. If you're using this for mobile/tablet compatibility - kde or xfce may be better for you.

**Comment by NeoGeo64** [comment] 2015-01-03 17:12
I currently only have a desktop computer.  The system specs are in my original post.

**Comment by NeoGeo64** [comment] 2015-01-16 20:08
Well, has anyone else been having this issue or perhaps hacked up a fix for now?

It's been a couple of weeks and no activity on here so I decided to check on it and let everyone know that I still am watching this.

**Comment by mtwebster** [comment] 2015-01-16 20:10
There have been a lot of fixes in the last couple weeks towards resolving this issue, if anyone is interested in testing, you can try the nightly ppa.  There will likely be an update rolled out to users in the coming days/week.

**Comment by arfett** [comment] 2015-01-18 22:32
Same issue. Every 10 minutes or so the taskbar becomes entirely unresponsive until I alt+tab between a few windows and then it starts working again. I have been unable to pin down exactly what I'm doing that triggers this.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3f
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  4200 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux Mint 17.1 Rebecca (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.18.0-031800-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 346.35
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x10de
    DeviceID:  0x1380
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3600 x 1080
    Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                            59.7cm x 33.6cm  (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC1150
    
Memory:
    RAM:  15942 Mb
```

**Comment by HerrDIerk** [comment] 2015-02-01 12:25
Same story here.  When Cinnamon freezes, I have to open a new program, mostly Firefox. (I can only click on the menu-icon).  That's the only sollution for me. Alt-Tab and other related stuff works fine, so I don't know where the bug is comming from.

**Comment by NeoGeo64** [comment] 2015-02-04 04:54
*Something* needs to be done about this bug!

**Comment by lestcape** [comment] 2015-02-15 06:12
Please see that i do not recommend update the firmware of the motherboard, this could be dangerous.

I'm downgraded the motherboard firmware for another matter, and i detected this problem. When i finished, i was updated the firmware to the last version again and problems disappear...

**Comment by arfett** [comment] 2015-02-16 16:48
This issue has nothing to do with your motherboard BIOS...

**Comment by lestcape** [comment] 2015-02-16 18:01
@arfetti I experimented the same problem described here. I don't say that is related or not, and you don't know this... Is clear that this bug is not for all cinnamon user, and this is my point. Some special driver or hardware, apparently cause this problem. So, i can not be sure of if can be relate or not.

**Comment by liamdawe** [comment] 2015-03-01 13:51
I am also getting this issue, and it's starting to become a real problem.

**Comment by mtwebster** [comment] 2015-03-01 19:08
Please see this: https://github.com/linuxmint/Cinnamon/issues/2946#issuecomment-76622190

**Comment by lestcape** [comment] 2015-04-07 04:40
I need to thinking that the problem is pretty relate with muffin. I need to restart my computer more than 8 time per day.

**Comment by dalcde** [comment] 2015-05-04 21:52
#4072

**Closed by dalcde** 2015-05-04 21:52 UTC
