### ISSUE TITLE
Open menus prevent locking

### ISSUE THREAD

**Issue by MavropaliasG** [linuxmint/Cinnamon#6237] opened 2017-02-02 03:16 UTC
Hello,

When a menu is open (e.g. the wifi, weather, battery, applet menus etc) mint cannot lock the screen neither by pressing Ctrl + Alt + L, nor by automatic timeout locking (locking the screen after 15 min of inactivity). Also if I close the lid of my laptop, the laptop goes to suspend but does not lock the screen, so when it resumes I go straight to the desktop with no lock screen.

This was an issue in mint 17.3 and I have reported it previously in an applet ( https://github.com/collinss/Cinnamon-Sticky-Notes/issues/9#event-945820474 ).

**Comment by leigh123linux** [comment] 2017-02-02 06:10
Duplicate of https://github.com/linuxmint/cinnamon-screensaver/issues/93

**Closed by leigh123linux** 2017-02-02 06:10 UTC
