### ISSUE TITLE
Menu sometimes not always showing up on occasion 

### ISSUE THREAD

**Issue by BloodFever5634** [linuxmint/Cinnamon#4887] opened 2015-11-28 05:39 UTC
PLEASE FIX ASAP it is annoying and makes it hard to use

![51fzxgutzll _sy300_](https://cloud.githubusercontent.com/assets/15885291/11450300/bf18f144-9557-11e5-8364-25b38f247882.jpg)

**Comment by BloodFever5634** [comment] 2015-11-29 00:31
Bump

**Comment by BloodFever5634** [comment] 2015-11-29 00:32
Also doing alt+f2 thane typing in r FIXES it temporarollly

**Comment by irrenhaus3** [comment] 2015-11-29 03:15
If you want your issues resolved, it's crucial to give the developers more information on what's happening and what the circumstances are. Is there a (so to speak) rule to this behaviour? Like, does the menu only appear with certain settings and doesn't appear with other settings? What did you do to come across the bug? The devs don't know about your config or the software you're running, so you'll have to work with them, not just post "fix ASAP pls" and rely on black magic to make problems go away.

**Comment by BloodFever5634** [comment] 2015-11-29 03:42
@irrenhaus3 THANKS for finally replying, I have a alienware 17 laptop with 64gibs of ram, gtx980m grafics card, a blu-ray cd drive, and a core i7 8 cores That is my config it goes away when i try to use it all the time and needs to be fixed quickly as it makes the system really hard to use. ThanKS

**Comment by irrenhaus3** [comment] 2015-11-29 05:45
Sorry, but that's not helpful. If the problem is resolved by restarting Cinnamon, it's unlikely to be hardware related - if it was, it would persist over the restart, since (as far as I know) Cinnamon doesn't rely on specific CPU and RAM builds and graphics driver issues don't usually manifest themselves in non-appearing menus.  
It would be a lot more helpful to know:
* What exactly happens? Which menu causes trouble? Context menues? The main menu? Dropdown menus in the application panel? The issue's title doesn't make that very clear.
* What are the occasions on which the menu does or doesn't appear? The title also doesn't make that clear.
* Can the problem be reproduced by following the same steps with the same setup?
* Which version of Cinnamon are you using? If what you're describing is a bug, it might already be fixed in a more recent version. Have you looked into the other issues yet?
  
Bug reports need to be more than "Doesn't work, please fix it", otherwise the devs won't be able to get behind it. idk how much experience you have with software development, but as soon as the project starts getting bigger, it becomes impossible to track down a vague problem description like "feature XYZ sometimes doesn't work" because noone involved could possibly know everything about every part of the software. To determine where the bug is in the code, you as the coder need to have enough information to draw the essential conclusions.

**Comment by JosephMcc** [comment] 2015-11-29 08:23
> Bump

Please don't do this.

**Closed** 2015-11-29 08:33 UTC
