### ISSUE TITLE
Cinnamon crash on Chrome and Chromium when move DOM objects in DevTool

### ISSUE THREAD

**Issue by alejandrosobko** [linuxmint/Cinnamon#5670] opened 2016-09-10 15:07 UTC
Hi! 
Using Google Chrome or Chromium when I move DOM objects in the dev tools all the system is frozen, only can reboot from command line (ctrl + alt + F1).
This issue was described here [#4789](https://github.com/linuxmint/Cinnamon/issues/4789) but this fix (those .deb in the comments) is applied in my system by default in linux mint 18 and the problem continue.
Additional: In Firefox I haven't problem moving DOM objects.

I have:
- Asus zenbook pro ux501
- Linux mint 18 cinnamon 64 bits
-  Kernel 4.4.0-34-generic (I tried with 4.6.4 and 4.7)
- nvidia-367 driver

**Comment by mainmachine** [comment] 2016-09-13 06:34
Hmmm... Chrome and Chromium do interact with the graphics driver, and there's not much else there in what you've described that would likely hard-lock a system...

There's a slightly newer version of nvidia-367 in the Ubuntu graphics driver ppa: https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

I've just upped to the 370 and they are working well on an 860m and 960, and I was using 367 from that ppa previously with no problems...

I suggest testing the newer 367, then 370 if that doesn't resolve your issue.

**Comment by alejandrosobko** [comment] 2016-09-15 00:23
@mainmachine Thanks for reply. I tried with nvidia 370 driver but the problem continues..

**Comment by mainmachine** [comment] 2016-09-18 13:27
I went back and read the thread you initially linked to, and the conclusion there is that this is caused by a Chrome/Chromium issue, so until they fix it at the source...

**Comment by JosephMcc** [comment] 2016-09-18 17:17
Have you had the chance to try this under any other DE? Can you reproduce it there?

**Comment by alejandrosobko** [comment] 2016-09-18 22:25
Sorry but I don't have another DE...

**Comment by Odyseus** [comment] 2016-09-19 09:37
Hello, g@ys.

I can reproduce this in my real system (specifications at the end of this message). I opened Chromium, opened the developer tools and went to the **Elements** tab. Dragging a DOM element froze my system immediately. Couldn't even exit to any tty nor do a Ctrl + Backspace. Had to force a restart with the button of my tower. After restart, my **/var/log/syslog** file show the following error:

```
Sep 18 19:30:45 cinnamon kernel: [56231.729995] NVRM: GPU at PCI:0000:02:00: GPU-bbdbf8b1-70dc-a013-f582-98dbc112e32b
Sep 18 19:30:45 cinnamon kernel: [56231.730002] NVRM: Xid (PCI:0000:02:00): 13, Graphics Exception: ChID 0003, Class 00008297, Offset 00001530, Data 00000001
```

I tested it on my virtual machine with Cinnamon nightly. Chromium wouldn't event start. The screen went nuts with visual glitches and had to force a restart of the virtual machine. After a short research, this is happening with Chromium/Chrome on Virtualbox for several versions now. To fix it, I had to disable 3D acceleration on the virtual machine, open Chromium (with Cinnamon in software rendering mode it opened ok) and uncheck the option **Use hardware acceleration when available** on Chromium's advanced preferences. Restarted the virtual machine with 3D acceleration enabled and opened Chromium. Moving DOM elements works fine without the system freezing.

I tested it on another virtual machine with Ubuntu Gnome. I had to take the exact same steps that I described in the previous paragraph to make Chromium work and not hang when moving DOM elements.

I tried to move DOM elements again on my real machine, but this time with the option **Use hardware acceleration when available** disabled. The elements can be moved and system didn't froze.

### My system information
**Kernel:** 4.4.0-21-generic x86_64 (64 bit)
**Desktop:** Cinnamon 3.0.7
**Distro:** Linux Mint 18 Sarah
**Mobo:** MSI model: MS-7374 v: 1.0 Bios: American Megatrends v: V3.9 date: 10/25/2010
**CPU:** Quad core AMD Phenom II X4 955 (-MCP-) speed: 3200 MHz (max)
**Graphic card:** NVIDIA G94 [GeForce 9600 GT]
**Display Server:** X.Org 1.18.3 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
**GLX Renderer:** GeForce 9600 GT/PCIe/SSE2 GLX Version: 3.3.0 NVIDIA 340.96

**Comment by mtwebster** [comment] 2016-09-19 12:19
This should be fixed (once more) in Cinnamon's nightlies by https://github.com/linuxmint/muffin/commit/79720a374f40582b79dc1c5438c2f809933c53be

**Closed** 2016-09-19 12:19 UTC
