### ISSUE TITLE
Hot Corner (expo) prohibits screen lock when returning from suspend.

### ISSUE THREAD

**Issue by Feighery** [linuxmint/Cinnamon#920] opened 2012-07-16 10:39 UTC
When hot corner is active and the laptop lid is closed to invoke sleep, the laptop sleeps without issue. Upon opening the lid later, the system restores but the screen is not locked. You can return to normal desktop from expo and operate as normal without entering a password. 

Similar to trying to lock the pc with ctrl+alt+L in expo mode, it will not lock.

**Comment by nyeates** [comment] 2016-02-22 22:04
Issue persists in Cinnamon 2.6.13

**Comment by nyeates** [comment] 2016-02-23 00:24
I would suggest closing this ticket and maybe opening a separate ticket against expo and scale.

The erroneous functionality described in the original description above is not accurate as of cinnamon 2.6.13 on fedora.

What is actually occurring is that, expo (Show all workspaces) and scale (Show all windows), very specifically, do not allow you to go to lock screen while you are using their functionality. You can verify this by putting your mouse in the middle of the desktop (not on a hot corner), initiating expo manually (ctrl+alt+up-arrow), and then trying to lock your desktop (ctrl+alt+L). It wont work. Same with scale.

Again, try Hot Corners set to 'Show the desktop' options, and ctrl+alt+L works fine. So its not Hot Corners causing this, it is a bug or feature of expo and scale.

**Comment by ManIVIctorious** [comment] 2016-09-10 19:16
@JosephMcc I think this is due to the same cause as #1430

**Comment by JosephMcc** [comment] 2016-09-10 19:32
@ManIVIctorious I think the root cause is the same but I'll leave it open for now.

**Comment by JosephMcc** [comment] 2016-09-27 19:11
Linking some issues that have the same root cause
https://github.com/linuxmint/Cinnamon/issues/1430

**Closed by JosephMcc** 2016-09-27 19:11 UTC
Labels: BUG, BUG REPRODUCED
