### ISSUE TITLE
No way to change default keyboard layout in login screen

### ISSUE THREAD

**Issue by tobami** [linuxmint/Cinnamon#3483] opened 2014-09-11 08:07 UTC
Removing the "Regional settings" module had a probably unintended consequence: the default keyboard layout for the login screen cannot be changed.

That was previously in "Regional Settings" under the tab "System". There you could copy "Your settings" to "system settings", so that "Input Source" was changed. In Cinammon 2.2 that is no longer possible.

My suggestion would be to add a new checkbox option to the "Keyboard Layouts" in the Keyboard settings module, so that you can set any selected layout as the system/mdm default. It would of course need superuser rights, and could be situated below the current two radiobox options ("Use the same layout for all windows", "Allow different...").

**Comment by dalcde** [comment] 2015-05-06 21:22
Duplicate of #3048

**Closed by dalcde** 2015-05-06 21:22 UTC
Labels: BUG, BUG REPRODUCED
