### ISSUE TITLE
Update Manager won't update any Flatpaks if at least one Flatpak is excluded

### ISSUE THREAD

**Issue by KW57** [linuxmint/cinnamon#11874] opened 2023-09-28 09:11 UTC
### Distribution

Linux Mint 21.2 Cinnamon

### Package version

5.8.4

### Graphics hardware in use

Advanced Micro Devices, Inc. [AMD/ATI] Cezanne

### Frequency

Always

### Bug description

Summary: Update Manager will only install Flatpak updates if ALL available updates are selected. If I exclude (i.e. block) a particular Flatpak update, leaving another one ticked for update, then click 'Install Updates', nothing happens.

More Details: Flatpak org.zdoom.GZDoom version 4.11.0 caused a crash when launching the game Doom. So I rolled this back (installed a previous version 4.9.0) and all was well. As expected Update Manager then re-listed org.zdoom.GZDoom version 4.11.0 for update, which I excluded (i.e. added to blocked packages list). Today Update Manager listed org.freedesktop.Platform as requiring an update, but when I clicked on 'Install Updates' (yes, it was ticked), nothing happened. When I removed org.zdoom.GZDoom from the blocked I could then apply the updates. So it seems that no Flatpak updates get applied if ANY flatpak updates are excluded (blocked). I would have expected the Update Manager to have updated org.freedesktop.Platform successfully and left org.zdoom.GZDoom excluded.

I know I can apply selected Flatpak updates via the Terminal, but I really appreciate the convenience of having Flatpak updates incorporated into the Update Manager!

### Steps to reproduce

If there are two or more Flatpak updates pending in Update Manager, exclude one (i.e. add to blocked list) then restart Update Manager and attempt to install the remaining Flatpak updates by clicking the 'Install Updates' button. For me, nothing happened.

### Expected behavior

Update Manager to install updates for all selected Flatpak updates, regardless of what is or isn't exluced.

### Additional information

System:
  Kernel: 6.2.0-33-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33
    wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Gigabyte product: B550M DS3H v: N/A serial: <superuser required>
  Mobo: Gigabyte model: B550M DS3H serial: <superuser required> UEFI: American Megatrends LLC.
    v: F14 date: 01/04/2022
Graphics:
  Device-1: AMD Cezanne vendor: Gigabyte driver: amdgpu v: kernel pcie: speed: 8 GT/s lanes: 16
    ports: active: HDMI-A-1 empty: HDMI-A-2 bus-ID: 05:00.0 chip-ID: 1002:1638
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: HDMI-A-0 mapped: HDMI-A-1 model: BenQ GL2450H res: 1920x1080 dpi: 92
    diag: 609mm (24")
  OpenGL: renderer: RENOIR (renoir LLVM 15.0.7 DRM 3.49 6.2.0-33-generic)
    v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1 direct render: Yes
Repos:
  Packages: 3374 apt: 3361 flatpak: 13
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //www.mirrorservice.org/sites/packages.linuxmint.com/packages victoria main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/opera-stable.list
    1: deb https: //deb.opera.com/opera-stable/ stable non-free
  Active apt repos in: /etc/apt/sources.list.d/spotify.list
    1: deb http: //repository.spotify.com stable non-free
Info:
  Processes: 347 Uptime: 40m Memory: 14.96 GiB used: 2.7 GiB (18.0%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12/9 Client: Unknown python3.10 client inxi: 3.3.13

**Comment by leigh123linux** [comment] 2023-09-28 10:52
Duplicate of https://github.com/linuxmint/mintupdate/issues/846

**Closed by leigh123linux** 2023-09-28 10:52 UTC
