### ISSUE TITLE
Can't switch between full-screen windows anymore

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/Cinnamon#7534] opened 2018-05-02 02:24 UTC
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.1

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch

 * Graphics hardware *and* driver used
Nvidia 390.48 

 * 32 or 64 bit
64bit
 ```

**Issue**
After upgrading to 3.8.x Cinnamon, full screen functionality has changed. The issue is that if you have multiple windows in full-screen mode (say, images opened with `xviewer`,) you cannot switch between them with Alt-Tab anymore. 

**Steps to reproduce**
1) Open two images with `xviewer`.
2) Put the first one to Full-screen mode (double-click on it or hit F11)
3) Alt-tab to the second one and put it into full-screen mode
4) Try to switch between them with Alt-Tab
... you can't.

**Expected behaviour**
Ever since I remember using `Cinnamon`, you could switch between two full-screen applications. Something changed in 3.8.x

**Other information**

**Comment by itzexor** [comment] 2018-05-02 03:01
Duplicate of https://github.com/linuxmint/muffin/issues/316

**Closed by itzexor** 2018-05-02 03:01 UTC
