### ISSUE TITLE
Make cinnamenu the default cinnamon menu?

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon#9714] opened 2020-11-22 00:21 UTC
@clefebvre @mtwebster 

Hi, I've been trying to develop cinnamenu as a suitable replacement for the default cinnamon menu applet and was just wondering if you had any thoughts about that. I would be happy to fix bugs/issues in the future and make any changes that would need to be made which I could do either to cinnamenu or I could make a version of cinnamenu just for this purpose. At the moment I'm not sure what changes would need to be made to cinnamenu or indeed if replacing the default menu is of any interest or a possibility.

**Comment by ItzSwirlz** [comment] 2020-11-23 01:32
Ooh... This would require a lot of thinking.

Keep in mind-this doesn't affect Mint too-you need to imagine; how would this apply to Mint? But not just that-but how does this apply to **other distros** such as Ubuntu Cinnamon, Fedora Cinnamon, Debian, CentOS, etc.

And then it's maintaining-would Cinnamon devs/contributors like me (and you) want to swap out the menus?

And one last thing-should the old menu still be supported as a cinnamon spice that can be externally downloaded at the users choice?

It's a thinking task everyone has to think of.

I like both menus-but ultimately which one we should pick is the ultimate fate of what this DE was built for.

**Comment by Lurux** [comment] 2021-02-15 14:51
@fredcw, may I ask why you closed this issue ?

I came here to suggest exactly that. Has some internal discussions occurred since you opened this issue ? Can we know the rationale behind closing this ?

**As a reminder, Cinnamenu can be configured to look and behave exactly like the current cinnamon menu,** so I don't think compatibility or familiarity would be a problem.

On the other hand, I always found Cinnamon's menu to be very limited compared to other desktop's counterparts, so it would make sense replacing it with the much more flexible Cinnamenu...

**Comment by fredcw** [comment] 2021-02-16 01:37
@Lurux I only closed it because I wasn't sure if this was the right place to discuss this.

**Comment by Lurux** [comment] 2021-02-16 10:32
> @Lurux I only closed it because I wasn't sure if this was the right place to discuss this.

To be honest, I have no idea. I'm relatively new to participating on open-source projects, but I haven't found a mailing list, so I guess this is the next best place to discuss.

Problem is, the issue is buried on the fifth page now :confused:

**Comment by icarter09** [comment] 2021-02-16 14:49
https://forums.linuxmint.com/

**Comment by Lurux** [comment] 2021-02-16 17:30
> https://forums.linuxmint.com/

@icarter09, do the Cinnamon devs really look at these, though ?

**Comment by mtwebster** [comment] 2021-02-18 19:36
We've definitely discussed having a menu applet with a grid-type layout in the past.

Personally, however, I'd prefer to keep it as a separate applet from the existing one, and have it *only* support the grid layout, as well as take a hard look at paring down configuration options (I'd love to do this with the current menu as well as the grouped window list as well).

It would easier to maintain. As an example, the grouped window list is nice and feature-rich, but the code is pure insanity and attempting to fix anything usually breaks two others, due to its complexity. That's the extreme example - it looks like cinnamenu's code is a bit more consistent with our existing menu applet.

I also like the trend we set when we added the second window list - giving the users more choice, and giving us a bit more flexibility to do things like having different layout presets (as we do in the Mint welcome app).

This is definitely my opinion though, not any 'official' stance, I'll see if I can get others to chime in as well.

Thanks

**Comment by Lurux** [comment] 2021-02-18 22:06
> We've definitely discussed having a menu applet with a grid-type layout in the past.

This isn't only about the grid layout, Cinnamenu is more flexible than the current one in every way. The main reason I use it is for the ability to *switch categories on click* and *show favorites as a category*, which I think should be implement regardless of our final decision.

> Personally, however, I'd prefer to keep it as a separate applet from the existing one, and have it *only* support the grid layout, as well as take a hard look at paring down configuration options (I'd love to do this with the current menu as well as the grouped window list as well).
> 
> It would easier to maintain. As an example, the grouped window list is nice and feature-rich, but the code is pure insanity and attempting to fix anything usually breaks two others, due to its complexity. That's the extreme example - it looks like cinnamenu's code is a bit more consistent with our existing menu applet.

The main point for proposing to use Cinnamenu is configuration, so I don't think we would want to reduce the amount of options, although what you're saying does make sense. As a reminder, @fredcw offered to maintain the applet and make modifications if needed, so i think this is all clear. I guess a slight cleanup could be done before integration into Cinnamon.

As for separating the grid version, I'm not too sure about that, as seems to me that these types of singular layouts could probably be separated correctly in the code of a single applet. Considering this would duplicate the rest of the codebase, I think it isn't the best idea in this case.

> I also like the trend we set when we added the second window list - giving the users more choice, and giving us a bit more flexibility to do things like having different layout presets (as we do in the Mint welcome app).

Yep, I would love to see the layout switcher come as an official part of Cinnamon :heart: 

> This is definitely my opinion though, not any 'official' stance, I'll see if I can get others to chime in as well.

Yeah, getting more people to look into this would definitely be a good idea. I'll try to implement the two option I mentioned above If we don't end up using Cinnamenu. :smile:

**Comment by leigh123linux** [comment] 2021-02-18 23:59
> We've definitely discussed having a menu applet with a grid-type layout in the past.
> 
> Personally, however, I'd prefer to keep it as a separate applet from the existing one, and have it _only_ support the grid layout, as well as take a hard look at paring down configuration options (I'd love to do this with the current menu as well as the grouped window list as well).
> 
> It would easier to maintain. As an example, the grouped window list is nice and feature-rich, but the code is pure insanity and attempting to fix anything usually breaks two others, due to its complexity. That's the extreme example - it looks like cinnamenu's code is a bit more consistent with our existing menu applet.
> 
> I also like the trend we set when we added the second window list - giving the users more choice, and giving us a bit more flexibility to do things like having different layout presets (as we do in the Mint welcome app).
> 
> This is definitely my opinion though, not any 'official' stance, I'll see if I can get others to chime in as well.
> 
> Thanks

Screw Jason's code, I'm -1 for adding more of his shit!

**Comment by Lurux** [comment] 2021-02-19 10:06
> Screw Jason's code, I'm -1 for adding more of his shit!

@leigh123linux Excuse me I'm new here, but who's Jason ? Are you talking about Cinnamenu or answering the remark about the grouped window list ?

At the very least, I think we should implement "switch categories on click" and "show favorites as a freaking category" in the current menu. I can try to do that, but I've never touched Gtk before. Maybe this would be a good place to start :smile:

**Comment by fredcw** [comment] 2021-02-19 18:47
@leigh123linux I've cleaned up the code a bit so hopefully it's a bit more readable now.

**Comment by JosephMcc** [comment] 2021-02-19 20:29
I for one don't really want or like the grid layout. I'm also with @mtwebster on this one. The configuration should be cut down to only what is really needed.

**Comment by Lurux** [comment] 2021-02-19 21:30
> I for one don't really want or like the grid layout. I'm also with @mtwebster on this one. The configuration should be cut down to only what is really needed.

WHAT THE HECK ? Because you don't like the grid layout automatically means no one will ever want it and the option shouldn't be available ?

As for the configuration, I can understand that you prefer to keep things easy to maintain. However, I can't help but feel the current menu is way too limited. For example, having the ability to switch categories on click is a basic function that I think many people would appreciate.

**Comment by NikoKrause** [comment] 2021-02-19 22:48
I'm with mtwebster and JosephMcc.
The default menu definitely needs some improvements, but Cinnamenu has far too many options for a default applet.

**Comment by collinss** [comment] 2021-02-19 23:41
What is often difficult to understand as a casual user, or even a casual developer is that configuration has it's costs. Not only does it make it exponentially harder to maintain, but even more importantly, it makes it much harder for the average user. It's actually a very small portion of our user base who really does a lot of configuration. The greater portion of users would actually be negatively impacted by having a large number of options. For a 3rd party applet, large amounts of configuration is fine since the majority of its users are individuals who actually _do_ like a lot of customization, but when we're talking about a default applet (especially the menu applet, which is arguably the most important applet on the panel), we really do need to keep the number of settings to a reasonable level.

Keeping Cinnamenu as a 3rd party applet is really probably the best thing for most of it's users anyway. It's not that hard to install it through cinnamon settings (and it's not something that anyone is likely to do often either), and as a 3rd party applet, it actually gets more attention, and (probably) much faster releases. 

One of the reasons that so many people use Cinnamon over KDE (which has a ton of configuration) or Gnome Shell (which has very little in the way of configuration) is that we've struck a balance in terms of configurability that many of our users appreciate. If we lose that balance we risk both alienating the core of our user base and losing what makes us unique for only marginal benefit to a very small minority of users.

**Comment by JosephMcc** [comment] 2021-02-19 23:57
> WHAT THE HECK ? Because you don't like the grid layout automatically means no one will ever want it and the option shouldn't be available ?

Since you obviously took my statement to mean what you wanted it to and not what I actually said, let me spell it out more clearly. I said I don't like it, I didn't say it shouldn't be a choice. Fact of the matter is that it's already a choice. You get everything you want by using Cinnamenu. So keep using it. It has a developer who is doing a good job of maintaining it and as pointed out by @collinss probably gives it more dedicated dev time than it would get as a part of Cinnamon itself. Also if you bother to read, the idea from @mtwebster was to make the variant with a grid layout a separate applet.

You'll notice that all the Cinnamon devs that chimed in have a very similar opinion on making it the new default menu. There is a reason for that which I think @collinss explained quite well.

**Comment by ItzSwirlz** [comment] 2021-02-19 23:59
Okay; can we get back to business? I don't want seeing this when I check my phone notifications of complaints. Lets settle the matter and you give constructive criticism. Thank you.

I'm personally fine with a grid layout, but there definitely should be a choice of the user. Maybe a traditional and more newer style type thing? A layout switcher similar to mate-tweak?

**Comment by fredcw** [comment] 2021-02-20 05:55
I agree that cinnamenu as it is probably has a few to many options for a default menu. Options are great for the typical linux user but linux also needs to attract the kind of users who just want to switch their computer on, check their email and switch it off again and who would barely change so much as their desktop background picture. Being presented with too many configuration options also adds to the perception of linux as being too complicated for the average computer user. I think that for instance Google chrome has the right approach by having the bare minimum of options on their settings page while also providing a /flags page for people who want more control. I also think that a grid view menu by default would give cinnamon a more modern look but of course this is always going to be highly subjective. Making a cut down version of cinnamenu with fewer options is simply a matter of deleting a few lines and in any case I'm sure I'll continue to develop cinnamenu as a separate applet because as @JosephMcc said, it's much easier for me to quickly make changes and experiment with new ideas etc. I also agree that cinnamon has struck a good balance by making the initial presentation of cinnamon for new users as that of simplicity while also providing more options "under the hood" when people become more familiar with their desktop and want to start making changes.

**Comment by Lurux** [comment] 2021-02-21 18:27
Ok, I agree with most of what have been said here, @NikoKrause and  @collinss have made great points; maybe everything is better as it is, actually.

*Answering to @JosephMcc here*

> Since you obviously took my statement to mean what you wanted it to and not what I actually said, let me spell it out more clearly.

That was not my intention. Sorry if I took your message wrong; I thought you were saying that as an argument, that would have been a bit silly :sweat_smile: 

> I said I don't like it, I didn't say it shouldn't be a choice. Fact of the matter is that it's already a choice. You get everything you want by using Cinnamenu. So keep using it.

Of course I'll do ! I found the Cinnamon menu was a bit too limited and thought rebasing it off of Cinnamenu would be a good solution, that's why I defended the idea. Turns out it's not; sorry if my message seemed misplaced.

> It has a developer who is doing a good job of maintaining it and as pointed out by collinss probably gives it more dedicated dev time than it would get as a part of Cinnamon itself.

Indeed, that's an excellent point.

> Also if you bother to read, the idea from mtwebster was to make the variant with a grid layout a separate applet.

Yeah, I read that, I don't know why you think I didn't; I wasn't answering to him there.

*End of answering to @JosephMcc*

In the end, I still think the current menu could be improved, but that would require a separate issue. As I said above, I might try to implement "switch categories on click" if I find the time, but I've never touched Cinnamon applets before.

Anyway, bye everyone, and sorry for the noise ! :smile:

**Comment by JosephMcc** [comment] 2021-02-22 02:20
@Lurux  No worries and discussing is never a bad idea. We've just had some previous experience porting over an applet like that and learned what the pitfalls can be.

**Comment by Lurux** [comment] 2021-02-27 14:13
@JosephMcc Of course, that makes sense :slightly_smiling_face:

**Closed** 2021-03-31 18:40 UTC

**Comment by Lurux** [comment] 2021-04-04 17:50
Update: PR #10028 implements optional "switch categories by clicking" option in the menu applet.

I don't know the workflow here, I guess someone needs to review it now... This is my first time touching Clutter GUIs, hopefully I didn't do anything too silly ! :smile:

**Comment by Secret-chest** [comment] 2022-12-25 08:45
> Being presented with too many configuration options also adds to the perception of linux as being too complicated for the average computer user.

Well, just don't go to these options!
