### ISSUE TITLE
Please pull improved keyboard support from gnome-control-center

### ISSUE THREAD

**Issue by jepst** [linuxmint/Cinnamon#3212] opened 2014-06-01 00:07 UTC
Although cinnamon-control-center and cinnamon-settings-daemon are based on gnome-control-center and gnome-settings-daemon, respectively, newer versions of the gnome-\* packages have additional features, especially regarding keyboard layout handling, that should be integrated into the cinnamon-\* packages. Some of these features:
1. As documented in #3146, the new gnome-\* packages remove the long-standing and annoying misfeature of limiting the number of active keyboard layouts to four.
2. The new gnome-\* packages are integrated with the input methods control panel, removing the need to configure ibus separately from keyboard layouts. This means that alternative input methods (such a cjkv character selection) can be installed, configure, and selected through the same user interface as normal keyboard layouts, thus obviated the need for the user to install and mess around with ibus. For example, the Japanese Anthy input method is displayed as a keyboard layout in the same menu as standard keyboard layouts, such as English (US).

**Comment by Suncatcher** [comment] 2015-02-03 08:09
Confirm this issue. When will it be fixed?

**Comment by dmrauch** [comment] 2016-09-03 16:01
No news on this? I am using Linux Mint 18 with Cinnamon 3.0.7, the maximum number of allowed keyboard layouts is still limited to 4. It would be really great if this limitation could be gotten rid of!

**Comment by Suncatcher** [comment] 2016-09-03 17:10
Shame on them! It is pathetic they haven't fixed this yet.

**Comment by JosephMcc** [comment] 2016-09-03 17:30
> Shame on them! It is pathetic they haven't fixed this yet.

Yep. That's the way to encourage devs to get stuff done.

**Comment by leigh123linux** [comment] 2016-09-04 00:09
@Suncatcher If you want it so bad do it yourself.

**Comment by TambourineReindeer** [comment] 2017-06-28 08:34
I have encountered this problem as well (Mint 18.1 Cinnamon), since I am multi-lingual and a linguist of sorts. So far, when I have needed it, I have been removing one keyboard layout and adding another, and then repeating any time I need one of the others, but I would rather not need to (I saw the script on AskUbuntu, but that doesn't seem to work with the current version of Mint).
I wish I were a more experienced programmer, as I would be glad to help if I knew how.

**Comment by foberle** [comment] 2017-10-17 22:13
I recently installed Mint 18.02 Cinnamon 3.4.6 on a machine and was surprised at the "four script" limitation discussed above. I also concur with all of jepst's comments.

I can confirm that the "System Settings -> Personal -> Text Settings" in Ubuntu 16.04 (what appears to be the same applet as "System Settings -> Hardware -> Keyboard -> Layouts" in Mint) does NOT have the "four script" limitation, and hasn't for some time.

As for Leigh123linux's question, I've used multiple scripts since the mid 1980s as I regularly deal with languages that utilize different scripts.* I can't speak for the general public of course, but I correspond using both English and Thai, do side-by-side translations of ancient Greek to English, and write tutorials on getting around the many impediments in application software to freely writing with multiple languages and scripts in single documents, particularly those with multiple directionality. Over the years, even with my limited knowledge, I've provided enough people with help in this regard that I can confirm that this particular limitation is an annoyance to more folks than you might expect.

I would ask Leigh123linux why anyone would need support for more than four fonts, or more than two paper sizes, or - well, you get the idea. As Bill Gates said in the mid-1980s, "why would anyone ever need more than 16k of RAM?" It's 2017 already! And the issue has been addressed upstream, so it shouldn't be like the wheel needs to be reinvented. So consider this my added request for this merging of whatever fixes gnome applied to the applet.

* P.S. The difference between Script and Language is significant: this post is written with Latin Script in the English language (U.S. variety). While something like Thai script is only used by Thai (e.g. แฟรงค์โอเบอลี), segments of Latin script are used by multiple western languages. English uses a subset; German uses characters like ü, French characters like è, Spanish like ¿, and so forth, all part of Latin script. Scripts have a layout direction, as do the languages that use them. Arabic Script is used by a wide variety of languages - many even less related than those that use Latin script and, like Hebrew, is written right to left. Devanagari script (फ़ऐग ओबरली) is used not only by Hindi, but by forty-some different languages on that sub-continent, many of which have nothing but the character set in common.

**Comment by foberle** [comment] 2017-10-18 20:56
Following up on the four keyboard layout limitation and a short term workaround .......

Since I really would like to have more than four layouts available, I decided to do some experimentation; hopefully this will assist anyone who wishes to attack this issue. For this demonstration, run a terminal (Ctrl+Alt+t) and bring up the dconf-editor by typing 'dconf-editor' (there is no need to use sudo as we'll be experimenting with the current user account.

If dconf-editor is not installed, simply type 'sudo apt install dconf-editor'

Now, using the panel on the left side, select in turn >org, >gnome, >libgnomekbd, and >keyboard.
On the right side, next to the "layouts" the available layouts will be displayed.

Now before doing anything else, go to System Settings -> Hardware -> Keyboard, and click on the Layouts tab. Arrange the dconf-editor and keyboard layouts windows side by side so both are easily visible.

It can be seen that the dconf schema shown is for the keyboard layouts displayed. If you have only one layout selected, use the [+] key at the lower left of the Keyboard Layouts panel to add some more. In my case, I added Thai (TIS-820.2538), Greek (polytonic), and Indian. As each new keyboard is added, the display on the dconf-editor is immediately updated. Once all four have been selected, the dconf-editor's layouts line looks like this:

layouts ['us', 'th\ttis', 'gr\tpolytonic', 'in']

So far, so good. On the Keyboard Layouts Tab, you will have noticed that the [+] key at the bottom left is now "greyed out." This is the actual issue discussed above.

But, the symptoms can be further refined by directly editing the "layouts" line in the dconf-editor. Click on the Value column of the layouts line, and edit it to read as follows:

layouts ['us', 'th\ttis', 'gr\tpolytonic', 'in', 'ara', 'il\tlyx']

Looking at the Keyboard Layouts tab, it is apparent that the two new keyboard layouts -- in this case Arabic and Hebrew (lyx) -- have been added, but they are "greyed out." Using the mouse to click on the Cinnamon Panel's keyboard selector icon (or using whatever shortcut key you have assigned), the new layouts *appear* to be available, but something quite interesting happens: if you click on any of the first four layouts, it will be applied. Clicking on the fifth layout in the list, however, will activate the first (in this example, clicking on Arabic will select US-English); clicking on the sixth (Hebrew) will activate the second (Thai). Obviously there is a hard-coded limitation somewhere in the code - can you say "mod 4"?

This is most definitely a bug! But we can go further.

Go back to the Keyboard Layouts tab in System Settings. Note that you can select any of the "greyed out" choices and move them up or down with the arrow keys, and whatever keyboards are in the first four positions will work just fine.

As a short term solution, I have manually added the keyboard layouts I want using the dconf-editor so at least I can select them more easily than having to DELETE one of them to add a new one. Better, but still quite annoying.

And another quirk:

In Ubuntu 16.04 and earlier versions, it was possible to set whatever "hot key combination" one wished to switch/scroll through the keyboard layouts; combining that with the Shift key would scroll "backwards" through the list. The current method of selecting the key combination (using the Options button at the lower right of the Keyboard Layouts tab) only seems to permit forward motion.

Whoever did this code seemed to think that even four layouts were too many; there is one choice described as:

"Left Ctrl (to first layout), Right Ctrl (to last layout)"

When this is selected, the Left Control key will indeed select layout number 1, but the right Control key will always select layout number 2. In other words, this is a rather pointless option.

So, enough ranting for something that not a whole lot of folks care about (based on the overwhelming silence on this topic). But one needs to question why, if no one cares that much about it, was the effort made to add so many changes and limitations.

If some bored developer wishes to take a shot at restoring keyboard selection to its former usefulness, I'd be more than happy to replace any updated/corrected library and test any changes, since I'm familiar with using this facility. More than four keyboards CAN BE USED; they're just difficult to select.

**Comment by maxdule** [comment] 2018-01-13 14:15
+1 for the feature request, I have actually waiting for this for years.

> @Suncatcher If you want it so bad do it yourself.
@leigh123linux His rudeness does not make your comment any less thick-witted.

> Whilst I do think that requiring four layouts might be a bit excessive for
> most users, I can also see that there are some people that might actually
> go that far.

@clfarron4 Whilst reading more than one book in a lifetime seems to be a bit excessive for most people, some **do actually** go that far.

**Comment by Suncatcher** [comment] 2018-01-13 14:37
Ha-ha, you've made my day! Too many people nowadays haven't read any book in their lives except hornbook and haven't learned its native lang properly, so switching layouts is absolutely redundant functionality for them 😊

P.S. The only solution for now is to use latest Ubuntu or latest Fedora. All other distros seems to have this bug.
You can manually install Cinnamon or Mate if you really stick to Cinnamon.

**Comment by foberle** [comment] 2018-01-13 14:45
An only slightly tongue-in-cheek suggestion.
If we could convince some developer that Greek, Hebrew, Korean, Thai, etc. are actually just a different set of Emojis rather than actual languages that strange foreign people speak, perhaps the bug would be fixed quite quickly.
Support for Emojis certainly seems more critical these days than being able to use actual living languages.
I'm getting old.

**Comment by leigh123linux** [comment] 2018-01-13 15:18
01010100 01101000 01100101 01110010 01100101 00100000 01101001 01110011 00100000 01100001 01101110 01111001 00100000 01101111 01101110 01100101 00100000 01110100 01110010 01110101 01100101 00100000 01101100 01100001 01101110 01100111 01110101 01100001 01100111 01100101 00101100 00100000 01100001 01101100 01101100 00100000 01101111 01110100 01101000 01100101 01110010 01110011 00100000 01100001 01110010 01100101 00100000 01101111 01100010 01110011 01101111 01101100 01100101 01110100 01100101 00100001

**Comment by foberle** [comment] 2018-01-13 21:35
Awwww. If you're going to write the quotation in binary, at least get it right! You should be ashamed :)
The third word 01100001 01101110 01111001 should be 01101111 01101110 01101100 01111001...
("only" not "any" for those young kids who only speak hex ...)
Yup; I'm really old. And, yup; I really do write in multiple scripts. And it would really be nice if the drop down box could be fixed.
Frank, aka แฟรงค์ โอเบอลี, aka Φρανκ Ώβερλι, aka फरऐक ओबरली, aka 프랑 오벨리, aka Франк Обэрли, et cetera ...

**Comment by foberle** [comment] 2018-01-26 22:21
Re:  jepst's comment on Jun 2, 2014 and  Suncatcher's comment 13 days ago ...

Both mention Fedora, but that's only assuming that the Gnome desktop is used. For whatever reasons, I simply can't abide Gnome and was one of the (apparently) few who actually liked Unity. With that going away, I searched around for something else, and decided that Cinnamon was the desktop I felt most comfortable with.

Just for grins, I tried the latest Fedora 27 with the Cinnamon desktop and I can confirm that the issue with the keyboard layout limitation is definitely with Cinnamon, not the OS. If indeed 

Re: leigh123linux's comment on Sep 3, 2016 that this limitation is due by libgnomekbd, my Ubuntu 16.04 installation uses that (although not sure what version) and I have no issues on that OS; I'm a bit leery of attempting to copy that over to my Mint machine (even though it is supposedly based on Ubuntu 16.04) due to potential conflicts. Is that practical if I back up libgnomekbd to a USB stick first with the idea that I could restore it from a live CD if something goes wrong?

Even so, are there any bored developers who might compare the two? Has anyone looked to see if this limitation is on one of the newer Ubuntus that use Gnome as their default?

Sorry to be so picky and anal about this but it's been twenty-five years since I first used multiple scripts on the same machine simultaneously and this seems like a step backwards.

**Comment by Suncatcher** [comment] 2018-02-03 21:23
I heard opinions that this bug is not connected to OS, or DE but rather to X.Org Server which was dominant for all distros till the last time.
Newer versions of Gnome (since 3.22) use Wayland instead and that can be the reason, why this issue is not present in modern Gnome-based distros (Ubuntu and Fedora). However, I have no proofs.

**Comment by foberle** [comment] 2018-02-04 12:03
Not sure I understand your comment...
* Ubuntu 16.04 with Unity does NOT use Wayland, and does NOT have this problem.
* Mint 18.03 does NOT use Wayland either, but DOES have this problem.
* Both Ubuntu 16.04 and Mint 18.03 still use X.Org server as far as I know ...

Fedora 27 with Cinnamon DOES have this problem.

So I'm still leaning toward Cinnamon as the culprit and don't see how Wayland could be the cause if that's what you're saying. Or are you saying that newer Gnome might be the issue?

jepst's original 2014 posting identifies the related issues concisely and is still easily reproduced.
I agree with your own comment in 2016 that "It is pathetic they haven't fixed this yet."

**Comment by maxdule** [comment] 2018-02-04 12:18
> Mint 18.03 does NOT use Wayland either, but DOES have this problem.

Mint 18.3 KDE does not have the problem. I believe elementary OS does not use Wayland, and is not affected as well.

Aside the root cause, in the world of SSD and high bandwidth I believe to have 2 workarounds to think about. 😃

**Comment by Suncatcher** [comment] 2018-02-04 12:23
>> Not sure I understand your comment...

I see no contradictions in your points:

>> Ubuntu 16.04 with Unity does NOT use Wayland, and does NOT have this problem.

Ubuntu seems to have solved this problem by some **workaround** on Unity. Worked around means not solved, I strongly doubt they rewritten X.Org, maybe just made some add-in, add-on or hook, I don't know. I have no proofs, as I said, and I will **not** show those line of code where they solved it. I have been tracking this bug for a long time (now gave up) and I heard this version from on of more experienced members.
Just try to install some other DE on 16.04 (not Unity) and you will see the bug is still there.

>> Mint 18.03 does NOT use Wayland either, but DOES have this problem.

Yes, of course. Because it uses X.org.

>> Both Ubuntu 16.04 and Mint 18.03 still use X.Org server as far as I know ...

Exactly.
It's wonderful that Mint 18.3 doesn't have this problem, but exceptions (Unity and Cinnamon 18.3) prove the rule. 

See [my question](https://unix.stackexchange.com/questions/182486/number-of-installed-keyboard-layouts-in-linux-mint-qiana) (and answer to it) for details. This [bug](https://bugs.freedesktop.org//show_bug.cgi?id=19501) was reported in 2009 and **still is not fixed**.

**Comment by leigh123linux** [comment] 2018-02-04 13:14
Closed as you MF's are free to submit a PR to fix if it bothers you that much.

**Closed by leigh123linux** 2018-02-04 13:14 UTC
Labels: FEATURE REQUEST

**Comment by maxdule** [comment] 2018-02-04 14:01
First thing we're gonna do when we're in charge - we will free the software world of lame dumb-ass uneducated morons, even if 95% needs to fall off.

And I guess you won't see when the PR get merged. 😄
