### ISSUE TITLE
Power management applet no longer allows showing time remaining since 2.6?

### ISSUE THREAD

**Issue by lf-** [linuxmint/Cinnamon#4270] opened 2015-06-05 21:13 UTC
When I right click on the power management applet and click configure, there is no option to show percent and time remaining or time remaining at all. This was possible in 2.4, Is this a bug?

**Comment by leigh123linux** [comment] 2015-06-06 01:25
duplicate of https://github.com/linuxmint/Cinnamon/issues/4245

**Closed** 2015-06-06 07:23 UTC
