### ISSUE TITLE
Cinnamon menu applet: submenus are truncated

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8632] opened 2019-06-12 00:49 UTC
```
 * Cinnamon version (cinnamon --version): 4.0.10
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). Yes, but the problem has existed for years.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD 620 3.0 Mesa 18.2.8
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

I have the problem mentioned [in this bug report](https://github.com/linuxmint/cinnamon/issues/8168). That problem is: when one right-clicks on some menu items, a scrollbar, but nothing else, is displayed - thus making it impossible to manipulate the item (e.g. to uninstall the program to which it refers) via the menu. The problem persists into the Mint/Cinnamon _alpha_. Screenshot:

![Untitled](https://user-images.githubusercontent.com/47056543/59315906-b9750780-8cb3-11e9-9658-8a62d79e8381.png)

The problem affects multiple (top-level) items in the menu (that menu being the one that describes itself as the, 'Main Cinnamon menu').

**Steps to reproduce**

Uncertain. The problem could owe to (1) my having HiDPI enabled (and my display is HiDPI). Or the problem could be (2) the number of packages installed (3190 - though obviously not all of those have menu entries). Or else the problem might be (3) something is wrong with data stored by the menu applet.

**Expected behaviour**

Clearly one should not see what I show in the screenshot. That is: an area that opens up to show a submenu (some icon(s)) should actually show that menu (/that icon / those icons).

**Other information**

The third-party applet 'CinnVIIStarkMenu' (_sic_) does _not_ have the problem.

I would have thought that this is the sort of thing one would want to fix before a release, if I may say so.

**Comment by clefebvre** [comment] 2019-06-12 11:02
Hi @LinuxOnTheDesktop, I can't reproduce this, but I'll close it because it's a duplicate of https://github.com/linuxmint/Cinnamon/issues/5461, which is still open.

**Closed by clefebvre** 2019-06-12 11:02 UTC
