### ISSUE TITLE
small field of dialog box

### ISSUE THREAD

**Issue by RenanOfugi** [linuxmint/cinnamon#8922] opened 2019-10-26 21:43 UTC
```
 * Cinnamon version (cinnamon --version) : **Cinnamon 4.2.4**
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) : **Mint 19.2 Tina**
 * Graphics hardware *and* driver used
 * 32 or 64 bit : **64 bits**
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
the field "details" of dialog box "Failed to download package files" is very small !

**Steps to reproduce**
I tried to install the "Alien-arena" application from the application manager and the installation did not complete by showing this dialog. (unreachable mirror)

**Expected behaviour**
larger "details" field of the dialog box

**Other information**
none

**Comment by icarter09** [comment] 2019-11-03 17:16
@RenanOfugi do you mind changing this ticket from an "issue" to a "feature request". That seems to be more along the lines what you are wanting.

**Comment by RenanOfugi** [comment] 2019-11-08 02:20
@icarter09 but the dialog box can only read one line, are you sure not to be a issue?

**Comment by icarter09** [comment] 2019-11-08 03:07
My reasoning behind this was the fact that the nothing was broken or working incorrectly. While the displaying only one line is not optimal, it still is working as intended. Which puts that more along the lines of a feature request/improvement instead of a issue/bug. 

@RenanOfugi could you provide a screen capture of what you are seeing? Thanks.

**Comment by RenanOfugi** [comment] 2019-11-09 03:13
@icarter09  good idea, better put the label

**Comment by JosephMcc** [comment] 2019-11-18 16:11
Closing this since it's unrelated to Cinnamon. I think the dialog you are talking about is actually coming from Synaptic.

**Closed by JosephMcc** 2019-11-18 16:11 UTC
Labels: FEATURE REQUEST
