### ISSUE TITLE
The inbuilt 'Launcher': some unforunate, unrobust behaviour

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#6739] opened 2017-07-28 17:04 UTC
Mint 18.2
Cinnamon 3.4.4
Version of applet: it's 'about' button doesn't report it, but I think it is the most current version of the Launcher applet.

**To see the problem / reproduce**

1) Put an instance of the Launcher applet onto a panel.
2) Configure that instance by entering a valid path to some executable file into its 'command field'.
3) Whilst the 'Launcher Properties' windows remains open, move the aforementioned file to another folder.

Result: the Launcher Properties window disappeared and so did the applet instance on my panel. I found that, after I recreated the applet, two versions of the applet appeared on the panel - duplicates of each other.

I now that the combination of 2 and 3 is slightly perverse behaviour, but one can imagine why the user might do it. So, I think the applet ought to be robust enough to handle it.

I attach (zipped) 
[.xsession-errors.zip](https://github.com/linuxmint/Cinnamon/files/1183761/default.xsession-errors.zip)
my .xsession-errors log file.

**Comment by jaszhix** [comment] 2017-07-28 17:43
I attempted to reproduce this, but haven't seen the applet disappear far. When I move a launcher I see:

```sh
(cinnamon:5434): Cjs-WARNING **: JS ERROR: GLib.SpawnError: Failed to execute child process "/home/jason/bin/rpcs3-v0.0.3-2017-07-27-f613901-7417_linux64.AppImage" (No such file or directory)
PanelAppLauncher.prototype.launch@/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js:247:30
PanelAppLauncher.prototype._onButtonRelease@/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js:280:22
```
The applet disappearing could be a Cinnamon bug, but probably not caused by the panel-launcher applet. The menu applet you're using is having some issues and flooding the log with St warnings.

**Comment by CottonEaster** [comment] 2017-07-28 18:18
jaszhix,

Thank you for your response. Since my menu applet is having problems, I will remove it. However, I am unclear whether you think that the particular warning that you cite owes to that menu applet, or to something else.

**Comment by jaszhix** [comment] 2017-07-28 18:44
I'm not sure exactly what is causing this particular problem just based on the log, but those St-CRITICAL errors are listing actors with their theme classes, and the classes are generally only used in menu applets. This appears to be CinVIIStarkMenu because its the only one I know of with ```starkmenu-applications-inner-box```. 

It could be totally unrelated to the other issue with applets disappearing - I also have noticed this happening while developing applets, where if an uncaught exception occurs on an applet that has multiple instances, it fails to handle it. The error isn't caught in glass.log though, its still showing as running, but its uuid is removed from the panel. I think there's an exception happening _after_ the original exception, but the exception is passing an undefined uuid to appletManager. I'll try to reproduce it with another applet later.

**Comment by CottonEaster** [comment] 2017-07-28 18:53
On the first paragraph: yes, I think it was CinVIIStarkMenu.

On your second paragraph: I seem to have uncovered - or rediscovered - something that does need working on. Good!

**Comment by NikoKrause** [comment] 2017-07-29 00:42
What's the problem here with StarkMenu?

**Comment by mtwebster** [comment] 2017-07-29 01:27
Just to be clear on what expected behavior is for the stock applet - if the executable is unavailable, the specific launcher for it won't display.  If you restore the executable, it should will restore the launcher.

Also, please keep the topics of issues factual and informative only.  I'm not really interested in your 'opinion' on how unfortunate or disheartening something is for you.

**Comment by jaszhix** [comment] 2017-07-29 05:20
@NikoKrause Not sure. Usually those errors can be seen when trying to get style information from an actor before its on the stage.

**Comment by icarter09** [comment] 2019-12-07 03:44
Closing this issue since the original submitter of this ticket is no longer present on Github.

**Closed by icarter09** 2019-12-07 03:44 UTC
