### ISSUE TITLE
Cinnamon panel / task bar becomes unresponsive to mouse (3.2.1)

### ISSUE THREAD

**Issue by ase1590** [linuxmint/Cinnamon#5984] opened 2016-11-19 22:07 UTC
I'm not sure yet what exactly causes it, but every few minutes my Cinnamon panel / task bar becomes unresponsive to mouse clicks.
I then can no longer click the Cinnamon menu icon or interact with anything related to the task bar with my mouse. I can only open the cinnamon menu by pressing the Super key. if I close out of all existing windows, cinnamon will start to work normally again and I can interact with cinnamon fine.

**Comment by ase1590** [comment] 2016-11-19 22:23
running cinnamon --replace in terminal window, I am greeted with a constant stream of the following error:

`(cinnamon:1611): CJS-WARNING **: JS ERROR: Error: can't convert NaN to an integer
Chrome.prototype.updateRegions@/usr/share/cinnamon/js/ui/layout.js:706`

**Comment by ase1590** [comment] 2016-11-20 02:17
Okay, I've found reproducible steps. 

1. open up some program
2. right click the title bar to get the maximize/minimize/close menu
3. close out the right click menu
4. The Cinnamon task panel is now unresponsive to left mouse button clicks. 

Curiously, if I try to right click the task bar, it instead shows me the same right click menu that I would get for the desktop. I have my Cinnamon task bar on the top edge of my screen. Perhaps the desktop is drawing over the top of the task bar?

**Comment by leigh123linux** [comment] 2016-11-20 10:24
Remove hwmonitor and any other spice applets and see if the issue still reproduces.

**Comment by morph027** [comment] 2016-11-20 11:56
Reverted to default settings, removed all other applets and keep watching ;)

**Comment by feren** [comment] 2016-11-20 18:55
It happens over here on 3.2 from the starting of Cinnamon and never ends... Applets are still responsive and their menus are usable, but the panel is completely click-through...

**Comment by feren** [comment] 2016-11-20 18:55
@leigh123linux I reset the panel applets to the fresh Linux Mint defaults, and that didn't help a single bit...

**Comment by stunted** [comment] 2016-11-21 02:55
Resetting all panel applets and restarting cinnamon seems to correct the issue for me.

Will be re-adding applets one by one until I find a potential offender.

**Comment by morph027** [comment] 2016-11-21 06:20
Probably a faulty one i was using ;)
https://github.com/jake-phy/WindowIconList/issues/172

Running smooth since i've cleared all spices.

**Comment by feren** [comment] 2016-11-21 11:09
Shall we have a clearing of some Spices then that won't work on Cinnamon anymore with 3.2's release?

**Comment by feren** [comment] 2016-11-21 15:26
Ok, turns out you have to restart Cinnamon to unbrick the panel once WindowListWithAppGrouping is removed...

**Comment by ase1590** [comment] 2016-11-21 15:45
@leigh123linux I can also confirm that removing the WindowListWithAppGrouping fixes the issue.

**Comment by JosephMcc** [comment] 2016-11-21 18:31
Closing this since the issue seems to be causes by third party applet/s

**Closed by JosephMcc** 2016-11-21 18:31 UTC

**Comment by maedox** [comment] 2016-11-21 19:15
The fact that a crash like this is possible seems like a bug to me, so shouldn't that be fixed instead of closing the issue?

**Comment by feren** [comment] 2016-11-21 19:19
@JosephMcc I think a clearing of outdated/non-functional/bricking applets is in order on Cinnamon Spices then...

**Comment by leigh123linux** [comment] 2016-11-21 19:22
@maedox It's down to the third-party applets maintainers to fix them as there not part of the linuxmint cinnamon code.

**Comment by JosephMcc** [comment] 2016-11-21 19:23
@maedox It doesn't crash. Applets are allowed to do quite a lot in Cinnamon and that can lead to this sort of thing happening. There are some things in place that will disable a bad applet but I'm not sure how much we can actually do given the amount of flexibility is allowed.

@feren We have been talking about exactly that. Something will likely happen once things settle down from Mint18.2.

**Comment by feren** [comment] 2016-11-21 19:28
@JosephMcc Good, I hope it happens, otherwise, new users will probably be confused when some applets don't work, it'll also mean there's more fresh applets available on the Spices repos.
BTW, ones I know still work include:

- slingshot@jfarthing84 (no Vertical Panel support)
- weather@mockturtl
- MessagingMenuV3@blub
- show-hide-applets@mohammad-sn
- ScreenShot+RecordDesktop@tech71
- search@bownz (Other applets of its kind are not working)
- window-buttons-with-title@fmete
- globalAppMenu@lestcape (Not sure if this one's in the repos, it's definetely on Git)
- stopwatch@pdcurtis
