### ISSUE TITLE
The applist in menu@cinnamon.org goes out of bounds underneath menu

### ISSUE THREAD

**Issue by Code-of-Isa** [linuxmint/cinnamon#12094] opened 2024-02-26 14:27 UTC
The applist only becomes invisible underneath the menu, but the apps still get a description on hover and remain clickable. This has probably been overlooked due to the standard placement being on the bottom of the screen, thus hiding the out of bounds applist. 

Here is a gif showcasing the issue:
![simplescreenrecorder-2024-02-26_15 13 13](https://github.com/linuxmint/cinnamon-menus/assets/161329261/bece6da8-f0e9-4dfa-808f-64d6fd3df33c)
 
(I'm new to github and my not know everything)

**Comment by rcalixte** [comment] 2024-02-26 14:42
Duplicate of #11123.

**Closed by rcalixte** 2024-02-26 14:42 UTC
