### ISSUE TITLE
Overlapping text on Mint Menu

### ISSUE THREAD

**Issue by bigcat4** [linuxmint/Cinnamon#6702] opened 2017-07-15 15:17 UTC
```
 * Cinnamon version (cinnamon --version)
3.4.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 18.2
 * Graphics hardware *and* driver used
Intel 3000 - driver=i915
 * 32 or 64 bit
64 bit
 ```

**Issue**
Overlapping text appears on program names.

**Steps to reproduce**
Fresh install of Linux Mint 18.2. Activate the Mint-Y Desktop theme, open the Mint menu and hover over the application categories. The program names in categories that have more programs than can be displayed without scrolling, will display with overlapping text

![screenshot](https://user-images.githubusercontent.com/10148398/28240369-a5680e1e-6978-11e7-9a44-21bd35a3b5de.png)
Categories where scrolling is required to display all programs

![screenshot2](https://user-images.githubusercontent.com/10148398/28240384-fefe5942-6978-11e7-83f5-e998821e140c.png)
Categories where scrolling is not required

**Expected behaviour**
The program names should show without overlapping text, as they do, before activating the Mint-Y theme.

**Other information**
This happens on a fresh install of Mint 18.2, but only on a Lenovo T420 with Intel graphics 3000. I cannot replicate this on a Lenovo X230.

**Comment by JosephMcc** [comment] 2017-07-15 17:20
Thanks for the report. It's a duplicate of https://github.com/linuxmint/mint-y-theme/issues/67

**Closed by JosephMcc** 2017-07-15 17:20 UTC

**Comment by bigcat4** [comment] 2017-07-15 17:52
Thanks for the update. I'll add my spec to the other entry if it helps?

Regards
Mark

**Comment by JosephMcc** [comment] 2017-07-15 18:26
Please do. I can't replicate the issue here. Would be nice if to know if it seems to be linked to certain graphics hardware.

**Comment by LyckanSv** [comment] 2017-07-16 04:10
I have an integrated intel 3000 graphics card

Graphics:  Card: Intel 2nd Generation Core Processor Family Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0116
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.00hz
           GLX Renderer: Mesa DRI Intel Sandybridge Mobile
           GLX Version: 3.0 Mesa 12.0.6 Direct Rendering: Yes
