### ISSUE TITLE
Application can unpin itself when grouping disabled on Grouped window list

### ISSUE THREAD

**Issue by Mikaka27** [linuxmint/cinnamon#8951] opened 2019-11-12 02:25 UTC
```
 * Cinnamon version: Cinnamon 4.2.4
   - Not using ppa
 * Distribution - Mint 19.2
 * GTX 1660 Ti on 440.26 driver
 * 64 bit
 * [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3833987/xsession-errors.txt)
 ```

**Issue**
When grouping is disabled on Grouped window list, correct sequence of events can cause the pinned application to be "unpinned" without user doing it manually.

**Steps to reproduce**
1. Disable window grouping in Grouped window list:
![1](https://user-images.githubusercontent.com/9214100/68636316-6ec61880-04fb-11ea-9bab-d43bcc0f24e7.png)
2. Open pinned application (terminal in this case):
![2](https://user-images.githubusercontent.com/9214100/68636341-81d8e880-04fb-11ea-94e0-69d6f8a6ce4c.png)
3. Open same application again (so there are 2 terminals):
![3](https://user-images.githubusercontent.com/9214100/68636376-97e6a900-04fb-11ea-8905-b8715673ea27.png)
4. Switch to first opened application (the one which is showing on the "pinned" spot), and close it:
![4](https://user-images.githubusercontent.com/9214100/68636419-bba9ef00-04fb-11ea-8771-65566515712e.png)
5. Pinned application (terminal) disappeared already, now close the other one:
![5](https://user-images.githubusercontent.com/9214100/68636454-d2e8dc80-04fb-11ea-846f-c86c08a1e158.png)

Now user has no terminal pinned, where clearly he did not unpin it himself.

**Expected behaviour**
Don't know what should happen between steps 3-4, but i guess the application should stay pinned regardless.

**Comment by smurphos** [comment] 2019-11-12 07:35
Duplicate of https://github.com/linuxmint/cinnamon/issues/8377

**Comment by Mikaka27** [comment] 2019-11-12 11:24
Hi, should I close it since it's a duplicate?

**Comment by smurphos** [comment] 2019-11-16 08:00
@Mikaka27 that's not a bad idea to try and help the devs manage the extensive issue list ;-)

You can give the OP of the linked issue a thumbs up to indicate your support for it being a bug that needs fixing, or if you think you can add any additional info to the existing bug report then add a comment.

**Comment by icarter09** [comment] 2019-12-08 03:40
Closing since it's a duplicate

**Closed by icarter09** 2019-12-08 03:40 UTC
