### ISSUE TITLE
Unlock screen with finger print

### ISSUE THREAD

**Issue by irwtdvoys** [linuxmint/Cinnamon#5975] opened 2016-11-16 17:58 UTC
When cinnamon is locked the only way to unlock the screen is to type in the password even though I can initially login via my finger print scanner.

I feel this would be a good addition to the lock screen functionality.

**Comment by NikoKrause** [comment] 2016-11-16 23:35
Do you need an extra driver? I have a fingerprint Scanner on my laptop. Didn't know it's working in Linux Mint.

**Comment by mtwebster** [comment] 2016-11-17 03:28
I'm working on this, but am having trouble finding a supported fingerprint scanner that isn't surrounded by a laptop.

**Comment by nipperv** [comment] 2016-11-17 10:57
Confirmed!
Fingerprint scanner is triggered only after entering any character in the password field. Laptop Tninkpad x201. In version 3.0, everything works.

**Comment by irwtdvoys** [comment] 2016-11-17 12:04
In my use case the finger print scanner is built into the laptop (X1 Carbon). 

I have `fprint` installed and setup which is detected and works on the initial login, just not on the lock screen.

**Comment by JosephMcc** [comment] 2016-11-17 18:17
I'm going to close this one since the same issue is opened here: https://github.com/linuxmint/cinnamon-screensaver/issues/147

**Closed by JosephMcc** 2016-11-17 18:17 UTC
