### ISSUE TITLE
Panel can't hide when fullscreen.

### ISSUE THREAD

**Issue by amaothree** [linuxmint/Cinnamon#7568] opened 2018-05-10 02:46 UTC
```
 * Cinnamon version 3.8.2
 * Distribution - Arch
 * Graphics hardware *and* driver used Intel HD Graphics 520
 * 64 bit
 ```

**Issue**
The panel can't hide when I run all fullscreen software. Just like fullscrenn play video by VLC or fullscreen game from steam.

**Steps to reproduce**
1.In the panel setting , Set the panel-hide-setting to always-show-panel.
2.Run some full screen software.
3.The panel still on the screen.

**Expected behaviour**
The panel should be hide when run full-screen application although the setting is always-show-panel.

**Other information**
Cinnamon version 3.8.1 no this issue in my arch.
![snapshot](https://user-images.githubusercontent.com/26244249/39849460-0db9fae8-543f-11e8-9dda-ff23dc9e06bd.png)

**Comment by itzexor** [comment] 2018-05-10 02:54
this should be fixed in muffin 3.8.2.

duplicate of https://github.com/linuxmint/muffin/issues/320

**Closed by itzexor** 2018-05-10 02:54 UTC
