### ISSUE TITLE
New Panel Launcher Actions unuseable

### ISSUE THREAD

**Issue by dominikFenzl** [linuxmint/Cinnamon#5354] opened 2016-06-02 05:46 UTC
Since cinnamon 3 there are new actions within the panel launchers. The Actions worked fine for a time, but now i am not able to use them any more. 

The title is 'Unbekannt', german for unknown, and if i click on them nothing will happen. The icon is just bumping.

This is for all launchers, self created and even for default lauchers like firefox or thunderbird.

Looking Glass does not show anything like an error.

**Comment by JosephMcc** [comment] 2016-06-02 10:58
I seem to be getting this as well. Firefox just shows "Unnamed".

**Comment by JosephMcc** [comment] 2016-06-02 19:16
Not sure exactly which commits affected this but they work again now after updating to the latest git master.

**Comment by mtwebster** [comment] 2016-06-02 22:19
It was caused by this: https://github.com/linuxmint/cinnamon-menus/commit/44ee2de737e53b0d1f59df46fc2df8ed1b5ea5ff and subsequently fixed by https://github.com/linuxmint/cinnamon-menus/commit/055bd2ea3a721557f6e20fdd1f3b0a2b8c9bd99c

**Closed by mtwebster** 2016-06-02 22:19 UTC
Labels: BUG REPRODUCED
