### ISSUE TITLE
Refreshing theme list error

### ISSUE THREAD

**Issue by JosephMcc** [linuxmint/Cinnamon#4429] opened 2015-07-11 12:29 UTC
Just creating an issue for a problem reported here: http://forums.linuxmint.com/viewtopic.php?f=90&t=199870

Running cinnamon-settings themes from the terminal produces the following error: http://pastebin.com/URSAG6Z7
And pops up 10 dialog boxes.

On Cinnamon 2.6.13

**Comment by VolMi** [comment] 2015-07-11 14:03
I just had a symptom which, I suspect, might have the same root cause: When updating the theme list, the progress window seems to reach an undefined state... See the screen cast (116 kiB):
<a href="http://www.file-upload.net/download5.php?valid=95.34247105605&id=10758037&name=Cinnamon_2.6.12_themes_update.webm">Cinnamon_2.6.12_themes_update.webm</a>

**Comment by leigh123linux** [comment] 2015-07-12 18:10
Reverting this commit seems to fix the issue here

https://github.com/linuxmint/Cinnamon/commit/317043678517a246349c80fe8d8fb8f5cbd52a06

**Comment by VolMi** [comment] 2015-07-12 18:17
> Reverting this commit seems to fix the issue here

Confirmed!

**Comment by clefebvre** [comment] 2015-07-17 10:19
Fixed on the server side (the server didn't properly generate thumbnails for jpg files)

**Closed by clefebvre** 2015-07-17 10:19 UTC
