### ISSUE TITLE
Closing terminal window crashes cinnamon

### ISSUE THREAD

**Issue by leandro19** [linuxmint/Cinnamon#7211] opened 2018-01-19 16:32 UTC
```
 * Cinnamon 3.6.7
 * Arch
 * graphics hardware: Intel® HD Graphics 5000
    driver used: i915
 * 64 bit
 ```

**Issue**
Closing any terminal emulator causes cinnamon to crash. I have reproduced the issue with gnome-terminal, xterm, and Cool Retro Term

**Steps to reproduce**
1. Open any terminal emulator.
2. close all instances of the terminal that are open.

**Expected behaviour**
Normally the terminal emulator window would close without causing cinnamon to crash and enter fallback mode.

**Other information**
`dmesg` gives the following line after the crash occurs:
`[ 2196.133168] traps: cinnamon[5252] general protection ip:7fae48e53422 sp:7ffe1f024a80 error:0 in libgobject-2.0.so.0.5400.3[7fae48e1c000+54000]
`
I've also attached the output of `journalctl -f` at the moment that the problem occurs:
 [crashlog.txt](https://github.com/linuxmint/Cinnamon/files/1647303/crashlog.txt)

**Comment by clefebvre** [comment] 2018-02-01 10:15
Duplicate of https://github.com/linuxmint/Cinnamon/issues/7064

**Closed by clefebvre** 2018-02-01 10:15 UTC
