### ISSUE TITLE
Add dictionary search  to the start menu

### ISSUE THREAD

**Issue by mzs112000** [linuxmint/Cinnamon#3481] opened 2014-09-11 03:01 UTC

**Comment by anandrkris** [comment] 2015-01-28 04:16
https://github.com/linuxmint/Cinnamon/pull/3853 Seems to provide support for search capabilities. Will be glad to see some add online dictionary service?

**Comment by lestcape** [comment] 2015-01-28 04:44
@anandrkris thats is the type of thing that if i will do i will do when search providers be mature. I don't want to crash cinnamon, waiting for an slower connection. I don't want to call for an slower search, without a way to be cancelled, if user decide change the pattern after a time out, more higher that the time that i define to waiting for the pattern, that currently the user are writing.

I'm not sure how search providers are working, so the first thing to do is create locals search providers and test what happens. I don't want also return to the time when the menu was slow.

Finally I don't want to receive search result events on my extension if my extension not invoked this search. I will can do all this now? I think not.

https://github.com/linuxmint/Cinnamon/issues/3854

**Comment by anandrkris** [comment] 2015-01-28 11:17
@lestcape - Sorry, i have no idea on background technology / architecture. It's just a suggestion if someone one wants to implement. If it can not  be done, fine. I have an offline dictionary that I will continue to use.

**Comment by glebihan** [comment] 2015-01-28 12:12
@anandrkris : the new search providers definitely provide a technical way to implement that dictionary search (it actually shouldn't be hard to do).
However, finding a usable (ie open) source for the data is another issue. For example, http://dictionary.reference.com/, that you mentioned earlier, would probably not allow it (see section 3.2 on http://dictionary.reference.com/help/terms.html).

**Comment by dalcde** [comment] 2015-01-28 12:40
How about Wiktionary?

**Comment by mtwebster** [comment] 2015-01-28 12:40
Could there be some "libdictionary" or something offline we could use to do lookups?  All sorts of programs do spellchecking - they can't all be implementing their own solution.

**Comment by lestcape** [comment] 2015-01-28 16:35
I agree with @mtwebster, @glebihan does certainly an amazing thing, but it's fresh. I don't know how resolve all problems that i can find, so why take risks? Will be the time to do that? Also i think that an online dic will require to do the kernel on python.

**Comment by lestcape** [comment] 2015-01-28 18:17
I thinking that will be interesting create first a tester for a search provider, to find the speed of the specific search provider and alert the user and devs when the client of the search provider are slower. This will contribute to detect easy the cause of an slower performance of cinnamon, causing by an slower client of a search provider and then take a user custom decision or automatically one on some critical cases. I had to leave some of my projects, because i consider that could be the cause of decrease the cinnamon performance and this is not cinnamon, is a wrong implementation of an application that i'm doing. I disagree to provide a bad imagen of all works that devs of cinnamon are doing. And this is what will happen if we do wrong things, the users think that the third-party extensions are responsibilities of cinnamon devs...

**Comment by dalcde** [comment] 2015-01-28 18:30
@mtwebster /usr/share/dict/words is a long list of things that are considered to be words.*
@lestcape I think glebihan employed a clever dbus trick (or hack) so that the search providers won't slow down cinnamon. The idea is (I think) to launch an external process to reach the search providers, and then use dbus to notify cinnamon when the results are obtained.

**Comment by collinss** [comment] 2015-01-28 18:33
Just a thought here... I haven't really looked into the implementation yet, but wouldn't it work with a separate applet? If so, why not just make a separate 3rd party applet to start out with, and then once it is mature, you could consider merging it into the menu applet... I might do that myself now that I have a working Linux machine again. (I already have a really nice icon for it ;) )

**Comment by lestcape** [comment] 2015-01-28 18:40
@dalcde thanks... I see the dbus feature... but this is exactly what i say. I have not a good know of how made things yet and i not want to do wrong things. The time when i do a synchronous spaw and then blocked all cinnamon waiting for the response is in the past, and is the reason to not do again the same.

**Comment by lestcape** [comment] 2015-01-28 18:54
Yes @collinss this is the idea and the @glebihan examples are doing the things on that way... but the novice devs will read it and before doing a thing? jejeje... I was a novice and I did not read anything, so... Is a risk added without having an idea.

**Comment by glebihan** [comment] 2015-01-28 19:21
@mtwebster : spell checking only needs a glossary, not a dictionary, and there are indeed some standard libs for that. I've never seen a dictionary lib.
@dalcde : didn't think about that one, would probably work.

**Comment by glebihan** [comment] 2015-01-28 19:26
@collinss : Here is a first implementation of a sample applet using the providers : https://github.com/linuxmint/Cinnamon/tree/master/doc/applets-examples/finder%40cinnamon.org
And there'll definitely be more.

**Comment by lestcape** [comment] 2015-01-29 17:12
@glebihan not really a lib but a offline dict: stardict have a DBus implementation... http://manpages.ubuntu.com/manpages/hardy/man1/qstardict.1.html internally to the dict, you can add more dict (an online dict also).. So, an asyncronous way to implemented the support for several dictionarys...

**Comment by JosephMcc** [comment] 2018-01-30 19:13
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Closed by JosephMcc** 2018-01-30 19:13 UTC
Labels: FEATURE REQUEST
