### ISSUE TITLE
[Cinnamon 4] Some tray icons missing

### ISSUE THREAD

**Issue by vlatkoB** [linuxmint/Cinnamon#7998] opened 2018-11-08 08:32 UTC
```
 * Cinnamon 4.0.0
 * Linux vlArch 4.18.16-arch1-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
 * Intel Corporation HD Graphics 530
 * 64 bit
 ```

**Issue**
Two of my tray icons are missing, `birdtray` and `owncloud`.
In Looking Glass there are lines
```
info t=2018-11-08T09:04:48Z Adding indicator: birdtray
info t=2018-11-08T09:04:48Z Adding indicator: ownCloud
```
but the icons are not visible, not even in Panel Edit Mode.

Both apps are running fine, just the icon is not visible. No errors reported in the system log.

**Steps to reproduce**
Start `birdtray` and `owncloud`-client and watch tray.

**Expected behaviour**
`birdtray` and `owncloud` icons appear in system tray

**Other information**
No errors reported in any of the logs, looking glass, .xsession-errors or system log.
Both apps autoload, with the delay of 15s and 20s, respectively.

**Comment by jaszhix** [comment] 2018-11-08 09:05
I compiled birdtray and can reproduce this when indicator support is enabled. Disabling that (in Settings -> General) seems to fix it.

**Comment by leigh123linux** [comment] 2018-11-08 09:35
Duplicate of #6143

**Closed by leigh123linux** 2018-11-08 09:35 UTC

**Comment by vlatkoB** [comment] 2018-11-08 10:58
For some reason, both icons reappeared. :-)
@jaszhix Thanks for the tip. It didn't work after the first Cinnamon restart but after several.
