### ISSUE TITLE
Cinnamon shows non-existent files on Desktop

### ISSUE THREAD

**Issue by bigos** [linuxmint/Cinnamon#6884] opened 2017-09-09 10:06 UTC
```
 * Cinnamon version - 3.4.6
 * Distribution - Mint 18.2
 * Graphics hardware *and* driver used - Intel Broadwell-U
 * 64 bit
 ```

**Issue**
Cinnamon shows non-existent file icons on the Desktop. I have 2 files that can be checked with desktop menu/Properties. Type of both files is Archive (application/zip), their names are; zipC7FQG and ziRMcJnk. But they are non-existent. Both command ls and Nemo do not see those files. I guess they are temporary files created by a program VYM - View Your Mind. Logging off and logging in seems to fix the problem.

**Steps to reproduce**
Install VYM - View Your Mind and save your work on the Desktop. Don't forget to go to VYM menu Setting and select Write backup file on save.

Video demonstration: https://youtu.be/xljPscOVYtM

**Expected behaviour**
Either add an option to refresh the desktop, or improve watching for deleted/dodgy files.

**Other information**

**Comment by NikoKrause** [comment] 2017-09-09 11:34
I tried it and can confirm on LM 18.2.
I see this sometimes, when downloading files or using JabRef and LaTeX.
You can refresh the desktop by pressing `F5`, then the will disappears.

**Comment by itzexor** [comment] 2017-09-10 20:08
Duplicate of https://github.com/linuxmint/nemo/issues/1509

**Closed** 2017-09-27 20:22 UTC
