### ISSUE TITLE
Grouped Window List disappear after returning from Expo Mode

### ISSUE THREAD

**Issue by BrunoNZ** [linuxmint/cinnamon#11016] opened 2022-08-08 19:39 UTC
```
 * Cinnamon version 5.4.9
 * Mint 21
 * Intel Corporation UHD Graphics 620 (Mesa 22.0.5-0ubuntu0.1)
 * 64 bit
 ```

**Issue**
Grouped Window List disappear after clicking Expo Mode and then return to some workspace.

**Steps to reproduce**
1. Add "Expo" applet to the panel
2. Add "Grouped Window List" to the panel
3. Click "Expo" button and choose a workspace
4. Notice that the Grouped Window List is missing/blank.

**Expected behaviour**
That everything looks exactly the same after clicking and returning from Expo Mode.

**Other information**
* Clicking on the "Scale" applet brings back the GWL applet.
* No other applet seems to be affected by this bug

[cinnamon-2022-08-08T163828-0300.webm](https://user-images.githubusercontent.com/1660320/183500367-b0e4dccc-6f67-489f-970d-ad08ac9c805b.webm)

**Configuration info, if applicable**
Expo:
```json
{
    "section1": {
        "type": "section",
        "description": "Behavior"
    },
    "activate-on-hover": {
        "type": "switch",
        "default": false,
        "description": "Activate expo on hover",
        "value": false
    },
    "__md5__": "5965ee74f3d0d4ec75d6f319ca59a789"
}
```

Grouped Windows List
```json
{
    "layout": {
        "type": "layout",
        "pages": [
            "generalPage",
            "panelPage",
            "thumbnailsPage",
            "contextMenuPage"
        ],
        "generalPage": {
            "type": "page",
            "title": "General",
            "sections": [
                "generalSection",
                "hotKeysSection"
            ]
        },
        "panelPage": {
            "type": "page",
            "title": "Panel",
            "sections": [
                "appButtonsSection"
            ]
        },
        "thumbnailsPage": {
            "type": "page",
            "title": "Thumbnails",
            "sections": [
                "thumbnailsSection",
                "hoverPeekSection"
            ]
        },
        "contextMenuPage": {
            "type": "page",
            "title": "Context Menu",
            "sections": [
                "contextMenuSection"
            ]
        },
        "generalSection": {
            "type": "section",
            "title": "Behavior",
            "keys": [
                "group-apps",
                "scroll-behavior",
                "left-click-action",
                "middle-click-action",
                "show-all-workspaces"
            ]
        },
        "appButtonsSection": {
            "type": "section",
            "title": "Application Buttons",
            "keys": [
                "title-display",
                "launcher-animation-effect",
                "number-display",
                "pinned-apps",
                "enable-app-button-dragging"
            ]
        },
        "hotKeysSection": {
            "type": "section",
            "title": "Hot Keys",
            "keys": [
                "cycleMenusHotkey",
                "show-apps-order-hotkey",
                "show-apps-order-timeout",
                "super-num-hotkeys"
            ]
        },
        "thumbnailsSection": {
            "type": "section",
            "title": "Thumbnails",
            "keys": [
                "thumbnail-scroll-behavior",
                "show-thumbnails",
                "animate-thumbnails",
                "vertical-thumbnails",
                "sort-thumbnails",
                "highlight-last-focused-thumbnail",
                "onclick-thumbnails",
                "thumbnail-timeout",
                "thumbnail-size"
            ]
        },
        "hoverPeekSection": {
            "type": "section",
            "title": "Hover Peek",
            "keys": [
                "enable-hover-peek",
                "hover-peek-time-in",
                "hover-peek-time-out",
                "hover-peek-opacity"
            ]
        },
        "contextMenuSection": {
            "type": "section",
            "title": "",
            "keys": [
                "show-recent",
                "autostart-menu-item",
                "monitor-move-all-windows"
            ]
        }
    },
    "number-display": {
        "type": "checkbox",
        "default": true,
        "description": "Show window count numbers",
        "value": true
    },
    "title-display": {
        "type": "combobox",
        "default": 1,
        "description": "Button label",
        "options": {
            "None": 1,
            "Application name": 2,
            "Window title": 3,
            "Window title (only for the focused window)": 4
        },
        "value": 1
    },
    "scroll-behavior": {
        "type": "combobox",
        "default": 1,
        "description": "Mouse wheel scroll action",
        "options": {
            "None": 1,
            "Cycle apps": 2,
            "Cycle windows": 3
        },
        "value": 1
    },
    "left-click-action": {
        "type": "combobox",
        "default": 2,
        "description": "Left click action",
        "options": {
            "None": 1,
            "Toggle activation of last focused window": 2,
            "Cycle windows": 3
        },
        "value": 2
    },
    "middle-click-action": {
        "type": "combobox",
        "default": 3,
        "description": "Middle click action",
        "options": {
            "None": 1,
            "Launch new app instance": 2,
            "Close last focused window in group": 3
        },
        "value": 3
    },
    "pinned-apps": {
        "type": "generic",
        "default": [
            "firefox.desktop",
            "org.gnome.Terminal.desktop",
            "nemo.desktop"
        ],
        "value": [
            "com.spotify.Client.desktop:flatpak",
            "nemo.desktop",
            "firefox.desktop",
            "webapp-WhatsApp1173.desktop",
            "net.lutris.Lutris.desktop",
            "steam.desktop"
        ]
    },
    "group-apps": {
        "type": "checkbox",
        "default": true,
        "description": "Group windows by application",
        "value": true
    },
    "show-all-workspaces": {
        "type": "checkbox",
        "default": false,
        "description": "Show windows from all workspaces",
        "value": true
    },
    "enable-app-button-dragging": {
        "type": "checkbox",
        "default": true,
        "description": "Enable app button dragging",
        "value": true
    },
    "launcher-animation-effect": {
        "type": "combobox",
        "default": 3,
        "description": "Launcher animation",
        "options": {
            "None": 1,
            "Fade": 2,
            "Scale": 3
        },
        "value": 3
    },
    "cycleMenusHotkey": {
        "type": "keybinding",
        "default": "",
        "description": "Global hotkey for cycling through thumbnail menus",
        "value": ""
    },
    "show-apps-order-hotkey": {
        "type": "keybinding",
        "default": "<Super>grave",
        "description": "Global hotkey to show the order of apps",
        "value": "<Super>grave"
    },
    "show-apps-order-timeout": {
        "type": "spinbutton",
        "default": 2500,
        "min": 100,
        "max": 10000,
        "step": 10,
        "units": "milliseconds",
        "description": "Duration of the apps order display on hotkey press",
        "value": 2500
    },
    "super-num-hotkeys": {
        "type": "checkbox",
        "default": true,
        "description": "Enable Super+<number> shortcut to switch/open apps",
        "value": true
    },
    "thumbnail-timeout": {
        "dependency": "!onclick-thumbnails",
        "type": "combobox",
        "default": 250,
        "description": "Delay before showing thumbnails",
        "options": {
            "50 ms": 50,
            "250 ms": 250,
            "500 ms": 500
        },
        "value": 250
    },
    "thumbnail-size": {
        "type": "combobox",
        "default": 6,
        "description": "Thumbnail size",
        "options": {
            "Small": 3,
            "Medium": 6,
            "Large": 9,
            "Largest": 12
        },
        "value": 6
    },
    "thumbnail-scroll-behavior": {
        "type": "checkbox",
        "default": false,
        "description": "Cycle windows on mouse wheel scroll",
        "value": false
    },
    "show-thumbnails": {
        "type": "checkbox",
        "default": true,
        "description": "Show thumbnails",
        "value": true
    },
    "animate-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Animate thumbnails",
        "value": false
    },
    "vertical-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Enable vertical thumbnails",
        "value": false
    },
    "sort-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Sort thumbnails according to the last focused windows",
        "value": false
    },
    "highlight-last-focused-thumbnail": {
        "type": "checkbox",
        "default": true,
        "description": "Highlight the thumbnail of the last focused window",
        "value": true
    },
    "onclick-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Click to show thumbnails",
        "value": false
    },
    "show-recent": {
        "type": "checkbox",
        "default": true,
        "description": "Show recent items",
        "value": true
    },
    "autostart-menu-item": {
        "type": "checkbox",
        "default": false,
        "description": "Show autostart option",
        "value": false
    },
    "monitor-move-all-windows": {
        "type": "checkbox",
        "default": true,
        "description": "Apply the monitor move option to all windows",
        "tooltip": "When clicking \"Move to monitor\" in the context menu, this option will move all of an app's windows instead of just the last focused window from the app.",
        "value": true
    },
    "enable-hover-peek": {
        "type": "checkbox",
        "default": true,
        "description": "Show the window when hovering its thumbnail",
        "value": true
    },
    "hover-peek-time-in": {
        "dependency": "enable-hover-peek",
        "type": "combobox",
        "default": 300,
        "description": "Window fade-in time",
        "options": {
            "150 ms": 150,
            "300 ms": 300,
            "450 ms": 450
        },
        "value": 300
    },
    "hover-peek-time-out": {
        "dependency": "enable-hover-peek",
        "type": "combobox",
        "default": 0,
        "description": "Window fade-out time",
        "options": {
            "None": 0,
            "150 ms": 150,
            "300 ms": 300,
            "450 ms": 450
        },
        "value": 0
    },
    "hover-peek-opacity": {
        "dependency": "enable-hover-peek",
        "type": "spinbutton",
        "default": 100,
        "min": 0,
        "max": 100,
        "step": 1,
        "units": "percent",
        "description": "Window opacity",
        "value": 100
    },
    "__md5__": "e40a0b58776e89bfacbd212bc3d55f20"
}
```

**Comment by piotrek94692** [comment] 2022-08-18 14:44
Same thing is happening to me on Arch.

**Comment by mtwebster** [comment] 2022-08-18 14:54
Can't reproduce - 

Anything in the logs? (~/.xsession-errors for Mint)

**Comment by BrunoNZ** [comment] 2022-08-18 19:05
This is what is logged when i click on the Expo applet:

My Mint is set to use PT_BR language, and "Espaço de Trabalho" means "Workspace". So maybe a language-related bug?

```
(cinnamon:2577): St-CRITICAL **: 15:59:01.490: st_widget_get_theme_node called on the widget [0x55d6af119fe0 StEntry.expo-workspaces-name-entry ("Espaço de trabalho 1")] which is not in the stage.

(cinnamon:2577): St-CRITICAL **: 15:59:01.490: st_widget_get_theme_node called on the widget [0x55d6af119fe0 StEntry.expo-workspaces-name-entry ("Espaço de trabalho 1")] which is not in the stage.

(cinnamon:2577): St-CRITICAL **: 15:59:01.490: st_widget_get_theme_node called on the widget [0x55d6af119fe0 StEntry.expo-workspaces-name-entry ("Espaço de trabalho 1")] which is not in the stage.

(cinnamon:2577): Clutter-WARNING **: 15:59:01.491: Spurious clutter_actor_allocate called for actor 0x55d6af119fe0/StEntry which isn't a descendent of the stage!


(cinnamon:2577): St-CRITICAL **: 15:59:01.501: st_widget_get_theme_node called on the widget [0x55d6afd01980 StEntry.expo-workspaces-name-entry ("Espaço de trabalho 2")] which is not in the stage.

(cinnamon:2577): St-CRITICAL **: 15:59:01.501: st_widget_get_theme_node called on the widget [0x55d6afd01980 StEntry.expo-workspaces-name-entry ("Espaço de trabalho 2")] which is not in the stage.

(cinnamon:2577): Clutter-WARNING **: 15:59:01.501: Spurious clutter_actor_allocate called for actor 0x55d6afd01980/StEntry which isn't a descendent of the stage!


(cinnamon:2577): St-CRITICAL **: 15:59:01.508: st_widget_get_theme_node called on the widget [0x55d6afdab3f0 StEntry.expo-workspaces-name-entry ("Espaço de trabalho 3")] which is not in the stage.

(cinnamon:2577): St-CRITICAL **: 15:59:01.508: st_widget_get_theme_node called on the widget [0x55d6afdab3f0 StEntry.expo-workspaces-name-entry ("Espaço de trabalho 3")] which is not in the stage.

(cinnamon:2577): Clutter-WARNING **: 15:59:01.508: Spurious clutter_actor_allocate called for actor 0x55d6afdab3f0/StEntry which isn't a descendent of the stage!


(cinnamon:2577): St-CRITICAL **: 15:59:01.513: st_widget_get_theme_node called on the widget [0x55d6b0bc58f0 StEntry.expo-workspaces-name-entry ("Espaço de trabalho 4")] which is not in the stage.

(cinnamon:2577): St-CRITICAL **: 15:59:01.513: st_widget_get_theme_node called on the widget [0x55d6b0bc58f0 StEntry.expo-workspaces-name-entry ("Espaço de trabalho 4")] which is not in the stage.

(cinnamon:2577): Clutter-WARNING **: 15:59:01.514: Spurious clutter_actor_allocate called for actor 0x55d6b0bc58f0/StEntry which isn't a descendent of the stage!


(cinnamon:2577): Clutter-CRITICAL **: 15:59:01.525: clutter_input_focus_set_cursor_location: assertion 'clutter_input_focus_is_focused (focus)' failed

(cinnamon:2577): Clutter-CRITICAL **: 15:59:01.525: clutter_input_focus_set_cursor_location: assertion 'clutter_input_focus_is_focused (focus)' failed

(cinnamon:2577): Clutter-CRITICAL **: 15:59:01.587: clutter_input_focus_set_cursor_location: assertion 'clutter_input_focus_is_focused (focus)' failed

(cinnamon:2577): Clutter-CRITICAL **: 15:59:01.587: clutter_input_focus_set_cursor_location: assertion 'clutter_input_focus_is_focused (focus)' failed
```

**Comment by BrunoNZ** [comment] 2022-08-18 19:17
Ps: I've just did a test using EN lang, but the bug still happening.

**Comment by thegreatyellow67** [comment] 2022-08-20 18:59
Same exact issue on cinnamon 5.4.10.  Ctrl + Alt + Up that shows workspaces make disappear grouped window list icons.

**Comment by anatolij-novoselcev** [comment] 2022-08-23 09:51
> Same exact issue on LMDE5 with updated cinnamon 5.4.10. In my case Ctrl + Alt + Up that shows workspaces makes disappear grouped window list icons.

I have the same problem on LM 21, Cinnamon 5.4.9 - 5.4.11

**Comment by BrunoNZ** [comment] 2022-08-23 22:25
I've just figured out the source of the problem: Workspace effects.
When effects are disabled, the bug happens, otherwise it doesn't. More precisely, only when the "main" option is disabled. I've tried to disable all the other effects, leaving the main button enabled, but it didn't triggered the bug.

[cinnamon-2022-08-23T192354-0300.webm](https://user-images.githubusercontent.com/1660320/186276882-8d418a18-676f-4d42-b220-861ee5f07b13.webm)

**Comment by anatolij-novoselcev** [comment] 2022-08-23 22:29
https://user-images.githubusercontent.com/111016103/186277231-08cb2036-9169-47d3-b564-32c4df52f8d2.mp4

**Comment by mtwebster** [comment] 2022-08-24 01:23
I can reproduce now, thanks a lot.

**Comment by mtwebster** [comment] 2022-08-24 23:21
should be fixed by https://github.com/linuxmint/cinnamon/commit/01faeaa0103cbd3286b0ac6cc37198fe55a0ac5f

**Closed by mtwebster** 2022-08-24 23:21 UTC
