### ISSUE TITLE
Power manager label not shown and settings have no effect on tooltip

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/Cinnamon#6882] opened 2017-09-08 07:27 UTC
```
 * Cinnamon 3.4.3
 * Mint 18.2
 * Intel Haswell-ULT Integrated Graphics Controller ("drivers: intel (unloaded: fbdev,vesa)")
 * 64 bit
 ```

**Issue**

Power Manager applet doesn't have a label to show the percentage or time remaining.

**Steps to reproduce**

Right-click the applet and choose "Configure..."

The default selection for "Display" (the only option) is "Hide label" but changing it to any of the other options has no effect: there's still no label.  I wondered if the label meant the tooltip but that shows percentage regardless of the option chosen.

**Expected behaviour**

I expected a label to be shown next to the icon showing percentage and/or time remaining, depending upon the chosen settings.

**Other information**

N/A

**Comment by NikoKrause** [comment] 2017-09-09 11:42
It works here for me on Mint 18.2 Cinnamon 3.4.6:
![screenshot-cinnamon-2017-09-09-134004](https://user-images.githubusercontent.com/8415124/30239825-7731fd3a-9564-11e7-9578-0bb293656191.png)
![screenshot-cinnamon-2017-09-09-134026](https://user-images.githubusercontent.com/8415124/30239827-79bea4f4-9564-11e7-9409-07f632bf1d52.png)

Does it show the percentage and the remaining time in the applet itself (as in the upper screenshot of mine)? Can you take a screenshot of yours?

**Comment by rmwiseman** [comment] 2017-09-11 07:18
Thanks for the reply @NikoKrause.  I see the same sort of thing as in the top part of your image, but I think it's the bottom part of your image (the bit that's visible all the time) which should be affected by the "Display" setting.  Where you've got "86% (0:29)" (which is exactly the kind of thing I want to see) I have nothing, regardless of the settings.  And what's displayed when I click is the same regardless of the settings too: it always says percentage and, if the battery is being used, the time remaining.  Here's an image as requested:

![battery](https://user-images.githubusercontent.com/10866705/30262611-7e23a600-96c9-11e7-89e8-e3d58a689e90.png)

This looks the same regardless of what I choose for "Display".  (I blurred out all but the adjacent applet icons for clarity.)

**Comment by NikoKrause** [comment] 2017-09-11 07:24
As you mentioned correctly, the settings in the applet should affect the panel icon.

Your laptop has 2 batteries. Maybe that's the reason why it doesn't work.
When you change your setting, does happen something in the `~/.xsession-errors` file?

**Comment by rmwiseman** [comment] 2017-09-11 08:30
You may be right...

> (csd-power:2806): libupower-glib-WARNING **: Property ID 'vendor' (2) was never set
> 
> (csd-power:2806): libupower-glib-WARNING **: Property ID 'model' (3) was never set
> 
> (csd-power:2806): GLib-GIO-CRITICAL **: g_dbus_proxy_get_object_path: assertion 'G_IS_DBUS_PROXY (proxy)' failed
> 
> (csd-power:2806): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
> 
> (csd-power:2806): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
> 
> (csd-power:2806): GLib-GIO-CRITICAL **: g_dbus_proxy_get_object_path: assertion 'G_IS_DBUS_PROXY (proxy)' failed

The above happens immediately when I change the setting, before I close the dialogue window.

**Comment by NikoKrause** [comment] 2017-09-11 08:32
Can you remove one battery and test with only one battery connected?

**Comment by rmwiseman** [comment] 2017-09-11 08:44
Yes, and actually it displays correctly as soon as the battery is removed!

Is this something that might be fixable or is it just unrealistic to display aggregated battery information beside the icon?

Thanks for getting to the bottom this anyway.

**Comment by leigh123linux** [comment] 2017-09-11 09:01
Closed, duplicate of https://github.com/linuxmint/Cinnamon/issues/4979

**Closed by leigh123linux** 2017-09-11 09:01 UTC
