### ISSUE TITLE
Alt+Tab does not work properly after a window is fullscreen

### ISSUE THREAD

**Issue by victords22** [linuxmint/Cinnamon#7550] opened 2018-05-05 19:28 UTC
```
 * Cinnamon version (cinnamon --version) : 3.8.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) : Fedora 28
 * Graphics hardware *and* driver used : intel integrated graphics
 * 32 or 64 bit : 64
 ```

**Issue**
Alt+Tab does not work properly after a window is fullscreen

**Steps to reproduce**

1. Open a window(say terminal)
2. Now open second window(text editor/ writer / firefox or anything)
3. Press f11 to get the text editor to full screen
4. Now when I press alt+tab I still see the text editor not the terminal. Also if I type something now it will be written in the terminal(which i cannot even see on screen).Its as if alt+tab half worked.

**Expected behaviour**
alt+tab show the other window in front of full screen window

**Other information**

**Comment by itzexor** [comment] 2018-05-05 19:32
Duplicate of https://github.com/linuxmint/muffin/issues/316

**Closed by itzexor** 2018-05-05 19:32 UTC
