### ISSUE TITLE
Memory leak in Cinnamon

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#3796] opened 2015-01-01 05:58 UTC
Hi there,

A few other users and I have noticed what appears to be a memory leak in Cinnamon 2.4. I'm on Cinnamon 2.4.3 on openSUSE, and the other user is on 2.4.5:
http://www.reddit.com/r/LinuxActionShow/comments/2qy1bo/cinnamon_245_bleeding_ram_anyone
I'm seeing well over 500MB of memory usage by Cinnamon after 11 days of being logged in, and the other user is seeing almost 2GB in a session!

---

**Update:** Bug still present with Cinnamon 2.6.13.

**Comment by lestcape** [comment] 2015-01-02 19:20
https://github.com/linuxmint/Cinnamon/issues/3690

**Comment by NeoGeo64** [comment] 2015-01-06 01:20
I, too, am having the same issue.  I'm about to give up on Mint Linux.  This is the latest in a long string of issues I've had with Mint.  I'm really about done with this distro.

**Comment by gaydenko** [comment] 2015-03-13 11:04
The same: after few hours > 500 MB with 2.4.6, Arch Linux, nvidia  proprietary driver 340.76.

**Comment by sb56637** [comment] 2015-03-16 20:16
Now I'm seeing extremely inflated memory usage (2 GB) by nemo, and I'm not really doing anything intensive with it at all.

**Comment by lestcape** [comment] 2015-03-16 23:42
@sb56637 try to disable any external nemo extension. Also see if you execute nemo as root, some files could need now root access in this case. You need detect and delete this file manually(on your user profile) to be create again by nemo without root access.

**Comment by sb56637** [comment] 2015-03-17 07:11
@lestcape wrote:
>  Also see if you execute nemo as root, some files could need now root access in this case.
> You need detect and delete this file manually

This could be what happened. Any suggestions on how to detect and delete the(se) file(s)?

**Comment by lestcape** [comment] 2015-03-17 07:24
@sb56637 https://github.com/linuxmint/Cinnamon/issues/3676 and also see:
https://github.com/linuxmint/nemo/issues/777

**Comment by sb56637** [comment] 2015-03-22 04:57
I don't seem to have any file permissions issues, but this *MASSIVE* 2GB memory leak was still persisting in Nemo. So I downgraded Nemo to 2.2.4, which has fixed it.

So should I file a separate Nemo memory leak bug?

**Comment by 0v3rth3d4wn** [comment] 2015-03-28 06:33
Cinnamon was taking 4GB Memory after a few days not rebooting and not logging out. Previously I had like 90 days uptime and Cinnamon still took 4-5GB memory. Cinnamon 2.4.6. I had to replace ( alt + f2 -> r) the session in order to clear the memory.

**Comment by sb56637** [comment] 2015-09-14 20:39
I'd say this is still a bug. I'm now on Cinnamon 2.6.11 on Ubuntu, and the `cinnamon` process is the biggest memory hog on my system. I booted my system at around 7:00 this morning, and now barely 7 hours later it's consuming over 400MB of RAM.

**Comment by utack** [comment] 2015-09-14 20:41
Same on Arch, it can easily climb up to 650Mb over 3 days.

**Comment by JosephMcc** [comment] 2015-09-14 20:52
@sb56637 Are you using the trash applet by chance? 2.6.11 is not the newest version of 2.6 and a serious bug was fixed in this applet. Not sure if that was in 2.6.11

**Comment by sb56637** [comment] 2015-09-14 20:59
@JosephMcc  Thanks for the suggestion. Nope, not using the trash applet.

**Comment by JosephMcc** [comment] 2015-09-14 21:22
I know this issue if frustrating if you are experiencing it and I mean no disrespect but the feedback posted in this issue really does nothing to help solve this issue. We need to know more info, such what kinds of things are you doing or using when you experience this.

A good place to start is by grabbing this applet: https://github.com/mtwebster/Cinnamonitor
and placing it on cinnamons panel. Keep an eye on it while you're working and see if there are any particular actions you do that cause jumps in memory usage.

**Comment by sb56637** [comment] 2015-09-14 21:39
@JosephMcc  Likewise, I don't mean any disrespect, my apologies if I sounded grumpy.

I'll try out the applet to see if I notice anything. But the memory usage doesn't really seem to correlate with any specific action or event. It just steadily rises from a base of around 200MB and just keeps going from there.

I should mention that this particular machine has plenty of free RAM, 8GB total. Could this just be a case of "free RAM is wasted RAM" and the Linux kernel is just trying to cache all of Cinnamon for speed? The Gnome system monitor just labels the column as "Memory", which I don't think included the caches.

**Comment by JosephMcc** [comment] 2015-09-14 21:50
@sb56637 My machine is the same, 8GB total. On a fresh start cinnamon uses around 110mb and even after a couple of days never raises above 150. That's what makes these types of issues so hard to troubleshoot. If you don't experience the problem it's nearly impossible to pinpoint it's source.

**Comment by utack** [comment] 2015-09-14 21:53
sb56637 has a different system with Ubuntu, I am on Arch.
Maybe @JosephMcc you can give us some pointers what we could compare?
Running apps that spawn a tray icon
Running apps that spawn notifications
Applets and panel layout.
What is important here?

**Comment by sb56637** [comment] 2015-09-14 21:57
Is the `cinnamon` process the one that hosts the javascript applets? That would seem to be the biggest source of variability from one system to another.

**Comment by JosephMcc** [comment] 2015-09-14 22:09
@sb56637 Yes

While I know it inconvenient, to start troubleshooting these issues the first thing you should do is disable any 3rd party applets, desklets, and extensions. Not to place blame on those devs but just to reduce some of the variables involved. In fact I would suggest only using the bare minimum applets you need for a bit just to see what effect it has. Like I said we recently discovered an issue in the built in trash applet where a single delete operation could explode cinnamons memory usage to several gigabytes.

**Comment by sb56637** [comment] 2015-09-14 22:13
Not sure if this LookingGlass screenshot helps any?

![screenshot from 2015-09-14 17 11 53](https://cloud.githubusercontent.com/assets/2692138/9863235/cfc3b8dc-5b03-11e5-8a83-4b5aab63e5af.png)

BTW I upgraded to Cinnamon 2.6.13, and after an hour or so `cinnamon` process memory usage is over 350MB.

**Comment by werescape** [comment] 2015-10-12 02:36
Am also having this, I have 8GB RAM in my laptop and just got locked up completely, granted it took awhile to get there, but I have remember to reload Cinnamon daily.

**Comment by benhaze** [comment] 2015-10-21 08:13
Same for me.
- Version 2.6.13
- 16 GB RAM
- NVidia-Driver
- cinnamon process mem usage: 508 MiB (from gnome-system-monitor)
- System Uptime: 1:16
<br><br>
![bildschirmfoto 2015-10-21 10 02 35](https://cloud.githubusercontent.com/assets/15227645/10631074/a4085c30-77db-11e5-9a47-837ce382a227.png)

**Comment by brianjmurrell** [comment] 2016-02-29 15:41
cinnamon-2.8.6-1.fc23.x86_64 here, using 3.4GB of VM and 1.4GB of real ram in 12 days.

LookingGlass says glibc_uordblks is 675MB.

I don't have any desklets or extensions enabled.  It's really not practical to disable all applets as the desktop/environment will be unusable.

**Comment by ManIVIctorious** [comment] 2016-09-05 16:33
Does this still happen in cinnamon 3.0?

**Comment by NeoGeo64** [comment] 2016-09-05 16:39
Not that I'm aware of.  Cinnamon 3.0 is pretty stable.

**Comment by geckolinux** [comment] 2016-09-05 16:40
My Cinnamon process was started about 48 hours ago, currently consuming 238MB. I'll check to see if it continues going up.

**Comment by utack** [comment] 2016-09-05 16:47
Definitely still happening  
The rate is much better now, It can run for 5-7 days for me before hitting ~700MB, but it is not entirely gone

**Comment by 0v3rth3d4wn** [comment] 2016-09-05 16:49
Sometimes I just Alt+F2 and "r" to reload cinnamon and the memory gets flushed.

**Comment by maks1m** [comment] 2016-09-05 22:58
I have a fresh install of Linux Mint, cinnamon version is 3.0.7.
After a day of usage, the cinnamon process takes 579 Mb.
![screenshot from 2016-09-06 01-57-19](https://cloud.githubusercontent.com/assets/4282621/18257965/5254ed62-73d5-11e6-850f-3acc8db8bb70.png)

**Comment by brianjmurrell** [comment] 2016-09-06 15:54
I have cinnamon 3.0.5 here, installed July 05/16 on F24.  My ```cinnamon``` process has been running since Aug. 08:

```
brian     2684  2641  2 Aug08 ?        19:57:27 cinnamon --replace
```

It's VM usage:

```
VmPeak:	 3012408 kB
VmSize:	 2838196 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	 1344436 kB
VmRSS:	 1116724 kB
RssAnon:	 1077184 kB
RssFile:	   31028 kB
RssShmem:	    8512 kB
VmData:	 1635676 kB
VmStk:	     136 kB
VmExe:	      12 kB
VmLib:	   61276 kB
VmPTE:	    4224 kB
VmPMD:	      24 kB
VmSwap:	  266784 kB
```

So as we can see, it's using 3GB of VM and 1GB of real memory.  Again, I would submit that chewing up 1GB of real memory for desktop management is a bit much, so I'd say, yes, this is still happening on 3.0.

**Comment by NeoGeo64** [comment] 2016-09-09 16:10
It is still happening on 3.0 but it's nowhere near as unstable as 
previous versions.  You're right and I agree; Cinnamon needs much 
cleaner memory management code.  As a side issue, I use my Linux machine 
as a WiFi hotspot (use ethernet to connect on my computer) and it 
crashes after a few weeks.  Any suggestions?

**Comment by mainmachine** [comment] 2016-09-13 06:16
@NeoGeo64 - cron job or systemd timer for a weekly reboot?

What crashes, exactly? Might just need a task to automatically restart a service if that's how you're fixing it...

**Comment by Madh93** [comment] 2016-09-22 20:24
Manjaro 16.08 with Cinnamon 3.0.7 and same issue.

Startup:
![photo_2016-09-22_21-23-30](https://cloud.githubusercontent.com/assets/5855179/18764768/d308e0ac-810a-11e6-866a-4ce7be6f5592.jpg)

After 8 hours:
![photo_2016-09-22_21-23-24](https://cloud.githubusercontent.com/assets/5855179/18764771/d972dc5e-810a-11e6-9fda-1b8a5a9aad8b.jpg)

**Comment by nick-s-b** [comment] 2016-10-24 21:46
`Kernel: 4.4.0-45-generic x86_64 (64 bit) Desktop: Cinnamon 3.0.7   Distro: Linux Mint 18 Sarah`

Last week I noticed that cinnamon process was using 1.5GB of RAM before I restarted it. Since then, I've been logging cinnamon process and have been collecting memory usage every 5min. Here's the data if anyone's interested: http://pastebin.com/GAP8zgAv (1st column - unix time, 2nd column memory use in bytes).

Today, I've noticed that my cinnamon process is using roughly 722MB of RAM... which is on the high end given how most of the time it doesn't cross 300MB. I plotted the data with gnuplot and this is what the memory use looks like:

![Cinnamon mem use](https://i.sli.mg/bUiP53.png)

and here's what 11 days of cinnamon memory use look like (all the data I have). Dips are reboots or cinnamon process restarts. Click on images to see full-size.

![cinnamon mem](https://i.sli.mg/zXCbyy.png)

I'm not exactly sure what those steep memory jumps correspond to. I'm also not sure how to figure out what's causing this. If anyone has any suggestions or wants me to provide logs, please let me know and be specific please.

**Comment by JosephMcc** [comment] 2016-10-24 23:02
The graphs are neat but don't provide any really useful info. What we need to know are things like, what were you doing at the time? What applets are you running? Are you using something that sends a lot of notifications? Is there an applet or desklet you are using that is updating constantly? Like a system monitor type of applet. Please don't take this as rude. A lot of people are posting screenshots of their memory usage. We believe you. We know there is an issue but tracking it down is pretty much impossible without useful info so we can at least attempt to reproduce it.

As an example, the other day I installed the Multi Core system monitor applet. I can tell you that it definitely caused an increase in Cinnamons memory usage on my machine.

**Comment by nick-s-b** [comment] 2016-10-25 00:05
I've been running the same set of applets for the past few months Here's what they are:

Search Applet, System Monitor, Weather, Calendar, Keyboard, Menu, Nvidia Prime, Network Manager, Notifications, Panel launchers, Removable drives, Sound, System Tray, Window List, Windows Quick List.

As to what caused those jumps, I have no idea. I've tried doing few things to see if I can trigger the memory leak but everything I tried didn't seem to change things.

**Comment by lestcape** [comment] 2016-10-25 02:05
@nick-s-b i have a similar problem before, my solution was create another user and logging to that user, configure my desktop similar to the old one. When i make the test again, the problem not disappear, but was reduced a lot. I don't know how... But i can live with that now...

**Comment by nick-s-b** [comment] 2016-10-26 00:55
@lestcape that sounds like a placebo solution to me. Unless we know what's causing this, there's really no way to resolve it properly.

**Comment by lestcape** [comment] 2016-10-26 01:00
@nick-s-b true... Sorry for try to help you.

**Comment by nick-s-b** [comment] 2016-11-23 01:28
I wrote a script to notify me when memory use jumps by 5% or more (you can set it to what you prefer) and to notify me when `cinnamon` process consumes more than 300MiB (again, you can adjust it). This will allow you to try to figure out what causes memory leaks on your setup. You can also restart `cinnamon` process if you wish.

Save the script below as `cinnamonlog.sh` and put it in a bin directory that you prefer and add this line to cron by typing `crontab -e` and adding this to the bottom:  `*/5 * * * * /PATHTOYOURBIN/cinnamonlog.sh` This will cause the script to run every 5 min. Change it to 1min by replacing 5 with 1 if you want more granularity.

cinnamonlog.sh: 

```
#!/bin/bash

logfile="$HOME/.cin-log.txt"
changemax=5 #percent change
cinmax=300000 #max memory

#create the log file, if it doesn't exist, and check if we can write to it
( [ -e "$logfile" ] || touch "$logfile" ) && [ ! -w "$logfile" ] && echo "Error: Cannot write to $logfile" && exit 1

#grab the previous cinnamon process memory value
previousmem=$(tail -n 1 $logfile | awk -F  "," '{print $2}')
currentmem=$(echo 0 $(awk '/Rss/ {print "+", $2}' /proc/`pidof "cinnamon"`/smaps) | bc)

#calculate percent change if previous mem exists and notify us if it increases by more than 10%
if [[ $previousmem != "" ]]; then
    percentchange=$(( (currentmem - previousmem)*100/previousmem ))
    if [[ $percentchange -ge $changemax ]]; then
        export DISPLAY=":0"
        /usr/bin/notify-send "Cinnamon Monitor" "Memory has increased by $percentchange%"
    fi
fi

#output new mem value to the log
echo -n `date +%s` >>$logfile
echo -n "," >>$logfile
echo $currentmem | bc >>$logfile

if [ "$currentmem" -gt "$cinmmax" ]; then
    export DISPLAY=":0"
    /usr/bin/notify-send "Cinnamon Monitor" "Current mem usage: $currentmem ; cinnamon process exceeded $cinmax."
    #pkill -HUP -f "cinnamon --replace"  #uncomment this line to restart cinnamon process; or type Alt+F2 and type "r" to restart it manually
fi

```

**Comment by lestcape** [comment] 2016-11-23 01:32
@nick-s-b:
https://github.com/mtwebster/Cinnamonitor
https://github.com/lestcape/Garbage-Collector

**Comment by nick-s-b** [comment] 2016-11-25 01:39
Well, after running cinnamonlog for few days, I've noticed few things:

- Image Viewer/Xviewer causes memory use to jump between 5-8%
- when Nemo creates new thumbnails for new images, memory again increases by few percent. that tends to accumulate.

Anyway, I'll continue keeping track of mem usage.

**Comment by germanfr** [comment] 2016-12-04 21:51
Not sure if related, but there's an obvious memory leak when changing themes.
I have a script that auto-reloads the theme each time I save changes, and after a while the memory increases a lot.

I have made a test script. In a few seconds memory increases up to 1GB, and never decreases again until you restart Cinnamon.
```bash
while true ;do
	gsettings set org.cinnamon.theme name default
done
```
It happens also if you change it manually through theme settings.

**Comment by xeon-zolt** [comment] 2016-12-05 00:29
![screenshot from 2016-12-05 05-57-59](https://cloud.githubusercontent.com/assets/4529442/20870521/d95fe78c-baaf-11e6-9d5e-331d27eec60b.png)

i have faced this issue with cinnamon recently 

any idea what is causing it or how do i troubleshoot it

**Comment by nick-s-b** [comment] 2016-12-05 08:05
I have one more observation... after I upgraded to a 4K display, Cinnamon's usage increased dramatically. Average session now reaches 600MB within an hour of use and it's a lot more unpredictable.  At this very moment, it's using around 700MB.

Here's the graph from the time I got a 4K display:
![mem leak](https://i.sli.mg/3D9OQe.png)
Dips to zero are manual restarts.

So, a bigger display means a lot larger cinnamon memory use.

**Comment by lestcape** [comment] 2016-12-05 18:14
@germanfr the main problem it's the theme icons. They are not destroyed in several extensions. The most  important i think it's the cinnamon menu. You can play to remove the cinnamon menu and then add it again, and you will see what happens.

**Comment by germanfr** [comment] 2016-12-05 18:57
@lestcape yep. Added lots of menus and cleared the panel several times and it happened. There's a memory leak there. I believe it's not related with this issue.

**Comment by lestcape** [comment] 2016-12-06 00:45
@germanfr yes, the cinnamon menu problem it's not related, but not destroy theme icons in some places, well, cloud be.

**Comment by xeon-zolt** [comment] 2016-12-07 15:02
how to trouble shoot memory leak
![screenshot from 2016-12-07 11-31-04](https://cloud.githubusercontent.com/assets/4529442/20972806/1b830514-bcbc-11e6-8fc5-707c516ac9a8.png)

**Comment by spider-mario** [comment] 2016-12-23 12:19
I haven’t verified but I have the impression that memory (and CPU) usage increases a lot when tray icons change. For example, for online backups, I use SpiderOak ONE, which animates its tray icon when it backs up stuff, and Cinnamon’s memory usage at the end of a session seems much higher if I had to upload a lot of data.

I guess it could be easily verified by writing a small app with a tray icon that would change repeatedly.

**Comment by nick-s-b** [comment] 2016-12-23 22:48
After upgrading to Cinnamon 3.2.x, memory problem seems to be mostly gone. While the memory does jump a certain percentage as before, it is not as bad. I'm hopeful that this improvement in memory consumption will continue. Thanks devs!

**Comment by spider-mario** [comment] 2016-12-29 20:31
Really? for me, it got much worse than with 3.0.

**Comment by nick-s-b** [comment] 2016-12-29 22:29
@spider-mario Well, I just did some checking to see what's going on. I'm using the script above to constantly check my memory usage and I've modified it to warn me when `cinnamon` crosses the 800MiB threshold. Since updating to 3.2.x, I haven't received that many notices. It almost never crosses the 800 mark anymore but it does go up slowly during the course of the day. Before 3.2.x, I've seen `cinnamon` process use 1GB+ of RAM every second day or so. I have not used 2.x branch at all so have no idea.

Biggest jump in RAM usage occurred when I added a 4K monitor to my setup. More pixels on screen = more RAM for `cinnamon` for some reason. That's when `cinnamon` went from using 150MiB at the start to 300MiB+ right off the bat.

Also, when I browse images with `Xviewer`, the default image viewer, `cinnamon` RAM usage skyrockets. Why? I have no idea.

Here's the RAM usage from the past few days... I just plotted the last 500 data points. Dips are shutdowns at the end of the day.

![cinnamon ram](https://i.imgur.com/nx9ishn.png)

**Comment by magnetx** [comment] 2017-09-03 19:28
Still exists in 3.4. Pity.

**Comment by nick-s-b** [comment] 2017-09-03 20:16
@magnetx yeah, it's still there but it's not as bad. It never goes over 600MB anymore.

**Comment by melmelissa** [comment] 2017-09-10 19:32
Hello
the problem is still present
Cinnamon 3.4.6 with ArchLinux.

Excessive consumption of the ram from the start of the pc (1.1 GB anyway)
and after 5 hours of operation I am at 2.8 GB with only 6 open firefox tabs and Quodlibet ..

the problem is nonexistent on my Debian Sid Cinnamon (3.4.6)

it's a memory leak of Cinnamon on Arch?

the more the versions of Cinnamon evolve, the more it becomes greedy, as much as Gnome, pity

hoping for a fix ...
[url=http://pix.toile-libre.org/?img=1505071937.png][img]http://pix.toile-libre.org/upload/img/1505071937.png[/img][/url]

**Comment by solax76** [comment] 2017-09-20 14:57
I think this is not related to Cinnamon. I had the same issue with Ubuntu, then I tried different distros with different window manager and searched the net to find a solution, but nothing.
I have a DELL latitude with nvidia proprietary driver and I suspect that this due to graphic driver.
Now I'm using Mint on two notebooks, one with nvidia and one with intel GPU, and the issue is present much more on the first one.

**Comment by aitorbk** [comment] 2017-09-21 16:35
I also have the problem, and yes, it is worse with Nvidia and high resolution panels.
Not only that, but also the GPU use is much much higher than even Unity!
I get 400MB of memory use that quite quickly climb to about 1GB, and stays there.

**Comment by sboukortt** [comment] 2017-09-21 18:28
For me, what seems to accelerate the leak is when there is an animated icon in the systray, for example SpiderOak ONE uploading stuff.

**Comment by melmelissa** [comment] 2017-09-25 20:47
Nvidia drivers seem to be worried.
on my Sid after updating the Nvidia driver, I have 200MB of RAM at startup used more before the update.
knowing that I did not add any software at startup.

Therefore, ArchLinux and Debian are almost identical in RAM consumption at startup.
About 1 GB used.
Maybe the Intel chipset (i7 3630qm) uses some of the ram?

**Comment by nick-s-b** [comment] 2017-09-29 20:57
I monitored Cinnamon 3.5.7 over the past 6-7 days again. Here's the plot:

![Cinnamon 3.4.6](https://i.imgur.com/Ist8Bi3.png)

It seems to me that memory usage has gotten somewhat worse than from before. It now averages over 700MB. If I were betting money, I'd wager that Nemo's thumbnails view is the culprit. When I browse folders with lots of images in a thumbnail mode, memory always spikes up a lot. Nemo's also quite unstable for me (crashes about 6-12 times every day on my machine).

**Comment by okornev** [comment] 2017-12-13 06:24
Memory map for 'cinnamon' process shows that 80% of memory usage is 'heap'. 
![image](https://user-images.githubusercontent.com/3410513/33924450-1e7269f2-dfa4-11e7-8239-ddaaae0b3e88.png)

**Comment by leigh123linux** [comment] 2017-12-17 21:45
Closed

Duplicate of #6850

**Closed by leigh123linux** 2017-12-17 21:45 UTC
Labels: BUG
