### ISSUE TITLE
Applet Manager does not enforce max instance setting correctly for applets

### ISSUE THREAD

**Issue by Gr3q** [linuxmint/cinnamon#9004] opened 2019-12-06 10:04 UTC
```
 * Cinnamon version  4.4.3
 * Distribution - Arch
 * Intel Integrated graphics
 * 64 bit
 ```

**Issue**
Applet manager does not enforce max-instance setting in the applet's metadata correctly. It works if it's not set or set to 1, but anything above that allows an infinite number of the same applets.

Also it allows to spam the Add (+) button what can lead to crashes or messed up settings for said applet for the current session.

**Steps to reproduce**
For example add more than 3 instances (the maximum) of the Weather Applet.

**Expected behaviour**
Add button is disabled after the maximum number of instances is reached. Also button is disabled after its clicked until the applet is added.

**Comment by icarter09** [comment] 2019-12-06 14:28
@eli-schwartz

**Comment by collinss** [comment] 2021-02-20 20:32
Hi @Gr3q , we've changed the way we use the max-instances field over time. Originally it was used as you're describing, but now we only use it to distinguish between single-instance and multi-instance. (I can't think of a use-case where you could allow more than one instance, but not more than x instances, so I don't really see the point in having a multi-instance applet that doesn't allow an infinite number of instances). Admittedly it would probably make more sense to rename it and make it a boolean setting so it's less confusing, but I believe we left it as-is for backwards compatibility reasons, and I'm not sure it's worth the effort to change it now. In any case, this is actually working as intended, so I'm going to close this. The crashing is a different issue entirely, so we probably want a separate issue for that

**Closed by collinss** 2021-02-20 20:32 UTC
Labels: APPLETS, BUG REPRODUCED

**Comment by Gr3q** [comment] 2021-02-20 20:36
Ok, I agree on it really shouldn't have a limit if it supports multiple instances. One user brought it up, I'll make he is informed as well.

Thanks
