### ISSUE TITLE
Custom date format broken

### ISSUE THREAD

**Issue by korteland** [linuxmint/Cinnamon#7050] opened 2017-11-19 12:11 UTC
```
 * Cinnamon version 3.6.3
 * Distribution - Arch Linux
 * Nvidia GTX 1080, nvidia driver
 * 64 bit
 ```

**Issue**
Updated to Cinnamon 3.6.3 today (from Cinnamon 3.6.2), and noticed that the custom date format in my calendar applet was broken. It displayed the hour and minute separated by a newline, instead of the custom format string I use. Even resetting to the default custom format string causes this breakage. The clock display looks normal if I turn off "Use a custom date format".

**Steps to reproduce**
From the settings, with the stock date format, select "Use a custom date format".

**Expected behaviour**
Should display day, date, etc.

**Other information**
I have duplicated this on two separate machines running Cinnamon 3.6.3.

**Comment by mtwebster** [comment] 2017-11-19 13:55
Duplicate of #7037 and fixed

**Closed by mtwebster** 2017-11-19 13:55 UTC
