### ISSUE TITLE
[BUG] Cinnamon sometimes hangs on "show workplace selection screen"

### ISSUE THREAD

**Issue by ienzo** [linuxmint/cinnamon#11165] opened 2022-09-12 08:24 UTC
* Cinnamon version Cinnamon 5.4.12, not using the daily builds, using the base Linux Mint Cinnamon
 * Distribution Linux Mint 21
 * Graphics hardware *and* driver used, NVIDIA Geoforce 940mx, nvidia-driver-515 v515.65.01-0ubuntu0.22.04.1
 * 64 bit
 * Attached ~/.xsession-errors: [xsession-errors.log](https://github.com/linuxmint/cinnamon/files/9546132/xsession-errors.log)

### Issue

Cinnamon sometimes hangs when invoking "show workplace selection screen" and it looks like this:

![Screenshot from 2022-09-12 16-10-30](https://user-images.githubusercontent.com/4653894/189606421-3f383485-2300-4d03-a300-33d7af5071fe.png)

### Steps to reproduce

I cannot reliably reproduce this bug. It just sometimes happens when I invoke "show workplace selection screen" through Super+Tab, a custom key binding. 

### Expected behaviour

It's supposed to invoke "show workplace selection screen" without any issue.

### Other information

I did not have this problem in Linux Mint 20.3. I only started having this problem when I did a clean install of Linux Mint 21, though many of my customization settings were saved in my Home folder.

**Comment by mtwebster** [comment] 2022-09-12 14:23
Do you recall if this happens when there are any windows open on the current workspace? Or only when there are none?

**Comment by ienzo** [comment] 2022-09-13 04:12
> Do you recall if this happens when there are any windows open on the current workspace? Or only when there are none?

I've seen it happen either way, either with multiple windows open or no windows open. Though it seems to happen more with windows open than otherwise, though this may be the result of bias since I usually have windows open than otherwise. Also it does not happen when I newly boot the OS, it happens a few hours into use.

**Comment by ienzo** [comment] 2022-09-20 14:54
I was able to reproduce the bug twice using this method. Seems like this is it. I made my window animations faster. I will use this set up and let you know if it still happens.

**Comment by mtwebster** [comment] 2022-09-20 15:51
I'm pretty sure this is fixed now (not in a release yet, though) - the commit I linked above - https://github.com/linuxmint/cinnamon/commit/b207debc9f4344307c7246cc1eb0d7f71c3b0743.

I'm was unable to reproduce this in cinnamon master, but rolling back to 5.4.12, I was able to immediately.

A couple of ways you can confirm this:
- Download the tar from here: https://github.com/linuxmint/cinnamon/releases/tag/master.mint21, unpack the packages and install them (`sudo dpkg -i *.deb` from a terminal - don't double-click in nemo).
- Manually edit the file `/usr/share/cinnamon/js/ui/overrides.js` to reflect the change in that commit.

Either route you go, make sure you restart Cinnamon after (alt-f2, r, enter)

**Closed by mtwebster** 2022-09-20 15:51 UTC
Labels: New

**Comment by mtwebster** [comment] 2022-09-20 15:59
I understand  - I'll try for a release by the weekend.

**Comment by ienzo** [comment] 2022-09-21 05:24
Thank you so much!
