### ISSUE TITLE
Vertical Panel

### ISSUE THREAD

**Issue by cb474** [linuxmint/Cinnamon#629] opened 2012-04-20 06:42 UTC
I'm excited about Cinnamon as the most useable effort to bring a more traditional desktop metaphor to Gnome 3. One thing I really would love to see is the ability to move the panel to the side of the screen. With a small laptop monitor, this is a must have feature for me. I just don't want to waste what little vertical space I have with a panel at the bottom or top, when I've got plenty of extra room at the sides of the screen.

Thanks for considering this idea and thanks for all the great work already on Cinnamon.

**Comment by brownsr** [comment] 2015-02-09 17:45
Feel free to auto-hide the panel to increase visible space and/or to install something like cairo dock if you like to see things vertically.  That can be configured to show its icons down any side of the screen.

**Comment by lestcape** [comment] 2015-02-10 04:25
After the pull https://github.com/linuxmint/Cinnamon/pull/3746 will merged (thanks @dalcde),  with the posibility of create a vertical panel, with the current search provider feature (thanks to @glebihan) and when this https://github.com/rgcjonas/gnome-shell-extension-appindicator (thanks to @rgcjonas) will be merged (see roadmap: https://github.com/linuxmint/Roadmap) i really don't know why other people could continue doing desktops interfaces, we can clone all possible appearances and features of any current desktop inside cinnamon and without use any other external code. I think we just have to be patient, I do not think that cinnamon developers will take the risk of mix everything at once, but, what is the desktop that has more feature by release, than the cinnamon desktop today?

**Comment by GitRASQ** [comment] 2015-02-17 06:14
+1
Low res laptop screen, don't want to waste vertical screen space. Need to put panel on the side.

**Comment by damarev** [comment] 2015-05-06 06:32
+1

After doing some google research....  this bug has been around since 2002, almost 13 years: https://bugzilla.gnome.org/show_bug.cgi?id=86382

I think this is a major UX issue. The "window list" on a vertical panel is just unusable, and as other people has already said, nowadays widescreens are the standard. From many points of view a vertical panel should be the most logical option.

**Comment by lestcape** [comment] 2015-05-06 17:17
Is possible add a vertical panel as a 3rd party extension right now, will really easy if this will be merged https://github.com/linuxmint/Cinnamon/pull/4045. Of course, this mean make a patch to all cinnamon standar applets to allow be working vertical and waiting for the others 3rd party applet, to see if they want add compatibility with it or not. The only intention will be test this for a while to see if the idea is finally accepted by the cinnamon devs, otherwise this always could be a 3rd party option, is win or win i think...

The work in progress here:
https://github.com/lestcape/Vertical-Panels

**Comment by dalcde** [comment] 2015-05-06 18:45
On Wed, May 06, 2015 at 10:17:20AM -0700, Lester Carballo Pérez wrote:
>Is possible add a vertical panel as a 3rd party extension right now, will really easy if this will be merged https://github.com/linuxmint/Cinnamon/pull/4045. Of course, this mean make a patch to all cinnamon standar applets to allow be working vertical and waiting for the others 3rd party applet, to see if they want add compatibility with it or not. The only intention will be test this for a while to see if the idea is finally accepted by the cinnamon devs, otherwise this always could be a 3rd party option, is win or win i think...

I think the general consensus among the devs is that we think vertical
panels are good ideas, but don't know how to display applets correctly.
As you said, it is really easy to make vertical *panels*, especially
given the new panel structure. So really don't rush to create a panel
that is vertical.

I do have some preliminary ideas regarding how to handle applets, but
I haven't got anything solid. Bring out your ideas if you have got any.
Also come and talk to us on #linuxmint-dev. Implementing it as an
extension is definitely not the way out, since it misses the core of the
issue - applets.

**Comment by lestcape** [comment] 2015-05-07 00:41
@dalce of course that this is possible thanks of what you do, and i agree with you on all, except one thing.

I'm not agree with you, about your plan of how do this. I think that the most natural way is black listing all applets, except the applet that implemented an specific functionality (the vertical panel behavior), and then introduce the api slowly and as an extension. Of course, is the best that this extension will be provided by cinnamon, and not as a third party. When several popular applets support this and this will be tested for a while, you can include in the cinnamon core the extension. I like to have the vertical panels, but not taking risk on the cinnamon core, and the cinnamon popularity. Is clear that this will create several problems, so the best will be have this problems out of the cinnamon core, to be fixed slowly and also at the same time provide the extension, because in that way applets could begin the migration soon as possible.

As i see what is occurring on cinnamon about the time, this will be the best opportunity. @clefebvre  is really hard some times, and he don't like the inclusion of things that would cause some problems on Cinnamon. Ofcourse that this is the best decision that he can take, but as an extension he don't need to be exhaustive, and this will be include soon... I'm stupid (but not to much) and i know that make a vertical panel is a thing that you want to do, but you have compromised with cinnamon devs and you will involved on a hard situation where of course, there are not a solution to all problematic, because the solution will be on the hands of third party developments and not in your hands...

I have not any compromise, and i can do what i want, also an automatically override of the cinnamon code when the extension init (also a complete override of panels.js file), if i have not any other solution.
Finally, are you sure that you want to wait 3 years to see your vertical panel implementation working on cinnamon, as same of what occurs with your other implementation of panels, or this one, that finally was partially merged and you will need to cut the scope a lot?

Sorry for be honest and say what i think. Possible i 'm wrong as is normally, I'm not a cinnnamon dev and i don' t know all details, i speak as a github user...

**Comment by dalcde** [comment] 2015-05-07 06:26
On Wed, May 06, 2015 at 05:41:41PM -0700, Lester Carballo Pérez wrote:
>I'm not agree with you, about your plan of how do this. I think that the most natural way is black listing all applets, except the applet that implemented an specific functionality (the vertical panel behavior)

Okay I haven't even stated my plan of what to do with applets, and you
disagree?

>, and then introduce the api slowly and as an extension. Of course, is the best that this extension will be provided by cinnamon, and not as a third party. When several popular applets support this and this will be tested for a while, you can include in the cinnamon core the extension. I like to have the vertical panels, but not taking risk on the cinnamon core, and the cinnamon popularity. Is clear that this will create several problems, so the best will be have this problems out of the cinnamon core, to be fixed slowly and also at the same time provide the extension, because in that way applets could begin the migration soon as possible.

As an extension, you cannot declare an API. Only Cinnamon can declare an
*Cinnamon* applet API. We can introduce it as an experimental feature
and not expose it on cinnamon-settings if it proves to cause some
trouble, but I doubt it would, since what we have to do is more or less
the same as what we are currently doing. If it gets merged early enough
in the release cycle, there will be quite a lot of time to sort bugs
out.

OTOH, making it an extension is *much* more prone to causing troubles.

>As i see what is occurring on cinnamon about the time, this will be the best opportunity. @clefebvre  is really hard some times, and he don't like the inclusion of things that would cause some problems on Cinnamon. Ofcourse that this is the best decision that he can take, but as an extension he don't need to be exhaustive, and this will be include soon... I'm stupid (but not to much) and i know that make a vertical panel is a thing that you want to do, but you have compromised with cinnamon devs and you will involved on a hard situation where of course, there are not a solution to all problematic, because the solution will be on the hands of third party developments and not in your hands...

Every now and then, we make big changes that can possibly introduce
regressions. The Cinnamon devs have no issues with that. I am, however,
very convinced that extensions will not work as well and cleanly as you
wish.

>Finally, are you sure that you want to wait 3 years to see your vertical panel implementation working on cinnamon, as same of what occurs with your other implementation of panels, or this one, that finally was partially merged and you will need to cut the scope a lot?

The "3 years" is because I got busy with life and couldn't allocate much
time to Cinnamon, and my involvement basically halted. There was nothing
wrong about Cinnamon itself. Also the current one is almost the same as
the one originally proposed, apart from slightly cleaner code, and that
I gave up on "drag-and-drop to move panel" because it becomes a mess
especially when you have monitors of different sizes. The "cut the
scope a lot" part is entirely untrue.

**Comment by lestcape** [comment] 2015-05-07 07:46
Ok then, that's is excellent. What i speak is what i see outside, not need to be the true of course. My preoccupation is exactly the time involved (after what you do, i have not doubt that you can do what you want in a short time). The problem is that is not only create the api, is also port the third party applets and this only can be done by the authors, so, this will be a lot of time to be completed the integration. This is why i consider the  involved time very important and my only preoccupation about that.
Anyway thanks, for the clarifications.

**Comment by harogaston** [comment] 2015-05-11 22:59
Maybe merge with this one https://github.com/linuxmint/Cinnamon/issues/278 ?

**Comment by gresolio** [comment] 2015-05-27 12:43
For years have used a left panel, and for me it's the best way by far. Please add side-panel mode :) Thanks

**Comment by vithalklrk** [comment] 2015-08-13 13:50
+1

Please provide side panels. Most monitors nowadays are wider than taller

**Comment by luispabon** [comment] 2015-08-23 11:30
Panel on the side and menu on the window decoration save LOADS of vertical space. Unity really has the edge on making use of the most screen real estate and the main reason I'm stuck with it for the foreseeable.

**Comment by Deathangel908** [comment] 2015-08-26 18:12
+1

**Comment by Vahan86** [comment] 2015-08-31 10:43
+1

**Comment by attila123** [comment] 2016-02-04 18:09
I have found a perfect workaround (seems so far) to this problem! :) :)
I also have XFCE installed (actually I installed Cinnamon on top of Linux Mint XFCE edition)), so I started xfce4-panel (e.g. via Alt + F2 or from command prompt (I guess something like 'nohup xfce4-panel &')). If you don't have XFCE, installing xfce4-panel with your package manager would hopefully pull the required dependencies nicely.
In the XFCE panel's preferences you need to set it to Deskbar mode. I set it to 60 px wide with 2 rows.
I needed to restart Pidgin, but after that even that appeared on the XFCE panel.
Everything seems to work nicely, e.g. the windows do not maximize under the panel.
Then you can set the Cinnamon panel to auto-hide to get it out of the way. :)
Still, when you press the Super key (or whatever you configured), the Cinnamon launcher (or whatever it is called) appears, which is also nice. :)
I didn't check the RAM footprint, because my work PC has 12 GB currently, so honestly, I don't care.
Enjoy!!! :)

**Comment by gresolio** [comment] 2016-02-06 12:20
A better workaround in this case: use Xfce entirely instead of Cinnamon, not only one panel.
But here we are requesting a new useful feature exactly for Cinnamon...

**Comment by denisleroy** [comment] 2016-03-15 11:07
+1 here as well, currently the main reason I'm sticking with old Xfce.

**Comment by jkbrwn** [comment] 2016-07-06 03:04
Hey everybody from year 2012 who requested this feature... it is I, Mint user from the present future. Still no vertical panel! Can I get a +1!!!!!!!

**Comment by collinss** [comment] 2016-07-06 06:51
@jkbrwn There is currently a pull request to implement this feature, but it was postponed until Cinnamon 3.2 because there will likely be a lot of bugs with a code change as extensive as this, and there wasn't enough time to test and bugfix before the release of Cinnamon 3.0. It will be here soon, though, so please be patient.

**Closed** 2016-08-17 03:09 UTC
Labels: FEATURE REQUEST
