### ISSUE TITLE
Panels disappear after returning from lock screen on ubuntu 

### ISSUE THREAD

**Issue by daschuer** [linuxmint/Cinnamon#3793] opened 2014-12-30 19:21 UTC
I am using Ubuntu Trusty and Cinnamon 2.4.5ubunt2. 

After the Cinnamon Update from 2.2 I am facing the issue, that he panels are disappeared after returning from the lock screen. 
I am able to start cinnamon-looking-glass, but I can find an error message or something else obvious. 
It is also possible to "successful" resart cinnamon, but the panels are still not appearing. 

In my system the gnome-screensaver and the cinnamon-creensaver is installed. I am not able to manually look the screen. I have also tried to have only one of them installed, but I have not managed to solve the issue. 

I would like to provide more debug information, but I have no Idea how. 

Any idea for a solution or workaround?

**Comment by lestcape** [comment] 2015-01-01 21:33
Try to disable the auto hide option of the panels, and disable also the animation startup on the settings and see if this help...

**Comment by daschuer** [comment] 2015-01-03 22:54
Autohide is disabled. Changing the animation setting do not effect the issue. 

I have noticed the following on a second machine, where a user menu is installed: 
On this machine I am able to manually enable the screen lock, from the app menu, the cinnamon-screensaver is enabled. I can log in again and the panels are still there. From the user menu the gnome-screensaver is activated, I can log in, but the panels are gone. 

What could be the reason that manual screen lock is working on this machine, but not on the other?

**Comment by lestcape** [comment] 2015-01-04 01:16
I really don't know what occurs. What i know is that this can not be occurs on the cinnamon session any more. See:
https://github.com/linuxmint/Cinnamon/issues/2466

I can not reproduce the problem...

**Comment by daschuer** [comment] 2015-01-04 01:44
.. at least it can occur on two of my systems ...

If I read it correct, https://github.com/linuxmint/Cinnamon/issues/2466 is finally fixed in Cinnamon-session 2.4.2 
I am using cinnamon-session 2.4.2ubuntu1 so I should have the blacklist entry. 

ps -A | grep indicator- 

has no output.

**Comment by tbl0605** [comment] 2015-02-13 20:32
Hi,
just to tell, that I exactly have the same problem (using Ubuntu Trusty and Cinnamon 2.4.5ubunt2) ! And sadly no clue what's the problem :(

**Comment by aungthurhahein** [comment] 2015-03-04 12:13
have the same exact problem with same environment. Ubuntu 14.04 LTS with cinnamon 2.4.6. At least wants a quick fix to deal with this issue. "cinnamon --replace" is not working and no idea how to deal with it.

**Comment by lestcape** [comment] 2015-03-04 12:21
The title was wrong so i don't understand what happend the first time...
@aungthurhahein and all can post the xsession-errors? home/USER/.xsession-errors

**Comment by mtwebster** [comment] 2015-03-04 12:28
Last I checked, gnome-screensaver had started ignoring our blacklisting of it - is having it installed a common factor for everyone?  Is it running when this occurs?  To be honest I don't recall if I figured out what was starting it - this could have been before we blacklisted all the indicator- apps ( and one of those might have been starting it) so this could have no bearing whatsoever.

**Comment by aungthurhahein** [comment] 2015-03-04 12:33
I extracted some error message from .xsession-errors. Apart form these repeated error msg,the rest are font-config warning.

    ** (cinnamon-settings-daemon:2849): WARNING **: Failed to get session for pid: GDBus.Error:org.freedesktop.ConsoleKit.Manager.GeneralError: Unable to lookup session information for process '2849'

    ** (cinnamon-settings-daemon:2849): WARNING **: Failed to get session for pid: GDBus.Error:org.freedesktop.ConsoleKit.Manager.GeneralError: Unable to lookup session information for process '2849'

    ** (cinnamon-settings-daemon:2849): WARNING **: Failed to get session for pid: GDBus.Error:org.freedesktop.ConsoleKit.Manager.GeneralError: Unable to lookup session information for process '2849'

    ** (cinnamon-launcher:2920): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-jojZDCBWqv: Connection refused

    ** (cinnamon:2933): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-jojZDCBWqv: Connection refused
    sudo: no tty present and no askpass program specified

    ** (nm-applet:2953): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-jojZDCBWqv: Connection refused

    ** (polkit-gnome-authentication-agent-1:2951): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-jojZDCBWqv: Connection refused

**Comment by lestcape** [comment] 2015-03-04 12:37
@mtwebster but if @aungthurhahein has ubuntu 14.04 and use my repo he has this patch and is working ok... What is true is that ligthdm is broken for cinnamon session... i use mdm instead.... This is on the repo description and also in web8... thats is the Consolekit errors...

**Comment by lestcape** [comment] 2015-03-04 13:32
I will recommend switch to mdm, but is possible that this can not resolve the problem... Just at less, the usb device can be mounted automatically when they are connected, and with lucky also this problem will be the cause. I have not another idea.

**Comment by aungthurhahein** [comment] 2015-03-05 06:01
another input is that my work machine have same environment setup(ubuntu 14.04 with cinnamon 2.4.6) but there is no such problem like that. I think the problem is not occured at every Ubuntu distros, which replaced DE with cinnamon.

**Comment by lestcape** [comment] 2015-03-05 13:17
@aungthurhahein you are sure that you take the correct xsession error? what is need is to see the error after return for the screen saver (and the problem occurs), if you take the xsession without the problem no one can see anything...

**Comment by aungthurhahein** [comment] 2015-03-06 14:41
@lestcape yes.I looked at error file after I login from screen saver.

**Comment by davidchua** [comment] 2015-03-08 04:06
I'm on Ubuntu 14.04 (Ubuntu GNOME) and also on @lestcape's repo.

I'm also getting the same issue after recovering from screensaver lockout.

My bottom panels are gone and the only way for me to fix this is to do a full on restart. 

Would appreciate if there was a way to reload the panels without having to be forced to restart.

**Comment by leigh123linux** [comment] 2015-03-08 05:25
@lestcape 

I wouldn't say lightdm is broken with cinnamon-session, it's been working fine here for years.

**Comment by lestcape** [comment] 2015-03-08 05:49
@leigh123linux after 2.0 cinnamon has its own name, when this occurs i suppose that also cause some incompatibilities with lightdm. The problem is that, this only occurs using upstart (ubuntu 14.04, not fedora)... Thats will not be resolved on lightdm, because upstart is deprecated. You use consolekit on fedora for something?

https://github.com/linuxmint/cinnamon-settings-daemon/issues/70

**Comment by lestcape** [comment] 2015-03-08 06:34
I really can not be sure if fix the lightdm problem, could also solve this problem, but if the session, not start properly i will  expect that could happen several things, this could be one of them. I don't have this problem, but if some one with the problem want to test the swap to mdm and see what happen would be good.

**Comment by leigh123linux** [comment] 2015-03-08 09:01
@lestcape 

Fedora uses systemd only since F17

**Comment by lestcape** [comment] 2015-03-08 21:34
@leigh123linux but i detected the problem after the change of the cinnamon session name, thats is relative new, Anyway i try to avoid this point, but if a problem exist and how mint have a dm, the cinnamon devs need to have an idea of what ocurs. I think if an explicit patch to cinnamon is needed on mdm this will not be ported to lightdm if cinnamon devs not reported this...

You can see that the problem exist and not also to me and for @aungthurhahein here:
http://forums.linuxmint.com/viewtopic.php?f=190&t=158774

You also can see that mdm have explicit call to cinnamon features (this not occurs on lightdm, ofcourse and could be relate to this issue):
https://github.com/linuxmint/mdm/commit/30cd39d28a9db34abe4b30d502850180cfa72fc3

Anyway here there are a problem, do you have an idea to fix it?

**Comment by davidchua** [comment] 2015-04-04 00:59
I'm not sure how relevant is this but I've switched from LDM to MDM 1.6.0 on my Ubuntu 14.04 (Cinnamon 2.4.6) and the panels still disappear after coming out of lock screen.

**Comment by lestcape** [comment] 2015-04-04 02:36
@davidchua i think is relevant...

**Comment by tbl0605** [comment] 2015-04-04 09:40
After reading what davidchua posted about the screensaver lockout issue (1 month ago), I did following:
sudo chmod a-x /usr/bin/gnome-screensaver

to avoid that the gnome screensaver get launched on top of the cinnamon screensaver.
It's hacky but in my case it works, panels don't disappear anymore.
Only (big) drawback, is that (in very rare case) I don't have any screensaver showing after screen wake-up!
So that's just a bad workaround for now...

**Comment by lestcape** [comment] 2015-04-04 12:57
@tbl0605  this mean that you have the gnome-screensaver process working somehow before remove the execution permission? The only way will be that other application is starting the process, the cinnamon session can not do that.

**Comment by tbl0605** [comment] 2015-04-04 16:18
@lestcape : yes you're probably right. But as it was pretty random, I never found what launched the gnome-screensaver process! It really seems that it was launched each time exactly at same time than the gnome-screensaver process :S Sorry if I cannot help much more...

**Comment by lestcape** [comment] 2015-04-04 20:53
@tbl0605 https://github.com/linuxmint/cinnamon-screensaver/issues/65

**Comment by tbl0605** [comment] 2015-04-04 21:14
@lestcape : thank you! So in my case it's a different bug, but with same symptoms as this bug... Is there something to do ? :S

**Comment by lestcape** [comment] 2015-04-04 23:34
@tbl0605  Is not a thing that we can do, cinnamon devs also speak of return of use to gnome-screensaver. I think that there are a lot of work to do if they try to avoid all possible conflicts and also there are a lot of work if they decide be compatible with gnome-screensaver instead of cinnamon-screensaver, because of the compatibilities with cinnamon, that i think is the principal reason of the usage of the fork... Thats is a decision that they need to take. Another could be not do anything, because at last this only occurs when you have gnome-screensaver installed and you can uninstall it if what you want is use cinnamon only, but this is my opinion.

**Comment by dalcde** [comment] 2015-04-04 23:55
Unfortunately gnome screensaver no longer exists: https://git.gnome.org/browse/gnome-screensaver/log/

It was ditched after GNOME 3.6 and only a few updates (16 commits since Oct 2012, to be precise) has been provided since then, mostly tiny fixes and translation updates

**Comment by lestcape** [comment] 2015-04-05 00:09
@dalcde thats is really worse... Thanks for the reference and the explanation... then, personally to me the return is not a good option.

**Comment by lestcape** [comment] 2015-04-05 00:40
@tbl0605 rename the gnome-screensaver and create a symbolic link to the cinnamon-screensaver, this need to be a better patch than remove the execution permission. Of Course this is not a solution, and can create another types of problems on other sessions. You need to test what happens on your specific case... the inverse procedure could also work, but i think is worse for cinnamon session, of course.

**Comment by leigh123linux** [comment] 2015-04-05 05:01
Most distro's removed gnome-screensaver from the repo's because it's of no use to gnome-shell, ubuntu should have renamed it to unity-screensaver IMO (how does ubuntu stop gnome-screensaver running in gnome-shell?)!
Does debian packaging allow for obsoletes and provides, if so it could be used to purge it?

https://fedoraproject.org/wiki/Packaging:Guidelines#Renaming.2FReplacing_Existing_Packages

**Comment by tbl0605** [comment] 2015-04-05 12:35
@lestcape ok I renamed gnome-screensaver and created a link to cinnamon-screensaver, that's a better workaround than mine. Hopefully with no drawbacks ;)

**Comment by DaFri-Nochiterov** [comment] 2016-03-12 02:52
Still not fixed? :neutral_face:

**Comment by leigh123linux** [comment] 2016-03-12 06:32
@DaFri-Nochiterov 

It's not cinnamon that is broken so go and bitch at gnome-screensaver at launchpad bugzilla instead!

**Comment by mtwebster** [comment] 2016-03-12 19:14
Actually should be fixed in cinnamon 2.8.7

https://github.com/linuxmint/Cinnamon/commit/5c5d191d8e0bb30a3dd529c

**Comment by mtwebster** [comment] 2016-03-12 19:15
Removing gnome-screensaver will also fix, as before

**Closed by mtwebster** 2016-03-12 19:14 UTC
Labels: BUG

**Comment by DaFri-Nochiterov** [comment] 2016-03-13 08:35
OK. I removed it and all fixed.

Thanks you :blush:

**Comment by vladimir-didenko** [comment] 2016-03-21 07:39
> Actually should be fixed in cinnamon 2.8.7

Actually it is first version when I see reported problem on my system. At least with Gnome 3.19 libs (not able to reproduce with 3.18). Should I create separate story?

**Comment by vladimir-didenko** [comment] 2016-03-21 07:44
@leigh123linux 
>It's not cinnamon that is broken so go and bitch at gnome-screensaver at launchpad bugzilla instead!

I have no gnome-screensaver installed but see issue with 2.8.7

**Comment by vladimir-didenko** [comment] 2016-03-23 08:10
>Actually it is first version when I see reported problem on my system. At least with Gnome 3.19 libs

Can't reproduce with Gnome 3.20. Hope it was Gnome bug.

**Comment by pashdown** [comment] 2016-04-27 15:11
Removing gnome-screensaver fixes the problem, but for some reason the "Screen locker" applet no longer functions after doing so.  Weirdly enough, the "Lock screen" function under the Menu works just fine.

**Comment by vranki** [comment] 2016-07-21 16:03
Looks like this issue is back - got 2 lock screens, and after those the panel is gone. 
Cinnamon 2.8.6 on Ubuntu 16.04. 

I removed gnome-screensaver now, but it's just a workaround. This should be handled somehow in cinnamon, regular users can't be expected to do that.

**Comment by mtwebster** [comment] 2016-07-21 17:38
Update to 2.8.8 or 3.0.x

**Comment by ryanrca** [comment] 2016-11-07 19:16
I'm reproducing this with Kbuntu 16.04.

To get the panel back, I have to do this:
```
cd ~/.config
mv plasma-org.kde.plasma.desktop-appletsrc plasma-org.kde.plasma.desktop-appletsrc.bak
kbuildsycoca5 && kquitapp plasmashell && kstart plasmashell
```

Which sucks because my destop setting reset.

I am not running any screensaver, just screen locking.

**Comment by JosephMcc** [comment] 2016-11-07 19:43
From reports in the past KDE and Cinnamon do not play well together.

**Comment by imbezol** [comment] 2017-09-18 19:55
I've found just a "kstart plasmashell" is sufficient to get the desktop, icons, and panel back.

**Comment by stolk** [comment] 2017-11-26 02:48
I am on 16.04.3 LTS and this happens to me.
cinnamon version is 2.8.6-1ubuntu1

`cinnamon --restart` does not help.

But as root: `/etc/init.d/lightdm restart` does, but that does mean losing your apps.

**Comment by ontherunvaro** [comment] 2018-03-13 10:57
For me it was an issue of duplicity between `cinnamon-screensaver` and `gnome-screensaver`. Just uninstalling `gnome-screensaver` with `apt` was enough to work around the issue.

This was an Ubuntu 16.04 installation, with Cinnamon 2.8.7.

**Comment by wu-lee** [comment] 2018-03-16 21:39
I've also been seeing this.  Panel disappears after waking laptop from sleep, and an odd second screen-lock with a triangle mozaic pattern is there instead of my usual.  I have gnome-screensaver installed, I infer it's that. I've uninstalled, let's see if that banishes the problem.  (I am a refugee from KDE, if that helps, in that KDE is still installed alongside Cinnamon.)

I'm running Ubuntu 16.04 LTS.

**Comment by prinsherbert** [comment] 2018-03-28 11:54
To upgrade cinnamon to a version 2.8.6, add the [cinnamon ppa](https://launchpad.net/~embrosyn/+archive/ubuntu/cinnamon) and upgrade:

    sudo add-apt-repository ppa:embrosyn/cinnamon
    sudo apt-get update
    sudo apt-get upgrade
