### ISSUE TITLE
[Cinnamon or LMDE2?] Layout problem on LMDE2+Cinnamon 3.0.1

### ISSUE THREAD

**Issue by kmkom** [linuxmint/Cinnamon#5290] opened 2016-05-11 18:39 UTC
I have two partitions:
A: Mint 17.3 and Cinnamon 2.8.8
B: LMDE2 and Cinnamon 3.0.1.
On both version FF 46.0 is installed.
On A Cinnamon looks fine, but on B I often can see that in Dialogs or even in Firefox the layout is much wider and add useless space around buttons. Look at the Screen shots, Pic1 shows Firefox, the Buttons in the Bookmarks Toolbar are much wider in LMDE than in Mint. And the same happens in other dialogs as well, Pic2 shows this in Settings/Clock-Settings.
One can find that in other dialogs also, but this two example should be sufficient to show the problem.
![pic1](https://cloud.githubusercontent.com/assets/15555865/15192160/4a8ce63a-17b8-11e6-8823-8079c8b21d85.png)
![pic2](https://cloud.githubusercontent.com/assets/15555865/15192165/51397836-17b8-11e6-8ee5-dd43df40d9d9.png)

**Comment by darethehair** [comment] 2016-05-11 18:44
I noticed similar things the other day while using Firefox in the new Cinnamon release i.e. my 'favorites' folders list now takes up more room than it needs to, meaning that some of then were pushed off the right side into the overflow area.  I assumed this was because of a Firefox update, but maybe it is Cinnamon?

**Comment by ledufff** [comment] 2016-05-11 19:16
I've been having this issue before 3.0

**Comment by kmkom** [comment] 2016-05-12 08:30
Here is another example, this time: Synaptic Package Manager.
I'm wondering why this happens? And it "wasted screen size" and partly looks ugly :-(
And darethehair is right, the favorites take up to much space in LMDE2+Cinnamon 3.0.1.
I'm not sure if this already happen in pre 3.0 Cinnamon Versions, it's the first time that i test LMDE2.

![pic3](https://cloud.githubusercontent.com/assets/15555865/15208417/be1e3644-182b-11e6-9dae-397a7cebb9e7.png)

**Comment by lestcape** [comment] 2016-05-16 04:16
I think this is not relate with cinnamon, but maybe with a change in gtk.

**Comment by JosephMcc** [comment] 2016-05-16 07:05
Some of these probably need to be fixed in Cinnamon, like the dialogs. The issue with the firefox bookmarks is caused by firefox switching to gtk3. It can be controlled by the gtk theme. It's already fixed in Mint-X for Mint18. I'll have to see if the fixes can get pushed for LMDE and Mint 17.

**Comment by JosephMcc** [comment] 2016-08-25 18:32
I'm going to close this because the root cause of your issues are from several different things. The only one Cinnamon related is the date/time settings and we know about that one. I've tried a bit to track that down in the past but had no luck.

**Closed by JosephMcc** 2016-08-25 18:32 UTC
