### ISSUE TITLE
Cinnamon maybe removed from Debian testing because of mozjs

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/cinnamon#9603] opened 2020-09-30 06:30 UTC
Hello dear Mint Team,

Debian is considering removing cinnamon from testing as it depends on the orphaned package "mozjs52". Apparently an update to version "libmozjs78" and "gjs" is desired. I would be very disappointed if Cinnamon was removed from Debian because it is a great desktop. Is an update of the packages planned or is there a cooperation with the Debian team? 
https://www.preining.info/blog/2020/09/cinnamon-for-debian-imminent-removal-from-testing/

Best regards, Jakob

**Comment by leigh123linux** [comment] 2020-09-30 09:51
Closed, duplicate of https://github.com/linuxmint/cjs/issues/80

**Closed by leigh123linux** 2020-09-30 09:51 UTC
