### ISSUE TITLE
[sound applet] missing output devices

### ISSUE THREAD

**Issue by gregsheremeta** [linuxmint/Cinnamon#2888] opened 2014-02-13 18:22 UTC
In the Output device submenu of the sound applet, only two devices show up, but I have 3. When I click the Sound Settings submenu, I can then choose from all 3.

For some reason, get_sinks() must only return the two devices. Maybe it's that my digital and analog outputs are both "Built-in Audio"?

cinnamon.x86_64  2.0.14-4.fc20
Fedora 20
greg@dauntless:~$ yum list installed alsa*
Loaded plugins: langpacks, refresh-packagekit
Installed Packages
alsa-firmware.noarch                                                 1.0.27-2.fc20                                         installed
alsa-lib.x86_64                                                      1.0.27.2-2.fc20                                       installed
alsa-plugins-pulseaudio.x86_64                                       1.0.27-2.fc20                                         installed
alsa-tools-firmware.x86_64                                           1.0.27-3.fc20                                         installed
alsa-utils.x86_64                                                    1.0.27.2-3.fc20                                       installed
greg@dauntless:~$ yum list installed pulseaudio*
Loaded plugins: langpacks, refresh-packagekit
Installed Packages
pulseaudio.x86_64                                                    4.0-9.gitf81e3.fc20                                   installed
pulseaudio-gdm-hooks.x86_64                                          4.0-9.gitf81e3.fc20                                   installed
pulseaudio-libs.x86_64                                               4.0-9.gitf81e3.fc20                                   installed
pulseaudio-libs-glib2.x86_64                                         4.0-9.gitf81e3.fc20                                   installed
pulseaudio-module-bluetooth.x86_64                                   4.0-9.gitf81e3.fc20                                   installed
pulseaudio-module-x11.x86_64                                         4.0-9.gitf81e3.fc20                                   installed
pulseaudio-utils.x86_64                                              4.0-9.gitf81e3.fc20                                   installed

greg@dauntless:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC892 Analog [ALC892 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 1: ALC892 Digital [ALC892 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

![workspace 1_008](https://f.cloud.github.com/assets/2248293/2163108/c68fd994-94da-11e3-862b-f120f77648a0.png)

![selection_007](https://f.cloud.github.com/assets/2248293/2163109/ca3d1a2a-94da-11e3-9f91-9ff655f9933d.png)

**Comment by iraklisg** [comment] 2015-01-08 16:41
The problem is still present in Linux Mint 17.1. Whenever I am connecting an external TV monitor via an hdmi cable, the hdmi sound option is not listed in sound applet/output device.... I am able to switch among the preferred sound devices only through Settings --> Sound (which is really annoying sometimes)

**Comment by clefebvre** [comment] 2015-03-07 12:25
This should help https://github.com/linuxmint/Cinnamon/commit/47c9223a5dbc276e9b598c3295582415aa019ada

It brings the Cinnamon GVC lib on par with the one used by cinnamon-control-center. That doesn't mean it fixes the issues you mentioned (I think it might help with detecting devices connections/removals in the applet but it certainly doesn't make the applet differentiate between Built-In Audio profiles for instance).

Anyway, give it a try if you get a chance.

**Comment by mtwebster** [comment] 2015-04-06 14:24
fixed as of 05f65cf

**Closed by mtwebster** 2015-04-06 14:24 UTC

**Comment by mlopezcoria** [comment] 2017-08-09 23:43
I've got a similar issue with Linux Mint 18.2 Cinnamon 64-bit (https://gist.github.com/anonymous/ae19404aa8097399f521ab007f5d6ac3)
Normally I can see my output analog audio adapter, that's the one I use. But when I plug my headphones into the frontal panel it disappears from the sound settings dialog, the only device that becomes available is HDMI/Display Port Built-in Audio and the speakers doesn't sound.

![sound_019](https://user-images.githubusercontent.com/15494802/29148398-6b301a14-7d43-11e7-8170-169e4b459042.png)
