### ISSUE TITLE
Cinnamon Menu loses all software

### ISSUE THREAD

**Issue by Infinatum** [linuxmint/Cinnamon#5484] opened 2016-07-25 09:56 UTC
I have found a problem with the Cinnamon menu applet.

**What Happened** 

With a clean install with Linux mint 18, I copied my home directory, so that I would have all my files after the update. 
 
After the update I went into “Menu Edit”  in the menu applet. After trying to untick some of the programs under the wine menu the program became unresponsive. When I closed it I could not open “Menu Edit”. As well as this all of the programs in the menu where gone. 

After resetting the applet to the default state and importing my previous menu the only thing that came back were the places and recent files. The same thing happened with the quick launcher.
The only way I could run programs was to use the terminal.  

**How I Fixed the Problem**

by renaming the “.config” directory to old.config then restarting the system. 

**What I Think the Issue is**

I think the problem is that since wine is no longer installed on this computer the old config file conflicted with the new one causing it to crash and corrupt the file which has all the list of software installed. 

The reason for this is that after fixing the issue the wine section is empty and all of the things which where in wine are now in other

![mint menu](https://cloud.githubusercontent.com/assets/13417797/17097613/630eca2e-5256-11e6-97cb-e51b33cfe12c.png)

**Comment by xenopeek** [comment] 2016-08-24 08:53
Per-user menu entries are found in the directory .local/share/applications/ in your home directory. You can manually delete cruft from there.

I think this will be very hard to reproduce.

**Comment by JosephMcc** [comment] 2016-08-24 09:45
This would be the downside of moving your home directory between installs. I'm going to close this because as @xenopeek said it is hard, if not almost impossible, to replicate the exact user setup and I'm not sure it's even realistic to try and deal with every little corner case that could pop up from a user doing this.

**Closed by JosephMcc** 2016-08-24 09:45 UTC
