### ISSUE TITLE
Bug report: Cannot find all folders from home folder via panel starter

### ISSUE THREAD

**Issue by jepster** [linuxmint/Cinnamon#6573] opened 2017-05-29 12:43 UTC
In cinnamon-settings->privacy make sure recents are enabled and in the settings for the menu, make sure show bookmarks and places is enabled. Go to the Cinnamon menu applet settings window and enable the option called Enable filesystem path entry in search box. 

It will allow you to search files from the search entry on the menu applet - **but** - it does not. It finds only **a few folders** from my home folder. Not **all** folders are being found. E.g. the "images" folder is being found, the document folder is not found.

See the attached screenshots below (german language, but you will understand it by the description above):
![cf7a25d2-4247-11e7-9311-b8c4146aba72](https://cloud.githubusercontent.com/assets/628434/26550204/e3ff3fe2-447c-11e7-85c9-4e37d3a09be4.png)
![cf753478-4247-11e7-9873-25dc6c4bf05d](https://cloud.githubusercontent.com/assets/628434/26550205/e405d12c-447c-11e7-82ef-058dc27d9fc6.png)
![b7f48baa-4247-11e7-97fe-a07f0d5c1cf2](https://cloud.githubusercontent.com/assets/628434/26550208/e63d6072-447c-11e7-90d8-a45d61a576b3.png)

**Comment by NikoKrause** [comment] 2017-06-04 21:26
Dateisystempfad erfordert normalerweise den ganzen Pfad, z.B. `/home/jepster/Dokumente`.

Wird "Dokumente" angezeigt in der Kategorie "Orte"?

Welche Cinnamon Version benutzt du?

**Comment by Cos-mo** [comment] 2017-06-16 11:43
I cannot reproduce the given example. Tested with Mint 17.3 and 18.2 beta, both 64 bit and both with German locale.

The folders Bilder (pictures), Schreibtisch (Desktop), Dokumente (Documents), Downloads and Videos show as expected, if I enter the respective term into the search box (without path). Only Öffentlich (Public) and Vorlagen (template) do not appear.

I think that this is related with the fact, whether there is a bookmark set in Nemo or not. Even a folder on a separate internal partition, where I had set a bookmark for, gets shown, if I enter the name (without path) into the menu search box. So check, if Dokumente is missing in your Nemo bookmarks.

If there is no bookmark set the path must be given in the search box. Something like ~/path/to/folder/inside/your/home should work.

**Comment by NikoKrause** [comment] 2017-06-16 12:19
This works for me as expected as well in LM 18.1
As Cos-mo explained it very well, this can be closed imo.

**Comment by NikoKrause** [comment] 2017-06-16 17:21
@jepster Read my first post and provide more info

**Comment by jepster** [comment] 2017-06-16 18:29
Aye, aye Sir! 

It's 18.1. I am currently on a trip, so I cannot prove if bookmarks will be found via search. However, if it is by design, that only bookmarks will be found, then things are explained for me. The proof of your systems is enough here.

But again: this is poor functionality compared to Windows 10 and OSX "starter search" functionality. From my point of view, there should be an issue created for this lack of functionality. What do you think?

**Comment by JosephMcc** [comment] 2017-06-16 18:36
Ok. I'm closing this. If you would like to request better search features, we already have open feature requests you can add more info to.

**Closed by JosephMcc** 2017-06-16 18:36 UTC

**Comment by Cos-mo** [comment] 2017-06-16 20:19
@jepster 
You did read, that the option you marked is named to support the "Dateisystempfad" (English: File system path), didn't you? So yes, if the path is needed, it works as designed.

**Comment by jepster** [comment] 2017-06-16 21:00
@Cos-mo: The full path way is totally not useful. I would type such in the terminal or files explorer (nemo). I miss a search index, which is related to the start search. However, if this is by the design, then there is no bug - but the design is bad.

**Comment by Cos-mo** [comment] 2017-06-16 21:11
@jepster 
If this feature is useful, is discussable. But this is not a bug, as you wrote in the title.
