### ISSUE TITLE
Power Button causes no action, logind fail

### ISSUE THREAD

**Issue by calebmillerkb3** [linuxmint/cinnamon#5250] opened 2016-04-27 16:01 UTC
Linux 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 17.3 Rosa 64-bit, Cinnamon
Thinkpad T420

When pressing the power button, no shutdown action (menu or otherwise) is taken even though an appropriate ACPI event is triggered. This is due to /etc/acpi/powerbtn.sh exiting due to finding a PID for logind (line 11). The intended function is for logind to handle the shutdown requests if it is running.

I have fixed the issue on my computer by following the instructions at https://forums.linuxmint.com/viewtopic.php?t=197339#p1024204 ; namely, in terminal:

``` bash
gsettings set org.cinnamon.desktop.session settings-daemon-uses-logind true
gsettings set org.cinnamon.desktop.session session-manager-uses-logind true
gsettings set org.cinnamon.desktop.session screensaver-uses-logind false
```

After performing these commands and rebooting, the power button performs as expected (to the preferences set in power management gui).

**Comment by dandv** [comment] 2016-08-10 18:03
I've just installed Mint 18 Cinnamon and wanted to suspend my Dell E7450 laptop by pressing the power button, as I do in Ubuntu.

Nothing happened.

**Comment by JosephMcc** [comment] 2016-08-10 19:47
@dandv did you set it to in System Settings ->Power Management?

**Comment by dandv** [comment] 2016-08-11 04:42
@JosephMcc: not at all. However, the `Suspend - Hibernate - Restart - Cancel - Shutdown` dialog did appear after I stood by the laptop by closing the lid, resumed, and pressed the power button.

I checked the option now and it's set to "Ask", but I had never visited that dialog before. This bug must be caused by some uninitialized setting, since I had just installed Mint.

**Comment by Vahan86** [comment] 2019-11-26 19:49
@calebmillerkb3 , is this still an issue for you in Cinnamon 4.2?

**Comment by calebmillerkb3** [comment] 2019-11-26 20:35
Cannot confirm resolution, no longer have affected laptop

**Comment by Vahan86** [comment] 2019-11-28 18:31
@calebmillerkb3, thanks for your reply.

@icarter09, can we close the issue?

**Comment by icarter09** [comment] 2019-11-28 18:56
@Vahan86 i'll test this out on my laptop

**Comment by icarter09** [comment] 2019-12-01 04:16
Linux Mint 19.2
Cinnamon 4.2.4

Was able to reproduce this issue. Steps taken were:
 1. Verified that it was set to "Ask" in the Power Management settings when the power button is pressed.
 2. Held down power button.
 3. No Session dialog with Shutdown Options was presented. Laptop instead shutdown.

Tried this several times with the same results.

**Comment by smurphos** [comment] 2019-12-01 08:51
> 2. Held down power button.

Surely that's expected behaviour? 

Holding / long press of the power button is a forced power-down on most hardware.

A short press of the power-button gives me the session dialogue without fail.

**Comment by icarter09** [comment] 2019-12-01 14:40
@smurphos great point and you are correct. A short press did give me the same result as you. I have grown so used to pressing and holding down the power button for a given computer over the years that I never do a short press. Thanks.

**Closed by icarter09** 2019-12-01 14:40 UTC
Labels: BUG, BUG REPRODUCED
