### ISSUE TITLE
[BUG, probably] Kolourpaint in Cinnamon freezes when copying the color code

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#11158] opened 2022-09-08 17:31 UTC
```
Arch Linux, Cinnamon 5.4.9, GTX 1660 Ti, nvidia-dkms 515.57
There are no logs available
 ```

### Issue
Kolourpaint in Cinnamon freezes when copying the color code.
Please read "Other information" too.

### Steps to reproduce
1. Open Kolourpaint.
2. Double click on the color square in the bottom left corner to open the color chooser and click "another color".
3. In the newly open dialog window you'll see the HEX code for the current color. Double click on that code to highlight it, then right click on it and select "copy". 
4. At that point Kolourpaint freezes and will eventually show a dialog offering a forced quit.

### Expected behaviour
Kolourpaint shouldn't be freezing when copying the code.

### Other information
I'm aware Kolourpaint is not a Cinnamon program, it's a KDE program. However, this problem appears to be happening only when Kolourpaint is used in desktops such as Cinnamon - GNOME, MATE, XFCE, Deepin, anything that ISN'T KDE. The program works fine in its own DE, so I'm guessing the problem must be caused by the desktop environment somehow.
I reported this problem to KDE 5 months ago but it still hasn't been fixed and given their history with bugs, I doubt they will ever fix it, so I thought to report it here as well, just in case I'm right in my assumption.

Unfortunately there are no logs that I could provide. Running Kolourpaint through terminal and causing it to freeze shows nothing in terminal.

**Comment by mtwebster** [comment] 2022-09-08 17:40
Maybe I'm not doing it correctly - 
I double-click this:
![image](https://user-images.githubusercontent.com/262776/189189541-7fad5de7-f9c6-44ba-9ff7-e3d34437db61.png)
it brings up this:
![image](https://user-images.githubusercontent.com/262776/189189628-bf2c0976-cb50-443e-9c03-0210f3e630f6.png)
If I then double-click the #000000, right-click and copy, it should freeze?  It works ok here. If I'm doing it wrong let me know.

Do you have any sort of clipboard managers, applets, etc... installed?

**Comment by leigh123linux** [comment] 2022-09-08 18:51
@mtwebster  It freezes here with recent  kolourpaint-22.04.3

![image](https://user-images.githubusercontent.com/1299302/189202524-0bce6db3-4a05-4830-9c1a-227f52fc5a6a.png)

**Comment by leigh123linux** [comment] 2022-09-08 18:56
I'm +1 in favour of closing this as the app fails in every DE.
It's clearly the app that is faulty, there is no crash log or error and I know nothing about debugging kde.

**Comment by leigh123linux** [comment] 2022-09-08 19:32
There is another report https://bugs.kde.org/show_bug.cgi?id=436078

**Comment by leigh123linux** [comment] 2022-09-08 19:52
@mtwebster  your colour chooser appear to be kcolorchooser


Do you recognize this picker? 

![image](https://user-images.githubusercontent.com/1299302/189212026-92df38ba-9aa9-4f38-92e1-1ea9e552faa5.png)

It's similar to the gtk chooser

https://lazka.github.io/pgi-docs/Gtk-3.0/classes/ColorChooserDialog.html

**Comment by rado84-github** [comment] 2022-09-09 08:03
> I'm +1 in favour of closing this as the app fails in every DE. It's clearly the app that is faulty, there is no crash log or error and I know nothing about debugging kde.

I used to have a dual boot with another Arch instance with KDE. The app didn't crash when used in KDE. But in KDE the app comes with its native KDE dialog (KColorChooser). Coming to think of it right now, maybe the problem is caused by GTK? Because these crashes seem to happen only when the dialog is GTK style.

@mtwebster , you're seeing the wrong dialog because you haven't chosen GTK3 dialogs in qt5ct. Open qt5ct and click on the dropdown menu that reads "Standard dialogs". Choose GTK3 and apply the setting. Then double click on the color square as I wrote above. Then copying the HEX color will make the program freeze.

**Comment by mtwebster** [comment] 2022-09-09 14:28
Ok, I can reproduce it if I change the setting in qt5 settings (though actually it says gtk2 - does yours really have gtk3 listed?).

I can also reproduce it in the flatpak version.

This could still potentially be an app/qt5 bug or x11 - it's more clipboard-related than color picker I think. I'm going to close this, however, since it isn't Cinnamon related.


trace of the hung thread:

```
Thread 1 (Thread 0x7ffff1cb19c0 (LWP 233048) "kolourpaint"):
#0  __futex_abstimed_wait_common64 (private=1663924592, cancel=true, abstime=0x7fffffffc770, op=137, expected=0, futex_word=0x5555556b4d14) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=1663924592, abstime=0x7fffffffc770, clockid=124, expected=0, futex_word=0x5555556b4d14) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x5555556b4d14, expected=expected@entry=0, clockid=clockid@entry=1, abstime=abstime@entry=0x7fffffffc770, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff5f19f1b in __pthread_cond_wait_common (abstime=0x7fffffffc770, clockid=1, mutex=0x5555556b4cc0, cond=0x5555556b4ce8) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_timedwait64 (cond=0x5555556b4ce8, mutex=0x5555556b4cc0, abstime=0x7fffffffc770) at ./nptl/pthread_cond_wait.c:652
#5  0x00007ffff6493c7c in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff6493d7b in QWaitCondition::wait(QMutex*, unsigned long) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff1619e64 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#8  0x00007ffff15ee883 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#9  0x00007ffff15eef6d in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#10 0x00007ffff15f09f8 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#11 0x00007ffff6b2c053 in QInternalMimeData::formats() const () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#12 0x00007ffff15f068d in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#13 0x00007ffff6b2c22c in QInternalMimeData::hasFormat(QString const&) const () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#14 0x00007ffff66a0dd0 in QMimeData::hasUrls() const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff66a0e84 in QMimeData::hasText() const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00005555555dd8d3 in  ()
#17 0x00007ffff66b2783 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff6b1c785 in QClipboard::emitChanged(QClipboard::Mode) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#19 0x00007ffff15f2be4 in QXcbConnection::handleXcbEvent(xcb_generic_event_t*) () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#20 0x00007ffff15f4116 in QXcbConnection::processXcbEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#21 0x00007ffff161ad67 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#22 0x00007ffff4c2dd1b in g_main_dispatch (context=0x7fffec005010) at ../../../glib/gmain.c:3417
#23 g_main_context_dispatch (context=0x7fffec005010) at ../../../glib/gmain.c:4135
#24 0x00007ffff4c826f8 in g_main_context_iterate.constprop.0 (context=0x7fffec005010, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4211
#25 0x00007ffff4c2d293 in g_main_loop_run (loop=0x555555e481e0) at ../../../glib/gmain.c:4411
#26 0x00007ffff07a8547 in gtk_dialog_run () at /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#27 0x00007ffff74283b1 in QDialog::exec() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x0000555555620b89 in  ()
#29 0x00007ffff725ae79 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff7308422 in QFrame::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff7217713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff721f364 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007ffff667ae2a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff721de47 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff7273d40 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ffff7276fd5 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff7217713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff667ae2a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007ffff6b0e4b0 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#40 0x00007ffff6ae3a2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#41 0x00007ffff161ad6e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#42 0x00007ffff4c2dd1b in g_main_dispatch (context=0x7fffec005010) at ../../../glib/gmain.c:3417
#43 g_main_context_dispatch (context=0x7fffec005010) at ../../../glib/gmain.c:4135
#44 0x00007ffff4c826f8 in g_main_context_iterate.constprop.0 (context=context@entry=0x7fffec005010, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4211
#45 0x00007ffff4c2b3c3 in g_main_context_iteration (context=0x7fffec005010, may_block=1) at ../../../glib/gmain.c:4276
#46 0x00007ffff66d40a8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007ffff667974b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#48 0x00007ffff6681ce4 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#49 0x000055555559c6e6 in  ()
#50 0x00007ffff5eafd90 in __libc_start_call_main (main=main@entry=0x55555559bb90, argc=argc@entry=1, argv=argv@entry=0x7fffffffdca8) at ../sysdeps/nptl/libc_start_call_main.h:58
#51 0x00007ffff5eafe40 in __libc_start_main_impl (main=0x55555559bb90, argc=1, argv=0x7fffffffdca8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdc98) at ../csu/libc-start.c:392
#52 0x000055555559cba5 in  ()
(gdb) q
```

**Closed by mtwebster** 2022-09-09 14:28 UTC
Labels: New
