### ISSUE TITLE
Flatseal does not work properly in Linux Mint 21.2, is not possible to grant "portals" permissions.

### ISSUE THREAD

**Issue by nakamichi-dragon** [linuxmint/cinnamon#11840] opened 2023-08-26 15:11 UTC
### Distribution

Linux Mint 21.2

### Package version

Cinnamon 5.8.4

### Graphics hardware in use

Radeon HD 7750 and others. the problem does not seem to have anything to do with the graphics card

### Frequency

Always

### Bug description

- It is not possible to grant the permissions in the "portals" section of Flatseal, such as the permission to run in the background, and therefore in applications such as Pika Backup or Déjà Dup it is not possible to schedule automatic backups.
- The problem occurs in all installed Flatpak applications in Linux Mint version 21.2.
- In Linux MInt version 21.1 the problem does not exist, you can change the permissions without any problem.

### Steps to reproduce

How to reproduce the error:
1.- Install Linux Mint 21.2
2.- Install Pika Backup, Déjà-Dup or any Flatpak.
3.- Install Flatseal
4.- If you open Flatseal is not possible to modify the "portals" permissions, so it is not possible to schedule automatic backups in Pika Backup or in Deja-dup

### Expected behavior

- If you open Flatseal is not possible to modify the "portals" permissions, so it is not possible to schedule automatic backups in Pika Backup or in Deja-dup
- The problem occurs in all installed Flatpak applications in Linux Mint version 21.2.
- In Linux Mint version 21.1 the problem does not exist, you can change the permissions without any problem.

### Additional information

I have tested it on several pcs
- The problem appears as soon as Linux Mint 21.2 is installed. 
- On Linux Mint 21.1 the problem does not exist
- On PCs where I have upgraded from Linux Mint 21.1 to Linux Mint 21.2 the problem exists.

Thanks

**Comment by mtwebster** [comment] 2023-08-26 18:05
Duplicate of https://github.com/linuxmint/xdg-desktop-portal-xapp/issues/2

**Closed by mtwebster** 2023-08-26 18:05 UTC
