### ISSUE TITLE
Window list overlapping indicators

### ISSUE THREAD

**Issue by NZamp** [linuxmint/Cinnamon#6638] opened 2017-06-21 13:17 UTC
This is happening on Cinnamon 3.4 tested under Linux Mint 18.2 BETA. When the opened windows are more than what could fit in the available space on the taskbar, the window list will expand throughout the panel to the right, thus overlapping the system indicators on the right panel edge. 

A possible solution is that in this case, Cinnamon should automatically split the window list allowing the user to navigate through the whole list with upper/down arrows.

![screenshot from 2017-06-21 16-09-32](https://user-images.githubusercontent.com/25671112/27385848-9bddc576-569c-11e7-97c4-65bffc7f160f.png)

**Comment by leigh123linux** [comment] 2017-06-21 16:40
Duplicate of https://github.com/linuxmint/Cinnamon/issues/4646

**Closed by leigh123linux** 2017-06-21 16:40 UTC
