### ISSUE TITLE
[Feature Request] Linux Mint 18.1 Cinnamon /w Horizontal & Vertical Panels

### ISSUE THREAD

**Issue by gh4snow** [linuxmint/Cinnamon#6133] opened 2016-12-25 13:09 UTC
Linux Mint 18.1 Cinnamon /w Menu on Lower Horizontal Panel, & additional Left Vertical Panel.
Need to be able to place Program Icons on either panel.
If one clicks Menu, selects a program, right clicks & selects "add to panel", then
the icon is added to the lower panel. User should be able to add to any panel.

**Comment by brownsr** [comment] 2016-12-25 15:13
Perhaps the wording 'add to panel' could do with improvement.  It actually adds to the 'panel launchers' applet, which can be placed on any panel.  Just turn on edit mode and drag the 'panel launchers' applet to whichever panel [section] you want.  Adding a new program from the menu via right click will now add into the newly positioned panel launcher.

There's also a drag and drop facility you might want to know about, you can actually drag an application straight out of the menu and drop it on the panel launchers  applet.  Within the panel launchers applet you can drag and drop to adjust positions of the various applications, panel edit does not have to be on to do this.

Recommend closing this issue, other than considering if the right click description can be improved.

**Comment by lestcape** [comment] 2017-01-03 17:46
I dislike the idea of change the description... I see this as a feature an any applet that implemented the "panellauncher" role could react to this action. This is implemented in a generic way in the menu and i like how is implemented: https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L135-L141

This is then not a bug, just a missing understood of the feature **please close this**...

**Closed** 2017-01-03 19:02 UTC
