### ISSUE TITLE
[accessibility] - make screen reader work out of the box

### ISSUE THREAD

**Issue by christophe-g** [linuxmint/cinnamon#11381] opened 2022-12-31 15:13 UTC
```
System:
  Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.5
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy

 ```

### Issue

Orca screen reader does not seem to work out of the box in Linux 21 (incl. 21.1). See https://github.com/linuxmint/cinnamon/issues/11146 for a more detailed report.

### Steps to reproduce
Turn screen reader on in accessibility settings. The sound output is : `this is a dummy module, ... ` . 

### Expected behaviour
Screen reader works 

### Fix

It seems ORCA needs `espeakup` and `speech-dispatcher-espeak` packages to be installed. It would avoid some frustration if those packages were installed by default.

**Comment by leigh123linux** [comment] 2022-12-31 16:15
Duplicate of https://github.com/linuxmint/cinnamon/issues/11146

**Closed by leigh123linux** 2022-12-31 16:15 UTC
Labels: New

**Comment by leigh123linux** [comment] 2022-12-31 16:16
You need to file the issue against orca at ubuntu launchpad bug tracker.

**Comment by christophe-g** [comment] 2022-12-31 17:24
Thanks - will do ; )
