### ISSUE TITLE
show-desktop@cinnamon.org Applet: Preview of Desktop does not restore after Menu opening

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#6261] opened 2017-02-09 15:08 UTC
How to reproduce?

- Configure "Show Desktop" with preview of desktop enabled
- Open any window
- Move mouse cursor to the applet "Show Desktop" > Window gets half-transparent
- Press "Super" on keyboard or any other keyboard-shortcut to open the Cinnamon Menu

Windows remain transparent, but should restore instead.

You can restore it by hovering over the Show Desktop applet.

See also: https://github.com/linuxmint/cinnamon-spices-applets/issues/16

**Comment by leigh123linux** [comment] 2017-02-09 16:31
Your issue looks like a duplicate of https://github.com/linuxmint/Cinnamon/issues/6234

**Comment by Piiit** [comment] 2017-02-09 17:11
@leigh123linux I don't think so. These transparent windows happen to me as well, but they are AFAIK not related to the show-desktop applet. My suspicion is, that this is an event-trigger issue.  That is, the "mouse left event" of the applet is not triggered somehow.

**Comment by JosephMcc** [comment] 2017-02-15 20:45
I can reproduce this.

**Closed** 2017-03-17 11:41 UTC
Labels: BUG REPRODUCED
