### ISSUE TITLE
"Launch in terminal" seems to ignore cinnamon settings

### ISSUE THREAD

**Issue by moonburnt** [linuxmint/cinnamon#10239] opened 2021-07-26 17:03 UTC
```
 * Cinnamon version (cinnamon --version)
Cinnamon 5.0.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 Manjaro Linux
 * 32 or 64 bit
 64 bit
 ```

**Issue**
If you have any other terminal (in my case, urxvt) installed instead of gnome-terminal (e.g gnome terminal isnt installed) and set as default (in both cinnamon settings and gsettings), .desktop files that have `Terminal=true` flag (or "launch in terminal", if we are talking gui representation of this) refuse to start. Simply nothing happens when you try to execute them - regardless if you do that from menu, panel applet or by directly clicking on .local/share/applications item

**Steps to reproduce**
- Install cinnamon normally
- Install urxvt or any other terminal than gnome-terminal
- Uninstall gnome-terminal
- Set urxvt as your default terminal in cinnamon settings manager and with `gsettings set org.cinnamon.desktop.default-applications.terminal exec urxvt`
- Reboot the system and try to launch something like htop from menu
- Nothing will happen, no new entries will appear in .xsession-errors

**Expected behaviour**
.desktop files with `Terminal=true` flag in them should use whatever terminal is set as default, not refuse to launch if gnome-terminal isnt installed

**Comment by forever-and-a-day** [comment] 2021-07-27 07:54
yeah, I've been experiencing this problem too - using tilix :/

**Comment by mtwebster** [comment] 2021-07-28 16:37
Duplicate of https://github.com/linuxmint/nemo/issues/2414

We could theoretically address it ourselves but it would be a lot of code, and the chances of regressions would be huge - we'd prefer to let this get fixed where the problem actually lies. The most reliable workaround would be to create a symlink for your program:
```
ln -s /usr/bin/tilix ~/.local/bin/gnome-terminal
```

If your terminal program has special arguments needed, `.local/bin/gnome-terminal` might perhaps be a small shell script to include those and call `/usr/bin/tilix`.

**Closed by mtwebster** 2021-07-28 16:38 UTC

**Comment by Lurux** [comment] 2021-08-07 11:13
@mtwebster 

> We'd prefer to let this get fixed where the problem actually lies.

Just curious here, where does the problem actually lies ? I guess it is down to the implementation of the .desktop specification used in Cinnamon ? Not sure about this, though.

**Comment by mtwebster** [comment] 2021-08-07 17:00
As discussed in the issue I linked, this needs to be addressed in glib so that all programs that use that library benefit from the fix.

https://gitlab.gnome.org/GNOME/glib/-/issues/338

**Comment by Lurux** [comment] 2021-08-09 09:37
Cool, thanks !
