### ISSUE TITLE
Size of Panel Edit Mode is inconsistent on Vertical panels compared to Horizontal ones

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5584] opened 2016-08-20 19:23 UTC
When Panel Edit Mode is enabled, on Horizontal panels, it's what it's supposed to be, but on Vertical ones, the middle part is too big unlike the top and bottom parts which are either tiny or use the minimum height to squeeze the applets onto, for example:
![screenshot from 2016-08-20 19-22-55](https://cloud.githubusercontent.com/assets/11057934/17833395/8814130a-670b-11e6-8f06-dca11ebe0b96.png)

**Comment by brownsr** [comment] 2016-10-29 19:46
Can't reproduce this in the latest version.  A lot of change has occurred since August when this was reported.  I suggest we close this.

**Comment by feren** [comment] 2016-10-30 09:05
Ok, that was an early build of Vertical Panels

**Comment by NikoKrause** [comment] 2018-02-02 22:35
This seems to be fixed.

**Closed by NikoKrause** 2018-02-02 22:35 UTC
Labels: BUG
