### ISSUE TITLE
Sound applet only shows last app

### ISSUE THREAD

**Issue by rexmadgere** [linuxmint/Cinnamon#5645] opened 2016-09-05 07:39 UTC
Clementine always runs on background and sound applet shows it settings, but when I run video player clementine settings hides and only video settings visible.
![01](https://cloud.githubusercontent.com/assets/9503811/18240516/fcd5128e-7354-11e6-8dcf-0e8313a8bee1.jpg)
![02](https://cloud.githubusercontent.com/assets/9503811/18240515/fcd058e8-7354-11e6-8728-9b013f0a4f8a.jpg)

**Comment by ManIVIctorious** [comment] 2016-09-05 10:17
Duplicate of #4755 

Also linked to #5556

**Comment by JosephMcc** [comment] 2016-09-05 10:26
Thank you very much :)

**Closed by JosephMcc** 2016-09-05 10:26 UTC
Labels: BUG
