### ISSUE TITLE
[Feature Request] Cinnamon notifications should support html markup in titles

### ISSUE THREAD

**Issue by Piiit** [linuxmint/cinnamon#5655] opened 2016-09-07 15:22 UTC
```
notify-send --icon=gtk-add "Test&gt;notification" "This &gt; is the message body http://test.com" -t 10 -u low
```

gives the following notification

![bildschirmfoto vom 2016-09-07 16-48-52](https://cloud.githubusercontent.com/assets/6096063/18317779/626b8256-751f-11e6-9ee6-1fc379aa60b9.png)

`&gt;` is shown correctly in the text field below the title, whereas the title does not transform it.

**Comment by anandrkris** [comment] 2016-09-07 16:33
Duplicate of https://github.com/linuxmint/Cinnamon/issues/2416

**Comment by Odyseus** [comment] 2016-10-26 20:09
Hello, everybody.

The issue described by @Piiit isn't really a bug on Cinnamon nor with the notification system. First, because it can be reproduced in all desktops environments (I tested it on XFCE, KDE 4.x, Plasma 5, Mate, Gnome Shell and of course Cinnamon). And second, the title (or summary as described on the [Desktop Notifications Specification](https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html)) of a notification doesn't support markup (HTML tags), [only the body of the notification does](https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html#markup). So there is no need to escape the `<>` symbols for them to be displayed on the notification title. The reason that `&gt;` is *translated* to `>` inside the body is precisely to avoid rendering HTML tags when one needs/wants to display a *raw tag* on the notification body.

**Comment by icarter09** [comment] 2019-12-04 03:38
@Odyseus can this ticket be closed?

**Comment by Piiit** [comment] 2019-12-04 08:53
@icarter09 I would like to keep it open, but I will change it into a feature request

**Comment by icarter09** [comment] 2020-01-19 14:50
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Closed by icarter09** 2020-01-19 14:50 UTC
Labels: FEATURE REQUEST
