### ISSUE TITLE
Constant crashes -> fallback mode on Fedora 27

### ISSUE THREAD

**Issue by h0wdyd3wdy** [linuxmint/Cinnamon#7240] opened 2018-01-31 20:16 UTC
```
 * Cinnamon version (cinnamon --version) - Cinnamon 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - Fedora 27
 * Graphics hardware *and* driver used - Inspiron 15 5000
 * 32 or 64 bit - 64 bit
 ```

For nearly 3 Fedora versions now(25-27), I constantly have issues with cinnamon crashing on my laptop, and says it's running in fallback mode.

I have been unable to figure out what is causing this.

journalctl -b0 >> boot.txt

I did this, but don't really see what I should be looking for.

Please see attachment.

[cinnamon-core-dump.txt](https://github.com/linuxmint/Cinnamon/files/1683175/cinnamon-core-dump.txt)

**Comment by clefebvre** [comment] 2018-02-01 09:05
Duplicate of https://github.com/linuxmint/Cinnamon/issues/7064

**Closed** 2018-02-01 09:05 UTC

**Comment by h0wdyd3wdy** [comment] 2018-02-01 10:36
It's not a duplicate.

Your script doesn't even work on my system:

#!/bin/bash
# Refresh network connections
sudo service network-manager restart
sleep 10
exit
---
Redirecting to /bin/systemctl restart network-manager.service
Failed to restart network-manager.service: Unit network-manager.service not found.
