### ISSUE TITLE
Sound Warning For Low Battery 

### ISSUE THREAD

**Issue by Ashutoshkale** [linuxmint/Cinnamon#3341] opened 2014-07-09 08:14 UTC
I am Using Mint 17 cinnamon There should be 'Sound Warning' For low battery.So Whenever I read E-books or play games in full-screen It should Alert me !!!

**Comment by pradacr** [comment] 2015-03-02 17:28
Necessary

**Comment by gilbertohasnofb** [comment] 2015-03-02 18:36
Absolutely. I already display the pavlovian effect of automatically plugging the cable when going to full screen, regardless of the current battery situation.

**Comment by rameshgkwd05** [comment] 2015-07-03 23:37
Hello,
I was also facing the same issue. I have developed one script which can be found at https://github.com/rameshgkwd05/Battery-Checker-Script-for-mint-ubuntu
A Battery Monitor script for mint/ubuntu os. Once started it polls for every 5 minutes. It Checks Battery percentage. If it is less than 18% then prompts a low-battery-sound. ( You can modify chekpc parameter in the script to other than 18).

Hope it helps.

**Comment by marksarnold** [comment] 2015-09-24 20:37
Absolutely crucial to prevent data loss.
Re. anandrkris's question: it definitely has to go into power management, because there should not only be an audible alert but also a popup, and some more settings/option. E.g. I  would suggest warning more than once (e.g. every x minutes while power is below the threshold and power cord is not plugged in; or every time the battery decreases another x percent).

Also, since getting hibernate to work properly on many laptops, there should be another option to "Suspend" on low power, in addition to "do nothing" and "hibernate". I understand that suspend mode still draws power, but for those that can not use hibernate because their laptop will not properly wake up, it is better than just plain out dying. Maybe it can survive long enough for someone to come back and plug in a power cord after all...

**Comment by ManIVIctorious** [comment] 2015-09-24 21:24
In this case I would also like to have some more options, especially "hybrid-sleep" would be a really good option.

**Comment by leigh123linux** [comment] 2015-09-25 06:11
I don't see any point in fixing this issue as it will all be obsolete/broken when mint rebases to the newer ubuntu (upower-0.99 +).

**Comment by SunRed** [comment] 2015-09-25 20:50
This might be related to issue #1646.
It would make much more sense fixing this bug instead of implementing the features being discussed here.

**Comment by marksarnold** [comment] 2015-09-25 22:56
@leigh123linux - when will that be?

@SunRed - I think this is much more than notifications not being displayed during full screen mode

**Comment by Vahan86** [comment] 2016-09-04 06:27
@JosephMcc, If I am not mistaken this feature is developed (thanks to you) and will be available in Cinnamon 3.2. Can we close this issue?

**Comment by JosephMcc** [comment] 2016-09-04 06:47
Well, you can now get a sound effect when a notification is displayed. So it would depend on weather a notification is properly displayed in this case.

I would be curious to hear from some of the posters in this issue if they do get a notification on low battery. In that case they would now be able to enable sound effects on notifications and get what they need.

**Comment by Vahan86** [comment] 2016-10-31 14:43
@JosephMcc, it means that the new feature doesn't solve this issue for example in case when you turn notifications off via inhibit applet for some reasons (for example during presentation). In this case you won't get sound warning for critically low battery.

**Comment by ManIVIctorious** [comment] 2016-10-31 18:49
Also I don't see any sense in getting (annoying) sounds with every displayed notification, I get much to much desktop notifications for this to be useful.

**Comment by mifas** [comment] 2017-07-08 05:48
When I'm watching a movie, the notification doesn't come in front. So suddenly laptop went to shutdown. This is the most important feature. I've how Windows 10 handle, force user t charge

**Comment by JosephMcc** [comment] 2017-07-08 05:52
I Cinnamon 3.4 critical notifications should show over fullscreen applications.

**Comment by mifas** [comment] 2017-07-08 14:18
@JosephMcc Yes, I do have Cinnamon 3.4, but how to identify 'critical' notification. Seems there is no option available

**Comment by clefebvre** [comment] 2018-02-05 16:18
Closing this issue as I can't reproduce the issue.

The sound idea is interesting but it's not necessary and it can be considered later on.

Looking at the CSD power plugin, we define power levels as such:

org.cinnamon.settings-daemon.plugins.power percentage-action 2
org.cinnamon.settings-daemon.plugins.power percentage-critical 3
org.cinnamon.settings-daemon.plugins.power percentage-low 10

Action and critical issue critical notifications.
Low issues a normal notification.

I tested with xplayer in fullscreen.. normal notifications don't show above the media player, but cricital notifications do indeed.

You can test yourself with:

`sleep 5 && notify-send -u critical test`

**Closed** 2018-02-05 16:18 UTC
Labels: FEATURE REQUEST, In Progress
