### ISSUE TITLE
Battery percentage in Power Management applet stuck

### ISSUE THREAD

**Issue by silver-awk** [linuxmint/Cinnamon#5116] opened 2016-03-03 23:45 UTC
Hello guys,

I've just noticed that the battery percentage in power management applet is stuck. If I delete and add again the applet it shows the correct value, but it does not change. In power management settings, under the "Batteries" tab, the percentage is correct and it updates accordingly to the battery status.

I'm running on Arch linux machine with kernel 4.4.3-1. If necessary, I can post the list of the last upgraded packages. Cinnamon doesn't seem to appear in recent upgrades, so I guess it could be something related to other packages.

Is anyone experiencing the same problem?

Thanks in advance and best regards.

Mauro

**Comment by Foxtrot** [comment] 2016-03-04 00:11
I am having the exact same problem on Arch 4.4.3-1-ARCH.

**Comment by f2404** [comment] 2016-03-04 05:06
The issue is similar to #4925

**Comment by Foxtrot** [comment] 2016-03-04 08:50
This bug is the same as #4925.

Issue resolved by downgrading to upower 0.99.3.

**Comment by silver-awk** [comment] 2016-03-04 09:26
I downloaded the git repo of `upower`, but there are lot of changes between the two tags, I can't figure out what could cause this problem. Anyway, I downgraded to 0.99.3 and it works fine. Thanks for suggestion @Foxtrot

**Comment by JosephMcc** [comment] 2016-03-04 11:11
Duplicate #4925

**Closed by JosephMcc** 2016-03-04 11:11 UTC
