### ISSUE TITLE
xdg-desktop-portal-gtk no longer used with x-d-p >= 1.17, x-cinnamon-portals.conf needed

### ISSUE THREAD

**Issue by smcv** [linuxmint/cinnamon#11857] opened 2023-09-11 15:20 UTC
### Distribution

any, I used Debian testing (Debian 13 prerelease)

### Package version

5.6.8

### Graphics hardware in use

qemu virtual machine with virtio emulated GPU 

### Frequency

Always

### Bug description

In older versions of x-d-p, if x-d-p does not find a suitable backend for the current desktop environment, it would fall back to trying any backend. This meant that all backends needed to be prepared to run in an environment where their functionality cannot actually work, which is rarely tested, leading to undesired situations where a desktop environment's backend can cause bugs while running different desktop environments (like https://github.com/linuxmint/xdg-desktop-portal-xapp/issues/5 and https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/74, each of which was a problem for "the other" desktop environment).

In the x-d-p 1.17.x prereleases and the upcoming 1.18.x stable release, this has been changed to give desktop environment developers more control over the backends they use. As described in https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst, the recommendation is now that each desktop environment should provide a file listing its preferred backends, similar to the one added by https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/95/diffs in GNOME.

This mechanism is similar to mimeapps.list, and it makes sense to configure it in some "reasonably central" desktop package - in GNOME, it's gnome-session that took responsibility for this. I don't normally use Cinnamon myself, but either cinnamon-common or cinnamon-session seems fairly appropriate.

As a result of not providing an `x-cinnamon-portals.conf` file, x-d-p falls back to only using the portals that have `UseIn=X-Cinnamon`. This includes x-d-p-xapp but not x-d-p-gtk. The result is that there is no portal for interfaces that are not implemented in x-d-p-xapp, notably FileChooser and OpenURI, which are important/basic functionality for sandboxed apps.

Another symptom of not having this configuration is that you will see warnings from `xdg-desktop-portal`:

```
xdg-desktop-portal-WARNING **: 16:14:51.348: Choosing xapp.portal for org.freedesktop.impl.portal.Inhibit via the deprecated UseIn key
```

and if debug output is enabled (`/usr/libexec/xdg-desktop-portal --verbose`), you'll also see that interfaces like `FileChooser` are not being provided.

### Steps to reproduce

* Install Cinnamon. I used a debian-installer daily build to install a Debian 13 prerelease, selecting all available desktop environments in the installer.
* Make sure both `xdg-desktop-portal-gtk` and `xdg-desktop-portal-xapp` are installed. I have x-d-p-gtk 1.14.1-1 and x-d-p-xapp 1.0.3-2.
* Use the upstream version of xdg-desktop-portal (this is necessary to reproduce the bug on Debian, but only because Debian temporarily has a downstream patch that mitigates this issue by hard-coding xdg-desktop-portal-gtk, which we should remove when major desktop environments have been fixed)
    * `sudo apt install git`
    * `sudo apt build-dep xdg-desktop-portal`
    * `git clone https://github.com/flatpak/xdg-desktop-portal`
    * `cd xdg-desktop-portal`
    * `meson setup --prefix=/usr --sysconfdir=/etc _build`
    * `meson compile -C _build`
    * `./_build/src/xdg-desktop-portal --verbose --replace`
    * Or to use the system copy of x-d-p, instead run: `/usr/libexec/xdg-desktop-portal --verbose --replace`
* Follow https://flathub.org/setup/Debian (or equivalent for your distro)
* `sudo flatpak install flathub xyz.tytanium.DoorKnocker`
* `sudo flatpak install flathub com.belmoussaoui.ashpd.demo`
* `flatpak run xyz.tytanium.DoorKnocker`, see which portals are available
* `flatpak run com.belmoussaoui.ashpd.demo`, try to use some portals
    * go to File Chooser tab, leave everything at its defaults, click Request; you should get a File -> Open dialog
    * go to Open URI tab, leave everything at its defaults, click Request; you should get a website opened in your browser

### Expected behavior

* xdg-desktop-portal-xapp is used for the portals that it implements, such as Inhibit
* xdg-desktop-portal-gtk is used for other portals, notably File Chooser and Open URI

Because `xdg-desktop-portal` was run with `--verbose`, you'll see messages about which portal backend it chooses for each interface, and why.

### Additional information

If you're using Debian's patched `xdg-desktop-portal` and the configuration file is missing, it will fall back to `xdg-desktop-portal-gtk`, with warnings like this logged:

```
xdg-desktop-portal-WARNING **: Choosing gtk.portal for org.freedesktop.impl.portal.Account via temporary hard-coded fallback
```

### Proposed solution

The solution to all of this is to install a file into `${datadir}/xdg-desktop-portal/x-cinnamon-portals.conf` with details of the portals that Cinnamon wants to use. The `x-cinnamon` prefix is because Cinnamon uses `XDG_CURRENT_DESKTOP=X-Cinnamon`.

For example, I think the Cinnamon developers' intention is to try to use the -xapp backend, falling back to -gtk if -xapp isn't installed or doesn't know how to do something. The way to write that would be:

```
[preferred]
default=xapp;gtk;
```

Downstream request: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050801

**Comment by mtwebster** [comment] 2023-09-11 15:43
Thanks for the heads-up with this. I'll get those files added when I get a chance to test it all out.

For us it looks like I'll need to add 3 of them (-xapps has partial support for xfce and mate). We'll probably have add breaks/conflicts once/if mate and xfce4 ship their own portal implementation.

**Comment by smcv** [comment] 2023-09-11 20:06
> For us it looks like I'll need to add 3 of them (-xapps has partial support for xfce and mate). We'll probably have add breaks/conflicts once/if mate and xfce4 ship their own portal implementation.

No, please add only an `x-cinnamon-portals.conf` for Cinnamon. Please don't add a `mate-portals.conf` for Mate or an `xfce-portals.conf` for XFCE: the preferred portal backend(s) for Mate should be the Mate developers' choice, and the preferred portal backends for XFCE should be the XFCE developers' choice.

I've asked [Mate](https://github.com/mate-desktop/mate-session-manager/issues/311) and [XFCE](https://gitlab.xfce.org/xfce/xfce4-session/-/issues/181), separately, to add similar files to choose their own preferred portals.

It makes more sense (in my opinion at least) to put `x-cinnamon-portals.conf` in some central Cinnamon package, and not in `xdg-desktop-portal-xapp`. The GNOME equivalent is `gnome-portals.conf` in `gnome-session`, not in `xdg-desktop-portal-gnome`.

**Comment by clefebvre** [comment] 2023-09-11 21:10
There's no reason for MATE/Cinnamon/Xfce to all make their own implementations. The goal of XApp is to provide common software for these desktops. That's what xdg-desktop-portal-xapp does, it's designed to support all these desktops. It was done because -gtk didn't.

I don't know what's wrong with raveit. He can't accept the fact that we develop projects which are cross distribution and/or cross DE. He thinks everything we do is Mint/Cinnamon specific. We started XApp (years ago) specifically because we wanted to support cross-DE development between GTK based desktops.

If MATE and Xfce provide these files and switch to the -gtk portal, they won't just create regressions in their respective DEs, they'll make xdg-desktop-portal-xapp completely useless. If only Cinnamon uses it, it'll have no reason to continue to be an XApp project.

If xdg-desktop-portal-gtk accepts to support all these DEs, like xdg-desktop-portal-xapp currently does then we'll all point towards it and we'll discontinue xdg-desktop-portal-xapp.

**Comment by clefebvre** [comment] 2023-09-12 17:43
@smcv I think the big question is whether or not the xdg-desktop-portal-gtk project is happy to officially support MATE, Cinnamon and Xfce. Can you clarify the scope of the project and the position of the devs on this?

We started xdg-desktop-portal-xapp on the assumption that xdg-desktop-portal-gtk was GNOME-centric and didn't/wouldn't. If it does, we'd be happy to use it and discontinue xdg-desktop-portal-xapp going forward.

Our main priority with XApp is to factorize common needs, so that we don't each develop the exact same thing in all three DEs. If it's done upstream at GTK level, then even better.

**Comment by smcv** [comment] 2023-09-12 18:26
This issue report is not intended to be about whether x-d-p-xapp is the right thing for MATE or Xfce, only about making the right thing happen when running Cinnamon. The point of the `portals.conf(5)` design is that it puts the maintainers of each desktop environment in control of what will happen while running their specific desktop environment - whether that means their own desktop-specific implementation or a shared/collaborative implementation is up to them.

From what I've seen of the design of the `portals.conf(5)` mechanism, I'm quite sure that the intention is that Cinnamon should not be installing a `foo-portals.conf` for any non-Cinnamon desktops. If GNOME or MATE installed an `x-cinnamon-portals.conf` or an `x-cinnamon-mimeapps.list` that set the preferred portals or apps for Cinnamon to the implementations that GNOME or MATE developers thought Cinnamon should prefer, I'm sure you'd consider that to be rude.

> I think the big question is whether or not the xdg-desktop-portal-gtk project is happy to officially support MATE, Cinnamon and Xfce. Can you clarify the scope of the project and the position of the devs on this?

I am not a lead developer on x-d-p-gtk, so I can't say anything on that authoritatively. x-d-p-gtk has a bit of a weird history because it was originally written with only GNOME in mind, but everyone except KDE started using it on other desktops anyway, because there were no portal implementations beyond -gtk and -kde for a while; so eventually the GNOME-specific bits of x-d-p-gtk (which have GNOME dependencies, and also tend to be relatively tightly coupled to a specific GNOME Shell version) were moved to x-d-p-gnome. Initially, the features with GNOME dependencies were made compile-time- or runtime-optional in x-d-p-gtk instead of being deleted, so that older distributions could still enable them if they didn't have x-d-p-gnome available yet; but most of them were recently removed altogether, equivalent to compiling an older version with those features disabled.

My understanding (which might be wrong) is that anything that can work completely generically without desktop-environment-specific code paths (like its AppChooser and FileChooser UIs) is in-scope for x-d-p-gtk, but things that need a separate code path for each desktop environment (like the various Screenshot and Wallpaper implementations in x-d-p-xapp) are considered to be out of scope for x-d-p-gtk.

For the parts with desktop-specific behaviour, it's a desktop environment maintainer decision whether to collaborate on an x-d-p-xapp with multiple code paths like `if (is_xfce) { ... }` and so on, or have separate backends for separate desktops. I don't want to get involved in that choice, except to say that if the maintainers of another desktop environment don't want to use or participate in a shared portal backend, then trying to force it on them is probably counterproductive.

**Comment by clefebvre** [comment] 2023-09-12 19:01
It goes without saying Cinnamon isn't going to provide a MATE file or vice versa. That would be mad. The design of portals.conf makes it so this decision rests with each DE. Nobody's forcing anyone here. We all want these DEs to be as functional as possible.

To fix this issue we don't only need to provide a .conf file, we need to know what to write in it. We can't do that if we don't know if we can rely on xdg-desktop-portal-gtk. This needs to be clarified by the -gtk project. We have a dependency on the xapp portal because that's the one which supports us right now and which gives us a functional portal implementation. If the GTK one is cool to take on that role we'll switch to it instead.

MATE and Xfce are faced with the same decision. If they switch to -gtk and -gtk isn't OK to support them, we're just going to see regressions at user level and unwanted bug reports directed upstream at -gtk.

What we do at XApp level will depend on the DEs decisions. Obviously if they switch to -gtk, we'll discontinue xdg-desktop-portal-xapp.

**Comment by smcv** [comment] 2023-09-12 19:36
> We have a dependency on the xapp portal because that's the one which supports us right now and which gives us a functional portal implementation. If the GTK one is cool to take on that role we'll switch to it instead.

If you're assuming that a single backend is sufficient for everything, then that would require duplicating a lot of code in -xapp that currently does not need to be there. Neither x-d-p-gtk nor x-d-p-xapp implements everything on their own: for example -gtk never implemented `o.fd.impl.portal.Screenshot` for anything other than GNOME (and that interface has now been removed from -gtk completely), and conversely, -xapp never implemented `o.fd.impl.portal.FileChooser`.

However, by combining the two backends as `default=xapp;gtk;`, you get the majority of the `o.fd.impl.portal.*` interfaces, including both `Screenshot` and `FileChooser`. Needing to have both is normal: if you look at the gnome-session change that I linked in the issue request, you'll see that GNOME needs multiple backends for full functionality too. x-d-p chooses an implementation for each interface on a per-interface basis, so it is completely OK to be using -gtk for some and -xapp for others.

I think it's safe to assume that -gtk will continue to provide most of the interfaces that it provides, in a reasonably cross-desktop way. The ones that can already be turned off at compile-time by distributors are the most likely to disappear, especially the ones that are GNOME-specific and therefore won't work on Cinnamon anyway (Wallpaper, Lockdown, some of Settings). The ones that are completely non-GNOME-specific (like FileChooser and Email) are the most likely to stay.

You already can't assume that -gtk will provide you with implementations of *every* interface, because it already doesn't: for instance it has never had an implementation of Screenshot that worked outside GNOME. For the interfaces that -gtk doesn't provide, either Cinnamon provides a backend that does (-xapp or similar), or the interface will just not be available to Cinnamon users. Similarly, if you're not happy with the UI or features provided by -gtk for a particular interface, then that would be a good reason to have another implementation of that interface in a backend of your choice, which you can make better or more featureful if you want to.

**Comment by Fantu** [comment] 2023-09-15 07:57
@smcv thanks for the info
I was thinking of including x-cinnamon-portals.conf you suggested in the next cinnamon upload to debian experimental.
actually in cinnamon package of debian I had put xdg-desktop-portal-xapp in recommends as not all users use snap and flatpak (and as seen over the years there are many users who want to do minimal desktop installations and therefore I try to support such cases too), have xdg-desktop-portal-xapp in recommends is ok or I should put in deps?
and I should add xdg-desktop-portal-gtk in recommends as needed for something not implemented in -xapp and after add x-cinnamon-portals.conf that point to it, right?

**Comment by smcv** [comment] 2023-09-15 09:50
>  I was thinking of including x-cinnamon-portals.conf you suggested in the next cinnamon upload to debian experimental

Yes please, or even the next upload to unstable.

> have xdg-desktop-portal-xapp in recommends is ok or I should put in deps?

I think using a Recommends is OK for a desktop environment that aims to be relatively modular. Suggests would be too weak, though.

> and I should add xdg-desktop-portal-gtk in recommends as needed for something not implemented in -xapp and after add x-cinnamon-portals.conf that point to it, right?

Yes, I think a Recommends on x-d-p-gtk is necessary: otherwise a default installation of Cinnamon will be missing some very basic portal backends like the file chooser.

**Comment by Fantu** [comment] 2024-01-28 17:39
@smcv when I added it to Debian 4 months ago I added in cinnamon-common as don't arch dependent and without need to stay on arch dep. package FWIK.
Upstream added to cinnamon instead in https://github.com/linuxmint/cinnamon/pull/11863
Is there a reason to have it in arch dependent package or not and is better to have it in -common?

**Comment by smcv** [comment] 2024-01-29 00:35
I think either way is fine. I don't think there's any particularly strong reason in either direction to prefer putting this file in cinnamon vs. cinnamon-common - as long as installing the Cinnamon desktop environment pulls it in somehow (directly or indirectly), I would consider this issue to be resolved. The specific package that it lives in is a minor implementation detail.

If it's in -common then it's shared across all architectures, but it's such a small file that any advantage from that would be *extremely* minor.

If it's in the cinnamon package then that's the same place as the Depends on x-d-p-gtk and x-d-p-xapp, which seems like something that intuitively makes sense?

**Comment by Fantu** [comment] 2024-01-29 09:07
@smcv big thanks for your reply. Then I move it to Debian in cinnamon.

**Comment by mtwebster** [comment] 2024-07-28 17:12
I think I can close this?

https://github.com/linuxmint/cinnamon/commit/5dfcbd4666ed6d053055e409ef1b1b347622c4dc

**Closed by mtwebster** 2024-07-28 17:12 UTC
