### ISSUE TITLE
[ISSUE] High CPU and RAM usage

### ISSUE THREAD

**Issue by Translator5** [linuxmint/Cinnamon#5034] opened 2016-01-24 18:31 UTC
The RAM usage after a hour of using the desktop is up to 700 MB, at the start it was just 300 MB.
I just open and close different Settings.
Customized the Themes (I use just the default).
Also the CPU is allways up to 75%.

Linux Mint 17.3 fresh installed.
I use a Intel Pentium 4 3.2 Ghz 1x (2x Thereads).
2250 MB RAM. 500 GB HDD.
ATI READON 9600 Series XT AGP.
More about: http://community.linuxmint.com/hardware/view/25651

In compare with MATE or XFDE it is dramatic.
I also tried KDE, but there are averywhere the "K's". Its not the most pretty one.
Yes I tried for every DE a new OS installation with fullwipe.

By the way I also had 2 time a full Crash to Terminal/Console, while gaming.

**Comment by leigh123linux** [comment] 2016-01-25 00:07
MATE or XFDE are very light weight compared to Cinnamon!, I would expect cinnamon to use double the RAM.
As for CPU usage, post the output for 'top' command.

**Comment by lestcape** [comment] 2016-01-25 05:32
The RAM after several things that you have is normal to me. I think is not good, but it's in that way. The Icon theme are cache by gio, so will not be release this memory after load an icon, for example. Also could be some memory leaks in the tree party extension that you use or also inside the cinnamon core (is difficult but could be).

 Which reference a possible unknown problem is the cpu usage.

**Comment by RalfJung** [comment] 2016-03-07 08:17
The memory usage of the `cinnamon` process is excessive. After some days of uptime (I don't usually reboot my computer), it is typically above 1GB, which is pretty ridiculous - that's more RAM than KDE *plus* Gnome take together.

This is with Cinnamon 2.8.

**Comment by jean** [comment] 2016-06-17 09:10
Uptime 4 days, cinnamon is at top of `top`, VIRT 3089M, RES 1884M, SHR 282M, CPU 7.8%

System:    Host: X250 Kernel: 3.19.0-32-generic x86_64 (64 bit) Desktop: Cinnamon 2.8.8
           Distro: Linux Mint 17.3 Rosa

**Comment by Translator5** [comment] 2016-06-19 09:33
Update - second machine
Linux Mint 17.03
Intel core i7x980 3.33GHz x12
18 GB RAM
All up to date
Cinnamon 2.8.8+rosa
Uptime: 30 min.

CPU usage 6%
RAM usage 400MB

Also running;
Steam, Telegram and Firefox (1 tab)

This is really bad for a DE, because this usage will slow down the users experience of Linux and will scare them. Especially the newbies. :confused:

**Comment by Translator5** [comment] 2017-01-03 10:42
I have got new news for latest version;
On start Cinnamon takes ~ 288 RAM, but on open a new windows it adds ~ 1.5 MB RAM additional.
On close of those "windows" cinnamon do not clear the cache & the RAM is still in use!

**Comment by lestcape** [comment] 2017-01-03 17:14
@Translator5 the cjs garbage collector do not execute when you want or when you think that it's time to be executed... You can force to execute the garbage collector, but  also this not give you a measure of the memory usage, because will also clean more things... So, you can not speak of it adds ~ 1.5 MB RAM, because yes all that you use add RAM, but it's not released when you want and will never be in that way, because cinnamon (cjs) use a garbage collector and the garbage collector work in this way he do a clean when he want... In other word this not add any additional point of information.

**Comment by leigh123linux** [comment] 2017-12-17 21:44
Closed

Duplicate of #6850

**Closed by leigh123linux** 2017-12-17 21:44 UTC
