### ISSUE TITLE
Cinnamon's center window placement is off by a few pixels.

### ISSUE THREAD

**Issue by Sojiro84** [linuxmint/cinnamon#8915] opened 2019-10-23 19:18 UTC
```
 * Cinnamon version =  4.2.4
 * Distribution = Manjaro
 * Graphics hardware = AMD RX 580 and MESA 19.2.1-1
 * Architecture = 64 bit
 ```

**Issue**
Cinnamon's window placement in the center is off by a few pixels to the left.

**Steps to reproduce**
Open a window and measure the distance in pixels on both sides of the window. You will see that it is not perfectly in the center. It is off to the left by a few pixels.

**Expected behavior**
I expected the windows to be placed in the center correctly.

**Other information**
I attached 2 screenshots to showcase the issue. In this example I got my steam game list in a small window and the friends-list in the exact same width. Then I have Firefox placed in the center. The placement is done by Cinnamon itself (I also have a key bound to re-center windows and used that as well to make sure it is in the center that Cinnamon thinks is the center). You can see in the
screenshots that on the left it covers more of the steam games window vs the steam friends-list.

You can do the same measurement with other programs, the centering is always off.

https://user-images.githubusercontent.com/13678578/67426414-563c9f80-f5da-11e9-8594-c1246bf3e6e0.png
https://user-images.githubusercontent.com/13678578/67426415-563c9f80-f5da-11e9-9dbf-b05d29b26c6e.png

**Comment by Sojiro84** [comment] 2019-10-23 19:19
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3764061/xsession-errors.txt)

**Comment by JosephMcc** [comment] 2019-11-21 11:36
Yes. It's a duplicate of another issue you already posted in :) https://github.com/linuxmint/cinnamon/issues/5115

**Closed by JosephMcc** 2019-11-21 11:36 UTC
