### ISSUE TITLE
Black screen with mouse cursor after login - high CPU usage and memory leak due to 'Failed to set the background'

### ISSUE THREAD

**Issue by bendovercz** [linuxmint/Cinnamon#5569] opened 2016-08-19 08:34 UTC
I'm having trouble with Cinnamon since version 3. Almost every time I boot (lets say 9 out of 10) I get black screen with mouse cursor. When looking to system usage Cinnamon slowly eats all of my 16G RAM with high CPU usage.

Restarting X server solves this issue but my wallpaper always gets reset to some default image.

Attaching `.xsession-errors` for my last boot - its truncated
`(cinnamon-settings-daemon:722): CinnamonDesktop-WARNING **: Failed to set the background '/home/user/Pictures/wallpaper.jpg': GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'SetBackgroundFile'` is still repeating until Cinnamon runs out of RAM or X server is restarted.

[xsession_log.txt](https://github.com/linuxmint/Cinnamon/files/426599/xsession_log.txt)

**Comment by hubertmeier** [comment] 2016-08-30 05:50
I have a similar problem ! Every About 6-8 of 10 starts need about 15 Minutes to start, the background picture has reset to standard. The cinnamon Log shows hundreds of "Background Image loaded". The problem came with mint 18. 17.3 was absolutely ok. Yesterday i tested Mint 18 KDE beta and istalled later cinnamon from the repository. KDE startet without problems, Cinnamon shows the same problem.

**Comment by OldSparta** [comment] 2016-08-31 14:41
I have the exact same problem, and I've had it happen both on Korora 24 and Mint 18. Installed XFCE on both distros and it works fine. However I switch back to cinnamon, and about 2/3 of the time, it fails to start or starts in fallback mode. 

Asus S550CA: Intel core i5 3317U, 8GB, 128GB Kingston HyperX

**Comment by steveyh25** [comment] 2016-09-24 23:06
Same here - although mine's happening randomly about 10% of the time. Black screen with cursor, and switching to another terminal and logging in I can see cinammon at 100% cpu usage and quickly filling my entire 16gb of ram up. If I kill it and startx then there is no issue. Also glass.log is filled with background picture errors.

cpu 2500k, gpu gtx1070

**Comment by JosephMcc** [comment] 2016-09-24 23:13
> Also glass.log is filled with background picture errors.

It would help if you could tell us what the actual error is.

**Comment by steveyh25** [comment] 2016-09-24 23:40
I lost the log but managed to make it do it again so... here's one. It's not the same error but it's to do with the background.. however the way Cinammon is behaving is similar.

My xsession-errors log is also filled with the following error:
(cinnamon-settings-daemon:1894): GLib-CRITICAL **: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed

[glass.log.txt](https://github.com/linuxmint/Cinnamon/files/491417/glass.log.txt)

**Comment by jeweloper** [comment] 2016-10-03 21:14
I can confirm these bug.
Since cinnamon v3 more or less every tenth startup is unsuccessful. By now it is far better. There was a time nearly every second startup failed.
When it happens the login screen hangs after I confirmed my password. All you can see is the login background image and the mouse pointer (the login mask is already closed).
My workaround is to switch into tty 3, login and do a restart. (And hope the next startup will become successful.)
Like bendovercz mentioned the cinnamon and cinnamon-settings-damon process causes a high cpu and ram usage when the startup fails/hangs. The .xsession-errors file increase successively by the following lines:
>(cinnamon-settings-daemon:844): CinnamonDesktop-WARNING **: Failed to set the background '/usr/share/pixmaps/backgrounds/antergos/field_by_stevenfields-d59ap2i.jpg': GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method »SetBackgroundFile«
> (cinnamon-settings-daemon:844): GLib-CRITICAL **: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed

After a restart it could happen that the org.cinnamon.desktop.background picture-uri is set to its default value: 'file:///usr/share/backgrounds/gnome/adwaita-timed.xml'.
For now I edit adwaita-times.xml in a way that cinnamon loads my personal favourite background image by default. But that doesn't solve the hangups, only the reconfiguration.

System: Arch Linux 4.7.5-1-ARCH
Desktop: Cinnamon 3.0.7
Display Manager: lightdm 1.18.3 + lightdm-gtk-greeter 2-0-1

Hope somebody will find a solution.

**Comment by steveyh25** [comment] 2016-10-03 21:43
The issue appears to be logging in too fast with specific kernels.. I can reproduce the issue very regularly using 4.4.0-38 kernel if I login in under 5 seconds from when the login screen appears. I haven't reproduced it yet on kernel 4.40-21, which leads me to believe this is something to do with the kernel version installed...

**Comment by jeweloper** [comment] 2016-10-03 23:11
Since cinnamon v3 release I frequently run cinnamon with an up-to-date mainline kernel as well as with an up-to-date 4.4-lts kernel (on the same machine).
I cant recognize no verifiable differences.

I don't think that it is in practise to wait additionally 10s on every boot. Occasional reboots are less time consuming. At least with an ssd.  :smile:

**Comment by jeweloper** [comment] 2016-10-04 01:12
I thought to disable the background plugin could be a workaround.
`gsettings set org.cinnamon.settings-daemon.plugins.background active false`
But the background plugin seems not cause the issue. Cinnamon still hangs on startup.

So the relevant error message is:
`(cinnamon-settings-daemon:844): GLib-CRITICAL *: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed`

But I think this is a empty message  :/

**Comment by jeweloper** [comment] 2016-10-04 23:19
For completeness: Here are the xsession-errors file and the corresponding debug output of cinnamon-settings-daemon.
I've copied only the first 2000 lines of each file, because of the file size.
But I think the recurring parts are identifiable.
[cinnamon-settings-daemon.debug.txt](https://github.com/linuxmint/Cinnamon/files/509673/cinnamon-settings-daemon.debug.txt)
[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/509674/xsession-errors.txt)

Hope this can be helpful.

**Comment by jeweloper** [comment] 2016-10-09 22:01
Up to now it seems there are multiple root causes for this issue. And yes, I think I've got a workaround.
In my scenario I could avoid the startup freeze by increasing the startup delay for all listed applications under Preferences->Startup Applications. (10s or maybe 5s should be enough.)
But this doesn't solved the problem in all. From time to time there are still these "power-plugin-WARNING[s]" and GLib-CRITICAL errors in .xsession-errors file. But now this doesn't end up in a freeze anymore.
My startup applications are:
- easystroke
- owncloud (Didn't cause the issue. Because of another startup issue I set for these app a delay of 5s long time ago.)
- PulseAudio Sound System
- [parmac] Update Notifier (I think this app cause the issue. Because the app needs a network connection and its very laggy at startup. And its integrate a tray-icon in the panel.)

Hope this workaround helps somebody else.

**Comment by leigh123linux** [comment] 2016-10-10 04:45
@jeweloper 

Get Arch to patch cinnamon-settings-daemon and cinnamon-desktop

http://pkgs.fedoraproject.org/cgit/rpms/cinnamon-settings-daemon.git/tree/csd-background-manager.patch

http://pkgs.fedoraproject.org/cgit/rpms/cinnamon-desktop.git/tree/gnome-bg.patch


This is needed as Ubuntu have fucked around with the accountservice package and added a new function (SetBackgroundFile).

**Comment by leigh123linux** [comment] 2016-10-10 04:56
@jeweloper 

```
(cinnamon-settings-daemon:745): power-plugin-WARNING **: session inhibition not available, cinnamon-session is not available
```

This message is harmless spam caused because the session wasn't ready

https://mail.gnome.org/archives/commits-list/2013-January/msg07388.html

**Comment by jeweloper** [comment] 2016-10-10 08:24
@leigh123linux thanks for your hints.

> Get Arch to patch cinnamon-settings-daemon and cinnamon-desktop

Could you also please post the corresponding error description. Or are there no known issues - except that it minimize spam? (Like I mention some post above the bug seems nothing to do with my startup freeze.)

> This message is harmless spam caused because the session wasn't ready

Yes, it seems to be harmless when cinnamon starts the power-plugin before the session is available. But on the other it could end up in a freeze, when cinnamon starts specific third-party-apps before the session is available.
Currently I'm missing the overview how the startup works. But in my point of view cinnamon shouldn't run any third-party-apps before the session isn't available.

Although for now I'm happy I could fix the issue with a easy workaround.

**Comment by spicypixel-** [comment] 2016-10-22 19:34
Any progress on what is causing this? It's happening to me on a fresh install of Mint 18 and it's a pretty big show stopping bug.

**Comment by steveyh25** [comment] 2016-11-09 23:45
re-installed Mint 18 on my thinkpad x220 over the weekend and it happens on there too (intel graphics, only similarity is the sandybridge processor). This is surely a widespread bug?

**Comment by crocket** [comment] 2016-11-14 23:19
I'm on ArchLinux, and this bug affects me. This is very painful. I almost thought about moving to GNOME because of this.

I merely wanted a desktop environment with proper color management and wacom tablet GUI settings.

Which desktop environments other than GNOME and cinnamon support proper color management and wacom tablet GUI settings?

**Comment by shavounet** [comment] 2016-11-17 08:22
Reproduced yesterday and today. I have a Linux Mint 18, with kernel 4.4 and btrfs filesystem.

I noticed a very high CPU & RAM usage (filling it up, all 8Go), and on reboot I only noticed one missing custom setting : my desktop backgroup with Mint's default photos was reverted to the default background (with the logo).

**Comment by crocket** [comment] 2016-11-17 10:45
If you use ArchLinux, vote on https://bugs.archlinux.org/task/51831 which works around this issue.

**Comment by kpeterson11** [comment] 2016-12-05 20:18
I just wanted to mention that I am having this exact issue on arch linux since upgrading my laptop from a mechanical hdd to an ssd.  No problems when using the slow hard drive.  When running the ssd I can't log in to cinnamon most of the time.  Doesn't matter which kernel I use either.  I'm currently on 4.9.rc8.

**Comment by steveyh25** [comment] 2017-02-18 13:46
Is no one looking at this? :(

@kjp4756 both of my computers with this issue are on SSD's also...

**Comment by spicypixel-** [comment] 2017-02-18 13:48
Have to admit I gave up using shutdown and just use suspend/hibernate now. It's not fun to run a russian roulette gamble of a successful cold boot, especially since the odds are in the favour of failing.

**Closed** 2017-05-03 11:15 UTC
Labels: BUG
