### ISSUE TITLE
two batteries in laptop but in “power management” I can see only one

### ISSUE THREAD

**Issue by sublime238** [linuxmint/cinnamon#9024] opened 2019-12-15 10:24 UTC
* Cinnamon version (cinnamon --version)
Cinnamon 4.2.4

 * Distribution
Mint 19.2

 * Graphics hardware *and* driver used
no proprietary drivers are in use

**Issue**
two batteries in laptop. in “power management” I can see only one

upower -d

Device: /org/freedesktop/UPower/devices/line_power_AC
  native-path:          AC
  power supply:         yes
  updated:              Sun 15 Dec 2019 10:35:27 AM CET (2466 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              no
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/battery_CMB1
  native-path:          CMB1
  vendor:               Fujitsu
  model:                CP700282-01
  serial:               01A-Z160325006308Z
  power supply:         yes
  updated:              Sun 15 Dec 2019 11:15:22 AM CET (71 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              43,6752 Wh
    energy-empty:        0 Wh
    energy-full:         67,1868 Wh
    energy-full-design:  72,36 Wh
    energy-rate:         5,8968 W
    voltage:             11,568 V
    time to empty:       7,4 hours
    percentage:          65%
    capacity:            92,8507%
    technology:          lithium-ion
    icon-name:          'battery-full-symbolic'
  History (rate):
    1576404922	5,897	discharging

Device: /org/freedesktop/UPower/devices/battery_CMB2
  native-path:          CMB2
  vendor:               Fujitsu
  model:                CP709256-02
  serial:               01A-W171120012010W
  power supply:         yes
  updated:              Sun 15 Dec 2019 11:14:45 AM CET (108 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              17,6364 Wh
    energy-empty:        0 Wh
    energy-full:         29,8836 Wh
    energy-full-design:  28,08 Wh
    energy-rate:         3,8016 W
    voltage:             11,556 V
    time to empty:       4,6 hours
    percentage:          59%
    capacity:            100%
    technology:          lithium-ion
    icon-name:          'battery-good-symbolic'
  History (rate):
    1576404885	3,802	discharging

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         yes
  updated:              Sun 15 Dec 2019 11:15:22 AM CET (71 seconds ago)
  has history:          no
  has statistics:       no
  battery
    present:             yes
    state:               discharging
    warning-level:       none
    energy:              61,3116 Wh
    energy-full:         97,0704 Wh
    energy-rate:         9,6984 W
    time to empty:       6,3 hours
    percentage:          63,162%
    icon-name:          'battery-full-symbolic'

Daemon:
  daemon-version:  0.99.7
  on-battery:      yes
  lid-is-closed:   no
  lid-is-present:  yes
  critical-action: HybridSleep

![image](https://user-images.githubusercontent.com/14123399/70861380-5d729080-1f2d-11ea-9bf8-b0f7ebe63973.png)

![image](https://user-images.githubusercontent.com/14123399/70861392-7aa75f00-1f2d-11ea-83d9-82f157f906e9.png)

**Comment by leigh123linux** [comment] 2019-12-15 11:30
Duplicate of #7745

**Closed by leigh123linux** 2019-12-15 11:30 UTC
