### ISSUE TITLE
Cinnamon Serena sometimes freezes when switching display modes

### ISSUE THREAD

**Issue by jjaakkol** [linuxmint/cinnamon#6275] opened 2017-02-13 09:51 UTC
I have a dual monitor setup on HP laptop with a dock with Ubuntu 16.04 + Mint Cinnamon. Pretty often (like 25% of times) cinnamon freezes when switching between laptop internal monitor and dock external DP monitor. Only mouse still moves, cinnamon fails to scale the display and no windows can gain focus.  Restarting cinnamon fixes the issue (but you off course you cannot do that in the frozen session).  This issue is not new for me, Cinnamon Sarah had it too (I updated to Serena in the hope that it would fix this).

Since I can reproduce this easily, I attached the backtrace of the hung cinnamon process (all threads). However, I suspect the hung thread is thread 1:

Thread 1 (Thread 0x7fe60723fac0 (LWP 6219)):
#0  0x00007fe60533ab5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fe5fdc1bc62 in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fe5fdc1d617 in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fe5fdc1d721 in xcb_wait_for_reply () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#4  0x00007fe603e3bb14 in  () at /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#5  0x00007fe603590103 in _cogl_winsys_wait_for_vblank (onscreen=onscreen@entry=0x55c451d372c0) at winsys/cogl-winsys-glx.c:1632
#6  0x00007fe6035908a0 in _cogl_winsys_onscreen_swap_region (onscreen=0x55c451d372c0, user_rectangles=<optimised out>, n_rectangles=<optimised out>) at winsys/cogl-winsys-glx.c:1834
#7  0x00007fe60357f865 in cogl_onscreen_swap_region (onscreen=0x55c451d372c0, rectangles=rectangles@entry=0x7ffe7f1d2520, n_rectangles=n_rectangles@entry=1) at cogl-onscreen.c:374
#8  0x00007fe60648e175 in clutter_stage_cogl_redraw (stage_window=0x55c451cfa070) at cogl/clutter-stage-cogl.c:625
#9  0x00007fe6064fa447 in _clutter_stage_do_update (stage=0x55c451d4be00 [ClutterStage]) at clutter-stage.c:1130
#10 0x00007fe6064fa447 in _clutter_stage_do_update (stage=0x55c451d4be00 [ClutterStage]) at clutter-stage.c:1186
#11 0x00007fe6064e4199 in clutter_clock_dispatch (master_clock=0x55c451bf6640 [ClutterMasterClockDefault], stages=0x55c455aa3560) at clutter-master-clock-default.c:443
#12 0x00007fe6064e4199 in clutter_clock_dispatch (source=<optimised out>, callback=<optimised out>, user_data=<optimised out>) at clutter-master-clock-default.c:567
#13 0x00007fe605870197 in g_main_context_dispatch (context=0x55c451899e60) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3154
#14 0x00007fe605870197 in g_main_context_dispatch (context=context@entry=0x55c451899e60) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3769
#15 0x00007fe6058703f0 in g_main_context_iterate (context=0x55c451899e60, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimised out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3840
#16 0x00007fe605870712 in g_main_loop_run (loop=0x55c45188f9d0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4034
#17 0x00007fe606c54938 in meta_run () at core/main.c:542
#18 0x000055c44f8b38c0 in main (argc=1, argv=0x7ffe7f1d2928) at main.c:329

Driver and device is:

[   382.071] (II) intel(0): Using Kernel Mode Setting driver: i915, version 1.6.0 20151010
[   382.071] (II) intel(0): SNA compiled: xserver-xorg-video-intel 2:2.99.917+git20160325-1ubuntu1.2 (Timo Aaltonen <tjaalton@debian.org>)
[   382.073] (--) intel(0): Integrated Graphics Chipset: Intel(R) HD Graphics 5500

xrandr output also attached. 

- Jani

[trace.txt](https://github.com/linuxmint/Cinnamon/files/770633/trace.txt)
[xrandr.txt](https://github.com/linuxmint/Cinnamon/files/770634/xrandr.txt)

**Comment by ryantiger658** [comment] 2017-03-15 13:41
I am having the same issue on my Intel NUC with 3 monitors. Two 1080p and one 4k monitor. It gets really annoying really quickly!

**Comment by flavorjones** [comment] 2017-07-04 04:26
This *might* be a dupe of #6224?

**Comment by Vahan86** [comment] 2019-11-26 19:07
@jjaakkol, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment] 2019-12-22 09:34
@icarter09, can we close the issue since there is no response from OP?

**Closed** 2019-12-22 14:45 UTC
Labels: BUG
