### ISSUE TITLE
Screensaver doesn't lock the PC if panel widget is active and focused on

### ISSUE THREAD

**Issue by ikoveshnikov** [linuxmint/Cinnamon#7677] opened 2018-06-27 15:04 UTC
* Cinnamon version (cinnamon --version): 3.8.4
 * Distribution - Arch
 * Graphics hardware *and* driver used: Intel HD Graphics 5500, driver=i915 
 * 64 bit

**Issue**

Screen is not locked if focus is on panel widget. The lock timeout in `cinnamon settings -> screensaver -> settings -> delay` is ignored. In other cases it works just fine.

**Steps to reproduce**

* Click to any panel widget, e.g. calendar. 
* The widget is shown (the calendar). 
* Wait some time. No actions taken. No mouse or keyboard or other HID activity.
* The screen is not locked.

**Expected behaviour**

The screen should be blocked after the delay. 

**Other information**

**Comment by leigh123linux** [comment] 2018-06-27 15:09
Duplicate of 1430

**Closed by leigh123linux** 2018-06-27 15:09 UTC
