### ISSUE TITLE
Icons disappear (get unpinned) from panel

### ISSUE THREAD

**Issue by putnokiabel** [linuxmint/cinnamon#8517] opened 2019-04-15 17:30 UTC
```
 * Cinnamon version (cinnamon --version)  Cinnamon 4.0.10
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used
 * 32 or 64 bit 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3081295/xsession-errors.txt)

**Issue**
Icon of application disappears (gets unpinned) from panel after having multiple windows of application open.
Happens with multiple applications, for example: Nemo, Chrome, Terminal, etc.

This disappearance is only temporary: If I press Alt+F2 and type 'r', the icon is pinned to the panel again, as it is supposed to.

**Steps to reproduce**
A screen recording of how to reproduce:
[screen_record.zip](https://github.com/linuxmint/cinnamon/files/3081316/screen_record.zip)

Steps to reproduce in text:
1. Have an application pinned to the panel (in this example Nemo).
2. Open this application.
3. Open another window of this application
4. Close the first window of this application.
5. Close the second window of this application.
6. The icon is now unpinned from the panel.

**Expected behaviour**
The icon of an application that is pinned to the panel, stays pinned, even after closing multiple windows of this application.

**Other information**
Effects are only temporary, as mentioned before.

**Comment by roadhazard** [comment] 2019-09-07 00:48
Came here to say I'm having the EXACT same problem. Fresh install of Mint Cinnamon 19.2. I'm also seeing this same problem on a fresh Arch install when using Cinnamon. In Mint 19.2, it shows my Cinnamon version as 4.2.4.

**Comment by smurphos** [comment] 2019-09-14 03:47
I think this is a duplicate of #8377

**Closed** 2019-09-14 07:55 UTC
