### ISSUE TITLE
There's a small strip above the taskbar that's unclickable

### ISSUE THREAD

**Issue by Ketchup901** [linuxmint/Cinnamon#6669] opened 2017-07-02 05:15 UTC
Maybe 20 pixels of space above the taskbar cannot be clicked. Moving a window into that space makes it impossible to click on that section of the window.

**Comment by leigh123linux** [comment] 2017-07-02 06:45
Can you post system info including theme details, also post ~/.xsession-errors.

**Comment by praveenp** [comment] 2017-07-06 03:27
This may be caused by margin using in the theme. Please see this [forum thread](https://forums.linuxmint.com/viewtopic.php?f=90&t=248787&p=1337024#p1337024).

**Comment by itzexor** [comment] 2017-07-06 05:28
Referencing https://github.com/linuxmint/cinnamon-spices-themes/pull/196

**Comment by Ketchup901** [comment] 2017-07-06 06:39
The "Desktop" theme is nightfall.
~/.xsession-errors doesn't exist.

**Comment by praveenp** [comment] 2017-07-06 12:49
Afraid this nightfall theme is not from [cinnamon spices environment](https://cinnamon-spices.linuxmint.com/themes). Could you verify?

**Comment by Ketchup901** [comment] 2017-07-07 05:29
I probably got it from "Add/remove desktop themes..." and then "Available themes (online)" from the theme settings.

There is indeed no problem with other themes, do you know of a very similar one I can use in the meantime?

**Comment by JosephMcc** [comment] 2017-07-07 06:21
The spices site was heavily reworked over the last couple of months. Part of this was removal of many broken and unmaintained things.

Since this issue is with the theme you are using and not actually a problem with Cinnamon itself I'm going to close this.

**Closed by JosephMcc** 2017-07-07 06:21 UTC
