### ISSUE TITLE
calibre crashes cinnamon

### ISSUE THREAD

**Issue by tpapp** [linuxmint/Cinnamon#5191] opened 2016-04-09 13:08 UTC
Running [calibre](https://calibre-ebook.com/download_linux) crashes cinnamon, which offers to restart, but then it keep crashing. Calibre version: latest, 2.54.0. Ubuntu/xenial, cinnamon 2.8.6-1ubuntu1amd64, Dell XPS 13 Skylake, kernel 4.5.0 (Ubuntu mainline).

**Comment by tpapp** [comment] 2016-04-09 14:43
Managed to capture some debug information from Cinnamon:
```
tamas@tamas ~ % cinnamon --replace
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Sat Apr 09 2016 16:38:56 GMT+0200 (CEST)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active
Window manager warning: Window 0x1c00004 (calibre) sets an MWM hint indicating it isn't resizable, but sets min size 16383 x 16383 and max size 2147483647 x 2147483647; this doesn't make much sense.
Window manager warning: Window 0x1c00004 (calibre) sets an MWM hint indicating it isn't resizable, but sets min size 16383 x 16383 and max size 2147483647 x 2147483647; this doesn't make much sense.
Window manager warning: Window 0x1c00004 (calibre) sets an MWM hint indicating it isn't resizable, but sets min size 16383 x 16383 and max size 2147483647 x 2147483647; this doesn't make much sense.

(cinnamon:18382): Cogl-ERROR **: Failed to create texture 2d due to size/format constraints
zsh: trace trap (core dumped)  cinnamon --replace
```
Calibre (in fact, one of its subprocesses) crashes too, with stack exhausted. While this could be a bug in Calibre primarily, an application still should not be able to crash Cinnamon.

**Comment by JosephMcc** [comment] 2016-04-24 12:12
The Cogl error is likely fixed by this commit here: https://github.com/linuxmint/muffin/commit/8fc6ff94fbe5e572fb335270338a526298258b86
Not sure if this will fix that crashing problem you are seeing.

**Comment by founderio** [comment] 2016-06-06 21:37
I also do get this issue here.  
Calibre also seems to have an insanely large window after the cinnamon crash.
Currently running on xenial, cinnamon 2.8.6 as well. The issue only started appearing after the 
upgrade to xenial.  
Same symptoms:
```
oliver@oliver-desktop:~$ cinnamon --replace
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Mon Jun 06 2016 23:34:41 GMT+0200 (CEST)
Cjs-Message: JS WARNING: [/home/oliver/.local/share/cinnamon/applets/devutils@fogl/applet.js 257]: assignment to undeclared variable s
Cjs-Message: JS WARNING: [/home/oliver/.local/share/cinnamon/applets/devutils@fogl/applet.js 258]: assignment to undeclared variable c
Cjs-Message: JS WARNING: [/home/oliver/.local/share/cinnamon/applets/devutils@fogl/applet.js 263]: assignment to undeclared variable out_reader
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active

(cinnamon:5155): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:5155): St-WARNING **: Did not find color property '-gradient-end'
Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1400006 specified for 0x1400004 (calibre).
Window manager warning: Window 0x140000d (calibre) sets an MWM hint indicating it isn't resizable, but sets min size 16383 x 16383 and max size 2147483647 x 2147483647; this doesn't make much sense.
Window manager warning: Window 0x140000d (calibre) sets an MWM hint indicating it isn't resizable, but sets min size 16383 x 16383 and max size 2147483647 x 2147483647; this doesn't make much sense.
Window manager warning: Window 0x140000d (calibre) sets an MWM hint indicating it isn't resizable, but sets min size 16383 x 16383 and max size 2147483647 x 2147483647; this doesn't make much sense.
Window manager warning: Window 0x140000d (calibre) sets an MWM hint indicating it isn't resizable, but sets min size 16383 x 16383 and max size 2147483647 x 2147483647; this doesn't make much sense.

(cinnamon:5155): Cogl-ERROR **: Failed to create texture 2d due to size/format constraints
Trace/breakpoint trap (core dumped)
```
Are there any hints on when the above commit hits the ubuntu repos?

**Comment by mtwebster** [comment] 2016-06-06 22:20
This sounds similar to https://github.com/linuxmint/Cinnamon/issues/4789.

That was fixed in muffin 2.8.5 - looks like you may be using 2.8.4 still judging from your Cinnamon version.

**Comment by founderio** [comment] 2016-06-07 13:25
Yes, looks like 2.8.4 is also the latest available for xenial:
http://packages.ubuntu.com/xenial/x11/muffin
You you think I can snag a 2.8.5 .deb from somewhere as a quick fix? (e.g.
here: http://packages.linuxmint.com/list.php?release=Rosa) Or do the ubuntu
maintainers do something "special"?

2016-06-07 0:20 GMT+02:00 Michael Webster <notifications@github.com>:

**Comment by JosephMcc** [comment] 2016-06-07 18:53
I'm closing this since the issue is fixed on our end. There isn't much we can do about the version for Xenial. You could build yourself or grab a newer version from one of the Cinnamon ppas.

**Closed by JosephMcc** 2016-06-07 18:53 UTC

**Comment by mtwebster** [comment] 2016-06-07 23:44
For 64 bit, you can try the packages here: https://github.com/linuxmint/Cinnamon/issues/4789#issuecomment-183171839, or the Rosa packages may work.

Debian packages that for Ubuntu, and you may end up with some packaging conflict or other - they rename one of muffin's packages from `gir1.2-muffin-3.0` to `gir1.2-meta-muffin-0.0` and cinnamon depends on one or the other.  If you grab Rosa's muffin packages, be sure to get the cinnamon packages as well (just cinnamon, cinnamon-common, cinnamon-doc, cinnamon-dbg - the last two aren't even strictly necessary).
