### ISSUE TITLE
[Feature Request] Gestures

### ISSUE THREAD

**Issue by DiggsAsura** [linuxmint/cinnamon#10493] opened 2021-12-01 21:12 UTC
Hi,

I'm sorry if I dont do this entirly as I should. Please feel free to correct me. 
I have been off Linux for about 10 years, mainly was a Mac user. However I got the urge to test it, and tested a bunch of distros last few months. Mint was the first one this time around, and its also what I have been running on my work computer now for the last month. Absolutly love it, great - great work!

From Mac there are a couple of things I definetly mean made my daily work much more productive (compared to Windows and Linux 10+ years ago). I'm running Macbook Pro's and I was very happy to see Cinnamons implementation of Hot corners. This is amazing, when you first used to it. 

However, the one thing I still miss, which I see other distros fix out of the box is the gestures. Would there be a chance to have this better implemented to the core of Cinnamon? Thats the only thing I really miss. Four finger swipe up for X action (my case was show my desktop), Four fingers down for Y action (show running apps/workspaces etc). And of course the two finger zoom (which is very smooth on Fedora and Zorin I beleive). 

I am currently running fully up to date 20.2 Cinnamon. 

Thank you for your effort.

**Comment by ItzSwirlz** [comment] 2021-12-04 16:02
Duplicate of #9760

**Comment by BL4-z** [comment] 2021-12-19 16:40
You can use https://github.com/JoseExposito/touchegg to get touchpad gestures working under cinnamon, I believe it is the same program Zorin OS uses for its gestures.

**Comment by LinuxOnTheDesktop** [comment] 2023-07-26 01:36
Doesn't Victoria (Mint 21.2) have gestures?

**Closed** 2023-07-26 01:45 UTC
