### ISSUE TITLE
meta key pulling up panel

### ISSUE THREAD

**Issue by atiredman** [linuxmint/cinnamon#9745] opened 2020-12-03 19:51 UTC
```
 * Cinnamon version: 4.8.0
 * Distribution: Manjaro
 * Graphics hardware *and* driver used: NVIDIA GeForce GTX 1660 Ti Mobile, driver version 455.45.01-2
 * 32 or 64 bit: 64 bit
 ```

**Issue**
Since upgrading to Cinnamon 4.8.0 pressing the meta key when the panel is set to Auto hide panel or Intelligently hide panel pulls up the entire panel rather than just the menu, it then takes a second to readjust the menus placement. I'm not sure if this is a bug or a feature, but I find it quite annoying. 

Downgrading to Cinnamon 4.6.7 fixes this issue and only opens the menu when the meta key is pressed.

**Steps to reproduce**
Upgrade to Cinnamon 4.8.0
Set your panel to Auto hide or Intelligently hide
Open a full screen program (if set to Intelligently hide)
Press the Meta/Super/Windows key

**Expected behaviour**
Menu opens without panel.

**Other information**
I have attached 2 GIFs showing the behaviour differences in 4.6.7 & 4.8.0

![cinnamon 4 6 7](https://user-images.githubusercontent.com/32468329/101080476-d6bc2680-3576-11eb-84a0-fcb8ae89f7b4.gif)
![cinnamon 4 8 0](https://user-images.githubusercontent.com/32468329/101080495-dae84400-3576-11eb-8c76-2d707e9f877d.gif)

**Comment by ItzSwirlz** [comment] 2020-12-04 23:47
I'm pretty sure by default that's the setting.

**Comment by JosephMcc** [comment] 2020-12-05 17:36
If I remember  correctly this behavior was changed because people complained that it only pulled up the menu and not the panel. We can't win on this one :)

**Comment by atiredman** [comment] 2020-12-16 05:21
> If I remember correctly this behavior was changed because people complained that it only pulled up the menu and not the panel. We can't win on this one :)

I know it sounds silly but this was the feature that led me to choose to use Cinnamon over Budgie or KDE as my DE of choice years ago, I really like to minimize the number of moving things on my screen as I find they pull my eyes away from what I'm working on. 

I sympathize with those that complained though, every workflow is different, and though I may not like it pulling up the panel is standard on every other desktop environment I have tried. Hopefully I can find a way to toggle it off when I do upgrade, for now 4.6.7 still works great.

**Comment by JosephMcc** [comment] 2020-12-28 05:54
Going to go ahead and close this. It's working as intended for now.

**Closed by JosephMcc** 2020-12-28 05:54 UTC
