### ISSUE TITLE
Workspace OSD is cut off at bottom

### ISSUE THREAD

**Issue by warwickmm** [linuxmint/cinnamon#12542] opened 2024-12-02 03:09 UTC
### Distribution

Arch

### Package version

Cinnamon 6.4.0

### Graphics hardware in use

Radeon 780M

### Frequency

Always

### Bug description

When the panel is placed at the top of the screen, the workspace OSD appears too low and the bottom of it is cut off.

![cropped](https://github.com/user-attachments/assets/2a9e1e17-495c-4808-b254-b35bfeff40e2)

### Steps to reproduce

Place the panel at the top of the screen.  Enable workspace OSD, and switch workspaces.

### Expected behavior

The entire workspace OSD should appear, with some margin between the bottom of the OSD and the edge of the screen.

**Comment by JosephMcc** [comment] 2024-12-02 03:16
Duplicate of https://github.com/linuxmint/cinnamon/issues/12540#issuecomment-2510258604

**Closed by JosephMcc** 2024-12-02 03:16 UTC
Labels: BUG
