### ISSUE TITLE
ALT+TAB issue

### ISSUE THREAD

**Issue by Jostino** [linuxmint/Cinnamon#6940] opened 2017-10-12 13:14 UTC
```
 

> * Cinnamon 3.4.6
>  * Linux Mint 18.2
>  **-display
>              description: VGA compatible controller
>              product: Broadwell-U Integrated Graphics
>              vendor: Intel Corporation
>              physical id: 2
>              bus info: pci@0000:00:02.0
>              version: 09
>              width: 64 bits
>              clock: 33MHz
>              capabilities: msi pm vga_controller bus_master cap_list rom
>              configuration: driver=i915 latency=0
>              resources: irq:50 memory:c1000000-c1ffffff memory:b0000000-bfffffff ioport:5000(size=64) memory:c0000-dffff
>  * 64 bit

 ```

When I press ALT+TAB both desktop show me only wallpaper, until i release the combination of buttons.

Simply press ALT+TAB and keep

I should see which app I can select

**Comment by NikoKrause** [comment] 2017-10-15 13:01
> Simply press ALT+TAB 

![screenshot-area-2017-10-15-145908](https://user-images.githubusercontent.com/8415124/31584973-7f6e9712-b1b9-11e7-8271-9133a51c2ca9.png)

How do you press ALT + TAB?

You have to press ALT first and keep it pressed! Then you do a short press on TAB.

**Comment by NikoKrause** [comment] 2017-10-15 13:02
See the first minute of this video on how to do this: https://www.youtube.com/watch?v=T2qaPWMG6Nc

**Comment by Jostino** [comment] 2017-10-15 13:12
I'm sorry @NikoKrause but is what I already do..

**Comment by NikoKrause** [comment] 2017-10-15 13:13
Maybe try to play with settings:
Open Menu -> Windows -> Alt-Tab

**Comment by Jostino** [comment] 2017-10-16 14:29
@NikoKrause I'm in the Windows settings but I don't find any ALT+TAB label or similar things

**Comment by Jostino** [comment] 2017-10-16 14:31
Ok @NikoKrause i've found the menù of the Alt-tab but changing the style the problem persists..

**Comment by JosephMcc** [comment] 2017-10-29 18:04
It works fine here as well. Are you using any custom themes or extensions? Alt-tab is a rather heavily used functionality. Since you are the only one reporting this type of issue something must have happened to your particular setup. Maybe post the contents of your ~/.xsession-errors after you've tried alt-tab and it failed.

**Comment by Jostino** [comment] 2017-11-02 14:25
Alt+tab is working well, the only problem is that I can't see the preview of what i'm selecting... But it's working well for the rest

**Comment by NikoKrause** [comment] 2017-11-02 14:34
Video or GIF?

**Comment by Jostino** [comment] 2017-11-02 14:41
Here you are
[video.zip](https://github.com/linuxmint/Cinnamon/files/1438168/video.zip)

**Comment by NikoKrause** [comment] 2017-11-02 15:02
Have you tried with Live USB/CD?
Wondering if something went wrong during the installation or configuration.

**Comment by Jostino** [comment] 2017-11-02 15:06
Sincerely, nope.
I've updated Mint from the previous version, I've update Cinnamon after that, and alt+tab disappeard.

**Comment by NikoKrause** [comment] 2017-11-02 15:15
Did you use some extensions, desklets, applets?
If so turn all of them off. Restart your machine. And try again.

**Comment by Jostino** [comment] 2017-11-03 08:06
I have only one error with DesktopCube@yare

`Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:156:13
Extension@/usr/share/cinnamon/js/ui/extension.js:115:5
loadExtension@/usr/share/cinnamon/js/ui/extension.js:450:25
init@/usr/share/cinnamon/js/ui/extensionSystem.js:108:9
_initUserSession@/usr/share/cinnamon/js/ui/main.js:262:5
start@/usr/share/cinnamon/js/ui/main.js:461:5
@<main>:1:31
---------------->
error t=2017-11-03T07:24:02.050Z [Extension "DesktopCube@yare"]: Error importing extension.js from DesktopCube@yare
error t=2017-11-03T07:24:02.051Z Could not load extension DesktopCube@yare
info t=2017-11-03T07:24:02.061Z Loaded extension opacify@anish.org in 9 ms
info t=2017-11-03T07:24:02.067Z loaded at Fri Nov 03 2017 08:24:02 GMT+0100 (CET)
info t=2017-11-03T07:24:03.581Z Loaded applet menu@cinnamon.org in 1479 ms
info t=2017-11-03T07:24:03.595Z Loaded applet show-desktop@cinnamon.org in 13 ms
info t=2017-11-03T07:24:03.713Z Role locked: panellauncher
info t=2017-11-03T07:24:03.714Z Loaded applet panel-launchers@cinnamon.org in 116 ms
info t=2017-11-03T07:24:03.735Z Loaded applet window-list@cinnamon.org in 20 ms
info t=2017-11-03T07:24:03.754Z Role locked: notifications
info t=2017-11-03T07:24:03.765Z Loaded applet notifications@cinnamon.org in 28 ms
info t=2017-11-03T07:24:03.877Z Loaded applet user@cinnamon.org in 103 ms
info t=2017-11-03T07:24:03.934Z Loaded applet removable-drives@cinnamon.org in 55 ms
info t=2017-11-03T07:24:03.984Z Loaded applet keyboard@cinnamon.org in 47 ms
info t=2017-11-03T07:24:04.083Z Loaded applet network@cinnamon.org in 95 ms
info t=2017-11-03T07:24:04.166Z Loaded applet sound@cinnamon.org in 81 ms
info t=2017-11-03T07:24:04.209Z Loaded applet power@cinnamon.org in 42 ms
info t=2017-11-03T07:24:04.236Z Loaded applet systray@cinnamon.org in 26 ms
info t=2017-11-03T07:24:04.308Z Loaded applet calendar@cinnamon.org in 70 ms
info t=2017-11-03T07:24:04.324Z Loaded applet windows-quick-list@cinnamon.org in 14 ms
info t=2017-11-03T07:24:04.324Z AppletManager.init() started in 2241 ms
info t=2017-11-03T07:24:04.329Z Cinnamon took 3562 ms to start
info t=2017-11-03T07:24:05.842Z Adding systray: alarm-clock (24x24px)
info t=2017-11-03T07:24:05.845Z Hiding systray: network
info t=2017-11-03T07:24:05.848Z Adding systray: remmina-icon (24x24px)
info t=2017-11-03T07:24:05.852Z Adding systray: blueman (24x24px)
info t=2017-11-03T07:24:05.855Z Adding systray: skypeforlinux (24x24px)
info t=2017-11-03T07:24:05.859Z Adding systray: shutter (24x24px)
info t=2017-11-03T07:24:06.163Z Adding systray: touchpad-indicator (24x24px)
info t=2017-11-03T07:24:07.383Z Resized alarm-clock with normalized size (16x16px)
info t=2017-11-03T07:24:07.383Z Resized remmina-icon with normalized size (16x16px)
info t=2017-11-03T07:24:07.384Z Resized blueman with normalized size (16x16px)
info t=2017-11-03T07:24:07.385Z Resized skypeforlinux with normalized size (16x16px)
info t=2017-11-03T07:24:07.385Z Not resizing shutter as it's known to be buggy (24x24px)
info t=2017-11-03T07:24:07.679Z Resized touchpad-indicator with normalized size (16x16px)
info t=2017-11-03T07:26:00.855Z Adding systray: rambox (24x24px)
info t=2017-11-03T07:26:02.149Z Adding systray: telegramdesktop (24x24px)
info t=2017-11-03T07:26:02.364Z Resized rambox with normalized size (16x16px)
info t=2017-11-03T07:26:03.665Z Resized telegramdesktop with normalized size (16x16px)
info t=2017-11-03T07:34:26.367Z Adding systray: mintupdate.py (24x24px)
info t=2017-11-03T07:34:27.873Z Resized mintupdate.py with normalized size (16x16px)
`

**Comment by JosephMcc** [comment] 2017-11-03 08:30
When you have issues, the first thing you should do is remove any 3rd party xlets and try again. See if they are the source of the issue.

**Comment by NikoKrause** [comment] 2018-02-02 22:44
Since we can't reproduce this issue, I'll close this now. I hope an update to LM18.3 or a fresh install has solved your issue.

**Closed by NikoKrause** 2018-02-02 22:44 UTC
