### ISSUE TITLE
Cinnamon crashes on display configuration

### ISSUE THREAD

**Issue by vpal** [linuxmint/Cinnamon#6314] opened 2017-02-24 20:37 UTC
I usually use my laptop with an external monitor and the laptop display is disabled.
Sometimes I would like to enable the laptop display as a secondary monitor in Cinnamon with the Display app.
When I hit apply first the output goes to the laptop screen, the "Keep this configuration" dialog does not appear.
Then after a few seconds (I guess when the "Keep this configuration" timer is up in the background) I see some stretched output on both displays.
I can move the mouse pointer but can't click r do anything with the keyboard.
Ctrl + Alt + Fn works.
All I can do is reboot with sysrq.

Before I was already able to apply the described setting after a few freezes and restarts.
So I would say it is intermittently working and pretty reproducible.

I can set the displays to be mirrored, that works.

Seem pretty similar to this: https://forums.linuxmint.com/viewtopic.php?t=224722

```
Details
=========================================
lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena
=========================================
Laptop model: Latitude E5550
=========================================
Lspci:
00:00.0 Host bridge: Intel Corporation Broadwell-U Host Bridge -OPI (rev 09)
00:02.0 VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09)
00:03.0 Audio device: Intel Corporation Broadwell-U Audio Controller (rev 09)
00:04.0 Signal processing controller: Intel Corporation Broadwell-U Camarillo Device (rev 09)
00:14.0 USB controller: Intel Corporation Wildcat Point-LP USB xHCI Controller (rev 03)
00:16.0 Communication controller: Intel Corporation Wildcat Point-LP MEI Controller #1 (rev 03)
00:19.0 Ethernet controller: Intel Corporation Ethernet Connection (3) I218-LM (rev 03)
00:1b.0 Audio device: Intel Corporation Wildcat Point-LP High Definition Audio Controller (rev 03)
00:1c.0 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #1 (rev e3)
00:1c.3 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #4 (rev e3)
00:1c.4 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #5 (rev e3)
00:1d.0 USB controller: Intel Corporation Wildcat Point-LP USB EHCI Controller (rev 03)
00:1f.0 ISA bridge: Intel Corporation Wildcat Point-LP LPC Controller (rev 03)
00:1f.2 RAID bus controller: Intel Corporation 82801 Mobile SATA Controller [RAID mode] (rev 03)
00:1f.3 SMBus: Intel Corporation Wildcat Point-LP SMBus Controller (rev 03)
01:00.0 SD Host controller: O2 Micro, Inc. SD/MMC Card Reader Controller (rev 01)
02:00.0 Network controller: Intel Corporation Wireless 7265 (rev 59)
=========================================
xrandr 
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected (normal left inverted right x axis y axis)
   1920x1080     60.05 +  59.93    48.04  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      59.89  
   1280x960      60.00  
   1368x768      60.00  
   1360x768      59.80    59.96  
   1152x864      60.00  
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   640x480       59.94  
   720x405       60.00  
   640x360       60.00  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.08    60.00  
   800x600       75.00    60.32  
   640x480       75.00    60.00  
   720x400       70.08  
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
=========================================
```

[xorg_logs.zip](https://github.com/linuxmint/Cinnamon/files/800411/xorg_logs.zip)

Xorg log attached.

**Comment by flavorjones** [comment] 2017-07-04 04:26
This *might* be a dupe of #6224?

**Comment by vpal** [comment] 2017-07-04 08:57
@flavorjones Very likely.

**Closed** 2018-02-01 10:03 UTC
Labels: BUG
