### ISSUE TITLE
memory leak in cinnamon 2.0.14 when opening/destroying windows

### ISSUE THREAD

**Issue by austin987** [linuxmint/Cinnamon#2986] opened 2014-03-29 19:30 UTC
I've noticed that running the wine (https://www.winehq.org) unit tests cause cinnamon to take up a lot of memory usage. I decided to test it with a short script:
# !/bin/bash

while true ; do
xeyes & sleep 1 & killall xeyes
done

I restarted cinnamon (low cpu/memory usage, then started the script) After 7 hours, I came back to this:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND  
19669 austin    20   0 6352952 3.854g  15932 S   6.4 68.1 147:17.65 cinnamon       

3.85G of memory / 69% !

cinnamon --replace serves as a workaround.

**Comment by greyfade** [comment] 2015-01-06 00:10
I can confirm this is happening on Cinnamon 2.4.

    $ cinnamon --version
    Cinnamon 2.4.5

I've been trying to track down what exactly is causing memory usage by Cinnamon on my system to balloon from 600MB to well over 2GB in the course of a few days. This seems to be the biggest factor, as I can watch the resident memory count rise while running @austin987's scriptlet. I can also reproduce it by summoning [Synapse](https://launchpad.net/synapse-project) (which I use frequently) and closing it repeatedly.

As the memory consumption rises, also, Cinnamon becomes increasingly sluggish and moving windows around (*especially* OpenGL programs) has a tendency to temporarily lock my display. This doesn't happen with any other window manager I have on my system.

**Comment by austin987** [comment] 2015-01-06 00:13
On Jan 5, 2015 6:10 PM, "Charles Banas" <notifications@github.com> wrote:
>
> I can confirm this is happening on Cinnamon 2.4.
>
> $ cinnamon --version
> Cinnamon 2.4.5
>
> I've been trying to track down what exactly is causing memory usage by
Cinnamon on my system to balloon from 600MB to well over 2GB in the course
of a few days. This seems to be the biggest factor, as I can watch the
resident memory count rise while running @austin987's scriptlet. I can also
reproduce it by summoning Synapse (which I use frequently) and closing it
repeatedly.
>
> As the memory consumption rises, also, Cinnamon becomes increasingly
sluggish and moving windows around (especially OpenGL programs) has a
tendency to temporarily lock my display. This doesn't happen with any other
window manager I have on my system.
>
> —
> Reply to this email directly or view it on GitHub.

I won't be able to test this for a week or so, but oprofile or valgrind may
be helpful in tracking down the leak.

**Comment by anandrkris** [comment] 2015-01-14 07:30
https://github.com/linuxmint/Cinnamon/issues/3796
https://github.com/linuxmint/Cinnamon/issues/3736
Linking related defects.

**Comment by NeoGeo64** [comment] 2015-01-24 20:25
Hello all.

Cinnamon has been a buggy, glitchy mess for a while now.  The funny thing is that the developers swear that it's the user's fault and that nothing is wrong with Cinnamon.  I have had memory issues with Cinnamon also.  After about a week of uptime my Cinnamon RAM usage is sitting around 300MB.  When I boot it's around 70MB and right now (after just two days uptime) Cinnamon's RAM usage is at 163.3.

Cinnamon has a lot of other minor glitches and bugs that no one seems to be able to fix or at least figure out what's going on.  But plenty of users, including me, have experienced these glitches.  I would love to know the hardware/software setup of these developers so I can experience the magic of no crashing on Linux Mint 17.1.

Really, though, the developers can deny it all they want.  I have a better idea.  Switch distros and forget about it.

Fix y'alls shit.  Damn.

**Comment by tylery71** [comment] 2015-01-26 19:39
@NeoGeo64 
Having used cinnamon for a few years now, the fact it has recently become unstable with its memory does not equal "a buggy, glitchy mess". In fact, fixing bugs often has the side effect of introducing new bugs. 

> "The funny thing is that the developers swear that it's the user's fault and that nothing is wrong with Cinnamon."

Where exactly did they say that?

> "As users we're always told we're "doing something wrong" when we're just using our computer and Linux distro normally. I don't hack and I don't install a ton of random programs, plug-ins or addons. "

Not sure how you use your computer & distro "normally" but in my experience, hacking & installing random programs, plugins & addons IS normal in linux. The LM team has done a amazing job (in large part of course to Ubuntu & Debian) at making Linux accessible to practically anyone. But if you really want a UI that requires 0 involvement by the user, Mac & Windows specifically cater to this.

I am curious how users are "doing something wrong". In almost every case I've ever read that, it's because the "right" way will improve security / easier to read / more efficent / considered best practice / educate the user / etc. Yes.. RTFM is a harsher way of communicating that, but linux is about knowing how to fish, not getting handouts.

**Comment by mtwebster** [comment] 2015-01-26 20:03
I'm pretty sure no developers have said 'you're doing it wrong' - don't confuse frequent-posters with developers.

What we have said, *repeatedly*, is that everyone has a different workflow - I may do stuff that never gets me around the code or logic that's causing a freeze, while Joe User encounters it daily.  That's why we need information - what were you doing, what programs, do you use expo, do you alt-tab alot, etc... and some problems, honestly, are not going to be fixed, because the issue lies with things out of our control.

If you guys really feel like you're being ignored, feel free to move on to greener pastures.  Personally I hate spending days or weeks on a problem, while daily seeing complaints that we're ignoring the issue, or blaming users - real motivational stuff there.  Not everything is simple, not everything can be fixed in 10 minutes.  Conversely, some of the most annoying bugs are often fixed with 1 line changes (after spending days finding that line!).

There's no such thing as bug-free software - get used to it.

**Comment by NeoGeo64** [comment] 2015-01-27 17:58
I appreciate your candid response.  The thing is, with Linux Mint, it is 
a nice distro.  As users, we recognize that fact and that is why we have 
chosen to use not just any Linux distro - but Linux Mint.  I didn't mean 
to offend anyone.  The main thing that's been going on with Mint are 
memory issues.  If that could be fixed, it would be golden.  But even 
with Mint's "quirks" I will continue to use it.  I understand that 
software is complex.  Also, regarding your comment on some bugs are easy 
to fix by changing one line -- the problem is finding that one line -- 
I've totally been there before lol

**Comment by NeoGeo64** [comment] 2015-01-27 18:13
Knowing how to fish?  The majority of Linux users are at the mercy of 
the developers.  We can't program or read code.  Our trust is put into 
your hands.  When we have a problem all we can do is report it.  You 
guys are helpful and we do appreciate it.

**Comment by tylery71** [comment] 2015-01-27 19:45
>The majority of Linux users are at the mercy of the developers. We can't program or read code. Our trust is put into your hands. When we have a problem all we can do is report it. You guys are helpful and we do appreciate it.

I want to clarify, there are people who say that you should be able to read all source code & fix your own problems before complaining. You seemed to perceived it this way & it wasn't my point.
Knowing "how to fish" means to learn Linux. Knowing how to navigate the file-system, fix common troubleshooting errors and most importantly - be able to give effective bug reports to dev's so that they *can* fix the bug. Windows may not require you to know this, but this is not windows.
Statements like 
>Cinnamon has been a buggy, glitchy mess for a while now.
> The funny thing is that the developers swear that it's the user's fault and that nothing is wrong with Cinnamon. 
> I would love to know the hardware/software setup of these developers so I can experience the magic of stability.
>  I'm serious about to give up on this distro. .. Here is my post about it in the LInux Mint forums (as if it would help)

are not cool. As a fyi, threats to abandon a distro do not carry much weight.

>Well, has anyone else been having this issue or perhaps hacked up a fix for now?

You received a response from mtwebster the same day you posted this, inviting users to test the nightly build noting that some related fixes had been applied *and* that it will be provided to users soon. Then you posted the above.

> I didn't mean to offend anyone.

What was your intent then? Because it looks like you were trying to get the message across that the dev's don't care & don't listen. Which you know is not true.

> A lot of us are Windows converts and get frustrated when things break in the OS that the average user can't fix with a few clicks (or commands).

I suggest you read this. Please take the time to consider what it says.
http://linux.oneandoneis2.org/LNW.htm

**Comment by Vahan86** [comment] 2016-11-20 15:41
@austin987, is this still an issue for you in Cinnamon 3.0?

**Comment by austin987** [comment] 2016-11-22 01:17
@Vahan86, yes:
After a few minutes of running:
austin   17964  6.5  1.5 1834856 255236 ?      Sl   21:13   0:07 cinnamon --replace
About 20 hours after starting:
austin   17964  5.9 17.9 4455416 2930832 ?     Sl   Nov20  77:57 cinnamon --replace

FYI, I'm no longer running cinnamon because of this bug. I reinstalled to test, but this is super easy to reproduce with the script I posted previously:
`#!/bin/bash
while true ; do
xeyes & sleep 1 && killall xeyes
done`

`austin@debian-desktop:~$ cinnamon --version
Cinnamon 3.0.7`

**Comment by austin987** [comment] 2016-11-28 06:18
Hi cinnamon devs,

It's unclear to me if any of you are able to reproduce this issue. While I don't mind installing cinnamon to retest, I don't think the bug is likely to ever be fixed if no one else can reproduce it. Could someone confirm that the xeyes script I gave also shows the issue for them, in 3.x? Keep in mind you'll need to run it for a few hours (at least) to see the issue.

I could help to debug this, if someone tells me what would be helpful. This bug has been around for 2.5 years, with no attempt to fix AFAICT, even though this is a memory leak that can cause the program to crash and the user to lose data. As a FOSS developer, I understand there are limited resources, but I would also think that bugs such as this would get a higher priority. At the least, when there's a trivial testcase, developers should try it before asking a user to retest years later..

**Comment by Lourens-Rich** [comment] 2016-11-28 21:10
Distro: Arch Linux
Cinnamon: 3.2.1

Leak confirmed.

**Comment by kulga** [comment] 2016-12-06 04:39
Distro: Linux Mint 18 Cinnamon
Cinnamon 3.0.7

Leak confirmed..

___

If you use ```top -p cinnamon_pid``` it's pretty easy to watch it climb while opening xeyes over and over.

**Comment by Psykar** [comment] 2016-12-09 05:34
I've got a pretty simple repro here:
Every run will increase cinnamon RAM usage by between 10-50MB. This continues well into the GB of ram usage by Cinnamon.
```bash
#!/bin/bash
if [ ! -f ./test.png ]; then
    convert -size 6000x6000 xc:white test.png
fi
for loop in {0..100}
do
    xviewer ./test.png & 
    sleep 0.5
    killall xviewer
done
```

**Comment by leigh123linux** [comment] 2017-12-17 21:46
Closed

Duplicate of #6850

**Closed by leigh123linux** 2017-12-17 21:46 UTC
Labels: BUG
