### ISSUE TITLE
Online accounts: cant connect to google

### ISSUE THREAD

**Issue by tothpsk** [linuxmint/cinnamon#7321] opened 2018-03-02 22:29 UTC
...
 * Cinnamon version 3.6.7
 * Distribution Mint 18.3 Cinnamon
 * Intel 2nd Generation Core Processor Family Integrated Graphics Controller, NVIDIA GF108M [GeForce GT 540M]
 * 64 bit
 ```

**Issue**
I cant use online accounts in Linux Mint. I want to connect my Google Drive with Nemo. So I open "online accounts" and click on Google. After that popup window appears with error message "Error resolving 'http': Name or service not known".



**Steps to reproduce**
1. open Online accounts
2. clicking on Google leads to "Error resolving 'http': Name or service not known"


**Expected behaviour**
successful connection of Nemo with Google Drive


**Other information**
![vyber_048](https://user-images.githubusercontent.com/11166910/36925130-8c3c9d34-1e71-11e8-94b0-0d6b396b7f1e.png)

**Comment by CottonEaster** [comment] 2018-12-08 02:33
I have the same problem. Also, I was faced with the following unhelpful window (well, it's unhelpful unless there is a button missing due to a theme problem):

![image](https://user-images.githubusercontent.com/9998846/49680861-94e46c80-fa91-11e8-914b-353cb410db7c.png)


Having Google Drive integration not working on Mint, together with Dropbox not working (see e.g. [this bug report](https://github.com/linuxmint/Cinnamon/issues/7235) - it is not the only one) and indeed - in my experience too - syncthing not working, does rather limit things for users.

**Comment by icarter09** [comment] 2019-11-16 15:27
Linux Mint 19.2
Cinnamon 4.2.4

@tothpsk I'm not able to reproduce the issue you are having. 

@ghost I agree with your comment. It would be nice to have Google Drive listed there and also the window isn't the most helpful since there is no "confirmation" button. Having only a "Remove Account" button can be confusing.

**Comment by tothpsk** [comment] 2019-11-17 08:48
@icarter09 With the Linux Mint 19.2 (everything updated until 17th of November 2019) I am able to use online accounts. As far as I remember a year ago, when clean install of Linux Mint, it was possible to set up online accounts. Later on I got the the error "Error resolving 'http': Name or service not known" clicking on Google account.

**Comment by icarter09** [comment] 2019-11-18 03:42
@tothpsk thanks for the update. I'm going to close this issue since it sounds like it has been fixed.

**Closed by icarter09** 2019-11-18 03:42 UTC
Labels: FEATURE REQUEST
