### ISSUE TITLE
Window focus will not follow mouse

### ISSUE THREAD

**Issue by unlimitedbacon** [linuxmint/Cinnamon#3782] opened 2014-12-23 22:56 UTC
I have a machine here running Cinnamon on Linux Mint 17.1. Setting the window focus mode to "Sloppy" or "Mouse" has no effect. You still need to click on a window to focus it.

**Comment by ams001** [comment] 2015-06-29 16:53
I have the same issue.  Very annoying since I am so used to sloppy mode on all my laptop.

**Comment by ManIVIctorious** [comment] 2016-09-05 16:32
Can't reproduce here, is this still an issue in cinnamon 3.0?

**Comment by JosephMcc** [comment] 2016-09-05 18:09
I can't reproduce this either. I always use "sloppy". Closing for now.

**Closed by JosephMcc** 2016-09-05 18:09 UTC
Labels: BUG
