### ISSUE TITLE
Cinnamon is laggy with a second display

### ISSUE THREAD

**Issue by kogans** [linuxmint/cinnamon#8071] opened 2018-11-26 19:09 UTC
```
 * Cinnamon 4.0.2
 * Fedora 29
 * NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1)
 * Graphics driver: nvidia-driver-415.18-2.fc29.x86_64
 * 64 bit
 ```
When connecting a second monitor, cinnamon starts ti consume a lot of CPU and the rendering performance of the desktop substantially decreases.

The problem appeared after upgrading to F29 from F27.

**Comment by jaszhix** [comment] 2018-11-27 10:53
I have three monitors with different refresh rates and not seeing much lag. I use an optimus laptop with a second display as well. You could try running `CLUTTER_SHOW_FPS=1 cinnamon --replace`, and compare the results before and after attaching a second monitor. The output will be in ~/.xsession-errors, which I recommend attaching to this issue, and /var/log/Xorg.0.log.

Performance issues can have many different causes, so its good practice to provide as much info as possible. There isn't really enough here to reproduce anything. Its worth keeping in mind that the compositor has undergone a lot of changes, and some of the driver workarounds for 3.8 don't apply to 4.0 (#7985 as one example).

Also wrote up some [performance tips for 4.0](https://github.com/linuxmint/Cinnamon/wiki/Performance-Tips) that you might want to consider, based on my own experience.

**Comment by kogans** [comment] 2018-11-27 16:49
OK, so I enabled the setting and there is a marked decrease in the FPS when I attach the second monitor.

Normally, if I drag the window around the FPS goes up to 60+, while with the second screen connected it stays at below 20.

Note: I don't have any driver workarounds enabled - 3.8 worked fine for me out of the box.

[xsession-errors.log](https://github.com/linuxmint/Cinnamon/files/2620932/xsession-errors.log)
[Xorg.0.log](https://github.com/linuxmint/Cinnamon/files/2620944/Xorg.0.log)

**Comment by jaszhix** [comment] 2018-11-27 21:33
Thanks. One potential optimization for you - if you're the visual display mode in the workspace switcher applet, switching that to simple buttons will reduce overhead when dragging windows. The reason for this is because it calls back a JS function every time the window moves a pixel to paint the representation of the windows in the panel.

From Xorg.0.log:

``` [    10.491] (**) NVIDIA(0): Option "AllowUnofficialGLXProtocol" "on"```

You could try disabling this, along with these removing options, which are usually disabled anyway:

```
[    10.491] (**) NVIDIA(0): Option "Stereo" "0"
...
[    10.491] (**) NVIDIA(0): Option "SLI" "Off"
[    10.491] (**) NVIDIA(0): Option "MultiGPU" "Off"
[    10.491] (**) NVIDIA(0): Option "BaseMosaic" "off"
```

Also see this in your kernel boot parameters:

```
nvidia-drm.modeset=1
```

If you're using PRIME sync, you should be able to disable VBlank in Cinnamon settings -> General, and still not have tearing. Otherwise it would be adding more overhead.

**Comment by jaszhix** [comment] 2018-11-28 15:35
Did you try disabling `AllowUnofficialGLXProtocol`? That is a driver work-around that you have to enable on both the X server and in the driver through an environmental variable or application profile in nvidia-settings. 

Clutter's benchmark can tell you the FPS when its painting and could give a vague idea, but its not going to be able to tell you how responsive the compositor is, since its only one library used by Muffin. FYI, there's an [upstream fix ](https://gitlab.gnome.org/GNOME/mutter/merge_requests/154) to make Clutter's FPS benchmark more accurate.

Mixed monitor refresh rates might also play a role - muffin uses those to send frame timing to the X server.

**Comment by kogans** [comment] 2018-12-03 16:36
I'm happy to report that the problem is gone. I'm not exactly sure what, specifically fixed it, because there was an update to the nVidia driver over the weekend and I also set AllowUnofficialGLXProtocol to "off".
I'm going to do some testing later today to see what actually did it.

**Comment by Vahan86** [comment] 2020-02-16 19:57
@kogans, can we close this ticket or it is still an issue with Cinnamon 4.4?

**Closed** 2020-04-04 23:35 UTC
