### ISSUE TITLE
Touchegg .xprofile and Cinnamon

### ISSUE THREAD

**Issue by tsusanka** [linuxmint/Cinnamon#5361] opened 2016-06-07 11:23 UTC
I'm using [touchegg](https://github.com/JoseExposito/touchegg) - a touchpad gesture recognition program. After a recent update of my system, the gesture recognition seized to work.

The solution on Ubuntu [should](https://github.com/JoseExposito/touchegg/issues/273) be to start the software

> before gnome-shell, e.g. via .xprofile.

However, that doesn't work for cinnamon. Is there someting similar as gnome-shell or is that GNOME only? Is there a similar concept how to start touchegg before it?

Thank you for any help and big thanks for Cinnamon!

**Comment by leigh123linux** [comment] 2017-08-12 08:29
Duplicate of https://github.com/linuxmint/Cinnamon/issues/5497

**Closed by leigh123linux** 2017-08-12 08:29 UTC
Labels: FEATURE REQUEST
