### ISSUE TITLE
Translation issue in the enable/disable gestures in brazilian portuguese.

### ISSUE THREAD

**Issue by Luiz-Trindade** [linuxmint/cinnamon#12122] opened 2024-03-16 23:59 UTC
The issue is in the word "disativados", the correct word is "desativados". That's the equivalent to write "dosabled" instead of "disabled". I don't know if there is the correct place to tell an translation issue, but i'm trying to help. 

![captura_de_tela](https://github.com/linuxmint/cinnamon/assets/149267777/82db5d24-aeaa-4036-b01c-68295d0de1a6)

**Comment by rcalixte** [comment] 2024-03-17 02:37
Translation are done via Launchpad. This string in particular is [here](https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/pt/+translate?batch=10&show=all&search=gestures). You can try to fix it yourself if you want. It may be worth a conversation with @hugok79 about it too. Feel free to close this Issue once it's been resolved.

**Comment by hugok79** [comment] 2024-03-17 09:47
@Luiz-Trindade @rcalixte
The `Portuguese (pt)` translation is correct, which is my translation. The problem is with the `Brazilian Portuguese (pt_BR)` translation, which is not done by me.
I have already made a suggestion to correct that typo because i'm not part of the brazilian translation team
This was the last brazilian translator to translate https://launchpad.net/~alberlan Try to reach him

**Comment by rcalixte** [comment] 2024-03-17 10:28
Sorry about the mix-up. I can't seem to find a GitHub account but thank you for already nudging with the suggestion. Let's hope it gets fixed soon.

**Comment by rcalixte** [comment] 2024-03-17 10:59
I've found an account for another translator on the team who can hopefully make the change as well.

cc @eco-star

**Comment by eco-star** [comment] 2024-03-28 17:05
Hello mates, 
there already was a new translation, which I reviewed and applied in launchpad.
Thank you for mentioning me @rcalixte :)

**Comment by rcalixte** [comment] 2024-03-28 17:11
Thank you for making the correction @eco-star and thank you @Luiz-Trindade for opening the issue! This will likely end up in Mint 22.0/Cinnamon 6.2.

**Closed by rcalixte** 2024-03-28 17:11 UTC
