### ISSUE TITLE
Calendar applet's support for vertical panels is unfinished (and glitchy)

### ISSUE THREAD

**Issue by mbazley** [linuxmint/cinnamon#6137] opened 2016-12-28 14:43 UTC
See thread: https://forums.linuxmint.com/viewtopic.php?f=208&t=236185&p=1257947#p1257947

I think [this image](http://i.imgur.com/XiuSIyH.png) speaks for itself.

Currently, there is no way to get the calendar to show the date on a vertical panel without using a custom format string.  It ignores the "Display the date" option in the "Date and Time Settings" button offered from the applet's menu - bug number 1.  (Possibly a feature request.)

This situation is worsened by the fact there is no reasonable way to use a custom format string on a vertical panel.  Firstly, I can't find any way to define newlines, thus making the custom format have less functionality than the default one (bug number 2).  But even if it were possible, the default settings already change depending on the orientation of the panel, so why not have the ability to define two format strings - one for horizontal, and one for vertical?  (Bug/feature request number 3.)

Finally (and fourthly), there is the effect that using overlong custom format strings currently has, but I'm going to report that one separately because it's mostly a bug with the panel itself and not just the calendar.

**Comment by leigh123linux** [comment] 2016-12-28 15:49
duplicate of https://github.com/linuxmint/Cinnamon/issues/6109

**Comment by mbazley** [comment] 2016-12-28 18:12
I don't appreciate this issue being closed in favour of an issue that was also closed with no resolution.  I concede that it turns out it *is* possible to insert newlines, although arguably the lack of documentation on how to do so is a bug in its own right.

> It ignores the "Display the date" option in the "Date and Time Settings" button offered from the applet's menu - bug number 1.

This is still a bug.

> why not have the ability to define two format strings - one for horizontal, and one for vertical?

This is still a feature request.

The other bug - lack of sanity checking on icon alignment - is still a bug, and still causes redraw glitches.

Are you announcing your intention to ignore them?

**Comment by leigh123linux** [comment] 2016-12-29 11:42
> Are you announcing your intention to ignore them?

The devs are aware of the issues and don't need multiple duplicate reports

**Comment by mbazley** [comment] 2016-12-29 18:35
They do need at least one, though.  Have you not noticed the other one was closed?

If it had not been closed, I would have noticed it when I skimmed the bug list for vertical panel-related issues a couple of days ago, as users are supposed to do before reporting potential duplicate bugs.  Furthermore, there's now nothing to stop somebody else making the exact same mistake in the future.

And this is supposed to be a bug *tracker*, after all.  Do the devs just hold all of the bugs in their heads?

**Comment by leigh123linux** [comment] 2016-12-29 19:47
The devs have a private thread on slack for cinn-vertical-panels and it's issues.
If it makes you happy I will reopen it.

**Comment by brownsr** [comment] 2016-12-30 08:42
@mbazley When I originally wrote the vertical panel changes for the calendar applet I quickly realised that the options for what clock would physically show in the panel were very limited.  I decided to use a single locked format as the alternative was simply to disallow use of the calendar in a vertical panel.  Subsequently we extended this so that people who were happy trying custom formats could do so.  The default format in a vertical panel is %H%n%M by the way, the way to get a newline in is with the %n.  You do get some very strange things happen in a vertical panel if the applet is wider than the panel - everything centre aligns to the central position of the widest applet in a panel section.  (That's why I went with a locked format in the first place).  The applet is not trimmed to avoid this because it is readily correctable by the user [i.e. use of a custom date format that actually fits].  

I appreciate that some people will feel really strongly about wanting to see a full length date/time string, but the width of the panel is a fundamental constraint.  The only way I can see a visually pleasing result being obtained with an over-long date string is to a) use a theme that has a completely transparent panel [I came across a couple like this] b) put the calendar applet in a panel section [top, middle, bottom] entirely on its own.  Do experiment along those lines if that will suit you.

**Comment by mbazley** [comment] 2016-12-30 15:07
I've [been experimenting](http://i.imgur.com/3F4xYpo.png).  Would be nice if there was a way to change the time to see how it copes with 22:22, but the "Use network time" off switch has no effect.  I can change the time all I like, and it just snaps back a second later without ever reaching the panel.

The principle bug here is actually the other one, #6138 (or #6109), which you say you encountered and had to work around.  That was actually what moved me to report a bug in the first place.  The icons disappeared without it being at all obvious where they had gone or what was causing this.  If all that had happened was that the calendar went off the screen, I'd had known what was going on and how to fix it.  The correct behaviour is to align to the widest applet **or the panel width if this is smaller**.

Still, at least I found out about the secret undocumented %n option, without which I wouldn't have been able to work out a satisfactory solution anyway.  I might put in a PR to remove the link to foragoodstrftime.com (which itself links to a site that has since vanished) and replace it with inline documentation, since it doesn't seem like that much work.  Lots of translation though...

The other suggestion, to have two configurable format strings, stands as well.  This would make more sense, as the default vertical format string is a special case whereas the default horizontal one is also the default custom.  This would provide an illustration of the use of %n too.

**Comment by inferno596** [comment] 2017-04-13 22:58
Why don't you just change the date/time format to %H%n%M (or in my opinion preferably %I%n%M) automatically when switching to a vertical taskbar? That seems simple to implement and seems like it would make everyone involved happier.

**Comment by shred** [comment] 2017-11-19 15:26
I don't know if this is related, or if I should open a separate bug.

I use the calendar in a **horizontal** panel with a custom format (`%a %d.%m. %H:%M:%S`). After I updated to cinnamon-3.6.0-1.fc27, the calendar ignores my custom format, or anything else I type into the format configuration. As soon as I turn on custom format, it seems to use a hardcoded `%H%n%M`, which looks rather ugly on a horizontal pane.

Removing and re-adding the calendar applet to the panel did not resolve this problem.

**Comment by mtwebster** [comment] 2017-11-19 16:13
Not sure why that would occur for you in that version, 3.6.3 introduced a bug that caused that, and it has been fixed for the next point release

**Comment by mtwebster** [comment] 2017-11-19 16:18
For the main topic of this issue, honestly I think the only way to make the time/date look good on a vertical panel would be to make a separate applet, with different configuration controls - I'm thinking 2 configurable lines instead of one, and a smaller font.

**Comment by shred** [comment] 2017-11-19 16:28
Yes, what I meant was that I updated *from* cinnamon-3.6.0-1.fc27 *to* cinnamon-3.6.3-1.fc27.

**Comment by Vahan86** [comment] 2020-01-19 18:31
Still an issue in Cinnamon 4.4.8.

**Comment by brownsr** [comment] 2020-01-19 20:34
I don't honestly think there is a bug here now.  The default format fits both styles of panel.  If you choose a custom string then it's over to you.  Choose too long a custom string in a vertical panel and it will be truncated.  That appears to be a well behaved outcome.  So I am not convinced there is either a bug or even a well defined feature request here.  Closing.

Regards

Simon

**Closed by brownsr** 2020-01-19 20:34 UTC
Labels: BUG REPRODUCED
