### ISSUE TITLE
[BUG] Cinnamon crash when clicking window list window preview (Clutter-CRITICAL)

### ISSUE THREAD

**Issue by mcarans** [linuxmint/cinnamon#11086] opened 2022-08-19 02:40 UTC
```
 * Cinnamon version (cinnamon --version) 5.4.10
   - Please specify if you are using the daily builds PPA - No
 * Distribution - Mint 21
 * Graphics hardware *and* driver used - Intel Iris XE
 * 32 or 64 bit - 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/9378784/xsession-errors.txt)

### Issue
Cinnamon sometimes crashes when I click a window list window preview

### Steps to reproduce
1. Open applications
2. Go to the bottom menu bar
3. Hover on an application so that its window preview shows
4. Click the window preview

### Expected behaviour
No crash

### Other information
I upgraded from 20.3 to 21

I see things like this in .xsession-errors:
```
(cinnamon:3227): Clutter-CRITICAL **: 14:18:08.853: clutter_actor_get_allocation_box: assertion 'CLUTTER_IS_ACTOR (self)' failed
**
Clutter:ERROR:../clutter/clutter/clutter-actor.c:1419:clutter_actor_set_mapped: assertion failed: (CLUTTER_ACTOR_IS_MAPPED (self))
Unable to open desktop file /usr/share/applications/caja-browser.desktop for panel launcher: No such file or directory
Unable to open desktop file /usr/share/applications/mate-terminal.desktop for panel launcher: No such file or directory
mutter-Message: 14:18:19.984: Enabling experimental feature 'x11-randr-fractional-scaling'
```

Some info from inxi in case needed:
```
Kernel: 5.15.0-46-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    Desktop: Cinnamon 5.4.10 tk: GTK 3.24.33 wm: Mutter 42.2 vt: 7
    dm: LightDM 1.30.0 Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
...
Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] vendor: ASUSTeK
    driver: i915 v: kernel ports: active: HDMI-A-1 off: eDP-1 empty: DP-1
    bus-ID: 0000:00:02.0 chip-ID: 8086:9a49 class-ID: 0300
  Device-2: IMC Networks USB2.0 HD UVC WebCam type: USB driver: uvcvideo
    bus-ID: 3-6:5 chip-ID: 13d3:56a2 class-ID: 0e02 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 2560x1440 s-dpi: 96 s-size: 677x381mm (26.7x15.0")
    s-diag: 777mm (30.6")
  Monitor-1: HDMI-1 mapped: HDMI-A-1 model: BenQ GW2765 serial: <filter>
    res: 2560x1440 hz: 60 dpi: 109 size: 597x336mm (23.5x13.2")
    diag: 686mm (27") modes: max: 2560x1440 min: 720x400
  OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2) v: 4.6 Mesa 22.0.5
    direct render: Yes
```

**Comment by nalmada** [comment] 2022-08-19 13:01
I have the issue as well

```
Gjs-Message: 14:53:02.389: JS LOG: About to start Cinnamon
Gjs-Message: 14:53:02.426: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 33 ms
Gjs-Message: 14:53:02.429: JS LOG: [LookingGlass/info] loading user theme: /home/home/.themes/Orchis-grey-light/cinnamon/cinnamon.css
Gjs-Message: 14:53:02.443: JS LOG: [LookingGlass/info] added icon directory: /home/home/.themes/Orchis-grey-light/cinnamon

(cinnamon:56961): St-WARNING **: 14:53:02.481: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:02.481: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:02.503: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:02.503: parse_shadow_property: default case
Gjs-Message: 14:53:02.760: JS LOG: [LookingGlass/info] loaded at Fri Aug 19 2022 14:53:02 GMT+0200 (heure d’été d’Europe centrale)
Gjs-Message: 14:53:02.761: JS LOG: Cinnamon started at Fri Aug 19 2022 14:53:02 GMT+0200 (heure d’été d’Europe centrale)
Gjs-Message: 14:53:02.761: JS LOG: GPU offload supported: false
Gjs-Message: 14:53:02.772: JS LOG: [LookingGlass/info] DeskletManager started in 1 ms
Gjs-Message: 14:53:02.772: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms

(cinnamon:56961): St-WARNING **: 14:53:02.790: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:02.790: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:02.791: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:02.791: parse_shadow_property: default case
Gjs-Message: 14:53:02.890: JS LOG: [LookingGlass/warning] [blur-overview@nailfarmer.nailfarmer.com]: Missing property "url" in metadata.json
Gjs-Message: 14:53:02.946: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 55 ms
Gjs-Message: 14:53:02.952: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 6 ms
Gjs-Message: 14:53:02.956: JS LOG: [LookingGlass/info] Role locked: tray
Gjs-Message: 14:53:02.959: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 7 ms
Gjs-Message: 14:53:02.968: JS LOG: [LookingGlass/info] Loaded applet notification-mute@jgillula in 9 ms
Gjs-Message: 14:53:02.974: JS LOG: [LookingGlass/info] Loaded applet expo@cinnamon.org in 6 ms
Gjs-Message: 14:53:02.975: JS LOG: [LookingGlass/info] Loaded extension blur-overview@nailfarmer.nailfarmer.com in 1 ms
Gjs-Message: 14:53:02.980: JS LOG: [LookingGlass/info] Loaded applet scale@cinnamon.org in 5 ms
Gjs-Message: 14:53:02.982: JS LOG: [LookingGlass/info] Loaded extension transparent-panels@germanfr in 2 ms
Gjs-Message: 14:53:02.983: JS LOG: [LookingGlass/info] Loaded extension transparent-panels@germanfr in 1 ms
Gjs-Message: 14:53:02.999: JS LOG: [LookingGlass/info] Loaded applet user@cinnamon.org in 15 ms
Gjs-Message: 14:53:03.000: JS LOG: [LookingGlass/info] Loaded extension transparent-panels@germanfr in 1 ms
Gjs-Message: 14:53:03.027: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 27 ms
Gjs-Message: 14:53:03.072: JS LOG: [LookingGlass/info] Loaded applet sessionManager@scollins in 45 ms
Gjs-Message: 14:53:03.139: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 67 ms
Gjs-Message: 14:53:03.148: JS LOG: [LookingGlass/info] Role locked: notifications
Gjs-Message: 14:53:03.155: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 16 ms
Gjs-Message: 14:53:03.155: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 0 ms
Gjs-Message: 14:53:03.170: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 15 ms
Gjs-Message: 14:53:03.177: JS LOG: calendar@cinnamon.org: Calendar events supported.
Gjs-Message: 14:53:03.184: JS LOG: calendar@cinnamon.org: Calendar events supported.
Gjs-Message: 14:53:03.191: JS LOG: [LookingGlass/warning] 
QRedshift: Created
Gjs-Message: 14:53:03.193: JS LOG: [LookingGlass/warning] 
QRedshift: ~/.config/redshift.conf should be removed
Gjs-Message: 14:53:03.217: JS LOG: [LookingGlass/warning] 
QRedshift: ADDED TO PANEL
Gjs-Message: 14:53:03.218: JS LOG: [LookingGlass/info] Loaded applet qredshift@quintao in 48 ms
Gjs-Message: 14:53:03.227: JS LOG: [LookingGlass/info] Role locked: panellauncher
Gjs-Message: 14:53:03.227: JS LOG: [LookingGlass/info] Role locked: windowattentionhandler
Gjs-Message: 14:53:03.232: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 14 ms
Gjs-Message: 14:53:03.246: JS LOG: [LookingGlass/info] Loaded extension Flipper@connerdev in 13 ms
Gjs-Message: 14:53:03.246: JS LOG: [LookingGlass/info] ExtensionSystem started in 477 ms
Gjs-Message: 14:53:03.255: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: nvidia-prime (:1.52/org/x/StatusIcon/Icon)
Gjs-Message: 14:53:03.265: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: nm-applet (:1.48/org/x/StatusIcon/Icon)
Gjs-Message: 14:53:03.268: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintUpdate.py (:1.473/org/x/StatusIcon/Icon)
Gjs-Message: 14:53:03.298: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 52 ms
Gjs-Message: 14:53:03.298: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: chrome_status_icon_1 (:1.43/org/x/StatusIcon/Icon)
Gjs-Message: 14:53:03.300: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: slack1 (:1.43/org/x/StatusIcon/Icon_1)
Gjs-Message: 14:53:03.303: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintreport (:1.85/org/x/StatusIcon/Icon)
Gjs-Message: 14:53:03.305: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: process-monitor (:1.85/org/x/StatusIcon/Icon_1)
Gjs-Message: 14:53:03.425: JS LOG: [LookingGlass/info] Hiding XAppStatusIcon (we have an applet): nm-applet (:1.48/org/x/StatusIcon/Icon)
Gjs-Message: 14:53:03.432: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 134 ms
Gjs-Message: 14:53:03.569: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 137 ms
Gjs-Message: 14:53:03.569: JS LOG: [LookingGlass/info] AppletManager started in 808 ms
Gjs-Message: 14:53:03.573: JS LOG: [LookingGlass/info] Cinnamon took 1184 ms to start
Gjs-Message: 14:53:03.588: JS LOG: Unknown network device type, is 14
Gjs-Message: 14:53:03.591: JS LOG: Unknown network device type, is 13
Gjs-Message: 14:53:03.592: JS LOG: Unknown network device type, is 13

(cinnamon:56961): St-WARNING **: 14:53:03.681: Ignoring length property that isn't a number at line 1278, col 11

(cinnamon:56961): St-WARNING **: 14:53:03.934: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:03.934: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:03.935: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:03.935: parse_shadow_property: default case
Window manager warning: calendar-open-36 - Overwriting existing binding of keysym 63 with keysym 63 (keycode 36).
Window manager warning: overlay-key-13 - Overwriting existing binding of keysym ffeb with keysym ffeb (keycode 85).
Window manager warning: launch-app-key-7 - Overwriting existing binding of keysym 37 with keysym 60 (keycode 10).
Gjs-Message: 14:53:06.633: JS LOG: Enabling WindowAttentionHandler

(cinnamon:56961): St-WARNING **: 14:53:17.430: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:17.430: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:17.430: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:17.430: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:17.430: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:17.430: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:17.430: parse_shadow_property: default case

(cinnamon:56961): St-WARNING **: 14:53:17.430: parse_shadow_property: default case

(cinnamon:56961): Clutter-CRITICAL **: 14:54:22.169: clutter_actor_get_allocation_box: assertion 'CLUTTER_IS_ACTOR (self)' failed
**
Clutter:ERROR:../clutter/clutter/clutter-actor.c:1419:clutter_actor_set_mapped: assertion failed: (CLUTTER_ACTOR_IS_MAPPED (self))
Impossible d'ouvrir le fichier de bureau /usr/share/applications/caja-browser.desktop pour le lanceur du tableau de bord: Aucun fichier ou dossier de ce type
Impossible d'ouvrir le fichier de bureau /usr/share/applications/mate-terminal.desktop pour le lanceur du tableau de bord: Aucun fichier ou dossier de ce type
mutter-Message: 14:54:46.349: Enabling experimental feature 'x11-randr-fractional-scaling'
Gjs-Message: 14:54:46.602: Profiler is disabled. Not setting up signals.
Gjs-Message: 14:54:46.779: JS LOG: About to start Cinnamon
Gjs-Message: 14:54:46.814: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 32 ms

```

**Comment by mcarans** [comment] 2022-08-21 23:17
@mtwebster I isntalled the Cinnamon and muffin updates that showed in my update manager a few hours ago, but I'm still seeing crashes that mention clutter:

```
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x8a00050
Window manager warning: WM_TRANSIENT_FOR window 0x8a011e7 for 0x8a011f9 window override-redirect is an override-redirect window and this is not correct according to the standard, so we'll fallback to the first non-override-redirect window 0x8a00050.
Window manager warning: WM_TRANSIENT_FOR window 0x8a01200 for 0x8a01207 window override-redirect is an override-redirect window and this is not correct according to the standard, so we'll fallback to the first non-override-redirect window 0x8a00050.

(cinnamon:13108): Clutter-CRITICAL **: 11:13:10.129: clutter_actor_set_mapped: assertion '!CLUTTER_ACTOR_IN_MAP_UNMAP (self)' failed
**
Clutter:ERROR:../clutter/clutter/clutter-actor.c:2181:clutter_actor_real_unrealize: assertion failed: (!CLUTTER_ACTOR_IS_MAPPED (self))
Unable to open desktop file /usr/share/applications/caja-browser.desktop for panel launcher: No such file or directory
Unable to open desktop file /usr/share/applications/mate-terminal.desktop for panel launcher: No such file or directory
```

**Comment by mtwebster** [comment] 2022-08-21 23:36
Does this happen every time you click on a preview?

Can you try removing your 3rd party menu (cinnamenu) temporarily, then restarting Cinnamon (alt-f2, r, enter).

Also, would you mind creating a new user account and trying to reproduce this there?

Thanks

**Comment by mcarans** [comment] 2022-08-22 02:39
@mtwebster No, it happens irregularly. I tried removing cinnamenu and restarting Cinnamon, but the problem remains.

I'll try creating a new user account later and get back to you.

**Comment by Siphalor** [comment] 2022-08-23 07:07
Hi, I can also reproduce this, in fact it's hard to do anything without getting Cinnamon crashes every few times when trying to switch windows.
I can safely reproduce it in like ten seconds by quickly clicking minimizing and un-minimizing multiple windows.
I don't have to click the preview window, this crash also happens for me when clicking the icon directly.

The relevant part of the `.xsession-errors`:‌ https://hastebin.com/pufutuhofu
(The actual file is multiple megabytes in size and totally spammed with that `assertion 'G_IS_DBUS_PROXY (proxy)' failed` assertion, but that's probably another story).

The crash doesn't happen in fallback mode, but I can safely reproduce it with all extensions and applets disabled (using the checkbox after a cinnamon crash).

<details>
<summary>System info (trimmed)</summary>

```
System:
  Kernel: 5.15.0-46-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: Cinnamon 5.4.11
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: LENOVO product: 20LAS01H00 v: ThinkPad T580 serial: <superuser required>
    Chassis: type: 10 serial: <superuser required>
  Mobo: LENOVO model: 20LAS01H00 serial: <superuser required> UEFI: LENOVO v: N27ET46W (1.32 )
    date: 05/18/2022
CPU:
  Info: quad core model: Intel Core i7-8550U bits: 64 type: MT MCP arch: Coffee Lake rev: A cache:
    L1: 256 KiB L2: 1024 KiB L3: 8 MiB
  Speed (MHz): avg: 797 high: 800 min/max: 400/4000 cores: 1: 800 2: 792 3: 800 4: 800 5: 795
    6: 793 7: 799 8: 800 bogomips: 31999
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel UHD Graphics 620 vendor: Lenovo driver: i915 v: kernel ports:
    active: HDMI-A-2,eDP-1 empty: DP-1,DP-2,HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:5917
  Device-2: NVIDIA GP108M [GeForce MX150] vendor: Lenovo driver: N/A pcie: speed: 8 GT/s
    lanes: 4 bus-ID: 02:00.0 chip-ID: 10de:1d10
  Device-3: IMC Networks Integrated Camera type: USB driver: uvcvideo bus-ID: 1-8:5
    chip-ID: 13d3:56a6
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting unloaded: vesa
    alternate: fbdev gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x1080 s-dpi: 96
  Monitor-1: HDMI-2 mapped: HDMI-A-2 pos: right model: Samsung res: 1920x1080 dpi: 305
    diag: 551mm (21.7")
  Monitor-2: eDP-1 pos: primary,left model: BOE Display res: 1920x1080 dpi: 141
    diag: 396mm (15.6")
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 22.0.5 direct render: Yes
Drives:
  Local Storage: total: 953.88 GiB used: 721.78 GiB (75.7%)
  ID-1: /dev/nvme0n1 vendor: Western Digital model: PC SN520 SDAPMUW-512G size: 476.94 GiB
    speed: 15.8 Gb/s lanes: 2 serial: <filter> temp: 39.9 C
  ID-2: /dev/nvme1n1 vendor: Samsung model: MZVLB512HAJQ-000L7 size: 476.94 GiB speed: 31.6 Gb/s
    lanes: 4 serial: <filter> temp: 28.9 C
Partition:
  ID-1: / size: 194.94 GiB used: 177.42 GiB (91.0%) fs: ext4 dev: /dev/nvme1n1p7
  ID-2: /boot/efi size: 95 MiB used: 39.3 MiB (41.4%) fs: vfat dev: /dev/nvme1n1p2
Swap:
  ID-1: swap-1 type: file size: 7.45 GiB used: 1.62 GiB (21.7%) priority: -2 file: /swapfile
Info:
  Processes: 381 Uptime: 21h 49m Memory: 15.49 GiB used: 6.13 GiB (39.6%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.2.0 alt: 11/9 clang: 14.0.0-1ubuntu1 Client: Cinnamon v: 5.4.11
  inxi: 3.3.13
```

</details>

### Other Information

I, too, upgraded from Mint 20.3 to Mint 21.
I'm using the Grouped Window List, if that's of any relevance.

**Comment by mcarans** [comment] 2022-08-23 08:15
@mtwebster With a new user account, the problem does not occur.

**Comment by mtwebster** [comment] 2022-08-23 12:55
Interesting - can you guys provide me with your Cinnamon settings?
```
dconf dump /org/cinnamon/ > settings.txt
```
and the applet, you can do this in the applet's settings, click the hamburger button in the upper right corner  (3 horizontal bars) and export to a file.

Are you using 3rd-party Cinnamon themes? If so, can you try with a Mint-X/Y or with the default Cinnamon theme?

Also, as a potential workaround, CobiWindowList (windowlist@cobinja.de) has much of the same functionality as the grouped window list.

@Siphalor if you'd like, you can open an issue here: https://github.com/linuxmint/cinnamon-settings-daemon regarding the csd-power warnings, and attach the .xsession-errors file (especially the beginning of the file, until those messages start). I can give you some furthere troubleshooting suggestions there.

**Comment by Siphalor** [comment] 2022-08-23 15:08
Ok, I tried some of your suggestions out (chronologically in the order that I tried them):

- I usually use Mint-Y and tried switching to Mint-X - no success
- As you suggested I switched from the default Grouped Window List to CobiWindowList. I couldn't reproduce the issue in a couple of minutes clicking around.
- I switched back to Grouped Window List and undertook the same procedure. Now it seemed to work too.

I was a bit frustrated at this point because I forgot to export the applet configuration first.

Just as I wanted to comment on this PR with my findings I got the idea to check the configuration, to see if I could spot any differences to my previous configuration.
To my surprise I quickly found the culprit!

The option `Thumbnails > Sort thumbnails according to the last focused windows` (`show-thumbnails` in the JSON) causes this crash!
Turning this back on allowed me to easily reproduce the issue.
Although not really necessary anymore, here's the broken config:‌ https://hastebin.com/huyiwarupi.json

So the workaround for now is to just turn that option off.

---

I'll create an issue over there :+1:

**Comment by mcarans** [comment] 2022-08-23 19:51
I also had the Sort thumbnails setting on. I will try the Sort thumbnails setting off for a while to see if it helps for me.

**Comment by nalmada** [comment] 2022-08-23 19:56
For me disabling thumbnails altogether worked for the past day

Enabling thumbnails but disabling sorting seems to work for the past hour

**Comment by mcarans** [comment] 2022-08-24 02:44
@mtwebster The issue seems to be the one @Siphalor identified with `Thumbnails > Sort thumbnails according to the last focused windows`. I haven't had a crash since turning that off. Should I raise an issue somewhere against the Grouped Window List applet or is this issue sufficient?

**Comment by mtwebster** [comment] 2022-08-24 03:27
No, this is the correct place. There's also some overlap with https://github.com/linuxmint/cinnamon/issues/11016, but I can reproduce this now so I should have it fixed soon.

Thanks

**Comment by mtwebster** [comment] 2022-08-24 23:20
Fixed by https://github.com/linuxmint/cinnamon/commit/de39163f21ef74383c8aea7697e842a2961f6592

**Closed by mtwebster** 2022-08-24 23:20 UTC
