### ISSUE TITLE
Add an applet to panel using Terminal

### ISSUE THREAD

**Issue by blueray453** [linuxmint/cinnamon#10904] opened 2022-07-06 11:46 UTC
```
 * csd version (5.2.0+una)
 * Distribution - Linux Mint 20.3 Una
 * 64 bit
 ```

**Issue**

In Gnome we can enable applet with

    busctl --user call org.gnome.Shell.Extensions /org/gnome/Shell/Extensions org.gnome.Shell.Extensions InstallRemoteExtension s APPLET_UUID

I was trying find similar solution. But what I found was:

run `gsettings get org.cinnamon enabled-applets` after adding and rearranging applets in the panel.

Then I use `gsettings set org.cinnamon enabled-applets "THAT-SPECIAL-STRING"` when I am running this on new machines.

This is not a good solution for few reasons.

1. When adding applet it does not only change `enabled-applets` but also few more keys.
2. The process is complex. To get the `enabled-applets` value, I have to go through the whole GUI steps. If anything change then I have to do it again.

**Expected behaviour**

Would be great to have a command something like:

    cinnamon-settings add panel1 APPLET_UUID

or a `busctl` or `dbus-send` command

**Other information**

https://forums.linuxmint.com/viewtopic.php?p=2196936

**Comment by leigh123linux** [comment] 2022-07-06 12:38
Duplicate of https://github.com/linuxmint/cinnamon/issues/10904

**Comment by mtwebster** [comment] 2022-07-06 12:45
This is a really niche feature and probably not one we'll pursue:

- For a majority of users, adding applets is not a frequent activity, so they wouldn't typically have a need to be able to script or perform bulk actions on extensions
- For the use case of being able to pre-configure multiple machines, there is already a method to accomplish this.

First, configure your prototypical desktop exactly how you want it.
2) Export your dconf entries for cinnamon (this is the backend for these settings)
```
dconf dump /org/cinnamon/ > defaults
```
This exports a text file, listing any settings that have been set to something other than their default values. For example:
```
[/]
command-history=['r']
enabled-applets=['panel1:left:0:menu@cinnamon.org:0', 'panel1:left:1:show-desktop@cinnamon.org:1', 'panel1:left:2:grouped-window-list@cinnamon.org:2', 'panel1:right:1:systray@cinnamon.org:3', 'panel1:right:2:xapp-status@cinnamon.org:4', 'panel1:right:3:notifications@cinnamon.org:5', 'panel1:right:4:printers@cinnamon.org:6', 'panel1:right:5:removable-drives@cinnamon.org:7', 'panel1:right:6:keyboard@cinnamon.org:8', 'panel1:right:7:favorites@cinnamon.org:9', 'panel1:right:9:sound@cinnamon.org:11', 'panel1:right:10:power@cinnamon.org:12', 'panel1:right:11:calendar@cinnamon.org:13', 'panel1:right:0:xrandr@cinnamon.org:14']
looking-glass-history=['global.segfault()', 'r(0).hover']
next-applet-id=15
...
...
[desktop/peripherals/mouse]
accel-profile='adaptive'
double-click=450
drag-threshold=8
left-handed=true
middle-click-emulation=false
speed=0.47478991596638664
...
...
```
You can edit that file and remove any entries you may have changed that you don't wish transferred to another machine - if you're left-handed maybe you changed that setting while configuring this machine, etc...

Then, on the machine(s) you're setting up,
```
dconf load /org/cinnamon/ < defaults
```

**Closed by mtwebster** 2022-07-06 12:45 UTC
