### ISSUE TITLE
Text cursor/focus is lost from text boxes when Control/Ctrl key is pressed due to mouse configuration

### ISSUE THREAD

**Issue by berbaba** [linuxmint/cinnamon#10322] opened 2021-09-15 22:33 UTC
```
 * Cinnamon version 4.8.6
   - Not using (I think)  the daily builds PPA
 * Distribution - Linux Mint 20.1 Cinnamon
 * GeForce 840M xserver-xorg-video-noveau
 * 64 bit

 ```

**Issue**
The text selection when writing in text boxes is lost when the CTRL key is pressed if the mouse option "Show pointer/mouse position when Control key is pressed" is enabled.  If one wants to press the CTRL key to copy or paste some text, the writing focus is lost and the only way to cut/copy/paste is with the mouse secondary button (or the open contextual menu key).

**Steps to reproduce**
Go to settings > Mouse settings > Enable "Show pointer/mouse position when Control key is pressed"
Some examples would be:
*  in the URL box in the browser 
*  when changing a file name in file explorer (just with List View)
* browser text boxes from websites or apps like Jupyter Notebook, or this very same text box I'm using right now (the blue rectangle surrounding the text box will turn off and the cursor will disappear).

There were more situations when this happens but these are the ones that I remember and can be reproduced.
From reading another bug I tried the website [Javascript Key Event Test Script](https://unixpapa.com/js/testkey.html) and one can see that the behaviour is not the expected.

**Expected behaviour**
Inability to perform actions over selected text that require the Control key. Background colour may change due to change of focus over the text box.

**Other information**
It can be easily avoided disabling that mouse configuration, but to anyone unaware of this it will be not a major problem but quite annoying and not obvious how to manage it as it doesn't generate any error messages. Might  be related to Issue #5518

**Comment by mtwebster** [comment] 2021-09-16 16:12
I can't reproduce this - focus doesn't change when I use the locate-pointer feature
![Peek 2021-09-16 12-02](https://user-images.githubusercontent.com/262776/133646786-8025bdd8-a985-4619-99c8-25c11a897178.gif)

Unable to reproduce in a virtual machine either. Am I misunderstanding the steps to reproduce

**Comment by berbaba** [comment] 2021-09-19 18:55
That's the mouse feature I was talking about. I don't know then what could be the difference.

The really annoying issue is to try to copy/paste/cut a file/folder name in the file explorer while on list view and also trying to do the same with the folder path (action that I forgot to record). In any case I wanted at least to report the bug in case someone else is struggling with this and couldn't find the cause so they see how to avoid it.

![simplescreenrecorder-2021-09-19_20 38 14](https://user-images.githubusercontent.com/19535577/133939207-b414be78-3a4d-47e8-a68b-2fe590136968.gif)
.

**Comment by leigh123linux** [comment] 2024-05-09 11:41
Duplicate of 11171

**Closed by leigh123linux** 2024-05-09 11:41 UTC

**Comment by DirkHaar** [comment] 2024-05-09 12:13
Shouldn't this one have been kept open (due to lower number and additional info, e.g. videos?
I'll add some info to my #11171 .

**Comment by leigh123linux** [comment] 2024-05-09 12:26
> Shouldn't this one have been kept open (due to lower number and additional info, e.g. videos? I'll add some info to my #11171 .

It's an older version, does the issue reproduce in a supported version (6.0.x)?

**Comment by DirkHaar** [comment] 2024-05-13 19:46
Yes, 6.0.4 shows the same behavior. In the symbol and compact view, this problem does not occur.
