### ISSUE TITLE
restarting cinnamon moves all windows up

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/cinnamon#7507] opened 2018-04-25 12:07 UTC
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.6.7

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Fedora 27

 * Graphics hardware *and* driver used
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
i915

 * 32 or 64 bit
64 bit
```

**Issue**
When I restart cinnamon with _ALT-F2->r_, all of the windows on the screen are moved up about the height of the titlebar of the window decoration.

**Steps to reproduce**
Start Cinnamon desktop.
Press _ALT-F2_
Enter _r_ into the input box and hit enter.
Wait while Cinnamon restarts.
Observe that all windows have been moved up the screen, about the same height as the window decorator's title-bar height.

**Expected behaviour**
Windows should stay where they were before the restart.

**Other information**

**Comment by icarter09** [comment] 2019-11-16 17:50
Linux Mint 19.2
Cinnamon 4.2.4

@brianjmurrell are you still experiencing this issue? I'm not able to reproduce this issue.

**Comment by claudiux** [comment] 2019-11-16 21:50
@icarter09 This bug is still present. Linux Mint 19.2. Cinnamon 4.2.4

![vokoscreen-2019-11-16_22-41-54](https://user-images.githubusercontent.com/33965039/68999588-af8aac80-08c2-11ea-855b-a083fa03002f.gif)

I dragged the Firefox window (the bottom of this window becomes not appearing). Then Alt-F2 r.

**Comment by Vahan86** [comment] 2020-01-28 09:26
@icarter09, can we mark this issue as a bug?

**Comment by claudiux** [comment] 2020-01-28 10:05
This bug is still present in Cinnamon 4.4.8 (Mint 19.3).

**Comment by JosephMcc** [comment] 2020-01-28 17:40
This is fixed in git master.

**Closed by JosephMcc** 2020-01-28 17:40 UTC
Labels: BUG, BUG REPRODUCED
